### ISSUE TITLE
6.3.5 WMS Import:Support GetLegend getAbstract for external wms

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#1041]
All OS all Browser

if for an external wms a GetLegend is available, the add the i button in the seection window and open with i button among the legend as well he abstract 
http://map.geo.gr.ch/geo_viewer/geo_viewer.phtml?mapfile=wms/gewaesserschutz.map&url=wms.geo.gr.ch/gewaesserschutz

**Comment by oterral** [comment]
Fixed [Test](https://mf-geoadmin3.dev.bgdi.ch/?dev3d=true&topic=geol&lang=fr&bgLayer=ch.swisstopo.pixelkarte-farbe&lon=6.94440&lat=47.01709&elevation=7145&heading=239.460&pitch=-16.188&catalogNodes=1786,1787&layers=ch.swisstopo.geologie-geocover,WMS%7C%7CTektonische%20Strukturen%7C%7Chttp:%2F%2Fwww.sogis1.so.ch%2Fcgi-bin%2Fsogis%2Fsogis_geologie.wms%7C%7Ctektonik&layers_opacity=0.75,1)
