### ISSUE TITLE
WMS & GetFeatureInfo

### ISSUE THREAD

**Issue by procrastinatio** [geoadmin/mf-geoadmin3#1148]
Tooltips and extern WMS layers (via heldpesk)

Via: http://openlayers.org/en/v3.2.1/examples/getfeatureinfo-image.html?q=GetFeature

[ ] and take care of legend as well #1041

**Comment by davidoesch** [comment]
might this be useful? https://github.com/openlayers/ol3/pull/3172 ?

**Comment by gjn** [comment]
This is actually done (legend).

**Comment by oterral** [comment]
Legend yes but tooltip no.

**Comment by davidoesch** [comment]
the tooltip is needed for EMAPIS - @p1d1d1

**Comment by procrastinatio** [comment]
If you do not have to much expectation on GetFeatureInfo display, response may be `text/plain`, `text\html`, `text/xml`, `application/vnd.ogc.gml`, usw.

**Comment by davidoesch** [comment]
text/plain is enough text/html already topnotch

**Comment by p1d1d1** [comment]
to confirm that we need tooltip on WMS for eMapis. But I see interest also for other users.
For me text/plain is enough.
Important is the multilingual support.

Displaying info as simple as possible: just a tuple label:value

**Comment by p1d1d1** [comment]
@gjn any update here?
