### ISSUE TITLE
Google Page Speed Insights analysis

### ISSUE THREAD

**Issue by twpayne** [geoadmin/mf-geoadmin3#1185]
https://developers.google.com/speed/pagespeed/insights/?url=http%3A%2F%2Fmap.geo.admin.ch%2F

Some indicate potential speed-ups, some are not relevant.

**Comment by ponceta** [comment]
Ty @twpayne 
Moved here https://github.com/geoadmin/mf-geoadmin3/wiki/Useful-Tips-Tricks-Ressources
