### ISSUE TITLE
Halo of text symbolizer is not printed

### ISSUE THREAD

**Issue by oterral** [geoadmin/mf-geoadmin3#1214]
Not available in the print server.

See https://github.com/mapfish/mapfish-print/issues/72

**Comment by procrastinatio** [comment]
No comment ?

**Comment by oterral** [comment]
Have you a test branch?

**Comment by ponceta** [comment]
![image](https://cloud.githubusercontent.com/assets/8614223/7082850/ac314ab2-df5a-11e4-8ab1-ba6dfb271fe8.png)

Solution found by one of our customers... :)

**Comment by oterral** [comment]
ahah nice , we could do better with a free hand mode.

**Comment by ponceta** [comment]
![image](https://cloud.githubusercontent.com/assets/8614223/7083379/670de326-df61-11e4-9cbf-fb1682bd0004.png)
Print v3 does not fix this

**Comment by procrastinatio** [comment]
Yes, Mapfish Print v3 does have halo:

![image](https://cloud.githubusercontent.com/assets/1236739/8130210/fdb525ba-1110-11e5-822c-349e7b034f97.png)

**Comment by procrastinatio** [comment]
won't fix within v2
