### ISSUE TITLE
LUBIS: Fullres Image manipulation

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#1350]
Most of the LUBIS Fullres imagery is over/or undersaturated
- -Would be nice tom manipulate contrast/brightness in the  fullress mode 
  according to http://ol3js.org/en/v3.7.0/examples/brightness-contrast.html 

IMHO it is worth even if its limited to webgl

regarding Icons: TBD if we go for an icon or text.....

**Comment by davidoesch** [comment]
One button autoenhance on /off . Nothing more. And it enhances the image as u zoom . And it is active on default . Actually no button needed at all -- we switch it on always.

**Comment by davidoesch** [comment]
Discussed this with dataowner of LUBIS
they give a go for this with

- One button autoenhance on /off . Nothing more. And it enhances the image as u zoom . And it is  *not * active on default (since this would be not the original image)

-no support of ie9-10 but if don't care we can switch the renderer used depending of the browser: is ok

**Comment by davidoesch** [comment]
@oterral status here? Is there an ETA?

**Comment by oterral** [comment]
@davidoesch  as you can see with the link which is in the summary of the issue.  OL3 has removed all the support of the contrast/brightness modification.

**Comment by oterral** [comment]
See https://github.com/openlayers/ol3/issues/4130

**Comment by oterral** [comment]
So it's probably still possible but we need to do more research.

**Comment by davidoesch** [comment]
boaa removing features ;-) nicely done ol. Now I know how our custoemrs feel when we remove features. keep it as enhancement. if there is  a solution by someone ale we adopt it

**Comment by oterral** [comment]
Maybe we can do something with http://openlayers.org/en/master/examples/color-manipulation.html

**Comment by davidoesch** [comment]
A test link with lightness only?

**Comment by davidoesch** [comment]
ping @oterral  ?

**Comment by oterral** [comment]
Not high priority.

**Comment by davidoesch** [comment]
But doable? Since it would add a nice function to the Most used Layer

**Comment by oterral** [comment]
yes I think we could.

**Comment by oterral** [comment]
Maybe something for @Ariadnigaki to begin with OpenLayers.  @gilbert ?

**Comment by gjn** [comment]
Will discuss it with here tomorrow. Might be a tad too complicated.

**Comment by oterral** [comment]
Not so difficult. It's only for this [viewer](https://api3.geo.admin.ch/luftbilder/viewer.html?lang=fr&width=8954&layer=ch.swisstopo.lubis-luftbilder_schwarzweiss&bildnummer=19531910013240&title=ch.swisstopo.lubis-luftbilder-dritte-kantone.ebkey&rotation=0&datenherr=swisstopo&height=9430&x=4477.00&y=4715.00&zoom=2)

**Comment by davidoesch** [comment]
one for @nadine-piveteau  ? oing @gjn

**Comment by oterral** [comment]
http://viglino.github.io/ol-ext/examples/map.filter.colorize.html

**Comment by davidoesch** [comment]
I like .
Just a simple slider from brighten to darken

**Comment by oterral** [comment]
http://viglino.github.io/ol-ext/examples/filter/map.filter.colorize.html

**Comment by nadine-piveteau** [comment]
Addressing issue [here](https://github.com/geoadmin/mf-chsdi3/pull/2874).
[Testlink](https://mf-chsdi3.dev.bgdi.ch/ltpin_lubis/luftbilder/viewer.html?lang=de&width=16574&layer=ch.swisstopo.lubis-luftbilder_farbe&bildnummer=20057120330698&title=ch.swisstopo.lubis-luftbilder-dritte-kantone.ebkey&rotation=0&datenherr=swisstopo&height=17001&x=9220.98&y=4156.53&zoom=3)

**Comment by nadine-piveteau** [comment]
I can add further filters if you want: https://www.w3schools.com/cssref/css3_pr_filter.asp

**Comment by davidoesch** [comment]
Try to establish a "auto histogram re equalization" . Only contrast. Reason; more then one slider/button will be to complicated for most users

**Comment by davidoesch** [comment]
BTW Does not work on iPhone chrome or safari. 
Use case: take black and white aerial image which is oversaturated.

**Comment by davidoesch** [comment]
Final layout.: Put the slider in the image itself. Centered bottom. Call it : enhance
