### ISSUE TITLE
Measure: possibility to resume measure drawing process

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#1481]
Situation
After the digitizing a measure item (profile area), result is shown: user would like to return to the finished  line/polygon
A) change some vertexes
B) add some vertexes/extent the line

-> in the draw menue we have this option with edit.

now it would be nice to have here the same option + adding vertexes in DRAW and MEASURE

my proposal

vertexes are always shown, in DRAW and MEASURE. Double click/touch'n'hold activates editing

**Comment by davidoesch** [comment]
@cedricmoullet for the UI session 4.6.2015

**Comment by oterral** [comment]
Fixed in prod
