### ISSUE TITLE
KML Import: support < GroundOverlay> 

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#1583]
Add KML support for < GroundOverlay> according to OGC: reprojection data on client side
-> This feature has to be implmented in OL3 directly
https://github.com/geoadmin/ol3/blob/master/src/ol/format/kmlformat.js

**Comment by cedricmoullet** [comment]
@elemoine Do you see the GroundOverlay support as a possible feature in OL3 ?

**Comment by davidoesch** [comment]
@elemoine status?

**Comment by oterral** [comment]
@davidoesch PR merged in ol3 https://github.com/openlayers/ol3/pull/4122

**Comment by davidoesch** [comment]
thanks this will solve requests like this https://groups.google.com/forum/#!searchin/geoadmin-api/overlay$20kml/geoadmin-api/StzvQzO-_-A/QHX2Bnte9Ok

**Comment by davidoesch** [comment]
Not yet solved imho

**Comment by oterral** [comment]
See https://github.com/openlayers/openlayers/issues/7255

**Comment by boecklic** [comment]
wontfix
