### ISSUE TITLE
ObjectSelectionwindow Print: Result window has stay open even when print closed

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#1599]
ALL OS ALL Browsers

- open http://s.geo.admin.ch/6bea3109c
- select by rectangle:
- in the object info window result click print
- print opens
- when closing the printer window

Result:
- print content dissapears

expected result;
- print content stays available, os user can copy paste the text
![unbenannt](https://cloud.githubusercontent.com/assets/4577727/4007785/8fec01b6-29cb-11e4-9203-1ce5bf055c79.PNG)

**Comment by cedricmoullet** [comment]
The print use case seems correct to me: if someone wants to print, he wants to print. 
For CSV, we'll have a second function: "Export CSV" -> then the user can download the file. 
So, for me, this is not an issue.

**Comment by davidoesch** [comment]
..it was like this in RE2  (ok ok things can change...)

**Comment by cedricmoullet** [comment]
right, it was like that in RE2....
