### ISSUE TITLE
[DEV APPCACHE] offline clientzoom fails

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#1606]
reproduce

1) save this perimeter offline http://mf-geoadmin3.dev.bgdi.ch/dev_appcache/?X=197896.86&Y=648843.25&zoom=9&lang=de&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.hiks-dufour,ch.kantone.cadastralwebmap-farbe&layers_visibility=false,true

2) go offline

3) zoom in to zoom=10

4) pan to the left/up/down keeping the zoom level 10

Result: 
a green area will be encoutered 
![unbenannt](https://cloud.githubusercontent.com/assets/4577727/4011000/502c960c-29fe-11e4-8e0d-6437d2066c83.PNG)

client zoom will not  work

Expected result:

client zoom works when entering an area which is not yet loaded

Workaround:
-Zoom out on the green area and then zoom in again-> client zoom works

**Comment by oterral** [comment]
Just discover the preload attribute on tilelayer.

Seems to fix this issue: http://mf-geoadmin3.dev.bgdi.ch/teo_fix_1606

**Comment by oterral** [comment]
I'm making some tests to see if there is performance issue on slow device.
