### ISSUE TITLE
PRINT: swiss vertical swisscordinates are not printed

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#1628]
printing swiss coordinates grid eg http://map.geo.admin.ch/?X=204204.00&Y=647326.50&zoom=8&lang=en&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe 
for scale 1:25K -1:500
- Vertical ans horiizontal spacing are to big
- for 1:20K-1:500: vertical grid line is not annotated

pls assign ticket

**Comment by cedricmoullet** [comment]
@procrastinatio what is the status here ?

**Comment by procrastinatio** [comment]
Sorry es gibt immer mehr als nur *zwei* Linie pro Blatt, und zwar eher viel mehr...

**OK**
![ok](https://cloud.githubusercontent.com/assets/1236739/5663327/bee8d4e8-9745-11e4-87f8-ff8b2f71f772.jpeg)

**Not OK** Why ?
![nok](https://cloud.githubusercontent.com/assets/1236739/5663330/c5c09e2c-9745-11e4-84fd-025512710e2d.jpeg)

**Comment by davidoesch** [comment]
now it is fixed..thanks! I completed the testbook

**Comment by davidoesch** [comment]
please megre and close @procrastinatio
