### ISSUE TITLE
[TESTING] Browserstack - Selenium / Dev ideas - Brainstorming

### ISSUE THREAD

**Issue by ponceta** [geoadmin/mf-geoadmin3#1644]
@kandre 

just reminder for what we saw and hot ideas:
 -  Update Browser list
 -  Extent to mobile browsers (Different test file)
 -  Search for wmts requests (tiles)
 -  Mouse interactions (scrolling / selecting / right clicking)
 -  Code test script to resume errors on all browsers (not only on the first crash)

and reminder of what is already there:
 -  basic script with of not all actual browsers
 -  timelapse of 0.5 sec due to webdriver (see doc webdriver on npmjs.org)
 -  max 20 sec testing time
 -  screen resolution is high enough to have menu deployed
 -  jenkins test basic script every night
 -  browsers are starting with no cache
 -  only mf-geoadmin is tested

**Comment by gjn** [comment]
@ponceta Still needs this for reference? If yes, maybe put into wiki? So we could close this.

**Comment by ponceta** [comment]
I'll migrate it
