### ISSUE TITLE
Add WMTS Support in Import

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#1654]
Adapt the "WMS import" to fulfill "WM(T)S import"

We use the same interface as here
http://help.geo.admin.ch/?id=63&lang=en 

Read the WMTS GetCap etc...

A test WMTS: http://t.co/hUH1yINUJO

**Comment by davidoesch** [comment]
https://github.com/openlayers/ol3/pull/3026 ?

**Comment by davidoesch** [comment]
one for @oterral

**Comment by cedricmoullet** [comment]
@davidoesch Could you provide a list of servers ?

**Comment by davidoesch** [comment]
as start we have http://www.gis.stadt-zuerich.ch/wmts/wmts-zh-stzh-ogd.xml
-- once we are up with this one we will make a call to public --- makes
sense?

**Comment by cedricmoullet** [comment]
only one ? Does it really make sense ? (80/20)

2015-03-12 9:22 GMT+01:00 davidoesch <notifications@github.com>:

> as start we have http://www.gis.stadt-zuerich.ch/wmts/wmts-zh-stzh-ogd.xml
> -- once we are up with this one we will make a call to public --- makes
> sense?
>
> On Thu, Mar 12, 2015 at 5:01 AM, Cédric Moullet <notifications@github.com>
> wrote:
>
> > @davidoesch <https://github.com/davidoesch> Could you provide a list of
> > servers ?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/geoadmin/mf-geoadmin3/issues/1654#issuecomment-78420299
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geoadmin/mf-geoadmin3/issues/1654#issuecomment-78439684>
> .
>



-- 
Twitter: http://twitter.com/cedricmoullet
Linked In: http://www.linkedin.com/in/cedricmoullet

<http://twitter.com/cedricmoullet>

**Comment by davidoesch** [comment]
http://www.catais.org/mapcache/wmts/1.0.0/WMTSCapabilities.xml
http://www.catais.org/mapcache/wmts?service=wmts&request=getcapabilities&version=1.0.0

**Comment by gjn** [comment]
Would it make sense to integrate this into wms import? The list would contain all external resourses, the user selects one but he does not need to care/know what kind it is.

**Comment by cedricmoullet** [comment]
+1 and we have to put our WMTS

2015-03-12 14:08 GMT+01:00 Gilbert Jeiziner <notifications@github.com>:

> Would it make sense to integrate this into wms import? The list would
> contain all external resourses, the user selects one but he does not need
> to care/know what kind it is.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geoadmin/mf-geoadmin3/issues/1654#issuecomment-78475763>
> .
>



-- 
Twitter: http://twitter.com/cedricmoullet
Linked In: http://www.linkedin.com/in/cedricmoullet

<http://twitter.com/cedricmoullet>

**Comment by davidoesch** [comment]
as proposed before: we make one "Import" and in the modal window 2 tabs KML
and WM(T)S

**Comment by cedricmoullet** [comment]
Then 3 tabs: WMS, WMTS and KML

2015-03-12 14:28 GMT+01:00 davidoesch <notifications@github.com>:

> as proposed before: we make one "Import" and in the modal window 2 tabs KML
> and WM(T)S
>
> On Thu, Mar 12, 2015 at 2:10 PM, Cédric Moullet <notifications@github.com>
> wrote:
>
> > +1 and we have to put our WMTS
> >
> >
> > 2015-03-12 14:08 GMT+01:00 Gilbert Jeiziner <notifications@github.com>:
> >
> > > Would it make sense to integrate this into wms import? The list would
> > > contain all external resourses, the user selects one but he does not
> need
> > > to care/know what kind it is.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/geoadmin/mf-geoadmin3/issues/1654#issuecomment-78475763
> > >
> > > .
> > >
> >
> >
> >
> > --
> > Twitter: http://twitter.com/cedricmoullet
> > Linked In: http://www.linkedin.com/in/cedricmoullet
> >
> > <http://twitter.com/cedricmoullet>
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/geoadmin/mf-geoadmin3/issues/1654#issuecomment-78475945
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geoadmin/mf-geoadmin3/issues/1654#issuecomment-78478791>
> .
>



-- 
Twitter: http://twitter.com/cedricmoullet
Linked In: http://www.linkedin.com/in/cedricmoullet

<http://twitter.com/cedricmoullet>

**Comment by gjn** [comment]
No need to separate WMS/WMTS. User does not care about the difference and UI can be exactly the same.

**Comment by cedricmoullet** [comment]
right

2015-03-12 14:40 GMT+01:00 Gilbert Jeiziner <notifications@github.com>:

> No need to separate WMS/WMTS. User does not care about the difference and
> UI can be exactly the same.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geoadmin/mf-geoadmin3/issues/1654#issuecomment-78480840>
> .
>



-- 
Twitter: http://twitter.com/cedricmoullet
Linked In: http://www.linkedin.com/in/cedricmoullet

<http://twitter.com/cedricmoullet>

**Comment by davidoesch** [comment]
all what we hae to do for now is just
- add the WMTS sources above
-read WMTS GEt cap
- change Translation table from "WMS Import" to "WM(T)S Import"

**Comment by oterral** [comment]
Duplicate with https://github.com/geoadmin/mf-geoadmin3/issues/2414
