### ISSUE TITLE
[aviation] add query function for ch.bazl.luftfahrthindernis

### ISSUE THREAD

**Issue by mariokeusen** [geoadmin/mf-geoadmin3#1801]
UC: ch.bazl.luftfahrthindernis needs to be queried link in map.bazl.admin.ch
Solution proposal: build up a generic query function for mf-geoadmin3 basing on the select-by-rectangle function, in order to fulfil (also) the BAZL-requirements

Discussion with customer if and how the current function can be simplified is ongoing...
Next step: discussion and definition of the further steps

**Comment by oterral** [comment]
Done in prod
