### ISSUE TITLE
Add slope parameter in profile tootip

### ISSUE THREAD

**Issue by kandre** [geoadmin/mf-geoadmin3#1840]
Add a slope parameter in the profile tootip (the black one). The value shown should be clearly given with a message like 'approximative slope' to not take any responsibility with this computation.

![slope description](https://cloud.githubusercontent.com/assets/8038575/4939328/2af65692-65d2-11e4-86e2-13e4e2d6b632.jpg)

**Comment by davidoesch** [comment]
algorithm to calculate slopes has to be disccused with topo : it has to be made sure that same algortihm is used...same results

**Comment by ponceta** [comment]
Duplicate with #1912

**Comment by davidoesch** [comment]
a nice feature request-- was never done in #1912

**Comment by davidoesch** [comment]
@pakb while on #1912 #3483 : have a look as well  on : print profile
