### ISSUE TITLE
 "Zolliker Strasse“ has to find „Zollikerstrasse“

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#1860]
as described in https://github.com/geoadmin/service-sphinxsearch/issues/4 

use case: "Zolliker Strasse“ has to find „Zollikerstrasse“

    issue is 50 results limit: Zollikerstrasse appears but later in the list

to be analyzed (and this needs a major change)

if a road without streetname (zolliker strasse) is searched, display the roadnames (1st entry) of each commune instead of all roads of the first commune, and use display fuzzy search before listing other data like places etc

**Comment by ponceta** [comment]
Yes

**Comment by ponceta** [comment]
But it is useless to add it in the wordforms (it won't change anything)!

`Zolliker Strasse` links to Zolliker Strasse in Zollikon
`Zollikerstrasse` links to Zollikerstrasse in Zürich
`Zolliker Strasse zu` links to Zollikerstrasse in Zürich

So it works as designed except if you wan't better results for Zürich but that's not very "Bund-like"

The improvement I see could be to find die Zolliker Strasse in Zollikon from
`zollikerstrasse Zollikon` which actually links to Zwillikerstrasse in Zwillikon (from soundex and metaphones scores) but I did not find any hints actually to solve this kind of issue!

**Comment by ponceta** [comment]
Duplicated with #2170
