### ISSUE TITLE
Zeitreihe: error on loading with 2 timestamps on mobile ios

### ISSUE THREAD

**Issue by cedricmoullet** [geoadmin/mf-geoadmin3#1890]
http://map.geo.admin.ch/?X=138521.30&Y=644878.38&zoom=6&lang=fr&topic=ech&bgLayer=voidLayer&layers_timestamp=20121231,19001231&swipe_ratio=0.54&layers=ch.swisstopo.zeitreihen,ch.swisstopo.zeitreihen

**Comment by cedricmoullet** [comment]
@kandre @pfanguin ?

**Comment by kandre** [comment]
I ve tested on iphone, I got no error

**Comment by ponceta** [comment]
Works great on iPad Mini. Very impressive!
