### ISSUE TITLE
Time behaviour: vector

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#1905]
all os all browser

http://map.geo.admin.ch/?X=190000.00&Y=660000.00&zoom=1&lang=en&topic=swisstopo&bgLayer=ch.swisstopo.pixelkarte-farbe&catalogNodes=1392&layers_timestamp=99991231&layers=ch.swisstopo.lubis-luftbilder_schwarzweiss

activate aerial images b/w
enable time eicon
then select a year  from layer selection
deactivate time over time button
result
in the selectin window and in map we have the last selected year

expected result
all years are selected

**Comment by davidoesch** [comment]
Here it's the very special use case where there is only one layer, maybe we shouldn't activate time selector button when only one timeenabled layer is displayed


Makes sense

**Comment by oterral** [comment]
I don't know,  the slider is more user friendly.

**Comment by davidoesch** [comment]
@cedricmoullet ?
