### ISSUE TITLE
[fuzzysearch] Result improvement 

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#1910]
Situation 

if  the exact term is not found in the swisssearch (Eg "Zuerich")
ther result returns, based on the fuzzy parameters "zürich"

expected result
as in Google search a proposal

After listing the exact results
start the fuzzy results the search results listing with an entry:
"did you mean: "
"Zürich"

Result:
the user is informed that this is a guess ( BTW, the sphinx ranking is funny: "belpmos " returns bülbinz as first suggestion.. here we should really work on the ranking of the results)

**Comment by ponceta** [comment]
Duplicated with #2170
