### ISSUE TITLE
Profile: enhancements

### ISSUE THREAD

**Issue by kandre** [geoadmin/mf-geoadmin3#1912]
Further profile enhancements:

- [ ]  the profile box width could be reduced when the main geoadmin panel is extended and going over the profile (Do we really want that?)
- [ ]  center transect to the middle of the map
- [ ] show the surface type based on geocover

- [x]  if only first line:
    - [x] show azimuth
    - [x] show distance
    - [x]  highest/lowest point

- [x] if only a line (more than one point):
    - [x]  show total m up
    - [x]  show total m down 
    - [x] show distance
    - [x]  highest/lowest point

- [x] if a polyline
    - [x] show total m up
    - [x] show total m down
    - [x] show distance
    - [x]  highest/lowest point

- [x] cross-browser compatibility

- [x] Allow Import of measured path as KML

- [x] Add slope parameter in profile tootip
- [ ] bring print back for profile
- [x] add hiking time for each direction

**Comment by ponceta** [comment]
Add " Allow Import of measured path as KML " #1944 as possible enhancement

**Comment by ponceta** [comment]
[Better Than Google]

![aletsch](https://cloud.githubusercontent.com/assets/8614223/7020269/fc7cd526-dd17-11e4-850f-54d82269cca0.PNG)
![aletsch_google](https://cloud.githubusercontent.com/assets/8614223/7020270/fc7d0410-dd17-11e4-8486-70a85a2afc47.PNG)

Possible Improvements:
 - [ ] Height / Length display everywhere on the graph (not only on the colored side)
 - [ ] Responsive design for the tooltip height (for high rez monitors)
 - [ ] Improve the Profile Print (Improving png rez before sending it to the print server)
Harder improvements
 - [ ] Improve Profile quality for bigger resolutions (either with minimal spacing or min max detection -> avoid as much as possible "smoothing")

**Comment by kandre** [comment]
@oterral, I know you are refining drawing and measure tool are in progress, then I suggest I could develop functionnalites anyway (such as highest/lowest point, slope, denivelé...) from the computation point of view, and not spending time too much on graphical interface and user interactions, what do you think ?

**Comment by cedricmoullet** [comment]
+1 with @kandre proposal.

**Comment by ponceta** [comment]
Since we extract coordinates, we should add the 3rd one (altitude) to the generated kml points.

**Comment by davidoesch** [comment]
surface type is still not solved... move this to a new ticket ?

**Comment by gjn** [comment]
Not really sure what is meant by that. Where do we get the info about the surface type? New service? What will be clolor mapping?

**Comment by davidoesch** [comment]
From tlm . Using existing Services. Might need an update in data integration. Will show you the reference of outdooractive. Goal: are you hiking in forest or paved roads etc.... More 1:1

**Comment by davidoesch** [comment]
@gjn see screenshot above in tik description and eg http://www.outdooractive.com/en/mountain-bike/graubuenden/433-poschiavo-san-romerio/19257197/#dm=1 

but IMHO we need for this
- snapping  to fit it to TLM vector info ( hiking trails do contain a surface info)
- or as a workaround use the service for ch.swisstopo.vec25-primaerflaechen and a add this info to the height service...

**Comment by oterral** [comment]
I've created a new issue for that https://github.com/geoadmin/mf-geoadmin3/issues/3460
