### ISSUE TITLE
Zeitreihe: play button

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#1942]
this is an enhancement: nice to have ( I know we ditched the movie.... )
- Play button
- fast medium slow speed

as in 
https://earthengine.google.org/#intro/SaudiArabiaIrrigation

**Comment by oterral** [comment]
@davidoesch @cedricmoullet something like that ?

**Comment by oterral** [comment]
I'm waiting for the icons

**Comment by davidoesch** [comment]
The transition- is it possbile to add a fading effect?
http://mf-geoadmin3.dev.bgdi.ch/teo_play/?lang=fr&topic=swisstopo&bgLayer=ch.swisstopo.pixelkarte-farbe&X=190000.00&Y=660000.00&zoom=1&layers_timestamp=18851231&catalogNodes=1392&layers=ch.swisstopo.zeitreihen&time=1885

**Comment by oterral** [comment]
No because of this -> https://github.com/geoadmin/mf-geoadmin3/issues/1999

**Comment by davidoesch** [comment]
lets wait https://github.com/openlayers/ol3/pull/2950 codesprint in a
couple of days....

**Comment by davidoesch** [comment]
@oterral is there an update  regarding "The transition- is it possbile to add a fading effect? " the https://github.com/openlayers/ol3/pull/2950  did AFAIK not address this

**Comment by oterral** [comment]
@davidoesch @cedricmoullet  it seems something exist in this PR : https://github.com/openlayers/ol3/pull/3660

There is no transition but at least the layer loads only when the tiles are ready to be displayed

**Comment by davidoesch** [comment]
can we have this on test enviro?

**Comment by oterral** [comment]
Yes when I have a bit of time i'll do that.

**Comment by oterral** [comment]
New PR in ol https://github.com/openlayers/ol3/pull/4389

**Comment by elemoine** [comment]
See http://erilem.net/ol3/dynamic-params/examples/wmts-dimensions.html for an example demonstrating the new behavior.

**Comment by davidoesch** [comment]
nice-- woder how it works with raster....as in https://s.geo.admin.ch/68276043c8

**Comment by gjn** [comment]
This is really nice @elemoine ...quite slow on my side. It drags alot of data in :=). Maybe it would make sense to cancel requests when moving the slider fast. Seems like requests might bottle up; which hurts reactivity on slower connections.

In any case, this would be really nice to have in map.geo.

**Comment by elemoine** [comment]
I merged my PR. Feel free to create issues if you experience performance problems.

**Comment by gjn** [comment]
Thanks alot @elemoine for this and keeping us in the loop.

**Comment by oterral** [comment]
@davidoesch  I've updated the branch with last changes in ol [Test](https://mf-geoadmin3.dev.bgdi.ch/teo_play/?lang=fr&topic=swisstopo&bgLayer=ch.swisstopo.pixelkarte-farbe&X=190000.00&Y=660000.00&zoom=1&layers_timestamp=18851231&catalogNodes=1392&layers=ch.swisstopo.zeitreihen&time=1885)

**Comment by davidoesch** [comment]
question: in the original configration , the play mode was faster.... can you set it to this speed? ( I'l ahve a demo with the steering comitee on monday...)

**Comment by oterral** [comment]
Yes currently it's each 2s  how much do you want?

**Comment by davidoesch** [comment]
hwo was it before? I'dont remember @cedricmoullet?

**Comment by oterral** [comment]
I've put 1s [TEst](https://mf-geoadmin3.dev.bgdi.ch/teo_play/?lang=fr&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&X=190000.00&Y=660000.00&dev3d=true&zoom=1&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bafu.wrz-wildruhezonen_portal,ch.swisstopo.swisstlm3d-wanderwege&layers_visibility=true,false,false,false&layers_timestamp=19731231,,,&time=1973)

**Comment by davidoesch** [comment]
perfect for the demo

**Comment by davidoesch** [comment]
fyi: replace the play stop button with
play: http://www.swisstopo.admin.ch/internet/swisstopo/de/misc/timehelp.parsys.44773.Image.jpeg
stop: http://www.swisstopo.admin.ch/internet/swisstopo/de/misc/timehelp.parsys.51411.Image.jpeg

the position at the makes sense

**Comment by oterral** [comment]
DOne in prod
