### ISSUE TITLE
Translation missing for IT / RM

### ISSUE THREAD

**Issue by ponceta** [geoadmin/mf-geoadmin3#1958]
http://bit.ly/165aDJl

(twitter publication of the day)

![image](https://cloud.githubusercontent.com/assets/8614223/5390283/e25bdb08-8108-11e4-857c-d4f0a7739f1f.png)

@AFoletti could you have a look?

**Comment by AFoletti** [comment]
Translations are delivered by customer.
I was already scolded a few times for spontaneous translations. Won't do that again ;)
