### ISSUE TITLE
Profile: don't send extra request if data already loaded

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/mf-geoadmin3#1962]
This is not a regression.

Step to reproduce:
1. Open map.geo.admin.ch
2. Open measure tools and start measuring
3. Display profil
4. Hide profil
5. Display profil

Result:
A request is performed even though a new measure wasn't performed.

Expected Result:
If the measure hasn't changed, we should not perform an extra request.

**Comment by cedricmoullet** [comment]
For me really a NTH. I can live with that
