### ISSUE TITLE
Artefacts in geological map

### ISSUE THREAD

**Issue by cedricmoullet** [geoadmin/mf-geoadmin3#1971]
http://map.geo.admin.ch/?X=179400.00&Y=606809.09&zoom=3&lang=fr&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.geologie-geologische_karte

![image](https://cloud.githubusercontent.com/assets/319676/5422747/7b76b0d4-8293-11e4-828e-7177b994f8f9.png)

**Comment by oterral** [comment]
Duplicate with #1973
