### ISSUE TITLE
Tiles artefacts in IE11 and all other browsers

### ISSUE THREAD

**Issue by cedricmoullet** [geoadmin/mf-geoadmin3#1973]
http://mf-geoadmin3.dev.bgdi.ch/ltmoc/?X=200812.89&Y=618058.57&zoom=6&lang=fr&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe

![image](https://cloud.githubusercontent.com/assets/319676/5426613/cc83e29a-835f-11e4-916c-178f240c2d7f.png)

**Comment by davidoesch** [comment]
update:

- since it can observed for standard bg layer: it can not be related to the header info and the tile file name extension as discussed above
- Since the deploy of 20150107 I get this under ff via BIT proxy quite often....

**Comment by procrastinatio** [comment]
I don't think it's a tile issue as it is random and not repeatable.

Note, the same kind of error hapens with PDF, I tend to incriminate the BIT Proxy (look at https://github.com/geoadmin/mf-geoadmin3/issues/2040) or something on the network which may mutilate in a some way binary files. The source files are perfectly fine.

**Comment by cedricmoullet** [comment]
I also agree with this theory. The question now is to understand why this
happens only since a few weeks.
A change in the way we deliver the tiles (through varnish in the VPC) ? A
change in the proxy (but this happens not only in the BIT proxy) ?
How can we investigate further ?

On Thu, Jan 8, 2015 at 9:31 AM, procrastinatio <notifications@github.com>
wrote:

> I don't think it's a tile issue as it is random and not repeatable.
>
> Note, the same kind of error hapens with PDF, I tend to incriminate the
> BIT Proxy (look at #2040
> <https://github.com/geoadmin/mf-geoadmin3/issues/2040>) or something on
> the network which may mutilate in a some way binary files. The source files
> are perfectly fine.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geoadmin/mf-geoadmin3/issues/1973#issuecomment-69149753>
> .
>



-- 
Twitter: http://twitter.com/cedricmoullet
Linked In: http://www.linkedin.com/in/cedricmoullet

<http://twitter.com/cedricmoullet>

**Comment by gjn** [comment]
Does the image arrive corrupted to the browser already? (Verifiable in the network tab).

**Comment by procrastinatio** [comment]
No, all the example I saw, the original data is good, apparently sometime it is corrupt during the transfer/visualisation..

**Comment by cedricmoullet** [comment]
But, does it mean that the image used by the browser is corrupted ?

On Thu, Jan 8, 2015 at 1:33 PM, procrastinatio <notifications@github.com>
wrote:

> No, all the example I saw, the original data is good, apparently sometime
> it is corrupt during the transfer/visualisation..
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geoadmin/mf-geoadmin3/issues/1973#issuecomment-69173531>
> .
>



-- 
Twitter: http://twitter.com/cedricmoullet
Linked In: http://www.linkedin.com/in/cedricmoullet

<http://twitter.com/cedricmoullet>

**Comment by procrastinatio** [comment]
The only way to know is to use a packet sniffing tool to see if somthing is corrupted. Before that, If you encounter such case, you have to describe careffuly the settings (network, browser), time and material affected (tile, pdf) to determine patterns.

**Comment by gjn** [comment]
If it's in browser cache, we could look at the raw image data via the network tab to see if browser uses an already corrupt file or not.

**Comment by davidoesch** [comment]
just another comment; in the proxy.pac of BIT we made an exception for map.geo so it can bypass the proxy.... maybe @hpchrist can give here a hint..... on the other hand: varnish is running now in he VPC,? side effect?

**Comment by cedricmoullet** [comment]
I can't reproduce anymore, also on VPN.....

On Fri, Jan 9, 2015 at 10:21 AM, davidoesch <notifications@github.com>
wrote:

> feedback from @hpchrist <https://github.com/hpchrist>
>
> "And I also guess that the VPC migration won’t be the reason of the issue.
> First because for the tiles, it already has been done several months ago.
> And second because it doesn’t proxy the http traffic."
>
> Proxy.pac
>
> "But this is the CMS @FUB <https://github.com/FUB> and has nothing to do
> with the tiles delivery in the cloud. So I guess, the problem is not linked
> to the proxy.pac from the VBS."
>
> :
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geoadmin/mf-geoadmin3/issues/1973#issuecomment-69310834>
> .
>



-- 
Twitter: http://twitter.com/cedricmoullet
Linked In: http://www.linkedin.com/in/cedricmoullet

<http://twitter.com/cedricmoullet>

**Comment by davidoesch** [comment]
Me neither--- Heavy usage today via vpn.

**Comment by hpchrist** [comment]
Since there are different proxies in use @Bund, please always quote which one you use.

**Comment by ltclm** [comment]
@hpchrist is there a list of proxies?

**Comment by hpchrist** [comment]
I don't have one, but I know the following two proxies:

lf00001a.adb.intra.admin.ch:8080
proxy-bvcol.admin.ch:8080

**Comment by cedricmoullet** [comment]
I think we can close it.

**Comment by mariokeusen** [comment]
![tileartefact_20150113_ff](https://cloud.githubusercontent.com/assets/4577749/5720279/5276ba1a-9b22-11e4-8305-a8fccfd9be31.PNG)
FF32 at office @Bund
Could not reproduce on IE and Chrome

**Comment by procrastinatio** [comment]
So what do we know ?

- Tile source is never corrupted (retry solve the issue)
- Looks like only jpeg are affected (any PNG example ?)
- Looks like only pixelkarte at smaller scales is affected (this is the most requested tiles)
- Prevalence: 1 every 1'000, 10'000, 100'0000 ??? More, less ??
- Never saw corrupted tiles (=multiple requests with differents sizes) in server to server requests
- Personnally, I never saw any of these tiles.
- Last year, with had some blank tiles instead.
- FF, Chrome and IE are affected.
- Windows,Mac are affected, Linux is not (?)
- Network settings: swisstopo network, VPN are infected, ADSL Bund(?), ADSL private (??)
