### ISSUE TITLE
zeitreise: tiles are not shown 

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#1975]
open latest ff 34
clear cache
open http://map.geo.admin.ch/?X=225762.77&Y=696742.57&zoom=6&lang=en&topic=ech&bgLayer=voidLayer&catalogNodes=457,458&layers_timestamp=19221231&time=1922&layers=ch.swisstopo.zeitreihen 

Result:

tiles do appear shortly and dissapear.... or tiles  do not load at all

related to #1973 ?

**Comment by gjn** [comment]
@davidoesch Can we close this?
