### ISSUE TITLE
jpeg format don't work for feedback tool

### ISSUE THREAD

**Issue by pfanguin** [geoadmin/mf-geoadmin3#1985]

**Comment by pfanguin** [comment]
![jpegformat](https://cloud.githubusercontent.com/assets/6862714/5658856/309b376c-9709-11e4-8860-5ff3b6ab103d.JPG)

Maybe the problem is the uppercase "JPG"

**Comment by gjn** [comment]
Indeed, it's the uppercase. PR is ready to address this and ignore the case.
