### ISSUE TITLE
legend are clipped in infobox on Iphone

### ISSUE THREAD

**Issue by pfanguin** [geoadmin/mf-geoadmin3#1986]

**Comment by AFoletti** [comment]
Yes, there is a max width of 480px. If this is systematically enforced or not, I don't know but the problematic legend here is within the limit

**Comment by oterral** [comment]
@alcapat this one out of bound : https://github.com/geoadmin/mf-chsdi3/commit/bbc62a1a4649c8c1871b122fb671b8cf11e503fc  can you reduce it ?

**Comment by oterral** [comment]
thy @AFoletti I will fixed it
