### ISSUE TITLE
Ensure that map.geo.admin.ch loads the correct version

### ISSUE THREAD

**Issue by ponceta** [geoadmin/mf-geoadmin3#1990]
Since we are deploying a new version every two weeks, it could be interesting to have a version number to assess that the version we are on is the right version of map.geo.admin.ch

a good routine could be:

`A) Check the version number`
`B) Compare the version number with the most actual`
`C) If needed, flush cache and update the new version of map.geo.admin.ch`

https://developer.mozilla.org/fr/docs/Utiliser_Application_Cache

**Comment by cedricmoullet** [comment]
The HTML page is not cached anymore, so that it should solve the problem
