### ISSUE TITLE
[Print] Get rid off numbering

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#1993]
in the selection of print layouts, 1-4 numbers are not needed (to many numbers

Replace
1 A4 landscape
...
4 A3 portrait

with
A4 landscape
...
A3 portrait

KISS
![unbenannt](https://cloud.githubusercontent.com/assets/4577727/5491564/692e14da-86da-11e4-85d7-8851acd5aaf5.png)

**Comment by procrastinatio** [comment]
Would it not be possbile to "translate" this client side ? Because for now it is not.

**Comment by davidoesch** [comment]
Since it is always landscape and portrait in all lang --- it does not even
to be translated and can be hardcoded in all lang as the same

**Comment by gjn** [comment]
@ponceta Status?

**Comment by ponceta** [comment]
I'll look with @procrastinatio today how to translate and PR this

**Comment by gjn** [comment]
I needed a break from my url magic and solved this. PR is ready.

**Comment by ponceta** [comment]
From now on, we shall call you Gjn the Grey holder of the mighty stone of Angular!
