### ISSUE TITLE
Time slider: moving year should not remove the layer before showing the new one

### ISSUE THREAD

**Issue by cedricmoullet** [geoadmin/mf-geoadmin3#1999]
http://map.geo.admin.ch/?X=232070.60&Y=745773.58&zoom=6&lang=en&topic=ech&bgLayer=voidLayer&catalogNodes=457,458&layers_timestamp=19051231&time=1905&layers=ch.swisstopo.zeitreihen

Click the next tab arrow -> the layer disappears and the new one appear, so that we can see white tiles.

It should not remove the old layer before the new one is visible.

**Comment by elemoine** [comment]
When `updateDimensions` is called on a WMTS source, or when `updateParams` is called on a WMS source, OpenLayers [invalidates](https://github.com/openlayers/ol3/blob/b6a550f354074668b7793e71e53d847966213200/src/ol/source/wmtssource.js#L235) the current tiles. So when the map is rendered again, no tiles are found for that source, so the layer is empty/white until we receive new tiles.

Invalidating the current tiles when `updateDimensions` is called does make some sense to me. Indeed, there are probably cases where you do not want to show old tiles at all when a dimension is changed.

But we could add an option to `ol.source.Tile` (`useOldAsInterims` or something), which, when set to `true`, would tell the source that old tiles may be used while new ones are being loaded. This would require changing the current logic (and therefore a fair amount of work), but it should be possible.

**Comment by elemoine** [comment]
This ol3 issue is related: https://github.com/openlayers/ol3/pull/2950.
