### ISSUE TITLE
Query tool: create help for attributes

### ISSUE THREAD

**Issue by cedricmoullet** [geoadmin/mf-geoadmin3#2002]
(in order to allow a map print of the result)

**Comment by cedricmoullet** [comment]
@oterral and @pauloamado could you please define the correct ID for this help ?

**Comment by pauloamado** [comment]
This Feature will be in the category "SELECTION AND DISPLAY OF DATA" with ID = 44

**Comment by oterral** [comment]
thx I modfiy the geoadmin

**Comment by mariokeusen** [comment]
Discussed with Paulo and ongoing now...
