### ISSUE TITLE
Query tool: only two attribute filters are possible

### ISSUE THREAD

**Issue by cedricmoullet** [geoadmin/mf-geoadmin3#2006]
It should be possible to add more attribute filters

**Comment by loicgasser** [comment]
Not sure it is exactly the same issue.

#2745 refers to advanced query operators AND/OR and NOT

This issue refers to the fact that we can use only 2 conditions at a time.

**Comment by gjn** [comment]
#2745 mentions 2 points. One point is a duplicate of this (allow more than 2 queries).
