### ISSUE TITLE
Query tool: search for attribute name fails for layer ch.bafu.hydrologie-wassertemperaturmessstationen

### ISSUE THREAD

**Issue by cedricmoullet** [geoadmin/mf-geoadmin3#2009]
1. Use query tool for layer ch.bafu.hydrologie-wassertemperaturmessstationen: http://mf-geoadmin3.dev.bgdi.ch/dev_query_2/?X=265979.18&Y=612451.87&zoom=7&lang=en&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.bafu.hydrologie-wassertemperaturmessstationen
2. Select the name attribute
3. Click on the three points to get attribute values
4. Select "Broye-Payerne, Caserne d'aviation" and click on "Search"

Nothing is found -> one station should be found

**Comment by procrastinatio** [comment]
The faulty query is `http://mf-chsdi3.dev.bgdi.ch/rest/services/all/MapServer/identify?geometryFormat=geojson&lang=en&layers=all:ch.bafu.hydrologie-wassertemperaturmessstationen&time=2013&where=name+ilike+%27%25Broye-Payerne,+Caserne+d%27aviation%25%27`

**Comment by loicgasser** [comment]
It is really an escaping quote issue. (Broye-Payerne, Caserne d'aviation)
once https://github.com/geoadmin/mf-chsdi3/pull/1210 is merged, this will be solved
