### ISSUE TITLE
Query tool: after clicking on "..." in order to get attribute values, the icon should be changed

### ISSUE THREAD

**Issue by cedricmoullet** [geoadmin/mf-geoadmin3#2010]
In this case, the user can click on it in order to modify manually the value. 
A kind of edit text icon should be used: http://www.qcad.org/doc/qcad/3.4.5/reference/en/scripts/Modify/EditText/doc/EditText_en.html

**Comment by oterral** [comment]
In the PR mentinoned I show a close button when the select box is displayed
