### ISSUE TITLE
Query tool: avenches not in the value list

### ISSUE THREAD

**Issue by cedricmoullet** [geoadmin/mf-geoadmin3#2012]
When clicking on "..." in order to get the value list of the attributes, Avenches is not visible, but should be: http://mf-geoadmin3.dev.bgdi.ch/dev_query_2/?X=190000.00&Y=660000.00&zoom=1&lang=rm&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers_opacity=0.6&layers=ch.bfe.energiestaedte

**Comment by loicgasser** [comment]
1) it is sorted in ascending order when I test and in the code.

**Comment by loicgasser** [comment]
To take care of 2) we could use an offset param and implement some infinite scrolling in geoadmin.

**Comment by loicgasser** [comment]
Solved via #1226
