### ISSUE TITLE
Query tool: treatment of null value

### ISSUE THREAD

**Issue by cedricmoullet** [geoadmin/mf-geoadmin3#2013]
http://mf-geoadmin3.dev.bgdi.ch/dev_query_2/?X=190000.00&Y=660000.00&zoom=1&lang=fr&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.swissboundaries3d-gemeinde-flaeche.fill

The name attribute can have null values, but it can't be searched. It should be possible to search for null values

**Comment by loicgasser** [comment]
Yes problem is that for null values we cannot use the regular operators `(=, ilike, >)` 

What should we do in a case where `foo > null`
->
`foo is null`
or
`foo is not null` ?

Do you understand the problem? I would not return null values or I would change the behaviour front-end (when selecting a null value selectable values are is or is not)

**Comment by oterral** [comment]
I think in th front-end we should allow null valued only  for text attributes no?

**Comment by ltclm** [comment]
what if we replace null values with an empty string
```sql
coalesce(attribute,'') = | > | ilike
```
should work...

**Comment by oterral** [comment]
@loicgasser what do we do with this ?

**Comment by loicgasser** [comment]
I totally forgot about this ticket.
Searching for an empty string seems kind of weird.
I would say that null and empty string should be translated front-end by "No value". And I should adapt code backend to treat "null" queries.

We could then finally remove the "beta" in the title of this tool.
