### ISSUE TITLE
Enable LV95 N/E Parameters

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#2015]
http://help.geo.admin.ch/?id=54
change in dav0 site
Easting (von 450‘000 bis 900‘000) Northing, Bereich von 50‘000 bis 350‘000 (Immer kleiner als  Y)

**Comment by cedricmoullet** [comment]
@pauloamado LV95 is now supported in Y and X. Could you please complete the documentation ?

**Comment by procrastinatio** [comment]
Just to be pedantic, there are not 'Y' and 'X' any more in **LV95**

**Comment by davidoesch** [comment]
Yes, I Knwo, we should introduce the permalink paramter N and  E for
it....@cedricmoullet?

**Comment by cedricmoullet** [comment]
What a strange idea ;-) Of course

2015-03-19 15:33 GMT+01:00 davidoesch <notifications@github.com>:

> Yes, I Knwo, we should introduce the permalink paramter N and E for
> it....@cedricmoullet?
>
> On Thu, Mar 19, 2015 at 2:49 PM, procrastinatio <notifications@github.com>
> wrote:
>
> > Just to be pedantic, there are not 'Y' and 'X' any more in *LV95*
>
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geoadmin/mf-geoadmin3/issues/2015#issuecomment-83610613>
> .
>



-- 
Twitter: http://twitter.com/cedricmoullet
Linked In: http://www.linkedin.com/in/cedricmoullet

<http://twitter.com/cedricmoullet>

**Comment by loicgasser** [comment]
@davidoesch and @cedricmoullet 
In order to avoid ugly comments when answering from emails, there is an app for github (IOS and Android).

Simply click "view it on GitHub" at the end of each email and you'll be redirected to the app. It is much easier to use as well.

**Comment by ponceta** [comment]
Should we close this or change it's name to "Enable N/E Parameters"?

**Comment by davidoesch** [comment]
Enable N/E Parameters

**Comment by ponceta** [comment]
@procrastinatio @oterral , this is a back end change right? Any hints are welcome! :)

**Comment by ponceta** [comment]
LV95 parameters are already implemented since 
https://github.com/geoadmin/mf-chsdi3/blob/98c5ea601113b80fadbd0b426ca09dcf0f24bd48/chsdi/static/doc/source/releasenotes/index.rst#release-20141218---thursday-december-18th-2014

They can be queried using standard parameters X, Y
Do we need new parameters?

There's a risk of conflict between using 2 parameters to determine the same thing : Position.

At least what we could do is add the link to the lv95 coordinates when we toogle the position tooltip:

![image](https://cloud.githubusercontent.com/assets/8614223/7227287/e1a663f6-e74f-11e4-898d-67abb7977c8b.png)

**Comment by gjn** [comment]
Yes, supported since PR https://github.com/geoadmin/mf-geoadmin3/pull/1970 triggered by issuehttps://github.com/geoadmin/mf-geoadmin3/issues/1861

Please close this if no new parameter is needed. If we want new parameter, should x/y still support lv95 (i think yew, otherwise we break old pl)? If both are given, which has higher priority?

**Comment by davidoesch** [comment]
Lv95 should have higher  prio 

@cedricmoullet

**Comment by gjn** [comment]
So we want the new N/E parameters? (I would try to avoid it, as _both_ we'll have to support for eternity)

**Comment by procrastinatio** [comment]
One more thing, we display LV95 at two place, in the `MousePosition` component and in the righ-click popup, but we use two differents reframing method: `proj4js`(which is basically a translation only and the `REFRAME`service (grid reframing).

**Comment by davidoesch** [comment]
New parameter... I know it is pinta - but lv95 will be the new standard and there will be a parallel pain operating phase with lv03 
Any suggestion to circumvene this? @cedricmoullet

**Comment by davidoesch** [comment]
@cedricmoullet how do we proceed on that?

**Comment by davidoesch** [comment]
After the SLA meeting feedback: we need to have a global strategy on lv system s

**Comment by procrastinatio** [comment]
You don't need new parameters, as there is no way to mix both systems, LV95 coordinates being bigger than LV03. The only issue is that `X` and `Y` are not used in LV95 anymore, replaced by `E`and `N`, but again you cannot mix between X and Y.

The only issue I see, you add a parameter for projection, per default it is LV03, and alway use `x`and `y`for coordinates, and then we have to decide, if we respect the axis order or not.

**Comment by oterral** [comment]
@gjn  is it implemented in the lv95 branch?

**Comment by procrastinatio** [comment]
@oterral 
For LV03, it is Y/X as now, e.g. [Lugano](https://mf-geoadmin3.int.bgdi.ch/gjn_lv95/index.html?zoom=8&X=95000&Y=717000)
For LV95 it is N/E [Ambri]( https://mf-geoadmin3.int.bgdi.ch/gjn_lv95/index.html?zoom=7&E=2695805.47&N=1151576.80)

**Comment by oterral** [comment]
ok good

**Comment by cedricmoullet** [comment]
Should we transform yx to en in order to kill old permalinks ?

Envoyé de mon iPhone

**Comment by oterral** [comment]
xy disappear after the first map move.

I close this since the code has been merge din master.

**Comment by oterral** [comment]
Fixed by https://github.com/geoadmin/mf-geoadmin3/pull/3905

**Comment by gjn** [comment]
No need to transform old permalinks. Application will/should work with both yx (lv03 permalink) and EN (lv95 permalinks)
