### ISSUE TITLE
Print; does not work under Linux Debian 8, Firefox (iceweasel 31.3.0). 

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#2022]
Issue;
"Drucken funktioniert nicht mit Debian 8, Firefox (iceweasel 31.3.0). 
Ausschnitt, Format kann gewahlt werden. Wird visuell angezeigt. Jedoch anschliessend keine Reaktion, wenn Drucken-Button gedruckt wird. 

"
Permalink: http://map.geo.admin.ch/?X=102737.50&Y=605490.00&zoom=7&lang=de&topic=ech&bgLayer=ch.swisstopo.pixelkarte-grau&layers=ch.swisstopo.hangneigung-ueber_30,ch.blw.hang_steillagen&layers_opacity=0.75,0.75&layers_visibility=true,false

**Comment by madlenenussbaum** [comment]
(back on my office computer..)
1) You did: "Wir haben Änderungen seit Ihre Nachricht gemacht. Nach Überprüfung, sollte Ihr Link mit Ihrem Konfiguration funktionieren." (Email 23.12.2014)
2) I updated Debian 8 with apt-get upgrade 
3) I did not have a pop up blocker in the first place

>> now the printing function works. A window appears for donwloading/opening the PDF with the map content. 

Thank you very much for your help!
