### ISSUE TITLE
Zeitreihe: print overview does not work

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#2028]
win 7 ff
open ff clear cache etc
http://s.geo.admin.ch/61412dbeae  

go directly to print
print multiyear pdf

result:
"N:\5-kogis\5-KOGIS\51-BGDI\5103-Geobasisdaten\5103-04-Originaldaten\5103-04-09-bund-swisstopo\Zeitreise\fehlerhaftepdf\map.geo.admin.ch-2.pdf"

-> PDF is corrupt

I can reproduce this every 10th time or so... strange

**Comment by procrastinatio** [comment]
Please test!

- The generated file is always OK
- Only big PDF files may be corrupted (multipdf)
- Maybe less than every 20 files
- Cannot reproduce at home

**Comment by procrastinatio** [comment]
Sorry, cannot reproduce anymore... Tested with 200 multipages PDF ranging from 100 MB to 1GB. Prove me wrong. Otherwise, close it.

**Comment by davidoesch** [comment]
tested heavily now on RAS VPN -- seems to be fixed
