### ISSUE TITLE
query tool: delete results when closing the query window

### ISSUE THREAD

**Issue by mariokeusen** [geoadmin/mf-geoadmin3#2034]
This is something I asked for last year already:

UC: open the aviation topic, open the query tool, make a query, close the query tool and open it again
Result: The result list is still present after closing and reopening the tool
Expected: Result list should be empty and user should make a new query.

This is what also the bazl wants. But we can discuss.
![query_delete_on_closing](https://cloud.githubusercontent.com/assets/4577749/5625746/17d47254-9581-11e4-9784-60c5a2c799c7.PNG)

**Comment by davidoesch** [comment]
The select by rectangle had  the same behaviour....

**Comment by cedricmoullet** [comment]
Which one ? What is the correct behaviour ?

On Tue, Jan 6, 2015 at 7:51 PM, davidoesch <notifications@github.com> wrote:

> The select by rectangle had the same behaviour....
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geoadmin/mf-geoadmin3/issues/2034#issuecomment-68912505>
> .
>



-- 
Twitter: http://twitter.com/cedricmoullet
Linked In: http://www.linkedin.com/in/cedricmoullet

<http://twitter.com/cedricmoullet>

**Comment by davidoesch** [comment]
The correct behavior: when tool is closed everything is reset.

**Comment by oterral** [comment]
@davidoesch do we close ?

**Comment by davidoesch** [comment]
Yes
