### ISSUE TITLE
query tool: missing attribute translations for luftfahrthindernis in EN

### ISSUE THREAD

**Issue by mariokeusen** [geoadmin/mf-geoadmin3#2035]
UC: open the aviation topic switch language to EN, open the query tool, look at the dropdown menu with searchable attributes.
Result: the attributes are not translated (see screenshot)
Expected: attrbutes are translated the same way as for the other languages.
![query_attributetranslation_en](https://cloud.githubusercontent.com/assets/4577749/5625757/6493eed0-9581-11e4-8880-837c5e814fab.PNG)

**Comment by cedricmoullet** [comment]
@oterral ?

**Comment by oterral** [comment]
I guess some attributes haven't translations in english because one is translated.

**Comment by oterral** [comment]
https://github.com/geoadmin/mf-chsdi3/blob/d664268bfc97dccfc3360dd805a319cca5136c2b/chsdi/locale/en/LC_MESSAGES/chsdi.po#L1562

**Comment by oterral** [comment]
@mariokeusen do you have a document where you set the translations ?  Marc found the translations in database bod, schema public, table translations.
