### ISSUE TITLE
Query tool: add help content for the attribute Status

### ISSUE THREAD

**Issue by mariokeusen** [geoadmin/mf-geoadmin3#2037]
This is one of the results from the last meeting in December with Bazl (explaining the values of the attribute Status).

UC: open the aviation topic, open the query tool, click the info button on the first predefined query besides the attribute Status:
![query_aviation_helpstatus](https://cloud.githubusercontent.com/assets/4577749/5625777/ccc83a74-9581-11e4-8a5a-c2cc9c0ec96f.PNG)

Result: the time/copy compare help content appears
Expected: explanation of values of the attribute Status:
![query_translations_statusw](https://cloud.githubusercontent.com/assets/4577749/5625819/76250c8c-9582-11e4-98db-ba34a973d391.PNG)

**Comment by cedricmoullet** [comment]
@mariokeusen yes, please do that in the help: see https://github.com/geoadmin/mf-geoadmin3/issues/2002
