### ISSUE TITLE
[Help] Links don't open a new tab

### ISSUE THREAD

**Issue by oterral** [geoadmin/mf-geoadmin3#2038]
Tested with help fom Import KML. I think it would be better to open a new tab when clicking on links.

**Comment by ponceta** [comment]
Yes I'm on it! Must modify the fusion tables

**Comment by ponceta** [comment]
@oterral @pauloamado Here I think we should have 2 different IDs since we have clearly 2 times the title/content/image and 2 sections : kml import and kml generation

**Comment by ponceta** [comment]
It is this page http://help.geo.admin.ch/?id=63&lang=de
@davidoesch Paulo told me that it was your idea to squash both into one! But you agree that if we build a service with geodesy we will have 2 different topics, don't you?
Having 2 id's let things easier to integrate on map.geo.admin and this will be only one popup

**Comment by ponceta** [comment]
Should be solved now!
@oterral plz close if OK

**Comment by davidoesch** [comment]
@ponceta if geodesy cont. with providing a solution we will simply link to thier site and their into. If we need a walktrough we make it with an embedded slide show as in http://help.geo.admin.ch/?id=40

**Comment by ponceta** [comment]
ok! :)

**Comment by oterral** [comment]
so beautiful !!! thx @ponceta
