### ISSUE TITLE
[print] the background (white, colormap or aerial image) appears in the foreground for years between 1885 -1958

### ISSUE THREAD

**Issue by pfanguin** [geoadmin/mf-geoadmin3#2039]
![timeserie1](https://cloud.githubusercontent.com/assets/6862714/5625861/3debc54e-9583-11e4-8a61-3c4ddc1af024.JPG)
![timeserie2](https://cloud.githubusercontent.com/assets/6862714/5625862/3def6e9c-9583-11e4-91fb-163101d5dad1.JPG)

**Comment by ponceta** [comment]
Printing with basemap layer without transparence is bad anyway, I think we should warn the user to use the blank map before printing timeseries (divide the file size by two!) @oterral @cedricmoullet @gjn @procrastinatio what do you think?

**Comment by pfanguin** [comment]
Tested on Chrome and E11

http://mf-geoadmin3.dev.bgdi.ch/?X=221692.34&Y=545313.30&zoom=6&lang=fr&topic=ech&bgLayer=voidLayer&catalogNodes=457,458&layers=ch.swisstopo.zeitreihen&time=1945&layers_timestamp=19451231

**Comment by ponceta** [comment]
404 Tile not found :)

http://mf-geoadmin3.dev.bgdi.ch/?X=223966.36&Y=541898.39&zoom=8&lang=fr&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&catalogNodes=457,458&layers_timestamp=18881231&time=1888&layers=ch.swisstopo.zeitreihen

**Comment by ponceta** [comment]
Tile does not exist since we are outside CH :)
