### ISSUE TITLE
[PRINT Timeseries] IE 11 does not support LU vector200 layer

### ISSUE THREAD

**Issue by ponceta** [geoadmin/mf-geoadmin3#2040]
Try Print Timeseries on 
http://mf-geoadmin3.int.bgdi.ch/?X=183979.48&Y=578480.46&zoom=6&lang=fr&topic=ech&bgLayer=voidLayer&catalogNodes=477,457,458&layers=ch.swisstopo.zeitreihen,ch.swisstopo.vec200-landcover&layers_opacity=1,0.8&layers_timestamp=20121231,&time=2012

Pdf is corrupted, message is shown but download find 0 octet file.

Expected : Result is a 179 Mo File. (Works on FF and chrome.)

Size is not a problem since we can print 300 Mo Files with IE 11.

Did not reproduce with other layers.

**Comment by procrastinatio** [comment]
The generated PDFs are always fine on the server, you may try to request a second time the PDF, and it's download fine.
There is apparently an issue with binary content on IE11...

**Comment by cedricmoullet** [comment]
@procrastinatio could you please investigate further in order to see if we could improve/workaround this ?

**Comment by procrastinatio** [comment]
Did 200 multipages PDF today, no error at all. If anyone could reproduce this, I would be glade, otherwise I close the case.

**Comment by ponceta** [comment]
Already closed, but indeed it works fine now!
