### ISSUE TITLE
[query tool] serial print of extended tooltips of result list only in German

### ISSUE THREAD

**Issue by mariokeusen** [geoadmin/mf-geoadmin3#2042]
UC: open the aviation topic on integration, switch to FR, open the query tool and make a query, print the results

Result: the html-extended tooltips of the objects of the query results appears in a new window in DE
Expected: the html-extended tooltips of the objects of the query results appears in a new window in FR

Same for IT and EN (but this is no showstopper for me for tomorrow).

**Comment by oterral** [comment]
easy to fix, thx for having found this

**Comment by oterral** [comment]
@mariokeusen can you confrm it's fixed http://mf-geoadmin3.int.bgdi.ch/?X=265979.18&Y=612451.87&zoom=7&lang=en&topic=aviation&bgLayer=ch.swisstopo.pixelkarte-grau&catalogNodes=1379,1381,1514&layers=ch.bazl.luftfahrthindernis

**Comment by mariokeusen** [comment]
I could not reproduce on integration... do you have the fix on test?

**Comment by oterral** [comment]
Yes it's fixed on test and integration

**Comment by mariokeusen** [comment]
Yes, now confirmed from my private pc (probably a cache problem at office)
