### ISSUE TITLE
Catalog: not open by default, but the selection of the accordeon panel

### ISSUE THREAD

**Issue by mariokeusen** [geoadmin/mf-geoadmin3#2044]
This is something that was not like this before and in my eyes not optimal esp. for the topics.

UC: open the map viewer map.geo.admin.ch, look at the accordeon panel
Result: the "selection" section is open, while the "Catalog section" is closed
Expected: Catalog section is open, and selection section is closed (like not a long time ago)

**Comment by cedricmoullet** [comment]
@davidoesch @gjn @oterral I can't remember if this has been changed or if this was always the case. Can you ? In all case, this is not a prio 1.

**Comment by davidoesch** [comment]
defined behavior :
Catalog :
If no dataset is active catalog is closed. If a dataset is active tree is open at the corresponding tree (eg lubis)
Selection :
If a layer is active or selected : window is  open 
If no dataset is active or selected : window is closed 

This is how it was and it should be

**Comment by mariokeusen** [comment]
IMHO for the initial state of the mapviewer:

IS:
![catalog_is](https://cloud.githubusercontent.com/assets/4577749/5642117/57987920-9645-11e4-8e18-e5f067c2bf09.PNG)
Here, it does IMHO not make sense to have the selection open and the catalog closed

SOLL:
![catalog_should](https://cloud.githubusercontent.com/assets/4577749/5642122/76948d46-9645-11e4-83ef-e39e5379cdaa.PNG)

in Lubis' initial view, now the selection with the two layers is open and the catalog closed:
![catalog_lubis](https://cloud.githubusercontent.com/assets/4577749/5642147/af4f6eb2-9645-11e4-9f91-70aa71322748.PNG)

**Comment by davidoesch** [comment]
again; 

## catalogue:
**if no dataset is active catalog is closed**
Aim was and is: 
-> show as much map as possible: save screen space.
-> we should even go so far and close the menue completely (tablet mode
->  _current behaviour is ok_

**If a dataset is active tree is open at the corresponding tree (eg lubis)**
->  _current behaviour is **not ok**_

## selection :
**If a layer is active or selected : window is open
If no dataset is active or selected : window is closed**
->  _current behaviour is **not ok**_

**Comment by oterral** [comment]
Here is the behavior we have since a long time I think: http://mf-geoadmin3.dev.bgdi.ch/teo_catlog/?lang=fr&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&X=190000.00&Y=660000.00&zoom=1

Catalog:

   - mobile: never displayed
   - catalog: rely on the showCatalog property  see [here](http://mf-chsdi3.dev.bgdi.ch/1420732751/rest/services) or hidden if the window height is too small

Selection:
  - always displayed


Personnaly I prefer the behavior described by David in the previous comment.

@cedricmoullet @mariokeusen  what do you think?

**Comment by mariokeusen** [comment]
I would really go back to the behaviour of Olivier's dev-link.

**Comment by davidoesch** [comment]
Yep

**Comment by mariokeusen** [comment]
This is solved IMHO. I think we can close the ticket, not?
