### ISSUE TITLE
[query tool] IE9: default attribute values in predefined query not visible

### ISSUE THREAD

**Issue by mariokeusen** [geoadmin/mf-geoadmin3#2045]
UC: open topic aviation with IE9, open the query tool, choose the first predefined query, look at the values in the attribute fields.

Result: there is a value list visible in each field
Expected: there is a default value visible in each field (like in all other browsers)
![query_ie9_default_predef_values](https://cloud.githubusercontent.com/assets/4577749/5631113/2e1014ea-95c4-11e4-8ac4-21cde0e629f7.PNG)

**Comment by mariokeusen** [comment]
If I start the query like this, I get the correct results, but:

When I click inside the field of "Baubeginn", the date of today is added (which should be the date two weeks ago) to the field and the query switches to "user-defined-query" (which is correct).

**Comment by oterral** [comment]
Yes I can reproduce, fix comes soon.

**Comment by oterral** [comment]
Can you confirm it's fixed with this: http://mf-geoadmin3.dev.bgdi.ch/teo_fix_ie9/?lang=fr&topic=aviation&bgLayer=ch.swisstopo.pixelkarte-grau&X=190000.00&Y=660000.00&zoom=1&catalogNodes=1379,1381,1514&layers=ch.bazl.luftfahrthindernis

**Comment by mariokeusen** [comment]
Yes. Confirmed. Thanks
