### ISSUE TITLE
Feedback Tool: Contextual Help 

### ISSUE THREAD

**Issue by p1d1d1** [geoadmin/mf-geoadmin3#2053]
Is it possible to have more formatting for this contextual help?
E.g. bold text is subtitle and should be on a new line.

Actually, would it be possible to reproduce the same formatting as in 
http://help.geo.admin.ch/?id=70&lang=en

Thanks

**Comment by cedricmoullet** [comment]
Which help ?

**Comment by ponceta** [comment]
I'm on it.

**Comment by ponceta** [comment]
Done @p1d1d1 please close the issue and open new ones if you find other help formating issues!

**Comment by p1d1d1** [comment]
nice. thanks
