### ISSUE TITLE
[Help] html interpretation on non-html content

### ISSUE THREAD

**Issue by ponceta** [geoadmin/mf-geoadmin3#2056]
Help in info boxes on map.geo.admin.ch is structured in 3 types:
 1. A title
 2. A content
 3. An image

Recently we add html interpretation for title and content with #2000 previously we just had text and we wanted to be able to show images and links in the content.

To create the well looking help.geo.admin.ch @pauloamado and @procrastinatio used a script with a small library called "marked" to export via javascript the fusion table content to formated html.

We have now the issue to have two different methods and of course two different interpretations of the same content.

I see here mutliple solutions.

1. is to create a "content html-formatted" field in the fusion table which will be only use from map.geo.admin.ch ("manually formated")
2. is to create a "marked-like" formating script to encode the content in html with the fusion table properties before binding it with angular
3. is to apply a magic trick from anyone of you who has a better solution

@gjn @oterral @procrastinatio ?

**Comment by oterral** [comment]
Personaly I prefer 1) .

Can't we stored what the "marked" script exports?

**Comment by cedricmoullet** [comment]
As just discussed, I would propose to use a markdown or rst format in the
fusion table and then having a tool that generates HTML

On Thu, Jan 8, 2015 at 8:59 AM, oterral <notifications@github.com> wrote:

> Personaly I prefer 1) .
>
> Can't we stored what the "marked" script exports?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geoadmin/mf-geoadmin3/issues/2056#issuecomment-69147343>
> .
>



-- 
Twitter: http://twitter.com/cedricmoullet
Linked In: http://www.linkedin.com/in/cedricmoullet

<http://twitter.com/cedricmoullet>

**Comment by ponceta** [comment]
Ok, so the solution is a mix of 1 and 2 with a zest of 3. 
 * The content source will be written in RST format (like on git)
 * A tool like the one previously used will be set to translate the RST into HTML
 * The HTML content will be stored in a new cell in the fusion table.
 * This new cell will be directly used from both map.geo.admin.ch and help.geo.admin.ch

**Comment by cedricmoullet** [comment]
In google sheet, it's quite easy to implement JS functions that can be
triggered. I can imagine that it's possible to do that in a fusion table.

On Thu, Jan 8, 2015 at 9:13 AM, Arnaud Poncet-Montanges <
notifications@github.com> wrote:

> Ok, so the solution is a mix of 1 and 2 with a zest of 3.
>
>    - The content source will be written in RST format (like on git)
>    - A tool like the one previously used will be set to translate the RST
>    into HTML
>    - The HTML content will be stored in a new cell in the fusion table.
>    - This new cell will be directly used from both map.geo.admin.ch and
>    help.geo.admin.ch
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geoadmin/mf-geoadmin3/issues/2056#issuecomment-69148359>
> .
>



-- 
Twitter: http://twitter.com/cedricmoullet
Linked In: http://www.linkedin.com/in/cedricmoullet

<http://twitter.com/cedricmoullet>

**Comment by ponceta** [comment]
I found pandoc as a good translator http://johnmacfarlane.net/pandoc/demos.html

But it's in python, should find an equivalent library in js!

**Comment by gjn** [comment]
Why not use the same script as in help.geo.admin.ch?

**Comment by gjn** [comment]
ping @ponceta ?

**Comment by ponceta** [comment]
The actual script is great but the markdown format is not used in help encoding, that's why @cedricmoullet proposed to use RST as base format(more common -> like git). Actually I corrected the problematic cases with html

**Comment by gjn** [comment]
So now we have 3 solutions. One for help.geo.admin.ch, one for map.geo.admin.ch and the special case you just corrected, this is not good for maintenance.

Wouldn't it be the easiest solution to use the same for help.geo.admin.ch and map.geo.admin.ch? It would also allow @pauloamado to test with help.geo.admin.ch when he changes entries. I don't really care if it's RST or Markdown (Markdown/marked script is obvious as it's used for help.geo.admin.ch)

**Comment by cedricmoullet** [comment]
The goal is to have one process for both cases. There are two aspects to
consider:
1. The content creation has to be easy (HTML creation is considered as not
easy)
2. The content has to be published in map.geo.admin.ch and in the official
help.
Currently, the first aspect is non standard and is a mix of content and
html. For the second aspect, we'd like to avoid to process something on
map.geo.admin.ch side. Because of that, the idea is to standardize the
first aspect (with RST or markdown) and then to generate HTML automatically
which can be used both in map.geo.admin.ch and in the official help.
Hope this makes sense. If you see another more straightforward approach,
please let use know.

On Thu, Jan 8, 2015 at 5:54 PM, Gilbert Jeiziner <notifications@github.com>
wrote:

> So now we have 3 solutions. One for help.geo.admin.ch, one for
> map.geo.admin.ch and the special case you just corrected, this is not
> good for maintenance.
>
> Wouldn't it be the easiest solution to use the same for help.geo.admin.ch
> and map.geo.admin.ch? It would also allow @pauloamado
> <https://github.com/pauloamado> to test with help.geo.admin.ch when he
> changes entries. I don't really care if it's RST or Markdown
> (Markdown/marked script is obvious as it's used for help.geo.admin.ch)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geoadmin/mf-geoadmin3/issues/2056#issuecomment-69209457>
> .
>



-- 
Twitter: http://twitter.com/cedricmoullet
Linked In: http://www.linkedin.com/in/cedricmoullet

<http://twitter.com/cedricmoullet>

**Comment by gjn** [comment]
I'm all for streamlining, that's why I'm arguing against introducing yet another way to address this issue here. I was under the impression that help.geo used marked script to create html from fusion table...but that is wrong. Indeed, and looking at [1], there is alot of custom stuff done, which is not good and is very bad for maintenance.

Why not having a service, taking id as parameter, and returning the html as we want it from the fusion table? This service could then be used in both help.geo and map.geo.

Or maybe the simplest: if help.geo and map.geo are the only consumers of the source in fusion tables, why not put the html directly in the fusion tables?

[1] http://help.geo.admin.ch/script.js

**Comment by ponceta** [comment]
I'll not be here for the maintenance and evolution of help, but in any case we'll have to recode the content either in RST or in HTML the 169 snippets! That's why I opened this issue! I need to know which technology you want to keep in the future, to avoid encoding all in html if you want RST and vice versa.

This is how [1] it could look in html: 

```
<p><strong>HILFE KARTE: FUNKTIONEN UND PRAKTISCHE ANWENDUNG</strong></p>

<p><strong>Die Karte von geo.admin.ch ist eine intuitive Anwendung für die Suche, Anzeige und Nutzung von Informationen geografischer Art. Sie ermöglicht die interaktive Darstellung von Karten und eingeblendeten Fachdaten mit Hilfe eines standardmässigen Web-Browsers.</strong></p>

<p>Als Benutzer können Sie zahlreiche Parameter dieser Karte festlegen - zum Beispiel die dargestellte Zone und die Bildgrösse sowie den Typus der angezeigten Informationen oder den Kartenhintergrund.</p>

<p>Die Anwendung gestattet nicht nur die Bildschirmanzeige, sondern auch einen qualitativ guten Papierausdruck. Sie ermöglicht je nach Einstellung den Zugriff auf Zusatzinformationen, die mit den geografischen Objekten verknüpft sind.</p>
```

And in RST

```
**HILFE KARTE: FUNKTIONEN UND PRAKTISCHE ANWENDUNG**

**Die Karte von geo.admin.ch ist eine intuitive Anwendung für die Suche, Anzeige und Nutzung von Informationen geografischer Art. Sie ermöglicht die interaktive Darstellung von Karten und eingeblendeten Fachdaten mit Hilfe eines standardmässigen Web-Browsers.**
 
Als Benutzer können Sie zahlreiche Parameter dieser Karte festlegen - zum Beispiel die dargestellte Zone und die Bildgrösse sowie den Typus der angezeigten Informationen oder den Kartenhintergrund. 

Die Anwendung gestattet nicht nur die Bildschirmanzeige, sondern auch einen qualitativ guten Papierausdruck. Sie ermöglicht je nach Einstellung den Zugriff auf Zusatzinformationen, die mit den geografischen Objekten verknüpft sind.
```

[1] https://www.google.com/fusiontables/DataSource?docid=1Tx2VSM1WHZfDXzf8rweRLG1kd23AA4aw8xnZ_3c#rows:id=1

**Comment by gjn** [comment]
@pauloamado As you most probably will maintain the fusion table, which format would you prefer?

@ponceta Please be aware that the data in the fusion table is live data.

**Comment by pauloamado** [comment]
For me it's equal. Up to now I'm the only one (David sometimes) taking care of the help in GoogleDrive.

**Comment by ponceta** [comment]
HTML it is!

@gjn what did you mean with add the correct classes?

**Comment by gjn** [comment]
We need to be able to style the HTML that is in the fusion table. It will look different on map.geo.admin and on help.geo.admin, so we could add classes to be used in css files on the targets.

**Comment by ponceta** [comment]
It is better to add these classes here for maintenance purposes, isn't it?
https://github.com/geoadmin/mf-geoadmin3/blob/master/src/components/help/HelpDirective.js#L28-L35

**Comment by gjn** [comment]
They need to be in the source as they will be used in map.geo.admin and in help.geo.admin.

**Comment by gjn** [comment]
@ponceta @pauloamado What's the status of this issue. Can we close it?

**Comment by ponceta** [comment]
Yes! I'll come back as soon as I'll finish html translations
