### ISSUE TITLE
500 error

### ISSUE THREAD

**Issue by cedricmoullet** [geoadmin/mf-geoadmin3#2057]
http://api3.geo.admin.ch/1420635330/rest/services/geol/MapServer/ch.swisstopo.geologie-geologischer_atlas/608167/htmlPopup?imageDisplay=1600,805,96&lang=fr&mapExtent=421250,59750,821250,261000

Is it related to 3D ?

**Comment by ltclm** [comment]
No it is a mismatch between model and mako, see https://github.com/geoadmin/mf-chsdi3/pull/1195.

**Comment by cedricmoullet** [comment]
Thanks Marcel.
