### ISSUE TITLE
[aviation] IE9: serial print of html extended tootlips: map extent is empty

### ISSUE THREAD

**Issue by mariokeusen** [geoadmin/mf-geoadmin3#2070]
UC: open map.aviation.admin.ch, open the query tool, make a query of new objects from the last 2 weeks, print the object list with the print icon
Result: list appears correctly in the print preview under iE9. But all map extents are empty
Expected: list appears with visible map extents like in the extended tooltip

It works well on all other browsers...

**Comment by oterral** [comment]
on a real IE9 ?
do you print directly to the printer or in a PDF?  can you try printing in a PDF?

I hev the feeling it's related to  https://github.com/geoadmin/mf-geoadmin3/issues/1951 .
Canvas print seems to have problem in IE9

**Comment by mariokeusen** [comment]
A real IE9 user reported this. And I could reproduce it with IE9 mode. Printed a PDF then -> same result

**Comment by oterral** [comment]
hmm with IE9 mode I havn't the problem

**Comment by mariokeusen** [comment]
Weird. I get this with IE9 mode:
![serial_html_ie9mode](https://cloud.githubusercontent.com/assets/4577749/5702212/13884c4a-9a57-11e4-9942-9d02e62cacc5.PNG)

**Comment by oterral** [comment]
@mariokeusen in the tools on the top, you must active "print colors and background images"

**Comment by mariokeusen** [comment]
Thanks for that workaround. It works on my IE9 mode.
