### ISSUE TITLE
start mapviewer in IE11: issue by user

### ISSUE THREAD

**Issue by mariokeusen** [geoadmin/mf-geoadmin3#2073]
A "Bundes" internal user just fowarded me the following screenshot from IE11:

![ie11_phenomena](https://cloud.githubusercontent.com/assets/4577749/5700547/333ff7de-9a40-11e4-8ce3-502fe38ccd40.jpg)

He tried to reach the mapviewer with different permalinks and urls.

But I could not reproduce it on my IE11 and other users neither. Very strange though. But maybe you know some existing issues with IE11 personal settings?

Thanks Mario

**Comment by cedricmoullet** [comment]
@mariokeusen Can we have access to his PC ?

**Comment by mariokeusen** [comment]
Yes, we could it's Marcel Pfiffner from LG.

**Comment by mariokeusen** [comment]
The problem could be solved. Was something really strange on the user's browser settings. A switch to IE10 mode and back to IE11 solved the problem.
