### ISSUE TITLE
Whitelist ch.bazl.luftfahrthindernis

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/mf-geoadmin3#2075]
Step to reproduce:
1. Open map.geo.admin.ch
2. Switch to topic aviation
3. Switch back to topic ech
4. Click a feature on the map

Result:
HTML popup request fails (No layer with id ch.bazl.luftfahrthindernis)

Expected result:
If ch.bazl.luftfahrthindernis is part of ech -> htmlpopup does not fail
if ch.bazl.luftfahrthindernis not part of ech -> layer is removed when topic is changed

@ltclm Is ch.bazl.luftfahrthindernis supposed to be part of ech topic?

**Comment by ltclm** [comment]
@mariokeusen should the layer ch.bazl.luftfahrhindernis be part of topic ech?

**Comment by mariokeusen** [comment]
Is not (yet) foreseen. But I have a meeting with the data owner next week and will request, resp. recommend that.

**Comment by mariokeusen** [comment]
Will check that with customer on Monday. Tbc...

**Comment by mariokeusen** [comment]
Customer gave me green light for ECH. 
@alcapat : i have added the layer in ID 1561 in the topic config. Please consider this for the next deploy
