### ISSUE TITLE
Query tool highlight improvement

### ISSUE THREAD

**Issue by cedricmoullet** [geoadmin/mf-geoadmin3#2076]
Currently, the query tool highlight uses the real geometry and highlight it. On small scale, the highlighted features are not very visible. 
We need to find a way to make the highlight more visible. What about a scale dependent behaviour ?

For zoom level 0 to 5:
- Point: use current circle
- Lines: if line bbox is smaller than the circle, use the circle, otherwise, like current highlight
- Polygons: if polygon bbox is smaller than the circle, use the circle, otherwise like current highlight

For zoom level 6 to 13: like now

Not sure that it's easily implementable.
@davidoesch @mariokeusen @gjn @oterral Thoughts ?

**Comment by oterral** [comment]
You can specify a style depending on the resolution using a styleFunction.

**Comment by davidoesch** [comment]
Hi use the same ruleset zoomleve  and styling (just the different color as
for the ch.bak.schutzgebiete-unesco_weltkulturerbe dataset
http://map.geo.admin.ch/?X=190000.00&Y=660000.00&zoom=1&lang=de&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.bak.schutzgebiete-unesco_weltkulturerbe&layers_opacity=0.75

**Comment by cedricmoullet** [comment]
not very visible on first zoom levels...

**Comment by mariokeusen** [comment]
My thoughts for lines and polygons: 
make highlight for lines and polygon outlines thicker (using a buffer?) for zoomlevels 0 to 5. Possible?
or make line and outline color brighter / more obvious

**Comment by davidoesch** [comment]
the points are veryy well visible on zoom=1 ...?

**Comment by oterral** [comment]
I think modifying the size of stroke according to zoom level is enough

**Comment by davidoesch** [comment]
+1 oterral

**Comment by cedricmoullet** [comment]
@oterral could you test this ?

**Comment by oterral** [comment]
yes
