### ISSUE TITLE
Some tooltips are missing for journey through time

### ISSUE THREAD

**Issue by cedricmoullet** [geoadmin/mf-geoadmin3#2077]
A tooltip should appear here when clicking on the map: https://map.geo.admin.ch/?X=172233.28&Y=651872.50&zoom=7&lang=fr&topic=swisstopo&bgLayer=voidLayer&catalogNodes=1392&layers_timestamp=18681231&time=1868&layers=ch.swisstopo.zeitreihen

**Comment by ltclm** [comment]
The tooltip views for the most detailed zoomlevels `` zeitreihen.public.view_tooltip_21`` and ``zeitreihen.public.view_tooltip_22`` are not configured with dufour map as active layer.
These views have to be modified and the database has to be deployed.

**Comment by ltclm** [comment]
views have been updated in order to support tk100 clientzoom.

**Comment by gjn** [comment]
@ltclm Any db/table to deploy?

**Comment by ltclm** [comment]
no, since the deploy has already started, i have changed the views in-place.
