### ISSUE TITLE
Menu Share: description message stays displayed on mobiles

### ISSUE THREAD

**Issue by kandre** [geoadmin/mf-geoadmin3#2078]
Menu Share: description message (QR code, Twitter, Facebook..) stands still. Once it is displayed it hide the Shorten URL. These description message should either disappear after a given time or at least no hide the URL.

**Comment by loicgasser** [comment]
http://getbootstrap.com/javascript/#tooltips

I propose to put it on the right.

**Comment by oterral** [comment]
Remove it on mobile.

**Comment by kandre** [comment]
On mobile, those tooltips are displayed once the user already touch it, as there are no mouseover events on touchscreens. Therefore I go for the removal solution.
