### ISSUE TITLE
ch.swisstopo.geologie-geologischer_atlas: inconsistencies between infobox and behaviour

### ISSUE THREAD

**Issue by p1d1d1** [geoadmin/mf-geoadmin3#2082]
When you click the layer info icon you get : 
![ch swisstopo geologie-geologischer_atlas_de 1](https://cloud.githubusercontent.com/assets/1533649/5738860/9bbee77c-9bf1-11e4-921f-772700f72447.png)
Actually there is no "Kartenblatt". The tooltip shows if you click on some line objects: then you have to click the link in the tooltip to open the legend.

Got this from HelpDesk:

***********************************************************************************************************************
 Liebe Leute

wenn Ihr schon eine neue Website bastelt, ware es doch gut, wenn diese im Vergleich zur vorhergehenden auch besser ist. Dies ist ja nun wirklich nicht der Fall. 
Legende erscheint beim Anklicken eher selten und das in allen moglichen Kartenausschnitten. Zudem ist es extrem muhsam geworden einen Ausschnitt zu drucken, da der gewahlte Ausschnitt und das pdf deutlich voneinander abweichen. Man muss also diverse Anlaufe nehmen um dann mit gut Gluck mal etwas brauchbares zu haben.
Und wo ist eigentlich das Luftbild geblieben??

Liebe Grusse

Petra. 
Permalink: http://map.geo.admin.ch/?X=153737.61&Y=786951.24&zoom=8&lang=de&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&catalogNodes=532,533&layers=ch.swisstopo.geologie-geologischer_atlas. 

User-Agent: Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; WOW64; Trident/5.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; InfoPath.3)

**Comment by mariokeusen** [comment]
This is a known bug, which was fixed by @ltclm in https://redmine.prod.bgdi.ch/issues/4254. should be on prod with next deploy.

**Comment by p1d1d1** [comment]
Actually now the tooltip is also available for polygons. Was not available when I tested this morning.
Something changed in the meanwhile?

**Comment by gjn** [comment]
Good timing. The deploy just finished (unofficial yet).

**Comment by mariokeusen** [comment]
Jep. Works as designed with LG again. Problem solved.
