### ISSUE TITLE
Add mapExtent imageDisplay and tolerance in identify in query mode

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/mf-geoadmin3#2083]
@davidoesch 

min/max resolution on the models is not taken into account for queries (where) with identify. As a result, the same object is returned multiple times but with different resolutions.

Adding the above parameters in the identify is necessary for resolution computation.

Now from a user experience perspective, when zooming on a feature from the list, with the current implementation and if we take into account the min/max resolutions on the models we will end up with the wrong geometry since we'll have loaded a geometry with a lower resolution initially.

My question is:
Do we keep the current behaviour returning all geoms?
or
Do we implement the min/max scale concept in the query tool?
or
Do we send an extra request in order to get the geometry at the appropriate resolution? (This will require changes in the actual implementation of the query tool and select by rectangle)

This remark also applies for select by rectangle.

Here is a searchable layer with different resolutions.

ch.bav.sachplan-infrastruktur-schiene_kraft

**Comment by davidoesch** [comment]
Pareto; "implement the min/max scale concept in the query tool /select by rectangle" since it affects thsi function
@cedricmoullet ?

**Comment by gjn** [comment]
@loicgasser What's the state of this issue?

**Comment by loicgasser** [comment]
I guess we go for the third proposal.
When zooming in or out we refresh the selection in the rectangle. While waiting for infra, I can do that.

**Comment by gjn** [comment]
It's low prio for me.

**Comment by loicgasser** [comment]
This has been fixed since 2015 :laughing:
