### ISSUE TITLE
[query tool] get rid of maximum number of results by introducing a "load more results" button

### ISSUE THREAD

**Issue by mariokeusen** [geoadmin/mf-geoadmin3#2087]
UC: open app, load layer ch.bazl.luftfahrthindernis, search for all objects with AGL altitude > 100m
Result: the first 200 results are listed and highlighted. In reality there are more results on that query and the user has no chance to access the further results
Expected: first 200 results are listed and highlighted and the user can load the previous/next 200 results with a paging (like in old mf-bazl)

To be discussed:
But according to the feedbacks this will be the main improvement bazl will want in the meeting next week
IMHO this is valuable for all other layers which will be queried
Do you see any technical difficulties?

Thanks for your 2 cents

**Comment by cedricmoullet** [comment]
@oterral @procrastinatio do you think that a paging is doable ?

**Comment by gjn** [comment]
Should be.

But I doubt the value of more than 200 results. How many times are you one the second page of a google search? Too many (or wrong) results are usually a smell for the wrong query. So maybe there are other ways to fullfull their requirements, like combining query with rectangle.

There _might_ be a use case where you want 200+ results, but analyse it carefully. (In old app, this feature was maybe a workaround for something not doable then)

**Comment by cedricmoullet** [comment]
@gjn comments make sense. One use case that I see is for the CSV export.

**Comment by mariokeusen** [comment]
I see your argument to motivate users to make "queries that make sense". 
But: When I "play" with the luftfahrthindernis data, I get easily more than 200 results. E.g. deleted objects in the last year or new created of the last year.
In mf-bazl, the paging was implemented due to performance reasons (rendering and database) and because a result limit was a no-go for the bazl that time.

**Comment by mariokeusen** [comment]
Besides the csv export I see potential for that use case in other layers to be queried like e.g. the geological reports and of course all the water data existing and coming this year from the GEWISS-project.

**Comment by gjn** [comment]
Reports and exports are different than having it all in a list in UI and highlighted on the map.
We'll see.

**Comment by mariokeusen** [comment]
Goal is giving the user the possiblity to load more results (if necessary several times), if the maximum number of results is larger than 200. 
Idea is introducing a "load more results"-button to the result list.

**Comment by procrastinatio** [comment]
Only this _identify_ service or all services where max feature is implemented ?
