### ISSUE TITLE
Date layer is not responsive in map.aviation.admin.ch

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#2088]
open
map.aviation.admin.ch desktop

play with the window size

if not fullscreen 

Result:

Date is not shown south bottom
![unbenannt](https://cloud.githubusercontent.com/assets/4577727/5778885/bc90c71e-9d9e-11e4-8dda-b1145df8346c.png)

Expected result

Date layer is always shown
cc @mariokeusen @ltclm

**Comment by mariokeusen** [comment]
I think, if this is an issue, it is a minor. Behaviour is as follows according to my few checks:
on IOS: all good, data status visible on the bottom of the map window (as expected) -> see screenshot
![data_status_lfh_mobile](https://cloud.githubusercontent.com/assets/4577749/5780137/7055c98a-9da8-11e4-8924-fe71540018c5.png)

playing with desktop window size (firefox): data status not visible on reducing window until you make a zoom or pan operation.

**Comment by davidoesch** [comment]
Will be tricky to fixYou need a WMS request -- and resizing a window does not send one....

**Comment by mariokeusen** [comment]
Exactly. IMHO this is a wontfix.

**Comment by gjn** [comment]
New request is made if resize results in area that is bigger than before. So it's only problematic when making the window smaller.
We could
1. try a hook that triggers a new request on re-sizing for all wms single-tile sources, which I consider hacky. 
2. close this.
@davidoesch your call.

**Comment by davidoesch** [comment]
What I imagined is working with a hook---- but the possible side effects of this..not  worth the effeort

As long as we can explain the beahviour and show the solution with a refresh.
it is enough
