### ISSUE TITLE
[Mobile] Share my position VS Geoloc = true

### ISSUE THREAD

**Issue by ponceta** [geoadmin/mf-geoadmin3#2091]
It is actually complicated to share your position on http://map.geo.admin.ch

You must activate your gps/geolocalisation service and then deactivate it to share your position by holding your finger on the screen to have a crosshair link in a new window from where you can share your position. (Impossible for the common user)

On mobile it could be great to replace the facebook/twitter/qrcode sharelinks

Do you think that's possible/good idea? @gjn @cedricmoullet @procrastinatio @oterral ?

**Comment by cedricmoullet** [comment]
@davidoesch ?

**Comment by davidoesch** [comment]
Proposal 
Always remove geolocation=true parameter when creating a a short Url.

Then via sharing the user sets the right extent when sharing 

Link with faden Kreuz : here he already has to right parameters to share with whatever app he wants

@cedricmoullet?

**Comment by gjn** [comment]
So the famous 'where am  I' / 'where are you' qrcode can't be shared anymore? :-)

**Comment by davidoesch** [comment]
Ahh bloody hell you are right Gilbert - here the code must be generated manually with the parameter.... Imho no issue

**Comment by davidoesch** [comment]
@cedricmoullet IMHO adding manually geolocation=true if needed is 80/20. your thoughts?

**Comment by cedricmoullet** [comment]
+1

2015-10-14 21:22 GMT+02:00 davidoesch <notifications@github.com>:

> @cedricmoullet <https://github.com/cedricmoullet> IMHO adding manually
> geolocation=true if needed is 80/20. your thoughts?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geoadmin/mf-geoadmin3/issues/2091#issuecomment-148166085>
> .
>



-- 
Twitter: http://twitter.com/cedricmoullet
Linked In: http://www.linkedin.com/in/cedricmoullet

<http://twitter.com/cedricmoullet>

**Comment by davidoesch** [comment]
decision; Always remove geolocation=true parameter when creating a a short Url.

**Comment by gjn** [comment]
Is it ok to never have it in the URL at all? Would facilitate implementation greatly and manual creation would still work. Downside: F5 would loose geolocation state.

**Comment by davidoesch** [comment]
Is it ok to never have it in the URL at all? -> yes

**Comment by gjn** [comment]
PR ready: https://github.com/geoadmin/mf-geoadmin3/pull/2766
