### ISSUE TITLE
[query tool] integrate a warning text, if number of result is more than max (200 currently)

### ISSUE THREAD

**Issue by mariokeusen** [geoadmin/mf-geoadmin3#2094]
UC: open app, switch to topic aviation, search for all objects from the layer ch.bazl.luftfahrthindernis with "maximum heighth AGL" >= 100.
Result: 200 results in list, in reality there would be more results. No warning for the user
Expected: if the number of results is more than the maximum of now 200, a warning text appears like in this screenshot:
![warning_query_results](https://cloud.githubusercontent.com/assets/4577749/5802636/19c5f3f0-9ff7-11e4-9000-c14cf7e879a6.PNG)

My proposal for DE:
"ACHTUNG: Zu grosse Anzahl Ergebnisse. Es werden nur die ersten 200 Ergebnisse angezeigt!"

My proposal for EN: 
"ATTENTION: Too large number of results. Only the first 200 results are being displayed!"

Open for some other proposals and also versions in FR and IT.

Thanks in advance
Mario

**Comment by cedricmoullet** [comment]
@oterral @gjn How can we solve this ?

**Comment by oterral** [comment]
Can we close this one @mariokeusen ? problem has been fixed differently in the referenced PR

**Comment by mariokeusen** [comment]
IMHO yes. Do you have the result on dev?

**Comment by oterral** [comment]
yes [here](http://mf-geoadmin3.dev.bgdi.ch/teo_results/?X=190000.00&Y=660000.00&zoom=1&lang=fr&topic=aviation&bgLayer=ch.swisstopo.pixelkarte-grau&catalogNodes=1379,1381,1514&layers=ch.bazl.luftfahrthindernis)

**Comment by mariokeusen** [comment]
Thanks, I tested a bit:

In general I think it's a good solution and we can put it on prod. As soon as we are I'll take care about updating the help, which seems important to me.

Just found a strange thing on IE10:
![query_ie10_highlight_issue](https://cloud.githubusercontent.com/assets/4577749/6409641/da72a048-be66-11e4-9b9f-bc7cddabcb36.PNG)
It seems that the highlight does only display line objects but no points (performance issue?). Anyway it works very well on Chrome and FF. (I always used the query [Maximum height AGL m] >= 120, which produces 455 results in total)

Another thought: shouldn't the "Zustand"/"Conditions" be opened, when the user chooses a "custom filter" in the dropdown above? In this case he will anyway want to adjust things there and we could save a click with that.
![query_user_defined_zustand](https://cloud.githubusercontent.com/assets/4577749/6409795/5008a5fe-be68-11e4-87ad-ca1f85451298.PNG)

Then I made some modifications on the translations, especially in German: i entered some different translations here (red cells at the bottom of the table): https://docs.google.com/spreadsheets/d/1F3R46w4PODfsbJq7jd79sapy3B7TXhQcYM7SEaccOA0/edit#gid=0

**Comment by oterral** [comment]
```
It seems that the highlight does only display line objects but no points (performance issue?). Anyway it works very well on Chrome and FF. (I always used the query [Maximum height AGL m] >= 120, which produces 455 results in total)
```
Hmm points are displaying on my IE, maybe the browser was too laggy

**Comment by mariokeusen** [comment]
At office it also works correctly on my IE10. Probably the slow VPN connection.
