### ISSUE TITLE
[query tool] load tests for the maximum number of results

### ISSUE THREAD

**Issue by mariokeusen** [geoadmin/mf-geoadmin3#2095]
Maximum number of results in the query tool is now 200. 
As discussed this morning we could test, if and how much this limit can be increased without any bigger impact on the performance.

**Comment by cedricmoullet** [comment]
Can we test 500 ?

**Comment by loicgasser** [comment]
yes

**Comment by gjn** [comment]
@loicgasser Have tests been done? (I would test on the wohnungsregister layer)

**Comment by loicgasser** [comment]
No nothing on my side.

**Comment by gjn** [comment]
This is solved with 201 results now, so those tests not needed now. I'll close.
