### ISSUE TITLE
Offline button hides data copyright on ipad mini

### ISSUE THREAD

**Issue by kandre** [geoadmin/mf-geoadmin3#2096]
![img_0034](https://cloud.githubusercontent.com/assets/8038575/5815064/602fe774-a092-11e4-894f-48be1f3d5362.jpg)

**Comment by oterral** [comment]
problem with the image or is it just me?

**Comment by kandre** [comment]
Yes it does not load

**Comment by kandre** [comment]
Better with a jpeg. 

If I remember well, the problem was fixed for iphone (#1938)

**Comment by oterral** [comment]
It's caused by  the HTML page scroll when you opens a 2nd page

**Comment by gjn** [comment]
@kandre @oterral  Can we close this since it's wontfix?

**Comment by oterral** [comment]
yes
