### ISSUE TITLE
[Feedback] - Umlaut support

### ISSUE THREAD

**Issue by p1d1d1** [geoadmin/mf-geoadmin3#2100]
@gjn please support umlaut in feedback tool.
Would be good if available for the next deploy = GoLive of the new revision service.
thanks

**Comment by p1d1d1** [comment]
Is this really solved?
Got this from HelpDesk:

***************************************************************************
hhhsk@live.com just sent a feedback:
 die Mobile Version auf Windows Phone 8.1 funktioniert nicht mehr. man muss dafu??r den Explorer umstellen auf Normalansicht, womit andere URL nicht mehr funktionieren bis man wieder den Explorer zuru??ck gestellt hat. 
Permalink: http://map.geo.admin.ch/?lang=de&X=195328.68&Y=700073.41&zoom=0&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe. 

User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; EIE11;DECHWOL; rv:11.0) like Gecko
****************************************************************************

Check also meta.json (email sent to Gilbert.Jeiziner@swisstopo.ch)

**Comment by cedricmoullet** [comment]
@procrastinatio could you complete ?

**Comment by p1d1d1** [comment]
@procrastinatio any news about this?
thanks

**Comment by gjn** [comment]
Was not completely solved because encoding of text was set incorrectly. A new PR is chsdi is ready for this.

**Comment by gjn** [comment]
PR merged. Will be ok on next deploy next week.
