### ISSUE TITLE
KML layer are not added in the order defined by the permalink

### ISSUE THREAD

**Issue by procrastinatio** [geoadmin/mf-geoadmin3#2103]
KML layer are added to the layer selection in the order they are loaded and not in the order they are defined in the permalink.

Example:

http://s.geo.admin.ch/623c84f293

KML||http://dav0.bgdi.admin.ch/bfe_pub/bazl/kml/Schutzzone_Meteo_agreg.kml
KML||http://dav0.bgdi.admin.ch/bfe_pub/bazl/kml/Koordinationzone_Meteo_agreg.kml
KML||http://dav0.bgdi.admin.ch/bfe_pub/bazl/kml/Koordinationzone_Meteo.kml
KML||http://dav0.bgdi.admin.ch/bfe_pub/bazl/kml/Schutzzone_Meteo.kml
KML||http://dav0.bgdi.admin.ch/bfe_pub/bazl/kml/Koordination_CNS_agreg.kml
KML||http://dav0.bgdi.admin.ch/bfe_pub/bazl/kml/Koordinationzone_CNS.kml
KML||http://dav0.bgdi.admin.ch/bfe_pub/bazl/kml/Schutzzone_CNS.kml
KML||http://dav0.bgdi.admin.ch/bfe_pub/bazl/kml/Schutzzone_CNS_agreg.kml
KML||http://dav0.bgdi.admin.ch/bfe_pub/bazl/kml/meteoradar.kml
KML||http://dav0.bgdi.admin.ch/bfe_pub/bazl/kml/Bodenstationen.kml
KML||http://dav0.bgdi.admin.ch/bfe_pub/bazl/kml/SUR.kml
KML||http://dav0.bgdi.admin.ch/bfe_pub/bazl/kml/NAV.kml
KML||http://dav0.bgdi.admin.ch/bfe_pub/bazl/kml/COM_anlagen.kml

**Comment by oterral** [comment]
That need probably some huge modification of kml service using promises

**Comment by davidoesch** [comment]
why not make it: KML are in the permalink in the order they are added. So to user can control it this way

**Comment by oterral** [comment]
Not really because KMLs are distant files. So if the last file is loaded before the 1st file it will be added before.

**Comment by davidoesch** [comment]
This really needs a fix, since it prevents the building of custom based applications----

**Comment by cedricmoullet** [comment]
What about reordering them after the last is loaded ?

**Comment by oterral** [comment]
Yes it's a solution I will look into it today
