### ISSUE TITLE
Permalink handling on application load

### ISSUE THREAD

**Issue by gjn** [geoadmin/mf-geoadmin3#2105]
As discussed with @oterral , when loading the page, the permalink affects our application with it's parameter. We have several of those mechanics inside components. This means that the permalink loading would/will fail, when the component is not present for some reason (reduced page, etc).

We should refactor those.

**Comment by gjn** [comment]
See suspected directive here: https://github.com/geoadmin/mf-geoadmin3/pull/2197/files Comment by @oterral

**Comment by oterral** [comment]
We can add TimeSelctor in the suspect component list

**Comment by oterral** [comment]
`ga-translation-selector` and `ga-topic` will not be suspicious anymore  with https://github.com/geoadmin/mf-geoadmin3/pull/2471
