### ISSUE TITLE
WGS84 Coords wrong in footer

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#2107]
open map.geo.admin.ch

" WGS84 Koordinaten vom Standort,. Nicht grad/min/sek.
Diese sind im readout verdreht angegeben. Siehe attach rot markiert. lat/long 9.54, 46.84 für Chur. Bei Grad Min Sek stimmt's."
![unbenannt](https://cloud.githubusercontent.com/assets/4577727/5857544/eb7a9f34-a24c-11e4-9ecd-7fbc8aeec881.png)

**Comment by ponceta** [comment]
Should be reverted like that?  
![image](https://cloud.githubusercontent.com/assets/8614223/5870822/fe3399e0-a2d4-11e4-8edd-6bcd998b3d50.png)

http://en.wikipedia.org/wiki/ISO_6709

**Comment by davidoesch** [comment]
Yes,

**Comment by ponceta** [comment]
It is strange because we use lon/lat everywhere else (except on the search bar where X comes first)

![image](https://cloud.githubusercontent.com/assets/8614223/5871185/87040c2e-a2d9-11e4-8208-6b984b8bf6e6.png)

There's maybe a consistency issue here :)

**Comment by davidoesch** [comment]
yes this is a consistency issue to some part
geometers had agreat influence here .-)

fix it in the footer (the ISO representation)
tooltip is ok (The geometer representation)

**Comment by ponceta** [comment]
It is coming from OL3 design
https://github.com/geoadmin/ol3/blob/master/src/ol/coordinate.js#L322
@oterral how do you usually fix this kind of bug? 
Workaround? New functions YX for OL? Displaying only one?

**Comment by oterral** [comment]
Modifiy here: https://github.com/geoadmin/mf-geoadmin3/blob/2c2108158acdec34a2a27a4c7f6b1b33138d3457/src/js/MousePositionController.js#L35

**Comment by oterral** [comment]
And use this function http://openlayers.org/en/master/apidoc/ol.coordinate.html?unstable=true#format instead of toStringXY

**Comment by ponceta** [comment]
ty
