### ISSUE TITLE
Print in FR: wrong disclaimer link

### ISSUE THREAD

**Issue by p1d1d1** [geoadmin/mf-geoadmin3#2110]
Open map.geo.admin.ch in FR and print.
Disclaimer is pointing at: http://www.disclaimer.admin.ch/conditions_dutilisation.html
This is wrong. The right address is:

http://www.disclaimer.admin.ch/informations_juridiques.html

**Comment by cedricmoullet** [comment]
@mariokeusen is it not a translation issue ?

**Comment by ponceta** [comment]
No it is in the yaml file, I'll correct it

**Comment by ponceta** [comment]
Testlink is in the PR
