### ISSUE TITLE
Share : Twitter : use always shortened link

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#2113]
reproduce
on win8.1 latest Chrome
load http://map.geo.admin.ch/?topic=ech&lang=de&X=193488.00&Y=569535.85&zoom=5&bgLayer=ch.swisstopo.pixelkarte-farbe&catalogNodes=457,532,687,639,653,702&layers_opacity=1,0.5,1,0.3,1&layers=ch.swisstopo.swissalti3d-reliefschattierung,ch.swisstopo.vec25-strassennetz,ch.astra.ausnahmetransportrouten,ch.bafu.laerm-strassenlaerm_tag,KML%7C%7Chttp:%2F%2Fgpx2kml.com%2Fpublic%2F2015%2F01%2F19%2Feldr43q22_exercise-2013-6-26.kml

share  link via twitter
-> result
URL is shortened by twitter, but not correctly KML does not show

Proposal: do always use shorten URL on the geo.admin.ch before it is shared via twitter

**Comment by cedricmoullet** [comment]
We should probably shorten the link before sending it to twitter

**Comment by ponceta** [comment]
I do not understand what's wrong with it? Tested this morning, went correctly shortened by twitter and back to the same url on map.geo.admin.ch.

http://map.geo.admin.ch/?topic=ech&lang=de&X=193488.00&Y=569535.85&zoom=5&bgLayer=ch.swisstopo.pixelkarte-farbe&catalogNodes=457,532,687,639,653,702&layers_opacity=1,0.5,1,0.3,1&layers=ch.swisstopo.swissalti3d-reliefschattierung,ch.swisstopo.vec25-strassennetz,ch.astra.ausnahmetransportrouten,ch.bafu.laerm-strassenlaerm_tag,KML%7C%7Chttp:%2F%2Fgpx2kml.com%2Fpublic%2F2015%2F01%2F19%2Feldr43q22_exercise-2013-6-26.kml

**Comment by ponceta** [comment]
See [here](https://twitter.com/Arnaud_Poncet_M)

**Comment by davidoesch** [comment]
Take the win8.1 test machine with Chrome And reproduce hanspi s Demo last Friday

**Comment by ponceta** [comment]
Can't reproduce.
Did you accept the third party data agreement?

**Comment by ponceta** [comment]
https://twitter.com/Arnaud_Poncet_M/status/559605953554038784

**Comment by davidoesch** [comment]
If you reproduce it exactly how Hanspi did on the same machine --- You dont receive an faulty link? We reproduced IT Twice

**Comment by ponceta** [comment]
I don't know, I clicked on the proposed link on map.geo.admin.ch, click share, click twitter, posted on my profile, tested the link, is the same. We can try it again tomorrow or later.
