### ISSUE TITLE
WMTS Tile service for lubis?

### ISSUE THREAD

**Issue by ponceta** [geoadmin/mf-geoadmin3#2114]
Since it was mentioned in #2099, for printing time series maps and lubis images is a use case (but it should not only be numbers!?), why don't we have a map layer for lubis? Rights? Authorizations?

This could be great! Clicking on points to see on image after another is boring.

**Comment by davidoesch** [comment]
Rights ... GeoV swisstopo

besides that: how do you want to print the images? just the center? on a 4?
I close this
