### ISSUE TITLE
[WIP] [Testing Mobile] Browserstack

### ISSUE THREAD

**Issue by ponceta** [geoadmin/mf-geoadmin3#2115]
@gjn I'll create the mobile tests this week, but since it needs a few parameters different from the standard browsers, I suggest to create it separately from the actual testing machinery. Last time I tried this, it was a bit unstable so I think it's another reason to have it separated from the actual testing. 
(and maybe merge both in the future if it comes more stable)

**Comment by ponceta** [comment]
@gjn @oterral is it possible to have a DOM indicator after the build.js has been loaded for e2e on mobile? Or what is the last element which is loaded? Because I have troubles with uncompleted app when testing on mobile.

![image](https://s3.amazonaws.com/testautomation/08cfc8e9dd07f7df96332d9df93790b2ed35c2ed/screenshot-5.jpeg)

It could be great to have something like https://github.com/geoadmin/mf-geoadmin3/blob/0a187bb55024342427a31bc95e863a1510086411/src/components/print/partials/print.html#L44-L45

**Comment by gjn** [comment]
The catalog is one of the last, as in desktop (see start_test.js). Might be
on mobile, the element is invisible, but it should be in the DOM.

I'm sure there are others that could be used. Inspect the DOM on mobile
after the page is loaded. (There are lots of ivisible items)
Am 26.01.2015 10:22 schrieb "Arnaud Poncet-Montanges" <
notifications@github.com>:

**Comment by oterral** [comment]
With the  version in master if the loader element (the red bar) is hidden , that means the page is loaded.

**Comment by ponceta** [comment]
Yes, that's why I wanted to check if loader is hidden before beginning tests. But for that I need to find an empty DOM element that says that like we did for print.

**Comment by oterral** [comment]
https://github.com/geoadmin/mf-geoadmin3/blob/master/src/index.mako.html#L199  is it not enough?

**Comment by gjn** [comment]
IAs said, inspect the DOM. Check for attributes that change when page is
loaded. I'm sure you can use the catalog or loader element for this. The
loader likely adds an attribute when done, or you could check for
visibility or whatever.

We should avoid adding DOM elements for testing unless absolutely
necessary, as was the case for print.
Am 26.01.2015 11:36 schrieb "Arnaud Poncet-Montanges" <
notifications@github.com>:

**Comment by ponceta** [comment]
![iphone5](https://cloud.githubusercontent.com/assets/8614223/5915135/3e21b994-a602-11e4-8b71-e150683b1eb7.jpeg)
 
Mmmh... DOM is here... but the eye of selenium can't see it! :S

**Comment by ponceta** [comment]
https://www.browserstack.com/automate/builds/dddb1242fb9f3ffe297b057e6da2ea964b4caf1a/sessions/bd8dc8911118c13ba1d836494a7252cce83c8b3a#automate_button

This worked yesterday

https://www.browserstack.com/automate/builds/dddb1242fb9f3ffe297b057e6da2ea964b4caf1a/sessions/6c5a04e3cbc5c798b1d0f1a523c912440833877d#automate_button

And doesn't work anymore today... I'll try again later...

**Comment by gjn** [comment]
@ponceta Can we close this?

**Comment by ponceta** [comment]
Yes, this will be discussed directly after our tests directly in the PR
