### ISSUE TITLE
Map on mobile confuses extent

### ISSUE THREAD

**Issue by gjn** [geoadmin/mf-geoadmin3#2118]
**This is on integration only, detected during today's deploy. We can't deploy until this is fixed.**

In low zoom levels (0, 1, 2, x), the extend somehow gets confused and moves with the map when panning, rendering the map unusable at these zoom levels. Note that the same problems persist in higher zoom levels, but is only relevant at the boarder of the defined extent (so less visible to the user).

Problem prevalent on Nexus4 (hardware) and under following emulations in chrome (Nexus 4, IPhone4, IPhone5, Nexus7). 

No problem detected on IPad (hardware)

TestLink: mf-geoadmin3.int.bgdi.ch

It's also reproducable with an offical ol3 example using same hardware/emulators: http://openlayers.org/en/v3.1.1/examples/wms-image-custom-proj.html

@oterral @elemoine @fredj

**Comment by gjn** [comment]
Most likely the same issue as https://github.com/openlayers/ol3/issues/3148

**Comment by fredj** [comment]
@geoadmin/re3 : can you please try the patch at openlayers/ol3#3148 and report back if it's working for you?

**Comment by oterral** [comment]
@fredj yes I'm on it

**Comment by oterral** [comment]
[Test link](http://mf-geoadmin3.dev.bgdi.ch/teo_ratio/?lang=fr&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&X=190000.00&Y=660000.00&zoom=1)

**Comment by oterral** [comment]
@fredj yes that works thanks
