### ISSUE TITLE
Opacity and visibility of a dropped KML layer is added to the permalink

### ISSUE THREAD

**Issue by oterral** [geoadmin/mf-geoadmin3#2124]
1) Drop a KML on map.geo.admin.ch
2) CHange visibility or opacity of the this layer
3) the modiifcation is taking in  account by permalink params 

Expected : 
 no modifications of the permalink

**Comment by ponceta** [comment]
By dropping you mean with url? 
Because if you drag and drop a local file, it won't be part of the permalink (logic)

**Comment by ponceta** [comment]
I see what you mean, and this could be annoying because if you copy the permalink it will delete the droped file and confuse the opacity order of online layers.
