### ISSUE TITLE
Measure : select geometry from import

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#2130]
Use case:
KML import containing line, point, polygon. User wants to extract  distance / profile / area of one geometry element

Proposal
add in measure tool as below "profile","save" a third button " Select" whcih is only active if  a imported or drawn layer is active. Similar to "edit" ind raw an element can be selected.

**Comment by gjn** [comment]
Alternative proposal:

When kml is loaded and geometry is selected, open a tooltip with a 'create profile and measure' link, which will open the profile with this geometry. This could be in addition to Dave's original proposal.

**Comment by davidoesch** [comment]
when you klick on a KML you expect the tooltip of the KML eg
http://map.bafu.admin.ch/?topic=bafu&X=190000.00&Y=660000.00&zoom=1&lang=en&bgLayer=ch.swisstopo.pixelkarte-grau&layers=KML||http:%2F%2Fwww.ubst.bafu.admin.ch%2Fkml%2Fwald%2Fschweizer-holz_de.kml

not a measure info.....

**Comment by gjn** [comment]
Agree. Tooltip of KML, but there you could add a _link_ (at bottom or wherever) to measure/draw profile, which will open the draw/profile dialog with the selected kml element as geometry to draw profile and measure.

**Comment by davidoesch** [comment]
+1

**Comment by davidoesch** [comment]
@cedricmoullet related to UI session on 4.6.2015

**Comment by cedricmoullet** [comment]
Is fixd in the new draw
