### ISSUE TITLE
Topic name does not switch

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#2131]
all brwoser all os

open map.geo.admin.ch
-> "Geokatalog" is active
switch topic to aviation

Result:
topic name above tree is "Geokatlog"

Expected result
topic name above tree is "Aviation"

**Comment by gjn** [comment]
On it. Regression introduced by https://github.com/geoadmin/mf-geoadmin3/commit/1207a2bee5e694e46491763e3d9700ee2d849cb4
Fix coming soon.
