### ISSUE TITLE
Query doesn't find results

### ISSUE THREAD

**Issue by cedricmoullet** [geoadmin/mf-geoadmin3#2138]
Can't find object CH030000101210126010 with Query tool in http://map.geo.admin.ch/?X=190000.00&Y=660000.00&zoom=1&lang=fr&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.fixpunkte-lfp1

![image](https://cloud.githubusercontent.com/assets/319676/6055688/87d30558-ad04-11e4-80ed-ac8fb8782df2.png)

**Comment by loicgasser** [comment]
https://github.com/geoadmin/mf-chsdi3/pull/1210 fixes the issue
