### ISSUE TITLE
Measure: display the length on map 

### ISSUE THREAD

**Issue by oterral** [geoadmin/mf-geoadmin3#2139]
Like the new example : https://github.com/openlayers/ol3/pull/3206

@cedricmoullet, @davidoesch ?

**Comment by cedricmoullet** [comment]
Nice. Mobile support ?


On Thu, Feb 5, 2015 at 1:41 PM, oterral <notifications@github.com> wrote:

> Like the new example : openlayers/ol3#3206
> <https://github.com/openlayers/ol3/pull/3206>
>
> @cedricmoullet <https://github.com/cedricmoullet>, @davidoesch
> <https://github.com/davidoesch> ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geoadmin/mf-geoadmin3/issues/2139>.
>



-- 
Twitter: http://twitter.com/cedricmoullet
Linked In: http://www.linkedin.com/in/cedricmoullet

<http://twitter.com/cedricmoullet>

**Comment by ponceta** [comment]
Nice tool! (Could it be used to show dynamically elevation to the profile?)

**Comment by davidoesch** [comment]
defintely: so far  nice mobile support in http://www.stadtplan.bs.ch

**Comment by gjn** [comment]
Btw: measure on mobile could be a next nice feature...

**Comment by oterral** [comment]
Done on prod
