### ISSUE TITLE
Measure: cancel drawing with right click

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/mf-geoadmin3#2150]
@oterral @cedricmoullet @davidoesch 

Would be nice no?

**Comment by davidoesch** [comment]
+1 !

**Comment by kandre** [comment]
+1, I always forget where to click in order to erase

**Comment by oterral** [comment]
may be we shouldn't  have something to stop drawing and display the line only when the user adds a new point.

**Comment by cedricmoullet** [comment]
Should be put in V2
