### ISSUE TITLE
Home screen app: map parameters (zoom, locations) are not kept (mobiles)

### ISSUE THREAD

**Issue by kandre** [geoadmin/mf-geoadmin3#2153]
Home screen app: map parameters (zoom, locations) are not kept (mobiles), easily reproductible:

1. Add to home screen
2. Launch the app
3. Come back to home screen
4. Lauch the app again
Result: map comes back at initial state

**Comment by oterral** [comment]
every device ?

**Comment by kandre** [comment]
It got it on apple Ipad and Iphone, not tested yet on android

**Comment by oterral** [comment]
I'm not sure we can do anything for that

**Comment by ponceta** [comment]
It is browser dependent. On chrome mobile it works fine!
