### ISSUE TITLE
Zipcodes contains no names

### ISSUE THREAD

**Issue by gjn** [geoadmin/mf-geoadmin3#2160]
@davidoesch is there a special reasons why we don't put related commune name into zipcode searchable index? (It's put in the label, but it's not searchable on this index)

See discussion here:
https://groups.google.com/forum/#!topic/geoadmin-api/mSgiE0cKdN4

See relevant sphinx index code here:
https://github.com/geoadmin/service-sphinxsearch/blob/master/conf/search.conf.part#L151

**Comment by gjn** [comment]
ping @oterral This is related to the api group question.

**Comment by davidoesch** [comment]
Zipcodes are Free in BFS as in swisstopo as in Cadastre datasets: so pls add them

**Comment by procrastinatio** [comment]
Also in the query tools ? Much simplier IMHO

**Comment by gjn** [comment]
Yes, query tools.

Also, he could use the find service as well.
