### ISSUE TITLE
[mobile]: different landscape layout on iphone and samsung galaxy

### ISSUE THREAD

**Issue by mariokeusen** [geoadmin/mf-geoadmin3#2167]
UC1: open app with an iphone 4s (safari) and switch from portrait to landscape
UC2: open app with a samsung galaxy (chrome) and switch from portrait to landscape
Result 1: 
![mobile_layout_iphone](https://cloud.githubusercontent.com/assets/4577749/6330814/cf86b20c-bb7b-11e4-828e-bbc70541a98c.PNG)
Result 2:
![mobile_layout_galaxy](https://cloud.githubusercontent.com/assets/4577749/6330838/e544c890-bb7b-11e4-8ed3-7fe1a16620e9.PNG)

Not the same layout on both devices (we have the "tablet" layout already on the galaxy)

Expected: I would expect Result 1 on both devices
Is this wanted? To be discussed.

**Comment by ponceta** [comment]
@cedricmoullet @ least galaxy users can see where the menu is!

**Comment by oterral** [comment]
As we have done for small screen height on desktop, for extra small window height we could force to display mobile version. don't know if it's relevant,

**Comment by gjn** [comment]
hmm, isn't this what 'responsive' is supposed to do? I don't see the issue here.
(of course, I would be +1 to abandon the tablet mode, but that's another story).

**Comment by mariokeusen** [comment]
Hmja, it's a matter of definition, which screen size is considered as a "tablet" and which as a "smartphone". For me: on one hand I would expect that a samsung galaxy S4 mini should get the same layout as an iphone but on the other hand it's nothing severe and one can work with both layouts.

Anyway: this was a confused user, who told me about this difference via helpdesk telephone.

**Comment by ponceta** [comment]
I think there is an issue here, because our way to make the responsive design in function of the screen resolution won't last much longer. In the next months, we will see users with retina like resolution displays like the S6 edge with QHD resolutions that are larger that our desktop resolutions (2560x1440) on 5 inches screens.

http://www.samsung.com/fr/consumer/mobile-phones/smartphones/galaxy-s/SM-G925FZWAXEF
