### ISSUE TITLE
loading icon in tablet (?) mode: pls replace

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#2168]
Hi
the loading  icon: is very intrusive and big- and it overlays the federal logo ---

therefore: for dekstop/tablet size
replace the *rotating arrows*
![unbenannt](https://cloud.githubusercontent.com/assets/4577727/6337187/79143f20-bba8-11e4-866b-dc244a0610ce.png)

with the loading *bar* as in mobile
![unbenannt1](https://cloud.githubusercontent.com/assets/4577727/6337322/5eb5933a-bba9-11e4-828b-0fd4ac244974.PNG)

**Comment by oterral** [comment]
good decision.
