### ISSUE TITLE
Embed map

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#2182]
- [x] create embed.html

Create interface
- [x] add Text "Embed map" with one line with default code and disclaimer below
- [x] add show More options above disclaimer
- [x] "Show more" modal window contains
 Pulldown with
    - [x] preset sizes
    - [x] Custom sizes (minimum 200x200px), no max size limit
    - [x] Preview map (adapting to size)
- [x] disclaimer "By embedding this map, you agree to the terms of service" with link to http://www.geo.admin.ch/internet/geoportal/en/home/geoadmin/contact.html#iFrame

Embed map
- [x] white Box (analogue gmap embed) with top left, transparent outside: it is a link it goes to the map.geo.admin.ch the full size application (deskop mode)
 - [x]   icon (Favicon ) 
 - [x]   Text "view on map.xxx.admin.ch" xxx replaced by source domain
 Icons 
- [x] no geolocation
- [x] no overview
- [x] Footer left keep scale ( max size to middle of width) 
- [x] Footer right "C Data:" as in mobile ( max size to middle of width) if bigger then add 3 points (...) on mouseover show all dataowners links etc
- [ ] detect if embed.html is used in an iframe or embed context, if not display only a text "The map.geo.admin.ch Maps Embed must be used in an iframe." (Analogue to Google maps embed)

**Comment by davidoesch** [comment]
oh, and I forgot_ would be nice to have it online by mid march

**Comment by gjn** [comment]
+1000 for this from my side.

Do we have a max-size limitation?

**Comment by davidoesch** [comment]
Max size --- a good lets see what gmap has as max size use this one

**Comment by davidoesch** [comment]
Max size --- not limits: (aka fullscreen) gmap does not have one neither

**Comment by oterral** [comment]
@davidoesch  does we allow rotation?  time selector ?

**Comment by davidoesch** [comment]
Nope

**Comment by oterral** [comment]
Are you sur for the time selector if a lubis layer is displayed that can useful no?

**Comment by davidoesch** [comment]
The User embeds  a permalink - if there is a rotation or time parameter in there: it will be taken into account in the embed map. But I'm not sure that we should show the time selector /slider as button. But we should since otherwise the year is not shown ... So take it into account for rotation (user knows where north is) and the mobile time selector (pull down so it fits even on the 200 by 200 px)

**Comment by oterral** [comment]
Ok

**Comment by oterral** [comment]
Here a first example of the most complicated use case we have :  
http://mf-geoadmin3.dev.bgdi.ch/teo_embed/embed.html?lang=fr&topic=luftbilder&bgLayer=ch.swisstopo.pixelkarte-grau&X=205900.00&Y=590450.00&zoom=4&layers_opacity=1,1,0.75&catalogNodes=1179,1180,1186&layers_timestamp=19791231,,&time=1979&crosshair=bowl&swipe_ratio=0.46&layers=ch.swisstopo.lubis-luftbilder_schwarzweiss,ch.swisstopo.lubis-luftbilder_farbe,ch.bafu.biogeographische_regionen

@davidoesch @cedricmoullet @gjn @loicgasser @procrastinatio what do you think?

**Comment by davidoesch** [comment]
A) Complexity
- you can adda one complexity more: map is rotated.

B) Improvement
Timeslider: *Always* use the wheel/mobile version for selection of the
year, for all screen sizes: in this case the slider does never cut the link
and icon on top left....

**Comment by oterral** [comment]
A) Yes but there is no permalink for rotation :) you need to do it manually

**Comment by oterral** [comment]
@davidoesch what about the tooltip ? do we allow it?

**Comment by gjn** [comment]
I like it!

(Agree with B), even though i would not put timeselector, but only currently selected time as text. If they want to change the time, they have to jump to map.geo.admin.ch. The webmaster who embed a map want to embed a certain state)

**Comment by davidoesch** [comment]
tooltip on features yes elements, mouseklick right no

**Comment by davidoesch** [comment]
+1 for time "only currently selected time as text. If they want to change
the time, they have to jump to map.geo.admin.ch."

**Comment by oterral** [comment]
if they have multiple time enabled  layer, how should we display this infrmation

**Comment by davidoesch** [comment]
Currently In mobile: no time slider is shown in this case - unless you open the menue you don't see the time stamps. This is how we should deal here as well:

- show no time slider - the user has to click on the "view large map."




Other ideas ?

**Comment by oterral** [comment]
good for me

**Comment by davidoesch** [comment]
did I already say that : It is a GREAT function?

**Comment by davidoesch** [comment]
- [ ] detect if embed.html is used in an iframe or embed context, if not display only a text "The map.geo.admin.ch Maps Embed must be used in an iframe." (Analogue to Google maps embed)

is must otherwise it is an abuse

**Comment by gjn** [comment]
But why? What can you do with embed that you can't with index.html/mobile.html?

**Comment by davidoesch** [comment]
index.html/mobile.html are fully fledged applications : with embed it is too simple to create a standalone fullscreen app without using the fullscreen mode of the original app---- BTW google solves this in the same way....

**Comment by gjn** [comment]
I don't see this as a problem. The link to map.geo.admin.ch would still be there (or he removes it with js, but in that case he's violating the TOS already).
You expect app devs misusing it to create apps? What kind of app would that be?

**Comment by gjn** [comment]
btw, youtube does not have such protection: https://www.youtube.com/embed/cvMy1xOh6cw ;)

**Comment by davidoesch** [comment]
la fameuse hybrid webapp.. an app with only the pixelkarte and you wont be
able to leave the screen..... this why google introduced this

**Comment by davidoesch** [comment]
https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d21803.485960074377!2d7.418264149999999!3d46.91381440000001!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sde!2sch!4v1426086069618

does

**Comment by gjn** [comment]
hmm. no fan of this. I would have nothing against such an app. It will contain a link to map.geo.admin.ch!

Anyway, there's a problem because we use the embed.html to get customized-sized preview in separate window....which won't be possible if we add this security. This is solvable by some hacking (include iframe in separate window), but don't know if possible for tomorrows deploy.

@oterral ?
