### ISSUE TITLE
[Search] Android (4.4) Chrome

### ISSUE THREAD

**Issue by ponceta** [geoadmin/mf-geoadmin3#2190]
The search prevent the user from correcting more than one character his input:

Eg.
I type wandrr (instead of wander)
I type two backspace
I type er
the autocompletion writes wandrer

The user needs to clear the search field before he can rewrite his query

This is NOT a regression!

**Comment by gjn** [comment]
I doubt we can do anything about it. It's a `won't fix` for me. @ponceta Is there a setting where you can disable the autocompletion?

**Comment by gjn** [comment]
Or maybe test on how other sites with input boxes behave?

**Comment by ponceta** [comment]
Browser specific : Solution : De-activate autocompletion for formulars in parameters/autocompletion

I think we should wait the user to validate his query on mobile because the queries/loading bar are quite annoying (and displaying results with keyboard activated doesn't mean much IMO (1cm scrolling interface... not good for my big fingers))

**Comment by gjn** [comment]
So adding some sort of delay? (We had this before). Maybe it might be worth it.

**Comment by ponceta** [comment]
To be disscussed maybe, but for my smartphone it is just spamming fuzzy search results which I do not read since I'm not complete with writing my query! (But maybe I'm slow... should have a look at the users tests)

**Comment by gjn** [comment]
Compare with google search and google map search.
