### ISSUE TITLE
[Print] Legends are cut

### ISSUE THREAD

**Issue by pfanguin** [geoadmin/mf-geoadmin3#2191]
When there are a lot of legends, those on right are cut.

![print](https://cloud.githubusercontent.com/assets/6862714/6479789/2d51c892-c24b-11e4-9485-f257b6d9e418.PNG)

**Comment by oterral** [comment]
Print server bug , We can't do anything about it

**Comment by ponceta** [comment]
Maybe better with print v3?

**Comment by ponceta** [comment]
Tested with print v3, this is a won't fix.
