### ISSUE TITLE
measure: show intermediary results and hint for next mouseklick

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#2194]
as http://openlayers.org/en/v3.2.0/examples/measure.html 

- show results while drawing (see also https://github.com/geoadmin/mf-geoadmin3/issues/2139 )
- give hint on mouse position depending on state
 - click to start drawing
- click to continue drawindg doble click to stop

show results in polygon / at the end of line, make them selectable...

your thoughts?

**Comment by cedricmoullet** [comment]
I think we need to go away from the CAD principles

**Comment by davidoesch** [comment]
what does the averag user understand-- mspaint? picasa photo editor?.... 
Proposal
A) I'm really looking forward on how map.search.ch will solve this
B) gmaps: another approach: they added measure to the right cklick tooltip- IMHO would be easyfor us as well maps.geo.admin.ch/?widget=measure or even go completely the google way: measure only with right klick, show the distance on the map (their UUI is not CAD) and the area below the all in one search (? not that convinced...) play with it: IMHO it is realy nice

**Comment by oterral** [comment]
We hace use emapis for a beta test what do you think?   link to [emapis](http://web-emapis.prod.bgdi.ch/)

**Comment by AFoletti** [comment]
I really like the way emapis does that

**Comment by davidoesch** [comment]
Emapis has drawing?

**Comment by loicgasser** [comment]
Top right. I had a hard time finding it as well. But I don't think we have intermediary results there either.

**Comment by davidoesch** [comment]
Please with sugar on the top: remove the CD BUND from emapis ASAP ....this has nothing to do with geo.admin.ch

**Comment by oterral** [comment]
@davidoesch  see that with @p1d1d1 . We just follow their spec.

**Comment by oterral** [comment]
ah sorry @davidoesch , do you talk about about Copyright & Datenschutzerklärung in the bottom-right corner?  I thought you talk about the logo.

**Comment by davidoesch** [comment]
no ?im talking about the whole project

**Comment by davidoesch** [comment]
Tha drawing itself is nice.. as in google maps

**Comment by davidoesch** [comment]
@cedricmoullet related to UI session on 4.6.2015
