### ISSUE TITLE
measure window:cant move

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#2195]
FF 
prod
select tool measure
measure window opens bottom right
try to move the window

result:
measure window can not be moved

expected result
window can be moved

**Comment by ponceta** [comment]
Was this not a requirement to have a nice bottom large profile?

**Comment by davidoesch** [comment]
yes... but it covers on 16:10 screens haflf of the menu

why not add it back at the bottom as soon as the profile is activated

**Comment by ponceta** [comment]
@kandre ProfileMaster? what do you think?

**Comment by kandre** [comment]
Yes, I removed the draggable property weeks ago.

About the size of the profile/measure box, a PR #2176 from @loicgasser is under way, which is way nicer and improve the 16.10 screens problem. However it does not solve the fact that on small window's height, it can cover the menu. I propose to make the menu reactive to the measure/profile box as does the window's bottom

Regarding the popup moving to the bottom as soon as the profile is activated, nice idea (eventhough users tend to have panic attacks when they see popup, but that is another problem)

**Comment by davidoesch** [comment]
@cedricmoullet for the UI session on 4.6

**Comment by cedricmoullet** [comment]
Won't fix since new draw/measure will be finalized soon
