### ISSUE TITLE
Coordinate search "600 000 200 000"

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#2200]
old school user enter coordinates as ""600 000 200 000" (space after 3 digits) and not ""600000 200000"
currently "600 000 200 000" gives no result

**Comment by ponceta** [comment]
This was not not exactly no results : 
http://map.geo.admin.ch/?swisssearch=600%20000%20200%20000&X=190000.00&Y=660000.00&zoom=1&lang=fr&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe

But know it's right :
http://mf-geoadmin3.dev.bgdi.ch/?swisssearch=600%20000%20200%20000&X=200000.00&Y=600000.00&zoom=8&lang=fr&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe

**Comment by ponceta** [comment]
Since we support 
600'000 200'000 and 600 000 200 000, we should also support 
2'600'000 1'200'000 and 2 600 000 1 200 000
Right?

**Comment by davidoesch** [comment]
+1

**Comment by gjn** [comment]
Please not...

**Comment by davidoesch** [comment]
consistency FTW. But I see the issue with autocomplete

**Comment by ponceta** [comment]
Ah that's the thing! :) ok nevermind. (this concerns a small minority of old old people^^ ;)

**Comment by gjn** [comment]
Will be deployed today.
