### ISSUE TITLE
embed iframe code: src='//map.geo.admin.ch/

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#2220]
is  "//map" really best practice?

IMHO
change

//map

<iframe src='//map.geo.admin.ch/embed.html?topic=ech&lang=de&X=273253.00&Y=623352.00&zoom=9&bgLayer=ch.swisstopo.pixelkarte-farbe' width='400' height='300' frameborder='0' style='border:0'></iframe>

to
https://map

<iframe src='https://map.geo.admin.ch/embed.html?topic=ech&lang=de&X=273253.00&Y=623352.00&zoom=9&bgLayer=ch.swisstopo.pixelkarte-farbe' width='400' height='300' frameborder='0' style='border:0'></iframe>

**Comment by gjn** [comment]
See discussion here: https://github.com/geoadmin/mf-geoadmin3/pull/2216

Also, we don't yet fully support https - it's tested on all browsers and with complete testbook.

**Comment by davidoesch** [comment]
Hmm even if it is not https. Agnostic URLs look wrong to a standard webmaster .....

**Comment by oterral** [comment]
I've tested https om map.geo.admin.ch and it seems there is some warnings in the logs in these components:


 - Help: images in html content
 - Import WMS : Url of tiles WMS layer added
 - Import KML: Images google in kml, lien vers KML validator
 - Map: Sometimes tiles SSL error with WMTS
            Urls of WMS layers like luftfahrthindernisse are http

**Comment by oterral** [comment]
In api3.geo.admin.ch, there is sometime some files loading problems in the examples with https, but maybe it's simply the network.
