### ISSUE TITLE
iOS offline : broken

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#2221]
as discussed

ios device iphone

start map.geo.admin.ch
save offline
after offline complete
-> storead area is white / not tiles

**Comment by cedricmoullet** [comment]
This is a candidate for an emergency deploy

**Comment by gjn** [comment]
Can confirm this in our iPad Mini. Even reloading the page (which 'fixed' it last time) did not help. No tiles are shown on the downloaded area.

**Comment by oterral** [comment]
it seems to affect only bg layer

**Comment by oterral** [comment]
CORS problem

**Comment by oterral** [comment]
fixed on prod
