### ISSUE TITLE
Search ui improvements

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/mf-geoadmin3#2227]
Hi,

Here are a couple of suggetions.

1. Recently searched field

a. Type a searchText in the search bar.
b. Select a result
c. Result is stored in a local cache (best would be local storage for persitence)
d. Delete the result
e. Always show the 2 lastest searches per default
(-> we had that in RE1 of mobile... and ditched it)
f. Filter recently searched entries when typing a new word

2. Show borders on location selection for NPA, communes, district and cantons (we can do it as we have the refrence to the feature ID). I would use a dark red dashed line.

(->in this case we have to assume that we have to work with the swissboundaries technical layers) 

3. Use an animated zoom function for zooming to new locations. It is probably better from a user perspective as we can see from where we're starting to where we're ending. (would be a function defined in gaMapUtils we can call from anywhere)
-> not really convinced..

4). add geolocation as in map.search.ch as first suggestion when searching for a location

@davidoesch @cedricmoullet Anything you might consider to implement?

And of course the radio button (TripAdvisor Style) to filter what kind of search one wants to perform, but that will be discussed next week.

**Comment by davidoesch** [comment]
added comments inline

**Comment by loicgasser** [comment]
As a side note, those 3 features are used in google maps, search.ch and local.ch.

**Comment by davidoesch** [comment]
we will adress this in one of the next UI/ix meeting @cedricmoullet for taking this one up into the meeting minutes
