### ISSUE TITLE
ch.swisstopo.vec200-landcover not available

### ISSUE THREAD

**Issue by p1d1d1** [geoadmin/mf-geoadmin3#2229]
ch.swisstopo.vec200-landcover in not  visualised in map.geo.admin.ch

**Comment by davidoesch** [comment]
from zoom=6 onward it works

**Comment by AFoletti** [comment]
will look into it ASAP

**Comment by AFoletti** [comment]
wow, that's strange.
Looks like we have blank tiles for the first few zoomlevels [1] and [2] but the WMS looks good [3].
I think a good solution would be to regenerate some zoomlevel and flush the cache.
Now... how's possible that we never noticed that?

[1] http://wmts5.geo.admin.ch/1.0.0/ch.swisstopo.vec200-landcover/default/20140101/21781/14/0/0.png
[2] http://wmts5.geo.admin.ch/1.0.0/ch.swisstopo.vec200-landcover/default/20140101/21781/17/1/12.png
[3] http://s.geo.admin.ch/6357b64cab

**Comment by ltclm** [comment]
there is a maxscale limitiation in the layer snippet, (wms-bod.de.map) 
```
MAXSCALEDENOM 250001
```
preventing the layer to be visible these scales.

**Comment by AFoletti** [comment]
ouch... I looked at the untranslated WMS, where the MAXSCALEDENOM is not present. That left me puzzled.
Makes this limitation really sense?
I suggest deleting it and regenerate some zoomlevels, but I don't know the layer history and there is maybe an explanation for that

**Comment by ltclm** [comment]
the maxscaledenom is for performance reasons in our feebased service wms-swisstopwms.
i have generated the tiles with the raw version of wms-bod and i have updated the layer config in the tilegenerator.

**Comment by AFoletti** [comment]
thanks Marcel. Looks good on prod :)

**Comment by procrastinatio** [comment]
Side note the layer _ch.swisstopo.vec200-landcover_ wil at show at all scale in map.geo.admin.ch, only under _maxscaledenom_ in WMS and only approx. above _maxscaledenom_ in WMTS reprojected.
