### ISSUE TITLE
[redlining]: font size for labeling adjustable?

### ISSUE THREAD

**Issue by mariokeusen** [geoadmin/mf-geoadmin3#2231]
UC: open app, open the drawing tool, chose label, write a text somewhere into the map
Result: text is visible with a fix font size
Enhancement proposal: font size can be chosen, between e.g. small, medium and large or with point number.

What are your 2 cents @davidoesch @cedricmoullet ?

This is an often heard customer wish and we should discuss, if we want to do something in this direction or not.

**Comment by davidoesch** [comment]
we had this in re2-> but will take this into account since we have to review the complete #redlining process. The reason was: keep it simple . 
approach: https://www.mapbox.com/editor/#data

**Comment by mariokeusen** [comment]
Had another customer request for that today. Do you have some news, if we'll do it or not?

**Comment by davidoesch** [comment]
WE are working on that : end of q3 latest

**Comment by davidoesch** [comment]
@cedricmoullet will this be a wontfix since https://mf-geoadmin3.dev.bgdi.ch/teo_new_draw/ it's not included yet? IMHO it makes sense to add icon and text size in pulldown in at least a second step

**Comment by cedricmoullet** [comment]
I also see that as a second step.

**Comment by davidoesch** [comment]
the i reopen it , as a possible enhancement

**Comment by cedricmoullet** [comment]
It has to be put in the V2
