### ISSUE TITLE
[WGS84 Pos not displayed anymore]

### ISSUE THREAD

**Issue by ponceta** [geoadmin/mf-geoadmin3#2252]
Is this a regression? 

From Helpdesk

`Hallo, Wieso zeigt es die WGS 84 Koordinaten nicht mehr an Gruß Herre.`

**Comment by ponceta** [comment]
@oterral @procrastinatio The issue seems to be come from the backend since no modification was induced to the mouse position controller.

**Comment by oterral** [comment]
Missing axport for ol, fix is coming

**Comment by ponceta** [comment]
Ok ty!
