### ISSUE TITLE
Feedback widget: send a copy to user if email provided

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#2255]
If a user creates a feedback and adds his e-mail, on submit a copy of the mail is sent as well to the e-mail provided.

your thoughts?

@cedricmoullet 
@p1d1d1 
@danielabrandt

**Comment by p1d1d1** [comment]
I'd say... "customer care". So yes. Especially if we go forward with a follow-up for revision messages: to be discussed at a next meeting with Topo.

Would it make sense to have a "tracking ID" already now? 
I mean also before the follow-up process with Topo  is in place?

**Comment by davidoesch** [comment]
as discussed with @cedricmoullet risk of beeing abused by a spabot is to high ...therefore I close this one
