### ISSUE TITLE
Print at 1:300'000 scale

### ISSUE THREAD

**Issue by AFoletti** [geoadmin/mf-geoadmin3#2256]
A user suggested to add a 1:300'000 option to the list of printing scales in order to be able to print out the Glider Chart at its real scale.
@cedricmoullet and @davidoesch acecpted the proposal.

Goal:
to add the 1:300'000 printing scale to the list.

**Comment by ponceta** [comment]
ty @kandre

**Comment by ponceta** [comment]
Already live on dev
