### ISSUE TITLE
UI draw&measure combined

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#2258]
##  VERSION 1.0

- [x] Radius Azimuth (feature parity)
- [x]  line/icon width /size  (feature parity)
- [x] when drawing a polygon after a line : show "measure" instead of "show profile"
- [x]  change order link  (Admin link as second link) since share is what you want
- [x]  Put more explicit labels for links : "Link to edit your map (or
drawing) later" instead of "Administration link", and "Link to share your map (or drawing)" instead of "Share link"
- [ ] In object boxes : Remove the border surrounding icons, colours, etc (which is not necessary). It 
would further help to give an impression of simplicity.
- [x] put saving  at the top
- [x]  Keep the button red as along as
- [x] kill  the cross at right 
- [ ]  shared link: https://mf-chsdi3.dev.bgdi.ch/shorten/65563e569d  polygon/lines are clcikable and return profile & distance/surface at the bottom
- [x] For measurements, in object box : It is probably unnecessary to have the "Distance / Area" tab available, as the values are already displayed directly on the object (further simplification).

@pfanguin if above are solved
- [ ] update help draw http://help.geo.admin.ch/?id=67
- [ ] update help measure http://help.geo.admin.ch/?id=68 

##  VERSION 2.0 

- [ ]  Rectangle
- [ ]  Circle
- [ ]  Listings markers: within pop up up
- [ ]  enter multiple symbols in a row without having to click each time a button (use case: the guy who wants to mark a route with points )
- [ ] small screen: 
      - "plus"  items of menues are covered

- Styling 
      - [ ]  Polygon/rectangle: fill color and width (Slider? as in gmaps) 
      - [ ]  annotation: size

- [ ]  set the "Name" of the layer, and use it as kml exportname as well
- [ ] embed in more button "embed into my site"

on hold/ open points
- [ ]  Feature list in accordeon
- [ ]  "Delete last point" function, UNDO / REDO
- [ ]  showing a link between an object and an object box with a line or fit it to image

**Comment by oterral** [comment]
@davidoesch @cedricmoullet @gjn @loicgasser @procrastinatio 

first attempt with an interface a bit like gmaps : http://mf-geoadmin3.dev.bgdi.ch/teo_new_draw/?lang=fr&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&X=205114.57&Y=753540.73&zoom=1

**Comment by kandre** [comment]
Nice, I like the palette interface, without tooltip

**Comment by davidoesch** [comment]
- no  need for creating a pulldown for line or area- if it is closed it is automatically an area : see gmap     https://www.google.com/maps/d/
- feature_properties: to big (scrolling.... not needed) do it as gmap: a pulldown to choose from Etiquette/Description, so only one filed is presents
- show vertexex of line/polyline ( as in gmaps): highlight them on mouse over, so the user can drag them
- measure:show distance while  drawing as in gmaps standard interface

the accordeon: removing all others menue items. tempting, but  keep it open otherwise : how to come back?

**Comment by cedricmoullet** [comment]
The idea is to discuss this proposal during the usability sessions

Envoyé de mon iPhone

**Comment by davidoesch** [comment]
@cedricmoullet can we pick up this on the meeting 4.6.2015? thanks

**Comment by oterral** [comment]
@davidoesch  is this still wanted ? 

 `link: "With the following links, you can modify (URL) or share (URL) your drawing"`


Or we put 2 text inputs with the automatic selectionon focus  and the copy button?

**Comment by p1d1d1** [comment]
@all are you considering implications for the feedback tool?

**Comment by oterral** [comment]
yes we decide to keep the same design but without the more and measure buttons

**Comment by davidoesch** [comment]
@oli 2 text Inputs with the automatic selectionon focus and the copy button with the Text as above... Lets test

**Comment by gjn** [comment]
As @p1d1d1 mentioned, the feedback integration has to be there in version 1.0. @oterral Could you add it to the open issues list?

**Comment by oterral** [comment]
@gjn  it works now

**Comment by gjn** [comment]
Great! I'll code review this tremendous work once my brain is heated up.

**Comment by gjn** [comment]
Help on the object dialog is always pointing to measure. I think the help there should be removed and a help button maybe shown in the header next to back button to explain the draw/measure mode on one page (instead of 2 separate ones as right now)

**Comment by davidoesch** [comment]
Amado is working in the help --- there will be new entries

**Comment by oterral** [comment]
Agree with @gjn I remove it from the popup and add an help icon in the header

**Comment by davidoesch** [comment]
Put it in the header!

**Comment by oterral** [comment]
See https://github.com/geoadmin/mf-geoadmin3/issues/2467 for the next version
