### ISSUE TITLE
[extended tooltips] missing space in links to extended tooltips

### ISSUE THREAD

**Issue by mariokeusen** [geoadmin/mf-geoadmin3#2260]
UC: open app, load a layer with an extended tooltip, click an object, look at the link for "more info", "Zusatzinformation", "Information suppl."

Result: there is a space missing between the text and the "icon" for the link
Expected: space is there between text and icon.
![space_ext_ttip_link](https://cloud.githubusercontent.com/assets/4577749/6958853/d5fed8cc-d911-11e4-99d5-56abf29377b7.PNG)

Could you please add a space in all such links / layers / languages?

Was told me by a Datenherr. IMHO really minor, but still not so nice in a way.

**Comment by AFoletti** [comment]
solved

**Comment by mariokeusen** [comment]
Done. Thanks
