### ISSUE TITLE
Hover effect on building

### ISSUE THREAD

**Issue by cedricmoullet** [geoadmin/mf-geoadmin3#2264]
The cursor doesn't change when hovering a building: https://map.geo.admin.ch/?bgLayer=ch.swisstopo.pixelkarte-grau&lang=de&zoom=10&Y=637206.03&X=193915.98&time_current=latest&topic=aviation&catalogNodes=1379,1381,1514&layers=ch.bfs.gebaeude_wohnungs_register

**Comment by davidoesch** [comment]
might be due to the fact that this is an aggregated layer

**Comment by oterral** [comment]
Exactly the `queryable` propaerty is set to `true` to the parent layer  and `false` to its child
