### ISSUE TITLE
download geol gutachten: link/URL email?

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#2266]
Hi Mario
using
http://s.geo.admin.ch/63c090b780 
I get on the tooltip
Zugangsstufe "copy"	free
Zugangsstufe "view"	free
PDF Download 	geolinfo@swisstopo.ch - InfoGeol no.: 2518 

expected result
on PDF: a download not a mail address

**Comment by ltclm** [comment]
you get an email link because the file is bigger than 200mb.
this has been specified by customer.

**Comment by mariokeusen** [comment]
Confirmed: this is what has been agreed on with the customer. Besides the >200mb PDF's we have the email address for all files that are not directly accessible on the web, which IMHO is not that bad (customer can directly contact the data owner)

**Comment by davidoesch** [comment]
just rename "PDF download" with"PDF access " in de "PDF Bezug" so it works for email and download... Etc for it fr rm

**Comment by davidoesch** [comment]
@mariokeusen update?

**Comment by cedricmoullet** [comment]
@daguer could you fix this in the Mako ?

**Comment by davidoesch** [comment]
@mariokeusen update
