### ISSUE TITLE
Bad doc in makefile

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/mf-geoadmin3#2269]
make updateol
make: *** No rule to make target `updateol'.  Stop.

**Comment by loicgasser** [comment]
Please add some more doc and try new exports. I can't add any personnaly it works only with an ol3 update.

**Comment by loicgasser** [comment]
I also want to be able to recreate a build without having to update ol....

**Comment by loicgasser** [comment]
Ok think I got it, so I guess I need to
add my exports
make ol
commit ol-debug
?
Readme + make helo no?

**Comment by ponceta** [comment]
make updateol 
is now 
make ol

since https://github.com/geoadmin/mf-geoadmin3/pull/2254/files

Need a few corrections on the Makefile help to be coherent with make help.
