### ISSUE TITLE
"Layer Sorting" does not work if you highlight an object / all browsers

### ISSUE THREAD

**Issue by danielabrandt** [geoadmin/mf-geoadmin3#2271]
Hi,

a customer reported to following issue. The "sorting" mechanism did not work properly with the layers, if he highlighted an object in one layer:

"Wir entwickeln gerade eine WASTA-Storymap… Dabei sind wir auf ein Layer-Sortierung-Problem gestossen.

Wir machen folgendes:

http://map.geo.admin.ch/?zoom=5&lang=de&topic=ech&bgLayer=ch.swisstopo.swissimage&layers=ch.swisstopo.vec25-gewaessernetz,ch.bfe.stauanlagen-bundesaufsicht,ch.bfe.statistik-wasserkraftanlagen&ch.bfe.statistik-wasserkraftanlagen=206975

Permalink mit Highlight auf eine WASTA-Anlage. Auf der Karte sollte der Layer statistik-wasserkraftanlgen zu oberst sein. Ist er aber leider nicht. Er erscheint unter dem Gewässernetz. Reihenfolge der Layer lässt sich nicht über Permalink steuern… Liegt wohl an &ch.bfe.statistik-wasserkraftanlagen=206975 weil ohne das geht die Sortierung (haben wir ja damals gefixt für die SgT-Storymap).

Wäre für unsere Storymap super, wenn das funktionieren würde."

Thank you for fixing and reporting back to either me or directly our customer Martin Hertach: martin.hertach@bfe.admin.ch 

Kind regards

**Comment by cedricmoullet** [comment]
Layer sort should be permalink dependent

**Comment by ponceta** [comment]
This a conflict between permalink order of layers and permalink of a selected value.

Permalinking a specific value should not influence layers order.

**Comment by mariokeusen** [comment]
Do we have some news for this? Customer asked me today again.
Thanks

**Comment by oterral** [comment]
@mariokeusen  I'm looking right now
