### ISSUE TITLE
[extended tooltips] get rid of red font in datasets where a link to object is available

### ISSUE THREAD

**Issue by mariokeusen** [geoadmin/mf-geoadmin3#2277]
UC: open app, load the layer ch.bfe.statistik-wasserkraftanlagen, click an object, click more info, look at the extended tooltip's footer
Result: we have three links and one of them, the link to the object is written in red font
Expected: all links are in (normal) blue font

Action: please change for all extended tooltips where a link to the object is available

![ext_ttip_link_fonts](https://cloud.githubusercontent.com/assets/4577749/7087809/8467a49c-df8f-11e4-99fb-5965d1a4c0d9.PNG)

**Comment by AFoletti** [comment]
solved

**Comment by mariokeusen** [comment]
Done. Thanks
