### ISSUE TITLE
Tooltip doesn't work on ch.bav.laerm-emissionplan_eisenbahn_2015

### ISSUE THREAD

**Issue by cedricmoullet** [geoadmin/mf-geoadmin3#2278]
http://map.geo.admin.ch/?X=180640.00&Y=612720.00&zoom=5&lang=fr&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.bav.laerm-emissionplan_eisenbahn_2015

**Comment by ltclm** [comment]
identifiy is working:
http://api3.geo.admin.ch/rest/services/ech/MapServer/identify?geometry=609200,182019.99999999997&geometryFormat=geojson&geometryType=esriGeometryPoint&imageDisplay=1436,598,96&layers=all:ch.bav.laerm-emissionplan_eisenbahn_2015&mapExtent=598360,174660,627080,186620&tolerance=5
htmlpopup is not working:
http://api3.geo.admin.ch/1427420086/rest/services/ech/MapServer/ch.bav.laerm-emissionplan_eisenbahn_2015/2985556/htmlPopup?imageDisplay=1436,598,96&lang=fr&mapExtent=598360,174660,627080,186620
```
404 Not Found

The resource could not be found.

No layer with id ch.bav.laerm-emissionplan_eisenbahn_2015
```

**Comment by ltclm** [comment]
The layer is not in the topic ech. Im not sure if this is still an official layer, is anyobdy using this layer?
@kandre  https://redmine.prod.bgdi.ch/issues/4013

**Comment by mariokeusen** [comment]
I can confirm that this layer should not be present anymore. It has been replaced by the following:
ch.bav.laerm-emissionsplan_eisenbahn_tag
ch.bav.laerm-emissionsplan_eisenbahn_nacht

Like written in the redmine ticket, the old layer can be decommissioned.

**Comment by oterral** [comment]
This layer is in topic api:

http://api3.geo.admin.ch/1427420086/rest/services/api/MapServer/ch.bav.laerm-emissionplan_eisenbahn_2015/2985556/htmlPopup?imageDisplay=1436,598,96&lang=fr&mapExtent=598360,174660,627080,186620

**Comment by kandre** [comment]
Ok I havent totally desactivated this layer, which have been replaced by ch.bav.laerm-emissionplan_eisenbahn_tag and nacht, I take care of it

**Comment by kandre** [comment]
I cleaned this layer in the bod, and I asked @alcapat the tiles in S3 bucket. I created [this PR](https://github.com/geoadmin/mf-chsdi3/pull/1374) to remove the identify service on this layer as well.
