### ISSUE TITLE
WGS84 (lat/lon) coordinates are not shown

### ISSUE THREAD

**Issue by p1d1d1** [geoadmin/mf-geoadmin3#2279]
From HelpDesk:

-----------------------------------------------------------------------------------------------------------------------
sascha.brunner@sunrise.ch just sent a feedback:
 Guten Tag,
Bei WGS84 (lat/lon) werden die Werte nicht angezeigt. Freundliche Grüsse Brunner Sascha. 
Permalink: https://map.geo.admin.ch/?X=215272.18&Y=671596.51&zoom=8&lang=de&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe. 

User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:36.0) Gecko/20100101 Firefox/36.0

**Comment by oterral** [comment]
Duplicate with #2252  will be fixed for the next deploy
