### ISSUE TITLE
From HelpDesk

### ISSUE THREAD

**Issue by p1d1d1** [geoadmin/mf-geoadmin3#2280]
Guten Tag

 "Ort suchen : Pegelstein Dotzigen" ergibt einen Unterschied von etwa 250 Meter zur tatsächlichen Position (LK 1:25000) siehe BS-Foto unten.
________________________________________

 

MfG Th. Lüthi
![a](https://cloud.githubusercontent.com/assets/1533649/7133397/52a1503c-e293-11e4-9ce3-8a120f9b3579.png)

**Comment by davidoesch** [comment]
This is an issue for revision swisstopo
