### ISSUE TITLE
line breaks in footer...

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#2283]
open multiple layers with multiple dataowners
and you get this
![unbenannt](https://cloud.githubusercontent.com/assets/4577727/7138515/214db646-e2c1-11e4-8cef-f97df6ea05d7.PNG)

expected:
after c data: the first owner comes

**Comment by oterral** [comment]
Already tried to fix this on a previous issue (for embed page I think). The only way is  to avoid the use of the `ol.control.Attribuiton` and makes our own directive to manage attributions.  
With a new directive we also could translate the attributions.
