### ISSUE TITLE
Popups: are fixed-width when sticked to left-border but not on right borders

### ISSUE THREAD

**Issue by kandre** [geoadmin/mf-geoadmin3#2286]
Popups are fixed-width when sticked to left-border but not on right borders. 

Either: popups are always fixed-width (like it is when drag to left, top and bottom sides)
or : popups are resizable when dragged and sticked to window's sides

**Comment by cedricmoullet** [comment]
@oterral any thoughts ?

**Comment by oterral** [comment]
Fixed
