### ISSUE TITLE
spelling mistake

### ISSUE THREAD

**Issue by barbalex** [geoadmin/mf-geoadmin3#2288]
You have a typo in
https://github.com/geoadmin/mf-geoadmin3/blob/master/src/components/StorageService.js#L109

It is:

    this.removeTiem

It should be:

    this.removeItem

**Comment by oterral** [comment]
Thx for this @barbalex  fixed with https://github.com/geoadmin/mf-geoadmin3/commit/4a65fa91db65b89d12023e97d286e11ae7ab2570
