### ISSUE TITLE
[Heading]: geolocation point is misplaced after loss of signals

### ISSUE THREAD

**Issue by kandre** [geoadmin/mf-geoadmin3#2289]
After a loss of signal, either or both the following can occur: 

- geolocation point may stay idle/frozen even if device is moving
- geolocation point is no longer centered on the map

I think it could be reproductible by using heading outside, doing 'indoor navigation' in our building and exiting at some other entrance. I investigate

**Comment by cedricmoullet** [comment]
Wont fix
