### ISSUE TITLE
Console error on safari: 'viewport argument key 'minimal-ui' not recognised and ignored'

### ISSUE THREAD

**Issue by kandre** [geoadmin/mf-geoadmin3#2290]

**Comment by oterral** [comment]
we can't do anything about it , we keep it for ios7.

**Comment by kandre** [comment]
This console error does not affect at all app behavior on safari (on apple deskop). 

However, Apple added minimal-ui meta tag on safari with ios 7,1, but removed it since iOS 8 (https://developer.apple.com/library/prerelease/ios/releasenotes/General/RN-iOSSDK-8.0/). 

This tag hides Safari controls at the top and bottom of the screen, allowing for more room for the actual browser content. 

Do we need this i our app?

**Comment by kandre** [comment]
ok thanks
