### ISSUE TITLE
[Feedback Tool] - Date/Time as ID

### ISSUE THREAD

**Issue by p1d1d1** [geoadmin/mf-geoadmin3#2291]
Please add ISO 8601 DATE¦TIME in e-mail subject and in meta.json.
Millisecond precision?

**Comment by ponceta** [comment]
![image](https://cloud.githubusercontent.com/assets/8614223/7202596/2ed1d324-e514-11e4-920b-7e41c83a3b84.png)

@p1d1d1 ¦ is not python friendly.

**Comment by p1d1d1** [comment]
¦ is not a problem. Actually is ISO 8601 this ¦ is a "T".
By the way the idea is to have the tyimestamp in the email subject. Now I understand that having it in the body simplifies to put it in the meta.json.
But please put also in email subject, something like:

Customer feedback - timestamp 

For the formatting a "T" is missing between DATE and TIME.
We could also use a compacted form if needed: more compact but less human readable:

20150417T150429.946465 

@cedricmoullet @davidoesch ?

**Comment by davidoesch** [comment]
think of the guy who is gonna spell you the ticket number on the phone
so use
"ID: YYYY-MM-DD-HH-MM-SS"

everything else is gonna be a nightmare

**Comment by ponceta** [comment]
![image](https://cloud.githubusercontent.com/assets/8614223/7225148/a08eceee-e73b-11e4-88eb-3b75ade00071.png)

Like this?

**Comment by p1d1d1** [comment]
I would use milliseconds.
And I prefer:

2015-04-17T15:04:29.946465 

(more standard and more readable IMHO)
with or without "ID", I don't care

**Comment by ponceta** [comment]
ISO 8601 Version

![image](https://cloud.githubusercontent.com/assets/8614223/7228083/f9543ac2-e755-11e4-8ce7-63c73c3133b7.png)

**Comment by p1d1d1** [comment]
Just one point: millisecond is 3 digits after the comma, and I think is enough, isn't it (or am I wrong?)? 

Otherwise ok for me. @davidoesch @cedricmoullet

**Comment by ponceta** [comment]
Milisecond version

![image](https://cloud.githubusercontent.com/assets/8614223/7246310/89a76dd8-e7fb-11e4-8736-8a65ea0c127a.png)

**Comment by davidoesch** [comment]
Keep it simple:
Imagine a customer is telling  you on the phone the ID:
- a numeric number is simpler (everyone in the helpdeks can count to 10 in 4 lbguages, but spelling in for languages?)
- short: don't make it too long ..with milisecond, come on
- use dash (-) only ---- it makes spelling easier and extracting the data easier ( 3 different seperators : . -  are just ridicolous)

This is why I still insisit on
"ID: YYYY-MM-DD-HH-MM-SS"

**Comment by ponceta** [comment]
Guys please ... take a time together to discuss together and come back to me when you'll have chosen something that both agree with! <3

**Comment by davidoesch** [comment]
Ok we (@p1d1d1 and I ) have a decision

•	Customer feedback – "ID YYYYMMDDHHMMSSSS"
and for consistency reason
•	"Meta-YYYYMMDDHHMMSSSS.json" -> can you open a seperate ticket
•	"Drawing-YYYYMMDDHHMMSSSS.kml" -> can you open a seperate ticket

**Comment by p1d1d1** [comment]
@ponceta Just one last point.
In the metaJSON I wouldn't use the label "date" for this. Use instead "ID"
@davidoesch OK?

and many thanks

**Comment by ponceta** [comment]
Fine for me!

**Comment by ponceta** [comment]
![image](https://cloud.githubusercontent.com/assets/8614223/7318086/4a5ca3f2-ea88-11e4-9a51-63b17e565ff5.png)

![image](https://cloud.githubusercontent.com/assets/8614223/7318099/661f9842-ea88-11e4-9802-6d9137d8cf4b.png)

[Testlink](https://mf-geoadmin3.bgdi.ch/ltpoa)

**Comment by p1d1d1** [comment]
Sorry @ponceta we need "SSSS". 
1/100 of second.
As far as I can see you implemented "SS"

**Comment by ponceta** [comment]
Nice, I did it right and then I corrected myself into false... now it should be fine.

**Comment by gjn** [comment]
What happens if 2 users are sending an email at the same millisecond?

;=)

**Comment by p1d1d1** [comment]
@gjn hope you're ironic: aren't you?

**Comment by gjn** [comment]
Only joking :=). Hey, it's Friday.

**Comment by p1d1d1** [comment]
yep. no problem... easy... nice weekend

**Comment by davidoesch** [comment]
all ok---

**Comment by ponceta** [comment]
Will be online next deploy.
