### ISSUE TITLE
GetFeatureInfo for layers which already have no CHSDI tooltip.

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#2292]
Use Case 
https://groups.google.com/forum/#!topic/geoadmin-api/h9-NXokN6uU 

We have then a Service for RAsterData which is not covered in REST API

**Comment by procrastinatio** [comment]
OGC WCS ?

**Comment by p1d1d1** [comment]
WMS GetFeatureInfo is enough.
WCS is a data service. I you implement a WCS, users can download the data.

**Comment by oterral** [comment]
SHould be not difficult ith http://openlayers.org/en/master/apidoc/ol.source.TileWMS.html#getGetFeatureInfoUrl

**Comment by davidoesch** [comment]
@oterral update? ETA?

**Comment by oterral** [comment]
No update. Needs to be implemented.
