### ISSUE TITLE
[JpegTiles] Use progressive jpeg tiles

### ISSUE THREAD

**Issue by ponceta** [geoadmin/mf-geoadmin3#2295]
Why not use progressive jpeg for jpeg tiles (mainly on the background aerial image)?

This has a speed improvement of only 7% for most computers but this could be more on mobile phones and tablets (with mobile connexions).

http://blog.patrickmeenan.com/2013/06/progressive-jpegs-ftw.html

(demo on large image)
http://pooyak.com/p/progjpeg/

**Comment by procrastinatio** [comment]
Even better, webp

**Comment by ponceta** [comment]
http://caniuse.com/#search=webp... No go for swiss confederation.
