### ISSUE TITLE
UI refactoring: Share menu

### ISSUE THREAD

**Issue by kandre** [geoadmin/mf-geoadmin3#2297]
Share menu should have:

- [ ] Short URL => copy to clipboard
- [ ] Mail, QRcode | FR, Twitter, G+
- [ ] Change Embed message link (redirection to configuration dialog box), title and copy to clipboard

**Comment by kandre** [comment]
Memo @kandre Help printscreen will have to be adapted as well

**Comment by kandre** [comment]
We need a copy to clipboard in **OS clipboard** (to copy links crossbrowser or even anywhere) and compatible with all browsers we support. Indeed an url copy in the 'webpage clipboard' would make no sense in our share menu. For security reasons OS clipboard is not accessible in javascript unless using a module with flash plugin (such as [zeroclipboard](https://github.com/zeroclipboard/zeroclipboard) or [ng-clip with zeroclipboard](https://github.com/asafdav/ng-clip)).

The idea behind that is 'Flash can access your computers clipboard because you have to install flash and agree to the security settings'.

Using these Flash solutions is not very nice and has this main disadvantage: the user needs flash, that we would not really like... 

I keep still trawling the web for a solution without flash and compatible on all browsers

**Comment by cedricmoullet** [comment]
Flash is not an option

2015-04-23 11:37 GMT+02:00 kandre <notifications@github.com>:

> We need a copy to clipboard in *OS clipboard* (to copy links crossbrowser
> or even anywhere) and compatible with all browsers we support. Indeed an
> url copy in the 'webpage clipboard' would make no sense in our share menu.
> For security reasons OS clipboard is not accessible in javascript unless
> using a module with flash plugin (such as zeroclipboard
> <https://github.com/zeroclipboard/zeroclipboard> or ng-clip with
> zeroclipboard <https://github.com/asafdav/ng-clip>).
>
> The idea behind that is 'Flash can access your computers clipboard because
> you have to install flash and agree to the security settings'.
>
> Using these Flash solutions is not very nice and has this main
> disadvantage: the user needs flash, that we would not really like...
>
> I keep still trawling the web for a solution without flash and compatible
> on all browsers
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geoadmin/mf-geoadmin3/issues/2297#issuecomment-95512620>
> .
>



-- 
Twitter: http://twitter.com/cedricmoullet
Linked In: http://www.linkedin.com/in/cedricmoullet

<http://twitter.com/cedricmoullet>

**Comment by oterral** [comment]
Only one pure HTML5 solution:
http://updates.html5rocks.com/2015/04/cut-and-copy-commands

**Comment by kandre** [comment]
Really nice, I go for this one
