### ISSUE TITLE
UI refactoring: Print menu

### ISSUE THREAD

**Issue by kandre** [geoadmin/mf-geoadmin3#2298]
Improve menu and button names to 'Imprimer' and 'Créer PDF pour impression'.

**Comment by kandre** [comment]
Memo @kandre Help printscreen will have to be adapted as well

**Comment by davidoesch** [comment]
IMHO : only  a case of  translation

**Comment by cedricmoullet** [comment]
yes.

2015-04-17 15:47 GMT+02:00 davidoesch <notifications@github.com>:

> IMHO : only a case of translation
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geoadmin/mf-geoadmin3/issues/2298#issuecomment-93989364>
> .
>



-- 
Twitter: http://twitter.com/cedricmoullet
Linked In: http://www.linkedin.com/in/cedricmoullet

<http://twitter.com/cedricmoullet>

**Comment by davidoesch** [comment]
changed FR DE EN RM of print_action in Transaltion @AFoletti can you do IT?

**Comment by AFoletti** [comment]
sent trad to @kandre

**Comment by davidoesch** [comment]
FR DE EN RM are done....

**Comment by kandre** [comment]
@davidoesch how would you say 'Créer PDF pour impression' in RM ?

**Comment by davidoesch** [comment]
As written above --- I've done the translation already in the translation table except IT ( msgid :print_action )

**Comment by davidoesch** [comment]
print_actionErstelle PDF für DruckCreate PDF for printCréer PDF pour
impression???Creais PDF per stampa

**Comment by kandre** [comment]
@davidoesch I understand you message now. You add them in the bod right ? Actually, 'app translations' are not read from bod but directly from geoadmin code. Is the row 'print_action' existed before (it might be never used). Thank you for the translations

**Comment by kandre** [comment]
By the way, a bit of code has to be adapted since we dont want to change print popup message (no pdf in that case)
