### ISSUE TITLE
GPX Support

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#2301]
In drawing support GPX

Version/Format
- [ ] GPX 1.1 : does this make sense? http://kml2gpx.com/ ?
- [ ]  as in schweizmobil : does this make sense?
- [ ]  as http://openlayers.org/en/master/examples/gpx.html : does this make sense?

Export:
- [ ]  support one Version concluded from the finding above
- [ ]  file name convention corresponds with the KML export

Import:
- [ ] Provide a validator link (similar as for galdos kml) --- if there is none, might be nice to add one like in http://www.topografix.com/gpx_validation.asp

**Comment by procrastinatio** [comment]
IN GPX you have tracks, waypoints and routes.

Import:
* Event. ask what to import, but tracks may be heavy
* Main use case, people want to see their tracks

Export:
* Main issue is that features do not have labels. Event. ask user for a name.
* Main use case is creating waypoint and route. Line -> route, point -> waypoint

There is an _official_ schema (http://www.topografix.com/GPX/1/1/gpx.xsd), so we won't use anything fancy.

**Comment by davidoesch** [comment]
Ok I think we will address this when we update UI for import

**Comment by davidoesch** [comment]
And I still think this why there is measure and draw : with measure the user expects a GPx with draw a kml

**Comment by davidoesch** [comment]
- might be solved with http://swissmapconverter.ch/

**Comment by davidoesch** [comment]
Provide GPX import by an external site http://www.swisstopo.admin.ch/internet/swisstopo/en/home/apps/calc/kml.html - this site has to use http://swissmapconverter.ch/ provide service as swisstopo

**Comment by loicgasser** [comment]
http://swissmapconverter.ch/  does GPX to KML not the opposite right?

**Comment by loicgasser** [comment]
Anyway this shouldn't be to hard to implement in CHSDI in case we can't use this service.

**Comment by loleg** [comment]
+1 for GPX support for better rendering of traces with elevation data - when imported via KML conversion, we found them unreadable in 2.5D view (alpha warning noted)

**Comment by davidoesch** [comment]
@loleg: currently elevation datat support in KML is very limited, we hope to improve this in the BETA version

**Comment by davidoesch** [comment]
@loleg see  https://github.com/geoadmin/mf-geoadmin3/issues/3104 and 
 https://github.com/geoadmin/mf-geoadmin3/issues/2612

**Comment by loleg** [comment]
Great to know - thanks @davidoesch

**Comment by oterral** [comment]
Import GPX supported
