### ISSUE TITLE
[Popup] extendedHtmlPopup is not a popup anymore

### ISSUE THREAD

**Issue by ponceta** [geoadmin/mf-geoadmin3#2307]
Talking about usability, clicking on an item displays a small description popup which is great, but clicking on the [moreinfo](http://api3.geo.admin.ch/rest/services/ech/MapServer/ch.bfe.windenergieanlagen/turbine_50/extendedHtmlPopup?lang=de) goes to a new page which is a dead end.

Example:
http://s.geo.admin.ch/6410c28054

Why not extend the popup as its name suggest to display an extendedhtmlpopup?
With a click you can browse all the usefull informations without quitting map.geo.admin.ch and close it very easily with a simple click anywhere outside of the popup?

![pimpmypopup2](https://cloud.githubusercontent.com/assets/8614223/7293602/abab71c0-e9a6-11e4-8691-d980cad445e2.png)

or 

![pimpmypopup3](https://cloud.githubusercontent.com/assets/8614223/7293616/bf66f4f0-e9a6-11e4-9b12-e837c0180dc9.png)

**Comment by davidoesch** [comment]
The reason is quite simple:
 not everyone has a big screen as you ahve.. on a small laptop you cover with the normal tooltip already most of the map.
having a new window open was actually *the* reason for the expert tooltip
