### ISSUE TITLE
Wanderwege doesn't show up at highest zoom levels

### ISSUE THREAD

**Issue by cedricmoullet** [geoadmin/mf-geoadmin3#2308]
http://map.geo.admin.ch/?X=182974.52&Y=611535.70&zoom=3&lang=fr&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.swisstlm3d-wanderwege

But it's fine on smallest zoom levels

**Comment by ltclm** [comment]
@daguer 
Im already on it. Tiles have not been generated completely for this update.

**Comment by cedricmoullet** [comment]
really not nice. Who tested this ?

**Comment by cedricmoullet** [comment]
When was this layer published ?

**Comment by mariokeusen** [comment]
https://redmine.prod.bgdi.ch/issues/3644

**Comment by ltclm** [comment]
The tiles are there and varnish has been flushed.

**Comment by cedricmoullet** [comment]
it doesn't show up

2015-04-23 11:37 GMT+02:00 Clausen Marcel <notifications@github.com>:

> The tiles are there and varnish has been flushed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geoadmin/mf-geoadmin3/issues/2308#issuecomment-95512681>
> .
>



-- 
Twitter: http://twitter.com/cedricmoullet
Linked In: http://www.linkedin.com/in/cedricmoullet

<http://twitter.com/cedricmoullet>

**Comment by gjn** [comment]
Works here. So all that was missing was a varnish flush?

**Comment by ltclm** [comment]
it must be your client cache.
@gjn  we had to generate the missing tiles and flush varnish.

**Comment by cedricmoullet** [comment]
now, ok

2015-04-23 11:41 GMT+02:00 Clausen Marcel <notifications@github.com>:

> it must be your client cache.
> @gjn <https://github.com/gjn> we had to generate the missing tiles and
> flush varnish.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geoadmin/mf-geoadmin3/issues/2308#issuecomment-95513697>
> .
>



-- 
Twitter: http://twitter.com/cedricmoullet
Linked In: http://www.linkedin.com/in/cedricmoullet

<http://twitter.com/cedricmoullet>
