### ISSUE TITLE
Use angular translate-attr directive  instead of filter or scope variable

### ISSUE THREAD

**Issue by oterral** [geoadmin/mf-geoadmin3#2310]
It could be nice to use the new angular [translate attribute directive](http://angular-translate.github.io/docs/#/api/pascalprecht.translate.directive:translate) to avoid using filter or polluted scope like for popup buttons.

@ponceta do you want to try?

**Comment by ponceta** [comment]
Yep!

**Comment by oterral** [comment]
angular translate attribute can be used due to  https://github.com/angular-translate/angular-translate/issues/1027
