### ISSUE TITLE
Huge topic selector

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/mf-geoadmin3#2312]
@oterral @davidoesch @cedricmoullet 
On my laptop I noticed that the topic selector is likely to become really big, too big.
We should address this problem.

![hugetopicselector](https://cloud.githubusercontent.com/assets/3306154/7297494/9f901788-e9c9-11e4-8e93-9750f8776c1e.png)

**Comment by cedricmoullet** [comment]
responsiveness ?

**Comment by ponceta** [comment]
Responsive images:

http://www.smashingmagazine.com/2014/05/14/responsive-images-done-right-guide-picture-srcset/

http://caniuse.com/#search=srcset

**Comment by davidoesch** [comment]
prio1: I like responsive apprpoach, even srcset (here I only see an issue with the curretn lmitations with safari)

prio2 as alternative
- we *always* show only 4 lines with 4 images width : 1 line offices (blue), second + third line other topics (green), 4th line catalogues (red)
- enable horizontal scrolling with two arrows on each side as in http://www.geoportal.de/DE/Geoportal/geoportal.html?lang=de
