### ISSUE TITLE
Drawing + Save to cloud

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#2315]
UI
![unbenannt](https://cloud.githubusercontent.com/assets/4577727/7333011/d156072e-eb5d-11e4-8b57-acbd1a78eacc.PNG)

- [x]  generate a public link (1 in fig above)  public.geo.admin.ch/<10digitsaphanumericRandom> , shortened. as in doodle (pref: after user clicks on a button generate link
- [x]  create on file per session
- [x]  provide a link to Terms and use conditions (as in iframe cas)
       www.geo.admin.ch/internet/geoportal/en/home/geoadmin/contact.html#drawing 
       www.geo.admin.ch/internet/geoportal/de/home/geoadmin/contact.html#drawing 
       www.geo.admin.ch/internet/geoportal/fr/home/geoadmin/contact.html#drawing 
       www.geo.admin.ch/internet/geoportal/it/home/geoadmin/contact.html#drawing 
       www.geo.admin.ch/internet/geoportal/rm/home/geoadmin/contact.html#drawing 

- [x]  imported data are not stored in public.geo.admin.ch (onyl what is drawn) 

layer selector: as soon as layer is saved it is active in the layer selector
- [x] display dataset as third data as in #2282 

Backend
- [x]  generate an admin link (2 in fig above)  public.geo.admin.ch/<10digitsaphanumericRandom>.kml , shortened. as in doodle (pref: after user clicks on a button generate link)
- [x] set creation date (in fact, last_updated date)

**Comment by davidoesch** [comment]
@oterral Terms and conditions links are live

**Comment by procrastinatio** [comment]
Adapte translation according to usability session:

“Votre dessin est automatiquement stocké, vous acceptez ainsi les conditions d’utilisations.”
“Vous pouvez éditer votre dessin plus tard en conservant ce lien: ” (in red)

**Comment by cedricmoullet** [comment]
You can put the conditions d'utilisation on the bottom

Le 20 mai 2015 15:32, procrastinatio <notifications@github.com> a écrit :

> Adapte translation according to usability session:
>
> “Votre dessin est automatiquement stocké, vous acceptez ainsi les
> conditions d’utilisations.”
> “Vous pouvez éditer votre dessin plus tard en conservant ce lien: ” (in
> red)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geoadmin/mf-geoadmin3/issues/2315#issuecomment-103890187>
> .
>



-- 
Twitter: http://twitter.com/cedricmoullet
Linked In: http://www.linkedin.com/in/cedricmoullet

<http://twitter.com/cedricmoullet>

**Comment by davidoesch** [comment]
Any testlink ?

**Comment by gjn** [comment]
See https://github.com/geoadmin/mf-geoadmin3/pull/2323 for testlink, but it was not updated yet.

**Comment by gjn** [comment]
It should be complete now. [Please test](https://mf-geoadmin3.dev.bgdi.ch/teo_save_draw/), @davidoesch 

(As discussed with @cedricmoullet , we don't show the expiration date)

**Comment by davidoesch** [comment]
@gjn 

- [ ] red color for warning
![unbenannt](https://cloud.githubusercontent.com/assets/4577727/7745414/3cee23d4-ffab-11e4-92a8-1c34d29170bb.PNG)

- [ ] "Your drawing is automatically saved for one year" we have at least to indicate that it is not stored *forever* and he has to take care of it (steering committee key point). adding "for one year" is a short text -> I adapt the text in share_file_disclaimer DE EN @AFoletti ls in FR EN

**Comment by gjn** [comment]
Regarding 2nd point: please discuss with @cedricmoullet and come up with a consens.

**Comment by davidoesch** [comment]
2nd point cedric agreed

**Comment by cedricmoullet** [comment]
+1 for this info in the text

2015-05-21 11:49 GMT+02:00 davidoesch <notifications@github.com>:

> 2nd point cedric agreed
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geoadmin/mf-geoadmin3/issues/2315#issuecomment-104206854>
> .
>



-- 
Twitter: http://twitter.com/cedricmoullet
Linked In: http://www.linkedin.com/in/cedricmoullet

<http://twitter.com/cedricmoullet>

**Comment by AFoletti** [comment]
Done IT

**Comment by gjn** [comment]
Adapted according to comments. Please test again.

**Comment by loicgasser** [comment]
As a side note: we should make a little effort to present those links.

**Comment by davidoesch** [comment]
@loicgasser "little effort to present those links" in which sense? example?

**Comment by davidoesch** [comment]
@loicgasser You mean this links 1 and 2 in 
https://cloud.githubusercontent.com/assets/4577727/7333011/d156072e-eb5d-11e4-8b57-acbd1a78eacc.PNG

**Comment by loicgasser** [comment]
@davidoesch yes those ones

**Comment by davidoesch** [comment]
We discuss this 2morrow in the UI session

**Comment by loicgasser** [comment]
ok will be there then.
