### ISSUE TITLE
[Swisssearch] Test Fails

### ISSUE THREAD

**Issue by ponceta** [geoadmin/mf-geoadmin3#2316]
![image](https://cloud.githubusercontent.com/assets/8614223/7348069/9cf991e8-ecee-11e4-88f9-9d63e81fb539.png)

Check :
[http://map.geo.admin.ch/?swisssearch=brückenmoostrasse 11 raron&lang=de](http://map.geo.admin.ch/?swisssearch=brückenmoostrasse 11 raron&lang=de)

Works correctly on ci, dev int
[http://mf-geoadmin3.dev.bgdi.ch/?swisssearch=brückenmoostrasse 11 raron&lang=de](http://mf-geoadmin3.dev.bgdi.ch/?swisssearch=brückenmoostrasse 11 raron&lang=de)
[http://mf-geoadmin3.int.bgdi.ch/?swisssearch=brückenmoostrasse 11 raron&lang=de](http://mf-geoadmin3.int.bgdi.ch/?swisssearch=brückenmoostrasse 11 raron&lang=de)
[http://mf-geoadmin3.ci.bgdi.ch/?swisssearch=brückenmoostrasse 11 raron&lang=de](http://mf-geoadmin3.ci.bgdi.ch/?swisssearch=brückenmoostrasse 11 raron&lang=de)

See https://www.browserstack.com/automate/builds/dddb1242fb9f3ffe297b057e6da2ea964b4caf1a/sessions/0895e5237ab0b4f65002e551ba3cf6a018c1b798
for logs

@ltclm any idea?

**Comment by ltclm** [comment]
hello
dont understand, cant reproduce the issue, what result do you except?
there is the same result for 

http://mf-chsdi3.prod.bgdi.ch/rest/services/ech/SearchServer?searchText=br%C3%BCckenmoostrasse%2011%20raron&lang=de&type=locations

http://mf-chsdi3.int.bgdi.ch/rest/services/ech/SearchServer?searchText=br%C3%BCckenmoostrasse%2011%20raron&lang=de&type=locations

http://mf-chsdi3.dev.bgdi.ch/rest/services/ech/SearchServer?searchText=br%C3%BCckenmoostrasse%2011%20raron&lang=de&type=locations

http://mf-chsdi3.ci.bgdi.ch/rest/services/ech/SearchServer?searchText=br%C3%BCckenmoostrasse%2011%20raron&lang=de&type=locations

**Comment by ltclm** [comment]
there is something weird with the cache:
http://api3.geo.admin.ch/1429715345/rest/services/ech/SearchServer?searchText=br%C3%BCckenmoostrasse%2011%20raron&lang=de&type=locations

returns two results

the uncached version 
http://api3.geo.admin.ch/1429715345/rest/services/ech/SearchServer?searchText=br%C3%BCckenmoostrasse%2011%20raron&lang=de&type=locations

returns one result.

Have no idea how this could happen. Short term we have to flush varnish cache for 
``http://api3.geo.admin.ch/1429715345/rest/services/ech/SearchServer``
@alcapat is this possilbe?

**Comment by ponceta** [comment]
This is really strange, yes, because it was not the case on friday and saturday but only on sunday night!

**Comment by ltclm** [comment]
seems to be a problem related to the new streaming replication infra.
Sometimes the tables on the slaves are not fully recovered when the creation of the sphinx index is starting. Before starting the sphinx index creation we have to ensure that the master and the slaves are ready. Have to investigate this.

**Comment by ponceta** [comment]
And the problem only occurs on combination of lang=de and swisssearch parameters on prod.

[http://map.geo.admin.ch/?swisssearch=brückenmoostrasse 11 raron&lang=de]
(http://map.geo.admin.ch/?swisssearch=brückenmoostrasse 11 raron&lang=de)

vs 

[http://map.geo.admin.ch/?swisssearch=brückenmoostrasse 11 raron&lang=fr](http://map.geo.admin.ch/?swisssearch=brückenmoostrasse 11 raron&lang=de)

**Comment by ltclm** [comment]
https://github.com/geoadmin/deploy/issues/6

**Comment by ltclm** [comment]
the problem has been described more in detail and hopefully solved within ticket https://github.com/geoadmin/deploy/issues/6

Could you please check if there are still errors.

**Comment by ponceta** [comment]
Jenkins build is back to normal : map.geo.admin.ch

Ty for the fix.

**Comment by ponceta** [comment]
Test fails again but only on dev and int this time, and the error is probably in the recently merged code I think.

**Comment by ponceta** [comment]
![image](https://cloud.githubusercontent.com/assets/8614223/7451556/590848e4-f252-11e4-96f9-5dcc1156b8e3.png)

**Comment by ponceta** [comment]
@ltclm 

Query to API works fine
https://mf-chsdi3.dev.bgdi.ch/rest/services/ech/SearchServer?searchText=br%C3%BCckenmoostrasse%2011%20raron&lang=de&type=locations

But not the app : 
[http://mf-geoadmin3.dev.bgdi.ch/?swisssearch=brückenmoostrasse 11 raron&lang=de](http://mf-geoadmin3.dev.bgdi.ch/?swisssearch=brückenmoostrasse 11 raron&lang=de)

**Comment by ponceta** [comment]
There is something weird with the cached version of dev/int geoadmin. I ran the test against ci and https dev and both works.

The error generated is a wrong encoding on the swisssearch query :

http://mf-chsdi3.dev.bgdi.ch/rest/services/ech/SearchServer?searchText=br%25C3%25BCckenmoostrasse%252011%2520raron&lang=fr&type=locations

and the correct encoding (generated on ci / prod / https dev) is :

http://mf-chsdi3.dev.bgdi.ch/rest/services/ech/SearchServer?searchText=br%C3%BCckenmoostrasse%2011%20raron&lang=fr&type=locations

And this since Friday Morning.

https://jenkins.dev.bgdi.ch/job/geoadmin3/356/

**Comment by ponceta** [comment]
@hpchrist, this seems to be an encoding error due to the http to https redirection.

**Comment by ltclm** [comment]
special characters are encoded two times by the https redirection:
``bash
https://mf-geoadmin3.dev.bgdi.ch/?test=ü
will be redirected to
https://mf-geoadmin3.dev.bgdi.ch/?test=%25C3%25BC
instead of 
https://mf-geoadmin3.dev.bgdi.ch/?test=%C3%BC
``

**Comment by gjn** [comment]
Question asked to c2c.

mf-geoadmin3.ci.bgdi.ch is not yet redirected from http to https, that's why on jenkins it is ok.

**Comment by ponceta** [comment]
Since #2322 has been merged this morning, this won't make jenkins fails (all https) but the http to https needs to be solved for legacy of "ü" swissearch permalinks

**Comment by ponceta** [comment]
Fixed, tx to Marvin :)
