### ISSUE TITLE
HTTPS: kml validator loaded over http

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/mf-geoadmin3#2317]
submitting data to an insecure location at http://www.kmlvalidator.org/validate.htm

I guess we'll have to use a proxy for that.

**Comment by procrastinatio** [comment]
Yes this is the only way

**Comment by gjn** [comment]
Or simply remove it. It doesn't work in all browsers and with local file anyway.

**Comment by oterral** [comment]
@kml validator has been removed
