### ISSUE TITLE
HTTPS: WMS import and KML import

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/mf-geoadmin3#2318]
We have to use ogcproxy as well.

It simply does'nt work on IE9 and raises warnings in other browsers.

**Comment by loicgasser** [comment]
Or redirect to http as @gjn just mentioned it.

**Comment by ponceta** [comment]
I thought we agreed that having https warnings when using external data as KML and WMS was a good behaviour?

**Comment by gjn** [comment]
Warnings are ok, because that's what we want.

Not working: what does not work. Page loading overall? Or just the wms/kml layer?

**Comment by ponceta** [comment]
![image](https://cloud.githubusercontent.com/assets/8614223/7414557/de340f0a-ef53-11e4-8e53-f7749b82a219.png)

It returns errors indeed while using external ressources... But it works anyway! Almighty IE9 :)

**Comment by oterral** [comment]
@gjn @loicgasser we can use ogcproxy only for IE 9 what do you think?

**Comment by oterral** [comment]
just see, we already use it for KML and WMS .

**Comment by oterral** [comment]
For KML import it's not a problem we use the ogcproxy also for images used by the KML.

In ie9 mode the WMS layers are displayed with a Security warning. Anyone has a real ie9 to test if it works ?

**Comment by ponceta** [comment]
@oterral ask IT for a IE9 testing device? 

http://media.techeblog.com/images/toaster_mod_6.jpg

**Comment by gjn** [comment]
I have IE9 at home. I'll test and report.
