### ISSUE TITLE
[query tool] indication of total number of results when more than 200

### ISSUE THREAD

**Issue by mariokeusen** [geoadmin/mf-geoadmin3#2319]
UC: open app, load a queryable layer, make a query with more than 200 results, look at the list.
Result: in the headline there is "Objects (+200)". No obvious message, that there are more than 200 results to load. Users who are not common with the tool do not understand that.
Expected: indicate the total number of results, e.g. "Objects 200/1260" in the headline. Is this querying the total number of results really a performance issue? Make a message text or a tooltipwindow appear, when more than 200 objects are available.

To discuss again. I had more customer feedbacks in this direction.

**Comment by cedricmoullet** [comment]
@gjn What do you think ?

**Comment by gjn** [comment]
Depending on layers, a count request (which would be needed for that) might take quite a long time. We should analyse this for a couple of layers; the biggest ones. The gebaeude_register has more than 2 million entries...
Of course, optimisation is still possible by creating indices for the required attributes. But this would need to be analysed on a case by case basis.

@ltclm Would it be possible to take 2-4 typcial query tool requests and make a count on them for a couple of layers?

**Comment by ltclm** [comment]
here a typical select by rectangle request for gebaeude_register:
```sql
SELECT bfs.adr.egid_edid AS bfs_adr_egid_edid, bfs.adr.egid AS bfs_adr_egid, bfs.adr.strname1 AS bfs_adr_strname1, bfs.adr.deinr AS bfs_adr_deinr, bfs.adr.plz4 AS bfs_adr_plz4, bfs.adr.plzname AS bfs_adr_plzname, bfs.adr.gdename AS bfs_adr_gdename, bfs.adr.gdekt AS bfs_adr_gdekt, bfs.adr.dstrid AS bfs_adr_dstrid, bfs.adr.gkplaus AS bfs_adr_gkplaus, bfs.adr.gstat AS bfs_adr_gstat, bfs.adr.gdenr AS bfs_adr_gdenr, bfs.adr.ggbkr AS bfs_adr_ggbkr, bfs.adr.bgdi_created AS bfs_adr_bgdi_created, ST_AsEWKB(bfs.adr.the_geom) AS bfs_adr_the_geom
        FROM bfs.adr
        WHERE ST_DWITHIN(bfs.adr.the_geom, ST_GeomFromWKB('\x010300000001000000050000000000000090ff204100000000701c04410000000090ff204100000000b0760f4100000000906a244100000000b0760f4100000000906a244100000000701c04410000000090ff204100000000701c0441'::bytea, 21781), 2500.0)
         LIMIT 201
```
Executing this request takes ``80ms``

If you try to get the total number of rows in this table, the standard way would be to run ``select count(1) FROM bfs.adr;``. But this can take a "long" time, in this case the query takes ``400ms``. Postgres has to walk through all the rows to get the total number...
```bash
$ time psql -c "select count(1) FROM bfs.adr;" -d kogis_dev -h pg.bgdi.ch -U www-data -o /dev/null

real    0m0.344s
```

It would be much faster to estimate the total number by running the following query:
```bash
$ time psql -c "SELECT reltuples FROM pg_class WHERE oid = 'bfs.adr'::regclass;" -d kogis_dev -h pg.bgdi.ch -U www-data -o /dev/null

real    0m0.062s
```
This query is using the reltuples field from the pg_class catalog table, this table is updated by vacuum,

**Comment by ltclm** [comment]
retrieving the total number of results of a select by rectangle query is really slow:
```bash
$ time psql -c "Select count(1) FROM (SELECT bfs.adr.egid_edid AS bfs_adr_egid_edid, bfs.adr.egid AS bfs_adr_egid, bfs.adr.strname1 AS bfs_adr_strname1, bfs.adr.deinr AS bfs_adr_deinr, bfs.adr.plz4 AS bfs_adr_plz4, bfs.adr.plzname AS bfs_adr_plzname, bfs.adr.gdename AS bfs_adr_gdename, bfs.adr.gdekt AS bfs_adr_gdekt, bfs.adr.dstrid AS bfs_adr_dstrid, bfs.adr.gkplaus AS bfs_adr_gkplaus, bfs.adr.gstat AS bfs_adr_gstat, bfs.adr.gdenr AS bfs_adr_gdenr, bfs.adr.ggbkr AS bfs_adr_ggbkr, bfs.adr.bgdi_created AS bfs_adr_bgdi_created, ST_AsEWKB(bfs.adr.the_geom) AS bfs_adr_the_geom
         FROM bfs.adr
         WHERE ST_DWITHIN(bfs.adr.the_geom, ST_GeomFromWKB('\x010300000001000000050000000000000090ff204100000000701c04410000000090ff204100000000b0760f4100000000906a244100000000b0760f4100000000906a244100000000701c04410000000090ff204100000000701c0441'::bytea, 21781), 2500.0)
          ) sub" -d kogis_dev -h pg.bgdi.ch -U www-data
 count
--------
 671602
(1 Zeile)

real    0m9.440s
user    0m0.028s
sys     0m0.008s
```

Since there are already geometry indices, i dont think we can significantly improve this query performance.
