### ISSUE TITLE
[extended tooltip] ch.bfe.windenergieanlagen: table layout issue on some browsers (by user feedback)

### ISSUE THREAD

**Issue by mariokeusen** [geoadmin/mf-geoadmin3#2320]
UC: open app, load layer ch.bfe.windenergieanlagen, click an object, go to the ext. tooltip
Result: table layout is like this
![wind_exttooltip_ie9_ff37](https://cloud.githubusercontent.com/assets/4577749/7367855/fcc50382-eda2-11e4-8861-86cae7190f28.jpg)

Expected:
![wind_extttip](https://cloud.githubusercontent.com/assets/4577749/7367860/1698b416-eda3-11e4-9d33-5d348739ec71.PNG)

Remark: this comes from a user feedback from the UVEK and may be caused by some browser settings. They reproduced it on FF37 and IE9. I could not reproduce that on any of my browsers.

Next step: can this be reproduced? Does somebody have an idea how this can happen?

**Comment by ponceta** [comment]
Tested on all browsers, no trouble found.
