### ISSUE TITLE
[Search] return different results according to selected language

### ISSUE THREAD

**Issue by ponceta** [geoadmin/mf-geoadmin3#2321]
- Go to http://map.geo.admin.ch/?lang=de or http://map.geo.admin.ch/?lang=en or http://map.geo.admin.ch/?lang=rm
- search for "bruit"
  Result :
  ![image](https://cloud.githubusercontent.com/assets/8614223/7366026/abd31c5a-ed95-11e4-8bba-cb4dcd7f9d3c.png)

Expected result as on http://map.geo.admin.ch/?lang=fr or http://map.geo.admin.ch/?lang=it

![image](https://cloud.githubusercontent.com/assets/8614223/7368036/883639bc-eda4-11e4-9e15-2afa7da28415.png)

**Comment by ponceta** [comment]
http://api3.geo.admin.ch/rest/services/ech/SearchServer?searchText=bruit&lang=de&type=layers

Returns no result.

http://api3.geo.admin.ch/rest/services/ech/SearchServer?searchText=bruit&lang=fr&type=layers

Is working

**Comment by ltclm** [comment]
layer search is using different indexes for each language

**Comment by ponceta** [comment]
ty @ltclm, @AFoletti  here's the reason :)

There is still an issue, because on many browsers, the default language detected with browser sniffler is english, french speaking users won't find the noise related layers "bruit", and same for "rumore" for italian speaking people.

**Comment by davidoesch** [comment]
close this since user can switch lang
