### ISSUE TITLE
Redesigned accordeon menu

### ISSUE THREAD

**Issue by cedricmoullet** [geoadmin/mf-geoadmin3#2324]
The menu will contain the following elements:

Partager 
Imprimer 
Choisir des cartes
Dessiner sur la carte
Outils avancés
-> Importer des données (WMS / WMTS / KML)
-> Comparer 2 cartes
-> Information objets

**Comment by oterral** [comment]
Will be fixed on prod with https://github.com/geoadmin/mf-geoadmin3/issues/2414 and https://github.com/geoadmin/mf-geoadmin3/pull/2415

So we can close this one since the main accordion redesign has been made with draw.
