### ISSUE TITLE
UI: Redesign search 

### ISSUE THREAD

**Issue by kandre** [geoadmin/mf-geoadmin3#2325]
Redesign search to help users to understand what can be found with it:

- [x] Add label: “Rechercher un lieu ou ajouter une carte:”
- [x] Text in search area: examples such as 'e.g. Bundesplatz 1 Bern, Carte de bruit, 46.7 7.5 ...'
- [x] In the result list:
“Aller à….”
“Ajouter la carte…”
“Aller sur l’objet…”

**Comment by cedricmoullet** [comment]
@geoadmin/usability test the team mention

**Comment by kandre** [comment]
If we want to suggest the user he can enter 'Carte du bruit', he should be able to get it : [Search enhancement: Filter some keywords #2327](#2327)
