### ISSUE TITLE
Search enhancement: Filter some keywords

### ISSUE THREAD

**Issue by kandre** [geoadmin/mf-geoadmin3#2327]
E.g, search sould be able to return Noise map from 'Carte du bruit'. This can be either made by filtering (=removing) some keywords in the search or using tags as discussed some weeks ago.

**Comment by ponceta** [comment]
Have you ever typed "carte du bruit"? If we go this way we have to support "carte du Plan sectoriel de l'infrastructure aéronautique"

Using same logic as @ltclm did when we added on the parcel indices with https://github.com/geoadmin/service-sphinxsearch/pull/93 we could add the "map | carte | karte | ..."

We can apply the same for npa, communes, ... but we need to have the keyword in the indices...


AND we must be able to ignore the connectors : "de / du / la / le / ..." as google does.

Sphinx does this easily using stopwords (exactly the opposite of wordforms)

http://sphinxsearch.com/docs/current.html#conf-stopwords

**Comment by ponceta** [comment]
@loicgasser @ltclm Do you think it will be possible?

Since the layer "carte du bruit" does not exist? 

To find these? 
![image](https://cloud.githubusercontent.com/assets/8614223/7428671/df905f92-eff4-11e4-998f-6e727d2ae068.png)

Using the previous proposal?

**Comment by ltclm** [comment]
I think using/defining sphinx stopwords is a good idea! 

The grouping of layers like your example ``carte du bruit``, should be done with layer tags. 
I would use layer tags to group and priorize layers in the layer search result.

Think we should use the keyword approach ``parcel`` ``npa`` etc. only for swissearch indices.

**Comment by ltclm** [comment]
Hello 
i have changed the layer info views and added the tag information to the index.
I have added the tag ``Lärmkarte`` ``carte du bruit`` to the layers you mentioned.
You can test on dev.

Marcel

**Comment by gjn** [comment]
I can't find any results.

@ltclm Can you open a PR so I can look at the code?

**Comment by ltclm** [comment]
there is no code change, there is just a changed view:
https://github.com/geoadmin/db/commit/a17e3e30e14aa066ad6c0215e034fa2fd9706142

you can open mf-geoadmin3.dev.bgdi.ch and enter ``lärmkarte`` if gui is in german or ``carte du bruit`` if gui is in french.

**Comment by gjn** [comment]
I see. Works now.

I think where possible, we need to be consistent with keywords. We now have 3 approaches:
1) in chsdi3 code, see https://github.com/geoadmin/mf-chsdi3/blob/master/chsdi/views/search.py#L303
2) in sphinx index creation, as proposed by @ponceta https://github.com/geoadmin/service-sphinxsearch/pull/199
3) in db (as @ltclm metioned above)

As I see it, all 3 try to achieve the same thing. Or am I mistaken?

**Comment by ltclm** [comment]
1) is the code part for the correct priorization / ranking of results coming from indexes pimped by 2) 
3) is an independent approach, quite useful i think, which is not used so far. 

i think 1) and 2) should be synchronized. 

3) can be used for layer tagging, we can configure which layers should be found together (groups) priorize them,  and so on...

**Comment by ponceta** [comment]
+1 for "1) and 2) should be synchronized", I'll adapt chsdi to do the same with npa keywords and related stuff

3) is fine too.

**Comment by ponceta** [comment]
@ltclm in geoadmin/db@a17e3e3 should have Emissionsplan Eisenbahnlärm 2015 T and Emissionsplan Eisenbahnlärm 2015 N as the "Lärm" query does.

**Comment by ltclm** [comment]
Layers can be tagged in the table ``bod_master.public.dataset_tags``
I have tagged these two layers and deployed the table to dev 
``bash
./deploy.sh -s bod_master.public.dataset_tags -t dev``

**Comment by ponceta** [comment]
@kandre it could be great to have a list of all expected keywords and all expected layers to be related to, to create/adapt all the views in one. I could maybe help you with @pfanguin.
