### ISSUE TITLE
offline: reload preload data 

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#2331]
android samsung s4

start chrome
enter http://map.geo.admin.ch/?bgLayer=voidLayer&layers=ch.babs.kulturgueter (no bg layer)
save area offline with points
close browser
go offline
start chrome
enter map.geo.admin.ch

result:
pk1000 is shown but no kgs

expected result
it shows no pk1000 but kgs on a void bg 

-> or is me wrong?

**Comment by oterral** [comment]
I suppose pk100 tiles comes from the browser default cache. If you don't put `?bgLayer=voidLayer&layers=ch.babs.kulturgueter ` in the url when you reopen chrome I think it's normal, map.geo.admin.ch loads with the default configuration. The offline process doesn't override the first  url parameters.

**Comment by ponceta** [comment]
I do not know if kgs is an offline storable layer but there are indeed conflicts between chrome cached versions (stored as apps) and the actual latest cached layer.

Since the background is white, no tiles are stored and when you reload the webpage, it is the other cache stored contents which are displayed -> de facto the pk1000.

**Comment by ponceta** [comment]
And that's indeed the url parametrisation which is not overrided by the offline service. :)

**Comment by davidoesch** [comment]
But all layers should Be stored WMS wmts kml..... Why not kgs ? Do I miss here sth?

**Comment by oterral** [comment]
kgs is stored, but  in offline mode : 
if you open `http://map.geo.admin.ch/?bgLayer=voidLayer&layers=ch.babs.kulturgueter ` you have it, 
if you open `http://map.geo.admin.ch/` you don't have it

**Comment by ponceta** [comment]
If you want to avoid this, you can add it to your home screen and then the url parametrisation is saved.

**Comment by davidoesch** [comment]
... Not that user friendly. And it is when you are offline when u discover this. To late...

**Comment by gjn** [comment]
@oterral any possible solution to this? Like maybe safe also which layers should be present and thus adapting accordingly when in offline mode?

**Comment by davidoesch** [comment]
@oterral  update?

**Comment by oterral** [comment]
I think we can add by default all the layer saved offline.  We already do that for the bg layer I think.

**Comment by oterral** [comment]
@davidoesch if you want it put a priority to this bug, thx

**Comment by davidoesch** [comment]
With the new drawing of function... I'll raise the prio

**Comment by oterral** [comment]
@davidoesch in fact, the kultugebiet layer appears when you click the offline button then click to zoom to extent . 

For the voidLayer we doesn't save the fact it is used.

I think we do that to avoid layer appears / disappears if you have a capricious web connection.

**Comment by davidoesch** [comment]
correct-- if I zoom to the aoi then it works.
not that nice but for 80/20 it should fit
