### ISSUE TITLE
[Testing] IE 9 testing still not stable enough

### ISSUE THREAD

**Issue by ponceta** [geoadmin/mf-geoadmin3#2332]
@geoadmin/testing 

I propose to deactivate the mobile version test for IE 9 since this is really unstable.

Ref:

https://www.browserstack.com/automate/builds/dddb1242fb9f3ffe297b057e6da2ea964b4caf1a/sessions/e363972c27066571da23864af03c635383264c30

https://www.browserstack.com/automate/builds/dddb1242fb9f3ffe297b057e6da2ea964b4caf1a/sessions/8ad4b8ff8c549536662875b9b56d889ca4df774b

**Comment by ponceta** [comment]
Should not be the case since @gjn merged #2311 10 days ago... @geoadmin/testing somethings weird with the nightly tests.

**Comment by gjn** [comment]
In jenkins, map.geo.admin.ch tests latest release tag, so #2311 is not yet tested in this project.

**Comment by ponceta** [comment]
Yes, that's what I saw, because it sends 3 mails every day to all re3-dev members...
