### ISSUE TITLE
Right-click not working on Chrome 42.0.2311.135

### ISSUE THREAD

**Issue by p1d1d1** [geoadmin/mf-geoadmin3#2334]
from helpdesk:

------------------------------------------------
thomas.martinson@bluewin.ch just sent a feedback:
 Avec cette version de Google Chrome la fonction "click à droite" sur la souris ne fonctionne pas (je n'obtiens pas le cartouche d'information sur le point sélectionné). Fonctionne sur ce PC avec IE. Merci pour votre travail! Cordialement, ToM. 
Permalink: https://map.geo.admin.ch/index.html?X=152224.47&Y=575533.61&zoom=6&lang=fr&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&mobile=false. 

User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36

**Comment by ponceta** [comment]
I've the exact same version on my private notebook : Chrome/42.0.2311.135 and it works without error.

**Comment by ponceta** [comment]
Probably one of his widgets/advertise blocker. Without more info we can't do anything.

**Comment by p1d1d1** [comment]
Customer said... ya maybe i have a blocker... no more useful info.
I close the ticket
