### ISSUE TITLE
[Feedback Tool] doesn't allows to browse/upload files on chrome/firefox

### ISSUE THREAD

**Issue by ponceta** [geoadmin/mf-geoadmin3#2335]
It works without any issue on IE but clicking on the browse button doesn't do anything on chrome/FF AND spartan

**Comment by gjn** [comment]
Maybe you could use git bisect to find out when this was introduced. I'm pretty sure it worked before.

**Comment by ponceta** [comment]
This has been induced between r_150211 and r_150304
https://github.com/geoadmin/mf-geoadmin3/compare/r_150211...r_150304

Probably due to Browsersniffler?

**Comment by ponceta** [comment]
![image](https://cloud.githubusercontent.com/assets/8614223/7477058/d0960afe-f351-11e4-865a-6547d8867bb5.png)

Gagné!

**Comment by gjn** [comment]
I highly prefer a link to the commit instead of typing the hash off of a screenshot ;-)

**Comment by ponceta** [comment]
That's why I put both :) That was my first use of git bisect :)
