### ISSUE TITLE
[SEO] Link from help to geoadmin

### ISSUE THREAD

**Issue by ponceta** [geoadmin/mf-geoadmin3#2353]
Help page should have at least one link per page which is linked to map.geo.admin.ch.

Example : http://help.geo.admin.ch/?id=55&lang=en

Step 1 should be : go to https://map.geo.admin.ch

OR

Somewhere "Go back to geo.admin.ch" link

**Comment by davidoesch** [comment]
Good Point (we kept it initially neutral so it works for any map*admin.ch site)


Action: on each site a footer is added similar to http://api3.geo.admin.ch/rest/services/ech/MapServer/ch.swisstopo.lubis-luftbilder_schwarzweiss/19541810011215/extendedHtmlPopup?lang=de 

With
- disclaimer & copyright link
- link and text : map.geo.admin.ch
- print (if possible )

**Comment by ponceta** [comment]
This will be extremely useful for the school maps project

**Comment by pauloamado** [comment]
A footer and "back to map.geo.admin.ch" have been added.

**Comment by ponceta** [comment]
Ty @pauloamado this is great!
