### ISSUE TITLE
[Testing] Wordforms / Swisssearch enhancement

### ISSUE THREAD

**Issue by ponceta** [geoadmin/mf-geoadmin3#2355]
@geoadmin/testing 

As in https://github.com/geoadmin/mf-geoadmin3/blob/master/test/selenium/swisssearch_test.js#L9-L20 we should test some requests like "rte de Berne" to check wordforms enhanced.

**Comment by ponceta** [comment]
As corrected in fix https://github.com/geoadmin/service-sphinxsearch/pull/205 (need to be merged first (or your test will fail as it should actually be))

**Comment by ponceta** [comment]
As corrected in fix https://github.com/geoadmin/service-sphinxsearch/pull/205 (need to be merged first (or your test will fail as it should actually be))

**Comment by cedricmoullet** [comment]
@alcapat status ?

**Comment by alcapat** [comment]
@cedricmoullet new test created for wordforms https://github.com/geoadmin/mf-geoadmin3/pull/2540

**Comment by oterral** [comment]
#2540 merged
