### ISSUE TITLE
[query tool] implement AND/OR operators in order to connect single queries

### ISSUE THREAD

**Issue by mariokeusen** [geoadmin/mf-geoadmin3#2356]
According to a discussion with @davidoesch  and the BAFU people responsible for gewiss and water topic, we have the requirement to connect several queries with other boolean operators than AND:

UC: open app, load a queriable layer, open the query tool, make two user-defined queries
Result: the user has no possibility to define how the queries are combined
Expected: user has a choice of different boolean operators (AND, OR, XOR ...) to combine his queries

**Comment by loicgasser** [comment]
Technically not too hard.

**Comment by davidoesch** [comment]
@cedricmoullet: FYI we need this function for the go live for the GEWISS migration

**Comment by AFoletti** [comment]
It's planned to give the GEWISS ppl a link to the demo instance on the 19.06 (Friday next week). Do you have something against? Should we wait a couple of days more and deliver the link with this function already implemented?

**Comment by cedricmoullet** [comment]
This will be without this function

2015-06-11 14:49 GMT+02:00 AFoletti <notifications@github.com>:

> It's planned to give the GEWISS ppl a link to the demo instance on the
> 19.06 (Friday next week). Do you have something against? Should we wait a
> couple of days more and deliver the link with this function already
> implemented?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geoadmin/mf-geoadmin3/issues/2356#issuecomment-111121713>
> .
>



-- 
Twitter: http://twitter.com/cedricmoullet
Linked In: http://www.linkedin.com/in/cedricmoullet

<http://twitter.com/cedricmoullet>

**Comment by cedricmoullet** [comment]
The proposal is to offer a global operator AND, OR, NOT and this will apply to all conditions.
@mariokeusen could you validate this with the customer ?

**Comment by cedricmoullet** [comment]
@mariokeusen ?

**Comment by mariokeusen** [comment]
Confirmed. We'll implement a global boolean operator.

**Comment by cedricmoullet** [comment]
@loicgasser Could you please propose a mockup for this ?

**Comment by loicgasser** [comment]
ok I will

**Comment by loicgasser** [comment]
Keeping the same design we could per default, hide the option. (Nothing changes)
![query_1](https://cloud.githubusercontent.com/assets/3306154/8932885/1c12ce88-3540-11e5-80ca-373a49170e77.png)

Then when we have more than 1 filter, display a select box to select the operator:
![query_2](https://cloud.githubusercontent.com/assets/3306154/8932894/34f68f20-3540-11e5-8b98-993fca020ffe.png)

Alternatively we can use toggle buttons (Draw style, with red background when selected) 

As it is an very advanced feature, I would hide it per default...

**Comment by mariokeusen** [comment]
I'd also hide that until the user makes a second filter, because it's simply not needed with only one filter.

**Comment by oterral** [comment]
Do you want also grouped queries like (condition1 AND condition2) or (condition3 and condition4) ?

**Comment by loicgasser** [comment]
no we simply want a global operator and/or.

**Comment by mariokeusen** [comment]
What is the status here?

**Comment by loicgasser** [comment]
@mariokeusen I need the translations for "query_operator" as in print screen above.
@davidoesch What would be the title?

**Comment by davidoesch** [comment]
Since Boolean is not that common, I would call it

DE "Abfragebedingung"
EN "Query condition"

etc

and and a "-" in pulldown for no query operator

**Comment by loicgasser** [comment]
You want to use (-) when we have only one condition? How it works at the moment is that you can't select an operator untile you have at least 2 conditions.

What about "Query conditions operator"?
or "Query conditions connector"?

**Comment by davidoesch** [comment]
You want to use (-) when we have only one condition? How it works at the moment is that you can't select an operator untile you have at least 2 conditions.
-> omit the "-" if it is only visible if it has 2 conditions

What about "Query conditions operator"?
or "Query conditions connector"?

-> lets do how  google does it

[EN] Advanced search operator (https://support.google.com/mail/answer/7190?hl=en)
[DE] Erweiterte Suchoperatoren https://support.google.com/mail/answer/7190?hl=de
[FR]  opérateurs de recherche avancée https://support.google.com/mail/answer/7190?hl=fr
[IT] operatori per la ricerca avanzata https://support.google.com/mail/answer/7190?hl=it

makes sense?

**Comment by loicgasser** [comment]
makes total sense
