### ISSUE TITLE
Links in metadata are not working

### ISSUE THREAD

**Issue by cedricmoullet** [geoadmin/mf-geoadmin3#2365]
![image](https://cloud.githubusercontent.com/assets/319676/7725957/4e7afc64-feff-11e4-876e-895179bbd352.png)

http://map.geo.admin.ch/?X=190000.00&Y=660000.00&zoom=1&lang=fr&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.bafu.hydroweb-messstationen_grundwasser

**Comment by AFoletti** [comment]
what is wrong with this link? Works for me

**Comment by gjn** [comment]
They seem to work ,but they point to strange things: e.g. `http://map.geo.admin.ch/www.hydrodaten.admin.ch`

**Comment by AFoletti** [comment]
found the problem: the mako goes crazy when in the BOD the url do NOT begin with http://

**Comment by AFoletti** [comment]
BOD corrected. Will be OK next deploy

**Comment by davidoesch** [comment]
"Link to WMS" will then be  a "-" I assume... ;-)

**Comment by AFoletti** [comment]
No... it will still be there. Those layers are in teh wms-bgdi

**Comment by AFoletti** [comment]
You can test in DEV. Issue solved
