### ISSUE TITLE
Etat d'actualité is not correct

### ISSUE THREAD

**Issue by cedricmoullet** [geoadmin/mf-geoadmin3#2366]
![image](https://cloud.githubusercontent.com/assets/319676/7726062/d6e1ac60-feff-11e4-8c41-9ceeee970255.png)

Should be the same like in the map

**Comment by AFoletti** [comment]
At the moment, we do not have an elegant solution for that.

I could fake the date to implement an autoupdate to the current day, but will not reflect an actual integration of the data

**Comment by gjn** [comment]
We should have all the info in the backend for those layers. We know the json url and we know that the date is in this json (timestamp parameter); so we could use this in the mako.

**Comment by AFoletti** [comment]
I agree with @gjn ... this info should for those layers not come from the bod

**Comment by davidoesch** [comment]
time convention
![3](https://cloud.githubusercontent.com/assets/4577727/7732507/de298d7a-ff28-11e4-80c0-39baf467079f.png)

**Comment by loicgasser** [comment]
I can provide a fix using the geojson as @gjn said. But it means that I need to load the whole geojson just to read the timestamp. Not very nice but I don't see any other solution for now.

**Comment by cedricmoullet** [comment]
@loicgasser please do

**Comment by loicgasser** [comment]
it means code specific stuff for the legends of these layers, but ok.

**Comment by loicgasser** [comment]
Fixed via https://github.com/geoadmin/mf-chsdi3/issues/1885
