### ISSUE TITLE
french text is .... strange, at least

### ISSUE THREAD

**Issue by cedricmoullet** [geoadmin/mf-geoadmin3#2367]
![image](https://cloud.githubusercontent.com/assets/319676/7726112/2761099c-ff00-11e4-806f-71e76b956aa8.png)

**Comment by mariokeusen** [comment]
This is geocat content and in responsibility of the data owners. But anyway, I have a bunch of feedbacks for this customer / Projektleiter to provide for these layers.

**Comment by mariokeusen** [comment]
Feedback provided to customer. Let's see what happens.
