### ISSUE TITLE
hydroweb tooltips: open links in new tab

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#2368]
Adapt mako template

for
ch.bafu.hydroweb-messstationen_temperatur
ch.bafu.hydroweb-messstationen_vorhersage
ch.bafu.hydroweb-messstationen_grundwasser
ch.bafu.hydroweb-messstationen_zustand
ch.bafu.hydroweb-messstationen_gefahren

the tooltip ("Stationseite") 

result
opens in the same browser window

expected result
opens in *new* browser tab ( this is the default standard behaviour for all makos of fsdi)

or is there a special reason for this @mariokeusen  (did not find this in the meeting minutes)

**Comment by loicgasser** [comment]
we don't handle the tooltip content. they generate it in the geojson. But I can ask them to adapt.

**Comment by davidoesch** [comment]
pls do so

**Comment by mariokeusen** [comment]
+1 there is no special reason for that. I guess you have to tell that the people from LIIP, right?

**Comment by loicgasser** [comment]
no I believe gejson are generated by bafu team.

**Comment by mariokeusen** [comment]
ok, sent an email to the bafu project manager.

**Comment by loicgasser** [comment]
thanks

**Comment by mariokeusen** [comment]
According to my few clicks today this is done and the issue can be closed.
