### ISSUE TITLE
Use geodesy service directly (CORS)

### ISSUE THREAD

**Issue by procrastinatio** [geoadmin/mf-geoadmin3#2374]
End point is:
https://geodesy.geo.admin.ch/reframe/lv03tolv95?easting=619500&northing=169250

**Comment by gjn** [comment]
That's easily done. I'll do it.

**Comment by cedricmoullet** [comment]
For today's deploy or not ?

**Comment by gjn** [comment]
PR is ready. So @procrastinatio can merge it if for today.
