### ISSUE TITLE
Feedback widget broken

### ISSUE THREAD

**Issue by procrastinatio** [geoadmin/mf-geoadmin3#2388]
To reproduce:

1. Start geo.admin.ch with http://map.geo.admin.ch/?widgets=feedback
2. Try to select a gemometry --> warning 'veuillez renseigner ce champs'
3. Type something in the text box --> message sent. Over

Expected :

Click on the 'report problem' link (top right corner)

**Comment by oterral** [comment]
it seems it's because the popup loose the focus.
