### ISSUE TITLE
Draw: cant move menue on chrome on mac

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#2391]
on mocs macs to be reproduced

**Comment by oterral** [comment]
chrome 43 ? or less

**Comment by davidoesch** [comment]
@cedricmoullet ? it was you mac

**Comment by cedricmoullet** [comment]
now it works.............

2015-06-05 8:49 GMT+02:00 davidoesch <notifications@github.com>:

> @cedricmoullet ? it was you mac
>
> On Fri, Jun 5, 2015 at 8:29 AM, oterral <notifications@github.com> wrote:
>
> > chrome 43 ? or less
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/geoadmin/mf-geoadmin3/issues/2391#issuecomment-109175699
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geoadmin/mf-geoadmin3/issues/2391#issuecomment-109179275>
> .
>



-- 
Twitter: http://twitter.com/cedricmoullet
Linked In: http://www.linkedin.com/in/cedricmoullet

<http://twitter.com/cedricmoullet>
