### ISSUE TITLE
[Share] missing translations

### ISSUE THREAD

**Issue by mariokeusen** [geoadmin/mf-geoadmin3#2392]
UC: open app, open the share menu, watch the different items
Result: not all items are translated (see screenshot below)
Expected: items are translated in all lang
Workaround: enter the different item fields into the translation tab and ask @davidoesch, kem & @p1d1d1 for DE, IT and EN translations
![share_translations](https://cloud.githubusercontent.com/assets/4577749/7979171/5828b04a-0a9d-11e5-81fd-e8fe04117bf1.PNG)

**Comment by davidoesch** [comment]
will be changed anyways accoring to UI session
