### ISSUE TITLE
Position accuracy is overestimated in many cases (measuring tool, position popup)

### ISSUE THREAD

**Issue by kandre** [geoadmin/mf-geoadmin3#2396]
Position accuracy is overestimated in many cases in our app. For instance, accuracy delivered cant be greater than the value on the field of one pixel on our screen. Hence, the number of significant digits should be zoom-dependant. 

I suggest to:

- compute and show position with the minimal accuracy we can provide based on resolution (zoom-level dependant)
- enventually go further by taking account others parameters such as the differences between reference frames LV03 - LV95, which also have an impact on the position accuracy we can insure.

**Comment by davidoesch** [comment]
we have for Z a similar issue as solved  partially in #2185 .

not yet solved #2399 ---

zoom dependent accuracy will be difficult to explain to the user. (concept of pixel...)
A point has *always* the same accuracy ... the LV03 LV95 is bot shown in the tooltip and in the mouseposition. here we are using the official service.

-> so I propose to let it as it is
