### ISSUE TITLE
Height service does not work outside Switzerland 

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#2399]
.... For schweiz mobil

I know this is related to the accuracy discussion but we a result here as well

**Comment by cedricmoullet** [comment]
What are your thoughts in order to solve that ?

**Comment by davidoesch** [comment]
we need a decision by TOPO . this sued to work then we had the issue regarding the precision in the tooltip . is this realated?

proposal: height service is a height service and not a swissalti3d service. outside we use dhm25 and further out SRTM (eg http://height-service.dev.ifs.hsr.ch/dtm/v1/elevation?lon=8.772&lat=47.256&format=raw)
so far we clearly state in the profile that we use "swissalti3d/dhm2"

for this: @mariokeusen can you double check with TOPO that we can use here SRTM "swissalti3d/dhm2"  outside of dhm25 reach?

**Comment by oterral** [comment]
@davidoesch @mariokeusen can we have a answer for this ? or close this.

**Comment by davidoesch** [comment]
We ask topo - again

**Comment by davidoesch** [comment]
Close this , since topo has no feedback
