### ISSUE TITLE
Throttle service test fails

### ISSUE THREAD

**Issue by gjn** [geoadmin/mf-geoadmin3#2410]
Throttle service test fails from time to time. This happened today twice during deploy.

https://github.com/geoadmin/mf-geoadmin3/blob/master/test/specs/ThrottleService.spec.js

We should try to make it more robust. Assigend to @kandre as he's the original author.

**Comment by kandre** [comment]
Have you the log of the error?

**Comment by oterral** [comment]
In fact the problem is if the server is a little bit busy that slowdown the execution of the Throttle function.

**Comment by gjn** [comment]
I think anyway, that the tests could be made more robust (introduce a more fuzzy like test). I can do a proposal if @kandre doesn't want to do it :)

**Comment by oterral** [comment]
I've made a correction https://github.com/geoadmin/mf-geoadmin3/commit/ec5f044a541e2f8105a47f18acddfd50c5a5f172

Hope that fixes the problem
