### ISSUE TITLE
KML in iframe FF does not load

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#2412]
latest ff

start http://www.bafu.admin.ch/umwelt/12492/12891/13204/index.html?lang=de 

kml does not load in iframe, no errors shown in firebug

works nicely in chrome, ie

cc @danielabrandt

**Comment by cedricmoullet** [comment]
Related to the images referenced in the KML:
![image](https://cloud.githubusercontent.com/assets/319676/8099664/ae718e96-1000-11e5-8b71-e1daf27879d6.png)

**Comment by davidoesch** [comment]
How to Solve this cors issue in ff?

**Comment by gjn** [comment]
This has nothing to do with iFrame. The same issue is present when taking [the page directly](http://map.bafu.admin.ch/?topic=bafu&amp;lang=de&amp;layers=KML||http:%2F%2Fwww.ubst.bafu.admin.ch%2Fkml%2Fwald%2Fschweizer-holz_de2.kml)

It's the same in FF38, Chrome 43 and IE9.

CORS is a security feature and should be solved on the bafu side by setting correct CORS headers for the resources they want to include in other domains.

(We could always pass external resources through our ogcproxy, but I advise strongly against it).

**Comment by davidoesch** [comment]
ok  I thought this was a specific issue in ff

-> where does BAFU need to put the right info? in the webserver providing
the image ?

**Comment by gjn** [comment]
Yes. The response for the resources have to contain the following header: `Access-Control-Allow-Origin: *` (They can limit the domain/domains to map.bafu.admin.ch if they want)

Further details: http://enable-cors.org/server.html

**Comment by procrastinatio** [comment]
Or if they cannot change their webserver setting

They may use our  good old proxy, which set correctly the CORS headers...

**Comment by davidoesch** [comment]
informed BAFU
