### ISSUE TITLE
bgLayer=ch.swisstopo.swissimage: copyright info

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#2420]
since the bgLayer=ch.swisstopo.swissimage contains more than swissimage

task: pls change the footer info from

" ©  Data: swisstopo"

to 

"©  Data: CNES, Spot Image, swisstopo, NPOC"

-all lang: the same abbrevation
- link : as today

**Comment by cedricmoullet** [comment]
Will be solved at next deploy. BOD has been updated and translation is in https://github.com/geoadmin/mf-chsdi3/pull/1524
