### ISSUE TITLE
Minor refinements for share menu

### ISSUE THREAD

**Issue by kandre** [geoadmin/mf-geoadmin3#2424]
According to last usability discussion:

- "Code pour intégrer la carte” instead of "plus d’options"
- No separator between qrcode and facebook
- “Prévisualiser” instead of “Voir plus”
- "Ce code vous permet d’intégrer la carte dans votre site web ou votre blog”

**Comment by davidoesch** [comment]
Instead of more options  analog to youtube
FR "Intégrer"
IT "Codice da incorporare"
EN "Embed"
DE "Einbetten"
