### ISSUE TITLE
Update list of WMS

### ISSUE THREAD

**Issue by oterral** [geoadmin/mf-geoadmin3#2427]
Complete if necessary the WMS list : 

See: 

 - [x] https://www.so.ch/verwaltung/bau-und-justizdepartement/amt-fuer-geoinformation/geoportal/geodienste/wms-web-map-service/ 
 - [x] http://geo.gr.ch/index.php?id=113 
 - [x] http://www.apps.be.ch/geo/de/angebot-an-geodiensten.html   
 - [x] http://service.lisag.ch/wms?request=getCapabilities for kanton URI 
 - [x] http://www.geolion.zh.ch/opendata there are new datasets available
 - [x] http://www.zg.ch/behoerden/direktion-des-innern/geoportal/geodaten-einbinden/wms Can you double check ? does not work for the free layers
 - [x] http://wms.geoportal.ch:8080/geoserver/AVAI/wms

- [ ] is it possible to add a structure/tree in the pulldown?
* Kantone
 * AG
  * list WMS
 * AI
  * list WMS
etc

* Länder
 * Österreich/Voralberg
   * list WMS 
* Italien / Norditialien
   * list WMS

**Comment by davidoesch** [comment]
please add them as above

**Comment by oterral** [comment]
@pfanguin can you do that pls?

**Comment by davidoesch** [comment]
added as well URI and zrh and reverted issue to check boxes

**Comment by davidoesch** [comment]
is it possible to add a structure/tree in the pulldown? see refence above? some of the WMS server like http://wms.geoportal.ch:8080/geoserver/AVAI/wms cover multiple Cantons. Multiling support has to be taken itno accoutn as well
