### ISSUE TITLE
Search: cross misplaced on small mobile devices (only on DEV)

### ISSUE THREAD

**Issue by kandre** [geoadmin/mf-geoadmin3#2428]
Only on DEV

Appears when focus is in search input and when text is inserted.

![capture3](https://cloud.githubusercontent.com/assets/8038575/8185526/432b8fe4-1445-11e5-8157-7161f1e670aa.PNG)

**Comment by oterral** [comment]
good one I fix it

**Comment by oterral** [comment]
fix with #2429
