### ISSUE TITLE
WMS import

### ISSUE THREAD

**Issue by procrastinatio** [geoadmin/mf-geoadmin3#2431]
specify that the WMS must support LV03 (EPSG:21781)

**Comment by cedricmoullet** [comment]
Where ?

**Comment by procrastinatio** [comment]
in the 'WMS import' tool. Because a user did try to import a WMS, and as we display only layers which could be displayed (corret projection), he though his GetCapabilities document was broken someway...

**Comment by cedricmoullet** [comment]
make completely sense.

2015-06-17 15:15 GMT+02:00 procrastinatio <notifications@github.com>:

> in the 'WMS import' tool. Because a user did try to import a WMS, and as
> we display only layers which could be displayed (corret projection), he
> though his GetCapabilities document was broken someway...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geoadmin/mf-geoadmin3/issues/2431#issuecomment-112795095>
> .
>



-- 
Twitter: http://twitter.com/cedricmoullet
Linked In: http://www.linkedin.com/in/cedricmoullet

<http://twitter.com/cedricmoullet>

**Comment by davidoesch** [comment]
proposal: use the http://www.geo.admin.ch/internet/geoportal/de/home/services/geoservices/ech0056.html service to parse the wms and show all errors if there are any

**Comment by gjn** [comment]
The site above uses our own api3 owschecker.

**Comment by oterral** [comment]
Do you have the wms url @procrastinatio ?

**Comment by procrastinatio** [comment]
E.g. from BRGM:

http://geoservices.brgm.fr/geologie

Layer list loads fine, but obviously, not layer are displayed.

**Comment by oterral** [comment]
Thx
