### ISSUE TITLE
WordPress widget with iframe

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#2435]

**Comment by cedricmoullet** [comment]
@procrastinatio @oterral any idea how to do that ?

**Comment by davidoesch** [comment]
Energeiaplus.ch

**Comment by davidoesch** [comment]
https://wordpress.org/plugins/about/ should be easy  . all done via github. TOC are compliant with ours... once done: can be implementd in Energeiaplus.ch

**Comment by oterral** [comment]
Codepen has one http://blog.codepen.io/documentation/features/wordpress-plugin/

**Comment by oterral** [comment]
Since we have the iframe mode. i don't think this issue is relevant.
