### ISSUE TITLE
LUBIS data issue

### ISSUE THREAD

**Issue by cedricmoullet** [geoadmin/mf-geoadmin3#2436]
https://map.geo.admin.ch/?topic=swisstopo&X=275939.40&Y=714125.82&zoom=10&lang=de&bgLayer=ch.swisstopo.pixelkarte-grau&layers_timestamp=99991231,99991231&layers=ch.swisstopo.lubis-luftbilder_schwarzweiss,ch.swisstopo.lubis-luftbilder_farbe

The position 84 seems to be wrongly placed: it should be where the circle is:

![image](https://cloud.githubusercontent.com/assets/319676/8232325/12f054fa-15cf-11e5-92fb-418ef76e24f3.png)

**Comment by davidoesch** [comment]
see redmine ticket 3618

**Comment by ltclm** [comment]
the layer containing all the years (timestamp=9999) has not been updated.
I will recreate this layer now.

**Comment by ltclm** [comment]
the layer has been updated.
https://map.geo.admin.ch/?topic=swisstopo&X=275939.40&Y=714125.82&zoom=10&lang=de&bgLayer=ch.swisstopo.pixelkarte-grau&layers_timestamp=99991231,99991231&layers=ch.swisstopo.lubis-luftbilder_schwarzweiss,ch.swisstopo.lubis-luftbilder_farbe
