### ISSUE TITLE
Time from permalink not shown in mobile

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#2441]
Use this permalink
https://s.geo.admin.ch/653b2bb6ef
Result : the year is blank instead of 1984

**Comment by davidoesch** [comment]
![image](https://cloud.githubusercontent.com/assets/4577727/8266395/2cf26fdc-172d-11e5-97f1-b1928d3e67f4.jpg)

**Comment by cedricmoullet** [comment]
I thought it was solved...

**Comment by cedricmoullet** [comment]
@oterral any idea ?

**Comment by oterral** [comment]
I thought it was solved too. Need investigations
