### ISSUE TITLE
Offline drawing : icons not stored

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#2448]
Might be a duplicate issue 

Open https://map.geo.admin.ch/mobile.html?X=240911.39&Y=605016.11&zoom=12&lang=de&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=KML%7C%7Chttps:%2F%2Fpublic.geo.admin.ch%2Fq7jpAwBJScWDbAaqVysZ9Q

Store offline 
Go offline 
Icons are not visible 

Expected result icons are available offline as well

**Comment by cedricmoullet** [comment]
@oterral do you see a "not too complex fix" for that ?

**Comment by oterral** [comment]
Not really we could store theses images in local storage. But I'm not sure how OL will handle base 64 images.

**Comment by oterral** [comment]
May be the best is to add default images when offline.

**Comment by davidoesch** [comment]
not solved and will not be fixed
