### ISSUE TITLE
kml printing not working for chrome

### ISSUE THREAD

**Issue by gjn** [geoadmin/mf-geoadmin3#2456]
I'll try to attach kml file.

-----Ursprüngliche Nachricht-----
Von: webgis@swisstopo.ch [mailto:webgis@swisstopo.ch] 
Gesendet: Freitag, 12. Juni 2015 23:47
An: _swisstopo-webgis
Betreff: Customer feedback ID : 2015061223472131
sent a feedback:
 Polygone als KML importiert werden beim PDF-Druck nicht mitexportiert (bei Verwendung von Google Chrome). Mit dem Internet Explorer klappt der Print.. 
Permalink: http://map.geo.admin.ch/?X=221641.83&Y=682682.89&zoom=7&lang=de&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe. 

User-Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; Touch; .NET4.0E; .NET4.0C; Tablet PC 2.0; InfoPath.3; rv:11.0) like Gecko

**Comment by gjn** [comment]
I've send the file this morning @ 7:52. It's called 78_Track-Zugerberg.kml. Please have a look.

**Comment by oterral** [comment]
Can't reproduce the print works for me on chrome.

**Comment by cedricmoullet** [comment]
@gjn could you please retest ?
