### ISSUE TITLE
Copyright footer: if only one non swisstopo dataowner with void bg; remove coma

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#2458]
open https://s.geo.admin.ch/65486c72bc 

in copyright: there is a comma at the end which is not needed

**Comment by cedricmoullet** [comment]
Current approach doesn't allow to fix this. We need to create a new directive for the management of the attribution. This would give use also more freedom for the management of multilines etc...

**Comment by oterral** [comment]
Fixed
