### ISSUE TITLE
Geolocation : device orientation not correct 

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#2468]
The device orientation on geolocation points 90 degree wrong direction. Image below : holding the iPhone safari /chrome direction of the highway: result in map it tells me that the device is looking north. But arrow should point to West

**Comment by davidoesch** [comment]
![image](https://cloud.githubusercontent.com/assets/4577727/8506996/b34b5400-2230-11e5-8389-c142180ae5ca.jpg)

**Comment by cedricmoullet** [comment]
have you calibrated the "boussole" ?

2015-07-04 9:41 GMT+02:00 davidoesch <notifications@github.com>:

> Assigned #2468 <https://github.com/geoadmin/mf-geoadmin3/issues/2468> to
> @cedricmoullet <https://github.com/cedricmoullet>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geoadmin/mf-geoadmin3/issues/2468#event-347739964>.
>



-- 
Twitter: http://twitter.com/cedricmoullet
Linked In: http://www.linkedin.com/in/cedricmoullet

<http://twitter.com/cedricmoullet>

**Comment by davidoesch** [comment]
I did ... Gmaps and map search mobile and web app do run perfectly on the same device. Gmap u have to use the old version...

**Comment by oterral** [comment]
Can't reproduce

**Comment by davidoesch** [comment]
will show it to you tomorrow

**Comment by davidoesch** [comment]
Might be related to nearby metal (IMHO a smartphone relies on GPS)

**Comment by oterral** [comment]
I've experimented the same this we, but I was close to a  car, few meters further all worked fine so I really think  it was related
