### ISSUE TITLE
[query tool] integrate a warning in a tooltip, if the result number is more than 200

### ISSUE THREAD

**Issue by mariokeusen** [geoadmin/mf-geoadmin3#2470]
As discussed with Cédric today:

UC: open app with topic=aviation, make a user defined query on the obstacle layer that produces more than 200 results.
![query_alert_over200](https://cloud.githubusercontent.com/assets/4577749/8525649/7a6dba46-2402-11e5-8e9c-3748b2d0b817.PNG)

Result: on top of the result window there is indicated (+200 objects). A new user who does not know the tool, will not understand, that his query does provide so many results. The customer claims a better "warning" of the users in this case.
Workarounds/actions:
1) please make the font of the text in brackets "(+200) red instead of black and bold
2) please let a tooltip window appear with a warning text available in the translation tab [1] under the attribute "query_alert_more_than_200_results" (FR and IT translations coming soon).

Thanks in advance

**Comment by mariokeusen** [comment]
[1] https://docs.google.com/spreadsheets/d/1F3R46w4PODfsbJq7jd79sapy3B7TXhQcYM7SEaccOA0/edit#gid=0

**Comment by mariokeusen** [comment]
@cedricmoullet can you make an estimation when we could have this resolved, in order I can make a solid statement for the stakeholders? Thanks

**Comment by cedricmoullet** [comment]
@mariokeusen end of Q3 deadline ?

**Comment by mariokeusen** [comment]
Fine for me. Will inform the bazl people.

**Comment by mariokeusen** [comment]
Do we have any news on this? I have a meeting with the customer this week and should give a status update.

**Comment by gjn** [comment]
This was lost. I'll take care of it this week to assure it's in there for next deploy.

For point 2: tooltip means non-modal window? Or modal window (app can't be used while it's open).

**Comment by mariokeusen** [comment]
I'd say non-modal would be better in order to let the user more flexibility. Or do you see any side-effects with that?

**Comment by oterral** [comment]
A red tooltip like the third party data warning should be enough

**Comment by mariokeusen** [comment]
Status here?
