### ISSUE TITLE
Swipe permalink doesn't work

### ISSUE THREAD

**Issue by oterral** [geoadmin/mf-geoadmin3#2477]
https://mf-geoadmin3.dev.bgdi.ch/?lang=fr&topic=swisstopo&bgLayer=voidLayer&X=190000.00&Y=660000.00&zoom=1&catalogNodes=1392&layers_timestamp=20131231,18641231&layers=ch.swisstopo.zeitreihen,ch.swisstopo.zeitreihen&swipe_ratio=0.50

**Comment by cedricmoullet** [comment]
Please add this as test in the deployment procedure
