### ISSUE TITLE
IE9/IE10 content type issue for file storing

### ISSUE THREAD

**Issue by cedricmoullet** [geoadmin/mf-geoadmin3#2479]
Content type is not sent correctly by IE9/IE10.

**Comment by gjn** [comment]
Effect is 503 on service?

**Comment by cedricmoullet** [comment]
no, but a 415

2015-07-07 14:46 GMT+02:00 Gilbert Jeiziner <notifications@github.com>:

> Effect is 503 on service?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geoadmin/mf-geoadmin3/issues/2479#issuecomment-119193286>
> .
>



-- 
Twitter: http://twitter.com/cedricmoullet
Linked In: http://www.linkedin.com/in/cedricmoullet

<http://twitter.com/cedricmoullet>

**Comment by gjn** [comment]
STrange. I tested on IE9 and it seemed to be working.

Anywho, post has it's trouble with headers in IE9. We had to fix profile service as well when we switched from GET to POST: https://github.com/geoadmin/mf-geoadmin3/blob/master/src/components/profile/ProfileService.js#L149 

We simulated formdata in IE9. See full PR here: https://github.com/geoadmin/mf-geoadmin3/commit/25d07f2e1ea5224b4c60c0384bfc1ce5a6701aea#diff-bfd39f2f09138781ec89cd2819dbd0d7

I think the same could work for files service.

**Comment by oterral** [comment]
Maybe we can do a generic transformrequest to automatically build a formDtat when it's ie9

**Comment by gjn** [comment]
Yes, this might be the best solution (inside one of angulars request hooks)

**Comment by oterral** [comment]
In fact I don't think it the same problem.

The only problem of files service is that IE9 can send custom headers.
The problem of Profile service is that it doesn't handle json as a content/type that why you need to send FormData
