### ISSUE TITLE
[Print grids]: LV03 longitude labels not visible on all print scales

### ISSUE THREAD

**Issue by mariokeusen** [geoadmin/mf-geoadmin3#2489]
UC: open app, open the print menu, check the coordinate grid checkbox, select one of the printscales from this list:
1:2 500 000
1:1 000 000
1:500 000
1:300 000
1:200 000
1:10 000
1:2 500
1:1 000

then print a PDF.
Result: for the listed scales the longitude labels of the swiss coordinate grid (LV03) are not visible
Expected: longitude labels are visible for both WGS84 and LV03 grids

Alternative: make grids checkable by user. This is also an often mentioned user's wish in the helpdesk, to have the choice, which grid to be appearing on the PDF. To discuss with @davidoesch

**Comment by davidoesch** [comment]
There is already an open feature request regarding this --- will look into that

**Comment by procrastinatio** [comment]
What do you mean, by **not visible** ? Colour, font size ?

![image](https://cloud.githubusercontent.com/assets/1236739/8667700/4593f1bc-2a03-11e5-95e8-3b7909dd9369.png)

**Comment by mariokeusen** [comment]
The latitude labels are visible, the longitude not.

**Comment by procrastinatio** [comment]
Even for the above mentionned scale, it is not systematic. Sometimes, the longitude/Y/eastings are present, sometime not.

**Comment by procrastinatio** [comment]
If you want full control, with real preview, the best alternative is using vector on the client side.

**Comment by davidoesch** [comment]
@cedricmoullet strong suggestion to go here for 
1) a vector approach on the client side 
2) or improving mapfish print server via geomapfish initivative
before we invest here more time with the WMS

**Comment by davidoesch** [comment]
we solve this with intgerating each EPSG as dataset and have only LV03 in the print as default

**Comment by davidoesch** [comment]
will be solved by data intgeration of the different epsg's. 
only lv03 will be visible by default
