### ISSUE TITLE
GPS tracking: user defined refresh interval

### ISSUE THREAD

**Issue by procrastinatio** [geoadmin/mf-geoadmin3#2504]
via helpdesk

> Es wäre nett, wenn man den Aktualisierungs Intervall beim GPS Tracking manuell einstellen könnte. Bei den paar Sekunden, die jetzt hardcoded drin sind, ist der Akku ganz schnell mal leer.
> 
> Als Wanderer z.B. brauche ich bestimmt nicht alle 5 Meter einen Waypoint. Um dann dafür nach 3 Stunden mit leerem Akku dazustehen.

**Comment by oterral** [comment]
He just has to deactivate geolocation when he doesn't use it.
