### ISSUE TITLE
Print of KML (tooltip) in Desktop Version does not work properly (image does not show up)

### ISSUE THREAD

**Issue by danielabrandt** [geoadmin/mf-geoadmin3#2513]
If I want to print out the KML: 
https://s.geo.admin.ch/65e4f43354

![pdf](https://cloud.githubusercontent.com/assets/5592275/8844996/364d2ee8-311b-11e5-913f-43284ca917a9.JPG)

see Image there is no proper print.

**Comment by gjn** [comment]
Do you mean printing the tooltip?

**Comment by danielabrandt** [comment]
yes exactly!

**Comment by gjn** [comment]
It seems to work for me: https://www.dropbox.com/s/a31lt0vjq15dg1v/Screenshot%202015-07-23%2009.33.23.png?dl=0

**Comment by gjn** [comment]
Can you specify which object exactly?

**Comment by danielabrandt** [comment]
any objekt in this link: https://s.geo.admin.ch/65e4f43354 (pdf print)

**Comment by gjn** [comment]
pdf print? tooltip print does not create pdf. I'm confused...

**Comment by gjn** [comment]
Does the print preview show up correctly? (After clicking the print icon)

**Comment by oterral** [comment]
There is a map on the tooltip. The default print browser is not efficient.

**Comment by danielabrandt** [comment]
![pdfprintkmltooltip](https://cloud.githubusercontent.com/assets/5592275/8845411/4a27e7ce-311f-11e5-96db-6a1acec44b27.JPG)
I see the map on the preview but afterwards on the pdf its gone

**Comment by gjn** [comment]
Looks like a printer/browser issue then to me. Did you try to print on a different printer?

**Comment by gjn** [comment]
Or with a different browser?

**Comment by danielabrandt** [comment]
it is IE and I tried with surface print as well it did not work with surface print

**Comment by danielabrandt** [comment]
Google Chrome does not work too
![printgooglechrome](https://cloud.githubusercontent.com/assets/5592275/8845506/12c3e4bc-3120-11e5-8b70-a65d76f55f69.JPG)

**Comment by gjn** [comment]
hmm. We'll have a look. But as @oterral said, printing maps with browser print is not very well supported. That's why we create pdfs with mapfish print in the first place...
