### ISSUE TITLE
CSS: kml overrides application

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#2515]
open
https://map.geo.admin.ch/?X=222686.62&Y=649577.34&zoom=5&lang=fr&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=KML||http:%2F%2Fpublic.geo.admin.ch%2FStoryMap_NLK25.kml,ch.swisstopo.zeitreihen&catalogNodes=457,458&layers_timestamp=,20101231&time=2010&swipe_ratio=0.50

click on a POI

then right click in map

result
![unbenannt](https://cloud.githubusercontent.com/assets/4577727/8845172/ae0dc86a-311c-11e5-8407-22a776404054.PNG)

**Comment by oterral** [comment]
Step to reproduce : 
1) Click on a marker --> that displays the tooltip
2) Right click on the map, the css appears like in the screenshot

The css of the contetn of tooltip breaks the css of the app.

@pauloamado can you fix the CSS of the KML description ?

**Comment by gjn** [comment]
We should make our css more robust as well. Can't controll all kml driven css..

**Comment by oterral** [comment]
Whatever we do, the user could  always override the previous css. Currently it's because a `!important` text is in specified in the html of the KML feature description.

**Comment by davidoesch** [comment]
cant' reproduce

**Comment by p1d1d1** [comment]
I can reproduce

![image](https://cloud.githubusercontent.com/assets/1533649/19524789/34409d96-961f-11e6-9492-4ef1a86da9e2.png)

**Comment by loicgasser** [comment]
you have to click on the marker.

But yes if css is disgustingly invasive with some !important css

**Comment by loicgasser** [comment]
@oterral is right css injection from kml there isn't much you can do

**Comment by oterral** [comment]
I've a extreme idea. We could simply remove all `<style>` tag form the html-popup when we get the information.

**Comment by gjn** [comment]
This would limit the user to style the html inside the kml description, but it would protect our site.

Not sure here.

**Comment by oterral** [comment]
we could also add manually add css class to the  content of html popup, when we receive the response of the service.

**Comment by oterral** [comment]
Kml fixed
