### ISSUE TITLE
scrollbar in selection window on large screen

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#2527]
open
https://s.geo.admin.ch/65fcc2a729

result: not all layers are vis in selection even if there are not a lot selected

![unbenannt](https://cloud.githubusercontent.com/assets/4577727/8918196/da8b827c-34b6-11e5-8386-f47797481e3e.PNG)

proposal: add scrollbar in selector if accordeon is bigger than screen height

**Comment by oterral** [comment]
I think we can set dynamically the max size of the pulldown on window resize, but we should wait the finish of the pulldown component redesign before doing this.

**Comment by oterral** [comment]
@davidoesch it's seems to be fixed, isn't it?

**Comment by davidoesch** [comment]
not completely- I can't acces the last layer
![image](https://cloud.githubusercontent.com/assets/4577727/18171720/3c6034f0-7063-11e6-8bcc-ee328abd4c2f.png)

but if i close the main tree:
![image](https://cloud.githubusercontent.com/assets/4577727/18171763/6167fc2e-7063-11e6-97dd-8a51018c8c96.png)

it works

so lets close it
