### ISSUE TITLE
[time slider] in desktop mode, tooltip window covers the time-slider

### ISSUE THREAD

**Issue by mariokeusen** [geoadmin/mf-geoadmin3#2548]
UC: open app on a desktop client, open the topic=luftbilder, enable the time-slider, go somewhere in space & time where there is data and left-click an object
Result: the tooltip window covers the time-slider (see screenshot)
![tooltip_timeslider](https://cloud.githubusercontent.com/assets/4577749/9079575/fe2dfb60-3b4b-11e5-8d3a-a066f59805b3.PNG)

Expected: tooltip window is placed a bit below the time slider in order both elements are visible
Workaround: optimize default position of the tooltip window.

**Comment by mariokeusen** [comment]
What is the status here for the further procedure? There was again a customer request for that.

**Comment by oterral** [comment]
For me nothing must be done. The tooltip corresponds to a year so it makes sense the user have to  close the popup before he changes the year

**Comment by oterral** [comment]
@davidoesch can you decide ?

**Comment by davidoesch** [comment]
global  setting

 works as defined
