### ISSUE TITLE
 On load of the application, search input is not focused

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#2549]
not the case currently on ff

**Comment by oterral** [comment]
can't reproduce

**Comment by davidoesch** [comment]
The cursor is not active in the search window, all browsers
![unbenannt](https://cloud.githubusercontent.com/assets/4577727/9624377/6f11489e-514c-11e5-8835-e5b8bd60b41d.gif)

**Comment by gjn** [comment]
I can reproduce. Bad regression. I'll elevate this to prio 1.

**Comment by gjn** [comment]
@alcapat Would be great if this is testable with selenium.

**Comment by oterral** [comment]
ok I haven't understood what the problem was.

**Comment by oterral** [comment]
@davidoesch on mobile we don't have the search focused on page laod, am I correct?

**Comment by davidoesch** [comment]
yes
