### ISSUE TITLE
Bad translations in fr

### ISSUE THREAD

**Issue by fbonzon** [geoadmin/mf-geoadmin3#2563]
In French, I see 1 spelling mistake and 3 poor translations in the Legend for layers
ch.swisstopo.swisstlm3d-karte-farbe
ch.swisstopo.swisstlm3d-karte-grau

German:
Einfahrt / Ausfahrt
Verbindungsstrasse
Perron
Schutzgebietsgrenze

Actual French incorrect:
Entrée / accès
Route d'importance régional
Perron
Limite de refuge

Correct French:
Entrée / sortie
Route d'importance régionale
Quai de gare OU Quai
Limite d'aire protégée OU Limite de site protégé

**Comment by cedricmoullet** [comment]
@mariokeusen could you please treat this ticket ?

**Comment by mariokeusen** [comment]
Forwarded to the data owner @swisstopo who's responsible for these layers.

**Comment by mariokeusen** [comment]
Adapted legends delivered by data owner:
https://redmine.prod.bgdi.ch/issues/4681
https://redmine.prod.bgdi.ch/issues/4682

**Comment by oterral** [comment]
@AFoletti, @alcapat @daguer can you make a PR for the new legend  in chsdi ?

**Comment by ltclm** [comment]
i will prepare a pr today.

**Comment by oterral** [comment]
Fixed
