### ISSUE TITLE
Create a test page for font-awesome icons

### ISSUE THREAD

**Issue by oterral** [geoadmin/mf-geoadmin3#2564]
Related to #2509
There is something that still bother me. A font-aweosme icon must be aligned with a text by default (default css is vertical-align: baseline) here it's not the case.

Are you able to provide an HTML test page with all the icons we have when you build the font?. Like this one http://fortawesome.github.io/Font-Awesome/3.2.1/cheatsheet/

With this kind of page we could easily see if icons are well-aligned and well-sized easily.

**Comment by pfanguin** [comment]
see : #2905

**Comment by oterral** [comment]
Fixed
