### ISSUE TITLE
[3D] olcs.OLCesium in GaMainController scope

### ISSUE THREAD

**Issue by fredj** [geoadmin/mf-geoadmin3#2568]
Just like the ol.Map, the olcs.OLCesium instance should be available in the GaMainController scope

**Comment by fredj** [comment]
If I understand correctly, the cesium initialization is in ga_map_directive because the map target has to be set (`map.setTarget(element[0])`) ?

**Comment by oterral** [comment]
yes

**Comment by oterral** [comment]
but now you can listen for  `globals.is3dActive` change event to load cesium viewer in the main controller .

**Comment by elemoine** [comment]
Creating an `olcs.OLCesium` instance with a map that does not yet have a `target` doesn't work? I'd consider this a bug in `ol3-cesium`.

**Comment by oterral** [comment]
Yes that doesn't work but in map.geo.admin.ch I don't think this use case happens

**Comment by fredj** [comment]
And what about listening to the `change:target` event?

**Comment by oterral** [comment]
We need lazyloading.

**Comment by oterral** [comment]
You can also listen the 'gaBgChange' event.

**Comment by elemoine** [comment]
> Yes that doesn't work but in map.geo.admin.ch I don't think this use case happens

Except if we want to create the `olcs.OLCesium` instance outside the map directive in the main controller, as @fredj is attempting to do (as I understand it).

**Comment by elemoine** [comment]
> And what about listening to the change:target event?

Indeed, the main controller can listen to `change:target`.
