### ISSUE TITLE
Loading indicator

### ISSUE THREAD

**Issue by cedricmoullet** [geoadmin/mf-geoadmin3#2570]
For some layers like https://map.geo.admin.ch/mobile.html?X=174472.32&Y=614224.87&zoom=4&topic=ech&lang=fr&bgLayer=ch.swisstopo.pixelkarte-farbe&layers_opacity=0.75&mobile=true&layers=ch.bafu.gewaesserschutzbereiche the tooltip query can take quite a long time. On mobile, we have a loading indicator. Could we have something equivalent on desktop ? Currently, the user clicks but doesn't know that something happens.
@davidoesch @gjn @oterral thoughts ?

**Comment by oterral** [comment]
On desktop the cursor is changing mormally.

**Comment by cedricmoullet** [comment]
not on chrome windows (with the desktop version, and not the mobile)

**Comment by davidoesch** [comment]
loading indicator:

nope ---please not, we managed to get around this

a loading indiactor - turning wheel- is the symbol of a slow websit. and
the prio1 we have is "SPEED" (even if speed is relative)


so: solve the issue where it occurs, simplify the geometries....as we did
for swissboundaries for the highlight


 (even I see that for the above mentioned dataset, in FF there is one on
the mouse)

**Comment by oterral** [comment]
If you don't want the cursor loading wheel effect, I think we have 2 solutions : 

 1) Use a common indicator always at the same place for all the application. A message as gmail does, or the red bar effect as on mobile, or whatever else.

or 2) Put a loading indicator at the place where the user click (for example in the button when printing, or replacing the search icon when searching (as gmap), puting an overlay when cliking on a map for a tooltip.


I'm in favor of 1 with a message as gmail.

**Comment by davidoesch** [comment]
+1 for " the red bar effect as on mobile" ( but nevertheless: we should
focus on NOT needing a loading indicator

**Comment by gjn** [comment]
Shouldn't we have the waitcursore for that? (Hourglass as long as requests are running in the back-end?)?

**Comment by davidoesch** [comment]
it is simply: hourglasses on mobile do look very win3.1

**Comment by davidoesch** [comment]
nicely done
