### ISSUE TITLE
Offline broken

### ISSUE THREAD

**Issue by oterral** [geoadmin/mf-geoadmin3#2578]
According to this: http://appcache.offline.technology/

on ios, it's broken,  can't save layers config files over https because they come from another origin.

on windows phone, it's broken. Nothing is saved by appcache (related to `no-store` header)

android works

**Comment by gjn** [comment]
Appcache is a big mess.

@davidoesch @cedricmoullet What do we do. Abandon this clients? Use http only for these clients (which seems messy...).

**Comment by davidoesch** [comment]
iOS: since in Switzerland it is the most used mobile OS: we have to support it . Even if it is a mess. ( explaining that it works under droid , warning messages etc will be a mess too)

Windows: prio2
