### ISSUE TITLE
2 timestamps comparison with swipe tool and not time-enabled layers

### ISSUE THREAD

**Issue by AFoletti** [geoadmin/mf-geoadmin3#2591]
With the old mapgeoadmin, this [1] permalink allowed the comparison, thanks to the “swipe” tool, of two WMTS pyramids for the same layer.
In V3 this only works for time-enabled layers.

@davidoesch agrees to re-implement it for each layer. How to do it is still to be defined, but I see two main ways:
- the functionality will be there, but not advertised in any way. You will have to build your permalink more or less by yourself
- by copying your layer and activating the swipe tool, in the "Selection" tab the available years will appear. similar to the time-enabled layers
![compare](https://cloud.githubusercontent.com/assets/691243/9353250/3f46767e-4667-11e5-9257-f7e9cebdd74e.PNG)

Any thoughts on that? Other possibilities?

[1] http://map.geo.admin.ch/?layers=ch.bafu.schutzgebiete-paerke_nationaler_bedeutung,ch.bafu.schutzgebiete-paerke_nationaler_bedeutung&layers_timestamp=20110103,20130416&swipe_ratio=0.5&lang=it

**Comment by oterral** [comment]
Fine for me if we allow it only from a self-construct permalink.

**Comment by AFoletti** [comment]
+1 for @oterral 's proposal.
Who should be assigned? This issue isn't getting much attention :p

**Comment by AFoletti** [comment]
recently the old timestamps were removed from the layersconfig table. This makes this ticket obsolete since there is no way now for the viewer to use them
