### ISSUE TITLE
PC always load mobile version

### ISSUE THREAD

**Issue by oterral** [geoadmin/mf-geoadmin3#2602]
PC always load mobile version.

From helpdesk 

> Window 8.1
> Browser: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.3; WOW64; Trident/7.0; Touch; .NET4.0E; .NET4.0C; .NET CLR 3.5.30729; .NET CLR 2.0.50727; .NET CLR 3.0.30729; Tablet PC 2.0; GWX:QUALIFIED)

**Comment by gjn** [comment]
Welcome to the transformer world...

**Comment by oterral** [comment]
Nearly impossible to detect.
