### ISSUE TITLE
[3D] Support kml/kmz

### ISSUE THREAD

**Issue by gjn** [geoadmin/mf-geoadmin3#2612]
For our layer ch.bazl.luftfahrthindernis, we currently do wms in 3d and drap it on the terrain. This layer has an official kml/kmz file that could be used. This file is in fully 3d (see attached screenshot which was dropped in a cesium example.

Sample code showed that this could easily be done by specifiying a kml datasource on a viewer widgets. As ol3cesium doesn't use the viewer, I was unable to add this layer. How would we add support for kml/kmz to ol3cesium? @gberaudo any ideas?

I think it would be a nice demo of realy 3D capabilities that are relatively cheap to come by.

![image](https://cloud.githubusercontent.com/assets/2572317/9546080/f88c3ca2-4d8f-11e5-9c31-2428403e755d.png)

**Comment by gberaudo** [comment]
Is it a single KML file or does it rely on KML network links?

**Comment by gjn** [comment]
Single file, dropable on the cesium viewer demo.

**Comment by oterral** [comment]
Technically we have a vector layer with the data, so with the VectorSynchroniser of ol3cesium we should apply a 3d style when we swicth to 3d. I guess.

**Comment by gberaudo** [comment]
We have two solutions:
- either to parse the KML with OL3 format and then convert it to Cesium
with the VectorSynchronizer;
- or add support for Cesium datasources in OL3-Cesium.

Both solutions have values.
The second one has the advantage of letting Cesium handle the conversion.

**Comment by oterral** [comment]
In the specific case of  `ch.bazl.luftfahrthindernis`, in 2d it's a WMTS and then in 3d it should be the KML file.

**Comment by gjn** [comment]
I think luftfahrhindernisse will not be the only case where a 2D layer is wmts/wms and in 3D, it will be vector based (geojson or kml). So I would say that we need to address this in a general manner.

It would be great to have kml datassource in ol3-cesium.

**Comment by oterral** [comment]
KMLDataSource used in production
