### ISSUE TITLE
Remove the bg layers array in bg selector service

### ISSUE THREAD

**Issue by oterral** [geoadmin/mf-geoadmin3#2632]
This [object](https://github.com/geoadmin/mf-geoadmin3/blob/master/src/components/backgroundselector/BackgroundService.js#L22) contains hardoced value for background layers we could easily put in the layersConfig.

**Comment by oterral** [comment]
What do you think @gjn @loicgasser @procrastinatio ?

**Comment by gjn** [comment]
Not sure about that. How would we put it in layersConfig?

**Comment by oterral** [comment]
Since backgrounds available are in the layersConfig through the `background` property. When this value is `true` we could add à `bgLabelId`  and a `bgDisable3d` properties as well.

**Comment by davidoesch** [comment]
ping @gjn --imho close it
