### ISSUE TITLE
Multiurl provider for 3D

### ISSUE THREAD

**Issue by cedricmoullet** [geoadmin/mf-geoadmin3#2634]
I make an issue in order to keep the record of the needed changes for the multiple url optimization.

for https://github.com/geoadmin/mf-geoadmin3/blob/49067e0bfa2d273382a5748f67e63808ad53a542/src/components/map/MapService.js#L912
please use wmts5 to wmts9.geo.admin.ch

We need multi urls for: 
 - [x] WMTS MapProxy  (wmts{10 -14}.geo.admin.ch)
 - [x] WMS MapProxy  (wmts{10 -14}.geo.admin.ch/mapproxy/service)
 - [x] WMS GeoAdmin
 - [x] Terrain (terrain{0 -4}.geo.admin.ch/)

**Comment by oterral** [comment]
PR in cesium https://github.com/AnalyticalGraphicsInc/cesium/pull/3038

**Comment by oterral** [comment]
Finally fixed with https://github.com/geoadmin/mf-geoadmin3/pull/2749
