### ISSUE TITLE
Feedback-Tool: problem with absolute filepath in attached filename - IE

### ISSUE THREAD

**Issue by p1d1d1** [geoadmin/mf-geoadmin3#2640]
Steps to reproduce:

1) Open Feedback-Tool with IE
2) Attach a file. Let's say the file name is "file.png" 
3) Send report

The name of the attached file in the email contains the entire path to the file on the local PC.
e.g. vt00003a.lt.admin.chswisstopo-Home$UserconfigDesktopfile.png.

Could you check it?
Thanks

**Comment by oterral** [comment]
We can't do anything , mor eprobably a fix can come on server side.

See http://stackoverflow.com/questions/2200100/input-type-file-for-ie-gives-full-path-need-file-name-only

**Comment by oterral** [comment]
I've created an issue on https://github.com/geoadmin/mf-chsdi3/issues/2052

**Comment by gjn** [comment]
@p1d1d1 As described in the linked article, this could be fixed by changing a setting in IE. Would this be fine for you?

**Comment by p1d1d1** [comment]
Client side?

**Comment by gjn** [comment]
Browsersettings

**Comment by p1d1d1** [comment]
@gjn no more actions needed.
