### ISSUE TITLE
Reset rotation refactoring

### ISSUE THREAD

**Issue by cedricmoullet** [geoadmin/mf-geoadmin3#2652]
use the existing function https://github.com/geoadmin/mf-geoadmin3/blob/master/src/components/map/MapService.js#L1443 for adding an ol3d param?

**Comment by cedricmoullet** [comment]
@fredj ?

**Comment by fredj** [comment]
Done: https://github.com/geoadmin/mf-geoadmin3/blob/master/src/components/controls3d/Controls3dDirective.js#L103
