### ISSUE TITLE
double click /tab -> zoom

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#2663]
desktop and mobile 
all os
https://mf-geoadmin3.dev.bgdi.ch/ltmoc/
in 3d
double click /tab 
Result: nothing happens
expected result: zoom to mouse position as in 2d an gmaps

**Comment by cedricmoullet** [comment]
@fredj doable ?

**Comment by fredj** [comment]
I've asked the question in the cesium mailing list

**Comment by cedricmoullet** [comment]
@fredj answer ?

**Comment by fredj** [comment]
Answer: https://groups.google.com/d/msg/cesium-dev/727fX-AhEDQ/Qs0GEBW5AQAJ

Should I start to work on this?

**Comment by cedricmoullet** [comment]
@davidoesch is is needed for the first Beta ?

**Comment by davidoesch** [comment]
nth

**Comment by davidoesch** [comment]
ping @fredj
