### ISSUE TITLE
void layer : set lightning

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#2664]
all os / all devices 
start with
https://mf-geoadmin3.dev.bgdi.ch/ltmoc/?dev3d=true&topic=ech&lang=de&bgLayer=voidLayer&layers=ch.swisstopo.swisstlm3d-karte-farbe,ch.bfs.arealstatistik-1997&layers_opacity=1,0.75&lon=7.86309&lat=46.37826&elevation=3112&heading=195.037&pitch=-5.312&layers_visibility=false,true

a layer draped over pure terrain
switch to 3d
result: "blue hills"
expected result : hillshading in greyish done with lightning

( I know this will be solved once we have the correct tiles)

**Comment by cedricmoullet** [comment]
Or deactivate void layer of the 3d mode.

**Comment by davidoesch** [comment]
Void layer is a need - as is it in 2d. Let's see how lighting works.

**Comment by cedricmoullet** [comment]
@loicgasser demo link ?

**Comment by loicgasser** [comment]
sure I can work on that, we need to prepare a new terrain tileset with unit vectors.

**Comment by davidoesch** [comment]
@gjn needed?

**Comment by gjn** [comment]
This is not high priority for the buildings beta.

**Comment by davidoesch** [comment]
IMHO this will be solved when we have shadows calculated on the fly

**Comment by gjn** [comment]
No. Terrain data needs to have modals ingrained to take advantage of this. Current set of terrain does not have them - so this ticket means creation of terrain with normals.

**Comment by davidoesch** [comment]
correct, I just had BETA in mind

**Comment by davidoesch** [comment]
we reopen this when we need shadow
