### ISSUE TITLE
icons rotate/tilt on mobile smaller

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#2666]
on mobile screens the icons rotate/tilt on mobile smaller are taking up a lot of space
-> since pinch/rotate makes more sense there , we can at least have the tilt/rotate have the same size as the other icons on the right

**Comment by cedricmoullet** [comment]
@davidoesch could you organize the icons ?

**Comment by cedricmoullet** [comment]
@davidoesch is it ready ?

**Comment by davidoesch** [comment]
Ok.
