### ISSUE TITLE
zoom in/out: leftmouse hold and wheel

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#2667]
compared to schweizmobil

zoom in/out: leftmouse hold and wheel makes to big steps : user gets lost very fast

expected result: same increment as in schweizmobil

**Comment by cedricmoullet** [comment]
@gberaudo @fredj what are the schweizmobil settings ?

**Comment by fredj** [comment]
I don't remember that we have a specific setting for veloland, maybe the cesium version ?

**Comment by davidoesch** [comment]
Cesium version

**Comment by cedricmoullet** [comment]
@davidoesch is it still the case ?

**Comment by davidoesch** [comment]
tested under chrome ff: they are the same now
