### ISSUE TITLE
collision distance: default mode 

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#2668]
collision distance: default mode 

*default* views like this https://mf-chsdi3.dev.bgdi.ch/ltmoc/shorten/6702a2f1bf

do not make any sense

proposal:
an altitude dependent collision setting:

for camera positions of altitudes above 1800m : use the same settings for distance camera - terrain as in schweizmobil
for camera positions of altitudes below 1800m : use half the distance schweizmobil has currently for urban area as for eg city of Bern

**Comment by cedricmoullet** [comment]
@davidoesch what is the prio ?

**Comment by davidoesch** [comment]
IMHO a must for alpha

**Comment by fredj** [comment]
I'm working on this.

**Comment by fredj** [comment]
Note: schweizmobil has only one value for the camera - terrain distance: 500m

**Comment by fredj** [comment]
To play the devil's advocate, this "I don't know what I'm looking at" view is not specific to the 3d mode, example:
https://map.geo.admin.ch/?X=145569.64&Y=535331.46&zoom=13

**Comment by fredj** [comment]
Plase test https://mf-geoadmin3.dev.bgdi.ch/minimumZoomDistance/?dev3d=true

**Comment by davidoesch** [comment]
perfect! ready to give it to the real users  (@fredj in the 2d case: if you ever get lost: :swimmer:)
