### ISSUE TITLE
WMS Import support 

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#2669]
Since cesium supports WMS
-> the WMS inport should work, but does currently not:
https://mf-geoadmin3.dev.bgdi.ch/ltmoc/?dev3d=true&topic=ech&lang=de&bgLayer=ch.swisstopo.pixelkarte-grau&layers=WMS||Fahrverbotszone||https:%2F%2Fwww.gis.stadt-zuerich.ch%2Fmaps%2Fservices%2Fwms%2FWMS-ZH-STZH-OGD%2FMapServer%2FWMSServer%3F||Fahrverbotszone&lon=8.53992&lat=47.36157&elevation=1963&heading=360.000&pitch=-40.011

Question: how to handle the rare case where the GetCap does not support WGS84 (will not work in 3d)? but the swiss projection (will work in 2d)
-> IMHO: we extend the import tool with a feedback: "does not support WGS84 etc might not work in 2d  and or 3d"

**Comment by oterral** [comment]
In the url you send the problem is the WMS has 2 `??`at the end of wms url. I fix that.

**Comment by davidoesch** [comment]
nice works now--even with labels https://mf-chsdi3.dev.bgdi.ch/ltmoc/shorten/6721706404
