### ISSUE TITLE
space view: lost

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#2670]
if zooming completely out
the white globe makes it hard to find switzerland https://mf-geoadmin3.dev.bgdi.ch/ltmoc/?dev3d=true&lang=de&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.swissimage-product&lon=5.58031&lat=44.90932&elevation=20074287&heading=359.935&pitch=-88.562

schweizmobil does not have a solution neither

-possibility to restrict cesium on zoom out?
-add at least a grid to the background ("under the terrain" ....)

more ideas?

**Comment by cedricmoullet** [comment]
@gberaudo @fredj is it possible to restrict the space where the camera can move ?

**Comment by fredj** [comment]
The maximum zoom can be restricted by using the `maximumZoomDistance` property (see https://cesiumjs.org/Cesium/Build/Documentation/ScreenSpaceCameraController.html)

**Comment by cedricmoullet** [comment]
I was more thinking to a kind of 3D box limiting the movement of the camera
