### ISSUE TITLE
[PDF print] no data visible in PDF

### ISSUE THREAD

**Issue by mariokeusen** [geoadmin/mf-geoadmin3#2676]
UC: open app, choose any bg layer and any data layer(s), print a PDF in any scale or format
Result: the PDF is empty, not data are drawn in the document, neither from the bg layers nor from data layes
Expected: same bg and data layers are visible in the PDF as in the map window.

Please fix with high prio! I checked with IE11 and chrome -> same results.

**Comment by mariokeusen** [comment]
There are also first helpdesk messages with the same problem...

**Comment by cedricmoullet** [comment]
@procrastinatio @gjn @danduk82 related to varnish change ?

**Comment by procrastinatio** [comment]
Non, il y a une histoire de certificat

**Comment by cedricmoullet** [comment]
Who treats this issue ?

2015-09-17 14:45 GMT+02:00 procrastinatio <notifications@github.com>:

> Non, il y a une histoire de certificat
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geoadmin/mf-geoadmin3/issues/2676#issuecomment-141069887>
> .
>



-- 
Twitter: http://twitter.com/cedricmoullet
Linked In: http://www.linkedin.com/in/cedricmoullet

<http://twitter.com/cedricmoullet>

**Comment by procrastinatio** [comment]
```java.io.IOException: server certificate change is restrictedduring renegotiation
````

**Comment by cedricmoullet** [comment]
Again, who treats this issue ??

2015-09-17 14:49 GMT+02:00 procrastinatio <notifications@github.com>:

> ```java.io.IOException: server certificate change is restrictedduring
> renegotiation
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geoadmin/mf-geoadmin3/issues/2676#issuecomment-141071079>
> .
>



-- 
Twitter: http://twitter.com/cedricmoullet
Linked In: http://www.linkedin.com/in/cedricmoullet

<http://twitter.com/cedricmoullet>

**Comment by gjn** [comment]
expired root certivicate that jvm is not able to update?

Maybe tomcat restart might help.

I propose me, @procrastinatio and @danduk82 work on this as it's cause is not clear.

**Comment by cedricmoullet** [comment]
Thanks.
Yes, please restart.

2015-09-17 14:51 GMT+02:00 Gilbert Jeiziner <notifications@github.com>:

> expired root certivicate that jvm is not able to update?
>
> Maybe tomcat restart might help.
>
> I propose me, @procrastinatio <https://github.com/procrastinatio> and
> @danduk82 <https://github.com/danduk82> work on this as it's cause is not
> clear.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geoadmin/mf-geoadmin3/issues/2676#issuecomment-141071651>
> .
>



-- 
Twitter: http://twitter.com/cedricmoullet
Linked In: http://www.linkedin.com/in/cedricmoullet

<http://twitter.com/cedricmoullet>

**Comment by gjn** [comment]
I would first like to know what changed regarding certificates on our infrastructure. pinging @danduk82 @hpchrist .

**Comment by cedricmoullet** [comment]
I wouldn't wait. Prod is down, so it can't be worst.....

2015-09-17 14:53 GMT+02:00 Gilbert Jeiziner <notifications@github.com>:

> I would first like to know what changed regarding certificates on our
> infrastructure. pinging @danduk82 <https://github.com/danduk82> @hpchrist
> <https://github.com/hpchrist> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geoadmin/mf-geoadmin3/issues/2676#issuecomment-141072345>
> .
>



-- 
Twitter: http://twitter.com/cedricmoullet
Linked In: http://www.linkedin.com/in/cedricmoullet

<http://twitter.com/cedricmoullet>

**Comment by gjn** [comment]
restart of tomcat seems to have fixed the issue. Could anyone verify?

**Comment by cedricmoullet** [comment]
yes, it works

2015-09-17 14:56 GMT+02:00 Gilbert Jeiziner <notifications@github.com>:

> restart of tomcat seems to have fixed the issue. Could anyone verify?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geoadmin/mf-geoadmin3/issues/2676#issuecomment-141073355>
> .
>



-- 
Twitter: http://twitter.com/cedricmoullet
Linked In: http://www.linkedin.com/in/cedricmoullet

<http://twitter.com/cedricmoullet>

**Comment by mariokeusen** [comment]
it works again

**Comment by gjn** [comment]
We need to analyse this why this can happen out of a sudden. Was it triggered by something we changed?

**Comment by gjn** [comment]
@procrastinatio Can you ping @danduk82 or @hpchrist ?

**Comment by hpchrist** [comment]
Hi

we have changed the geo.admin.ch multi SAN certificate. But I cannot say why tomcat needed to be restarted. As far as I know, it has never been necessary in the past, has it?

Best regards,

Hanspeter

**Comment by procrastinatio** [comment]
Not the first time we change a certificate. Didn't happen before

**Comment by cedricmoullet** [comment]
afaik, it was never the case before.

2015-09-17 14:59 GMT+02:00 hpchrist <notifications@github.com>:

> Hi
>
> we have changed the geo.admin.ch multi SAN certificate. But I cannot say
> why tomcat needed to be restarted. As far as I know, it has never been
> necessary in the past, has it?
>
> Best regards,
>
> Hanspeter
>
> From: Cédric Moullet [mailto:notifications@github.com]
> Sent: Donnerstag, 17. September 2015 14:57
> To: geoadmin/mf-geoadmin3
> Cc: Christ Hanspeter swisstopo
> Subject: Re: [mf-geoadmin3] [PDF print] not data visible in PDF (#2676)
>
> yes, it works
>
> 2015-09-17 14:56 GMT+02:00 Gilbert Jeiziner <notifications@github.com
> <mailto:notifications@github.com>>:
>
> > restart of tomcat seems to have fixed the issue. Could anyone verify?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/geoadmin/mf-geoadmin3/issues/2676#issuecomment-141073355>
>
> > .
> >
>
>
>
> --
> Twitter: http://twitter.com/cedricmoullet
> Linked In: http://www.linkedin.com/in/cedricmoullet
>
> <http://twitter.com/cedricmoullet>
>
>
> —
> Reply to this email directly or view it on GitHub<
> https://github.com/geoadmin/mf-geoadmin3/issues/2676#issuecomment-141073575>.
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geoadmin/mf-geoadmin3/issues/2676#issuecomment-141074161>
> .
>



-- 
Twitter: http://twitter.com/cedricmoullet
Linked In: http://www.linkedin.com/in/cedricmoullet

<http://twitter.com/cedricmoullet>

**Comment by gjn** [comment]
I seem to remember a similar issue once with JVM that wasn't capable to update a certificate. Might be that it caches some certificates and an updated SAN certificated can't be validated anymore.

Maybe it also depends on the domain that is update. Printing worked, but no tiles could be downloaded. So maybe we never updated wmts related certificates before.

**Comment by procrastinatio** [comment]
So now expect trouble form other java users...

**Comment by hpchrist** [comment]
I already informed Beat about this issue and asked him to inform the clients that we know had issues in the past when our SSL certificate changed. As far as I know it was Mobiliar (and maybe as well ASTRA?`) who use some kind of Java SSL clients to access our services...

**Comment by hpchrist** [comment]
@gjn we updated wmts related certificates before, since *all* geo.admin.ch "subdomains" are treated in one single SAN EV certificate. It's the same certificate that contains map.geo.admin.ch, wmts.geo.admin.ch, wms.geo.admin.ch, etc., etc.

**Comment by gjn** [comment]
Might be that my memory brought up other clients JVM issues with new certificates.
