### ISSUE TITLE
layer selector: empty

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#2677]
Current selection
https://mf-geoadmin3.dev.bgdi.ch/?dev3d=true&topic=ech&lang=en&bgLayer=ch.swisstopo.pixelkarte-farbe&lon=8.43054&lat=47.10591&elevation=1095&heading=29.410&pitch=-49.998

if no layer is loaded
![unbenannt](https://cloud.githubusercontent.com/assets/4577727/9936083/849f7388-5d5a-11e5-86f4-51d7d984898e.PNG)

-> this text is to big (not standard typefont, not CI CD) and it tells the user sth he already knows
-> distracts from "looking for more maps" whcih is where we actually want the user to go

proposal

A) remove this text field completely

or

B) add the msgid help_search_data_link with the correct typefont in this feild, remove help_search_data_link at the footer if it is empty

I tend to B) @cedricmoullet

**Comment by cedricmoullet** [comment]
B

**Comment by davidoesch** [comment]
ok go for B @oterral

**Comment by oterral** [comment]
ok

**Comment by oterral** [comment]
@davidoesch like this: 
![layermanager](https://cloud.githubusercontent.com/assets/621420/9954585/935d7ccc-5dea-11e5-90c7-5aa1c5aeef0f.png)

**Comment by oterral** [comment]
or you  want it is centered and larger?

**Comment by davidoesch** [comment]
yes

**Comment by davidoesch** [comment]
Centered makes sense, also if other data is available. don't change the
font since we should stick to CI CD  fonts we have

**Comment by oterral** [comment]
@davidoesch [test](https://mf-geoadmin3.dev.bgdi.ch/teo_empty)

**Comment by davidoesch** [comment]
purrfect - ready for deploy
