### ISSUE TITLE
A lot of 204

### ISSUE THREAD

**Issue by cedricmoullet** [geoadmin/mf-geoadmin3#2683]
If I start https://mf-geoadmin3.dev.bgdi.ch/ltmoc/?dev3d=true&topic=ech&lang=fr&bgLayer=ch.swisstopo.pixelkarte-farbe&lon=7.85044&lat=46.37530&elevation=8588&heading=0.094&pitch=-49.972 I can observe that several requests for ch.swisstopo.swisstlm3d-karte-farbe WMTS delivers a 204. Since this layer covers whole switzerland, it's not supposed to send 204 back. Any idea ?

**Comment by oterral** [comment]
There is some tiles outer the swiss which are downloaded, see the tile L10X1056Y249

![outside](https://cloud.githubusercontent.com/assets/621420/9963246/a0d00754-5e2a-11e5-88cf-93cdd06c7d3c.png)

**Comment by cedricmoullet** [comment]
I hope that it's possible to avoid to download tiles outside switzerland

**Comment by fredj** [comment]
Can we close this issue?
