### ISSUE TITLE
On second click on 3d, the map doesn't keep the current center

### ISSUE THREAD

**Issue by oterral** [geoadmin/mf-geoadmin3#2687]
First laod is ok then you re-click to go on 2d then on 3d, the mpa slide to the south.

1) Open https://mf-geoadmin3.dev.bgdi.ch/index.html?lang=fr&topic=are&bgLayer=ch.swisstopo.pixelkarte-grau&dev3d=true&layers_visibility=false&catalogNodes=954,959,965&X=198957.00&Y=600930.00&zoom=10

2) The map is centered on Kirchenfeld
3) Active the 3d -> The map is centered on Kirchenfeld
4) Active the 2d ->  The map is centered on Kirchenfeld
5) Active the 3d 

-> The map is not centered on Kirchenfeld anymore

Expected:

The map is still centered on Kirchenfeld

**Comment by gjn** [comment]
It seems to happen after every pan in 2D. Effect is more visible when browser is sized in landscape. (In protrait, effect is minimal).

**Comment by cedricmoullet** [comment]
@gjn could you check with actual version ?

**Comment by gjn** [comment]
This is good on current master.
