### ISSUE TITLE
Error in IE 11

### ISSUE THREAD

**Issue by cedricmoullet** [geoadmin/mf-geoadmin3#2689]
Starting in IE11/IE10: https://mf-geoadmin3.dev.bgdi.ch/ltmoc/src/
Generates the following errors:
![image](https://cloud.githubusercontent.com/assets/319676/10038078/8b4fb9e0-61bf-11e5-91a5-c7367614572b.png)

**Comment by cedricmoullet** [comment]
@oterral @gjn could you please have a look before the deployment ?

**Comment by gjn** [comment]
source mode in IE is broken for quite some time now (> 12 month). It never worked in IE9.

**Comment by gjn** [comment]
non-issue for me. @oterral ?

**Comment by cedricmoullet** [comment]
It affecta all IE version

Envoyé de mon iPhone

**Comment by oterral** [comment]
Doesn't affect the functionnalities but it's not nice. It seems it's related to teh translate directive.
