### ISSUE TITLE
Draw annotation text not translated

### ISSUE THREAD

**Issue by cedricmoullet** [geoadmin/mf-geoadmin3#2691]
![image](https://cloud.githubusercontent.com/assets/319676/10038260/5c5b6630-61c3-11e5-80ac-200a4995f2c6.png)

**Comment by gjn** [comment]
Like this in prod. I'll have a look.

**Comment by gjn** [comment]
missing translations for annotation as well.

**Comment by davidoesch** [comment]
draw_next_marker would fit
