### ISSUE TITLE
Visibility in 3D permalink

### ISSUE THREAD

**Issue by gjn** [geoadmin/mf-geoadmin3#2692]
It seems that the 3D viewer doesn't take in account the fact that a layer can have a "false" visibility:
https://mf-geoadmin3.dev.bgdi.ch/ltmoc/?dev3d=true&lang=fr&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bafu.wrz-wildruhezonen_portal,ch.swisstopo.swisstlm3d-wanderwege&layers_visibility=false,false,false,false&layers_timestamp=18641231,,,&lon=8.22546&lat=46.85843&elevation=88829&heading=360.000&pitch=-50.000

In this case, for example, ch.bfs.gebaeude_wohnungs_register is not visible but the 3D viewer still shows it.
Who could fix this issue?

**Comment by gjn** [comment]
I've tested it quickly. This seems only to be the case for wohnungs_register layer. Other layers seem to be ok.

Maybe because wohnungsregister layers is a layergroup? As we know, Guillaume is currently working on layergroup, so I expect this to be fixed by then.

@gberaudo Good testcase for layer group: `ch.bfs.gebaeude_wohnungs_register`

**Comment by gberaudo** [comment]
Fixed with #2710.
