### ISSUE TITLE
[hydroweb] one comma too much in copyright tool

### ISSUE THREAD

**Issue by mariokeusen** [geoadmin/mf-geoadmin3#2695]
UC: open the following permalink:
Ehm, this problem is not solved...
https://map.geo.admin.ch/?X=190000.00&Y=660000.00&zoom=1&topic=ech&lang=fr&bgLayer=voidLayer&layers=ch.bafu.hydrologie-hintergrundkarte,ch.bafu.hydroweb-messstationen_gefahren
Look at the copyright on the bottom right

Result: Données: OFEV,

Expected: Données: OFEV

Workaround: Please remove the comma, which is too much in this case. This issue exists in every language.

**Comment by oterral** [comment]
@mariokeusen cache issue? it works for me
