### ISSUE TITLE
print: maquette portrait is not centered

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#2697]
all browsers on a 16:9 screen

open https://s.geo.admin.ch/6726e1e8f4
use print rotate
result:
1:20K is not centered
![unbenannt](https://cloud.githubusercontent.com/assets/4577727/10055106/c287748c-6234-11e5-978d-efe2bd4fdcdd.png)

**Comment by cedricmoullet** [comment]
Yes, it is. It's because of the transparency of the header and because your screen is small. I would keep as it is.
