### ISSUE TITLE
print: portait 3rd party warning

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#2699]
3rd party warning eg https://s.geo.admin.ch/6726e7076b

in print portrait

- 3rd party part font is not the same size as the standard disclaimer
- 3rd party part: line break carriage return is missing
![unbenannt](https://cloud.githubusercontent.com/assets/4577727/10055314/cfb4d108-6235-11e5-9e56-e931718d1bdd.png)

**Comment by oterral** [comment]
@davidoesch Can we put the red warning on the bottom after the "Haftung: ...." text ? Because in portrait the number lines used differs between languages and it's not nice.

**Comment by davidoesch** [comment]
Yes ok
