### ISSUE TITLE
print: third party warning doubel entries and not red

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#2700]
load 9 third party kml files from same location as eg in https://s.geo.admin.ch/6726e7076b

then print portrait
result:
- twice the same 3rd party in footer
- one in red once in black

expected result:
only one mention of the same url, in red
![unbenannt](https://cloud.githubusercontent.com/assets/4577727/10055378/2b804238-6236-11e5-9b43-87683814967d.png)

**Comment by cedricmoullet** [comment]
@procrastinatio could you have a look and fix it ?
