### ISSUE TITLE
Popup on topic switch

### ISSUE THREAD

**Issue by p1d1d1** [geoadmin/mf-geoadmin3#2707]
Use case:

1) Go to "Change topic"
2) Click on a specific topic
3) Topic is shown and a popup is shown containing "Nutzungsbedingungen"

is that possible?

**Comment by davidoesch** [comment]
No - no po ups and we deal globally in disclaimer with nurzungsbedingungen. This fits for wildruhezonen, skitouren et al.

So definitely no. Happy to discuss this with your customer
