### ISSUE TITLE
Ordering issue in 3D viewer

### ISSUE THREAD

**Issue by cedricmoullet** [geoadmin/mf-geoadmin3#2712]
https://mf-geoadmin3.dev.bgdi.ch/ltmoc/?dev3d=true&topic=ech&lang=fr&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.swissimage-product,ch.bfs.gebaeude_wohnungs_register&lon=6.93318&lat=46.81298&elevation=1548&heading=355.093&pitch=-49.422

Addresses should be above swissimage

**Comment by oterral** [comment]
Fixed on prod https://map.geo.admin.ch/?dev3d=true&topic=ech&lang=fr&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.swissimage-product,ch.bfs.gebaeude_wohnungs_register&lon=6.95555&lat=46.67230&elevation=19646&heading=355.109&pitch=-49.560
