### ISSUE TITLE
switch from 2d to 3d: move south

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#2714]
start
https://mf-geoadmin3.dev.bgdi.ch/?dev3d=true

activate 3d

result: half of the screen (north) is empty is germany
https://mf-geoadmin3.dev.bgdi.ch/?dev3d=true&topic=ech&lang=de&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bafu.wrz-wildruhezonen_portal,ch.swisstopo.swisstlm3d-wanderwege&layers_visibility=false,false,false,false&layers_timestamp=18641231,,,&lon=8.22546&lat=46.85843&elevation=88829&heading=360.000&pitch=-50.000

since this is the first impression a user will get from 3d, he should get the "wow effect" and start with an impressive scenery

proposal

either 
A)start further south (which is complicated)

or
B) with with an elevation 9000 with the Pilatus and lucernen

https://mf-geoadmin3.dev.bgdi.ch/?dev3d=true&topic=ech&lang=de&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bafu.wrz-wildruhezonen_portal,ch.swisstopo.swisstlm3d-wanderwege&layers_visibility=false,false,false,false&layers_timestamp=18641231,,,&lon=8.29277&lat=46.93239&elevation=9011&heading=0.050&pitch=-49.399

my vote goes for B)

**Comment by gjn** [comment]
We need a solution that works allmthe time, not just for default coordinates, but for any coordinate and any zoom level.

I'd say A with the condition that everything that was visible in 2d should at least be shown in 3d. 3d wil show mor3 because of inclination.

**Comment by gjn** [comment]
@fredj The switch to 3D from default 2D view is not good anymore. I think it's a combination of extent limitations and minimumretrieval level, as discussed in the other issue. You seem to be working on that https://github.com/geoadmin/mf-geoadmin3/pull/2828, right?

**Comment by gjn** [comment]
The initial switch to 3D is now working well. It's positoined correctly. (You can see [here](mf-geoadmin3.dev.bgdi.ch/?dev3d=true)

Anyhow, I'm not sure about black/white stuff. I'll open an issue for that.
