### ISSUE TITLE
Tooltip: 2d footprint of highlight visible

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#2715]
https://mf-geoadmin3.dev.bgdi.ch/?dev3d=true&topic=geol&lang=fr&bgLayer=ch.swisstopo.pixelkarte-grau&lon=7.14721&lat=46.08595&elevation=6990&heading=286.274&pitch=-24.682&layers=ch.swisstopo.swissimage-product

although it is a nice feature, for the normal user this will be to complex to understands

![unbenannt](https://cloud.githubusercontent.com/assets/4577727/10122164/28b7b406-650f-11e5-9eea-fff623d91ccb.PNG)

**Comment by gjn** [comment]
That's a bug.

**Comment by oterral** [comment]
Line clamped to ground not yet available in Cesium

**Comment by mariokeusen** [comment]
Reproduced on all browsers on apple OSX. For me this is also a bug.
Expected: highlight outline fits to the highlight fill geometry.

**Comment by oterral** [comment]
Feature is planned on top of the Cesium todo list for 2016.

**Comment by gjn** [comment]
#3104 is the same. Missing clampToGround support in Cesium.

**Comment by oterral** [comment]
Duplicate of #3104
