### ISSUE TITLE
tooltip box highlight

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#2716]
https://mf-geoadmin3.dev.bgdi.ch/?dev3d=true&topic=geol&lang=fr&bgLayer=ch.swisstopo.pixelkarte-grau&lon=7.14721&lat=46.08595&elevation=6990&heading=286.274&pitch=-24.682&layers=ch.swisstopo.swissimage-product

when clicking in the object info box: red background

expected result:
as in 2d -> no bg color change in 
![unbenannt](https://cloud.githubusercontent.com/assets/4577727/10122178/900d02b4-650f-11e5-99ac-dee207e84901.PNG)

**Comment by davidoesch** [comment]
this affects now as well prod... and is really not nice

**Comment by cedricmoullet** [comment]
Is it not what we wanted ?

**Comment by davidoesch** [comment]
it makes sense if multiple ( more than one) features are active/selected on the map (consistency with select by rectangle) , but  not if there is only one (1) object selected: since it *is* already highlighted

@oterral  doable?

**Comment by oterral** [comment]
Yes we could remove it if only one object selected.

**Comment by davidoesch** [comment]
ok please proceed
