### ISSUE TITLE
Inconsistent behaviour on topic change

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/mf-geoadmin3#2721]
Step to reproduce:
1. open map.geo.admin.ch
2. Switch to geol topic

Result:
The layer manger is closed automatically.

Expected result:
??

Another use case is:
1. Open map.geo.admin.ch?topic=geol
2. Switch to ech topic

Result:
The catalog is closed automatically.

Excpected result:
??

This is kind of confusing for me, so I can't imagine users...

I believe that if the catalog or layertree were previously open before topic change, we shouldn't close them.

**Comment by davidoesch** [comment]
Shortterm
A) "if the catalog or layertree were previously open before topic change, we shouldn't close them."
-> Agree, if the cost on implementing that (incl side effects/regression) are reasonable- please do so

Longterm
B) we would like to close the topic tree by default on all topics and encourage the topic owner to show off on start with his 3-5 most wanted layer and layer manager open. for this we need ech as a show case

-> so please implement A)

**Comment by oterral** [comment]
I think the catalog should be hide if the new topic has activated layers , no?

**Comment by davidoesch** [comment]
this is currently the goal for ech and after the feedback from the topic
owners for all topics

**Comment by oterral** [comment]
We must keep in mind than probably 1% of the user (mainly us) change the topic, so I think we can live with that.

**Comment by davidoesch** [comment]
exactly... we do already urge dataowners to communicate URLs rather than
encourage users to switch topics
