### ISSUE TITLE
[Revision Service]: Permalink without X/Y

### ISSUE THREAD

**Issue by p1d1d1** [geoadmin/mf-geoadmin3#2722]
@gjn we are receiving revision messages where the permalink has no X/Y coordinates.
Could you please check this?

[Meta-2015092410280637.txt](https://github.com/geoadmin/mf-geoadmin3/files/4406/Meta-2015092410280637.txt)

**Comment by gjn** [comment]
It's due to a recent change we did. In default view, then the user didn't pan or zoom yet, X/Y/zoom is not in the permalink.

That's not a problem, because the default view doesn't change.
