### ISSUE TITLE
First 3D activation doesn't position the camera correctly

### ISSUE THREAD

**Issue by cedricmoullet** [geoadmin/mf-geoadmin3#2724]
all in the title

**Comment by gjn** [comment]
I think I've found the reason for this. It's related to ol3-cesium initialisation, where the canvas size is not updated on initialisation.

**Comment by gjn** [comment]
ol3-cesium patch is ready. See https://github.com/openlayers/ol3-cesium/pull/253

@gberaudo if you could have a look.

**Comment by oterral** [comment]
Fixed [Test](https://mf-geoadmin3.dev.bgdi.ch/?lang=fr&topic=ech&dev3d=true&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bafu.wrz-wildruhezonen_portal,ch.swisstopo.swisstlm3d-wanderwege&layers_visibility=false,false,false,false&layers_timestamp=18641231,,,&lon=8.88086&lat=43.36545&elevation=389646&heading=360.000&pitch=-43.714)
