### ISSUE TITLE
Deactive right mouse click in 3D

### ISSUE THREAD

**Issue by cedricmoullet** [geoadmin/mf-geoadmin3#2725]

**Comment by davidoesch** [comment]
Why this? If the user clicks over the horizon line just don't show no coordinates . Since we already plan to show the altitude in the footer the tooltip makes complete sense--- if not In the alpha then in the beta

**Comment by cedricmoullet** [comment]
Right button is used to zoom in zoom out.
We try to change that, but, for now, we need to deactivate context popup.

2015-09-30 12:33 GMT+02:00 davidoesch <notifications@github.com>:

> Why this? If the user clicks over the horizon line just don't show no
> coordinates . Since we already plan to show the altitude in the footer the
> tooltip makes complete sense--- if not In the alpha then in the beta
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geoadmin/mf-geoadmin3/issues/2725#issuecomment-144349888>
> .
>



-- 
Twitter: http://twitter.com/cedricmoullet
Linked In: http://www.linkedin.com/in/cedricmoullet

<http://twitter.com/cedricmoullet>

**Comment by davidoesch** [comment]
Ok

To Be consistent with 2d : left double click is zoom in
