### ISSUE TITLE
KML import: issues with coordinates well outside extent

### ISSUE THREAD

**Issue by procrastinatio** [geoadmin/mf-geoadmin3#2733]
Look at:

[Good KML](https://s.geo.admin.ch/6752d7872b)

[Wroong KML](https://s.geo.admin.ch/6752d8789d)

```
<coordinates>
	16.7852253163771,0.00176540157163452,0 16.7851783752391,0.00177218988870834,0 
</coordinates> 

```

**Comment by oterral** [comment]
If the placemark (well outside extent) is alone in the KML, the map is well centered on it.
When there is 2 placemarks very far away one from each other the map can't zoom out enough to show the 2 features because we have constrained the resoulton of the view .

So I don't think it's a bug.

**Comment by oterral** [comment]
Or may be we can improve that and at least, intersects the features's extent with the projection extent to avoid the map zooms in a no man's land.

**Comment by Jenselme** [comment]
FYI, the patch from #2741 fixed the problem in dev but not in prod (with build.js). From what I understand, the versions of OpenLayers are not exactly the same, and in dev, ol refuses to fit to an empty extent, whereas in prod it changes the center anyway.

To completely get rid of the problem, I had to add a method to `gaMapUtils`:

```js
        isExtentEmpty: function(extent) {
          return extent[0] > extent[2] || extent[1] > extent[3];
        },
```

and modify `addKmlLayer`:

```js
if (options.zoomToExtent &&
                  !gaMapUtils.isExtentEmpty(layerExtent)) {
```

I can open a PR for that if you are interested (and have the bug with build.js too).

**Comment by oterral** [comment]
I'm not fully understand what do you mean.   Do you mean `olMap.getView().fit([])` doesn't work or  `olMap.getView().fit([200000,600000,200000, 600000])` doesn't work ?

**Comment by Jenselme** [comment]
I mean that on some version of ol, `olMap.getView().fit([200000,600000,190000, 590000])` (which is a zoom on an empty extent) will zoom somewhere and that somewhere can be outside the portal, thus not completely solving the issue.

Is this clearer?

**Comment by oterral** [comment]
Since an extent is defined by `[minx, miny, maxx, maxy]` , your extent is not valid,so I don't think we can consider that as a bug in mf-geoadmin3.  The extent is calculate by the intersection of the `gaGlobalOptions.defaultExtent`and `source.getExtent()`  , what is the value for these extents?

**Comment by Jenselme** [comment]
> Since an extent is defined by [minx, miny, maxx, maxy] , your extent is not valid,

I agree. However, when I imported a KML in our geoportal (which is based on mf-geoadmin3), the intersection of `gaGlobalOptions.defaultExtent` and `source.getExtent()` gave me a invalid extend like the one I gave previously (I can give you the real values if you want). And on the dev version, ol tried to use it anyway and centered the map outside of the portal. Hence my correction.

I think that mf-geoadmin3 may be concerned too. That's why I signaled it here and proposed a correction.

**Comment by oterral** [comment]
I agree if the result of intersection is false it's a bug. Can you give the 2 extents please?

**Comment by Jenselme** [comment]
Here are the extents (EPSG:21781):

- Portal: 550000.0, 210000.0, 620000.0, 245000.0
- KML: [ 485791.5002320678, 107229.47002169346, 512656.946953667, 142289.5628862556 ] (from http://opendata.utou.ch/urbanproto/geneva/geo/kml/Routes.kml)
- intersect: [ 550000, 210000, 512656.946953667, 142289.5628862556 ]

OpenLayers centers the map at 531328.4734768334, 176144.78144312778 on production. Now that I am thinking about it, the problem may come from `gaMapUtils.intersectWithDefaultExtent` which should always return correct extents.

**Comment by oterral** [comment]
There is no intersection so `intersectWithDefaultExtent` should return undefined.

**Comment by Jenselme** [comment]
Indeed. Do you want me to open a PR for that?

**Comment by oterral** [comment]
Sure :)
