### ISSUE TITLE
Print A3: Coordinate labels

### ISSUE THREAD

**Issue by gjn** [geoadmin/mf-geoadmin3#2744]
From feedback:

 Koordinaten werden nur in X-Richtung beschriftet, im A3-Querformat wird überhaupt kein Netz generiert. Danke.. 
Permalink: https://map.geo.admin.ch/?topic=ech&lang=de&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bafu.wrz-wildruhezonen_portal,ch.swisstopo.swisstlm3d-wanderwege,ch.swisstopo.swissimage-product&layers_visibility=false,false,false,false,true&layers_timestamp=18641231,,,,&catalogNodes=457,458,485&X=203460.00&Y=701943.00&zoom=10

**Comment by davidoesch** [comment]
Known issue @afoletti and @mariokeusen are working on it

**Comment by procrastinatio** [comment]
See PR https://github.com/geoadmin/wms-bgdi/pull/13

@AFoletti @alcapat @daguer @ltclm Die someone deployed the WMS BGDI since the merge ?

**Comment by mariokeusen** [comment]
Steps to improve this situation (according to discussion with oed, foa and main customer bazl):
1. Integrate all wms-grid layers as data layers by data integrations: [1, 2, 3,]. This way the has the choice, which grid(s) he wants to have displayed on the map. And when this is done:
2. Keep only the org.epsg.grid_21781 grid (old swiss) on the grid "checkbox" of the print tool

[1] https://redmine.prod.bgdi.ch/issues/4268 
[2] https://redmine.prod.bgdi.ch/issues/4269
[3] https://redmine.prod.bgdi.ch/issues/4740

**Comment by cedricmoullet** [comment]
@AFoletti status update ?

**Comment by procrastinatio** [comment]
See PR https://github.com/geoadmin/wms-bgdi/pull/14.

Looks fine to me.

**Comment by AFoletti** [comment]
yes, WMS-side it's ok
