### ISSUE TITLE
Footer: Commune/Canton info

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#2746]
For Desktop only
Add Commune and Canton for mousposition, based on UTFGrid or similar service
![unbenannt](https://cloud.githubusercontent.com/assets/4577727/10348319/adee7caa-6d38-11e5-8417-0baea8852a12.png)

**Comment by gjn** [comment]
Yes, it's what we discussed with georanking. We need the service (first working package) for this.
