### ISSUE TITLE
Toggle for advanced settings in layer selector: show title of layer edited

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#2748]
it is more clear which layer is changed/edited (eg set transparency
proposal
- open on toggle on setting below the layer name as in As for exmaple in http://map.geo.fr.ch/?dataTheme=Localisation&theme=CARTES_COULEUR&lang=de

@all other proposals?

**Comment by gjn** [comment]
+1 from me.

**Comment by cedricmoullet** [comment]
+1

**Comment by oterral** [comment]
Shouldn't be hard to do.

**Comment by mariavkourouni** [comment]
I just saw it! yes, I will do it!

**Comment by Jenselme** [comment]
+1

**Comment by tigerfoot** [comment]
+1

**Comment by mariavkourouni** [comment]
https://github.com/geoadmin/mf-geoadmin3/pull/2786
