### ISSUE TITLE
aggregated layer: order not taken into account

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#2758]
https://mf-geoadmin3.dev.bgdi.ch/?bgLayer=ch.swisstopo.pixelkarte-farbe&dev3d=true&lang=en&topic=ech&layers=ch.swisstopo.swissimage-product,ch.bfs.gebaeude_wohnungs_register,ch.bafu.wrz-wildruhezonen_portal,ch.swisstopo.swisstlm3d-wanderwege&lon=7.67856&lat=46.50017&elevation=2640&heading=359.922&pitch=-88.441

expected result:

Address points are on swissimage

**Comment by oterral** [comment]
Simlilar to https://github.com/geoadmin/mf-geoadmin3/issues/2712 , I guess

**Comment by davidoesch** [comment]
duplicate of  #2712 ,
