### ISSUE TITLE
pegman improvements

### ISSUE THREAD

**Issue by fredj** [geoadmin/mf-geoadmin3#2762]
- [ ] buildings collision on
- [x] mouse over: make it the same mouse icon as when on rotate and shift
- [x] beautify pegman white https://fontawesome.com/icons/street-view?style=solid (otherwise paulo)
- [x] make pegman disappear when active
- [ ] NTH make pegman animated when mousover to jump on to the map (as in gmaps)
- [x] pegman amousover text: "[EN] Explore in FPV"
- [x] in pegman mode: full screen mode
- [x] add control description: all available features (press h to open in new window)
- [x] deactivate pegman on mobile

**Comment by davidoesch** [comment]
low prio
- [ ] mouse over: make it the same mouse icon as when on rotate and shift
- [ ] put the text below pegman 
- [ ] make pegman red when active
- [ ] mosue movement to sensible at the moment

**Comment by davidoesch** [comment]
integrate as well for go live the flight sim

**Comment by davidoesch** [comment]
ping @oterral ETA?

**Comment by oterral** [comment]
1 day

**Comment by davidoesch** [comment]
done
