### ISSUE TITLE
Search weird results 

### ISSUE THREAD

**Issue by oterral** [geoadmin/mf-geoadmin3#2765]
Type `velo` in the search then you obtain weird results in list of layers like `Peste de l'ecrevisse`, `Sites 200 watts`,  `Carte Sigfried`

**Comment by cedricmoullet** [comment]
@davidoesch ?

**Comment by davidoesch** [comment]
only in french 

It is in the word "développement " in french

-> for layer search remove fuzzy search or only show exact matches

**Comment by gjn** [comment]
There's no fuzzy search for layers. only exact matches; but part words are supported, and I think it's a good idea. But it could be changed if desired.

**Comment by davidoesch** [comment]
Agree on part words-... "velo" is just unhapy example...

Question is: how to ensure the ranking once with have the velolayer?

eg for "wanderwege" in DE ranking works very good

**Comment by gjn** [comment]
Full word matches weight more than part word matches. Beginning/end of word matches weight more than in-word matches. So I think this should be good.

**Comment by davidoesch** [comment]
ok

**Comment by oterral** [comment]
word in the title of the layer should weight more than others.
