### ISSUE TITLE
Print asks for permission (403)

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#2772]
Printing from "outside Bund" : a 403 is returned

Although I can not reproduce it, we had several customers who were able to do so (see eg helpdesk Customer feedback ID : 2015101913282565) and cleaning achace or restarting computer did not help

Error message after hitting the print button

"Die Website hat die Anzeige dieser Webseite abgelehnt.
HTTP 403
Wahrscheinlichste Ursachen:
•Diese Website erfordert, dass Sie sich anmelden.
Mögliche Vorgehensweise:
Wechseln Sie zur vorherigen Seite.
Weitere Informationen
Dieser Fehler (HTTP 403 Verboten) bedeutet, dass Internet Explorer eine Verbindung mit der Website herstellen konnte. Jedoch verfügen Sie nicht über die Berechtigung, um diese Webseite anzeigen zu können.
Weitere Informationen über HTTP-Fehler erhalten Sie in der Hilfe.

Permalink: https://map.geo.admin.ch/?topic=ech&lang=de&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bafu.wrz-wildruhezonen_portal,ch.swisstopo.swisstlm3d-wanderwege&layers_visibility=false,false,false,false&layers_timestamp=18641231,,,&X=221169.00&Y=614549.00&zoom=9. 

User-Agent: Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; WOW64; Trident/5.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; InfoPath.3; .NET4.0C; .NET4.0E)

"

->assumption:  this is the cas esince the varnish / s3 adaption ?

**Comment by gjn** [comment]
Looks like IE9. Might be security settings.

**Comment by davidoesch** [comment]
... We did once implement  a solution for IE for enabling the pdf download- a side effect?

**Comment by gjn** [comment]
Could very well be. We recently switched our print back-ends, thus changed something in varnish configuration. Might be that this broke IE9 workaround.

I'll have a look Thursday.

**Comment by gjn** [comment]
We did a change in varnish by also requiring referer for print downloads (before, referer was only needed to create the print).

@danduk82 Could you please revert this change as it break IE9 printing. Instead of /print/* i [1], we should use "/print/*.json*"

I can test it on dev/int before going to prod. Let med know.

**Comment by danduk82** [comment]
@gjn : I do it ASAP, I'm having a couple of issues right now because of the puppet 4 migration (which I was informed about only this morning by the way...).

**Comment by cedricmoullet** [comment]
@danduk82 any status update ?

**Comment by danduk82** [comment]
I can push a "quick fix in production" in 15 min, or make it clean in a couple of hours. What do you prefer?

**Comment by danduk82** [comment]
@gjn : can you test the new config on the infra ELB? Its DNS: vpc-lb-infra-923749892.eu-west-1.elb.amazonaws.com

**Comment by gjn** [comment]
@danduk82 I'll do it today. Can you provide a git diff?

**Comment by gjn** [comment]
@danduk82 There's no restriction at all. paths ending with `print/info.json` and `print/create.json` should be restricted. All others open.

**Comment by danduk82** [comment]
@gjn of course there is:
if req.url ~ "^/1.0.0/WMTSCapabilities.xml" || req.url ~ "^/1.0.0/legend/" -> no restrictions
else -> referer check.

**Comment by gjn** [comment]
I strictly tested print.

I assume your changes don't affect other regions. Full fletched tests needed?

**Comment by gjn** [comment]
all good

**Comment by gjn** [comment]
Let me know when it's ready to be tested on dev/int.

**Comment by gjn** [comment]
@danduk82 status?

**Comment by danduk82** [comment]
I am still waiting for C2C to solve the puppet-related bug... I cannot deploy the branch until it is fixed.

**Comment by danduk82** [comment]
and I do not want to push it on stable without proper testing. (of course)

**Comment by gjn** [comment]
Ok. let me know when it's done.

**Comment by danduk82** [comment]
It is now applied on DEV and INT. The ACLs seem correct, but I get nothing with a curl on <dev>/print/info.json. But I get a json back when I test it on INT... Can you test it too?

**Comment by procrastinatio** [comment]
I did reinstall the print-war. All fine now.

**Comment by gjn** [comment]
@danduk82 For prod addresses, I think everything is good.

But for the mf-chsdi3.int.bgdi.ch adress on int, I'm not sure. Jenkins on int (using mf-chsdi3.int.bgdi.ch address without any DNS spoofing) [fails](https://jenkins.ci.bgdi.ch/job/DEPLOY_chsdi_int/18/console) with the GetCapabilities check (it's not protected there). Any idea why?

**Comment by danduk82** [comment]
OK, I push it in a moment.

**Comment by danduk82** [comment]
it is applied on prod. I have to check for INT

**Comment by danduk82** [comment]
Actually, i was told to free WMTSCapabilites/ and legeng/, so this behavior is normal. Should I restrict them instead?

**Comment by gjn** [comment]
Ok for me. We just need to adapt the tests then.

**Comment by gjn** [comment]
@danduk82 Prod tests are failing now too.

We will let varnish configuration as it is (open up WMTSCapabilities and Legend) and we adapt the tests. I'll prepare a PR for this in chsdi. So nothing to be done on your side.

**Comment by danduk82** [comment]
OK
