### ISSUE TITLE
Support for non-Swiss projected WMS sources

### ISSUE THREAD

**Issue by gjn** [geoadmin/mf-geoadmin3#2773]
OpenLayers has added support for on-the-fly image reprojection [1]. We could use this to support wms sources which don't support Swiss projection systems (like IGN, etc).

[1] https://github.com/openlayers/ol3/pull/4122

**Comment by davidoesch** [comment]
referenced it in https://github.com/geoadmin/mf-geoadmin3/issues/2414

@cedricmoullet tackle now the Import tool as in 2414 would make sense

**Comment by oterral** [comment]
In this PR there is the update of ol for the raster reprojection stuff https://github.com/geoadmin/mf-geoadmin3/pull/2787

**Comment by gberaudo** [comment]
It is a feature I have on my radar for ol3-cesium.

**Comment by davidoesch** [comment]
Omg - if the openstreetmap community starts to display their data via our wms import in 3D .... ;-)

**Comment by davidoesch** [comment]
@mariavkourouni : status here?

**Comment by mariavkourouni** [comment]
@davidoesch the current status is https://github.com/geoadmin/mf-geoadmin3/pull/2917
