### ISSUE TITLE
Reload of page does not work

### ISSUE THREAD

**Issue by gjn** [geoadmin/mf-geoadmin3#2782]
This can only be reproduced in FF41 on Linux.

When loading a certain link for the first time, everything loads as expected. When re-loading the page using F5, there are not tiles loaded and map stays completely emtpy.

https://map.geo.admin.ch/?lang=en&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bafu.wrz-wildruhezonen_portal,ch.swisstopo.swisstlm3d-wanderwege&layers_visibility=false,false,false,false&layers_timestamp=18641231,,,&X=211000.00&Y=691600.00&zoom=3. 
 

Original message:
Guten Tag

Danke für Ihre Antwort.

Das Problem scheint mit dem Aktualisierungsproblem zusammenzuhängen. Es tritt erst nach einer Aktualisierung auf.

1) Seite im Browser aufgerufen. https://map.geo.admin.ch/
Karte wird angezeigt.

2) Aktualisieren der Seite.
Karte wird nicht mehr angezeigt.

3) Erneutes aktualisieren.
Karte wird wieder angezeigt.

4) Zoomen. Tiles werden teilweise angezeigt.

Firefox 41.0.1
Debian 8.0

Im Chromium tritt das Problem hier auch nicht auf.

**Comment by fredj** [comment]
Same issue when clicking on the "reload page" button (right of the address bar)

**Comment by fredj** [comment]
@gjn, @oterral I think I've found the issue: it's related to varnish

**Comment by fredj** [comment]
See RT ticket 194154

**Comment by gjn** [comment]
@fredj Great find!

**Comment by fredj** [comment]
fixed
