### ISSUE TITLE
Layer group load all the layers on each zoom level

### ISSUE THREAD

**Issue by oterral** [geoadmin/mf-geoadmin3#2785]
Example with `ch.bfs.gebaeude_wohnungs_register` which contains  wms layer and a wmts.  

I think specifiyng `minimumTerrainLevel`and `maximumTerrainLevel` to the [imageryLayer](https://cesiumjs.org/Cesium/Build/Documentation/ImageryLayer.html) in the [gaSynchronizer](https://github.com/geoadmin/mf-geoadmin3/blob/master/ol3-cesium-plugin/garastersynchronizer.js#L51) should fix the problem.

**Comment by cedricmoullet** [comment]
Could you prepare a demo ?

**Comment by gjn** [comment]
[Just add wohnungs register layer](https://mf-geoadmin3.dev.bgdi.ch/?dev3d=true&lang=de&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bafu.wrz-wildruhezonen_portal,ch.swisstopo.swisstlm3d-wanderwege&layers_visibility=false,true,false,false&layers_timestamp=18641231,,,&lon=8.22546&lat=42.48845&elevation=605346&heading=360.000&pitch=-44.353)
