### ISSUE TITLE
Print: on scale change zoom to corresponding extent

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#2791]
Zoom to ca 1:25k 
go to print
change scale to 1:500K

-> print extent is out of window

expected result

If print scale is changed change as well the map extent in in viewer

**Comment by davidoesch** [comment]
marc - since you are working on print, this might be doable in the next fix as well

**Comment by loicgasser** [comment]
zoom out automatically? That's a bit harsh, don't you have a better idea?

**Comment by davidoesch** [comment]
Nope... I agree it is harsh. As it is currently.

**Comment by pakb** [comment]
Should we add this scale's "min zoom level" to the informations the service-print is returning? That could also be hardcoded into PrintDirective.js as this is only relevant here (no?)

**Comment by davidoesch** [comment]
hmm IMHO this enhancement req is 2 yrs old. mf print 3 will maybe give some new opportunities. lets close it ot a non fix.
