### ISSUE TITLE
WMS imported: cannot be shared

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#2794]
This https://s.geo.admin.ch/67cf903cc9

should contain this http://owsproxy.lgl-bw.de/owsproxy/ows/WMS_Maps4BW?  WMS

but in FF CHrome and IE it does not work when shared

**Comment by oterral** [comment]
It's a  WMS 1.1.1 , It's not supporeted from the permalink because we don't load the GetCapabilities in this case.

**Comment by davidoesch** [comment]
well this is then really confusing for the user: since not even an error is reported. 

-> possible to support 1.1.1 as well? or can we onyl support one (1) WMS version clientside?

**Comment by oterral** [comment]
The first error is on their  side because in the import WMS tool, we try to load the GetCap 1.3.0 and we receive the 1.1.1.

**Comment by oterral** [comment]
We could put the version of the WMS in the permalink too.

**Comment by davidoesch** [comment]
Asked the owners in DE for a correction

**Comment by cedricmoullet** [comment]
Not a bug
