### ISSUE TITLE
[Feedback-Tool] - Implement delete options

### ISSUE THREAD

**Issue by p1d1d1** [geoadmin/mf-geoadmin3#2799]
It should be possible to delete features.

**Comment by davidoesch** [comment]
duplicate https://github.com/geoadmin/mf-geoadmin3/issues/2467

please coordinate with me the priorities. if we do changes to draw functions then we do it globally

**Comment by p1d1d1** [comment]
@davidoesch sorry. In fact I had some doubts whom assigning the ticket to.
Will address future tickets to you.
By the way..... deleting is not possible in Feedback Tool

**Comment by oterral** [comment]
Just select the feature and press `Delete` key .

**Comment by p1d1d1** [comment]
Ok didn't know it. 
Thanks
