### ISSUE TITLE
[infobox & tooltip window]: Bundesamt für Kultur not translated in EN

### ISSUE THREAD

**Issue by mariokeusen** [geoadmin/mf-geoadmin3#2802]
UC: open app, switch lang to EN, load a dataset of Bundesamt für Kultur BAK, open infobox and tooltip window
Result: Data owner is not translated in EN
Expected: Data owner is translated in EN like all other Federal Offices

Workaround: use following translation: Federal Office of Culture FOC
![bak_en](https://cloud.githubusercontent.com/assets/4577749/10785498/d8414384-7d64-11e5-8fd7-af5043839a7c.PNG)

**Comment by AFoletti** [comment]
Fixed in BOD. Will be online next deploy

**Comment by mariokeusen** [comment]
Merci
