### ISSUE TITLE
Print test with all kind of layers

### ISSUE THREAD

**Issue by gjn** [geoadmin/mf-geoadmin3#2808]
We need a print test in saucelab that tests a map containing the following type of layers:

- wmts
- wms single tile
- wms tiled
- geojson
- external wms
- external kml

Test if print is successfull.

**Comment by gjn** [comment]
See also https://github.com/geoadmin/mf-geoadmin3/pull/2807

**Comment by oterral** [comment]
and KML from public.geo.admin.ch

**Comment by alcapat** [comment]
Done in the Saucelbas PR https://github.com/geoadmin/mf-geoadmin3/pull/2906
commit : aabbb4f
Not ready to merge because of IE test not adapted yet.

**Comment by gjn** [comment]
Nice!

An alternative would be to put all layers into one view and test this. Might be faster than each individual test (How long does the current test take in one browser?). Downside would be that it's not clear which layer caused the failure (in case of failure)....

**Comment by alcapat** [comment]
Yes good solution, but if the test failed, you have no idea of which layer type is involved. It is really important to have this information ?
The current test take almost 1'30 / 1'50 by browser

**Comment by gjn** [comment]
If it fails, we can always analyse by hand which one caused the failure. Not ideal, but execution time does become more and more important.

**Comment by alcapat** [comment]
Modification is done : https://github.com/geoadmin/mf-geoadmin3/commit/0d7c0a39880e8ed7b0f5968a14de4d0de3debd6b 
Need to have a new available account to test.

**Comment by alcapat** [comment]
Print tests (with all layer type in only one link) are done in this PR : https://github.com/geoadmin/mf-geoadmin3/pull/3144 (already merged)
