### ISSUE TITLE
3d mobile: remove offline button

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#2809]
when in 3d on mobile: remove offline button

**Comment by oterral** [comment]
hmmm should be the case already. Do you have a special usecase?

**Comment by davidoesch** [comment]
if I open https://mf-geoadmin3.dev.bgdi.ch/teo_fix_2674/index.html?lang=fr&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&dev3d=true&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bafu.wrz-wildruhezonen_portal,ch.swisstopo.swisstlm3d-wanderwege&layers_visibility=false,true,false,false&layers_timestamp=18641231,,,&mobile=false&X=163030.49&Y=645942.61&zoom=2 from #2813 

it is removed... seems like my cache was not deleted fully
