### ISSUE TITLE
Chrome: Draw&measure "copy link" button does not work

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#2810]
Chrome 46

https://map.geo.admin.ch/?topic=ech&lang=en&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bafu.wrz-wildruhezonen_portal,ch.swisstopo.swisstlm3d-wanderwege,&layers_visibility=false,false,false,false,true&layers_timestamp=18641231,,,,&X=199428.57&Y=667071.43&zoom=1&adminId=5W5y3gNDRaegfLhUsAEBMA

click admin "copy link"

does not work

-> either remove the button as in FF or fix it

**Comment by oterral** [comment]
It's a collateral damge of a feature without geometry.
