### ISSUE TITLE
add msgid for kml drawing

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#2811]
When current drawing is shared it appears with a title "drawing" in all lang
AFAIK, this is the KML <Document><name> tag - we discussed this as well during the dev  of drawing... with @oterral 

proposal
A) detect lang setting at the beginning of the draw session and set <Document><name> to

DE Zeichnung
FR Dessin
IT  Disegno
EN Drawing
RM Dissegn

B) otherwise set it to all lang to a unilang abbrevation like
"KML" or "public.geo.admin.ch"

my vote goes out for A)

**Comment by cedricmoullet** [comment]
A
