### ISSUE TITLE
IE 11 Perfomance 3d: setting the viewer.resolutionScale property in IE only, for example, try it with 0.5 

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#2818]
Proposal to fix IE 11

"
Are we talking unusably slow, or just noticeably slower than all other" browsers?  For example, what does this link report for FPS.

If it's the former, you may be experiencing software rendering caused by IE's aggressive and large hardware black list.  If you look in the IE dev console when running Cesium, do you see any messages about software mode or rendering?  The best solution here is to make sure your video drivers are up to date and that Windows is fully patched, even then IE 11 might refuse to use hardware accelerated graphics for your card (what graphics card is it, by the way?)

If it's the latter, than the specific performance problems you are seeing are most likely a result of IE 11 not supporting transferable typed arrays, which causes additional copy and slower performance when marshaling data to and from web workers.  Also, IE 11's JavaScript engine is just flat out slow compared to Chrome, Firefox, and Edge.

While there's no magic "make faster" setting you can enable (if there was, we would already be doing it for you) you can try and make a trade off between quality and performance by rendering at a lower resolution in IE compared to other browsers.  You do this by setting the viewer.resolutionScale property in IE only, for example, try it with 0.5 and see if it affects my first link."

see https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/cesium-dev/OTwnQkSpInw

-> can we test the impact of " setting the viewer.resolutionScale property in IE only, for example, try it with 0.5 "

**Comment by gjn** [comment]
I played around a bit with fed IE11. It seems to me that performance is generally worse by factor 2-3 for cesium demo viewer; but still slower for our application. I think it's because we load more data than the cesium demo viewer.

Each request individaully does not appear to be slower to me, but they are issued in much greater intervals. This might be triggered by slow/slower software rendering as CPU usage increases considerably if I open the app in IE11 (as compared to chrome).

@gberaudo The `resolutionScale`  property mentioned in the thread above is attached to the viewer widget of cesium and we don't have it in ol3-cesium. Is there an easy way to add it?

**Comment by gjn** [comment]
I've created an issue with our IT regarding GPU and IE11.

**Comment by gberaudo** [comment]
@gjn, it seems easy to implement it. I will have a try to it.

**Comment by gberaudo** [comment]
@gjn, I added the ability in ol3-cesium: https://github.com/openlayers/ol3-cesium/pull/281.

Now OL3-Cesium also honours device pixel ratio (like in Cesium viewer) so devices with high density will consume more resources. See https://github.com/openlayers/ol3-cesium/pull/281/files#diff-9efadb08b1671f0f03c3e32face08d92R213
If it is not what we want, we can pass `ol3d.setResolutionScale(1/(window.devicePixelRatio || 1.0))`.

**Comment by gjn** [comment]
Google maps in IE11 works very well and is comparable to chrome version (a little slower). So there _are_ ways to have 3D mapping in IE11 at good performance.

The degrading of performance has to do with our code (cesium, ol3-cesium, mf-geoadmin3) that might be in conflict with some IE11 setting.

**Comment by danduk82** [comment]
Anyway, I have tested at home, with a 8 core PC and nvidia GTX980. It's great with firefox, quite slow with IE (not as slow as work). Didn't try it with Chrome.

**Comment by oterral** [comment]
For info I've tested on the win8 we have. And it's as slow in Chrome as in IE 11.

**Comment by gjn** [comment]
According to http://www.doesmybrowsersupportwebgl.com/, our installed IE11 does support webgl, but quite an outdated version with little extensions. Compare the results to chrome 45.

IE11:
![image](https://cloud.githubusercontent.com/assets/2572317/10996752/2721d700-8488-11e5-9fca-f56ee351d74b.png)

Chrome 45:
![image](https://cloud.githubusercontent.com/assets/2572317/10996757/3326ba3e-8488-11e5-8a4e-0f04de540971.png)

**Comment by gjn** [comment]
[Pure cesium viewer](https://cesiumjs.org/Cesium/Build/Apps/CesiumViewer/index.html?stats=true&view=-86.41356823617337%2C40.968330530058154%2C39914.93747130931%2C3.7105232380439385%2C-52.58141348032261%2C359.26708014877175) gives also differences between chrome and IE11, but they are much close than our application:

In chrome, page is fully loaded in < 15s. ~20s in IE11. Also, the fps shown is quite similar for both browsers. But the views in these are all flat (terrain is flat). I will test other pure cesium views.

**Comment by gberaudo** [comment]
You can add terrain by clicking on the second button from the top right.

**Comment by gjn** [comment]
Thanks @gberaudo , I will try.

Testing https://cesiumjs.org/Cesium/Apps/Sandcastle/gallery/Terrain.html now and IE11 is really slow compared to chrome...similar as our application.

**Comment by gjn** [comment]
You add the terrain, performance drops considerably in IE11. FPS shown is quite good though.

I suspect https and many requests might lead to slowdown in IE11.

**Comment by davidoesch** [comment]
ok: lets solve this with a different approach

if IE11 is detected, the show a pop up message 

"EN : You are using InternetExplorer 11 : 3D rendering will be slow. Please use latest Version of Microsoft EDGE, Firefox or Chrome to experience maximum performance"

DE: Sie verwenden InternetExplorer 11: Die 3D Darstellung wird nicht performant sein. Bitte nutzen Sie die neueste Version von Microsoft EDGE, Firefox or Chrome um beste Ergebnisse zu erhalten"

**Comment by gjn** [comment]
(maybe auto-resize window on IE11 start)

**Comment by gjn** [comment]
Fix will be merged soon. I'll downgrade to 2nd prio because of temporary approach.
