### ISSUE TITLE
Measure : 3 circles don't display

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#2820]
call up this URL https://s.geo.admin.ch/67fa47f06d

3 circles are displayed:
http://www.awesomescreenshot.com/image/720574/d4292e5e4c179fe3989c41b0f1027be7 

zoom in: :boom: only one is visible
http://www.awesomescreenshot.com/image/720580/b6a22f736abcd47b9d33f29b85d35cab

expected result

If I draw three circles they are always visible

**Comment by oterral** [comment]
Not trivial. The circle disappears because the corresponding line (dotted) is outside the current extent. 

We need to change the behavior how we create the circle.

**Comment by davidoesch** [comment]
Raised the prio since several other reported the issue

**Comment by davidoesch** [comment]
fix is not good enough
