### ISSUE TITLE
Weird zeitreihen

### ISSUE THREAD

**Issue by oterral** [geoadmin/mf-geoadmin3#2821]
Open https://mf-geoadmin3.int.bgdi.ch/?lang=fr&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&X=189085.79&Y=654862.85&zoom=6&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bafu.wrz-wildruhezonen_portal,ch.swisstopo.swisstlm3d-wanderwege&layers_visibility=true,false,false,false&layers_timestamp=18821231,,,&time=1882

Zoom in or out 

A better map is displayed on zoom 5 and 7 but disappears in zoom 6 , is it normal?

**Comment by ltclm** [comment]
thats not a bug, thats a feature of this famous "layer".
sad but true, zoomlevel 20 only shows lk100 or tk100.
