### ISSUE TITLE
3D mobile: tilt rotate do not reflect current state

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#2822]
Open current dev icon do not change if you move around to rotate .
If geolocation is active u have in addition two north indicator: keep only 3D in 3d
![image](https://cloud.githubusercontent.com/assets/4577727/10941378/709f6704-830b-11e5-8c6e-a831f59e0739.png)

**Comment by fredj** [comment]
Fixed with #2814
