### ISSUE TITLE
tooltip: show "no data available"

### ISSUE THREAD

**Issue by ltclm** [geoadmin/mf-geoadmin3#2823]
When you click into the map and there is no feature, the client could show a message "no data available". 
We already have some layers (luftfahrthindernis, agnes) point features with huge symbols or symbols with an offset where this could help. There will soon be more layers like that p.e. ch.astra.wanderland, the tooltip for this layer will only work on the astra data, the swisstopo.tlm trails are also visible but not clickable.
as discussed with @gjn @davidoesch 
see map.schweizmobil
![image](https://cloud.githubusercontent.com/assets/5286659/10942424/618a7fba-8310-11e5-8c53-eacbea762837.png)

**Comment by fredj** [comment]
Note: and the tooltip automatically disappear after  3 seconds

**Comment by cedricmoullet** [comment]
this needs to be discussed. Not 100% convinced

**Comment by davidoesch** [comment]
organize meeting pls

**Comment by AFoletti** [comment]
I think it's a very good idea.
It will help those people puzzled by the "hand" cursor doing something on some layers and nothing on others.
Now the cursor morphs into an hand if there is a feature displayed, regardless of tooltip/no tooltip. Sometimes you click and a tooltip appears, sometimes don't. Hmmmm??

**Comment by gjn** [comment]
As a reference, here's the PR that got the feature into `master`. Lots of discussion already. https://github.com/geoadmin/mf-geoadmin3/pull/2172

**Comment by ltclm** [comment]
do we have to wait for this festure to publish chmobil layers?

**Comment by davidoesch** [comment]
@ltclm nope - go out like this. we do this fix in a second step cc @mariokeusen
