### ISSUE TITLE
Strange label in wohnung register layer

### ISSUE THREAD

**Issue by oterral** [geoadmin/mf-geoadmin3#2824]
https://map.geo.admin.ch/?lang=fr&topic=ech&bgLayer=voidLayer&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bafu.wrz-wildruhezonen_portal,ch.swisstopo.swisstlm3d-wanderwege,ch.bazl.sachplan-infrastruktur-luftfahrt_kraft&layers_visibility=false,true,false,false,false&layers_timestamp=18641231,,,,&X=195397.67&Y=602565.40&zoom=12

**Comment by AFoletti** [comment]
solved. Thaks @ltclm !
