### ISSUE TITLE
Saved KML not displayed 

### ISSUE THREAD

**Issue by oterral** [geoadmin/mf-geoadmin3#2825]
Caused by OL update : 

Guten Morgen Herr Keusen

Gestern habe ich wieder vermietete Landflächen um den Sihlsee herum auf ihrer Webseite www.map.geo.admin.ch/ eingezeichnet.
Da aber die Internetanbindung im Kraftwerk Etzelwerk nicht die Beste ist, ist die Seite abgestürzt.
Als ich aber zuhause weiter arbeiten wollte, sind alle gespeicherten Links nicht mehr gegangen und auch die Kml-Datei konnte ich nicht einlesen.
Da gegen den Schluss hin das Arbeiten mit den vielen Eintragungen immer langsamer wurde, frage ich mich, haben sie eine Höchstgrenze an Daten die man einzeichnen darf.
Oder haben wir sonst eine Regel verletzt, die sie aufgestellt haben und sie uns somit die Daten gelöscht haben.

Oder besteht momentan einfach eine Störung.

Ich habe ihnen die KML-Datei angehängt und die beiden Links, zuerst der zum Editieren und dann den zum Teilen.

https://map.geo.admin.ch/?X=220937.07&Y=701303.09&zoom=10&lang=de&topic=inspire&bgLayer=ch.swisstopo.swissimage&layers=ch.swisstopo.zeitreihen,ch.bafu.wrz-wildruhezonen_portal,ch.swisstopo.swisstlm3d-wanderwege,ch.swisstopo-vd.geometa-grundbuch,ch.swisstopo-vd.geometa-nfgeom,ch.bfs.gebaeude_wohnungs_register,ch.kantone.cadastralwebmap-farbe,&layers_visibility=false,false,false,true,true,true,true,true&layers_timestamp=18641231,,,,,,,&catalogNodes=1,44,47&layers_opacity=1,1,1,0.75,0.75,1,1,1&adminId=5bSNSqfRQ1GAdKgTJCEk6Q

**Comment by gjn** [comment]
Is this true for all drawn kml files? Or just specific ones?

Kml drawing should be part of the squash tests. Drawing, opening linke, opening admin link and editing.

**Comment by oterral** [comment]
Fixed emrgency deploy yesterday

**Comment by oterral** [comment]
Tests added by @alcapat

**Comment by gjn** [comment]
Thanks alot @oterral and @alcapat for reacting fast.
