### ISSUE TITLE
[configuration of topic=wildruhezonen] change default backgroundlayer to color pixelmap

### ISSUE THREAD

**Issue by mariokeusen** [geoadmin/mf-geoadmin3#2830]
UC: open app, switch to topic=wildruhezonen, look at the bg-layer
Result: grey map is visible
Change (requested by customer): color map is visible
Workaround: please change topic configuration accordingly

**Comment by alcapat** [comment]
Bod (re3.topics) updated. 
Test link : https://mf-geoadmin3.dev.bgdi.ch/
