### ISSUE TITLE
Permalink issue

### ISSUE THREAD

**Issue by cedricmoullet** [geoadmin/mf-geoadmin3#2832]
The link: https://mf-geoadmin3.dev.bgdi.ch/ltmoc/?dev3d=true&lang=fr&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bafu.wrz-wildruhezonen_portal,ch.swisstopo.swisstlm3d-wanderwege,ch.swisstopo.swissimage-product&layers_visibility=false,false,false,false,true&layers_timestamp=18641231,,,,&lon=6.93164&lat=46.81563&elevation=578&heading=359.997&pitch=-24.987

is transformed in (elevation changed):

https://mf-geoadmin3.dev.bgdi.ch/ltmoc/?dev3d=true&lang=fr&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bafu.wrz-wildruhezonen_portal,ch.swisstopo.swisstlm3d-wanderwege,ch.swisstopo.swissimage-product&layers_visibility=false,false,false,false,true&layers_timestamp=18641231,,,,&lon=6.93164&lat=46.81563&elevation=1579&heading=359.997&pitch=-24.987

Elevation should be the same.

**Comment by gjn** [comment]
@fredj To be discussed when you are here.

**Comment by fredj** [comment]
Some observations:
 - The issue only occurs when the terrain is active.
 - The issue only occurs when elevation is bellow ~1600m

**Comment by fredj** [comment]
This issue should be fixed once https://github.com/camptocamp/cesium/pull/6 is used (thanks Guillaume for the hint !)

**Comment by gjn** [comment]
This is in master, but the elevation in the PL does still change. @fredj ?

**Comment by fredj** [comment]
The problem occurs because cesium gets the elevation from terrain tiles at level < 8.
Adding `?&terrainLevels=8,9,10,11,...` fixes the issue but I'm not sure it's the way to go. 
@oterral , @gberaudo ?

**Comment by oterral** [comment]
If it works starting with level 8. We can set the default value for terrainLevels to 8,9,10...17
