### ISSUE TITLE
Mix of white and black bg

### ISSUE THREAD

**Issue by cedricmoullet** [geoadmin/mf-geoadmin3#2833]
![image](https://cloud.githubusercontent.com/assets/319676/10989215/bf081780-8444-11e5-9846-81352f409886.png)
What could we do in order to improve the "no data" areas ? Currently, the mix of white and black is really not nice. 
Any idea @oterral @fredj @gberaudo @davidoesch @gjn @loicgasser @procrastinatio ?

**Comment by davidoesch** [comment]
A) use a freely available coarse res dataset source as in Cesium

aerial imagery by Bing, on a opacity by 50% so it is clear it is not our
data , but I hate to have bing layer copyright at the bottom.

B) Use DHME25 or GTOPO30/ASTERDEM to provide a coarse resolution DEM
outside switzerland and display it as a grey , very light hillshade, 50%

**Comment by gjn** [comment]
I've tried to solve this yesterday, no luck. I played with https://github.com/geoadmin/mf-geoadmin3/blob/master/src/js/GaCesium.js#L67 and other settings in cesium, but could not find a way to change this.

I assume the black regions is where we don't have terrain files loaded (because of definition in layers.json, which was adapted because of performance/data transfer to exclude levels 0-7). The white regions is where we have terrain data but don't have imagery data.

**Comment by gberaudo** [comment]
I also think there is a problem with terrain.

https://mf-geoadmin3.dev.bgdi.ch/gberaudo_autorenderloop/?dev3d=true&topic=ech&lang=fr&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bafu.wrz-wildruhezonen_portal,ch.swisstopo.swisstlm3d-wanderwege&layers_visibility=false,false,false,false&layers_timestamp=18641231,,,&lon=7.07823&lat=45.99270&elevation=148527&heading=359.762&pitch=-89.286

When enabling terrain wireframe, I can see some triangles look strange
(very longs) and some tiles are not full.

**Comment by gjn** [comment]
All white on all zoom levels. This is a must for Thursday.

**Comment by oterral** [comment]
To fix this I've proposed a PR in Cesium patches https://github.com/camptocamp/cesium/pull/6 .

This PR will display Terrain and imagery layers only in the extent of switzerland and from llod 8.

Outside the switzerland it's all transparent so we will can play with [Scene.backgroundColor](https://cesiumjs.org/Cesium/Build/Documentation/Scene.html#backgroundColor)

**Comment by gjn** [comment]
Do you have a demo for that one?

**Comment by oterral** [comment]
Not now but soon. I've tested on the mac.

**Comment by oterral** [comment]
@gjn here https://mf-geoadmin3.dev.bgdi.ch/teo_cesium2/?lang=fr&topic=ech&terrainLevels=8,11,13,15,17bgLayer&dev3d=true&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bafu.wrz-wildruhezonen_portal,ch.swisstopo.swisstlm3d-wanderwege&layers_visibility=false,false,false,false&layers_timestamp=18641231,,,&lon=8.02682&lat=46.50815&elevation=480724&heading=345.566&pitch=-81.896&bgLayer=ch.swisstopo.pixelkarte-farbe

**Comment by gjn** [comment]
fantastic. I could live with that for next week.

**Comment by davidoesch** [comment]
+1 , perfetto
