### ISSUE TITLE
3D BG data with lighting

### ISSUE THREAD

**Issue by cedricmoullet** [geoadmin/mf-geoadmin3#2835]
Process map bg with relief information

**Comment by ltclm** [comment]
Tile generation is ongoing and will take around 3 days for swisstlm3d-karte-farbe and 3 days for swisstlm3d-karte-grau.

```
https://wmts.geo.admin.ch/1.0.0/ch.swisstopo.swisstlm3d-karte-farbe.3d/default/20150501_50/4326/{TileMatrix}/{TileRow}/{TileCol}.jpeg
https://wmts.geo.admin.ch/1.0.0/ch.swisstopo.swisstlm3d-karte-grau.3d/default/20150501_50/4326/{TileMatrix}/{TileRow}/{TileCol}.jpeg
```

**Comment by gjn** [comment]
I don't understand the OP. Relief will be inside swisstlm3d?

**Comment by ltclm** [comment]
yes

**Comment by ltclm** [comment]
**ch.swisstopo.swisstlm3d-karte-farbe.3d** tiles with relief are ready:
```
https://wmts.geo.admin.ch/1.0.0/ch.swisstopo.swisstlm3d-karte-farbe.3d/default/20150501_50/4326/{TileMatrix}/{TileRow}/{TileCol}.jpeg
```

**Comment by gjn** [comment]
Demo upcoming.

**Comment by gjn** [comment]
[Visible difference](https://mf-geoadmin3.dev.bgdi.ch/gjn_relief/?dev3d=true&topic=ech&lang=de&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bafu.wrz-wildruhezonen_portal,ch.swisstopo.swisstlm3d-wanderwege&layers_visibility=false,false,false,false&layers_timestamp=18641231,,,&lon=7.56266&lat=46.25252&elevation=4897&heading=35.005&pitch=-18.462):

![image](https://cloud.githubusercontent.com/assets/2572317/11058116/b5f49dcc-8790-11e5-87ca-db4c67a57c2a.png)

![image](https://cloud.githubusercontent.com/assets/2572317/11058120/c1aab7d2-8790-11e5-8408-2ed03cd3fad7.png)

@davidoesch @cedricmoullet + or -?

**Comment by cedricmoullet** [comment]
+100

**Comment by davidoesch** [comment]
+100

**Comment by ltclm** [comment]
**ch.swisstopo.swisstlm3d-karte-grau.3d** tiles with relief are ready too:
```
https://wmts.geo.admin.ch/1.0.0/ch.swisstopo.swisstlm3d-karte-grau.3d/default/20150501_50/4326/{TileMatrix}/{TileRow}/{TileCol}.jpeg
```

**Comment by gjn** [comment]
This is done and in master. I'll close.
