### ISSUE TITLE
Wildlife areas don't appear in 3D

### ISSUE THREAD

**Issue by cedricmoullet** [geoadmin/mf-geoadmin3#2836]
https://mf-geoadmin3.dev.bgdi.ch/ltmoc/?dev3d=true&lang=en&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bafu.wrz-wildruhezonen_portal,ch.swisstopo.swisstlm3d-wanderwege&layers_visibility=false,false,true,false&layers_timestamp=18641231,,,&lon=7.37905&lat=45.75837&elevation=66630&heading=360.000&pitch=-40.364

**Comment by oterral** [comment]
According to MapProxy listing wildruhezone is only available in EPSG:21781 and EPSG:4258 .

**Comment by gjn** [comment]
@procrastinatio Could you have a look?

**Comment by cedricmoullet** [comment]
@procrastinatio this is a prio 1: could you have a look ?

**Comment by procrastinatio** [comment]
The timestamp do not match '20150106'  against '20151103'. As stated in the integration documentation, every time you:
- add a layer
- add/insert/remove a timestamp
- update its map/project/topics affiliation

You have to rerun `./buildout/bin/buildout -c <config> install mapproxy-config` and commit the resulting `mapproxy.yaml` 

Will merge https://github.com/geoadmin/mf-chsdi3/pull/1751 tomorrow.

**Comment by oterral** [comment]
Fixed
