### ISSUE TITLE
[topic=ech, top4-layers in selection] remove when changing to a specialized topic

### ISSUE THREAD

**Issue by mariokeusen** [geoadmin/mf-geoadmin3#2838]
Often heard user feedback since we initialized those top-4 layers in the ECH topic and IMHO this is really an issue:

UC: open map.geo.admin.ch, switch to a green specialized topic with default layers loaded (e.g. geology or aviation)
Result: the top4 layer from the "ECH" setting stay in the selection, although they have absolutely no relevance to the specialized topic
Expected: only the topic-specific default layers or no layers at all are present in the selection

How can we solve this? I think we definitely should do something here, because it also strongly bothers myself when I am working with the mapviewer

**Comment by davidoesch** [comment]
you have a point there.

the idea with inheriting the layer  on a topic switch was initially to keep the confguration ( we had a lenghty discussion on that and it was finally a GKG decision to keep the files ona topic switch to foster data aggregation) but I agree: most use cases are: you start with a topic, and you don't switch with a purpose to keep the layers


Proposal:
- on topic switch: we dont copy existing actviue and inactive layers layers 

@gjn ? your thoughts :-)

**Comment by mariokeusen** [comment]
Yes, I remember this "political" discussion with GKG and so on...
In the meantime we have a whole bunch of topics with specific default layers and regarding that: your proposal makes sense for me.

**Comment by gjn** [comment]
We need proposed layers for each topic...or say a given topic does not have those proposed layers.

It's all in data management: activatedLayers properties on [the topics service](http://api3.geo.admin.ch/rest/services). Currently, if this is empty for a given topic, we choose the ones from ech.

If you agree, we fully apply the definition as it is in the service above.

**Comment by mariokeusen** [comment]
+1 for the current topic definition
Main goal is IMHO to prevent that the ECH-proposed layers are still in the selection after switch to another topic. For all other topic default layers this is intention of the topic owners and I would not change anything on that unless discussing & agreeing with them.

**Comment by davidoesch** [comment]
+1 we will inform each topic owner when the switch from oen layer tree to
open selection will be made that we don't copy the layers on the topic
switch (planning: q1 2016, after the testphase we currently have with ech)

**Comment by davidoesch** [comment]
@cedricmoullet @gjn I got only negative feedback regarding the current situation: my proposal we remove it fro the selection

**Comment by cedricmoullet** [comment]
+1

**Comment by gjn** [comment]
So summarize.

On every topic switch:
1) Remove all layers that are not active
2) Keep active layers that are part of ech (previous behaviour)

On topic switch _to_ topic `ech`
1) Add ech proposed layers as inactive if not already present

Correct?

**Comment by davidoesch** [comment]
On topic switch to topic ech
1) Add ech proposed layers as inactive if not already present
-> nope we even get rid of the proposed layers.---Am I to radical?

**Comment by gjn** [comment]
I'm +1 for this (being radical)

But it was prio1 entity in User Value document...(I agree that it should be prio1, but I don't think it was well done)

**Comment by AFoletti** [comment]
For what is worth, here my +1 on the radical solution. The only thing I do with those proposed layers is to delete them from the list ;)

**Comment by gjn** [comment]
It's bad for us. But it was not done for us.

@davidoesch is negative feedback from power users / professional users?

**Comment by davidoesch** [comment]
Power user ---

**Comment by gjn** [comment]
As said, I'm for radical solution, but I think we should keep 'discoverability' in mind and maybe try different approach.

**Comment by mariokeusen** [comment]
+1 for "radical" and agree with @gjn at the same time

**Comment by oterral** [comment]
-1 Proposed layer are useful. I'm in favor to remove them when we change topic. As i always said NOBODY changes topic. It's sad we can't monitor the user interactions.

**Comment by davidoesch** [comment]
the users were gov employees who are sedning links from the URL: they mounr
that the URL is now very long ... this means: shortened URL are as well not
used

**Comment by gjn** [comment]
@oterral What about this solution (which is technically challenging, but might add value to the users): when loading a topic, we will add the proposed layers to the layermanager (as now) - but we don't add them in the permalink. Reasoning: the app will show the in the layermanager anyway when this topic is loaded, so no need to transfer this info in the permalink; as it's part of the application logic.

A proposed layers is added to the permalink once it's activated by the user.

Thoughts?

**Comment by oterral** [comment]
+1 I think it should be the good way

**Comment by loicgasser** [comment]
And if layers are defined in the permalink we don't add the default layers? (same behaviour as now)

**Comment by davidoesch** [comment]
see #3122  as well

**Comment by mariokeusen** [comment]
solved with https://github.com/geoadmin/mf-geoadmin3/issues/3122
