### ISSUE TITLE
KML loading and symbol rendering

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#2842]
-Symbols size is not stable to previous release
-KML do not always load

Customer feedback
•	Beim Rendering von png-Grafiken von Punktsymbolen ist die Grösse plötzlich anders. Siehe z.B.
http://www.energieschweiz.ch/de-ch/mobilitaet/fahrzeuge/fahrraeder/bikesharing.aspx
Vor Mittwoch waren die Symbole grösser. Gleiches Problem auch hier mit den OFA-Standorten:
http://www.bfe-gis.admin.ch/storymaps/EA_SGT/index.php?lang=de
•	Bei gewissen Permalinks mit kml-files drin wurde die KMLs nicht mehr geladen. Konnten wir schnell fixen indem wir neue Permalinks generiert haben aber mühsam.

might be related to https://github.com/geoadmin/mf-geoadmin3/issues/2820

**Comment by AFoletti** [comment]
Regression in OL3. Will be fixed with https://github.com/openlayers/ol3/pull/4385

**Comment by fredj** [comment]
Should be fixed by the ol3 update
