### ISSUE TITLE
3D : KML drawing line is not shown

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#2847]
there should be line in the drawing between the points
https://mf-geoadmin3.dev.bgdi.ch/?dev3d=true&topic=ech&lang=en&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bafu.wrz-wildruhezonen_portal,ch.swisstopo.swisstlm3d-wanderwege,KML%7C%7Chttps:%2F%2Fpublic.dev.bgdi.ch%2FBvcmy61fR5qX-u4QH4ZWRQ&layers_visibility=false,false,false,false,true&layers_timestamp=18641231,,,,&lon=7.74473&lat=46.67947&elevation=6104&heading=27.346&pitch=-40.033

**Comment by oterral** [comment]
Duplicate with  #2715

**Comment by davidoesch** [comment]
I reopen this: our drawing is not shown
https://map.geo.admin.ch/?topic=ech&lang=de&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=KML%7C%7Chttps:%2F%2Fpublic.geo.admin.ch%2FgfkH6qWNRmOe1XKz0SMmPg&lon=7.85123&lat=46.63744&elevation=7465&heading=0.026&pitch=-40.215

**Comment by oterral** [comment]
Only the circle is not displayed.

The circle comes from the styleFunction, could be difficult to show it in 3d.

**Comment by oterral** [comment]
Problems for this:
   - OL-Cesium doesn't display the circle -> PR ready https://github.com/openlayers/ol-cesium/pull/462
   - GroudPrimitive doesn't support Circle outline
   - GroundPrimitive doesn't support dash style

**Comment by davidoesch** [comment]
line is not shown either https://gpx2kml.com/trk/2017/06/03/cwtopguda_albeuve-moleson.kml
eg in https://s.geo.admin.ch/7399eda508

**Comment by oterral** [comment]
With:
                    <visibility>1</visibility>       

in th kml it's better.

**Comment by gjn** [comment]
We have to wait on AGI for the missing issues.

**Comment by davidoesch** [comment]
ping @gjn  IMHO to be closed
