### ISSUE TITLE
3d WMS add error can't add a feature

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#2849]
Try to add 
https://wms.geo.gl.ch/

in https://mf-geoadmin3.dev.bgdi.ch/?dev3d=true&topic=ech&lang=en&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=WMS%7C%7CBahnachsen%7C%7Chttps:%2F%2Fwms.geo.gr.ch%2Fseilbahnen%7C%7CSeilbahnen_Bahnachsen,WMS%7C%7CStationen%7C%7Chttps:%2F%2Fwms.geo.gr.ch%2Fseilbahnen%7C%7CSeilbahnen_Stationen,WMS%7C%7CAblagerungsstandorte%7C%7Chttp:%2F%2Fmapserver1.gr.ch%2Fwms%2Fbelastetestandorte%7C%7CAblagerungsstandorte,WMS%7C%7CAblagerungsstandorte%7C%7Chttp:%2F%2Fmapserver1.gr.ch%2Fwms%2Fbelastetestandorte%7C%7CAblagerungsstandorte,WMS%7C%7CVerkehr%7C%7Chttps:%2F%2Fwms.geo.gl.ch%2F%7C%7CVerkehr,WMS%7C%7CVerkehr%7C%7Chttps:%2F%2Fwms.geo.gl.ch%2F%7C%7CVerkehr,WMS%7C%7CVerkehr%7C%7Chttps:%2F%2Fwms.geo.gl.ch%2F%7C%7CVerkehr,WMS%7C%7CVerkehr%7C%7Chttps:%2F%2Fwms.geo.gl.ch%2F%7C%7CVerkehr&X=158246.84&Y=594517.14&zoom=4

Result
![unbenannt](https://cloud.githubusercontent.com/assets/4577727/11030922/68624ce0-86d1-11e5-8aa7-cb62d465225a.PNG)

**Comment by oterral** [comment]
Fixed by https://github.com/openlayers/ol3-cesium/pull/285/files

**Comment by oterral** [comment]
Fixed
