### ISSUE TITLE
3D : zeitreise close data is not shown

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#2850]
Open 
https://mf-geoadmin3.dev.bgdi.ch/?dev3d=true&topic=ech&lang=en&bgLayer=ch.swisstopo.pixelkarte-farbe&catalogNodes=457,458&layers=ch.swisstopo.zeitreihen&layers_timestamp=19231231&time=1923&X=159100.37&Y=621433.49&zoom=7

switch to 3d
 as expected it goes to the first dataset

but the close tiles are not shown,/ missing

![unbenannt](https://cloud.githubusercontent.com/assets/4577727/11031067/47298d26-86d2-11e5-8900-c5415bc0ccd7.PNG)

**Comment by fredj** [comment]
At level >= 15 the tiles are whites (eg. https://wmts14.geo.admin.ch/1.0.0/ch.swisstopo.zeitreihen/default/19231231/4326/15/33962/7912.jpeg)

**Comment by cedricmoullet** [comment]
data issue: we don't have data here.
