### ISSUE TITLE
Inline-Help for navigation

### ISSUE THREAD

**Issue by gjn** [geoadmin/mf-geoadmin3#2853]
Just like cesium viewer, we should add basic help for 3D navigation directly in the viewer. 

See http://cesiumjs.org/NewYork/?view=-74.01881302800248%2C40.69114333714821%2C753.2406554180401%2C21.27879878293835%2C-21.343905508724625%2C0.0716951918898415 and see question mark in upper right corner.

The idea is to have something similar at bottom of screen in 3D.

@pfanguin @rfrancel Do you want to try this?

**Comment by rfrancel** [comment]
Yes sure!

De : Gilbert Jeiziner [mailto:notifications@github.com]
Envoyé : mardi 10 novembre 2015 09:03
À : geoadmin/mf-geoadmin3 <mf-geoadmin3@noreply.github.com>
Cc : Francelet Rebecca swisstopo <Rebecca.Francelet@swisstopo.ch>
Objet : [mf-geoadmin3] Inline-Help for navigation (#2853)


Just like cesium viewer, we should add basic help for 3D navigation directly in the viewer.

See http://cesiumjs.org/NewYork/?view=-74.01881302800248%2C40.69114333714821%2C753.2406554180401%2C21.27879878293835%2C-21.343905508724625%2C0.0716951918898415 and see question mark in upper right corner.

The idea is to have something similar at bottom of screen in 3D.

@pfanguin<https://github.com/pfanguin> @rfrancel<https://github.com/rfrancel> Do you want to try this?

**Comment by cedricmoullet** [comment]
We should have that for the go live

**Comment by cedricmoullet** [comment]
@pfanguin ?

**Comment by pfanguin** [comment]
I am working on this. When is the go live ?

**Comment by gjn** [comment]
Go live might be next Wednesday.
