### ISSUE TITLE
3D : permalink layer is not active

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#2859]
https://mf-geoadmin3.dev.bgdi.ch/?dev3d=true&topic=ech&lang=en&bgLayer=ch.swisstopo.pixelkarte-farbe&layers_visibility=false&lon=8.04350&lat=44.93685&elevation=230713&heading=0.027&pitch=-39.960&layers_opacity=0.75&layers=ch.are.agglomerationen_isolierte_staedte

result:

3d mode but layer is not active

expected result

layer is active
(since I need this to test 400 layer if they load: I set this to prio)

**Comment by gberaudo** [comment]
@davidoesch, do you mean you want the `ch.are.agglomerationen_isolierte_staedte` to be visible?
If yes, removing `layers_visibility=false` from the URL should do this.

**Comment by davidoesch** [comment]
bugger --- sorry for this one
