### ISSUE TITLE
Icon drawn are not exported 

### ISSUE THREAD

**Issue by oterral** [geoadmin/mf-geoadmin3#2862]
Bug regresiioon in ol, see this commit https://github.com/openlayers/ol3/commit/d29f3b9068effdae158885c64ba50f5c57bbd2a9

This bug has been fixed in the release today(11.11.2015 see https://github.com/geoadmin/mf-geoadmin3/commit/4e55d58859a8f3f6d76e0bbd48fd6a902e323089) but not in the master.

**Comment by gjn** [comment]
So we need to update ol3 in master?

**Comment by oterral** [comment]
needs to fix ol3 first. I've hacked directly in build-artefacts/ol3 folder for the release.
