### ISSUE TITLE
South west of switzerland is missing in 3d 

### ISSUE THREAD

**Issue by oterral** [geoadmin/mf-geoadmin3#2872]
https://mf-geoadmin3.dev.bgdi.ch/?lang=fr&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&dev3d=true&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bafu.wrz-wildruhezonen_portal,ch.swisstopo.swisstlm3d-wanderwege&layers_visibility=false,false,false,false&layers_timestamp=18641231,,,&lon=6.08960&lat=46.20285&elevation=18158&heading=4.306&pitch=-89.994

**Comment by oterral** [comment]
Caused by ol3, ol3-cesium and cesium update https://github.com/geoadmin/mf-geoadmin3/pull/2787

**Comment by gberaudo** [comment]
This happens at all border tiles with missing terrain.
The tiles are not refined, and stay at zoom level 8:
![non_refining_border_tiles_zoom8](https://cloud.githubusercontent.com/assets/7294662/11142671/7e6192aa-89ef-11e5-87bf-ec6fa87a908a.png)

**Comment by gjn** [comment]
There are other regions missing as well:

https://mf-geoadmin3.dev.bgdi.ch/?&lang=fr&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&dev3d=true&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bafu.wrz-wildruhezonen_portal,ch.swisstopo.swisstlm3d-wanderwege&layers_visibility=false,false,false,false&layers_timestamp=18641231,,,&lon=9.96651&lat=46.34553&elevation=47089&heading=359.569&pitch=-89.515

I think it's because of the terrain layer.json definition, which simply excludes this regions for bigger LOD's

**Comment by gjn** [comment]
@gberaudo @oterral Oli referred to code change. Would you know where to look?

(I'm currently analysing layer.json file, but it's maybe not related to layer.json).

**Comment by gjn** [comment]
I think the current layer.json is correctly defined (at least for LOD the tiles are defined, but not loaded for given region). So problem seems to be in code.

**Comment by gjn** [comment]
@gberaudo @oterral Could it be this: https://github.com/camptocamp/cesium/commit/6d42f47726df2343f4e210206381e1c0b5487d77

**Comment by gberaudo** [comment]
@gjn, I looked at the changes in Cesium, it is only a few commits related to maximum zoom level of imageries. Very unlikely to be related but I traced anyway and found the option was not used (Infinity).

Then I noticed when you ar really close to Geneva (zoom 14) and you refresh the page, it may load with the right tiles (zoom 14, but not for all tiles).

When looking at the property `surface['_debug']['tilesWaitingForChildren']`, I see it never becomes 0,
whatever the time waited.

I am continuing investigation.

**Comment by gjn** [comment]
The commit in mf-geoadmin3: https://github.com/geoadmin/mf-geoadmin3/commit/fd9271a99ec42c07a73b2c8d85710f98d083cf3f

The changes in ol3-cesium: https://github.com/openlayers/ol3-cesium/compare/d72857d9c53471063d80f3622004dc14acbe6278...cd65a124a2c9f907abf8907be44cfa45228dc5a7

The changes in cesium: https://github.com/AnalyticalGraphicsInc/cesium/compare/9e67416d1016436b5cb237d6ec34f6c988bc5ecc...f04e8953bbef9103f53b8564039608dbaa5d7e16

**Comment by gjn** [comment]
Not sure it's (only) ImageryRelated. It looks to me as terrain files are not loaded as well.

I disabled the autorenderloop and have the same behaviour.

**Comment by loicgasser** [comment]
I updated the layer.json with the empty ranges at the begging, it works with wanderwege.
[Test Link] (https://mf-geoadmin3.int.bgdi.ch/?dev3d=true&topic=ech&lang=en&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.swisstlm3d-wanderwege&lon=7.71789&lat=46.02437&elevation=28188&heading=1.030&pitch=-39.156)

**Comment by gjn** [comment]
@loicgasser That's probably for https://github.com/geoadmin/mf-geoadmin3/issues/2874

**Comment by gjn** [comment]
Now this here is not an easy one. Couldn't find anything further. @gberaudo Any progress?

**Comment by gberaudo** [comment]
Not yet @gjn.

**Comment by loicgasser** [comment]
if the error comes from partial, the problem may solve by itself with new tiles as we will take into account the Switzerland's surroundings.

**Comment by gberaudo** [comment]
I cloned and compiled from scratch the commit 1e9a63303749ee1de644be031a104e3104a7deb3 (#2787) and the issue does not occur. @oterral, how did you find out about this commit?

**Comment by gjn** [comment]
I assume he used `git bisect`, as I tracked it down with this.

So it seems versions of ol3, ol3cesium and/or cesium as indicated in the Makefile does not correspond to the actual versions as put in git. I remember some hand patches.

Were you able to get the diff of ol3cesium-devug.js and cesium.js after clean compile?

**Comment by gjn** [comment]
Doing `make ol3cesium` for https://github.com/geoadmin/mf-geoadmin3/commit/1e9a63303749ee1de644be031a104e3104a7deb3 does actually create a huge commit. So versions in git are not the same as indicated in Makefile.

I'll try a clean checkout with current master.

**Comment by gjn** [comment]
The original problem is still there when doing a fresh checkout of master, make ol, make ol3cesium and make all.

**Comment by gjn** [comment]
Seems like #2883 new terrain tiles fixed this issue, which is awfully strange. I'd still like to keep this open and investigate a little more.

**Comment by oterral** [comment]
Really weird because I have done a checkout before and after the commit I mentioned and before the commit the bug was not there. But the 2 commits used the same layer.json.

**Comment by gberaudo** [comment]
The diff showed some debug code was removed. Certainly, the `minifyRelease`
target was not used
when generating Cesium.

This morning it looks like the blurred area was smaller near Geneva and
disappeared in some other places.

**Comment by oterral** [comment]
I've just tested   with and without the debug messages. With debug messages it doesn't work and without it's working.

**Comment by gberaudo** [comment]
@loicgasser, I am getting Cesium exception on some tiles when it tries to upsample them.
Notably, these upsampled tiles get no horizon occlusion point, which throws an exception.
They also have no vertices.
```
Cesium.js:29241 {"sX":4232,"sY":998,"sZ":12,"dX":8465,"dY":1997,"dZ":13}
Cesium.js:29241 {"sX":4232,"sY":998,"sZ":12,"dX":8464,"dY":1997,"dZ":13}
Cesium.js:29241 {"sX":4231,"sY":998,"sZ":12,"dX":8463,"dY":1997,"dZ":13}
Cesium.js:29241 {"sX":4231,"sY":998,"sZ":12,"dX":8462,"dY":1997,"dZ":13}
Cesium.js:29241 {"sX":8463,"sY":1996,"sZ":13,"dX":16927,"dY":3993,"dZ":14}
Cesium.js:29241 {"sX":8463,"sY":1996,"sZ":13,"dX":16926,"dY":3993,"dZ":14}
Cesium.js:29241 {"sX":16925,"sY":3993,"sZ":14,"dX":33851,"dY":7987,"dZ":15}
Cesium.js:29241 {"sX":16925,"sY":3993,"sZ":14,"dX":33850,"dY":7987,"dZ":15}
Cesium.js:29241 {"sX":16925,"sY":3993,"sZ":14,"dX":33851,"dY":7986,"dZ":15}
```
sX, sY, sZ are the coordinates of the source tile giving its data.
dX, dY, dZ are the coordinates of the destination tile that is created using data from the source.

This may be the cause of the blur and is preventing the autorender loop to work properly.

**Comment by gberaudo** [comment]
@loicgasser, in the south west of Geneva, I just got the following view:

![gap](https://cloud.githubusercontent.com/assets/7294662/11178828/96e1e9f8-8c4f-11e5-8842-431bd020cea7.png)

Cesium was able to refine the tile (don't know why it succeed this try) and we can see a big white gap.

**Comment by oterral** [comment]
I think I understand what was the problem.

For example with the tile at the south east of geneva like.

At zoom level 8 the tile is displayed correctly, but the there is no terrain data on the major part of this tile.
At level 9, this tile is divided in four smaller tiles but, for the tile at the south west, there is no data available (this tile is excluded by the layer.json) so Cesium try to upsample this tile with terrain data from parent tile. The problem is that the parent tile is totally empty at the south-west , so the tile has still no terrain data to display, so the tile is defined as not renderable and finally if one of the four tiles at the level9 is not renderable  all the tiles are not rendered and the parent tile (level 8) is displayed.

So, since we have now terrain tiles fully filled (tile with the timestamp 20160101) we can close this bug.

**Comment by oterral** [comment]
For informations, with the HEAD of c2c_patches branch I can reproduce the bug.

**Comment by gjn** [comment]
Seems like code changes resulted in more strict handling of partial tiles in the data.
