### ISSUE TITLE
Layer.json for image layers not correct

### ISSUE THREAD

**Issue by gjn** [geoadmin/mf-geoadmin3#2874]
Probably mapproxy configuration?

https://mf-geoadmin3.dev.bgdi.ch/?dev3d=true&topic=ech&lang=de&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bafu.wrz-wildruhezonen_portal,ch.swisstopo.swisstlm3d-wanderwege&layers_visibility=false,false,false,true&layers_timestamp=18641231,,,&X=126086.42&Y=632155.82&zoom=6

**Comment by procrastinatio** [comment]
No, `ch.swisstopo.swisstlm3d-wanderwege`is correctly configured on `wmts{10-14}.geo.admin.ch`
![15](https://cloud.githubusercontent.com/assets/1236739/11141278/13990e22-89e4-11e5-8d88-86efa638aa5c.png)

**Comment by cedricmoullet** [comment]
Then, what is the issue in the viewer ?

**Comment by gberaudo** [comment]
The imagery `layer.json` is 5.4 MB, which is very very big.
curl -e "http://terrain3.geo.admin.ch" http://terrain3.geo.admin.ch/1.0.0/ch.swisstopo.swisstlm3d-wanderwege/default/20150101/4326/layer.json > layer.json

If I bypass it, then the imagery shows up in 3D.

**Comment by procrastinatio** [comment]
The viewer ask for a layer definition in json. This layer does not exist for [TLM](https://terrain3.geo.admin.ch/1.0.0/ch.swisstopo.swisstlm3d-karte-farbe.3d/default/20150101/4326/layer.json) is empty, but [wanderwege](https://terrain3.geo.admin.ch/1.0.0/ch.swisstopo.swisstlm3d-wanderwege/default/20150101/4326/layer.json) is not.

So the config for this layer seems broken.

**Comment by gberaudo** [comment]
Moreover, the layer.json only contains 9 levels: [2, 7, 19, 42, 121, 555, 3396, 17423, 63406].
It makes use of the unsupported `minzoom` attribute.

**Comment by gberaudo** [comment]
To elaborate on my last comment, the `minzoom` attribute in the `layer.json` must always be `0`.
Unavailable zoom levels should simply be empty in the `available` array.
The array lengths would become [0, 0, 0, 0, 0, 0, 0, 0, 2, 7, 19, 42, 121, 555, 3396, 17423, 63406].

**Comment by gjn** [comment]
ok. seems like problem with layer.json. I will create PR to de-activate usage of layer.json for all layers (of course, well keep the terrain layer.json) - to assure stable environment for tests and next Thursday.

**Comment by gjn** [comment]
Changed title and attributed to @loicgasser .

We'll discuss this next Tuesday with @ltclm and @AFoletti .

**Comment by loicgasser** [comment]
I updated the layer.json with the empty ranges at the begging, it works with wanderwege.
[Test Link] (https://mf-geoadmin3.int.bgdi.ch/?dev3d=true&topic=ech&lang=en&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.swisstlm3d-wanderwege&lon=7.71789&lat=46.02437&elevation=28188&heading=1.030&pitch=-39.156)
