### ISSUE TITLE
3D mobile : Sky is not following rotation

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#2879]
android 4.4.2 galaxy s4 chrome

start https://mf-geoadmin3.dev.bgdi.ch/?dev3d=true

turn image
![88c2ab04-5bf8-42b1-868b-7c72a650605b](https://cloud.githubusercontent.com/assets/4577727/11150985/fcfe61de-8a2a-11e5-9e58-c9da027b47ef.png)

result:

blue sky is distorted

**Comment by fredj** [comment]
It's working as expected on a Nexus 5 (chrome browser)

**Comment by cedricmoullet** [comment]
@davidoesch still an issue ?

**Comment by davidoesch** [comment]
Still an issue on the same device on alpha for this orientation https://mf-geoadmin3.int.bgdi.ch/3dalpha/mobile.html?topic=ech&lang=en&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bafu.wrz-wildruhezonen_portal,ch.swisstopo.swisstlm3d-wanderwege&layers_visibility=false,false,false,false&layers_timestamp=18641231,,,&lon=8.07857&lat=46.81971&elevation=1999&heading=91.318&pitch=0.718

**Comment by oterral** [comment]
@davidoesch even it still an issue. If it works on more recent mobile I suggest we ignore it and close this.

**Comment by davidoesch** [comment]
yep
I close this one and let see how it works with the latest cesium Version before we launch beta
