### ISSUE TITLE
3D mobile: feature highlight is not shown 

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#2880]
android 4.4.2 galaxy s4 chrome

start https://mf-geoadmin3.dev.bgdi.ch/?dev3d=true

activate swissimage

tap for tooltip

tooltip appears

but no feature highlight shown
![88c2ab04-5bf8-42b1-868b-7c72a650605b](https://cloud.githubusercontent.com/assets/4577727/11151106/7e05bea8-8a2b-11e5-8030-fb8fe3d88780.png)

**Comment by mariokeusen** [comment]
I could not even display a tooltip. Tipping on map and nothing happened.
Same OS, same device.

**Comment by oterral** [comment]
Tooltip popup is probably fixed with  https://github.com/geoadmin/mf-geoadmin3/pull/2910

**Comment by oterral** [comment]
For the highlight it's related to this bug https://github.com/geoadmin/mf-geoadmin3/issues/2911 so I close this one.
