### ISSUE TITLE
Version mismatches and other build stuff

### ISSUE THREAD

**Issue by gjn** [geoadmin/mf-geoadmin3#2881]
Don't we have a potential mismatch of ol3 version as well? We build one in mf-geoadmin3 (OL3_VERSION in the Makefile, part of build.js), and we have one as submodule of ol3-cesium project.

Here's what I think needs to be adressed in current build setup:
**ol3 version mismatch**
- in src -> ol3-cesium subproject version (part of ol3cesium-debug.js)
- in prd -> ol3 version as specified in Makefile (part of build.js)

If correct, having different versions of ol3 in src/prd is not not good and needs to be corrected.

**ol3cesium in prd contains alot of whitespace (is not minified/uglified)**

ping @oterral @gberaudo @fredj

**Comment by gberaudo** [comment]
Currently, the OL3 version used in the OL3-Cesium project is only used to
generate OL3 externs.
During the OL3-Cesium build step, these externs are used by the closure
compiler (but not the OL3 code).

There is a reflexion to change the way OL3-Cesium is built: it would not
use OL3 externs,
but instead directly compile with OL3 source (like in ngeo). It would break
several benefits.

As soon as I have some time, I will have a look to this and update the
build mechanism in geoadmin.

**Comment by gjn** [comment]
But there is ol3 code in ol3cesium-debug.js, or not? If yes, it's the one specified as submodule in ol3-cesium, right?

**Comment by gberaudo** [comment]
No, it is the one from .build-artefacts/ol3.

**Comment by gjn** [comment]
I miss where this definition is made (to use .build-artefacts/ol3).

**Comment by gberaudo** [comment]
The `Makefile` contains the line `node build/build.js ../../scripts/ol3cesium-debug-geoadmin.json dist/ol3cesium-debug.js;`.
In `../../scripts/ol3cesium-debug-geoadmin.json`, the `../ol3` prefix resolves to `.build-artefacts/ol3`.

**Comment by gjn** [comment]
Thanks for the explanation and your patience.

**Comment by gberaudo** [comment]
New build mechanism implemented with https://github.com/geoadmin/mf-geoadmin3/pull/2924
@gjn, I think we can close this one.

**Comment by gjn** [comment]
Yes. Thanks alot for addressing this.
