### ISSUE TITLE
Fresh checkout fails

### ISSUE THREAD

**Issue by gjn** [geoadmin/mf-geoadmin3#2882]
Current master, fresh checkout. 

`make ol3cesium` fails with `ERR! Unsatisfied dependency "ol.Observable" in script: /home/ltjeg/mf-geoadmin3/.build-artefacts/ol3-cesium/src/abstractsynchronizer.js`

**Comment by gjn** [comment]
To reproduce, do `make ol3cesium` directly after an `make cleanall`.

After a `make ol` the command `make ol3cesium` does not produce this error anymore.

I don't understand our build system anymore.

**Comment by gberaudo** [comment]
@gjn, the line `node build/build.js
../../scripts/ol3cesium-debug-geoadmin.json dist/ol3cesium-debug.js;`
depends on `.build-artefacts/ol3`.

As such, the ol3cesium target should depend on OL3 from geoadmin.
