### ISSUE TITLE
Cadastral web map in 3D far zones 

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#2887]
I know its a feature and not a bug

Far zooones are in green:  since the WMS for this resoltion is defined as green

https://mf-geoadmin3.dev.bgdi.ch/mobile.html?dev3d=true&topic=ech&lang=en&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.kantone.cadastralwebmap-farbe,ch.swisstopo.geoidmodell-ch1903&mobile=true&lon=7.45777&lat=46.92195&elevation=828&heading=303.074&pitch=-15.167&layers_opacity=1,0.75&layers_visibility=true,false

an ideas on how to solve this?

**Comment by oterral** [comment]
We could define a maxResolution for 3d

**Comment by pakb** [comment]
Is it possible in Cesium to play with "far" properties on each layer drawing? Or is it only set in camera globally?
