### ISSUE TITLE
3D: IE 11/WIN 7 - Geolocalisation Button does not work

### ISSUE THREAD

**Issue by danielabrandt** [geoadmin/mf-geoadmin3#2889]
Test: 3D Navigatiion
Geolocalisation Button works with Chrome and FF, but not with IE 11.

If I click on Button nothing happens. It stays black - no geolocalisation on the Viewer.

**Comment by fredj** [comment]
Does it work in 2d?

**Comment by fredj** [comment]
Does it work here: http://html5demos.com/geo ?

**Comment by danielabrandt** [comment]
yes works on html5 but not in 2D, you are right.
