### ISSUE TITLE
3D mode:  does not load in IE11 on mobile device (surface)

### ISSUE THREAD

**Issue by rfrancel** [geoadmin/mf-geoadmin3#2890]
OS: Windows 8
BROWSER: IE11
LINK: https://mf-geoadmin3.int.bgdi.ch/3dalpha/
STEPS TO REPRODUCE: click on 3D button
RESULT: background becomes white and then application freezes.

**Comment by gjn** [comment]
Is there any way to at least catch the error and inform the user? Or to detect configurations (hardware/browser) with sniffer tool and de-activate 3D?

**Comment by oterral** [comment]
Error in console (Surface):
```
WEBGL11102: linkProgram: internl linker error
[Cesium WebGl] Shader program  link log: Internal linking error
```

Here the msdn doc: https://msdn.microsoft.com/library/dn358554(v=vs.85).aspx

**Comment by oterral** [comment]
Sandcastls cesium has the same problem. It doesn't work at all.

**Comment by gjn** [comment]
Any whay to catch that?

**Comment by oterral** [comment]
Seems we can https://cesiumjs.org/Cesium/Build/Documentation/Scene.html?classFilter=scene#renderError

**Comment by gjn** [comment]
It would be great to catch that, fail gracefully and inform the user about it in a popup.
