### ISSUE TITLE
3 D: WIN7 IE 11: Highlight of feature info and tooltip

### ISSUE THREAD

**Issue by danielabrandt** [geoadmin/mf-geoadmin3#2891]
Hi Gilbert,

dont know if the web is too slow, however other functions work, but if I want to Highlight the Jagdbanngebiete and print Feature info (tooltip), the Highlight does not work and I do not get the tooltop after clicking in the object.

Test: 3D Feature Tooltip
Win 7 / IE 11

**Comment by danielabrandt** [comment]
Hello Daniela.

About this issue : https://github.com/geoadmin/mf-geoadmin3/issues/2891 

I’m working on this layer (ch.bafu.wrz-jagdbanngebiete_select).
I have removed tiles to create it again (generation is on going) because of an update (Mario know that : https://redmine.prod.bgdi.ch/issues/4647 )

This layer should work’s normally in few minutes.
Best regards,
Patrick

**Comment by danielabrandt** [comment]
However it does not work with KGS Inventar as well. It seems to be a bug, because I get the Objectinfo on Chrome and FF:

**Comment by danielabrandt** [comment]
https://mf-chsdi3.int.bgdi.ch/shorten/683b3bf522

**Comment by oterral** [comment]
Tooltip popup is fixed with  https://github.com/geoadmin/mf-geoadmin3/pull/2910, for highlight see https://github.com/geoadmin/mf-geoadmin3/issues/2911
