### ISSUE TITLE
3D all ch.astra.*land layer are not working

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#2898]
https://mf-chsdi3.int.bgdi.ch/shorten/683fe88b78  no data in 3d

json od mapproxy config issue?

**Comment by gjn** [comment]
@procrastinatio Did we miss a mapproxy configuration update?

**Comment by procrastinatio** [comment]
See PR https://github.com/geoadmin/mf-chsdi3/pull/1763

With autoscalling, the mapproxy config will be automagically updated on the basis of `layersConfig` and `topics` services.

**Comment by procrastinatio** [comment]
@gjn yes, but I really would like to test the new `autoscaling`line now.

**Comment by gjn** [comment]
What about the baseline instances? Will they be updated as well?
