### ISSUE TITLE
3D bgLayer=voidLayer does not work

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#2899]
test
https://mf-geoadmin3.int.bgdi.ch/3dalpha/?topic=ech&lang=de&bgLayer=voidLayer&layers=ch.bafu.flussordnungszahlen-strahler&lon=8.54986&lat=47.24503&elevation=9890&heading=159.434&pitch=-27.869&layers_opacity=0.75

expected result:

no tlm shown as bg

**Comment by cedricmoullet** [comment]
I think it's fixed in the trunk

**Comment by gjn** [comment]
It's duplicate of https://github.com/geoadmin/mf-geoadmin3/issues/2837, which is fixed in current master.

**Comment by gjn** [comment]
It's duplicate of https://github.com/geoadmin/mf-geoadmin3/issues/2837, which is fixed in current master.
