### ISSUE TITLE
3D mode: WIN8 IE11: Feature is not highlighted & information popup is not appeared

### ISSUE THREAD

**Issue by mariavkourouni** [geoadmin/mf-geoadmin3#2900]
Steps to reproduce:
1. 3D button activated.
2. Add ch.bafu.bundesinventare-jagdbanngebiete to the map.
3. Click on an object of the layer in the map.

Result:
1. The feature is not highlighted.
2. The feature information popup is not appeared.

Expected result:
1. A feature information popup appears and the feature is highlighted.
2. The feature tooltip content can be printed.

WIN8 IE11
Same as for WIN7 IE11

Test link: https://mf-chsdi3.int.bgdi.ch/shorten/684033e69a

**Comment by mariavkourouni** [comment]
#2891

**Comment by oterral** [comment]
Tooltip popup is fixed with  https://github.com/geoadmin/mf-geoadmin3/pull/2910, for highlight see https://github.com/geoadmin/mf-geoadmin3/issues/2911
