### ISSUE TITLE
3D: strange layout of timeslider when returning to 2D from 3D mode

### ISSUE THREAD

**Issue by mariokeusen** [geoadmin/mf-geoadmin3#2901]
OS: apple OSX, Chrome and FF

UC: open app, switch to 3D mode, load the layer ch.swisstopo.zeitreihen, return to 2D mode
Result: in 3D the time-support is disabled (which is correct), after returning to 2D mode, the layout of the timeslider is weird (year number shifted to left).
Expected: time slider looks like always
![3d_timesliderafterreturn](https://cloud.githubusercontent.com/assets/4577749/11208133/a6966142-8d19-11e5-90df-f49200a72b98.PNG)

**Comment by fredj** [comment]
Same issue on linux
