### ISSUE TITLE
[WMS import]: not funtional URL in dropdown list

### ISSUE THREAD

**Issue by mariokeusen** [geoadmin/mf-geoadmin3#2902]
UC: open app, open the WMS-import tool, chose https://secure.asitvd.ch/proxy/ogc/vd-wms from the dropdown-list, try to connect to the service.
Result: no connection possible
Expected: WMS is accessible
Workaround: drop from the list or inform the WMS provider.

**Comment by davidoesch** [comment]
the WMS changed
http://wms.vd.ch/public/services/VD_WMS/Mapserver/Wmsserver 

pls change configuration in pulldown
