### ISSUE TITLE
[WMS import]: no zoom to layer button for layers of WMS Basel-Stadt

### ISSUE THREAD

**Issue by mariokeusen** [geoadmin/mf-geoadmin3#2903]
![Uploading 3D_wms_no_zoombutton.PNG…]()
All OS, all browsers

UC: open app, open the wms-import tool, chose https://wms.geo.bs.ch/wmsBS from the dropdown list, watch the layer selection
Result: no "zoom to layer" button (magnifying glass) available
Expected: button is visible as for all other external WMS-layers

Maybe an external issue with the concerned service itself?

**Comment by oterral** [comment]
We receive a WMS 1.1.1 Get Cap not 1.4.0. I bet it's the reason.

**Comment by mariokeusen** [comment]
Then, not in our responsibility
