### ISSUE TITLE
[3D mobile]: difficult to use the 3D navigation and orientation buttons with samsung galaxy s4

### ISSUE THREAD

**Issue by mariokeusen** [geoadmin/mf-geoadmin3#2904]
UC: open app with a samsung galaxy s4 mini (android 4.2.2 and chrome), switch to 3D mode, try to navigate with the buttons on the bottom of the map
Result: with "drummer's" fingers it's almost impossible to use those buttons. Workaround is using the zoom buttons an by panning the map.
Expected: usage of the buttons is more user friendly

Workaround: don't know, if it's possible to improve this, cause this is also due to the small screen. 
![3d_mobile_3d-buttons](https://cloud.githubusercontent.com/assets/4577749/11208617/87835d84-8d1c-11e5-865b-7db08010d515.PNG)

**Comment by davidoesch** [comment]
the icons below di not have the function except reset: rotate tilt is done using the touch/tap&hold on map

@gjin: proposal to grey it out in mobiel? other thoughts?

**Comment by davidoesch** [comment]
after one year of ALPHA
- lets keep the buttons on mobile, since they have a reset function
