### ISSUE TITLE
IE 11 and some Android:  Highlight of feature doesn't work

### ISSUE THREAD

**Issue by oterral** [geoadmin/mf-geoadmin3#2911]
See https://github.com/AnalyticalGraphicsInc/cesium/issues/3214

**Comment by mariokeusen** [comment]
After my test today on IE11: still no feature highlight visible...

**Comment by cedricmoullet** [comment]
@oterral status ?

**Comment by oterral** [comment]
I've put the  link to the bug in Cesium in the description. It's not something that will be fixed in the future.

**Comment by gjn** [comment]
Releated to #3017. We close this one.
