### ISSUE TITLE
[layertree] Catalog categories of topic=verteidigung have disappeared

### ISSUE THREAD

**Issue by mariokeusen** [geoadmin/mf-geoadmin3#2925]
UC: open app, switch to topic Verteidigung, look at the layertree
Result: all layers are listed without any categories
Expected: Layertree has the categorie according to the topic configuration (where it is correct):
https://docs.google.com/spreadsheets/d/1evs0_sEqqJ_zC2m3sn5GEMDYurBlUBCV7qVv4sUuhvY/edit#gid=0

Workaround: please import again the topic config for the next deploy.
![vtg_config](https://cloud.githubusercontent.com/assets/4577749/11303975/23266cd2-8fa6-11e5-8302-565614773e53.PNG)

**Comment by ltclm** [comment]
the category staging is set to 'test' instead of 'prod'

**Comment by ltclm** [comment]
it can be fixed in the bod in place, but the service is cached.

**Comment by ltclm** [comment]
the bod has been fixed. we need a deploy to flush the service cache.

**Comment by gjn** [comment]
Flushing varnish should be enought.

Or deploying the mf-geoadmin3 snapshot should be fine as well.

**Comment by ltclm** [comment]
@alcapat could you please flush varnish for the following pattern:
```
/1447264303/rest/services/verteidigung/CatalogServer
```

**Comment by gjn** [comment]
Still not working?

**Comment by mariokeusen** [comment]
Solved now on prod, got the categories again...

**Comment by alcapat** [comment]
Cache flushed today at 11h
