### ISSUE TITLE
Zeitreihe: play preload data to ensure perfomance

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#2930]
As in the first version, we need to make sure that 

- [ ] the step to the next time stamp is executed only if the current time stamp is completeley loadaed for the whole extent
- [ ] preload data to play time series either on load of the layer or if the timemode is enabled

any proposals?

this needs to be done to before we can go live with
#1942 #2929

**Comment by gjn** [comment]
Do we want to redo zeitreihen application. It won't be that easy and straight forward...

**Comment by davidoesch** [comment]
question @gjin : AFAIK after the first complete loop, all data is cached. On the second loop no delay will be the case.
Can you confirm? if yes- this should be enough

**Comment by oterral** [comment]
I confirm.
