### ISSUE TITLE
Zeitreihe : play v2

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#2931]
to have v2 of play in zeireise live the following tickets need to be resolved
#1942 
#2929 
#2930

**Comment by davidoesch** [comment]
@oterral since #2930 is closed: ready to go

**Comment by oterral** [comment]
All tickets closed

**Comment by davidoesch** [comment]
no so nice side effect: if the play buuton is active, you cant open share ....
