### ISSUE TITLE
[catalog & time button] button active with non time-enabled layers

### ISSUE THREAD

**Issue by mariokeusen** [geoadmin/mf-geoadmin3#2934]
UC: open app, go into ECH geocatalog, navigate in the catalog to "Base Maps", load one of the National Map "noscale" layers
Result: the time button on the right side below the zoom-in / zoom-out buttons is visible and functional and stays functional even when I drop the layer from the selection.
Expected: button is not visible at all.

**Comment by oterral** [comment]
can't reproduce on prod .

**Comment by oterral** [comment]
Forget, I can reproduce.
