### ISSUE TITLE
Zoom to box (SHIFT Mouse ) not visible

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#2935]
USer feedback

"Seit kurzem sieht man beim Aufziehen des gewünschten Kartenausschnitts  (Shift- und mit gedrückter Maustaste den Ausschnitt festlegen) die aufgezogene Box (früher in rot) nicht mehr. Wäre hilfreich, wenn diese wieder angezeigt würde!. "

**Comment by fredj** [comment]
See https://github.com/openlayers/ol3/pull/4278

**Comment by oterral** [comment]
Fixed on master https://github.com/geoadmin/mf-geoadmin3/commit/de81fd6e245b5d37a1844caf5acbd0b1df03f785
