### ISSUE TITLE
zeitreise : close tiles are not loaded in 3d 

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#2937]
https://mf-geoadmin3.int.bgdi.ch/3dalpha/?topic=ech&lang=en&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen&layers_timestamp=19391231&time=1939&lon=7.84129&lat=46.66672&elevation=2163&heading=254.029&pitch=-15.296

result
see: http://www.awesomescreenshot.com/showImage?img_id=782085

**Comment by gjn** [comment]
I need to create account to see the image?

You could direclty paste into github.

**Comment by oterral** [comment]
No tiles from lod 15

**Comment by cedricmoullet** [comment]
Mapproxy issue ? @procrastinatio

**Comment by oterral** [comment]
After debugging it's general problem for layers with  minResolution = 2 . Like geocover.

**Comment by procrastinatio** [comment]
This table shows the native source levels need to generate the EPSG:4326 zoom levels.

As the resolution of 2.0 meters is level 23, you only get reprojected tiles down to zoom level 14.


level 4326 | level 21781 (source)
------------ | -------------
12 |  20
13 | 21
14 | 22
15| 24
16 | 26
17 | 26
18 | 26
19 | 26

**Comment by gjn** [comment]
We now the min max resolution in 2D, with the table above we should be able to tell cesium min/max LOD for a given layer. Does imagery provider support this?

**Comment by oterral** [comment]
It has been already implemented with https://github.com/geoadmin/mf-geoadmin3/pull/2803

**Comment by gjn** [comment]
Does the implementation not correspond to the table mentioned by @procrastinatio higher up? Or why do we request lod 15 when we only have 14?

**Comment by oterral** [comment]
Not exactly :) the gaps are not taken in account

**Comment by procrastinatio** [comment]
See also https://github.com/geoadmin/service-mapproxy/pull/24
