### ISSUE TITLE
Duplicated scripts in master (dev)

### ISSUE THREAD

**Issue by gberaudo** [geoadmin/mf-geoadmin3#2951]
[On master](https://mf-geoadmin3.dev.bgdi.ch/src/?dev3d=true&lang=en&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bafu.wrz-wildruhezonen_portal,ch.swisstopo.swisstlm3d-wanderwege&layers_visibility=false,false,false,false&layers_timestamp=18641231,,,&lon=8.22546&lat=42.69089&elevation=517826&heading=360.000&pitch=-44.169), directive scripts appear several times in the chrome network tab (with disabled cache):
![duplication](https://cloud.githubusercontent.com/assets/7294662/11496096/14c89936-9810-11e5-97e4-7a4f5b18d32b.png)

The issue was found by @oterral while reviewing #2924; though it is unrelated (was already in master).

**Comment by oterral** [comment]
I close this one since it seems a chrome debugger bug.
