### ISSUE TITLE
Background selector reacts on permalink change

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/mf-geoadmin3#2960]
With this line https://github.com/geoadmin/mf-geoad2otmin3/blob/master/src/components/backgroundselector/BackgroundSelectorDirective.js#L81

The background selector closes every time one moves the map. (with a delay and that's the issue, e.g. update of x and y coordinates)

1. Open http://map.geo.admin.ch
2. Pan the map
3. Quickly (not that quickly) open the background

Result:
The background open and closes

Excepted result:
The background closes

Shouldn't we
1. simply remove that because that's a feature that really looks and feels like a bug
2. Listen only to some of the permalink parameters (list of layers etc..)
@gjn @oterral What's your feeling?

**Comment by davidoesch** [comment]
I observed this as well but blamed my old pc. Now I can reproduce it. I propose to deactivate as Loïc suggests

**Comment by gjn** [comment]
I have no qualms removing that part. It would be fully under user control.

**Comment by cedricmoullet** [comment]
Yes, we can remove it

2015-12-03 19:58 GMT+01:00 Gilbert Jeiziner <notifications@github.com>:

> I have no qualms removing that part. It would be fully under user control.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geoadmin/mf-geoadmin3/issues/2960#issuecomment-161747249>
> .
>



-- 
Twitter: http://twitter.com/cedricmoullet
Linked In: http://www.linkedin.com/in/cedricmoullet

<http://twitter.com/cedricmoullet>
