### ISSUE TITLE
Adapt 3d nav btns on mobile

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/mf-geoadmin3#2968]
At the moment 3d nav btns are not really usable in 3d. We should have custom buttons on mobile 
Arrow up and down to replace the head.
Arrow left and right to replace the north arrow.
@davidoesch what do you think?

**Comment by oterral** [comment]
Similar to https://github.com/geoadmin/mf-geoadmin3/issues/2904

**Comment by davidoesch** [comment]
the 3d buttons are used to reset the tilt and orientation on mobile. since verything else is done with pinch and zoom
