### ISSUE TITLE
Marker printed behind a layer added after a search

### ISSUE THREAD

**Issue by oterral** [geoadmin/mf-geoadmin3#2973]
1) Search and click to Bern
2) Add a layer
3) Print 

-> Marker printed behind the layer added

Expected:

Marker printed on top

**Comment by gjn** [comment]
Might be related, or not. But crosshair printin currently does not work in prod:

https://map.geo.admin.ch/?crosshair=marker

It does result in 503 error on the request. Might be fixed with https://github.com/geoadmin/mf-geoadmin3/pull/2959
