### ISSUE TITLE
Error message after usage for measurement tool

### ISSUE THREAD

**Issue by Jenselme** [geoadmin/mf-geoadmin3#2975]
Hi,

I just found a bug. To reproduce:

- Enable draw & measure on map
- Use the measurement tool
- Disable draw & measure on map

Error in chromium console:
```
TypeError: Cannot read property 'removeEventListener' of undefined
    at Nc (build.js:385)
    at Object.Wc [as unByKey] (build.js:391)
    at Object.fn (build.js:1304)
    at n.$digest (build.js:192)
    at n.$apply (build.js:195)
    at HTMLButtonElement.<anonymous> (build.js:312)
    at HTMLButtonElement.x.event.dispatch (build.js:5)
    at HTMLButtonElement.y.handle (build.js:5)
```

What happened? If we take a look at the values of `unSourceEvents` [in DrawDirective](https://github.com/geoadmin/mf-geoadmin3/blob/master/src/components/draw/DrawDirective.js#L371):
```
Array [ Object, Object, Object ] DrawDirective.js:417:13
index 0 Object { listener: this.$get/Debounce/this.debounce/<(), proxy: null, src: Object, type: "addfeature", capture: false, handler: undefined, key: 187, callOnce: false, removed: false } DrawDirective.js:419:15
index 1 Object { listener: this.$get/Debounce/this.debounce/<(), proxy: null, src: Object, type: "changefeature", capture: false, handler: undefined, key: 188, callOnce: false, removed: false } DrawDirective.js:419:15
index 2 Object { listener: this.$get/Debounce/this.debounce/<(), proxy: null, src: Object, type: "removefeature", capture: false, handler: undefined, key: 189, callOnce: false, removed: false } DrawDirective.js:419:15
index max function ProfileChart/Array.prototype.max()
```

In the `for i in unSourceEvent`, i get the `max` value. This comes from [ProfileService](https://github.com/geoadmin/mf-geoadmin3/blob/master/src/components/profile/ProfileService.js#L137) where two keys are added the prototype of Array.

I think this can be solved by either:

- Not modifying the prototype of Array. Quite easy I think but not practical to use.
- Modify the `for i in Array` loops (by switching to forEach or checking that i is an int). Harder since it may happen in any for loop.
- Any other ideas?

**Comment by oterral** [comment]
Good found I fix it

**Comment by Jenselme** [comment]
Thanks!
