### ISSUE TITLE
2d Rotate button permanently updated in 3d

### ISSUE THREAD

**Issue by oterral** [geoadmin/mf-geoadmin3#2985]
@gberaudo I have seen  that the 2d rotate button is always updated (css transform property) when 3d is active even if the map doesn't move.

It seems the [cesiumRendering](https://github.com/openlayers/ol3-cesium/blob/6189779042d3a25b0009cb697f0a35731afe64e8/src/ol3cesium.js#L189) is never stopped . Shouldn't the autorenderloop stuff fix this?

Or maybe it's the [checkCameraChange](https://github.com/openlayers/ol3-cesium/blob/19be567abaa12dc9bd89569bee422a6c4d0a774e/src/camera.js#L479) function that should be modified.

**Comment by cedricmoullet** [comment]
@gberaudo ?

**Comment by gberaudo** [comment]
Sorry, I overlooked this one.

@oterral, are you writting about this button?
![rotate_button](https://cloud.githubusercontent.com/assets/7294662/11835701/b7ca4fbe-a3d5-11e5-84fb-b666607d6d29.png)

or this button?
![rotate_2d](https://cloud.githubusercontent.com/assets/7294662/11835715/d38107d4-a3d5-11e5-9c8f-bd150ed2d2e2.png)

I tested the following url and in both cases the `transform` property stayed constant in the firefox inspector:
https://mf-geoadmin3.dev.bgdi.ch/src/?dev3d=true&lang=fr&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bafu.wrz-wildruhezonen_portal,ch.swisstopo.swisstlm3d-wanderwege&layers_visibility=false,false,false,false&layers_timestamp=18641231,,,&X=169999.63&Y=701388.76&zoom=9

Do you see a different behaviour?

**Comment by oterral** [comment]
The 2nd button yes on right of the screen , on chrome I see its  transform property updating all the time.

**Comment by oterral** [comment]
wow strange just tested and yes the bug doesn't exist anymore.  really weird.

**Comment by oterral** [comment]
@gberaudo have a look here : https://mf-geoadmin3.int.bgdi.ch/?dev3d=true&lang=fr&topic=ech&lon=8.22546&lat=44.01476&elevation=315049&heading=360.000&pitch=-42.846&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bafu.wrz-wildruhezonen_portal,ch.swisstopo.swisstlm3d-wanderwege&layers_visibility=false,false,false,false&layers_timestamp=18641231,,,

there is the bug

**Comment by oterral** [comment]
I guess the [refactoring of buttons directives](https://github.com/geoadmin/mf-geoadmin3/commit/e1c94925b6827afb60f2e066a56d47970c3ba0c2) has fixed this
