### ISSUE TITLE
Up / Down arrow in layer manager

### ISSUE THREAD

**Issue by cedricmoullet** [geoadmin/mf-geoadmin3#2988]
Two clicks are needed in order to up or down one layer. It should work only with one.

**Comment by oterral** [comment]
With which type of layers have you seen that?

**Comment by oterral** [comment]
Ah ok I see the problem. It's a order conflict when marker location is added.

**Comment by cedricmoullet** [comment]
I played with swissimage and wanderwege

2015-12-11 13:16 GMT+01:00 oterral <notifications@github.com>:

> Ah ok I see the problem. It's a order conflict when marker location is
> added.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geoadmin/mf-geoadmin3/issues/2988#issuecomment-163924905>
> .
>



-- 
Twitter: http://twitter.com/cedricmoullet
Linked In: http://www.linkedin.com/in/cedricmoullet

<http://twitter.com/cedricmoullet>
