### ISSUE TITLE
Mobile scrolling issue

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#2990]
Try to resolve the scrolling issue on mobile as described in
http://codepen.io/xavieralexandre/full/EPjgLQ for iframe

**Comment by xavieralexandre** [comment]
`interactions: ol.interaction.defaults({mouseWheelZoom: false})` for mouses & trackpads and `interactions: ol.interaction.defaults({dragPan: false})` for touchscreens avoid unwanted interactions with the iframe. It does not solve scrolling problem on mobile though as the iframe continues to capture touch interaction. And it obviously disables entirely `mouseWheelZoom` and `dragPan` which is not ideal.

A solution could be to have two states. When inactive the iframe would not capture `mouseWheelZoom` and `dragPan` and when clicked the iframe would switch to active mode and behaves as Today. The affordance of this behavior would be pretty low though.

**Comment by oterral** [comment]
No a mf-geoadmin issue. it seems the codepen has evolved and it's the good way to do that. Put an overlay on the top on the iframe.
