### ISSUE TITLE
[topic aviation] new service link URL's

### ISSUE THREAD

**Issue by mariokeusen** [geoadmin/mf-geoadmin3#2991]
UC: bazl will have a migration of its CMS on December 23rd. Therefore we'll have to replace the service link url on the topic=aviation.
New URL's are available in the translation sheet (row 161): https://docs.google.com/spreadsheets/d/1F3R46w4PODfsbJq7jd79sapy3B7TXhQcYM7SEaccOA0/edit#gid=0

Thanks for importing the new urls for this week's deploy.
FYI: new URL's are not yet functional, but the customer decided to replace them before the new cms is available

**Comment by mariokeusen** [comment]
Hi Patrick,

Unfortunately the CMS-project of bazl forced the customer to once again adapt the URL: I have updated the translation sheet on row 161. Thanks for considering this on short term

Mario

**Comment by cedricmoullet** [comment]
@alcapat @gjn could you please take in account this for today ?

**Comment by alcapat** [comment]
@cedricmoullet  the PR for this update (#2992) is already merged

**Comment by cedricmoullet** [comment]
With the latest translations ?

**Comment by alcapat** [comment]
Yes

**Comment by gjn** [comment]
@mariokeusen Can we close?

**Comment by mariokeusen** [comment]
Jep all good.
