### ISSUE TITLE
3D tooltip: can't close window

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#2993]
iphone 5s , 9.2
mf-geoadmin3.int.bgdi.ch/?dev3d=true

"1. Open application activate 3d Button
2. Activate the catalog in the accordeon panel
3. Add ch.bafu.bundesinventare-jagdbanngebiete to the map
4. Click on an object of the layer in the map
6. Close the tooltip window"

Cant close window since the object  window close button is not visible
![img_0100](https://cloud.githubusercontent.com/assets/4577727/11777089/38138d38-a24c-11e5-80b8-180844995a59.PNG)

Workaround: open and close Menü ( I assume it is a side effect of the new menü)

**Comment by oterral** [comment]
Fixed with https://github.com/geoadmin/mf-geoadmin3/pull/2989
