### ISSUE TITLE
Profil with IE 9 doesn't work (ont INT)

### ISSUE THREAD

**Issue by alcapat** [geoadmin/mf-geoadmin3#2999]
Open this link https://mf-geoadmin3.int.bgdi.ch with IE
Switch to IE 9.
Go to the drawing tool.
Draw a line. A window is display on the bottom left. If you select the tab "Profile", the profile is not visible.
Error occur during the deploy of 15.12.2015

**Comment by oterral** [comment]
Fixed with #3002
