### ISSUE TITLE
3D: Tooltip on nav btns and help (ctrl + right or left click)

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/mf-geoadmin3#3001]
The help is nice, but the user might want something more direct than a big popup window.

A tooltip on both 3D nav buttons as contextual help would be nice. (Desktop only)

The ctrl + right or left click for navigating in 3D is obvious to us but not to all of our users.
It should be more obvious you can use the keyboard to navigate.
This could show up when hovering on the 3D buttons as well.
(I know it's platform dependent but we can detect it and adapt the message accordingly)

@davidoesch What do you think?

translation

tilt
[DE] neigen
[FR] incliner
[IT]  inclina
[EN] tilt
[RM]  inclinar

Rotate
[DE] drehen
[FR] tourner
[IT]  ruotare
[EN] rotate
[RM]  volver

**Comment by davidoesch** [comment]
I already proposed this earlier. Yes +1

As we did for the zoom buttons

**Comment by oterral** [comment]
There is no title for map buttons.

**Comment by davidoesch** [comment]
But there is for plus and minus buttons

**Comment by davidoesch** [comment]
@loicgasser what about directing on hover of 3d button to http://help.geo.admin.ch/?id=28 with "see 3d nav instructions"

**Comment by loicgasser** [comment]
![image](https://cloud.githubusercontent.com/assets/3306154/19692450/420f3f6e-9ad8-11e6-904b-799677ff9e02.png)

@oterral 
We can add a title on the buttons pretty easily.

@davidoesch 
I think it's sufficient here:
![help_3d](https://cloud.githubusercontent.com/assets/3306154/19692601/ce85d4f8-9ad8-11e6-91b2-a9a5ef0b9766.png)

**Comment by davidoesch** [comment]
I agree as well... Let's Close This Ticket. No text below needed (see Schweiz Mobil)

**Comment by oterral** [comment]
I think native html tooltips are something very useful on desktop.
