### ISSUE TITLE
hiking time: overlapping in footer

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3003]
draw profile

result 
![unbenannt](https://cloud.githubusercontent.com/assets/4577727/11841472/c7efb582-a3fd-11e5-99b5-6768509186cd.PNG)

expected result
there is a bigger space between the result and and the axis annotation so there is now overlap

**Comment by mariavkourouni** [comment]
#3007

**Comment by oterral** [comment]
Fixed
