### ISSUE TITLE
3D keyboard control: add SHIFT +arrow  key function

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3005]
Add keyboard control
- [x] Rotate clockwise  Shift + left arrow Rotates the view clockwise. 
- [x]  Rotate counter-clockwise  Shift + right arrow    Rotates the view counter-clockwise.

**Comment by davidoesch** [comment]
Paulo can you update the help as well?

**Comment by oterral** [comment]
@pauloamado @pfanguin  has the help been adapted?

**Comment by oterral** [comment]
@pfanguin can you add it please ?

**Comment by pauloamado** [comment]
It's done

**Comment by oterral** [comment]
Thx @pauloamado
