### ISSUE TITLE
3d not working on android 4.2.2 chrome 47

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3008]
3d of map.geo.admin,ch does not run.
2d works as a defined. When switching 2 3d . Map content is just white . 3d icon is active. No error shown . Cesium newyork exsmple runs fine.

![screenshot](https://cloud.githubusercontent.com/assets/4577727/11850367/28328d28-a42d-11e5-8e26-83a538f33f0d.png)

Expected result -  it runs

**Comment by oterral** [comment]
Yesterday i had the exact same bug on our android 4.2.1, today the alert error message appears correctly. Can you retry please @davidoesch ?

**Comment by davidoesch** [comment]
I have to replace The battery on the device ... Sorry can't test it in the next couple of days. 

But the error was odd

**Comment by oterral** [comment]
I can reproduce again on our  android 4.2.1, all works fine terrain tiles and layers are loaded but  nothing display. I don't understand why.  The browser  and the device seems unusable (CPU overloaded probably)  then the browser crash few minutes after.

**Comment by davidoesch** [comment]
Any idea how many percent of users in Switzerland are using 4.2 and older?

**Comment by davidoesch** [comment]
device to old
-> can we detect if nothing is displayed and issue a warning ?

**Comment by gjn** [comment]
If we would detect it, 3D button would be disabled anyway and 3D links would redirect to 2D.

We can try to improve the feature detection - but we are using cesium standard for that, AFAIK.

**Comment by davidoesch** [comment]
device is just too old. I close it
