### ISSUE TITLE
3D Icon vertical spacing in iframe

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3013]
This one is a picky one

Vertical spacing should be the same as between + and - icon

![image](https://cloud.githubusercontent.com/assets/4577727/11881361/a5c17b12-a506-11e5-9838-59787a79b85f.png)

**Comment by oterral** [comment]
Fixed with https://github.com/geoadmin/mf-geoadmin3/pull/3059
