### ISSUE TITLE
3D and tiny iframes 

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3014]
No idea how deal with this one here ---
http://www.sac-cas.ch/unterwegs/tourenplanung/naturvertraeglich-unterwegs.html
![image](https://cloud.githubusercontent.com/assets/4577727/11881957/26b66e00-a50a-11e5-98dd-f40d7cd8f33c.png)

Expected result:

No overlapping 
Icons visible

**Comment by oterral** [comment]
@davidoesch  we could simply remove buttons when screen < 350px, what do think?

**Comment by oterral** [comment]
or we do nothing, I guess a link to map.geo.admin.ch makes more sense in that case : http://www.sac-cas.ch/umwelt/weitgehend-freier-zugang/wildruhezonen.html

**Comment by davidoesch** [comment]
Just remove the icons if smaller than 350px ... Not only for iframe but as well for the normal site
