### ISSUE TITLE
PDF Issue Adobe Reader Pro

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3016]
Reproduced by several customers: our PDF seems to have an issue with compliance
" Funktion Drucken: Auf dem Bildschirm erscheint das erstellte PDF okay; nach dem Ausdruck aus Adobe Acrobat pro erscheinen ein oder mehrere weisse quadratische Lücken - in der Grösse der quadratischen Markierungen durch den Cursor. Ich fand keinen Weg, sie zu entfernen. Einziger Wrk around: Öffnen mit Adobe Acrobat Reader anstatt Pro, und von dort aus drucken. Das selbe Problem in der professionellen Druckerei, die mich erst auf das Problem aufmerksam gemacht hat udn die auch keine Erklärung wusste.. "

example: [tsa_du_touno_2.pdf](https://github.com/geoadmin/mf-geoadmin3/files/66677/tsa_du_touno_2.pdf)

Goal we support the most widely used PDF Standard PDF/A [1]

I I use tools like http://www.pdf-tools.com/pdf/validate-pdfa-online.aspx 

I get the following errors 
The file contains cross reference streams.
The key Metadata is required but missing.
The dictionary must not contain the key 'OCProperties'.
The key MarkInfo is required but missing.
A device-specific color space (DeviceRGB) without an appropriate output intent is used.
The value of the key SMask is an image but must be None.
A device-specific color space (DeviceGray) without an appropriate output intent is used.
The font Helvetica must be embedded.
The document does not conform to the requested standard.
The file format (header, trailer, objects, xref, streams) is corrupted.
The document contains device-specific color spaces.
The document contains fonts without embedded font programs or encoding information (CMAPs).
The document contains transparency.
The document's meta data is either missing or inconsistent or corrupt.
The document doesn't provide appropriate logical structure information.

-> So we have to fix this otherwise we are not compliant. I Add this as a prio 1 since it affects a lot of customers

[1] https://en.wikipedia.org/wiki/PDF/A

**Comment by loicgasser** [comment]
We re migrating to MapFish print 3. I don't think it s worth the effort right now. We should test the new Print with this tool instead and make sure this one is compilant.

**Comment by procrastinatio** [comment]
Same test with `mapfish print v3` (PDF 1.7)

```
Validating file "out30.pdf" for conformance level pdfa-1a
The key Metadata is required but missing.
The key MarkInfo is required but missing.
The value of the key SMask is an image but must be None. (2)
A device-specific color space (DeviceRGB) without an appropriate output intent is used.
The key CIDSet is required but missing.
A device-specific color space (DeviceGray) without an appropriate output intent is used.
The key S has a value Transparency which is prohibited. (2)
The font Helvetica must be embedded.
The document does not conform to the requested standard.
The document contains device-specific color spaces.
The document contains fonts without embedded font programs or encoding information (CMAPs).
The document contains transparency.
The document's meta data is either missing or inconsistent or corrupt.
The document doesn't provide appropriate logical structure information.
Done.
```

My take on PDF. As our PDF are mostly raster (pixelkarte, swissimage), using a format designed for vector brings no adavantage. Providing a (georeferenced) image would be even more useful for many users. The PDF standard is über-complex.

**Comment by davidoesch** [comment]
Question 

-> issue is not related to pdf compatibility 

Pdf is simplest format to open and to print for most users, especially for raster. Second we can assure scale of print out since we print for an a4 or a3: with a simple image distortion /scale is a risk

**Comment by procrastinatio** [comment]
To test you assumption, here is a PDF with two layers: the PK and swissimage. All swissimage tiles arewrongs, and hence are not displayed. [pk-with-buggy-swissimages.pdf](https://github.com/geoadmin/mf-geoadmin3/files/68510/pk-with-buggy-swissimages.pdf).

Result:
![habkern](https://cloud.githubusercontent.com/assets/1236739/11932090/f1a8c9d8-a7f2-11e5-863e-0be1fbbe45c7.jpg)

**Comment by davidoesch** [comment]
Rolf z has access to The pro version of Adobe : can you test it at his machine

**Comment by gjn** [comment]
@procrastinatio What do you mean by buggy swissimage tiles? What is buggy?

**Comment by procrastinatio** [comment]
I did issue a PDF with a swissimage with a wrong timestamp (20151230), so this layer exists in the PDF but with no tiles (no images), to test assumption in https://github.com/geoadmin/mf-geoadmin3/issues/3016#issuecomment-166149130. With Adobe Acrobat Pro, no trouble.

**Comment by procrastinatio** [comment]
For now I am listing all possibles _limit_ cases to test the PDF generation, display and print in various viever

**Raster**

- [ ] Missing tiles (no retry)
- [ ] Wrong layer geometry, timestamp
- [ ] Mixed image type: png/jpeg, png8/32 bits, color/greyscale, etc.
- [ ] Transparent tiles, no content tile

**Vector**

- [ ] Multigeometries, outside print area, application area
- [ ] Not supported geometries, wrong geometries, Z and M coordinates
- [ ] Not supported styles
- [ ] Wrong text encoding, not allowed characters
- [ ] Too big geojson

**Comment by procrastinatio** [comment]
Tested  [tsa_du_touno_2.pdf](https://github.com/geoadmin/mf-geoadmin3/files/66677/tsa_du_touno_2.pdf) on Windows, MacOs and Linux, on Acrobat Reader, Acrobat Pro, and various PDF viewer. No problem. Only Adobe Illustrator  CC Tryout 18 on a Mac issues the following error:

```PDF Objects that have been Reinterpreted```
```An unknown imaging construct was encountered.```

resulting in:

<img width="583" alt="pastedgraphic-1" src="https://cloud.githubusercontent.com/assets/1236739/11955890/25b114a6-a8b6-11e5-87c7-39d88c378e40.png">

MapFish print v2 uses `iText 2.1.5 by lowagie.com` to generate PDF

The black tile is in fact an empty tile from layer `ch.bafu.wrz-wildruhezonen_portal` turned black for some reason, probably a network issue. In Adobe Illustrator you may remove it. Missing tiles are simply not displayed (
[missing.pdf](https://github.com/geoadmin/mf-geoadmin3/files/69775/missing.pdf))

**Comment by davidoesch** [comment]
OK: can we sum up
A) Issue: " misisng tiles in the pdf might generate an error"
B) Workaround: regenerate the PDF
C) Solution: adapt mapfishprint to overcome missing tiles  due to  network issue

**Comment by procrastinatio** [comment]
I tested against [JHOVE](http://jhove.sourceforge.net/index.html), one of the few free validating PDF parser.
With [Mapfish print v2](http://www.mapfish.org/doc/print/), pdf document are well-formed and valid PDF 1.5, unless they have WMTS layer. But multipages PDF are valid PDF 1.3.
With [Mapfish print v3](http://mapfish.github.io/mapfish-print-doc/#/overview) documents are well-formed and valid PDF 1.7, even with WMTS layer.

**Comment by procrastinatio** [comment]
Valdating the [ESRI ArcGis API for Javascript](https://developers.arcgis.com/javascript/jsapi/printtask.html), for instance this [demo](http://developers.arcgis.com/javascript/sandbox/sandbox.html?sample=widget_print_webmap) generated PDF gives:

```

Validating file "x_____x2Aoqp2xDc-wF9_eV5CU5-w..x_____x_ags_82e4c08..." for conformance level pdfa-1a
The comment, classifying the file as containing 8-bit binary data, is missing.
The file trailer dictionary must have an id key.
The key Metadata is required but missing.
The dictionary must not contain the key 'OCProperties'.
The key MarkInfo is required but missing.
A device-specific color space (DeviceRGB) without an appropriate output intent is used.
The key CIDSet is required but missing.
The separator before an 'endobj' must be an EOL.
The width for character 1 in font 'XKPUDP+ArialMT' does not match.
The width for character 2 in font 'XKPUDP+ArialMT' does not match.
The width for character 3 in font 'XKPUDP+ArialMT' does not match.
The width for character 4 in font 'XKPUDP+ArialMT' does not match.
The width for character 5 in font 'XKPUDP+ArialMT' does not match.
The width for character 6 in font 'XKPUDP+ArialMT' does not match.
The width for character 7 in font 'XKPUDP+ArialMT' does not match.
The width for character 8 in font 'XKPUDP+ArialMT' does not match.
The width for character 9 in font 'XKPUDP+ArialMT' does not match.
The width for character 10 in font 'XKPUDP+ArialMT' does not match.
The width for character 11 in font 'XKPUDP+ArialMT' does not match.
The width for character 12 in font 'XKPUDP+ArialMT' does not match.
The width for character 13 in font 'XKPUDP+ArialMT' does not match.
The width for character 14 in font 'XKPUDP+ArialMT' does not match.
The width for character 15 in font 'XKPUDP+ArialMT' does not match.
The width for character 16 in font 'XKPUDP+ArialMT' does not match.
The width for character 17 in font 'XKPUDP+ArialMT' does not match.
The width for character 18 in font 'XKPUDP+ArialMT' does not match.
The width for character 19 in font 'XKPUDP+ArialMT' does not match.
The width for character 20 in font 'XKPUDP+ArialMT' does not match.
The width for character 21 in font 'XKPUDP+ArialMT' does not match.
The width for character 22 in font 'XKPUDP+ArialMT' does not match.
The width for character 23 in font 'XKPUDP+ArialMT' does not match.
The width for character 24 in font 'XKPUDP+ArialMT' does not match.
The width for character 25 in font 'XKPUDP+ArialMT' does not match.
The width for character 26 in font 'XKPUDP+ArialMT' does not match.
The width for character 27 in font 'XKPUDP+ArialMT' does not match.
The width for character 28 in font 'XKPUDP+ArialMT' does not match.
The width for character 29 in font 'XKPUDP+ArialMT' does not match.
The width for character 30 in font 'XKPUDP+ArialMT' does not match.
The width for character 31 in font 'XKPUDP+ArialMT' does not match.
The width for character 32 in font 'XKPUDP+ArialMT' does not match.
The width for character 33 in font 'XKPUDP+ArialMT' does not match.
The width for character 34 in font 'XKPUDP+ArialMT' does not match.
The width for character 35 in font 'XKPUDP+ArialMT' does not match.
The width for character 36 in font 'XKPUDP+ArialMT' does not match.
The width for character 37 in font 'XKPUDP+ArialMT' does not match.
The width for character 38 in font 'XKPUDP+ArialMT' does not match.
The width for character 39 in font 'XKPUDP+ArialMT' does not match.
The width for character 40 in font 'XKPUDP+ArialMT' does not match.
The width for character 41 in font 'XKPUDP+ArialMT' does not match.
The width for character 42 in font 'XKPUDP+ArialMT' does not match.
The width for character 43 in font 'XKPUDP+ArialMT' does not match.
The width for character 44 in font 'XKPUDP+ArialMT' does not match.
The width for character 45 in font 'XKPUDP+ArialMT' does not match.
The width for character 46 in font 'XKPUDP+ArialMT' does not match.
The width for character 47 in font 'XKPUDP+ArialMT' does not match.
The width for character 48 in font 'XKPUDP+ArialMT' does not match.
The width for character 49 in font 'XKPUDP+ArialMT' does not match.
The document does not conform to the requested standard.
The file format (header, trailer, objects, xref, streams) is corrupted.
The document contains device-specific color spaces.
The document contains fonts without embedded font programs or encoding information (CMAPs).
The document's meta data is either missing or inconsistent or corrupt.
The document doesn't provide appropriate logical structure information.
The document contains optional content (layers).
Done.
```

**Comment by gjn** [comment]
@davidoesch To be discussed.
