### ISSUE TITLE
KML Import - support clampToGround  mode 

### ISSUE THREAD

**Issue by cedricmoullet** [geoadmin/mf-geoadmin3#3017]
https://github.com/AnalyticalGraphicsInc/cesium/blob/7d449906cf65cf06e75d5cde7bf2dd5921bc95dd/Source/DataSources/KmlDataSource.js#L1461

**Comment by gjn** [comment]
Wait on Cesium.

**Comment by oterral** [comment]
KML import use the KmlDataSource hack now. So lines from import (dndn or via url)  are clamped to ground except for kml creates from the draw.
