### ISSUE TITLE
KML works  with local import but not on URL

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3032]
Why does KML file
https://gist.githubusercontent.com/davidoesch/2d3fa44b076b06449645/raw/9ff3431141f17e37349e38939b34924e03b4a0e8/PatrouilledesGlaciersPOI.kml
not load ? 
https://api3.geo.admin.ch/ogcproxy?url=https%3A%2F%2Fgist.githubusercontent…%2Fce340a06201593f1fc68d7c4cf83950cf9caf5c1%2FPatrouilledesGlaciersPOI.kml Failed to load resource: the server responded with a status of 500 (Internal Server Error)

But perfectly when adding as a local source?

**Comment by oterral** [comment]
Error when parsing the encoding in the ogcproxy (line 75)[https://github.com/geoadmin/mf-chsdi3/blob/master/chsdi/views/ogcproxy.py#L75]

The regex should be something like this `encoding=(\"|')(.*?)(\\\"|\"|')`

**Comment by davidoesch** [comment]
so a bug in ogcproxy?

**Comment by oterral** [comment]
yes

**Comment by davidoesch** [comment]
Now I have a 403 - must be related to our actions yestetday

**Comment by davidoesch** [comment]
403 - related to our actions yesterday

**Comment by oterral** [comment]
@davidoesch  works again 

but the KML mentioned use `insetPixels` for the y coordinate of the hotSpot and ol3 doesn't manage it so nothing appears.

**Comment by davidoesch** [comment]
funny -it worked before with insetpixel
