### ISSUE TITLE
Firefox 43: no map or no app

### ISSUE THREAD

**Issue by gjn** [geoadmin/mf-geoadmin3#3035]
Recently, we get more and more usre reports that they can't see a map or even the application using
Firefox 43. We need to investigate this a little deeper.

First goal would be to try to reproduce it. Do we have a native system with FF43 on windows available?

**Comment by p1d1d1** [comment]
Just tested with FF 43.0.4
It does work. Cannot reproduce

**Comment by oterral** [comment]
yes we have one on win8 pc

**Comment by oterral** [comment]
The only thing it could be. It's the link to map.geo.admin.ch is called with http and the redirection to https is not done. I've seen this bug a long time ago.  But yet it works as expected.

**Comment by davidoesch** [comment]
await ff updates
seems to be oscp cert issue related , maybe plugins
-> advise helpdesk to use alternate browser

**Comment by oterral** [comment]
Any more complains about this ?

**Comment by davidoesch** [comment]
Yes -- but wait for the next ff update
