### ISSUE TITLE
Display coordinates tooltip footer inconsistent : lat/lon

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3036]
- [ ] in "Display coordinates" http://help.geo.admin.ch/?id=12&lang=en

- [x] in contextpopup : is lon/lat representation ( I know we had a reason for this...) but we should switch to lat /lon as in footer info. Since it is ISO standard ( http://www.iso.org/iso/iso_catalogue/catalogue_tc/catalogue_detail.htm?csnumber=39242 https://en.wikipedia.org/wiki/ISO_6709 ) to first mention lat

- [x]   add the human  readable format 46°02.917'N / 7°39.400'E as  well to the context popup? ( I know we use again two lines)

UPDATE this is a flight safety issue request (LW)

**Comment by oterral** [comment]
@davidoesch  @gjn  do we add the format '46°02.917'N / 7°39.400'E'  in the tooltip ?

**Comment by davidoesch** [comment]
Yes as described abive

**Comment by pfanguin** [comment]
See #3100
