### ISSUE TITLE
add RSS syndication to http://api3.geo.admin.ch/releasenotes/index.html

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3039]
Can you add a RSS feed/syndication to http://api3.geo.admin.ch/releasenotes/index.html 
-> user gets a push info on changes

**Comment by loicgasser** [comment]
Good idea: some basic doc on the mecanics
http://pageaffairs.com/notebook/create-your-own-simple-rss-feed

**Comment by gjn** [comment]
something for rebecca or maria.

**Comment by rfrancel** [comment]
I'd be happy to do it

**Comment by mariavkourouni** [comment]
I'd be happy to help if it is needed!
