### ISSUE TITLE
Blurry Images on IE edge

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/mf-geoadmin3#3040]
Map is a bit blurry in IE edge.

Here are 2 printscreens picturing this issue. Pixel ratio issue?

On IE:

![ie_edge](https://cloud.githubusercontent.com/assets/3306154/12293680/6a39e512-b9f5-11e5-829e-56d44eaca59c.png)

On Chrome:

![chrome](https://cloud.githubusercontent.com/assets/3306154/12293687/74a847c8-b9f5-11e5-9ccd-e864990be242.png)

**Comment by oterral** [comment]
Can't do anything.
