### ISSUE TITLE
Tablets Pro:  app load in desktop version (not mobile)

### ISSUE THREAD

**Issue by rfrancel** [geoadmin/mf-geoadmin3#3041]
On Surface Pro size 12.3 " and iPad Pro size 12.9", app loads on desktop, not mobile version.

**Comment by davidoesch** [comment]
Works as defined. Force mobile with mobile=true

**Comment by oterral** [comment]
@davidoesch if at least all worked fine it will  not be a problem but there is some bad behaviors (selection in search results, geolocation, bad hover effects)
I think we could optimize the desktop version for touch device too..

**Comment by davidoesch** [comment]
as discussed: try to add touch detection @oterral

**Comment by oterral** [comment]
Will be fixed with #3408
