### ISSUE TITLE
Offline & geolocation

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3046]
When offline geolocation does not always work

reproduce

https://map.geo.admin.ch/index.html?topic=ech&lang=de&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bafu.wrz-wildruhezonen_portal,ch.swisstopo.swisstlm3d-wanderwege,KML%7C%7Chttps:%2F%2Fgist.githubusercontent.com%2Fponceta%2F68f53f68df2acfb82f87%2Fraw%2Fe02393a787e937ea5f83a1e3bc6e4a0c49f950fe%2Fawards.kml&layers_visibility=false,false,false,false,true&layers_timestamp=18641231,,,,&X=200030.51&Y=602072.97&zoom=6

go offline

Then click geolocation

does not work

Could be reproduced with 2 iphones latest os
![img_1342](https://cloud.githubusercontent.com/assets/4577727/12323705/fd45e1d0-babd-11e5-8065-80288c57264d.png)

**Comment by oterral** [comment]
Apple maps isn't better, no geolocation when airplane mode active.

**Comment by davidoesch** [comment]
What is awkward : sometimes it is working in airplane mode sometimes not: why?

**Comment by oterral** [comment]
Yes I confirm it's working on Android, closer to the window :)

**Comment by oterral** [comment]
If the button stays red it's because it's searching GPS satelittes.

**Comment by oterral** [comment]
I don't succeed to make it works with our iPads, always "Position unavailable" also with apple maps.

**Comment by oterral** [comment]
@davidoesch can we close this one?, because it seems to work when satellites are reached successfully.

**Comment by davidoesch** [comment]
I'm not sure to close this one: with our tests we made during the dev off offline it used to work
