### ISSUE TITLE
Android 6 embedded browser twitter webgl not working

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3049]
Android 6.0.1 
Open ink twitter https://twitter.com/swiss_geoportal/status/687906750008274944?s=09

Webgl warning appears
![screenshot_20160116-080822](https://cloud.githubusercontent.com/assets/4577727/12371141/c3b0eb8c-bc29-11e5-8884-8ff204a0634b.png)

**Comment by oterral** [comment]
It works on Android 5 .  The WebView should support WEBGL since [android 4.4](https://developer.chrome.com/multidevice/webview/overview) . 

Can you verfify in the PlayStore if the WebView component is up to date : https://play.google.com/store/apps/details?id=com.google.android.webview&hl=fr

**Comment by davidoesch** [comment]
yes it IS up to date

**Comment by fredj** [comment]
FYI, it works on my Nexus 5x, android 6.0.1 and Chrome 47.0.2526.83

**Comment by davidoesch** [comment]
OK, I rebooted now my device and now it works,- strange sorry but before i could reproduce it always)
