### ISSUE TITLE
yellow square on map controls (Android)

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3050]
![screenshot_20160117-204849 2](https://cloud.githubusercontent.com/assets/4577727/12379520/f94a7108-bd5c-11e5-88f4-e1273b02de3a.png)
On all Android version 4.2.2 till 6.0.1 on chrome
Touch a map control eg geo location
Result a yellow square appears around the selected icon
The square persists until another highlight is active

**Comment by oterral** [comment]
That's the default behavior it's use for accessibility

**Comment by davidoesch** [comment]
Ugly as hell
