### ISSUE TITLE
Error ch.bafu.swissprtr

### ISSUE THREAD

**Issue by cedricmoullet** [geoadmin/mf-geoadmin3#3052]
HTTP error 404 beim clicken von `Detaillierte Beschreibung` für Ojekt Perlen Papier AG.

Permalink: https://map.geo.admin.ch/?lang=de&topic=bafu&bgLayer=ch.swisstopo.pixelkarte-grau&layers=ch.bafu.swissprtr&X=218301.00&Y=670603.00&zoom=7

**Comment by mariokeusen** [comment]
Data owner has been informed about this error already quite a while ago. Will try once again...

**Comment by AFoletti** [comment]
It's basically an error in the data, and we have no control over that.
@cedricmoullet , a possibility will be to implement a pre-test and not display the link if the answer is a 404, but does it make really sense? The datenherr is responsible for that

**Comment by mariokeusen** [comment]
Request for new delivery with correct URL's has been sent to data owner

**Comment by davidoesch** [comment]
tickets like this rather in redmine: since data related

**Comment by mariokeusen** [comment]
https://redmine.prod.bgdi.ch/issues/4980
