### ISSUE TITLE
[query tool] two translation corrections in Italian

### ISSUE THREAD

**Issue by mariokeusen** [geoadmin/mf-geoadmin3#3058]
Update of translations in Italian at the query tool section (was not proper Italian) on customer request. Was verified with @p1d1d1 
Lines 297 and 301 in [1].

**Comment by davidoesch** [comment]
Removed the link to transition spreadsheet (don't reference the link public)

**Comment by mariokeusen** [comment]
In consequence the translation tab should be moved to an exceltable on the chtopo network...
