### ISSUE TITLE
Use ol.format.EsriJSON

### ISSUE THREAD

**Issue by oterral** [geoadmin/mf-geoadmin3#3064]
[EsriJSON](http://openlayers.org/en/master/apidoc/ol.format.EsriJSON.html) 

Looking at @dcustode code , I discover the EsriJSON format existed in ol3. Maybe using it could clean some parts of code in mf-geoadmin3.

**Comment by oterral** [comment]
@loicgasser @procrastinatio @gjn do you see any places where it could be useful ?

I didn't find one, so we can close this if we don't use this format.

**Comment by loicgasser** [comment]
I feel our ESRIJson solution in chsdi3 is currently suboptimal so I would not make it the default format.
I want to write a clean ESRIJson encoder in python and publish the module.
Only then we could think about making esriJSON the default geometry format.

**Comment by oterral** [comment]
I don't want to make it the default format. I just ask if we currently use it in mf-geoadmin3

**Comment by loicgasser** [comment]
Notre tour m'y knowledge

**Comment by oterral** [comment]
Thx
