### ISSUE TITLE
Share Embed is covered by the short url contextual help

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3066]
all Desktop browsers

open map.geo.admin.ch
open share
point your mouse down to embed
when crossing with the mouse the short url box-> contextual help appears

result: it does cover the embed function
![unbenannt](https://cloud.githubusercontent.com/assets/4577727/12475176/42c970ce-c021-11e5-83fc-d3daf179ae0d.PNG)

Expected result: it does not cover it

Proposal ; on mouse over in map.geo.admin.ch on a box with link: just highlight content as no but do not Show the contextual help

**Comment by oterral** [comment]
I propose to put the tooltip on one line.

**Comment by davidoesch** [comment]
+1 "Ctrl+c for copy"

**Comment by oterral** [comment]
Fixed
