### ISSUE TITLE
haltestellen Stationbaord : time not correct

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3071]
Issue
"
- [ ] A) alle Fahrplanangaben um eine Stunde verschoben. Ausserdem wird die
- [ ] B)  Liniennummer teilweise falsch übernommen.
 Zum Vergleich die Daten von sbb.ch, die im konkreten Fall mit dem gedruckten Kursbuch übereinstimmen! Siehe Feld 31.210. "

![unbenannt2](https://cloud.githubusercontent.com/assets/4577727/12504549/c9e3498c-c0de-11e5-993e-1f2d80ac0453.png)

*Time*
Possible issues
-	is in the delivery of teimtable file the correct time ?
-	is  UTC in their delivery http://time.is/UTC  and we are UTC +1

*Line number*

-> is the link correct between haltestellen data file and the timetable delivery

**Comment by AFoletti** [comment]
Confirmed: times are UTC instead of UTC+1
About line numbers, @pfanguin saw very early during integration process that some stops were wrong (see https://s.geo.admin.ch/6993c16a8e as an example) but it's extremely difficult to assess the real scope of the problem

**Comment by davidoesch** [comment]
both tasks have been assigend to dataowner since it is cleary a problem of data delivery (bs in bs out)
