### ISSUE TITLE
icons do not load

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3084]
Android 601 nexus
Icons like logo and checkboxes do not load
Delete cache 
Restart app everything is OK
Reload by clicking on swiss icon 
Result: icons do not load

Is it just me?

**Comment by davidoesch** [comment]
![screenshot_20160127-201230](https://cloud.githubusercontent.com/assets/4577727/12625231/2a802384-c533-11e5-971c-3a5e31786652.png)

**Comment by cedricmoullet** [comment]
This affects also Safari on Mac. Font awesome is not found

**Comment by cedricmoullet** [comment]
@gjn emergency deploy ?

**Comment by gjn** [comment]
I'll have a look later.

**Comment by gjn** [comment]
Can't reproduce as I don't have the correct environment here.

I assume it's a appcache issue (appcache is such crap...)

@oterral Please have a look first thing in the morning. If you find it, please do an emergency deploy.

**Comment by cedricmoullet** [comment]
I have the same issue on iPhone and Firefox.

**Comment by mariokeusen** [comment]
Can confirm: have no icons neither in Chrome nor in IE11 this morning. And in addition the layer-selection is not visible/available at all.

**Comment by ltclm** [comment]
marcel from our it told me that he has a similar problem with ie11.  
since yesterday the icon on the right side of the swisssearch form is not visible anymore.

![image](https://cloud.githubusercontent.com/assets/5286659/12637797/3bfad16c-c598-11e5-93e6-53343da3a4a9.png)

**Comment by gjn** [comment]
all: doeva disabling and cleaning if browser cache help?

**Comment by oterral** [comment]
Just test on frefox a simple click on th refresh button fix the issue.

**Comment by oterral** [comment]
I redeploy the snapshot

**Comment by oterral** [comment]
It seems a machine hasn't the good version

**Comment by gjn** [comment]
ok.

I could get rid of the problem always with Cltr-F5.

**Comment by gjn** [comment]
For everybody: if you detect similar problems in the future, please safe the page source and send it to me by email.

**Comment by gjn** [comment]
@davidoesch @cedricmoullet Is this ok now?

**Comment by gjn** [comment]
ping @davidoesch

**Comment by cedricmoullet** [comment]
yes, it's fine

2016-01-29 12:24 GMT+01:00 Gilbert Jeiziner <notifications@github.com>:

> ping @davidoesch <https://github.com/davidoesch>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geoadmin/mf-geoadmin3/issues/3084#issuecomment-176700413>
> .
>



-- 
Twitter: http://twitter.com/cedricmoullet
Linked In: http://www.linkedin.com/in/cedricmoullet

<http://twitter.com/cedricmoullet>

**Comment by davidoesch** [comment]
sorry yes fixed
