### ISSUE TITLE
Firefox always detected as touch device

### ISSUE THREAD

**Issue by oterral** [geoadmin/mf-geoadmin3#3087]
Problem is , if the size of the browser window is small when we load the page, the `gaBrowserSniffer` detects the browser as  mobile browser and display a select box for the selection of language

**Comment by oterral** [comment]
It could be related to #3041

Since it's more and more difficult to detect which devices  is a desktop or a browser, maybe we shoudl think to use a mobile first approach and remove the use of 2 different file for desktop and mobile.

**Comment by gjn** [comment]
+1 for single page in principle.

Might be tricky, but we should take into account browser capabilites. might be tricky with hypbrid stuff like touch/mouse support.

And we have the offline stuff....

**Comment by gjn** [comment]
http://www.html5rocks.com/en/mobile/touchandmouse/?redirect_from_locale=de

**Comment by oterral** [comment]
I'm +1 for appcache every where no more requests on varnish cache :)

**Comment by gjn** [comment]
I'm for shooting appcache. Frankly, that is just broken technology.

I'd rather switch to [service workers](http://www.html5rocks.com/en/tutorials/service-worker/introduction/) for the browsers that support it.

**Comment by oterral** [comment]
I raised it to piro 1 because nothing works correctly on desktop (no tooltips for example)

**Comment by oterral** [comment]
ouf it a ff bug when we use dev tools : https://bugzilla.mozilla.org/show_bug.cgi?id=970346
