### ISSUE TITLE
Background selection not possible when snowsports topic activated in dev

### ISSUE THREAD

**Issue by rfrancel** [geoadmin/mf-geoadmin3#3093]
When snowsports topic is activated, and we click on background layers selector, only "no background" is proposed:
https://mf-chsdi3.dev.bgdi.ch/shorten/69b3f2f3f1
Other topics propose all the choices.

**Comment by loicgasser** [comment]
oups good catch

**Comment by loicgasser** [comment]
topic title could be "Sports de neige" instead of "Sport de neige"

**Comment by gjn** [comment]
@loicgasser Most certainly introduced by https://github.com/geoadmin/mf-geoadmin3/pull/3068

I think for the background layer list, we can't use the plConfig parameter.

**Comment by gjn** [comment]
@rfrancel Well done to find this!

**Comment by loicgasser** [comment]
Probably not, should I take it or do you have time?

**Comment by gjn** [comment]
I'll have time tomorrow.

**Comment by loicgasser** [comment]
okay

**Comment by gjn** [comment]
@alcapat The backgrounds information is missing in the bod. This is needed for all topics, as it's a list that is _not_ part of the permalink. So please add this array for the schneesport topic.
