### ISSUE TITLE
Issue with snow topic

### ISSUE THREAD

**Issue by cedricmoullet** [geoadmin/mf-geoadmin3#3094]
![image](https://cloud.githubusercontent.com/assets/319676/12669134/3561f5da-c65e-11e5-82fc-61ba1d771bf2.png)
https://map.geo.admin.ch/?topic=ech&lang=fr&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bafu.wrz-wildruhezonen_portal,ch.swisstopo.swisstlm3d-wanderwege&layers_visibility=false,false,false,false&layers_timestamp=18641231,,,

Catalog and layer manager are not synchronized

**Comment by gjn** [comment]
This is standard behaviour since launch of R3. In Catalog, checkbox shows if layer is added to map or not.

In Layermanager, checkbox shows if layer is visible or not.

**Comment by gjn** [comment]
Anyhow, I think it's a bug that was introduced by this topic handling (new plConfig parameter) that opens the catalog instead of the layermanager.

I will take care of that.
