### ISSUE TITLE
schneesport: layers not avilable on all zoomlevel:

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3095]
https://mf-geoadmin3.dev.bgdi.ch/?topic=schneesport&lang=de&bgLayer=voidLayer&layers=ch.swisstopo.pixelkarte-farbe-pk50.noscale,ch.swisstopo.hangneigung-ueber_30,ch.swisstopo-karto.hangneigung,ch.bafu.wrz-jagdbanngebiete_select,ch.bafu.wrz-wildruhezonen_portal,ch.bazl.heliports-gebirgslandeplaetze,ch.swisstopo-karto.schneeschuhrouten,ch.swisstopo-karto.skitouren,ch.swisstopo.skitourenkarte-50.metadata,ch.bav.haltestellen-oev&layers_opacity=0.85,0.5,0.2,0.6,0.6,1,0.8,0.8,1,1&layers_visibility=false,false,false,false,false,true,true,true,false,false&X=171050.28&Y=675326.20&zoom=8

zoom in

https://mf-geoadmin3.dev.bgdi.ch/?topic=schneesport&lang=de&bgLayer=voidLayer&layers=ch.swisstopo.pixelkarte-farbe-pk50.noscale,ch.swisstopo.hangneigung-ueber_30,ch.swisstopo-karto.hangneigung,ch.bafu.wrz-jagdbanngebiete_select,ch.bafu.wrz-wildruhezonen_portal,ch.bazl.heliports-gebirgslandeplaetze,ch.swisstopo-karto.schneeschuhrouten,ch.swisstopo-karto.skitouren,ch.swisstopo.skitourenkarte-50.metadata,ch.bav.haltestellen-oev&layers_opacity=0.85,0.5,0.2,0.6,0.6,1,0.8,0.8,1,1&layers_visibility=false,false,false,false,false,true,true,true,false,false&X=171082.97&Y=675342.96&zoom=9

disseappears

**Comment by gjn** [comment]
This is data/tile related.

@alcapat @ltclm Is this known? Is this wanted?

**Comment by davidoesch** [comment]
no this is not wanted:ALL layer are visible on ALL zoomlevels-- are the tile still calculating?

**Comment by AFoletti** [comment]
Tiles were calculated up to level 22 (8 in viewer). Then should clientzoom kick in. Why is that not happening?

**Comment by ltclm** [comment]
@alcapat the table tileset is not set correctly.
The layer should switch to clientzoom from zoomlevel 21.
I have changed the bod and deployed to dev.

**Comment by gjn** [comment]
@davidoesch This has been fixed. Please retest and close.

**Comment by davidoesch** [comment]
tested and ok
