### ISSUE TITLE
schneesport: topic selector

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3096]
open per default as well the selection window as in topic ech
(tech lead , project lead)

**Comment by davidoesch** [comment]
Hi there is an issue now on dev:
in the slection window ALL layer should be loaded but onl the six should be active

**Comment by gjn** [comment]
The Heli Layers is now removed as well. Use testlink https://github.com/geoadmin/mf-geoadmin3/pull/3099 for tests that fixes all open issues.

**Comment by davidoesch** [comment]
Just me on Android that in 3d the routes are not showing up? Mapproxy
configuration missing?

https://mf-geoadmin3.dev.bgdi.ch/gjn_plconfigFix/mobile.html?topic=schneesport&lang=de&bgLayer=voidLayer&layers=ch.swisstopo.pixelkarte-farbe-pk50.noscale,ch.swisstopo.hangneigung-ueber_30,ch.swisstopo-karto.hangneigung,ch.bafu.wrz-jagdbanngebiete_select,ch.bafu.wrz-wildruhezonen_portal,ch.bazl.heliports-gebirgslandeplaetze,ch.swisstopo-karto.schneeschuhrouten,ch.swisstopo-karto.skitouren,ch.swisstopo.skitourenkarte-50.metadata,ch.bav.haltestellen-oev&layers_opacity=0.85,0.5,0.2,0.6,0.6,1,0.8,0.8,1,1&layers_visibility=true,false,true,true,true,false,true,true,false,false&catalogNodes=2352&lon=8.36540&lat=46.61928&elevation=7131&heading=360.000&pitch=-40.016

Gilbert Jeiziner <notifications@github.com> schrieb am Fr., 29. Jan. 2016,
14:36:

**Comment by gjn** [comment]
Yes. Most probably layers are missing in mapproxy.
Am 30.01.2016 10:12 nachm. schrieb David Oesch <notifications@github.com>:Just me on Android that in 3d the routes are not showing up? Mapproxy
configuration missing?

https://mf-geoadmin3.dev.bgdi.ch/gjn_plconfigFix/mobile.html?topic=schneesport&lang=de&bgLayer=voidLayer&layers=ch.swisstopo.pixelkarte-farbe-pk50.noscale,ch.swisstopo.hangneigung-ueber_30,ch.swisstopo-karto.hangneigung,ch.bafu.wrz-jagdbanngebiete_select,ch.bafu.wrz-wildruhezonen_portal,ch.bazl.heliports-gebirgslandeplaetze,ch.swisstopo-karto.schneeschuhrouten,ch.swisstopo-karto.skitouren,ch.swisstopo.skitourenkarte-50.metadata,ch.bav.haltestellen-oev&layers_opacity=0.85,0.5,0.2,0.6,0.6,1,0.8,0.8,1,1&layers_visibility=true,false,true,true,true,false,true,true,false,false&catalogNodes=2352&lon=8.36540&lat=46.61928&elevation=7131&heading=360.000&pitch=-40.016

Gilbert Jeiziner <notifications@github.com> schrieb am Fr., 29. Jan. 2016,
14:36:
