### ISSUE TITLE
Tooltip for polygons

### ISSUE THREAD

**Issue by gjn** [geoadmin/mf-geoadmin3#3101]
Original feedback:
```
Die tooltips sind für diese layer (kantone, bezirke, gemeinden) seit einiger Zeit nur noch beim Kllicken auf die Kantonsgrenzen aktiviert.
Wenn man in die Fläche hineinklickt kriegt man ein undefined.
```

There is no identify request issues for some of the polygon layers. We need to rethink our general strategy for the identify requests.

**I would propose** to launch an identify request as soon as a `tooltip` marked layer is available. The issue of the mouse pointer should be treated separately.

[Testlink](https://map.geo.admin.ch/?topic=ech&lang=de&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bafu.wrz-wildruhezonen_portal,ch.swisstopo.swisstlm3d-wanderwege,ch.swisstopo.swissboundaries3d-gemeinde-flaeche.fill&layers_visibility=false,false,false,false,true&layers_timestamp=18641231,,,,)

**Comment by gjn** [comment]
@davidoesch @oterral Thoughs on my proposal?

**Comment by oterral** [comment]
@AFoletti has confirmed what I thought. For the new polygon layers, polygons are  filled with a white color with opacity 0.1. with this hack we have the hand cursor everywhere. 

But the old layers were not  updated with this hack.

**Comment by davidoesch** [comment]
Hmm on mobile the testlink above does not work at all for tooltip. +1 for the proposal

**Comment by cedricmoullet** [comment]
+1

2016-01-29 17:40 GMT+01:00 David Oesch <notifications@github.com>:

> Hmm on mobile the testlink above does not work at all for tooltip. +1 for
> the proposal
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geoadmin/mf-geoadmin3/issues/3101#issuecomment-176853932>
> .
>



-- 
Twitter: http://twitter.com/cedricmoullet
Linked In: http://www.linkedin.com/in/cedricmoullet

<http://twitter.com/cedricmoullet>

**Comment by davidoesch** [comment]
I made this a 1st prio since it affects one of the most used layers (swissboundaries ) and we have  already 4 mails in the inbox regarding this

**Comment by ltclm** [comment]
we will integrate new data in the next two weeks.
The new polygons will have a white color fill with opacity 0.1.

**Comment by gjn** [comment]
@ltclm Can we have it until next Wednesday?
Am 29.01.2016 10:06 nachm. schrieb Clausen Marcel <notifications@github.com>:we will integrate new data in the next two weeks.
The new polygons will have a white color fill with opacity 0.1.

**Comment by gjn** [comment]
I have a little trouble with the fact that we 'hack' the tiles to solve a front-end issue....
Am 29.01.2016 3:07 nachm. schrieb oterral <notifications@github.com>:@AFoletti has confirmed what I thought. For the new polygon layers, polygons are  filled with a white color with opacity 0.1. with this hack we have the hand cursor everywhere. 

But the old layers were not  updated with this hack.

**Comment by ltclm** [comment]
dont know
have to ask the data owner, official release is 10.02.2016

**Comment by ltclm** [comment]
@mariokeusen can we publish this layer one week earlier?

**Comment by ltclm** [comment]
i propose to publish your proposal next week. there are a lot of dependencies on this publication date: 
```
Konkret müssen an diesem Tag die Daten auf folgende System aktualisiert werden : 

map.geo.admin.ch (clm)
data.geo.admin.ch (br liefert ein Zip an Mario)
wms (swisstopo und bgdi) (clm)
Toposhop
                Grundgeometrie für die Selektion (clm)
                Datei für den Download (br liefert ein Zip an Paulo)
ProdasP (Elias)
                Grundgeometrie für die Selektion 
                PRODAS_MANAGER.SPATIALSELTYPE
PRODAS_MANAGER.SPATIALSELTYPE_LV95
http://models.geo.admin.ch/ 
                br liefert die neue Modelle an Rolf Zürcher.
www.swisstopo.ch (br)
                Webseite anpassen (Neues Modell, Neues Datum, ReleaseNote)
                Carrousel news (br liefert DKW)

```

**Comment by ltclm** [comment]
Don't like the invisible fill tile hack at all for this layer. We have to generate millions of (useless) tiles ...
would it be possible to deactivate the client-side pixel value detector for these layers?
"ch.swisstopo.swissboundaries3d-bezirk-flaeche.fill"
"ch.swisstopo.swissboundaries3d-gemeinde-flaeche.fill"
"ch.swisstopo.swissboundaries3d-kanton-flaeche.fill"
"ch.swisstopo.swissboundaries3d-land-flaeche.fill"

**Comment by ltclm** [comment]
.. or we change the layer type to wms, they are in wms-bgdi already.

**Comment by oterral** [comment]
I think this pixel detection stuff leads to too much bugs this time. I understand users expect to have a cursor change  (cursor changed means data received) but we have a lot of use case where it's not consistent (Icons problem with tolerance, transparent polygons). May be the solution is to remove it completely and made a request each time a tooltip layer is available (as @gjn says and as before).

**Comment by gjn** [comment]
Please don't adapt tiles for this. We discuss this and come up with other solutions. Cheating on pixels has no future.
Am 01.02.2016 9:58 vorm. schrieb Clausen Marcel <notifications@github.com>:Don't like the invisible fill tile hack at all for this layer. We have to generate millions of (useless) tiles ...
would it be possible to deactivate the client-side pixel value detector for these layers?
"ch.swisstopo.swissboundaries3d-bezirk-flaeche.fill"
"ch.swisstopo.swissboundaries3d-gemeinde-flaeche.fill"
"ch.swisstopo.swissboundaries3d-kanton-flaeche.fill"
"ch.swisstopo.swissboundaries3d-land-flaeche.fill"

**Comment by davidoesch** [comment]
Wms is no option for this layer: it is one of the top most used layers. IMHO we will need to provide for each layer as well a tooltip geometry layer .... Would solve this issue and the public stop issue where we have multiple stopicons side by side...

**Comment by gjn** [comment]
I'll prepare a fix with my proposal (issue request for every tooltip layer independant of pixel detection) for tomorrow.
