### ISSUE TITLE
3d and gelocoation buggy on mobile

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3103]
This is a wider issue . general 3d and the geoloc is buggy. Especially if you cycle through geoloc buttons. The screen tries to get turned to north... Sometimes it crashes.
If you use it in an iframe as eg http://wandern.ch/de/wo-bin-ich it crashes 3d and 3d buttons stays active

see
![screenshot_20160130-084421](https://cloud.githubusercontent.com/assets/4577727/12748296/a9d466de-c9a9-11e5-819e-7f0b2b49c24e.png)

and

![screenshot_20160130-084213](https://cloud.githubusercontent.com/assets/4577727/12748335/e1f37c3a-c9a9-11e5-82ce-a316448bde98.png)
![screenshot_20160130-084407](https://cloud.githubusercontent.com/assets/4577727/12748336/e2195734-c9a9-11e5-945c-4392a83aa77e.png)

Solutions?

**Comment by oterral** [comment]
Sorry no acces to your links

**Comment by davidoesch** [comment]
update screenshots

**Comment by oterral** [comment]
Thx.  

It seems the problem comes from non-https website :+1: 

Error msg: 
```
getCurrentPosition() and watchPosition() are deprecated on insecure origins. To use this feature, you should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.
```
