### ISSUE TITLE
3D geojson : lines not clamped to ground

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3104]
open
https://map.geo.admin.ch/?lang=de&topic=ech&bgLayer=voidLayer&layers=ch.bafu.hydrologie-hintergrundkarte,ch.bafu.hydroweb-warnkarte_national&layers_opacity=1,0.5&lon=9.31634&lat=46.71379&elevation=100595&heading=8.203&pitch=-73.767

-> rivers not shown
-> Lakes are above the elevation

might be related to same terrain issue we have with kml

**Comment by loicgasser** [comment]
yep new set of tiles coming up next week.

**Comment by loicgasser** [comment]
FYI: geojson are 2D not 3D
Vector lines are not supported by Cesium yet. (only polygons and points)
If you want to test it yourself just draw a line and a polygon on the map.

@oterral Do you know when/if line will be supported in a near future?

Also tooltip on GeoJSON doesn't work

**Comment by oterral** [comment]
Yes same issue. Don't know when it will be fixed.

**Comment by oterral** [comment]
Official Cesium issue to watch : https://github.com/AnalyticalGraphicsInc/cesium/issues/2172

**Comment by gjn** [comment]
@davidoesch Can we wait on Cesium (it's high priority for them...but you never know) or should we try to patch it.

**Comment by davidoesch** [comment]
we await cesium.  neede for go live BETA

**Comment by davidoesch** [comment]
we awit for the cesium patch, -review and of 2016

**Comment by gjn** [comment]
We need to push AGI a little. ClampToGround does not seem to work yet for lines.

**Comment by davidoesch** [comment]
Can you @gjn ask / post this issue in the corresponding cesium github?

**Comment by oterral** [comment]
Seems to be fixed. Line appears in 3d.

**Comment by davidoesch** [comment]
Not on mobile... Now we have even webgl crashes.
![screenshot_20170425-161143](https://cloud.githubusercontent.com/assets/4577727/25389961/4d855e12-29d2-11e7-84ba-3c74e3276fca.png)
![screenshot_20170425-161322](https://cloud.githubusercontent.com/assets/4577727/25389962/4d86a63c-29d2-11e7-91ed-29134948a77a.png)

**Comment by oterral** [comment]
@davidoesch  does it work with this [branch](https://mf-geoadmin3.int.bgdi.ch/fix_3104/index.html?lang=fr&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&dev3d=true&debug&layers=ch.bafu.hydroweb-warnkarte_national&lon=9.08401&lat=47.09691&elevation=4729&heading=0.047&pitch=-40.572) ?

**Comment by davidoesch** [comment]
partially -- 
lakes yes river not always 

![image](https://cloud.githubusercontent.com/assets/4577727/25428265/a043430a-2a75-11e7-89c1-c3bfc36c5d48.png)

**Comment by davidoesch** [comment]
correction: it works
just have to zoom realy reayll close
