### ISSUE TITLE
Missing tranlation

### ISSUE THREAD

**Issue by cedricmoullet** [geoadmin/mf-geoadmin3#3105]
https://map.geo.admin.ch/?topic=ech&lang=fr&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bafu.wrz-wildruhezonen_portal,ch.swisstopo.swisstlm3d-wanderwege,ch.swisstopo-karto.hangneigung&layers_visibility=false,false,false,false,true&layers_timestamp=18641231,,,,&catalogNodes=457,508&layers_opacity=1,1,1,1,0.2

![image](https://cloud.githubusercontent.com/assets/319676/12709974/b9f15d04-c8b1-11e5-95ae-cdbe85145585.png)

**Comment by ltclm** [comment]
translation has not yet been deployed to prod. will be done tomorrow.

https://mf-geoadmin3.dev.bgdi.ch/?topic=ech&lang=fr&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bafu.wrz-wildruhezonen_portal,ch.swisstopo.swisstlm3d-wanderwege,ch.swisstopo-karto.hangneigung&layers_visibility=false,false,false,false,true&layers_timestamp=18641231,,,,&catalogNodes=457,508&layers_opacity=1,1,1,1,0.2

**Comment by oterral** [comment]
Deployed on prod
