### ISSUE TITLE
3D search - marker is not visible after moving

### ISSUE THREAD

**Issue by cedricmoullet** [geoadmin/mf-geoadmin3#3115]
Chrome  48.0.2564.82 on windows 10
Start https://mf-chsdi3.int.bgdi.ch/shorten/69d11c5039
Search for "La Berra"
Select "La Berra (FR) - La Roche"
Marke is not visible in view
![image](https://cloud.githubusercontent.com/assets/319676/12774464/6e47ee32-ca45-11e5-905d-f8548f5c3f31.png)

**Comment by oterral** [comment]
Something strange the marker is displayed but not where the map is zooming.

**Comment by cedricmoullet** [comment]
yes, exactly

**Comment by cedricmoullet** [comment]
related to the new terrain ?

**Comment by oterral** [comment]
Yes probably it seems all zooming after a search is not centered on the marker.

**Comment by loicgasser** [comment]
What about new Cesium?

**Comment by loicgasser** [comment]
I think it's related to the Cesium update:
[See new terrain without Cesium update](https://mf-geoadmin3.dev.bgdi.ch/gal_new_terrain/)

**Comment by oterral** [comment]
Same errors

**Comment by oterral** [comment]
When zooming we use the height service to get the altitude instead of using terrain. I guess the problem  comes from there.

**Comment by loicgasser** [comment]
my browser is a mutant cause I see the point everytime not exactly centered but pretty close.

**Comment by gjn** [comment]
`my browser is a mutant`

Truer words have never been spoken. It's true for any browser.
