### ISSUE TITLE
Wohnung register: Inconsistency between WMS amd WMTS 

### ISSUE THREAD

**Issue by oterral** [geoadmin/mf-geoadmin3#3116]
- Open https://mf-geoadmin3.int.bgdi.ch/?topic=schneesport&lang=fr&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.bfs.gebaeude_wohnungs_register&X=180951.41&Y=575882.84&zoom=12
---> No orange points

 -  Zoom out ----> orange points appears

@ltclm @gjn @AFoletti   wms deploy issue ?

**Comment by ltclm** [comment]
Obviously this is a data import issue. @beat-github will ask the data owner why we don't get this data anymore and if our sql query needs to be adapted.

**Comment by ltclm** [comment]
the points are now visible.
