### ISSUE TITLE
zeitreise_ blinking tiles when no map and play 

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3118]
If you start from scratch at the beginning , the previous bg layer or no scale layer blinck always where you have no map and you are in play mode

https://map.geo.admin.ch/?topic=ech&lang=de&bgLayer=voidLayer&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bafu.wrz-wildruhezonen_portal,ch.swisstopo.swisstlm3d-wanderwege&layers_visibility=true,false,false,false&layers_timestamp=18531231,,,&X=213687.22&Y=700881.87&zoom=5&time=1853

**Comment by gjn** [comment]
@oterral will explain technical details.

**Comment by oterral** [comment]
Issue cretaed on openlayers https://github.com/openlayers/ol3/issues/5269

**Comment by gjn** [comment]
PR is open.
