### ISSUE TITLE
Set iframe width by default to width="100%"

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3121]
Set iframe width by default to width="100%" fo all sizes, since most use case are covered like this

thoughts on that?

**Comment by gjn** [comment]
Not sure. Depending on how it's integrated in the page, it might have an impact.

@oterral ?

**Comment by davidoesch** [comment]
me not sure as well --- so far most sides I've seen so far would be better off with 1oo% ... just athought

**Comment by oterral** [comment]
The size of the iframe is the responsability of the container. I don't think we should do that.

**Comment by davidoesch** [comment]
OK agree --- was just a thought
