### ISSUE TITLE
on topic change : reset layer selection

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3122]
on topic change : reset layer selection - do not copy existing active layers.

as discussed.

**Comment by loicgasser** [comment]
+1 it's too messy with preselected layers now.

**Comment by mariokeusen** [comment]
+1 had another customer complaining about this topic-change behaviour

**Comment by gjn** [comment]
Also remove wms/kml layers?

**Comment by davidoesch** [comment]
IMHO yes. This is restart of the  site. clean slate. user can always go back with the browser history

**Comment by gjn** [comment]
No, go back with browser history does not work. We have stateless SAP page - no browser history of state.

Do we keep a drawing?

**Comment by davidoesch** [comment]
Browser back: topic change works. Drawing deletion as well : clean slate.

**Comment by gjn** [comment]
`Browser back: topic change works.` ? which browser?

**Comment by gjn** [comment]
ah, i think you mean the topic reset by clicking on the bund logo, right? yes, this trigger a new page load.

But the topic switch via the topic menu does not trigger a page load and therefore there's no 'go back' from browser history to previous topic.

**Comment by gjn** [comment]
[Testlink](https://mf-geoadmin3.dev.bgdi.ch/gjn_topicchange/)

See #3145 for PR.

**Comment by davidoesch** [comment]
@mariokeusen can you test as well? On mobile it works as discussed.

**Comment by mariokeusen** [comment]
Works fine for me (tested on chrome). On this occasion I would also update the top-layers in the default-ech-catalog according to the stats from 2015:
![toplayers15](https://cloud.githubusercontent.com/assets/4577749/13101183/923e394a-d544-11e5-9207-caa426c9c422.PNG)

Not sure if it's really helpful to take the tlm-map, because it's "half" a bg-layer. I'd go with the following top 3 "data" layers:

- wanderwege
- zeitreihen
- swissboundaries-land

What do you think @davidoesch @gjn ?

**Comment by davidoesch** [comment]
Carefull with stats. One step after the other- first we see how we solved the related tickets. Then we go ahead with a global solution for all topics

**Comment by mariokeusen** [comment]
Ok, I'd drop those proposal layers anyway. But I know: usability....

**Comment by AFoletti** [comment]
It's minor, but when you change the topic there are some "leftovers" of the old one in the URL. Namely layers_visibility and layers_timestamp when switching away from eCH
