### ISSUE TITLE
Misconfiguration for background layer in 3d 

### ISSUE THREAD

**Issue by oterral** [geoadmin/mf-geoadmin3#3123]
Probably a problem in the bod.

https://mf-geoadmin3.dev.bgdi.ch/?lang=fr&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&dev3d=true&debug&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bafu.wrz-wildruhezonen_portal,ch.swisstopo.swisstlm3d-wanderwege&layers_visibility=false,false,false,false&layers_timestamp=18641231,,,&lon=8.57383&lat=46.91513&elevation=2813&heading=0.350&pitch=-39.348

**Comment by ltclm** [comment]
the background layers are not yet finished, i just started them today.

**Comment by oterral** [comment]
Fixed on prod thx @ltclm
