### ISSUE TITLE
Statify layer.json for layers

### ISSUE THREAD

**Issue by gjn** [geoadmin/mf-geoadmin3#3130]
Statify the 3d layer.json definitions for the following layers:

`ch.swisstopo.swissimage-product_3d`
`ch.swisstopo.swisstlm3d-karte-farbe_3d`
`ch.swisstopo.swisstlm3d-karte-grau_3d`

Remove the layer.json usage for the other 3 layers from here:
https://github.com/geoadmin/mf-geoadmin3/blob/master/src/components/map/MapService.js#L944

**Comment by loicgasser** [comment]
I was 2 minutes faster. same prio and assignee
Duplicate of https://github.com/geoadmin/mf-geoadmin3/issues/3129

**Comment by gjn** [comment]
:)
