### ISSUE TITLE
Draw mobile ngeo

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/mf-geoadmin3#3132]
I came accross this test link on ngeo for the mobile draw.

I personnally think it's aweswome and think we could use ngeo code for that.

https://adube.github.io/ngeo/mobile-measure/examples/contribs/gmf/mobilemeasurelength.html

@davidoesch @cedricmoullet @gjn @oterral

**Comment by cedricmoullet** [comment]
If the overhead is not too high, I completely agree.

2016-02-10 13:42 GMT+01:00 Gasser Loïc <notifications@github.com>:

> I came accross this test link on ngeo for the mobile draw.
>
> I personnally think it's aweswome and think we could use ngeo code for
> that.
>
>
> https://adube.github.io/ngeo/mobile-measure/examples/contribs/gmf/mobilemeasurelength.html
>
> @davidoesch <https://github.com/davidoesch> @cedricmoullet
> <https://github.com/cedricmoullet> @gjn <https://github.com/gjn> @oterral
> <https://github.com/oterral>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geoadmin/mf-geoadmin3/issues/3132>.
>



-- 
Twitter: http://twitter.com/cedricmoullet
Linked In: http://www.linkedin.com/in/cedricmoullet

<http://twitter.com/cedricmoullet>

**Comment by davidoesch** [comment]
Come on guys : drawing/measuring  with moving the map instead of the pencil /point is sth gis experts can work but not the standard user. And it is completely different to desktop behavior. I agree that we should improve drawing/measuring on touch devices (not only "mobile"). Here the solution from Basel stadt is more b convincing

**Comment by loicgasser** [comment]
This has been designed mor touch devices only. It s a solution that is out there at least.

**Comment by loicgasser** [comment]
Do you prefer this kind of solutions?
http://m.scribblemaps.com/
google maps does for touch devices?
do you have an exemple I d be intrested.

**Comment by loicgasser** [comment]
The baselstadt:
http://www.stadtplan.bs.ch/geoviewer/

you just can t move the map. how are you supposed to even draw a line?
If I put it to the test the tool that let s me draw a line along a road is with moving map.

**Comment by davidoesch** [comment]
+1 for scribble maps (It is intuitive and close to desktop behavior). Google : open mymaps.google.com on mobile device. 

For moving a map while drawing a line : touch and hold (as you do on desktop)

**Comment by oterral** [comment]
Scribble maps: you can't move the map when you draw, it's unusable on mobile. This site is done for annotation not measure or drawing a long path or a polygon.

stadtplan.bs.ch: I don't see the difference with what we have. When  drawing it's the same behavior.

**Comment by davidoesch** [comment]
open https://www.google.com/mymaps  on mobile it is as we do, but only the the map is moved if you reach the border of the map window while tap and hold...

**Comment by oterral** [comment]
@davidoesch can we close this one since the new draw is on line?
