### ISSUE TITLE
Add error message when files service return 404

### ISSUE THREAD

**Issue by oterral** [geoadmin/mf-geoadmin3#3134]
If a user has an `adminId` but the file doesn't exist anymore, the `files`service returns 404. It will be great if the app warn the user his file has been deleted

**Comment by loicgasser** [comment]
+1 but this also means we have to keep a reference of the deleted files in dynamodb
also 410 would more approriate

probably better to open this issue in CHSDI

**Comment by loicgasser** [comment]
410 Gone
Indicates that the resource requested is no longer available and will not be available again. This should be used when a resource has been intentionally removed and the resource should be purged. Upon receiving a 410 status code, the client should not request the resource again in the future. Clients such as search engines should remove the resource from their indices.[46] Most use cases do not require clients and search engines to purge the resource, and a "404 Not Found" may be used instead.

**Comment by procrastinatio** [comment]
Hm, we use 2 interfaces to get a file from it's `adminId`:
- First the `file`service returns the `fileId`correcsponding to the `adminId`
- Then try to get the file itself directly in the S3 bucket. S3 response is only `200` or `404`.

If we want to keep track of disappearing files (i.e. `410`), we have to use the `file`service for both actions (and update the service).

So worth it ? For the record, every day we have about 35'000 requests on the `file`service, compare to only 1'000 requests for files directly in the S3 bucket.

**Comment by oterral** [comment]
404 is enough for me .

**Comment by procrastinatio** [comment]
OK, so this is correct:
`$ curl -I http://api3.geo.admin.ch/files/666`
`HTTP/1.1 404 Not Found`

But this should be `404` right ?:
`$ curl -I http://public.geo.admin.ch/files/666`
`HTTP/1.1 403 Forbidden`

**Comment by loicgasser** [comment]
This bucket is not protected with the refferer? Otherwise I would say yes this should be 404. I have the same experience lately with the vector bucket. I opened an issue in Jira for Andrea. I could also mention the public bucket.

**Comment by procrastinatio** [comment]
@loicgasser It's public, there no check. But this is an S3 peculiarity: if your profile has no `GetObjectList` credential, you get an `403`instead of an `404`trying to access an unexisting ressource. It's just a matter of adding this credential.

**Comment by procrastinatio** [comment]
OK, done on AWS S3 side

`$ curl -I http://public.geo.admin.ch/666`
`HTTP/1.1 404 Not Found`

**Comment by oterral** [comment]
Not yet handle on mf-geoadmin side

**Comment by loicgasser** [comment]
sorry did know there was anything you wanted to do front end.

**Comment by oterral** [comment]
With https://github.com/geoadmin/mf-geoadmin3/pull/3669 . KML are not deleted anymore.
