### ISSUE TITLE
propagate the settings state in the permalink

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3143]
propagate the settings state in the permalink

If settings are open:
![Alt text](https://monosnap.com/file/h8fEzGQnVgYNBQTOPMlR3EHNW6RoyR.png)

then keep this state in the PL

@gjin @cedricmoullet : your thoughts?

**Comment by gjn** [comment]
You mean the state (open/close) of the layer manager?

**Comment by gjn** [comment]
And if we do it, why not state for whole menu?

**Comment by gjn** [comment]
We also currently have some logic that when a layer is added, the layermanager is open. Does this not work in some cases?

**Comment by vasile** [comment]
Yap, the state of each layer (collapsed, expanded). It's easier to tell the story, now I have to send visual information to my followers :) https://twitter.com/vasile23/status/699539183015215104

**Comment by gjn** [comment]
Not a big fan of this. When we have something in the PL, we have to support it from here on out. (see for instance the openNode pl entry). It will make the PL longer (it's already too long for most of us) and I fear it will trigger still more state-saving features through PL.

Even though I can understand @valile's use case.

**Comment by gjn** [comment]
@vasile your use case might be better served with something like this: https://map.geo.admin.ch/?id=62&topic=ech&lang=en&bgLayer=ch.swisstopo.swissimage&layers=WMS%7C%7COrthofoto%20ZH%20Sommer%202014%2F15%20RGB%7C%7Chttp:%2F%2Fwms.zh.ch%2FOrthoZHWMS%3FSERVICE%3DWMS%7C%7Corthophotos&X=248570.00&Y=681836.00&zoom=10&swipe_ratio=0.43

**Comment by vasile** [comment]
Yay, that's much more visually appealing @gjn, thanks!
I can live with that for now :)
