### ISSUE TITLE
Post message of kml id/name on click

### ISSUE THREAD

**Issue by gjn** [geoadmin/mf-geoadmin3#3146]
Currently, in iframe mode, we post a message containing the id of the clicked element to the parent page.

This functionality should be extended. When a kml is integrated in the page and the user clicks on an placement of the kml, the name/id of the clicked element should be send.

@oterral Possible? Effort?

**Comment by oterral** [comment]
I guess we can retrieve the all feature without too much effort

**Comment by loicgasser** [comment]
http://api3.geo.admin.ch/examples/geoadmin_iframe.html

Example the geojson layers.  Code is in MapService it's something like 5 lines.

**Comment by gjn** [comment]
PR ready, waiting for feedback.

**Comment by gjn** [comment]
Decided between @davidoesch and @cedricmoullet to keep it simple as possible. We will send name tag of document/folder for the 'layerid' and the placement/feature name tag as the 'featureid'.

**Comment by gjn** [comment]
This is live. Documentation will be added next week. I'll close this.
