### ISSUE TITLE
kml/json option to not show tooltip on click only highlight

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3152]
#gjin: to be carefully thought about

**Comment by cedricmoullet** [comment]
I can see the following approaches:
- New permalink parameter: layers_click_behaviour 0: standard, 1: event only, 2: tooltip+event only 3: highlight+event only, 4: tooltip and highlight+event, per layer
- New permalink parameter: layers_no_tooltip: 0 or 1 per layer
- New permalink parameter: no_tooltip: true of false

**Comment by gjn** [comment]
KISS for me. Option 3. (always number lists)

Also, a) non-official, b) not documented, c) must be added by hand and maybe d) can be revoked/changed any time.

**Comment by davidoesch** [comment]
Number 3: but document it not in the official help - at least I a way we won't forget that this feature exits when we do the next migration.

**Comment by gjn** [comment]
This can be closes as the new parameter (notooltipo=true) parameter exists. See referenced PR and https://codepen.io/geoadmin/pen/yOBzqM?editors=0010
