### ISSUE TITLE
[topic change] wildruhezonen-layer is missing in wildruhezonen topic when coming from ech

### ISSUE THREAD

**Issue by mariokeusen** [geoadmin/mf-geoadmin3#3153]
UC: open app with standard ech catalog, look at the layer selection, change topic to wildruhezonen
Result: in ech the layer Wildruhezonen is present in the layer selector (but not loaded), after the change of the topic this layer has disappeared and is NOT loaded to the map (as necessary on the start of the topic=wildruhezonen)
Expected: When switching to the Wildruhezonen-topic, both layers Wildruhezonen and Wildschutzgebiete must be loaded to the map
![bugontopicchangewrz](https://cloud.githubusercontent.com/assets/4577749/13135278/7fac1e20-d60f-11e5-9e12-5b80279db598.PNG)

Remark: if you start the other way round (with map.wildruhezonen.admin.ch), it's the same problem: when you switch to ECH, the layer Wildruhezonen disappears from the layer selector. I suppose this is a general issue, in case you have the same layer in the layer selector of the previous and of the next topic on topic change.

**Comment by mariokeusen** [comment]
In case of Wildruhezonen this is a pretty severe one, therefore prio 1

**Comment by mariokeusen** [comment]
and this is probably related to https://github.com/geoadmin/mf-geoadmin3/issues/3122

**Comment by loicgasser** [comment]
```json
{
defaultBackground: "ch.swisstopo.pixelkarte-farbe",
plConfig: null,
selectedLayers: [
"ch.bafu.wrz-wildruhezonen_portal",
"ch.bafu.wrz-jagdbanngebiete_select"
],
backgroundLayers: [
"ch.swisstopo.swissimage",
"ch.swisstopo.pixelkarte-farbe",
"ch.swisstopo.pixelkarte-grau"
],
langs: "de,fr,it,en,rm",
activatedLayers: [ ],
id: "wildruhezonen"
},
```

You can see that these layers should be indeed both selected per default from the service.

**Comment by gjn** [comment]
Agree, prio 1. I'm having a look.

**Comment by gjn** [comment]
on-garanteed handling of the same event. on topic change, we now do alot of things, among others A) remove all layers, as part of #3122 and B) add default topic layers.

It's just that the order of execution of A) and B) is not garantueed.

Fix is coming and will be deployed as part of sonnendach release this afternoon.

**Comment by mariokeusen** [comment]
Ok, thanks for the quick fix!

**Comment by gjn** [comment]
It's on prod.
