### ISSUE TITLE
[topic selector] order of topic types

### ISSUE THREAD

**Issue by cedricmoullet** [geoadmin/mf-geoadmin3#3155]
![image](https://cloud.githubusercontent.com/assets/319676/13143940/822a5f6c-d647-11e5-8077-61060af86bde.png)

we will solve this as well midterm by: #3157

**Comment by cedricmoullet** [comment]
@mariokeusen ?

**Comment by mariokeusen** [comment]
@AFoletti ?

**Comment by mariokeusen** [comment]
Please reorder the topics according to the following order also because we'll publish the new topic cadastre with the next deploy:
1 blue topics (federal offices)
2 green topics (specialized topics)
3 red topics (general catalogs)

**Comment by davidoesch** [comment]
Now cadastre is wrong as well

thereofore
Please reorder the topics according to the following order also because we'll publish the new topic cadastre with the next deploy:
1 blue topics (federal offices) and ALPHABETICALLY
2 green topics (specialized topics) and ALPHABETICALLY
3 red topics (general catalogs) and ALPHABETICALLY

**Comment by davidoesch** [comment]
Green topics are not alphabetically ordered on mobile and desktop

**Comment by loicgasser** [comment]
On language change reorder topics? Would it not confuse people if we start moving the topics around?

**Comment by davidoesch** [comment]
The standard user will use only one language... So the topic is always at the same position

**Comment by oterral** [comment]
We have a problem here. Because we don't know which topics are blue, red or green in frontend. Any chance to add the info in the [topic](https://mf-geoadmin3.dev.bgdi.ch/ltteo/src/services) results.

**Comment by gjn** [comment]
We'll add needed infomration in topic service (topic group). Then we'll do ordering on client side.

**Comment by loicgasser** [comment]
fixed via https://github.com/geoadmin/mf-geoadmin3/issues/3155
