### ISSUE TITLE
Topic and single Topic

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3157]
Situation
- topic: current topic selector is growing - on desktop a scrolling is now needed
- Single topics as shown in www.geo.admin.ch on footer based https://docs.google.com/spreadsheets/d/11zjWdLgaCZWiFhB8kP2AWhOb9vKBqLuXeXDPTSd4rDk/edit?pli=1#gid=0  should be intgerated as well

Task:
-merge single topics  and topics to have them in map.geo.admin.ch and www.geo.admin.ch

Action: (tbd)

map.geo.admin.ch
- topics selector
- [ ] make three lines, scrollable horizontally
- [ ] first line BLUE topics and the end the RED ones
- [ ] Second line GREEN topics
- [ ] Third line Single topic maps as in https://docs.google.com/spreadsheets/d/11zjWdLgaCZWiFhB8kP2AWhOb9vKBqLuXeXDPTSd4rDk/edit?pli=1#gid=0 

www.geo.admin.ch
add the GREEN, RED BLUE as well in a divider (see example fanguin)

Result: tipic selection in map and www are synced

@gjn @cedricmoullet  feedback?

**Comment by gjn** [comment]
+1.

**Comment by cedricmoullet** [comment]
I like the idea to synch both.
But I don't get how the single topics will be integrated in map.geo.admin.ch
(from design perspective). Do you have a mockup for desktop and mobile ?


2016-02-19 8:51 GMT+01:00 Gilbert Jeiziner <notifications@github.com>:

> +1.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geoadmin/mf-geoadmin3/issues/3157#issuecomment-186107206>
> .
>



-- 
Twitter: http://twitter.com/cedricmoullet
Linked In: http://www.linkedin.com/in/cedricmoullet

<http://twitter.com/cedricmoullet>

**Comment by davidoesch** [comment]
they are just images with a permalink as they do currently exits at the bottom of www.geo.admin.ch.

**Comment by cedricmoullet** [comment]
yes, ok. But how do you integrate this in the UI of map.geo.admin.ch ?

2016-02-19 11:05 GMT+01:00 David Oesch <notifications@github.com>:

> they are just images with a permalink as they do currently exits at the
> bottom of www.geo.admin.ch.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geoadmin/mf-geoadmin3/issues/3157#issuecomment-186147515>
> .
>



-- 
Twitter: http://twitter.com/cedricmoullet
Linked In: http://www.linkedin.com/in/cedricmoullet

<http://twitter.com/cedricmoullet>

**Comment by davidoesch** [comment]
Horizontal slider. As in www.geo.admin.ch

**Comment by cedricmoullet** [comment]
On mobile ?
Do you really want to use such a big space of the screen ?

2016-02-19 11:40 GMT+01:00 David Oesch <notifications@github.com>:

> Horizontal slider. As in www.geo.admin.ch
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geoadmin/mf-geoadmin3/issues/3157#issuecomment-186164684>
> .
>



-- 
Twitter: http://twitter.com/cedricmoullet
Linked In: http://www.linkedin.com/in/cedricmoullet

<http://twitter.com/cedricmoullet>

**Comment by gjn** [comment]
It's topic selection - rarely or never used.

**Comment by davidoesch** [comment]
half a year later: topic selector is even bigger now. 2 complaints this weeks regarding this
For the mockup: desktop: see the description above. we keep it in three lines. Mobile: alphabetical sorting

**Comment by gjn** [comment]
ping @pfanguin

**Comment by gjn** [comment]
These are 2 issues. Will split them out.

**Comment by loicgasser** [comment]
> make three lines, scrollable horizontally
> first line BLUE topics and the end the RED ones, Second line GREEN topics

We need to extend the topic service for that. I propose a new attribute called `topicGroup`.

**Comment by mariokeusen** [comment]
This is getting some more relevance, since we'll have two additional topics to come in the next few weeks: geodesy and emapis. Means: would be one additional line on desktop with the current selector layout.

**Comment by davidoesch** [comment]
ping @gjn

**Comment by loicgasser** [comment]
PR for horizontal scrolling is ready, but please describe second part.

> Third line Single topic maps.

@davidoesch 

This is still not clear. Those are simply layers belonging to different topics.
I think it's great to have images that are easy to browse and understand but you also understand that with the current topic restrictions/implementation this is not doable as is.

Why not put all the layers that belong to ech (which we could add in all topics and we treat them as a layer only) in a another panel or modal  you could browse. At the end of the layer manager for instance. (top layers or something)

or remove all the topics restrictions....

**Comment by loicgasser** [comment]
Note that if you treat those as a topic they also need a catalog, a topic entry and so on....

**Comment by davidoesch** [comment]
Third line:
Those are simply URLS. I propose that switching to those topics just loads the permalink. No resticton for the needed. So they are actually all ech topics ... 
Question: would we need to configure them via the topic spreadsheet?

**Comment by loicgasser** [comment]
no they don't belong all to ech at least natively but ok:
https://s.geo.admin.ch/6ba218a46f which is a link for the accidents map

This is what topics are based on
http://api3.geo.admin.ch/rest/services

and then everything is based on topics.
https://api3.geo.admin.ch/1610261737/rest/services/blw/CatalogServer?lang=fr
https://api3.geo.admin.ch/1610261737/rest/services/blw/SearchServer?searchText=acciden&lang=fr&type=layers
etc...

> Question: would we need to configure them via the topic spreadsheet?

We would need to change the topics service (e.g. http://api3.geo.admin.ch/rest/services) and therefore the spreadsheet. So yes doable via spreadsheet.

Maybe if we separate the names and ids, adapt a bunch of code in geoadmin we can do it. I guess you have the plConfig parameter in mind we used for schneesport topic.

But know that technically we first switch to schneesport topic and then apply the permalink parameters.
So you actually can't provide a topic in the link with `topic=...`

We need a proper id for those as well. A `proxy topic` if you prefer.

Also backward compatibility during deploy is gona be fun to ensure.
So those are not simply URLs...

**Comment by loicgasser** [comment]
Question: on mobile we had those to the select box? It's something like 30 new entries.

**Comment by loicgasser** [comment]
I am making some tests, but these are really two separate issues.

**Comment by davidoesch** [comment]
I see all your points: Question is: how would you, from tech perspective implement a quick access in Topic selctor to URLS?

**Comment by loicgasser** [comment]
I did find something pushing in a few minutes.

**Comment by loicgasser** [comment]
I am basically falling back on the main topic of interest where needed and building a topic configuration identical to the `topicFallback` expect for permalink configuration. Good thing is that we still have new topic names in the permalink. complexity is growing though.

**Comment by davidoesch** [comment]
one interesting approach would be to use subdomains like adminboundaries.map.geo.admin.ch for SEO good for SSL mmgt a nightmare @gjn ?

**Comment by loicgasser** [comment]
closed via https://github.com/geoadmin/mf-geoadmin3/issues/3612
