### ISSUE TITLE
add what3words in tooltip

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3158]
Using http://developer.what3words.com we could add this coordinate info in the position tooltip.
If no what 3 words I'd available show a dash.
Coverage of what 3 words is not yet clear
Swiss search should accept w3w as well....
Any thoughts on that?

**Comment by vicchi** [comment]
Hi @davidoesch - in my day job I'm CTO for what3words; can you clarify what you mean by "coverage is not clear"? We have global coverage for 3 word addresses, so if you're reverse geocoding a long/lat to a 3 word address you should never have an "unavailable" 3 word address (you'll only get an invalid return if you're forwards geocoding a non-existent 3 word address).

**Comment by davidoesch** [comment]
Hi vicchi , by coverage I mean : is there a density /heatmap of w3w for Switzerland available?

**Comment by vicchi** [comment]
Ah! Now I see what you mean. No, there's not such a thing, but even if there was all you'd end up with is a pixellated polygon that corresponds to the country border.

To explain further; when I said in my previous post that we have global coverage, I was being quite literal. The what3words algorithm covers the entire surface of the globe, both land and sea, in a 3m x 3m grid. Each of these 57 trillion squares has a 3 word address assigned. So we have 3 word addresses for every 3m x 3m grid square for the entirety of Switzerland and for every other country in the world, as well as the seas, oceans, rivers, lakes and so on.

From this I hope you can see that a heat map or density map of Switzerland would effectively cover the entirety of the country's area, becoming slightly blocky and pixellated where the border exists.

Hopefully this makes things a little bit clearer and allays your concerns/questions? If not, feel free to ask as many questions as you like, either here or to gary at what3words dot com.

**Comment by davidoesch** [comment]
I have to be more precise:
I'm aware that for every 3x3m you guys have a coordinate, my question was targeting- how many custom 3 words you already sold in switzerland ...

@vicchi: since we run our portal in 5 languages : we need Multingual support, that means w3w in up to 5 languages
- German
- French 
- Italian
- English
- Rumantsch Grischun (a nice to have , see http://www.pledarigrond.ch/rumantschgrischun/ and https://en.wikipedia.org/wiki/Romansh_language#Rumantsch_Grischun

**Comment by vicchi** [comment]
Thanks @davidoesch ...

To support our built in error detection and to maintain consistency of 3 word addresses when used offline, we don't provide or support "custom words"; see our [knowledge base](https://support.what3words.com/hc/en-us/articles/203437482-Can-I-buy-my-own-words-or-change-some-of-the-words-) for some more background on this. Once finalised, the list of 3 word addresses per language are fixed and won't change.

As of the time of writing, we support English and have support for 9 other languages; [German, French and Italian](https://support.what3words.com/hc/en-us/articles/203105501-How-many-languages-are-you-in-) are in beta and more are in our release schedule.

I have to admit that Rumantsch Grischun is a new language to me but I've passed this onto our language/internationalisation team to see if this is already on their radar.
