### ISSUE TITLE
Saucelabs improvements

### ISSUE THREAD

**Issue by alcapat** [geoadmin/mf-geoadmin3#3173]
Link to https://github.com/geoadmin/mf-geoadmin3/pull/3144
- [ ] Use API_URL/rest/services instead of topic list (hard coded)
- [ ] use quote from urllib2 if possible and put something human readable (some humans only)

**Comment by gjn** [comment]
@procrastinatio and @pfanguin will help to advance this.

Focus is to add support IE and safari.

**Comment by gjn** [comment]
@alcapat I close this as most things are done now.
