### ISSUE TITLE
loading topics without default layers 

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3177]
The current behavior of topics without default layers on topic start is IHMO not optimal. Like this, the user does not obviously see, that there are specific topic data in the catalog, he first has to open the catalog. 
UC: open map.geo.admin.ch and switch e.g. to sachplan and look at the catalog section

Expected result: the user is guided to the dataset. on shortterm if selection is empty open the  topic tree on load

**Comment by davidoesch** [comment]
linked to #3122

**Comment by mariokeusen** [comment]
Whom to assign? @gjn?

**Comment by davidoesch** [comment]
Tbd

**Comment by loicgasser** [comment]
> Expected result: the user is guided to the dataset. on shortterm if selection is empty open the topic tree on load

I guess you mean catalog tree.

**Comment by davidoesch** [comment]
catalog tree of the topic yes

**Comment by gjn** [comment]
This has been done in #3232
