### ISSUE TITLE
profile is not displayed when drawing new line feature

### ISSUE THREAD

**Issue by ltclm** [geoadmin/mf-geoadmin3#3188]
Situation:
* open map.geo.admin.ch -> draw & measure
* draw a new line
* click on tab profile

the profile tab is empty.
![image](https://cloud.githubusercontent.com/assets/5286659/13525391/ed10b2ee-e200-11e5-8619-1cd08dae5b83.png)

 If you add an additional vertex it will be drawn.
![image](https://cloud.githubusercontent.com/assets/5286659/13525404/030eb762-e201-11e5-8e66-e757390f344f.png)

issue has been reported by customer via webgis mailbox.

**Comment by gjn** [comment]
Was introduced by https://github.com/geoadmin/mf-geoadmin3/commit/ccd14f621021d7a7e5bb3273b4e63a846c683168 via https://github.com/geoadmin/mf-geoadmin3/pull/3100
