### ISSUE TITLE
catalogue eCH -inspire

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3191]
All dataset in eCH have to be as well in inspire. It has to be at least a 1:n relation ship

**Comment by mariokeusen** [comment]
Steps to do: 

- a comparison of contents of ech and inspire catalogues in order to find out, which layers are missing in inspire
- determination of INSPIRE class basing on ech for this list of layers
- completing the inspire catalog

I agree that this is a prio 3.

**Comment by mariokeusen** [comment]
Blocked in step 2 due to the non explicit information in geocat...

**Comment by loicgasser** [comment]
This is already the case ech layers are available in all catalogs. What do we need to do here? Is this on the catalog level?

**Comment by oterral** [comment]
Not a geoadmin3 issue. 1 year of standby ...

**Comment by davidoesch** [comment]
question of prio and geocat @mariokeusen pls move to jiira
