### ISSUE TITLE
Create new drawing object

### ISSUE THREAD

**Issue by cedricmoullet** [geoadmin/mf-geoadmin3#3193]
Some times, but not always, when a new object is created, then the dialog disappears immediately.

On chrome/windows

**Comment by gjn** [comment]
Can easily be reproduced:

add element and quickly move mouse -> dialog disappears
add element and wait, then move mouse -> dialog stays

Is probably related to the tooltip mouse click delay we did a couple of weeks ago.

I'll have a look tomorrow.

**Comment by gjn** [comment]
I tested version from Januar - bug is there.
I tested version from Octobre - bug is there.

Never had feedback of this from clients that I'm aware of - and people often use drawing. I'm downgrading.

**Comment by gjn** [comment]
@davidoesch @cedricmoullet I think this was fixed by the update of ol3. I can't reproduce this anymore in production. Please verify and close.

**Comment by cedricmoullet** [comment]
It works by me !
