### ISSUE TITLE
Line of sight icon: add eye in symbol

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3194]
now we have two distances which is which? I assum ethe second one is line of sight

therefore 

add

http://fortawesome.github.io/Font-Awesome/icon/eye/ 

before the icon 
![image](https://cloud.githubusercontent.com/assets/4577727/13643088/6f3e5bbe-e61f-11e5-8154-5573c39a7fa7.png)

**Comment by gjn** [comment]
I actually thought the first distance is 'distance on profile' and the second one 'flat distance'. Does 'flight distance' really make sense? For whom?

**Comment by davidoesch** [comment]
Flat distance? No it should be direct line/ line of sight
Am 10.03.2016 8:18 vorm. schrieb "Gilbert Jeiziner" <
notifications@github.com>:

**Comment by gjn** [comment]
By flat distance I meant the distance in x-direction of the profile diagram. By 'distance on profile' I meant distance as traveled on the profile.

I don't see a use case for direct line. Who could be interested in this?

**Comment by davidoesch** [comment]
Flatdistance is Luftlinie - I think we mean the same case: user is on
mountain A) and looks at mountain B) : how far away is it ? -> luftlinie .
it is what you measure on a map in 2d.
Second v use case: what is the walking distance on profile from mountain a)
to mountain B)
Am 10.03.2016 12:46 nachm. schrieb "Gilbert Jeiziner" <
notifications@github.com>:

**Comment by gjn** [comment]
I assumed luftlinie from start to end point.

**Comment by davidoesch** [comment]
Then we are aligned. @maria is investigating why we have cases where profile distance is shorter than flat distance
