### ISSUE TITLE
FF: select box does not work

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3197]
FF: select box does not work
Windows 10 mit Firefox 44 od. 45 => funktioniert nicht
Windows 7 mit Firefox 42 => funktioniert ebenfalls nicht

![unbenannt](https://cloud.githubusercontent.com/assets/4577727/13675432/d733efbe-e6e1-11e5-9505-5e44577cf989.png)

**Comment by gjn** [comment]
Funny, if you click long enough, it works.

**Comment by gjn** [comment]
Introduced by https://github.com/geoadmin/mf-geoadmin3/pull/3043 - many testers.

@Jenselme Could you have a look?

**Comment by Jenselme** [comment]
That's weird. I just had a quick look and I may have an explanation for this: on firefox, with the *pick an element from the page* tool, select the button which select/unselect an layer. In the DOM tree it selects the `span` just after the `input`. If you delete the `span`, the select button disappears.

On Chrome, with the same action, the `input` element is correctly selected and removing the `span` does nothing.

This also happens on a portal without D&D: https://map.geojb.ch/ but you couldn't notice this.

Continuing investigations…

**Comment by Jenselme** [comment]
The input is actually hidden on non webkit browser [app.less](https://github.com/geoadmin/mf-geoadmin3/blob/master/src/style/app.less#L1533), so slipjs doesn't detects the span as an input (which is logical) and so it doesn't behave correctly.

**Comment by gjn** [comment]
There must have been a reason why it's hidden in non-webkit browsers.

any way to patch slipsj or the app?

**Comment by gjn** [comment]
On IE, the input is also hidden, but the checkbox is working just fine. So slipjs detects this correctly on IE, but not on FF.

**Comment by Jenselme** [comment]
> On IE, the input is also hidden, but the checkbox is working just fine. 

On IE (at least IE on edge rendering), the input is displayed.

**Comment by gjn** [comment]
hmm. both IE11 and FF44 give the same back (in above test)

**Comment by Jenselme** [comment]
```patch
diff --git i/src/lib/slip.js w/src/lib/slip.js
index 9c5e3aa..aa9185d 100644
--- i/src/lib/slip.js
+++ w/src/lib/slip.js
@@ -131,7 +131,8 @@ window['Slip'] = (function(){
 
     var transitionPrefix = "webkitTransition" in testElement.style ? "webkitTransition" : "transition";
     var transformPrefix = "webkitTransform" in testElement.style ? "webkitTransform" : "transform";
-    var transformProperty = transformPrefix === "webkitTransform" ? "-webkit-transform" : "transform";
+    console.log(transformPrefix, "webkitTransform" in testElement.style, testElement.style);
+    var transformProperty = transformPrefix === "webkitTransform" ? "-webkit-transform" : "-moz-transform";
     var userSelectPrefix = "webkitUserSelect" in testElement.style ? "webkitUserSelect" : "userSelect";
 
     testElement.style[transformPrefix] = 'translateZ(0)';
```
or
```patch
diff --git i/src/lib/slip.js w/src/lib/slip.js
index 9c5e3aa..c3c5e67 100644
--- i/src/lib/slip.js
+++ w/src/lib/slip.js
@@ -131,7 +131,7 @@ window['Slip'] = (function(){
 
     var transitionPrefix = "webkitTransition" in testElement.style ? "webkitTransition" : "transition";
     var transformPrefix = "webkitTransform" in testElement.style ? "webkitTransform" : "transform";
-    var transformProperty = transformPrefix === "webkitTransform" ? "-webkit-transform" : "transform";
+    var transformProperty = transformPrefix === "webkitTransform" ? "-webkit-transform" : "";
     var userSelectPrefix = "webkitUserSelect" in testElement.style ? "webkitUserSelect" : "userSelect";
 
     testElement.style[transformPrefix] = 'translateZ(0)';
```
fixes it for Firefox. Forwarding that to upstream.

**Comment by davidoesch** [comment]
Yep many testers... But I did not test Firefox. The famous test book has to be updated

**Comment by Jenselme** [comment]
@davidoesch I tested with FF but I click on the label, not the checkbox.

**Comment by davidoesch** [comment]
With every function we add complexity of the app  increases with exponential power...

**Comment by gjn** [comment]
@Jenselme Correct fix would be to not only check for webkit, but also for moz on the test element to differentiate between firfox and IE.

**Comment by gjn** [comment]
@Jenselme it would be great if you could create a fix for mf-geoadmin3 and prepare an upstream PR for slipJS.

**Comment by Jenselme** [comment]
> @Jenselme Correct fix would be to not only check for webkit, but also for moz on the test element to differentiate between firfox and IE.

It seems to me. I proposed this solution upstream, without much success for now: https://github.com/pornel/slip/issues/66#issuecomment-195111974

> @Jenselme it would be great if you could create a fix for mf-geoadmin3 and prepare an upstream PR for slipJS.

In the meantime, I can make the fix for mf-geoadmin3 so you can deploy it next Wednesday (or before if you choose to).

**Comment by gjn** [comment]
ok. Thanks alot.
