### ISSUE TITLE
Drag/drop layers 

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/mf-geoadmin3#3203]
Got this error in the console. (prod version)

Uncaught TypeError: Cannot read property 'getZIndex' of undefined

**Comment by gjn** [comment]
Care to share a little more info that would help me to reproduce it?

**Comment by Jenselme** [comment]
I think that's a bug I already seen before DnD. Never managed to figure out its origin nor how to reproduce it.

**Comment by oterral** [comment]
An element of layers collection must [undefined](https://github.com/geoadmin/mf-geoadmin3/blob/master/src/components/layermanager/LayermanagerDirective.js#L263)

**Comment by oterral** [comment]
@loicgasser dis you succeed to reproduce?

**Comment by oterral** [comment]
Feel free to reopen if you see the bug again
