### ISSUE TITLE
Position/North orientation does not work correctly when in landscape 

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3204]
[map_geo_admin_ch-iphone-rotation.zip](https://github.com/geoadmin/mf-geoadmin3/files/171609/map_geo_admin_ch-iphone-rotation.zip)
Iphone assumed Latest Version/ Safari
"Leider funktioniert es auch nach einer Kalibration nicht, habe es auf mehreren iOS Geräten getestet. Vielleicht habe ich mich auch unklar ausgedrückt, es geht nicht um eine Ungenauigkeit in der Ausrichtung. Bei einer Rotation des Gerätes, bzw. beim Start im Querformat wird die Karte anschliessend um 90° gedreht angezeigt. "

**Comment by gjn** [comment]
@davidoesch Can we close this?

**Comment by davidoesch** [comment]
Close it only one customer reported this
