### ISSUE TITLE
Offline issues

### ISSUE THREAD

**Issue by gjn** [geoadmin/mf-geoadmin3#3205]
Several negative customer feedbacks regarding offline. Please read those mails.

**Comment by oterral** [comment]
Versions number are different on the 2 prod instances

https://map.geo.admin.ch/geoadmin.1457621062.appcache
https://map.geo.admin.ch/geoadmin.1457621381.appcache

Deploymant process problem.

**Comment by oterral** [comment]
KEEP_VERSION is set to false in deploysnapshot script https://github.com/geoadmin/mf-geoadmin3/blob/1ece67b62ec96af18b1433823087837b66f21b23/scripts/deploysnapshot.sh

**Comment by gjn** [comment]
I don't think that the KEEP_VERSION in the deploysnapshot.sh file is the problem. This is for the build
_in_ the snaphot. And here we want a new version every time before we deploy it. Idea is this:

1. build project in snapshot directory
2. rsync code to targets
3. rebuild only needed files, keeping the version intact. That's why KEEP_VERSION in rc_prod is true. But it seems that this is ignored in the hook https://github.com/geoadmin/mf-geoadmin3/blob/master/deploy/hooks/post-restore-code . Or maybe some dependencies in the Makefile does not work as we expect it to work.

I think this PR might fix it: https://github.com/geoadmin/mf-geoadmin3/pull/3200

**Comment by gjn** [comment]
KEEP_VERSION in snapshot script should probably use the export mechanism (so sub-process sees it). But this needs to be verified.

**Comment by gjn** [comment]
Ha. The scripts and hooks are working as expected. When we deploy to all target machines at once.

In the case where we step-by-step deploys (first on one, the on the other usign `make deployprod` twiche with changed targets in deploy.cfg, we end up with different versions on the targets. And this is exactly what I did last week when I emergency deployed the profile fix. I did this because https://github.com/geoadmin/mf-geoadmin3/pull/3200 was not addressed yet and wanted to avoid any downtime. Also, I remember that we did this a couple of times in the past.

#3200 should adress it. And we need to remember to _not_ separate our deployments in sub-steps.

All this will be moot when we're in S3 with this project.

**Comment by gjn** [comment]
This is fixed on production now as I deployed the latest snapshot, assuring same version on both instances. I've tested offline mode in firefox, and it's working fine.
