### ISSUE TITLE
White tiles

### ISSUE THREAD

**Issue by gjn** [geoadmin/mf-geoadmin3#3206]
On some browser, under some conditions, the application turns into a state were certain tiles always stay white. Zoomin and panning does not get rid of this effect. A re-launch of the application helps most of the time.

Thsi is very hard to re-produce, but customers continue to file reports to that effect.

Might be related to offline issues (and/or appcache)

**Comment by gjn** [comment]
Analyse impact of 500 errors of tiles on ol3.

**Comment by loicgasser** [comment]
@gjn Might be related https://github.com/openlayers/ol3/pull/4964

**Comment by gjn** [comment]
@loicgasser Good find! Might indeed be related.

Anyhow, still not able to reproduce, even when erratically zooming in and out as described in the bug description. But it also indicates that the ol3 internal tilecache might influence this.

I'll do some tests.

**Comment by gjn** [comment]
Bingo. I can easily reproduce when I reduce the cacheSize from the default 2048 to 16, [see here](https://mf-geoadmin3.dev.bgdi.ch/gjn_whitetiles_demo/). Zoom in wildly a couple of times, then you'll have those artefacts.

Putting the cacheSize to 0 does not help. In fact it gets worst.

I will tripple the cacheSize to mitigate the effect until PR in ol3 is merged. I count on @fredj!

PR coming.

**Comment by gjn** [comment]
@fredj Just a side question: what happens in the tilecache if a specific tile gets a 503 error once? Will it be re-requested if I do a simple zoom in/zoom out or will it stay marked as errounous in the tilecache?

**Comment by fredj** [comment]
@gjn the tiles will be re-requested; the response code is not stored

**Comment by gjn** [comment]
@fredj Thanks for the info!

**Comment by gjn** [comment]
Patch if deployed to prod. Anyhow, I keep this open for reference and wait for the ol3 patch to be integrated in mf-geoadmin3 (it's merged in ol3).

I'll downgrade to 2.

@davidoesch Please let me know if we get feedback regarding white tiles again.

**Comment by davidoesch** [comment]
OK will inform Helpdesk

**Comment by gjn** [comment]
See also 
https://github.com/openlayers/ol3/issues/4338
https://github.com/openlayers/ol3/pull/5270

**Comment by davidoesch** [comment]
Hi Gilbert
We have intranet and internet report that this issue increase more often in the last week
![image](https://cloud.githubusercontent.com/assets/4577727/22773569/26d5a1ec-eea3-11e6-8258-d267c8110a06.png)

-> ETA for this fix?
