### ISSUE TITLE
Haltestellen Icons in print are too small

### ISSUE THREAD

**Issue by gjn** [geoadmin/mf-geoadmin3#3208]
Print https://map.geo.admin.ch/?topic=ech&lang=de&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bafu.wrz-wildruhezonen_portal,ch.swisstopo.swisstlm3d-wanderwege,ch.bav.haltestellen-oev,KML%7C%7Chttps:%2F%2Fpublic.geo.admin.ch%2FKWeuzcQWTR-Ym5AC75rFQg&layers_visibility=false,false,false,false,true,true&layers_timestamp=18641231,,,,,&X=156837.50&Y=540762.50&zoom=8

Icons are too small.

**Comment by davidoesch** [comment]
same for the adressen... related to the resolution

**Comment by rfrancel** [comment]
@davidoesch do you mean the Wohnungsregister?

**Comment by davidoesch** [comment]
Yep, gwr

**Comment by gjn** [comment]
This is a basic issue we have with pre-generated tiles. Sizes (icons sizes, line widths, etc) on the tiles are created for 96DPI (our standard WMS setting) - optimized for web and computer screens.

In print, we are using 150DPI. So, for a given zoom level in the WMTS pyramid, the icons, line width etc are .064 the size as they appear in the web-viewer. We also have this issues on screens with > 96DPI resolution.

We could address this by using the WMS and specifying the new dpi in the request. This seems to be supported by MapServer. But this means upscaling our WMS and assure that all layers are accessible via WMS. This requires quite some work (but migth be needed for other projects in the pipeline).

@rfrancel Maybe for test purposes, you can try to use WMS instead of WMTS for haltestellen print.

http://freegis.org/pipermail/mapserver-de/2012-January/004527.html
http://mapserver.org/development/rfc/ms-rfc-55.html

**Comment by gjn** [comment]
The parameter `MAP_RESOLUTION` can be added to specify a different DPI for a given request:

[Default (96 dpi)](http://wms1.geo.admin.ch/?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=ch.bav.haltestellen-oev&LANG=de&WIDTH=532&HEIGHT=532&CRS=EPSG%3A21781&STYLES=&BBOX=701500%2C216780%2C706820%2C222100)

[Same Request with 300 dpi](http://wms1.geo.admin.ch/?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=ch.bav.haltestellen-oev&LANG=de&WIDTH=532&HEIGHT=532&CRS=EPSG%3A21781&STYLES=&BBOX=701500%2C216780%2C706820%2C222100&MAP_RESOLUTION=300)

**Comment by gjn** [comment]
Funny thing: when printing a WMS layer, the print server sends a request with a `DPI=150` parameter specified. But this parameter is ignored by our WMS server.

**Comment by procrastinatio** [comment]
Available options are (needless to say vendor specific):
```
DPI -> QGIS Server
MAP_RESOLUTION -> Mapserver
FORMAT_OPTIONS -> Geoserver
```
