### ISSUE TITLE
Firfox offline: does not work with 'never remember history'' privacy setting

### ISSUE THREAD

**Issue by gjn** [geoadmin/mf-geoadmin3#3212]
With FF45.

When Firefox is started with 'never remember history' privacy setting:
![image](https://cloud.githubusercontent.com/assets/2572317/13794680/759e87c6-eafd-11e5-97e9-c0a9332674bf.png)
then offline mode can be started, but the user can't download any maps. The following error message is show:
![image](https://cloud.githubusercontent.com/assets/2572317/13794831/48f2a706-eafe-11e5-983c-f1a5d285df41.png)
This does not help much because the user has no idea what's wrong. He can retry as many times as he wants and it won't work.

I think the error message should be more explicit, with eventuell link to help page that describes possible solutions. (privacy settings).

@pfanguin Can you start preparing a help page for offline issues and possible solutions?

**Comment by gjn** [comment]
We should also inform helpdesk about this. Offline mode needs to correct setting.

**Comment by davidoesch** [comment]
offline step by step instructions including caveats/faq/troubelshooting: http://de.slideshare.net/swiss_geoportal/mobilegeoadminch-re1/32 happy to add stuuf

**Comment by oterral** [comment]
@davidoesch can you add it in your doc?

**Comment by davidoesch** [comment]
since slideshare does not allow re- upload anymore I woudl loose the link

@danielabrandt : pls inform helpdesk and update doc
