### ISSUE TITLE
Change mouse icon on drag and drop

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3213]
As mentioned in #3209. Change mouse icon on drag and drop as in moving mails in Gmail with drag and drop

**Comment by Jenselme** [comment]
@davidoesch I am OK to do that.

But from what I see, gmail is using its own image for the cursor. Maybe we should just rely on `cursor:  grab` or `cursor: grabbing;`?

**Comment by davidoesch** [comment]
Cursor grab
