### ISSUE TITLE
Map is broken on chrome 49.0.2623.87

### ISSUE THREAD

**Issue by gjn** [geoadmin/mf-geoadmin3#3224]
The effect: when zooming and panning, the map starts flickering heavily. Simple pans look like an epileptic seizure.

Only observed on mentioned version on Windows 7.

Not observerd on FF and IE on same machine. Not observed on chrome 48 on working laptop - and obviously not observed during deploy process today on any other browsers.
It's not caused by our cacheSize fix https://github.com/geoadmin/mf-geoadmin3/pull/3210, as removing the fix does not help.

When I try with older version (r_160310), the effect is not there and all is smooth.

I suspect it's because of update of ol3: https://github.com/geoadmin/mf-geoadmin3/pull/3187. Official ol3 examples don't show this effect in this browser. Also, map.wanderland is working fine.

 I try to update ol3 now to latest official release and see the results.

**Comment by gjn** [comment]
Updating to official ol3 relase makes it even worse. Tiles are completely missing now. Still only in chrome 49. I've even re-installed it.

@davidoesch @cedricmoullet Can you try with chrome 49 to reproduce this?

**Comment by gjn** [comment]
Portable 48 next to protable 49. 48 good, 49 bad.

I need wood.

**Comment by gjn** [comment]
Couldn't be reproduced on mac chrome 49 and on bundeslaptops with chrome 49. Downgrading to prio2 now.

Also, effect is only visible with jpeg tiles, not with png tile (from the background, the pixelkarte has it, the tlm zoom leves, which are png, don't have it).

I now suspect driver issues on my laptop.

**Comment by gjn** [comment]
Update of graphic cards driver resolved the issue.

**Comment by loicgasser** [comment]
Yes but in general ol seem to have issues lately, I would not be surprised to have this one reopened.
