### ISSUE TITLE
api example "All available layers as WMTS" does not complete load 

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3233]
the All available layers as WMTS http://api3.geo.admin.ch/api/examples.html  :http://codepen.io/geoadmin/pen/MyYYXR?editors=0010
does not load in BV Net with chrome and firefox 

-> the list is just showing "....loading"

I assume it is just to much for teh weak BV net.... if it cant be fixed : reduce this example

**Comment by gjn** [comment]
Can't reproduce inside BV. Tried with IE11, FF and chrome and all are loading fine.

**Comment by davidoesch** [comment]
White screen on latest chrome in bv , works on IE
![unbenannt2](https://cloud.githubusercontent.com/assets/4577727/14318545/aabedb92-fc0d-11e5-8191-855cf7870894.PNG)

**Comment by gjn** [comment]
I suspect your laptop :=)

**Comment by oterral** [comment]
Reproductible when we load the codepen with https. Ther e was a js file which were not loaded with https. I've fixed this , that should work now. @davidoesch can you confirm?

**Comment by davidoesch** [comment]
Fixed...ok
Am 07.04.2016 9:03 vorm. schrieb "oterral" <notifications@github.com>:

**Comment by gjn** [comment]
Thanks @oterral .
