### ISSUE TITLE
3D : KML "cannot read property "_External" of null

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3236]
open on android 601 Nexus 6P
https://map.geo.admin.ch/mobile.html?topic=ech&lang=en&bgLayer=ch.swisstopo.pixelkarte-grau&X=203907.72&Y=727746.46&zoom=2&layers=KML%7C%7Chttps:%2F%2Fgist.githubusercontent.com%2Fdavidoesch%2F9998ebd0cb211c3ac674%2Fraw%2F8bb58435e664352d50b53999393c45b2570b0db9%2FGemeindeGeneralisiert.kml

got ot 3D 
result
3D : KML "cannot read property "_External" of null
![screenshot_20160317-215426](https://cloud.githubusercontent.com/assets/4577727/13944561/687095ae-f006-11e5-91b7-61eb7d3475e8.png)

can't even deactivate 3d afterwards

KML file to big for cesium ?

**Comment by oterral** [comment]
It works in [src mode](https://map.geo.admin.ch/src/mobile.html?topic=ech&lang=en&bgLayer=ch.swisstopo.pixelkarte-grau&X=203907.72&Y=727746.46&zoom=2&layers=KML%7C%7Chttps:%2F%2Fgist.githubusercontent.com%2Fdavidoesch%2F9998ebd0cb211c3ac674%2Fraw%2F8bb58435e664352d50b53999393c45b2570b0db9%2FGemeindeGeneralisiert.kml)

**Comment by davidoesch** [comment]
But data is not loaded... I assume it is the fix we expect from cesium for polygons

**Comment by oterral** [comment]
no,  polygons are displayed here but only in dev mode.

**Comment by gjn** [comment]
Missing export?

**Comment by oterral** [comment]
I suspect this indeed. I'nm on it.

**Comment by oterral** [comment]
See https://github.com/openlayers/ol3-cesium/issues/329

**Comment by gjn** [comment]
Good find. Let's patch it.
