### ISSUE TITLE
no map content and menu not translated

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3237]
Since the deploy of 16.3.2016 several users report

ios with SAFARI:

map.geo.admin.ch loads with
- no map shown ( just the grid backgroudn)
- menus are not translated (they see the untraslted technical msgid's)

Clearing the cache does not NOT help
reboot does NOT help

firefox and chrome do always work on the same device

**Comment by gjn** [comment]
I assumbe on desktop? Or is it mobile? Both?

Could anyone reproduce this? @oterral @cedricmoullet

**Comment by davidoesch** [comment]
Always desktop.

**Comment by oterral** [comment]
Can't reproduce on all our apple devices.

**Comment by oterral** [comment]
For me is clearly related to the problem of the 2 instances which had 2 differents version number.

**Comment by oterral** [comment]
@davidoesch . Having a look in webgis inbox it seems a lot of Safari issues comes from old Safari version (4 or 5 ), am I right?

**Comment by davidoesch** [comment]
well people are still calling me on the phone... this one is really nasty.

**Comment by oterral** [comment]
May you could ask them to use private mode to see if there is the same problem.

**Comment by davidoesch** [comment]
people on the phone confirmed that they are updating thier os and safaris... in the helpbox we have *only* old safari messages. Do we detect it right?

**Comment by fredj** [comment]
please not that Safari 4 doesn't have the `Array.isArray` function; it may be the cause of the issue

**Comment by oterral** [comment]
I've seen 2 messages on the mailbox. Don't forget you can't update all Phones to a better iOS version. Some are blocked.

**Comment by oterral** [comment]
Interesting @fredj that could explians some errors.

**Comment by oterral** [comment]
`requestAnimationFrame` is also not supported for safari <=5.1

**Comment by gjn** [comment]
In helpbox, the user agent is reported as the browser tells it. We don't mangle it or interpret it.

Safari 4 is as old as IE8. Safari 5.1 is 5 years old.
Are we sure those issues are only related to these old versions?

**Comment by gjn** [comment]
I can reproduce on Safari 5.1.7. It works well in source mode, but not in built mode. Here's the error:

![image](https://cloud.githubusercontent.com/assets/2572317/13978791/0e884496-f0d4-11e5-9852-356ac3b7c521.png)

So it seems related to `requestAnimationFrame`. But it doesn't explain why it works in source mode.

**Comment by gjn** [comment]
@fredj Any hint?

**Comment by gjn** [comment]
I think we need to adapt our polyfill for requestAnimationFrame.

**Comment by gjn** [comment]
For the mess, read up on https://gist.github.com/paulirish/1579671

We either have to use polyfill via CDN (breaking our CDN policiy) or use somthing from above. I try to come up with something.

**Comment by fredj** [comment]
Looks like the requestAnimationFrame polyfill is only loaded for IE
View source for https://map.geo.admin.ch/; `polyfill.min.js` is inside a `<!--[if IE]>` block

**Comment by gjn** [comment]
Yes. Working on different polyfill now.

**Comment by gjn** [comment]
I tried to use https://github.com/julienetie/request-frame/, but doesn't seem to play well with closure library in safari:

![image](https://cloud.githubusercontent.com/assets/2572317/13979655/33ea27ee-f0da-11e5-944e-e90e18d72447.png)

**Comment by gjn** [comment]
From CDN also has its troubles.

**Comment by oterral** [comment]
We could use the polyfill service  directly in the htmlpage :
https://cdn.polyfill.io/v2/polyfill.min.js?features=Array.isArray,requestAnimationFrame

and let him decide when the browser needs the function.

**Comment by gjn** [comment]
Yes, that's what I tried. But didn't work as expected. Same error as above with the request-frame module.

**Comment by gjn** [comment]
We don't want to depend on CDN anyhow. I'll update the polyfills by hand in the browsers. With https://cdn.polyfill.io/v2/polyfill.js?features=Array.isArray,requestAnimationFrame&flags=always,gated

PR coming.
