### ISSUE TITLE
KML doesn't print

### ISSUE THREAD

**Issue by gjn** [geoadmin/mf-geoadmin3#3238]
We are unable to print the following KML:

https://map.geo.admin.ch/?X=175395.18&Y=628772.90&zoom=7&lang=de&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=KML%7C%7Chttp:%2F%2Fwww.skitourenguru.ch%2Fcalc_data%2Fkml%2FSwitzerland_SnowRoute094.kml

@procrastinatio @mariavkourouni Could you have a look?

**Comment by Jenselme** [comment]
Just saw that issue. The KML is not valid. At line 1363, there is a line string but it contains only one points. The KML parser from MFP (v2 or v3) doesn't like that. Maybe do some KML validation on import? Or make MFP ignore invalid geometries?

**Comment by procrastinatio** [comment]
Yes, I confirm, many KML from this site have invalid geometries. 

It would be nice if the print server did ignore invalid geometries, but it would be better to check/correct such errors when importing into map.geo.admin.ch (its done through the `ogcproxy`) and inform the user why it fails to import or what has been corrected.

**Comment by oterral** [comment]
We have a [sanitizeFeatures](https://github.com/geoadmin/mf-geoadmin3/blob/master/src/components/map/KmlService.js#L116)  function in the `gaKml` service.  Function which close unclosed poylgon, so we could also add a coordinate to LineStrings which have one coordinate.

**Comment by davidoesch** [comment]
informed skitourenguru

**Comment by gjn** [comment]
Or remove the one-point line (as it doesn't make sense anyway).

**Comment by davidoesch** [comment]
Feeback from skitourenguru
"ich habe den Server nun aktualisiert. Meine KML sollten nun keine LineStrings mit nur einem Punkt enthalten."
