### ISSUE TITLE
Keep drawings and KML on topic change?

### ISSUE THREAD

**Issue by Jenselme** [geoadmin/mf-geoadmin3#3245]
Hi,

While preparing for a deploy of your latest updates for our client, we presented the [reset layer selection on topic change](https://github.com/geoadmin/mf-geoadmin3/issues/3122). Everybody agreed that the reset as a whole is a good idea to avoid the selection to get messy with time (we have many pre-selected layers in our topics). However, we found disturbing that the imported KMLs and drawings are also removed.

In an ideal world, we think that only the layers from the former topic should be removed. That means keeping KMLs, imported WMS, drawing and layers added by search. But it may be a bit complex to implement. A good compromise would be to keep:

- KMLs
- Drawings
- imported WMS layers

What do you think? I saw there was a discussion about in the PR about this feature. I can help implement that if accepted.

**Comment by gjn** [comment]
It was decided to remove everything. Topics are rarely switched, and those who switch expect a real reset.

@davidoesch ?

**Comment by davidoesch** [comment]
+1 to keep it KISS a real reset is the intention here. to treat now external ressources makes it more complicated
