### ISSUE TITLE
Offline issues

### ISSUE THREAD

**Issue by gjn** [geoadmin/mf-geoadmin3#3246]
Offline issues still persist for some clients. If found a few articles that might explain the issues:

[Fact sheet](http://appcache.offline.technology/)

[Why using prefer-online is a bad idea](http://labs.ft.com/2012/07/prefer-online-not-so-much/). I think the solution proposed here might be really useful.

[Appcache use cases and their problems](https://www.w3.org/community/fixing-appcache/2012/01/18/appcache_use_cases/)

[Gotchas on Firefox (scroll down)](https://developer.mozilla.org/de/docs/Web/HTML/Using_the_application_cache)

[More fun with appcache](https://eclecticdreams.com/blog/fun-times-with-appcache)

[Debugging appcache](https://jonathanstark.com/blog/debugging-html-5-offline-application-cache?filename=2009/09/27/debugging-html-5-offline-application-cache/)

[Debugging appcache in Firefox](http://flailingmonkey.com/application-cache-not-a-douchebag/)

Debugging appcache in Chrome with chrome://appcache-internals/

Then I have this message in Firefox45 when opening a page with appcache: `The Application Cache API (AppCache) is deprecated and will be removed at a future date.  Please consider using ServiceWorker for offline support.` So we might come to a state where appcache is not supported anymore on firefox.

**Comment by gjn** [comment]
I again did some detailed analysis. Here are some results.
Initial state is working appcache store with same version on all browsers. Now the version of the cache is updated an newly deployed. The user then loads the page again with good internet connection.

**Chrome 49** (win7):
`checking` is triggered, `obsolete` is triggered (404 on the appcache file). This triggers an automatic page reload. Page with new version is loaded, then new appcache is loaded next. Events triggered in the followin order:
`checking`, `downloading`, `progress` (for each file to download), `cached`. The page is up-to-date without any problems.

A next load with the new version: `checking` (200 on appcache file with no change) and `noupdate` events are triggered.

**IE 11** (win7):
Exact same behaviour as Chrome 49.

**Safari 9** (latest ios), **Safari 5** (win7), **Safari** (on iphone 4, ios8):
Exact same behaviour as Chrome 49.

**Android Browser 4.2** (on Galaxy S4):
Exact same behaviour as Chrome 49.

**

**Firefox 45** (win7, the funny one):
`checking` is triggered, `obsolete` is triggered (404 on the appcache file). This triggers an automatic page reload. So far it's the same as in the other browsers. But when the page reloads, there is `checking` and `error` event triggered (and another 404 on the old appcache file which is tried first). The new page is accessed after that (200 can be seen on server), but it's not used. Still old version is actually used in the browser (with old version number) and the old cached resources are used.

Another manual load of the page triggers the loading of the new page with all new resources - and the last file downloaded is the appcache. The same sequence of events are triggered as in the other browsers from now on.

This is bad behaviour, but it also suggests a simple page reload should be enough to address the problem (assuming good internet connection).

I try to impove the situation for Firefox without breaking the others.

**Comment by gjn** [comment]
Not that the above analysis didn't take care of spotty connections or didn't analyse offline behaviour at all. It just analysed behaviour with good internet connection.

A little history.
Offline was activated on 18.9.2014 for both desktop and mobile.

Offline was removed from desktop version on 25.9.2014.

The caching of the appcache file was changed on 17.2.2015 - as we assumed that browsers might have cached the appcache file. On the same date, we switched to a per-version appcache file.

**Comment by gjn** [comment]
PR posted to create better update mechanism for FF.

Anlysing further in Firefox the offline/online dynamic.

**Comment by gjn** [comment]
I found another potential problem, which is related to the fact that we include the appcache manifest on the mobile page, but not on the desktop page. Assuming the following workflow.

1) Mobile Page is loaded by user. Appcache is created, including the fallback to index.html (desktop version)
2) User is back on desktop version
3) We update the application n times (n > 0)
4) User never switches to mobile version again, thus appcache is still pointing to the version of point 1
5) User loads destkop version. He gets latest version.
6) User is offline and loads the desktop version -> he will get the version from appcache, created on 1, including the layersConfig etc.

This version created under 1) remainds as appcache version for as long as the mobile page is not loaded again. And this old page is loaded whenever the browser detects 'I'm offline' (whenever that might be).

I think this _might_ explain some other issues our clients are having.

@oterral Do you think it makes sense to put the appcache manifest in the desktop version again? (Of course, offline saving of cards would only work on mobile page)

**Comment by gjn** [comment]
Another think I've notices is the following: the appcache is not working when a user if offline and tries to access the page using `http`. It only works if he uses a linke with `https`. That means if the browser history is empty and he types `map.geo.admin.ch` in the browser, the page will not show up.

@davidoesch That's something the helpdesk should know. Manually putting https:// in front of the URL will help in offline mode.

**Comment by gjn** [comment]
This year, we also changed the http -> https redirection from apache level (back-end) to varnish level (front-end). This might have a side effect on the appcache as well.

**Comment by davidoesch** [comment]
gelpdesk instructed, their wiki updated

**Comment by gjn** [comment]
@oterral I've assigned this one to you because I think we need to address the issue of an outdated stored offline map.

We need to at least alert the user that he can't use his stored map anymore - or find a way that enables him to use it still.

It's about the timestamp that might change after an update and that makes the stored map 'disappear'.

That's high priority for me.

**Comment by davidoesch** [comment]
+1 the user has to be notified if there is new data available compared to what he has stored. This was and is a must condition for offline

**Comment by gjn** [comment]
The PR has been merged. So for now, I consider this solved on the next release.
