### ISSUE TITLE
current timestamp support

### ISSUE THREAD

**Issue by ltclm** [geoadmin/mf-geoadmin3#3253]
The current timestamp should be detected as valid timestamp [1].
Current should be supported in the timeslider and it should be displayed / chosen by default if timeBehaviour is 'last' or 'current'.

There is a test database containing  time-enabled pk25.noscale, pk50.noscale and pk100.noscale configuration `bod_ltclm_noscale_master`

[layersconfig](https://mf-chsdi3.dev.bgdi.ch/dev_ltclm_noscale_timeenabled/rest/services/ech/MapServer/layersConfig)

[1] https://github.com/geoadmin/mf-geoadmin3/blob/01f6041d71dbe390738e91e48e1aa1a071d88923/src/components/map/MapService.js#L869

**Comment by oterral** [comment]
Timeslider applies only ' real ' timestamp.

timeBehavior is never 'current' or am I missing something?

**Comment by ltclm** [comment]
current is a recently introduced real timestamp in s3. 
this timestamp should be supported by the timeslider
```
ch.swisstopo.swissimage: {
		attribution: "CNES, Spot Image, swisstopo, NPOC",
		background: true,
		searchable: false,
		format: "jpeg",
		hasLegend: false,
		serverLayerName: "ch.swisstopo.swissimage",
		selectbyrectangle: false,
		attributionUrl: "http://www.swisstopo.admin.ch/internet/swisstopo/de/home.html",
		timeBehaviour: "last",
		tooltip: false,
		label: "SWISSIMAGE",
		highlightable: true,
		chargeable: true,
		timestamps: [
			"current",
			"20151231",
			"20140620",
			"20131107",
			"20130916",
			"20130422",
			"20120809",
			"20120225",
			"20110914"
		],
```

**Comment by oterral** [comment]
When I meant real timestamp I meant a number

**Comment by ltclm** [comment]
@loicgasser @gjn 
The "current" timestamp has to be replaced with a number for the timeslider. Assuming that ``current`` represents the current year we see two options to realize that:

**a) new timeBehaviour ``current``**
this option needs modifications on client and server side. The new layers config response would look like that:
```
ch.swisstopo.swissimage: {
        attribution: "CNES, Spot Image, swisstopo, NPOC",
        background: true,
        searchable: false,
        format: "jpeg",
        hasLegend: false,
        serverLayerName: "ch.swisstopo.swissimage",
        selectbyrectangle: false,
        attributionUrl: "http://www.swisstopo.admin.ch/internet/swisstopo/de/home.html",
-->     timeBehaviour: "current",
        tooltip: false,
        label: "SWISSIMAGE",
        highlightable: true,
        chargeable: true,
        timestamps: [
-->         "20161231",
            "20151231",
            "20140620",
            "20131107",
            "20130916",
            "20130422",
            "20120809",
            "20120225",
            "20110914"
        ],
```
The timestamps value ``20161231`` will be generated dynamically using the current year. This value will be used client-side for the timeslider. If the timeBehaviour is ``current``, the client has to replace the latest timestamp ``20161231`` back to ``current`` to get the tiles.

**b) current replacement client-side**
We keep the layersconfig response and the timeBehaviour value as it is today:
```
ch.swisstopo.swissimage: {
        attribution: "CNES, Spot Image, swisstopo, NPOC",
        background: true,
        searchable: false,
        format: "jpeg",
        hasLegend: false,
        serverLayerName: "ch.swisstopo.swissimage",
        selectbyrectangle: false,
        attributionUrl: "http://www.swisstopo.admin.ch/internet/swisstopo/de/home.html",
        timeBehaviour: "last",
        tooltip: false,
        label: "SWISSIMAGE",
        highlightable: true,
        chargeable: true,
        timestamps: [
            "current",
            "20151231",
            "20140620",
            "20131107",
            "20130916",
            "20130422",
            "20120809",
            "20120225",
            "20110914"
        ],
```
If there is a ``current``  timestamp in the array, the client has to replace it with the current year's timestamp  ``20161231`` and use this value for the timeslider.

Do you see other options? What do you think? 
We can discuss tomorrow.

**Comment by loicgasser** [comment]
I think b) is easier and makes more sense as timestamps are used to configure the wmts I would not mix both.

**Comment by gjn** [comment]
b for me as well.
Am 28.04.2016 11:12 vorm. schrieb Clausen Marcel <notifications@github.com>:@loicgasser @gjn 
The "current" timestamp has to be replaced with a number for the timeslider. Assuming that current represents the current year we see two options to realize that:

a) new timeBehaviour current
this option needs modifications on client and server side. The new layers config response would look like that:

ch.swisstopo.swissimage: {
        attribution: "CNES, Spot Image, swisstopo, NPOC",
        background: true,
        searchable: false,
        format: "jpeg",
        hasLegend: false,
        serverLayerName: "ch.swisstopo.swissimage",
        selectbyrectangle: false,
        attributionUrl: "http://www.swisstopo.admin.ch/internet/swisstopo/de/home.html",
-->     timeBehaviour: "current",
        tooltip: false,
        label: "SWISSIMAGE",
        highlightable: true,
        chargeable: true,
        timestamps: [
-->         "20161231",
            "20151231",
            "20140620",
            "20131107",
            "20130916",
            "20130422",
            "20120809",
            "20120225",
            "20110914"
        ],


The timestamps value 20161231 will be generated dynamically using the current year. This value will be used client-side for the timeslider. If the timeBehaviour is current, the client has to replace the latest timestamp 20161231 back to current to get the tiles.

b) current replacement client-side
We keep the layersconfig response and the timeBehaviour value as it is today:

ch.swisstopo.swissimage: {
        attribution: "CNES, Spot Image, swisstopo, NPOC",
        background: true,
        searchable: false,
        format: "jpeg",
        hasLegend: false,
        serverLayerName: "ch.swisstopo.swissimage",
        selectbyrectangle: false,
        attributionUrl: "http://www.swisstopo.admin.ch/internet/swisstopo/de/home.html",
        timeBehaviour: "last",
        tooltip: false,
        label: "SWISSIMAGE",
        highlightable: true,
        chargeable: true,
        timestamps: [
            "current",
            "20151231",
            "20140620",
            "20131107",
            "20130916",
            "20130422",
            "20120809",
            "20120225",
            "20110914"
        ],


If there is a current  timestamp in the array, the client has to replace it with the current year's timestamp  20161231 and use this value for the timeslider.

Do you see other options? What do you think? 
We can discuss tomorrow.

**Comment by gjn** [comment]
@oterral Could you try to implement variant 2 for next deploy?

**Comment by oterral** [comment]
I'm not sure replacing automatically a 'current' value by an hardoced value is a good thing.

**Comment by ltclm** [comment]
Well it is a value representing the current year, what's so bad about that approach? it is just a timeslider compatible alias for ``current``.

**Comment by oterral** [comment]
What's happening next year ? do we modify manually the hardcoded value ?

**Comment by ltclm** [comment]
no, javascript can detect the current year and replace current with this value.

**Comment by ltclm** [comment]
its just for labeling the timeslider.

**Comment by loicgasser** [comment]
What do you mean by hardcoded?
I see something like gaTime.getCurrentYear() method. Then the problem is that in January 2017 it won't be true but it won't matter for the tiles as you already have the timestamp (e.g. Current). The only problem is maybe on the identify service and the Timeinstant.

The question is do we have a case where we're using both the current timestamp and the identify service with a Timeinstant param ? Do we want to support such a case ?

If we do this backend you could send the 'current' keyword timestamp as a Timeinstant param that I would convert to 

> currentYear - 1

Couldn't we ue the newly created Cacheservice to determine the current year value ?

**Comment by oterral** [comment]
My problem is like you said " in January 2017 it won't be true" , for us may be it's ok for Datenherr I'm not sure.

**Comment by oterral** [comment]
and if the data are not updated in 5 year , the time slider always display 2017 and the data are from 2012.

**Comment by loicgasser** [comment]
we use current only for data that is updated often (every 6 months or so at most) right @ltclm 

FYI: @oterral http://api3.geo.admin.ch/services/sdiservices.html#cache-update

**Comment by ltclm** [comment]
@loicgasser yes, current is used only for data which is updated often.

**Comment by gjn** [comment]
@oterral has a point. It's about maintenance.

We should carefully choose which layers do actually support `current`, and in which services we support it. Haveing `current` for wmts address only is much different than having `current` for the dataset and other services.

@ltclm We have `current` now for pixel/raster data only, right?

**Comment by ltclm** [comment]
yes, we only have it for raster data.
```sql
select distinct fk_dataset_id  from tileset where timestamp = 'current';
                fk_dataset_id
----------------------------------------------
 ch.swisstopo.pixelkarte-farbe-pk25.noscale
 ch.swisstopo.swisstlm3d-karte-grau.3d
 ch.swisstopo.pixelkarte-farbe-pk100.noscale
 ch.swisstopo.pixelkarte-farbe-pk500.noscale
 ch.swisstopo.pixelkarte-farbe-pk50.noscale
 ch.swisstopo.pixelkarte-farbe
 ch.swisstopo.pixelkarte-farbe-pk200.noscale
 ch.swisstopo.swissimage-product
 ch.swisstopo.pixelkarte-grau
 ch.swisstopo.pixelkarte-farbe-pk1000.noscale
 ch.swisstopo.swisstlm3d-karte-farbe
 ch.swisstopo.swisstlm3d-karte-grau
 ch.swisstopo.swissimage
 ch.swisstopo.swisstlm3d-karte-farbe.3d
(14 rows)
```
what's the point?

**Comment by gjn** [comment]
The point is that it doesn't impact other services as identify, find, htmlpopup etc as we don't have geometries in the db for this layer. So we can exclude these concerns for this discussion.

As this currently concerns only regularely updated swisstopo data, I propose to implement b).

**Comment by ltclm** [comment]
i see, that's a good point!
because some of these layers (the timeenabled noscale layers) will have tooltips ...

**Comment by loicgasser** [comment]
Can I take care of it @oterral ? I should be quite trivial.

**Comment by oterral** [comment]
sure you can.

**Comment by ltclm** [comment]
Besides the ``current`` use-case which whe have discussed yesterday with @gjn @procrastinatio @oterral @loicgasser and me we will soon have the following requirement.

There are some layers with **gaps in the timeline**. we should be able to fill these gaps without generating physical tiles (what we have incorrectly done for the fruitcake layer). 
So to solve the ``current``  and the ``fill-the-gaps``problem i propose, based on our discussion:

* Introduce a new time behaviour ``mapped``
* the layers config for the **current use-case** would look like:
```
ch.swisstopo.swissimage: {
        attribution: "CNES, Spot Image, swisstopo, NPOC",
        background: true,
        searchable: false,
        format: "jpeg",
        hasLegend: false,
        serverLayerName: "ch.swisstopo.swissimage",
        selectbyrectangle: false,
        attributionUrl: "http://www.swisstopo.admin.ch/internet/swisstopo/de/home.html",
        timeBehaviour: "mapped",
        tooltip: false,
        label: "SWISSIMAGE",
        highlightable: true,
        chargeable: true,
        timestamps: [
            "current",
            "20151231",
            "20140620",
            "20131107",
            "20130916",
            "20130422",
            "20120809",
            "20120225",
            "20110914"
        ],
        timestamps_mapped: [
            ["20161231"],
            ["20151231"],
            ["20140620"],
            ["20131107"],
            ["20130916"],
            ["20130422"],
            ["20120809"],
            ["20120225"],
            ["20110914]"
        ],
```
* the attribute **timestamps** has an array of timestamps which **are used in our services** (wmst, identify,..)
* the new attribute **timestamps_mapped** has an array of arrays of timestamps, these timestamps **are used to configure and label the timeslider**
* the layers config for the **fill the gaps use-case** . The layer has a gap between 2015 and 2010. In the timeslider would like to show the year 2010 for this years. The layers config would look like: 
```
ch.swisstopo.swissimage: {
        attribution: "CNES, Spot Image, swisstopo, NPOC",
        background: true,
        searchable: false,
        format: "jpeg",
        hasLegend: false,
        serverLayerName: "ch.swisstopo.swissimage",
        selectbyrectangle: false,
        attributionUrl: "http://www.swisstopo.admin.ch/internet/swisstopo/de/home.html",
        timeBehaviour: "mapped",
        tooltip: false,
        label: "SWISSIMAGE",
        highlightable: true,
        chargeable: true,
        timestamps: [
            "2016",
            "2015",
            "2010",
            "2009",
            "2008"
        ],
        timestamps_mapped: [
            ["2016"],
            ["2015"],
            ["2014","2013","2012","2011"],
            ["2010"],
            ["2009"],
            ["2008"]
        ],
```

That's a proposition how to face these use-cases with the same approach. 
your input, feedback is very welcome.

**Comment by oterral** [comment]
Why do we need to fill these gaps ?

**Comment by gjn** [comment]
It's better explained with a whiteboard.

Possibly, there are other ways to achieve the same.

**Comment by procrastinatio** [comment]
@ltclm Not really sure about these **gaps**. We are starting to display false informations: if we have dispalyed year **2015**, I expect to have data ranging from 1.1.205 to 31.12.215, not 2011.

A better approach in my opinion, would be to use **time range**, and displaying all availlable in that range. No timestamp in that range, so layer is not displayed. By default it is *one* year  (as now) but may be set to many years. Clearer for the user, easier for us too.

Time ranges has also the advantage of beeing usable with smaller time intervals (month, week, day) , which, despite all what has been said, will have to be implemented (Murphy lässt sich grüssen)

**Comment by gjn** [comment]
We will deploy temporary solution #3314 and then discuss in detail the other use cases, the gaps and time range.

**Comment by ltclm** [comment]
@gjn do you want to keep this issue opened?
