### ISSUE TITLE
[SHOP] - Missing translations

### ISSUE THREAD

**Issue by p1d1d1** [geoadmin/mf-geoadmin3#3255]
Labels on some geological maps are not translated.
e.g. https://mf-chsdi3.int.bgdi.ch/shorten/6af1e3e9c0

**Comment by gjn** [comment]
Coul you specify all layers which miss translations?

**Comment by gjn** [comment]
Will also be ok once we are on prod. Sorry for the confusion. And thanks for testing!

**Comment by gjn** [comment]
@rfrancel Can you prepare a testlink to wms integration to verify that wms on integration is good?

**Comment by rfrancel** [comment]
If you change the language it works fine.

https://wms-bgdi.int.bgdi.ch/?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=ch.swisstopo.gkt500-papierkarte.metadata&CRS=EPSG%3A21781&STYLES=&WIDTH=739&HEIGHT=493&BBOX=420000%2C30000%2C900000%2C350000&lang=fr

De : Gilbert Jeiziner [mailto:notifications@github.com]
Envoyé : mercredi 30 mars 2016 10:06
À : geoadmin/mf-geoadmin3 <mf-geoadmin3@noreply.github.com>
Cc : Francelet Rebecca swisstopo <Rebecca.Francelet@swisstopo.ch>
Objet : Re: [geoadmin/mf-geoadmin3] [SHOP] - Missing translations (#3255)


@rfrancel<https://github.com/rfrancel> Can you prepare a testlink to wms integration to verify that wms on integration is good?
