### ISSUE TITLE
Language sensitive WMS should react on language change

### ISSUE THREAD

**Issue by gjn** [geoadmin/mf-geoadmin3#3258]
See https://github.com/geoadmin/mf-geoadmin3/pull/3257

Language sensitive [WMS layers](https://map.geo.admin.ch/?topic=ech&lang=fr&bgLayer=voidLayer&layers=ch.swisstopo.gkwvul500-papierkarte.metadata&X=162992.61&Y=649885.70&zoom=3) should react on language change.

@mariokeusen @davidoesch I let you choose the priority. A fix is currently deployed that will show correct language on page start or when layer is first added. But this issue still remains (language change by user).

Also, the fix deployed does not work in 3D.

**Comment by davidoesch** [comment]
For me this is solved with this fix. A workaround exists. Pareto.
