### ISSUE TITLE
Tooltip shop layer does not work in search result

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3261]
search for gk 200
 select (i) button for gk 200 Papier 

->nothing happens

**Comment by rfrancel** [comment]
If I select gk200 papier the layer appears, and if search and select a number of map (1 or 4), it selects and zooms on the selected feature. The tooltip and the shop button work too when I do this..  Can you explain more precisely what you tried?

**Comment by loicgasser** [comment]
info button in search result works for me as well.

**Comment by davidoesch** [comment]
Funny cant reproduce today and yesterday but i could before
