### ISSUE TITLE
LUBIS: while panning all data loads

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3262]
load LUBIS time enabled
https://map.geo.admin.ch/?topic=swisstopo&layers=ch.swisstopo.lubis-luftbilder_schwarzweiss,ch.swisstopo.lubis-luftbilder_farbe&lang=de&bgLayer=ch.swisstopo.pixelkarte-farbe&layers_timestamp=19451231,&catalogNodes=1430&X=249620.00&Y=690750.00&zoom=6&time=1945

then pan

result: while panning ALL data is loaded

**Comment by gjn** [comment]
Can't reproduce in chrome and FF.

**Comment by davidoesch** [comment]
Yep, stopped thsi afternoon, but was the case this morning on IE  FF anc chrom, confimred by @mariokeusen
