### ISSUE TITLE
need to work without 204 varnish translations

### ISSUE THREAD

**Issue by danduk82** [geoadmin/mf-geoadmin3#3267]
Hello,
to go-live with cloudfront for the tiles, we really need to fix the need of translating any S3 response codes with 204 (which is now the case).

We cannot (or I should say: we **should** not) put Varnish behind cloudfront, but directly an S3 bucket. Cloudfront will then forward the same response code as S3, i.e. :

- 403 for almost anything
- >500 ? 

Therefore, I have created the addresses wmts[5-9].dev.bgdi.ch that do not filter S3 response code. 

Cheers
Andrea

**Comment by gjn** [comment]
I've deployed a [Branch for Testing](https://mf-geoadmin3.dev.bgdi.ch/gjn_wmtserrors)

For reasons unknown to me, no tiles are loaded when using chrome based browsers (chrome, brave) or FF based. Requests are send out, response codes look good (200, 403, etc), but the response itself is empty. Can you reproduce it chrome?

In IE11, it's working.

Regarding the errors: they are now clearly visible in the console/network tab - and they are really annoying as they create alot of noise; potentially masking relevant errors. Generally, we tried to avoid having any errors in the console.

[Cloudfront offers](http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/custom-error-pages.html#custom-error-pages-response-code) some response codes handling - and I would prefere to keep the any-to-204 handling we have.

I'm sure there are other ways to get real S3 response codes, both now and with Cloudfront.

@danduk82 @hpchrist @cedricmoullet I would like your feedback regarding this.

**Comment by danduk82** [comment]
Interesting bug. I agree with translating all to 204 with cloudfront. Anyway I want to see if I missed something in the varnish config for these tiles.

I have to test to see if in the cloudfront logs there is a trace of the real backend return code.

Andrea

**Comment by fredj** [comment]
@gjn in https://mf-geoadmin3.dev.bgdi.ch/gjn_wmtserrors, the tiles are not display because the CORS header is missing (`Access-Control-Allow-Origin`)

**Comment by danduk82** [comment]
I know,
I have just set this : set beresp.http.Access-Control-Allow-Origin = "*";

I was waiting for my testing machine to finish before deploying it on stable

**Comment by danduk82** [comment]
@gjn @fredj , the new config is applied on varnish. Now it works.

It's insane that IE accepts this kind of requests...

Andrea

**Comment by gjn** [comment]
Yep, working fine. But I don't think we can get rid of the 204 (or similar) responsed. I think it's a good idea to analyse how we will handle it with cloudfront.

thanks alot @danduk82 for this test.

**Comment by danduk82** [comment]
@gjn did you fix something in the application anyway? I don't see the famous "red tiles" in corrispondence with 403 accesses, which means it works anyway. Did you?

**Comment by gjn** [comment]
No changes. Application is current master with different URL for wmts tiles.

What 'red tiles'?

**Comment by danduk82** [comment]
I remember that some application displayed red squares where the tiles were not loaded, but I may confuse with another application.

**Comment by fredj** [comment]
@danduk82 you're right: OpenLayers 2 displayed pink squares

**Comment by gjn** [comment]
Aaah. Good old ol2.

It was also possible to specify a MAX_RETRY for each tile. @fredj Any change for something similar in ol3?
(I know about the refresh, but this applies to all tiles of a layer).

**Comment by danduk82** [comment]
> OpenLayers 2 displayed pink squares 
I guess this is the original reason why all returns codes are transformed in 204, isn't it?

**Comment by fredj** [comment]
The reason for HTTP 204 instead of 404 or 403 is to hide loading errors from the console / debugger

**Comment by danduk82** [comment]
Ah ok. @gjn  so what, shall we stop thinking about this and just keep running with 204 translation? I will create a cloudfront distro for testing tiles with this translation.

**Comment by gjn** [comment]
Yes. Let's abandon that road for now. If we need specific errors, we can try to log them differently.

+1 for a any->204 test with cloudfront.
