### ISSUE TITLE
Iframe does not accept swipe

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3271]
Reproduce

Take 
https://map.geo.admin.ch/?topic=ech&lang=de&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.geologie-eiszeit-lgm-raster,ch.swisstopo.geologie-eiszeit-lgm,KML%7C%7Chttps:%2F%2Fpublic.geo.admin.ch%2FwwdHdWn-RVuqsMjwKS1HVw&X=191370.00&Y=759380.00&zoom=7&layers_visibility=true,false,false&swipe_ratio=0.59

go to embed

In the embed code / result
Swipe line does appear, but the LGM layer is not swiped
![unbenannt](https://cloud.githubusercontent.com/assets/4577727/14411918/0155c1b4-ff56-11e5-872a-80ea94a5a9d9.PNG)

**Comment by oterral** [comment]
You have a KML layer on top, so this is this layer which is swiped

**Comment by oterral** [comment]
https://map.geo.admin.ch/?topic=ech&lang=de&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.geologie-eiszeit-lgm-raster,ch.swisstopo.geologie-eiszeit-lgm&X=191370.00&Y=759380.00&zoom=7&layers_visibility=true,false&swipe_ratio=0.59

**Comment by davidoesch** [comment]
The issue was - the kml layer was not set active. But in the embed code it was active

**Comment by oterral** [comment]
in your link the kml visibility is set to false, but if you open it the kml is displayed. So the problem doesn't affect only iframe.

**Comment by oterral** [comment]
@davidoesch  [Test](https://mf-geoadmin3.dev.bgdi.ch/teo_fixes/?topic=ech&lang=de&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.geologie-eiszeit-lgm-raster,ch.swisstopo.geologie-eiszeit-lgm,KML%7C%7Chttps:%2F%2Fpublic.geo.admin.ch%2FwwdHdWn-RVuqsMjwKS1HVw&X=191370.00&Y=759380.00&zoom=7&layers_visibility=true,false,false&swipe_ratio=0.59)
