### ISSUE TITLE
iframe changes in preview are not taken into account

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3272]
go to
https://s.geo.admin.ch/6b2cae30ac

open Embed
go to preview
in preview zoom out and pan

copy result from preview URL window

result:
result in iframe is https://s.geo.admin.ch/6b2cae30ac

expected result:

zoom and pans in preview window are taken into account

**Comment by oterral** [comment]
I can understand the problem (google map iframe doesn't update the link too) but to fix this that needs a dirty communication between iframe and the parent window. I'm not sure we want this.

As workaround we could disallow navigation in the iframe modal

**Comment by gjn** [comment]
http://stackoverflow.com/questions/938180/get-current-url-from-iframe

we should be able to get url of iframe rather easy.

**Comment by oterral** [comment]
Yes but we still need to know when the url has changed and for that we need to listen some events from the child window.
We could detect mouse/keyboard/touch/wheel events on iframe but it seems not very robust.

**Comment by gjn** [comment]
Can't we read it when leaving the preview? No even on that?

**Comment by gjn** [comment]
This is live.
