### ISSUE TITLE
mobile: position does sometime not work

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3273]
Nexus P, latest chrome lates  android 6

reproduce
have a map.geo.admin.ch link stored on homescreen
start it from homescreen
navigate.
lock mobile
after a while ( 30min) unlock mobile
use the already open map application
try to position you
it gets youa nice position as shown in the image below: but the position is wrong, no error circle  but the arrow on the position point do turn if you turn as well

![unbenannt](https://cloud.githubusercontent.com/assets/4577727/14412318/579879d6-ff60-11e5-991b-d38ad2da2119.PNG)

workaround to fix it:

Close mpa.geo.admin.ch window, close all other chrome instances, reboot device

**Comment by oterral** [comment]
disabled then re-enabled the geoloc button doesn't fix the issue?

**Comment by davidoesch** [comment]
Nope

**Comment by gjn** [comment]
Is this sitll an issue?

Does other positioning enabled maps show correct position?
