### ISSUE TITLE
mobile: offline mode does not switch back

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3274]
android latest 6, nexus 6p, offline map stored, latest chrome

store map extent offline
set a link on homescreen
hike around , after a while activate link from home screen
although there is a god and constant 3g connection, app tells you that you are offline. at the same time if you do start map.geo.admin.ch in anew browser window, everything works fine

![unbenannt](https://cloud.githubusercontent.com/assets/4577727/14412376/afd05c58-ff61-11e5-9d84-04bf8df86ce6.PNG)

Workaround, reboot device

**Comment by oterral** [comment]
weird but can't reproduce

**Comment by davidoesch** [comment]
Just reproduced on Nexus 6p
![screenshot_20160715-105443](https://cloud.githubusercontent.com/assets/4577727/16873855/2148bfa4-4a96-11e6-93a1-d52561c0ef60.png)

**Comment by davidoesch** [comment]
Workaround: completey close all chrome windows. Then start link again from home screen

**Comment by gjn** [comment]
@procrastinatio has installed a spotty proxy. Maybe we can use this to reproduce.

**Comment by gjn** [comment]
We command a new Android device.

**Comment by oterral** [comment]
Possibly  related to https://github.com/geoadmin/mf-geoadmin3/pull/3751

**Comment by oterral** [comment]
Fell free to reopone if it happens again

**Comment by davidoesch** [comment]
well, for the moment I'm on iOS  ;-) and there it is perfect
