### ISSUE TITLE
[draw] script failure when draw mode is on and KML-data is loaded via URL

### ISSUE THREAD

**Issue by mariokeusen** [geoadmin/mf-geoadmin3#3275]
UC: click this permalink:
https://map.geo.admin.ch/?topic=ech&lang=de&bgLayer=ch.swisstopo.pixelkarte-grau&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bafu.wrz-wildruhezonen_portal,ch.swisstopo.swisstlm3d-wanderwege,KML%7C%7Chttp:%2F%2Fgeoshare.impulsthun.ch%2Fkml%2Fimpuls.kml,&layers_visibility=false,false,false,false,true,true&layers_timestamp=18641231,,,,,&X=178268.93&Y=614662.68&zoom=11&adminId=iZcLy04ISX6okEuwZYDk7Q

Result: in IE a script fails. Customer reported similar problems also for Chrome and FF.

**Comment by oterral** [comment]
Ther e is a extra comma at the end of the layer's name `....impuls.kml,`without it seems to work:

https://map.geo.admin.ch/?topic=ech&lang=de&bgLayer=ch.swisstopo.pixelkarte-grau&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bafu.wrz-wildruhezonen_portal,ch.swisstopo.swisstlm3d-wanderwege,KML%7C%7Chttp:%2F%2Fgeoshare.impulsthun.ch%2Fkml%2Fimpuls.kml&layers_visibility=false,false,false,false,true,true&layers_timestamp=18641231,,,,,&X=178268.93&Y=614662.68&zoom=11&adminId=iZcLy04ISX6okEuwZYDk7Q

**Comment by andreglauser** [comment]
Thanks for the Fix of this Problem. Unfortunately the comma after `...impuls.kml,` is generated by _Link to edit your drawing later:_ under _Draw and Measure on Map_.

**Comment by oterral** [comment]
Yes @andreglauser  fixed with https://github.com/geoadmin/mf-geoadmin3/pull/3278
