### ISSUE TITLE
[print] issue when printing drawings from KML generated with swissmapconverter

### ISSUE THREAD

**Issue by mariokeusen** [geoadmin/mf-geoadmin3#3276]
UC: open app, load a KML generated from an XOL with swissmapconverter. Print a PDF of the extent with the KML
Result: On the screen the lines are visualized smoothly, on the PDF the lines much fatter than on screen
Expected: looks more or less the same on screen and on the PDF
![print_kmlfromxol_symbology](https://cloud.githubusercontent.com/assets/4577749/14450779/b667ad52-0081-11e6-830c-791c5ee910b3.PNG)

**Comment by oterral** [comment]
KML file please @mariokeusen

**Comment by mariokeusen** [comment]
Requested that @helpdesk

**Comment by mariokeusen** [comment]
I could reproduce the issue with Chrome and IE11, with the original KML from the customer.
