### ISSUE TITLE
Offline Storage: browser vs homescreen link and external ressource 

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3277]
Android , Nexus P latest version

reproduce
A)on android load map.geo.admin.ch , create home screen link
B) on a desktop browser create a map, link an external kml , url ressource 
Create a qr code from the link in B)

on android , open qr code with qr droid. Chrome browser opens. store map with kml offline
result as expected:
![screenshot_20160412-082647](https://cloud.githubusercontent.com/assets/4577727/14453196/9aa2312a-0093-11e6-9395-744f67991b8d.png)

then close this browser window

open then the home scrreen link as in A) or enter when offline (airplane) https://map.geo.admin.ch
result:
offline bg map is saved, but not the kml:
![screenshot_20160412-082647](https://cloud.githubusercontent.com/assets/4577727/14453232/d1ed46ba-0093-11e6-9047-98855d9fa24f.png)

workaround:
use the link in the qr code: create a  NEW homescreen link from the browser, the both , bg and kml are available. there is a little quirk: the logo does not appear on start splash screen
![screenshot_20160412-082647](https://cloud.githubusercontent.com/assets/4577727/14453342/8414415e-0094-11e6-8234-ba256c2ba3da.png)

**Comment by oterral** [comment]
When you save A) in a home screen link, there is no KML defined in it so it's not normal it's not appearing when offline.

The stored content is displayed depending on what is defined in the permalink.

**Comment by davidoesch** [comment]
For the average user this is hard to understand: if I enter in offline map.geo.admin.ch I get all stored layers (BG and public transportation stop) but not the kml. So how do I get to display my track when I'm offline and I don't know my Permalink?
We are too complicated....

**Comment by oterral** [comment]
It's not complicated. You saved a link with layers so you have what you've saved. You ask for magic here. Imagine a user who save 2 links with 2 different KMLs. He doesn't want the 2 KMLs are displayed automatically in the 2 links.

The use case is: 
- the user opens chrome
- go to map.geo.admin.ch
- add a KML
- then save the link to the home screen

**Comment by davidoesch** [comment]
"then save the link to the home screen"
-> this has to be communicated to the user.

Brainstorming: what about adding to the confirmation window of offline when evrything is downloaded " please save the current URL to homescreen" is there a possibility to save it directly via an url? (for IOS I think there is not for android)

**Comment by oterral** [comment]
it seems it's a bad practice because we can't detect if it's a saved link or a chrome link:

See [best practices](https://developer.chrome.com/multidevice/android/installtohomescreen#best-practices) : 

> Do not prompt the user to add your app to the homescreen. There is no way to detect if the app is running installed or not

**Comment by oterral** [comment]
And in chrome the cache is shared between all saved link and that's a problem.

**Comment by gjn** [comment]
@davidoesch Good if we mark this 'won't fix'?

**Comment by davidoesch** [comment]
Won't fix- agree. We have a workaround
