### ISSUE TITLE
API URL via hidden permalink value

### ISSUE THREAD

**Issue by gjn** [geoadmin/mf-geoadmin3#3290]
I think to create testlinks for mf-chsdi3, it would make sense to be able to specify the API URL via hidden Permalink parameter. Therefore, you don't need to create a test-branch in mf-geoadmin3 to test mf-chsdi3 branches.

@rfrancel Could you give it a try?

**Comment by rfrancel** [comment]
Yes, I'll have a look at it, thanks!
