### ISSUE TITLE
[top4 layers] remove ch.bafu.wrz-wildruhezonen_portal from proposed layers in ech-topic

### ISSUE THREAD

**Issue by mariokeusen** [geoadmin/mf-geoadmin3#3293]
Due to a change in the layer stats and an input from the Wildruhezonen specialists, we (oed, kem) decided to remove this layer from the proposed layers in ech-topic.

**Comment by loicgasser** [comment]
Do we have a replacement?

**Comment by mariokeusen** [comment]
Either we go on with top-3 layers or we chose one of the other top layers from the latest wmts stats?
What do you think @davidoesch ?

**Comment by gjn** [comment]
haltestellen?

**Comment by davidoesch** [comment]
+1 push the haltestellen,

**Comment by mariokeusen** [comment]
Good idea, I think we can go with ch.bav.haltestellen-oev

**Comment by gjn** [comment]
@AFoletti Could you replace `ch.bafu.wrz-wildruhezonen_portal` with the `ch.bav.haltestellen-oev` layer for proposed layers of topic ech in the bod?

**Comment by AFoletti** [comment]
BOD changed and deployed to DEV
