### ISSUE TITLE
A3 landscape: coordinates not printed

### ISSUE THREAD

**Issue by oterral** [geoadmin/mf-geoadmin3#3297]
From helpdesk:

```
 Guten Tag,
Beim Drucken (erstellen des PDF) von "CadastralWebMap" wird das Koordinatennetz nicht dargestellt, sowohl wenn im Druckmenu angeklickt, als auch wenn separat aus dem Geokatalog ausgewählt und dargestellt..

Permalink: https://map.geo.admin.ch/?topic=ech&lang=de&bgLayer=voidLayer&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bafu.wrz-wildruhezonen_portal,ch.swisstopo.swisstlm3d-wanderwege,ch.kantone.cadastralwebmap-farbe,org.epsg.grid_21781&layers_visibility=false,false,false,false,true,true&layers_timestamp=18641231,,,,,&X=194681.25&Y=579171.25&zoom=12&catalogNodes=457,491.

User-Agent: Mozilla/5.0 (Windows NT 6.1; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; Tablet PC 2.0; rv:11.0) like Gecko

Application Version: 1461771594

```

**Comment by AFoletti** [comment]
That's wonderfully weird...

I printed out 44 different A3 pdfs with mixed results this morning. And I'm now unable to reproduce anymore.
Someone would like to test an A3 print of those permalinks?

https://s.geo.admin.ch/6bf31c21b3
https://s.geo.admin.ch/6bf31ff11f
https://s.geo.admin.ch/6bf31086cb
https://s.geo.admin.ch/6bf31086cb

**Comment by procrastinatio** [comment]
In case you wonder what the request is:

http://wms.geo.admin.ch/?BBOX=574477.7763923341,192991.1729166667,574680.6236076661,193128.22708333336&HEIGHT=1619&WIDTH=2396&CRS=EPSG:21781&MAP_RESOLUTION=150&SERVICE=WMS&REQUEST=GetMap&DPI=150&STYLES=,,,&TRANSPARENT=true&EXCEPTIONS=XML&VERSION=1.1.1&FORMAT=image/png&format_options=dpi:150&LAYERS=ch.swisstopo.swisstlm3d-karte-farbe.mapproxy,ch.kantone.cadastralwebmap-farbe,ch.bakom.mobil-antennenstandorte-umts,org.epsg.grid_21781&SRS=EPSG:21781

**Comment by AFoletti** [comment]
The problem looks to be bound to the image scale (you can get a correct image by juggling around wit the image WITH and HEIGHT in the above request) and / or size.

I just checked again the WMS code. No "hole" in the scale definition (there is no scale that can't be drawn)

**Comment by AFoletti** [comment]
Problem found and fixed... at the end, it was a hole in the scale definitions.
Exactly 1:500 and 1:1000 were not drawn (1:500,5 or 1:499,5 were ok...)
Well, I learnt something about WMS today.

Will be fixed on next deploy, or even today if @gjn allows me to do a WMS emergency deploy

**Comment by gjn** [comment]
@AFoletti is it deployed?

**Comment by AFoletti** [comment]
*censured*
I leaved earlier yesterday and I forgot it. Sorry.
I can deploy it this evening. Otherwise you will simply need to update the wms-bgdi project and deploy it (no need for a new translation)

**Comment by procrastinatio** [comment]
_never alone, never on friday_

**Comment by AFoletti** [comment]
It's thursday ;)
wms-bgdi is a simple component, but I agree: we have guidelines and we should stick to them.

**Comment by gjn** [comment]
Please do it next week during regular deploy.

**Comment by AFoletti** [comment]
fix is on prod
