### ISSUE TITLE
Stationboard: no results

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3300]
Hi Since Sunday 1.5.2016: the stationbaord as eg in

https://map.geo.admin.ch/?ch.bav.haltestellen-oev=8573055&lang=de&topic=ech&showTooltip=true&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.bav.haltestellen-oev,ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bafu.wrz-wildruhezonen_portal,ch.swisstopo.swisstlm3d-wanderwege&layers_visibility=true,false,false,false,false&layers_timestamp=,18641231,,,

does not give a result

**Comment by gjn** [comment]
Can't believe this...
Am 02.05.2016 8:23 nachm. schrieb David Oesch <notifications@github.com>:Hi Since Sunday 1.5.2016: the stationbaord as eg in

https://map.geo.admin.ch/?ch.bav.haltestellen-oev=8573055&lang=de&topic=ech&showTooltip=true&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.bav.haltestellen-oev,ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bafu.wrz-wildruhezonen_portal,ch.swisstopo.swisstlm3d-wanderwege&layers_visibility=true,false,false,false,false&layers_timestamp=,18641231,,,

does not give a result

**Comment by loicgasser** [comment]
seems like the departure table is empty:

```sql
uvek_master=> SELECT count(*) FROM bav.oev_departures;
 count 
-------
     0
(1 row)
```

**Comment by loicgasser** [comment]
It seems ok in dev, I could deploy the dev tables to prod as temporary measure

```sql
uvek_dev=> SELECT count(*) FROM bav.oev_departures;                                                                                                                                                          
  count  
---------
 8560169
(1 row)
uvek_dev=> SELECT time FROM bav.oev_departures ORDER BY time DESC LIMIT 1;
        time         
---------------------
 2016-05-06 08:41:00
(1 row)
uvek_dev=> SELECT time FROM bav.oev_departures ORDER BY time ASC LIMIT 1;
        time         
---------------------
 2016-05-02 00:00:00
(1 row)
```

**Comment by loicgasser** [comment]
It's ok on int as well.

**Comment by loicgasser** [comment]
@ltclm just took care of it. will be fixed tomorrow thanks man

**Comment by AFoletti** [comment]
@ltclm found the problem (wrong active branch) and it's now fixed.
We should still find a way to have a better look at this data.
@alcapat had a nice suggestion: to prepare a script checking the min and max date in the tables, and let jenkins send an email if the max date is less than 3 days from "now". This way the check mechanism will be completely independent from the integration

**Comment by davidoesch** [comment]
Not yet working here...

**Comment by AFoletti** [comment]
@davidoesch it's not "not working". There is not data for the station you selected and that's different (every point round this one has data).
In the last imported data, the only entry for the station you selected is a departure on may the 7th.
In my opinion, the original data is at fault here
