### ISSUE TITLE
icon in twitter handle dissapeared 

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3303]
Small thing, butwith one of the latest deploy, federal icon in twitter vanished... fb is ok
![unbenannt](https://cloud.githubusercontent.com/assets/4577727/15023462/da11aeb8-1230-11e6-851b-bc5426cb916c.png)

**Comment by davidoesch** [comment]
it is _not_ fixed 
https://twitter.com/swiss_geoportal/status/737533335707082752

![unbenannt3](https://cloud.githubusercontent.com/assets/4577727/15667367/34a33d5c-2716-11e6-86b6-3c99b4d55b50.PNG)

**Comment by procrastinatio** [comment]
Twitter and co need absolute path. And we exclusively deny all robots acces to `dev`and `int`(see https://github.com/geoadmin/mf-geoadmin3/pull/3338)

**Comment by gjn** [comment]
Fixed
