### ISSUE TITLE
Wanderkarte 1:500000

### ISSUE THREAD

**Issue by p1d1d1** [geoadmin/mf-geoadmin3#3304]
@gjn @davidoesch 
ch.swisstopo.wk50-papierkarte.metadata has a wrong translation in DE.
RM is shown.

**Comment by davidoesch** [comment]
Seems to be a geocat 2bod issue ping @mariokeusen

**Comment by ltclm** [comment]
will be fixed with the next bod deploy

**Comment by gjn** [comment]
@p1d1d1 Could you please verify and close if good?

**Comment by p1d1d1** [comment]
you already did it.
