### ISSUE TITLE
SHOP: ch.swisstopo.geologie-gravimetrischer_atlas.metadata

### ISSUE THREAD

**Issue by p1d1d1** [geoadmin/mf-geoadmin3#3310]
@gjn 
The layer ch.swisstopo.geologie-gravimetrischer_atlas.metadata is wrongly positioned in swisstopo catalog.

It is now in:
+Digitale Karten
  - Geologische Karten Digital
PS: it is present twice

It should be under Papierkarten

**Comment by mariokeusen** [comment]
I corrected that in the topic config (zoho table). @alcapat Could you please consider that for the next deploy?
Thanks

**Comment by alcapat** [comment]
@mariokeusen  here the link with new config : https://mf-geoadmin3.dev.bgdi.ch/?api_url=dev_catalog_import

**Comment by mariokeusen** [comment]
Checked and ok. Ready to deploy from my side.

**Comment by mariokeusen** [comment]
Fix is on prod now. Thanks
