### ISSUE TITLE
Drawing writes KML with lines with only one point

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3319]
Drawing writes KML with lines with only one point
Example

https://s.geo.admin.ch/6bf8508656 

proposal: download a couple of thousands of our KMLs
and test it against http://cite.opengeospatial.org/teamengine/about/kml22/2.2/site/ 

-> find possible other errors

**Comment by gjn** [comment]
That's hightest priority for me. We shouldn't be able to draw something that can't be printed.

**Comment by oterral** [comment]
Just to mention the previous issue https://github.com/geoadmin/mf-geoadmin3/issues/3238
