### ISSUE TITLE
WMS Sentinel :does not load

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3323]
Hi 
 Sentinel is the landsat of Europe , 10m resolution, very good spatial resolution - and FREE access however...

Access via WMS and WMTS

neither of 
- [x] http://postcards.sentinel-hub.com/v1/wms/bc5af835-ee20-4d98-bda9-b64b2fd975a8?SERVICE=WMS&REQUEST=GetCapabilities 

excellent doumentation on http://www.sentinel-hub.com/apps/wms

- [ ] http://landsatlook.usgs.gov/arcgis/services/Sentinel2/ImageServer/WMSServer?request=GetCapabilities&service=WMS 

does work in map.geo.admin.ch youc an add it to the list as well

BTW: http://sentinel-pds.s3-website.eu-central-1.amazonaws.com/ nice for WMTS

**Comment by gjn** [comment]
Either or Neither?

**Comment by davidoesch** [comment]
None of them

**Comment by oterral** [comment]
This one works  http://postcards.sentinel-hub.com/v1/wms/bc5af835-ee20-4d98-bda9-b64b2fd975a8

**Comment by davidoesch** [comment]
funny : http://postcards.sentinel-hub.com/v1/wms/bc5af835-ee20-4d98-bda9-b64b2fd975a8 does not work anymore @oterral 

Seems like they change the URL

**Comment by p1d1d1** [comment]
slowly but it's working

**Comment by oterral** [comment]
just tested it's working.

**Comment by davidoesch** [comment]
yep.. same here. they have sloow machine
