### ISSUE TITLE
shop layers in iframe -Breaks Link to full app 

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3328]
On mobile Android chrome 

Open http://www.swisstopo.admin.ch/internet/swisstopo/de/commons/didyouknow/Tunnelferroviaire.html

Click on link show in map geo admin.

Result nothing happens

**Comment by oterral** [comment]
works on my android

**Comment by davidoesch** [comment]
Not on my Nexus
![screenshot_20160525-172440](https://cloud.githubusercontent.com/assets/4577727/15550208/ac2e09ac-22b0-11e6-8ea2-314e74064398.png)

**Comment by gjn** [comment]
Popup blocker active in settings?
On my nexus 7,  in chrome, i got a warning and had to give permission.
Am 25.05.2016 7:48 nachm. schrieb David Oesch <notifications@github.com>:Not on my Nexus

**Comment by davidoesch** [comment]
Nope ... www.geo.admin.ch/iframe none of them works. Might not be related to do

**Comment by gjn** [comment]
I really think it's a setting somewhere....

**Comment by davidoesch** [comment]
will show you my device-- could also reproduce on a smasung s4 zoom with an
older android 4X

**Comment by gjn** [comment]
Settings -> Website Settings -> Pop-ups -> Blocked or Allowed?

Problem is really target="_blank" links inside iframe on Android. They are quite security relevant.

Can you try other iframe links? (Most twitter/facebook icons on pages are using those). Are they working? If yes, can you give me a link of a working example?

Possible workaround if it persists: http://stackoverflow.com/questions/15535823/dynamically-set-href-in-iframe-not-working-in-chrome-on-android

Some refs:
https://www.androidpit.com/how-to-block-ads-on-your-android
[http://stackoverflow.com/questions/18661372/android-webview-containing-hyperlinks-inside-iframe-not-working]

**Comment by davidoesch** [comment]
> Settings -> Website Settings -> Pop-ups -> Blocked or Allowed?
-> no effect

> Can you try other iframe links? (Most twitter/facebook icons on pages are using those). Are they working? If yes, can you give me a link of a working example?
 on the page www.geo.admin.ch/iframe we have Share button on top right for FB TW etc..they do all work

**Comment by gjn** [comment]
Those share buttons are _not_ inside an iframe.

The problems seem to be links with target=_blank _inside_ iframes. So when we have a page where it works, it might give us hints.

**Comment by davidoesch** [comment]
links in iframe works eg for this site for the youtube vid
http://www.htmlgoodies.com/tutorials/web_graphics/article.php/3480061/How-To-Add-a-YouTube-Video-to-Your-Web-Site.htm 

and it is an about:blank site....

**Comment by gjn** [comment]
Which links there? The share inside the video?

**Comment by davidoesch** [comment]
yep


On Fri, May 27, 2016 at 11:07 AM, Gilbert Jeiziner <notifications@github.com

**Comment by gjn** [comment]
I can't see what we are doing differently than them. @oterral Do you?

**Comment by p1d1d1** [comment]
Test on Huawei p8 with Android 5.0.1

It does work with default browser.
I confirm @davidoesch issue with Chrome. Same behaviour if you click to open the shop tooltip --> tooltip opens but you cannot close it --> same empty and white windows appears.

**Comment by gjn** [comment]
I'll downgrad to 2nd prio as only specific browser on specific platform is affected.

**Comment by oterral** [comment]
it's a meta tag viewport problem. I can reproduce on map.geo.admin.ch (share embed component) removing the view port tag.
If you zoom enough the page the white window doesn't appear and the link is clicked correctly.

**Comment by oterral** [comment]
Must be fixed on swisstopo site side.
