### ISSUE TITLE
Print KML with opacity doesn't work

### ISSUE THREAD

**Issue by oterral** [geoadmin/mf-geoadmin3#3333]
This line must be removed : https://github.com/geoadmin/mf-geoadmin3/blob/master/src/components/print/PrintDirective.js#L406

`layer.opacity` doesn't exist

**Comment by mariokeusen** [comment]
Confirmed: had a helpdesk customer yesterday who observed the same.

UC: open app, load a kml file with line or poly objects, set opacity of the kml-layer to e.g. 0.5, print a PDF
Result: the kml-layer is drawn fully opaque on the PDF
Expected: the kml-layer is drawn with the same opacity value as set in the mapviewer's layer selection
