### ISSUE TITLE
noscale LK layer: no highlight of selected geometrie

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3336]
open
https://s.geo.admin.ch/6c3102821e

select gemeinde or other perimeter: highlight on map is misisng

![unbenannt3](https://cloud.githubusercontent.com/assets/4577727/15666221/ee87f37c-270f-11e6-9024-b6e7fe9021f8.PNG)

I know this bug might be referenced somewhere else.... close it if it is a duplicate

**Comment by cedricmoullet** [comment]
Will be discussed in the shop POL

Envoyé de mon iPhone

**Comment by ltclm** [comment]
https://github.com/geoadmin/mf-chsdi3/issues/2094

**Comment by ltclm** [comment]
has also been reported to @pauloamado

**Comment by gjn** [comment]
@cedricmoullet What was the decision in the POL?

**Comment by davidoesch** [comment]
will be solved with the new layer strategy for the shop

**Comment by ltclm** [comment]
whats the new layer strategy?

**Comment by gjn** [comment]
We'll have shop-only meta layers.

**Comment by gjn** [comment]
Forget my comment - I was confused.
