### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by Jenselme** [geoadmin/mf-geoadmin3#3346]
I'm doing some checks on which license the project we use rely on. During this process, I found that the license for mf-geoadmin3 is not very clear. What it states makes me think of BSD 2, 3 or 3 clauses but I am not sure.

Can you please clarify that? See https://en.wikipedia.org/wiki/BSD_licenses for more information.

By the way, OpenLayers is license under the BSD 2 clause license as stated on [their website](http://openlayers.org/). I think you can just mention that in the LICENSE file (or put the full license text).

**Comment by gjn** [comment]
Yep. Licence is on may table.

I think we will go with the MIT licene. Any objection to that, @Jenselme ?

**Comment by Jenselme** [comment]
@gjn MIT is fine for me.

**Comment by gjn** [comment]
BSD 3-clause it is. Updated.

**Comment by Jenselme** [comment]
Thanks!
