### ISSUE TITLE
Search can't be deactivated

### ISSUE THREAD

**Issue by cedricmoullet** [geoadmin/mf-geoadmin3#3350]
1. Start https://map.geo.admin.ch/?topic=ech&lang=fr&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.pixelkarte-farbe-pk25.noscale,ch.swisstopo.lk25-papierkarte-zusammensetzung.metadata,ch.swisstopo.lk25-papierkarte.metadata
2. Search for "Bottens"
3. Place the cursor in the search field and clear the characters

Result
When everything is deleted,  search results appear and can't be removed anymore.
![image](https://cloud.githubusercontent.com/assets/319676/15716234/bf6b43c4-2821-11e6-8f19-e6ab673e081b.png)

**Comment by gjn** [comment]
Fixed on next deploy.
