### ISSUE TITLE
LK10 white line

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3352]
see https://s.geo.admin.ch/6c3849551f

viewer or dataintgeration issue?

**Comment by gjn** [comment]
Nice find!
Looks like data integration issue to me. Probably related to reprojection of original data to lv03. Will have a closer lok tomorrow.

Am 01.06.2016 7:07 nachm. schrieb David Oesch <notifications@github.com>:see https://s.geo.admin.ch/6c3849551f

viewer or dataintgeration issue?

**Comment by cedricmoullet** [comment]
David is able to check all pixels of all layers at all zoom levels.... I'm
more than impressed ;-)

2016-06-01 19:52 GMT+02:00 Gilbert Jeiziner <notifications@github.com>:

> Nice find!
> Looks like data integration issue to me. Probably related to reprojection
> of original data to lv03. Will have a closer lok tomorrow.
>
> Am 01.06.2016 7:07 nachm. schrieb David Oesch <notifications@github.com>:see
> https://s.geo.admin.ch/6c3849551f
>
> viewer or dataintgeration issue?
>
> —You are receiving this because you were assigned.Reply to this email
> directly, view it on GitHub, or mute the thread.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/geoadmin/mf-geoadmin3/issues/3352#issuecomment-223072742>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AATgvITH6JLsVk3tUKYaWZ6R5aA5YV7Lks5qHcbugaJpZM4IrxTh>
> .
>



-- 
Twitter: http://twitter.com/cedricmoullet
Linked In: http://www.linkedin.com/in/cedricmoullet

<http://twitter.com/cedricmoullet>

**Comment by mariokeusen** [comment]
Didn't find a 2nd example so far and I scrolled a lot of tiles ;-)

**Comment by AFoletti** [comment]
The anomaly goes veeery far N and S of the original find. See https://s.geo.admin.ch/6c3b7c8d4c ad an example.

I second the hypothesis of a tilegeneration issue. Tomorrow I'll try to regenerate a small BBOX and look at what changes.

**Comment by AFoletti** [comment]
tried a new generation on a small bbox around here
https://s.geo.admin.ch/6c40c6a9db

nothing has changed. The anomalies are in the tiles themselves (not at the juncitons), see [here](https://wmts7.geo.admin.ch/1.0.0/ch.swisstopo.landeskarte-farbe-10/default/current/21781/26/918/1904.png)

reprojection problem? @procrastinatio ?

**Comment by procrastinatio** [comment]
So we have a vector datasatet in LV95, from which we derive a raster dataset LK10, and then generate LV03 tiles using Mapserver gird transformation, right ?

**Comment by gjn** [comment]
+1

**Comment by davidoesch** [comment]
you can't unscambre eggs.... this process has to be changed

**Comment by procrastinatio** [comment]
@AFoletti may be check the original data in the first place, you have the same artifact at the same place in zoom level 16, 17 and 18. I doubt is related to reprojection.



.

**Comment by gjn** [comment]
White lines are in original data. It has been recognized by the Datenherr. Correction of this will be part of next regular update. I close this.

(For details, see internal mail exchange).
