### ISSUE TITLE
Use cacheUpdate service for offline obsolete detection

### ISSUE THREAD

**Issue by gjn** [geoadmin/mf-geoadmin3#3355]
See discussion https://github.com/geoadmin/mf-geoadmin3/pull/3279

We still have the issue when the 'current' timestamp is updated. For this, we would need the cacheUpdate service service. I create a low prio issue for this.

In fact, we would need to use this service for all WMTS layers.

**Comment by oterral** [comment]
Link to [cache update doc](https://api3.geo.admin.ch/services/sdiservices.html#cache-update)
