### ISSUE TITLE
favicon Android 

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3360]
On Android favicon do sometimes not appear

Use https://realfavicongenerator.net/favicon_checker?site=Map.geo.admin.ch&ignore_root_issues=on#.V1CXmMtCRnE

As test

**Comment by oterral** [comment]
Same problem on IE.
![capture](https://cloud.githubusercontent.com/assets/621420/15774563/4c026874-297d-11e6-83cb-f0d241e2b045.PNG)
