### ISSUE TITLE
improve site according to google report

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3363]
- [ ] Avoid landing page redirects (imho not possible with topic concept we have)  https://www.google.com/appserve/mkt/p/prJ6K5jDU4Sv9a_fEOk5I0ZysnTRtbPPdwwvP5h1VCpN4td-vpwM7OV04vPyCSWfH_gB7tRlWFkNWXrmleNp7V-GxvCXRbjXdAWPDJwo285o41_otb206u_JMfhUYyoQF9Lq
- [ ] Leverage browser caching
  https://www.google.com/appserve/mkt/p/c9cFYjqF69T5YuNjgNhjfPjrFB_ppqkMsUS49qNvpPTi2OTf-KuRTRF77frDIogZPhGbGakHKlr95qFUQMD_sjXLjAsR8voB_XVwhwRx8ghvxBK300gz-roT7-zDlLkSwUAINVUBS7OW
- [ ] Prioritize visible content ( difficult to achieve)
  https://www.google.com/appserve/mkt/p/j5Kc18GknBZ1wdC5ijA50INeCmuqypsEoTtCLnxK9hFx0OZ-gvIFNiXP3Hg3yymEawin3aWo4TygAyG9G-Fxnq6wfa6cod2VD0U4xTKomvhg9f0hqlulbQc_qxhJ5ERtEwYbLIt2RFCxSEhKhlo=
- [ ] Eliminate render-blocking JavaScript and CSS in above-the-fold content ( amust)
  https://www.google.com/appserve/mkt/p/WsdvjoUHxbTPhm5dqYheJJWn4x4J1jnGm-qnVY4EL3JcFTSMQ8tE7GwxFcSVf0ZO9HkVc9Py4OfzLvEVQ3Htc3ljKKwNZA8uiDtHa_W6cyyzoHf1ODfUO2p3UxPq9w==

**Comment by gjn** [comment]
(Number elements...)

1) we would need something on varnish level to improve current approach. And once we pass on S3, we won't have varnish level. If mobile links is shared, there's no re-direction.
The only option I see is to remove the redirection (mobile detection) and let the user handle it. Is this an option for you?

2) PR is underway - but needs lots of work and testing. Not easy to have it on mobile in parallel with mobile - and browser support is limited.

3) Needs deeper analysis. Could certainly improved quite alot. We have lazy loading for certain libraries already (3D, d3.js, etc). This would be a natural next step.

4) Similar as the above. Certain things could be improved. Need to find balance between packaging js and performance.

**Comment by oterral** [comment]
Same as #3902
