### ISSUE TITLE
Lk10 in 3d artefact 

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3366]
Open

https://s.geo.admin.ch/6c56bc160d

![screenshot_20160607-162653](https://cloud.githubusercontent.com/assets/4577727/15863081/f9a7920e-2cd1-11e6-91dc-41c410eeb9c4.png)

Lk10 is completely distorted

**Comment by gjn** [comment]
@procrastinatio Any news?

**Comment by gjn** [comment]
Fixed on prod. Thanks alot @procrastinatio .
