### ISSUE TITLE
KML 3d support BAZL

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3374]
Hi all

3d files from BAZL FME export

-> what adaptions do BAZL do need to make to get the KML into the final cesium viewer?

to be solved  in Sept/october

"Beiliegend zwei von uns generierte KML-Files zu Testzwecken für die 3D-Integration der Lufträume (Layer CTR – TMA – FIZ). Das erste KML ist gemäss Galdos KML Validator OGC-konform, allerdings musste ich dafür 3 Geometrien (nicht OGC Simple) entfernen. Das zweite KML enthält ebenfalls keine Fehler, aber Empfehlungen aufgrund ungültiger LinearRing-Definition (wegen selbstüberschneidenden Polygonen). 
"
[kml_testfiles.zip](https://github.com/geoadmin/mf-geoadmin3/files/313430/kml_testfiles.zip)

**Comment by oterral** [comment]
Same problem as https://github.com/geoadmin/mf-geoadmin3/issues/3104

Workaround: Don't use a border style and use only a fill style instead.

**Comment by oterral** [comment]
KML from bazl can be imported in map.geo.admin.ch and see it in 3d
