### ISSUE TITLE
extended tooltip not translated

### ISSUE THREAD

**Issue by ltclm** [geoadmin/mf-geoadmin3#3376]
https://api3.geo.admin.ch/rest/services/ech/MapServer/ch.bafu.wasserbau-querprofilmarken/29/extendedHtmlPopup?lang=de

* Why do we need an extended Toolitp?
* It should be fully translated

**Comment by daguer** [comment]
Resolved:
PR ready in mf-chsdi3:
https://github.com/geoadmin/mf-chsdi3/pull/2181

**Comment by daguer** [comment]
Why do we need an extended Toolitp? It's in the "Dateninteg. Formular".
The dataowner want that...:
The only additional attribute in the extended tooltip is "Bemerkung"...

...
_Fett gekennzeichnete Felder sollten im Tooltip Objekt-Information gezeigt werden. Die gesamte Auswahl an Feldern soll in den Zusatzinformationen (HTML extended Tooltip) angezeigt werden._
...
