### ISSUE TITLE
JSON styling resolution dependent styles

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/mf-geoadmin3#3378]
In the context of https://github.com/geoadmin/mf-chsdi3/pull/2133 we would like to use GeoJSON layers, because

1. Markers are big but point to a very small area -> identify requests can't detect the point if the user click in the middle of the marker.
2. As I already said it markers are big at low zoom levels the map is covered which is not ideal.

It's a good candidate for vector layers, but we would need to adapt the symbology according to the zoom level. (An important work for futrue MVT support as well.)

To do that we need to extend our JSON style parser.

ping @oterral @simonevonheute @AFoletti

**Comment by loicgasser** [comment]
Alternatively we could use layer groups, but that sounds like a hack.

**Comment by oterral** [comment]
OL manages style by resolution so it shouldn't be a big deal.

**Comment by loicgasser** [comment]
I propose the following structure to include the style in the JSON parser for ol styles.

https://github.com/geoadmin/mf-geoadmin3/compare/gal_res_style?expand=1

**Comment by oterral** [comment]
lgtm
