### ISSUE TITLE
Geojson 3d support missing

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3380]
Might be a duplicate

Open https://s.geo.admin.ch/6c9f58fa19 on android chrome mobile

Result
![screenshot_20160621-192303](https://cloud.githubusercontent.com/assets/4577727/16239660/14168554-37e6-11e6-9f5b-86a81d06e649.png)

Expected result as in 2d

**Comment by gjn** [comment]
THe points are visible. What is missing?

**Comment by davidoesch** [comment]
on android 6.0.2 & chrome : not all points are shown as on desktop

**Comment by gjn** [comment]
Might be problem of data connection?

**Comment by davidoesch** [comment]
nope, reproduced

**Comment by gjn** [comment]
works on blackberry and jolla :)

**Comment by oterral** [comment]
same here, taht works an android 5.

**Comment by davidoesch** [comment]
Do you see as well the point  at näfels ?

**Comment by oterral** [comment]
yes

**Comment by davidoesch** [comment]
not on the nexus 6p latest android 6*

**Comment by oterral** [comment]
I need  an android 6 device to test :)

**Comment by davidoesch** [comment]
can't be reproduced fixed on nougat 7.0 with latest chrome
