### ISSUE TITLE
No data in Payerne ?

### ISSUE THREAD

**Issue by cedricmoullet** [geoadmin/mf-geoadmin3#3383]
I'm surprised not to see data in Payerne for this layer: https://s.geo.admin.ch/6ccc8e20bd
Is the layer correct ?

**Comment by gjn** [comment]
Strange indeed. I only see something around Locarno.

**Comment by ltclm** [comment]
the layer configuration is right.
This layer shows all features of  ``uvek.bazl.laermbelastungskataster_zivilflugplaetze`` with ``exposuregroup_exposuretype like 'OverallTrafficMilitary_Lr'```.
It's probably an error in the delivered data, because there is no data at all from payerne.

**Comment by mariokeusen** [comment]
I can confirm that the data is not available for all existing civil and military airport facilities. As far as I know BAZL has running (political) approval procedures for each and every facility. As soon as one of those procedures is accepted, a data update will follow. Consider these layers as a data collection which is growing with each decision. May I therefore close this issue?

**Comment by davidoesch** [comment]
it is missing for ALP and BUO as well: dataset is not complete according to BAZL
