### ISSUE TITLE
[attribute search] results identical to search string appearing on the bottom of result list

### ISSUE THREAD

**Issue by mariokeusen** [geoadmin/mf-geoadmin3#3385]
UC: open https://s.geo.admin.ch/6cd0d48b1e, search for "FR 1303" or "FR 7.1" in the all-in-one search field.
Result: the corresponding objects can be found, but are listed at the very bottom of the object result list
Expected: corresponding objects appear on top of the object result list

![ivs_attributesearch_issue_sorting](https://cloud.githubusercontent.com/assets/4577749/16515568/f92c22be-3f72-11e6-99d0-1c335653ba4b.PNG)

**Comment by loicgasser** [comment]
This is an integration issue. These objects are the same. We should merge the road segements with th same IDs.
We should union all the lines with the same `ivs_nummer`

**Comment by mariokeusen** [comment]
Doesn't address the problem: there are bunches of different results up in the list. 
Merging segments is clearly not an option: data manipulation.

**Comment by loicgasser** [comment]
Can you give me a concrete example where these objects are actually different and have the same label?

**Comment by loicgasser** [comment]
https://api3.geo.admin.ch/1610191614/rest/services/ech/SearchServer?searchText=FR%207.1&lang=de&type=featuresearch&bbox=595624.5846387096,164505.44637942425,691624.5846387096,201755.44637942425&features=ch.astra.ivs-reg_loc,ch.astra.ivs-nat&timeEnabled=false,false&timeStamps=2015,2010

Detail field is always exactly the same and the featureId is the bgdi_id, so nothing to do with astra data.
If you don't want to create multilinestrings:

1. Add bgdi_id (relates really to nothing)
2. Ask them to merge it themselves

**Comment by oterral** [comment]
What is make sense to fix this is to put on top features which have the query in their label and then those which have the query in their detail section.

**Comment by boecklic** [comment]
decided with @davidoesch => wontfix
