### ISSUE TITLE
swissearch: name is on lk25 but not in search

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3395]
see: https://twitter.com/swiss_geoportal/status/751334662665109504

"l'ile de Peilz et l'ile aux oiseaux n'existent pas dans les swissnames3D"

expected result:
can be found in swisssearch

**Comment by ltclm** [comment]
yes, we will have to report this to the dataowner, or with http://map.revision.admin.ch 
i will do that tomorrow.

**Comment by gjn** [comment]
As @ltclm mentioned, this is a revision thing. We'll close. Information send to topo.
