### ISSUE TITLE
Conflict between touch and mouse 

### ISSUE THREAD

**Issue by oterral** [geoadmin/mf-geoadmin3#3408]
Win 10 chrome 51,

map.ge.admin active only toch events when the device supporting mouse too. So when the user try to click on map with its mouse it doesn't work because only touch events are registered .

Wait for https://github.com/openlayers/ol3/pull/5616

**Comment by oterral** [comment]
It's a general problem  which affect all the application. I will wait the draw is merged to fix this.

**Comment by gjn** [comment]
ok. But it's a use case that we'll have more and more in the future. Many devices already are hybrid and allow touch interactions as well as mouse interactions.

**Comment by gjn** [comment]
We wait for the merge of ol3 update.

**Comment by gjn** [comment]
90% of problems solved.
