### ISSUE TITLE
WMS doesn't manage  TIME=undefined

### ISSUE THREAD

**Issue by oterral** [geoadmin/mf-geoadmin3#3413]
1) Open https://map.geo.admin.ch/?lang=fr&topic=luftbilder&bgLayer=voidLayer&X=185900.00&Y=599950.00&dev3d=true&zoom=0&debug&catalogNodes=1179,1180,1186&layers=ch.swisstopo.lubis-luftbilder_schraegaufnahmen&layers_timestamp=1927&time=1927
2) Deactivate the time slider

-> WMS request failed because the WMS doesn't manage the parameter `TIME=undefined`

**Comment by ltclm** [comment]
which layer? normally time parameter has to be empty or a valid timestamp.

**Comment by oterral** [comment]
I think it's an OpenLayers problem we already had this problem for the `styles` parameter.

**Comment by oterral** [comment]
I could set empty easily but it doesn't seems to work: 

https://wms0.geo.admin.ch/?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=ch.swisstopo.lubis-luftbilder_schraegaufnahmen&LANG=fr&TIME=&WIDTH=552&HEIGHT=552&CRS=EPSG%3A21781&STYLES=&BBOX=671000%2C217000%2C809000%2C355000

**Comment by ltclm** [comment]
you're right, the mentioned layer is configured with the [built-in time dimension ](http://mapserver.org/de/ogc/wms_time.html) which is visible in the getcap. the downside is, we cannot configure a default parameter which is showing all the data, the only way to show all the data is to remove the time parameter completely from the getmap request. would this be doable?

If not we have to change the time dimension of this layer to runtime substitution (see [here](https://github.com/geoadmin/wms-mapfile_include/blob/master/ch.swisstopo.lubis-bildstreifen.map#L9 ))
Runtime Substitution would be much more flexible, but it is not visible in the getcap document. 
The question is now what is more important?

the same layer configured with runtime substitution:
[time=
](https://wms-bgdi.dev.bgdi.ch/ltclm/xx/?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=ch.swisstopo.lubis-luftbilder_schraegaufnahmen&WIDTH=552&HEIGHT=552&CRS=EPSG%3A21781&STYLES=&BBOX=671000%2C217000%2C809000%2C355000&time=)[time=undefined](https://wms-bgdi.dev.bgdi.ch/ltclm/xx/?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=ch.swisstopo.lubis-luftbilder_schraegaufnahmen&WIDTH=552&HEIGHT=552&CRS=EPSG%3A21781&STYLES=&BBOX=671000%2C217000%2C809000%2C355000&time=undefined)
[no time in getmap](https://wms-bgdi.dev.bgdi.ch/ltclm/xx/?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=ch.swisstopo.lubis-luftbilder_schraegaufnahmen&WIDTH=552&HEIGHT=552&CRS=EPSG%3A21781&STYLES=&BBOX=671000%2C217000%2C809000%2C355000)
[time=1950](https://wms-bgdi.dev.bgdi.ch/ltclm/xx/?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=ch.swisstopo.lubis-luftbilder_schraegaufnahmen&WIDTH=552&HEIGHT=552&CRS=EPSG%3A21781&STYLES=&BBOX=671000%2C217000%2C809000%2C355000&time=1950)

https://github.com/geoadmin/wms-mapfile_include/pull/33/files

**Comment by oterral** [comment]
I've the feeling that removing the time parameter is the correct way but I need to fix that in Openlayers.

**Comment by gjn** [comment]
Yes, I agree that not sending time parameter seems to be the correct way.
