### ISSUE TITLE
Swipe over menu

### ISSUE THREAD

**Issue by gjn** [geoadmin/mf-geoadmin3#3416]
The swipe line is over the menu. I don't know since when or if this is wanted:

![image](https://cloud.githubusercontent.com/assets/2572317/17362153/12fd6e76-5974-11e6-8788-5827d5c9645b.png)

@davidoesch ?

**Comment by davidoesch** [comment]
This is not wanted and was initially not the case

**Comment by loicgasser** [comment]
Behind or in front of popups?

**Comment by gjn** [comment]
Behind tooltips and other popus.

**Comment by davidoesch** [comment]
Behind tooltip and other pop-ups...directly on the map... As topmost layer
