### ISSUE TITLE
Geojson support getOlStyleForResolution  broken

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3418]
https://github.com/geoadmin/mf-geoadmin3/commit/81f34d8a52977649b6b4ac117518ca2859dccd2b
getOlStyleForResolution  seems to be broken

**Comment by loicgasser** [comment]
It's borken for range style, I am on it.

**Comment by loicgasser** [comment]
sorry for
ch.bafu.hydroweb-messstationen_zustand
ch.bafu.hydroweb-messstationen_vorhersage
only

**Comment by gjn** [comment]
When fixed, please emergency deploy mf-geoadmin3.

**Comment by loicgasser** [comment]
it because of a 0 value evaluated as false

**Comment by loicgasser** [comment]
https://github.com/geoadmin/mf-geoadmin3/pull/3420

**Comment by loicgasser** [comment]
I am redeploying.

**Comment by loicgasser** [comment]
Ok fixed on prod.
map.geo.admin.ch/?layers=ch.bafu.hydroweb-messstationen_zustand,ch.bafu.hydroweb-messstationen_vorhersage
thanks
