### ISSUE TITLE
KML Mapstyle issue

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3421]
Hi

open fusion table map
https://fusiontables.google.com/DataSource?docid=1E86rvB--SKZYJh87YX2F2zcHunGuGAfSDdrSQhRc#map:id=3 

go to map of geometry

result
![unbenannt](https://cloud.githubusercontent.com/assets/4577727/17406697/d0c786ee-5a64-11e6-9bd0-db204c7e2a89.PNG)

then go to 
file 
download
download as kml

import the kml into map.geo.admin.ch
result

![unbenannt](https://cloud.githubusercontent.com/assets/4577727/17406799/3f2b6330-5a65-11e6-81cf-7f3d6b52eb7e.PNG)

Bern does not have the same color class as in the fusion view ...

Question
- is google fusion messing up the export?
- is the <styleUrl> interpreted wrong?

**Comment by oterral** [comment]
@davidoesch  it's depending of the backgroun I guess . If you use satelitte layer on gmap and swissimage on admin.ch the colors are the same.

**Comment by oterral** [comment]
but there's still a polygon border's width  difference

**Comment by oterral** [comment]
The kml exported contains to LineStyle for a feature's stye:

```
<LineStyle>
				<color>7f0000ff</color>
				<width>2</width>
			</LineStyle>
			<LineStyle>
				<color>ff666666</color>
				<width>0</width>
			</LineStyle>
```

**Comment by oterral** [comment]
Funny thing the lineWidth property of a canvas's context can't be null 0. We just need to remove the stroke style when we sanitize the feature.

**Comment by davidoesch** [comment]
colors are not the sam even with BG: look at BE TG SH
I assume it has todo with Cantons which have islands.... if there is an island, if messes up the display
![unbenannt](https://cloud.githubusercontent.com/assets/4577727/17557957/64e247d4-5f19-11e6-8817-f8c78857ca39.PNG)

for the borders..yes this is as well an issue

**Comment by gjn** [comment]
kml sanitzising and support will be our next issue when draw is live.

**Comment by oterral** [comment]
Ah yes didn't this diffference. I'll have a look

**Comment by oterral** [comment]
Bern and Freiburg are defined with the same style so I guess the Google export is wrong.
