### ISSUE TITLE
3D Curve View

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3425]
in GE there seems to be a "lense" function: mountains are closer and give therefore a more impressive view
-> any support in cesium for this?
https://map.geo.admin.ch/?topic=ech&lang=de&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bav.haltestellen-oev,ch.swisstopo.swisstlm3d-wanderwege,ch.swisstopo.swissimage-product&layers_visibility=false,false,false,false,true&layers_timestamp=18641231,,,,&lon=7.55816&lat=46.79565&elevation=2288&heading=132.785&pitch=-8.679

![unbenannt2](https://cloud.githubusercontent.com/assets/4577727/17558523/2c079340-5f1b-11e6-94b0-04f77534c9ad.png)

in
https://www.google.ch/maps/@46.8488351,7.4927358,2771a,20y,137.62h,81.26t/data=!3m1!1e3?hl=en

![unbenannt](https://cloud.githubusercontent.com/assets/4577727/17558551/427e7a8a-5f1b-11e6-9948-bbfd7fc98462.PNG)

**Comment by oterral** [comment]
No

**Comment by davidoesch** [comment]
Imho this would be a nice feature request for cesium

**Comment by gjn** [comment]
No sure about support. Camera does have some options, so it might be possible? @fredj care to have a look?

**Comment by davidoesch** [comment]
wontfix
