### ISSUE TITLE
update disclaimer iframe link

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3426]
disclaimer in share in FR points to
https://www.geo.admin.ch/internet/geoportal/fr/home/geoadmin/contact.html#iFrame
instead of 
https://www.geo.admin.ch/de/about-swiss-geoportal/impressum.html#iFrame 

SAME for RM IT FR EN

**Comment by loicgasser** [comment]
Fixed in https://github.com/geoadmin/mf-geoadmin3/pull/3423

**Comment by loicgasser** [comment]
Fixed via https://github.com/geoadmin/mf-geoadmin3/pull/3423
