### ISSUE TITLE
Building the project doesn't work

### ISSUE THREAD

**Issue by bvpelt** [geoadmin/mf-geoadmin3#3427]
After cloning this project from the repository and executing make user the project gives error messages.

Environment:
uname -a
Linux pluto.universe.org 4.6.5-200.fc23.x86_64 #1 SMP Thu Jul 28 01:10:25 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

npm -version
3.10.5

[bvpelt@pluto Develop]$ git clone https://github.com/geoadmin/mf-geoadmin3.git
Cloning into 'mf-geoadmin3'...
remote: Counting objects: 63681, done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 63681 (delta 0), reused 0 (delta 0), pack-reused 63672
Receiving objects: 100% (63681/63681), 243.12 MiB | 9.19 MiB/s, done.
Resolving deltas: 100% (40348/40348), done.
Checking connectivity... done.
[bvpelt@pluto Develop]$ cd mf-geoadmin3/
[bvpelt@pluto mf-geoadmin3]$ make user
source rc_user && make all
Please provide a custom config file using the pattern rc_user_$USERNAME
make[1]: Entering directory '/home/bvpelt/Develop/mf-geoadmin3'
npm install --only=dev;
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130

> phantomjs-prebuilt@2.1.3 install /home/bvpelt/Develop/mf-geoadmin3/node_modules/phantomjs-prebuilt
> node install.js

PhantomJS not found on PATH
Download already available at /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
Verified checksum of previously downloaded file
Extracting tar contents (via spawned process)
Removing /home/bvpelt/Develop/mf-geoadmin3/node_modules/phantomjs-prebuilt/lib/phantom
Copying extracted folder /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2-extract-1470857182584/phantomjs-2.1.1-linux-x86_64 -> /home/bvpelt/Develop/mf-geoadmin3/node_modules/phantomjs-prebuilt/lib/phantom
Writing location.js file
Done. Phantomjs binary available at /home/bvpelt/Develop/mf-geoadmin3/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs
geoadmin3@3.0.0 /home/bvpelt/Develop/mf-geoadmin3
├── angular-mocks@1.4.8 
├─┬ commander@2.9.0 
│ └── graceful-readlink@1.0.1 
├── expect.js@0.3.1 
├─┬ google-closure-compiler@20151216.1.0 
│ ├─┬ chalk@1.1.3 
│ │ ├── ansi-styles@2.2.1 
│ │ ├── escape-string-regexp@1.0.5 
│ │ ├─┬ has-ansi@2.0.0 
│ │ │ └── ansi-regex@2.0.0 
│ │ ├── strip-ansi@3.0.1 
│ │ └── supports-color@2.0.0 
│ ├─┬ gulp-util@3.0.7 
│ │ ├── array-differ@1.0.0 
│ │ ├── array-uniq@1.0.3 
│ │ ├── beeper@1.1.0 
│ │ ├─┬ fancy-log@1.2.0 
│ │ │ └── time-stamp@1.0.1 
│ │ ├─┬ gulplog@1.0.0 
│ │ │ └── glogg@1.0.0 
│ │ ├─┬ has-gulplog@0.1.0 
│ │ │ └── sparkles@1.0.0 
│ │ ├── lodash._reescape@3.0.0 
│ │ ├── lodash._reevaluate@3.0.0 
│ │ ├── lodash._reinterpolate@3.0.0 
│ │ ├─┬ lodash.template@3.6.2 
│ │ │ ├── lodash._basecopy@3.0.1 
│ │ │ ├── lodash._basetostring@3.0.1 
│ │ │ ├── lodash._basevalues@3.0.0 
│ │ │ ├── lodash._isiterateecall@3.0.9 
│ │ │ ├─┬ lodash.escape@3.2.0 
│ │ │ │ └── lodash._root@3.0.1 
│ │ │ ├─┬ lodash.keys@3.1.2 
│ │ │ │ ├── lodash._getnative@3.9.1 
│ │ │ │ ├── lodash.isarguments@3.0.9 
│ │ │ │ └── lodash.isarray@3.0.4 
│ │ │ ├── lodash.restparam@3.6.1 
│ │ │ └── lodash.templatesettings@3.1.1 
│ │ ├── minimist@1.2.0 
│ │ ├─┬ multipipe@0.1.2 
│ │ │ └─┬ duplexer2@0.0.2 
│ │ │   └── readable-stream@1.1.14 
│ │ ├── object-assign@3.0.0 
│ │ ├── replace-ext@0.0.1 
│ │ └─┬ vinyl@0.5.3 
│ │   ├── clone@1.0.2 
│ │   └── clone-stats@0.0.1 
│ ├─┬ through2@2.0.1 
│ │ ├─┬ readable-stream@2.0.6 
│ │ │ ├── core-util-is@1.0.2 
│ │ │ ├── isarray@1.0.0 
│ │ │ ├── process-nextick-args@1.0.7 
│ │ │ ├── string_decoder@0.10.31 
│ │ │ └── util-deprecate@1.0.2 
│ │ └── xtend@4.0.1 
│ ├─┬ vinyl-fs@2.4.3 
│ │ ├─┬ duplexify@3.4.5 
│ │ │ ├── end-of-stream@1.0.0 
│ │ │ ├─┬ readable-stream@2.1.4 
│ │ │ │ └── isarray@1.0.0 
│ │ │ └── stream-shift@1.0.0 
│ │ ├─┬ glob-stream@5.3.2 
│ │ │ ├── glob@5.0.15 
│ │ │ ├─┬ micromatch@2.3.11 
│ │ │ │ ├─┬ arr-diff@2.0.0 
│ │ │ │ │ └── arr-flatten@1.0.1 
│ │ │ │ ├─┬ braces@1.8.5 
│ │ │ │ │ ├─┬ expand-range@1.8.2 
│ │ │ │ │ │ └─┬ fill-range@2.2.3 
│ │ │ │ │ │   ├── is-number@2.1.0 
│ │ │ │ │ │   ├─┬ isobject@2.1.0 
│ │ │ │ │ │   │ └── isarray@1.0.0 
│ │ │ │ │ │   ├── randomatic@1.1.5 
│ │ │ │ │ │   └── repeat-string@1.5.4 
│ │ │ │ │ ├── preserve@0.2.0 
│ │ │ │ │ └── repeat-element@1.1.2 
│ │ │ │ ├─┬ expand-brackets@0.1.5 
│ │ │ │ │ └── is-posix-bracket@0.1.1 
│ │ │ │ ├── extglob@0.3.2 
│ │ │ │ ├── filename-regex@2.0.0 
│ │ │ │ ├─┬ kind-of@3.0.4 
│ │ │ │ │ └── is-buffer@1.1.4 
│ │ │ │ ├── normalize-path@2.0.1 
│ │ │ │ ├─┬ object.omit@2.0.0 
│ │ │ │ │ ├─┬ for-own@0.1.4 
│ │ │ │ │ │ └── for-in@0.1.5 
│ │ │ │ │ └── is-extendable@0.1.1 
│ │ │ │ ├─┬ parse-glob@3.0.4 
│ │ │ │ │ ├── glob-base@0.3.0 
│ │ │ │ │ └── is-dotfile@1.0.2 
│ │ │ │ └─┬ regex-cache@0.4.3 
│ │ │ │   ├── is-equal-shallow@0.1.3 
│ │ │ │   └── is-primitive@2.0.0 
│ │ │ ├─┬ ordered-read-streams@0.3.0 
│ │ │ │ ├── is-stream@1.1.0 
│ │ │ │ └─┬ readable-stream@2.1.4 
│ │ │ │   └── isarray@1.0.0 
│ │ │ ├─┬ through2@0.6.5 
│ │ │ │ └── readable-stream@1.0.34 
│ │ │ ├─┬ to-absolute-glob@0.1.1 
│ │ │ │ └── extend-shallow@2.0.1 
│ │ │ └─┬ unique-stream@2.2.1 
│ │ │   └─┬ json-stable-stringify@1.0.1 
│ │ │     └── jsonify@0.0.0 
│ │ ├─┬ gulp-sourcemaps@1.6.0 
│ │ │ ├── convert-source-map@1.3.0 
│ │ │ └── vinyl@1.2.0 
│ │ ├── is-valid-glob@0.3.0 
│ │ ├─┬ lazystream@1.0.0 
│ │ │ └─┬ readable-stream@2.1.4 
│ │ │   └── isarray@1.0.0 
│ │ ├── lodash.isequal@4.3.1 
│ │ ├─┬ merge-stream@1.0.0 
│ │ │ └─┬ readable-stream@2.1.4 
│ │ │   └── isarray@1.0.0 
│ │ ├── object-assign@4.1.0 
│ │ ├─┬ readable-stream@2.1.4 
│ │ │ ├── buffer-shims@1.0.0 
│ │ │ └── isarray@1.0.0 
│ │ ├─┬ strip-bom@2.0.0 
│ │ │ └── is-utf8@0.2.1 
│ │ ├─┬ strip-bom-stream@1.0.0 
│ │ │ └── first-chunk-stream@1.0.0 
│ │ ├── through2-filter@2.0.0 
│ │ ├── vali-date@1.0.0 
│ │ └── vinyl@1.2.0 
│ └── vinyl-sourcemaps-apply@0.2.1 
├── google-closure-library@20151216.0.0 
├─┬ karma@0.13.22 
│ ├── batch@0.5.3 
│ ├── bluebird@2.10.2 
│ ├─┬ body-parser@1.15.2 
│ │ ├── bytes@2.4.0 
│ │ ├── content-type@1.0.2 
│ │ ├─┬ debug@2.2.0 
│ │ │ └── ms@0.7.1 
│ │ ├── depd@1.1.0 
│ │ ├─┬ http-errors@1.5.0 
│ │ │ ├── setprototypeof@1.0.1 
│ │ │ └── statuses@1.3.0 
│ │ ├── iconv-lite@0.4.13 
│ │ ├─┬ on-finished@2.3.0 
│ │ │ └── ee-first@1.1.1 
│ │ ├── qs@6.2.0 
│ │ ├─┬ raw-body@2.1.7 
│ │ │ └── unpipe@1.0.0 
│ │ └─┬ type-is@1.6.13 
│ │   └── media-typer@0.3.0 
│ ├─┬ chokidar@1.6.0 
│ │ ├─┬ anymatch@1.3.0 
│ │ │ └── arrify@1.0.1 
│ │ ├── async-each@1.0.0 
│ │ ├── glob-parent@2.0.0 
│ │ ├── inherits@2.0.1 
│ │ ├─┬ is-binary-path@1.0.1 
│ │ │ └── binary-extensions@1.5.0 
│ │ ├─┬ is-glob@2.0.1 
│ │ │ └── is-extglob@1.0.0 
│ │ ├── path-is-absolute@1.0.0 
│ │ └─┬ readdirp@2.1.0 
│ │   ├─┬ readable-stream@2.1.4 
│ │   │ └── isarray@1.0.0 
│ │   └── set-immediate-shim@1.0.1 
│ ├── colors@1.1.2 
│ ├─┬ connect@3.4.1 
│ │ ├─┬ finalhandler@0.4.1 
│ │ │ └── escape-html@1.0.3 
│ │ ├── parseurl@1.3.1 
│ │ └── utils-merge@1.0.0 
│ ├── core-js@2.4.1 
│ ├── di@0.0.1 
│ ├─┬ dom-serialize@2.2.1 
│ │ ├── custom-event@1.0.0 
│ │ ├── ent@2.2.0 
│ │ ├── extend@3.0.0 
│ │ └── void-elements@2.0.1 
│ ├─┬ expand-braces@0.1.2 
│ │ ├── array-slice@0.2.3 
│ │ ├── array-unique@0.2.1 
│ │ └─┬ braces@0.1.5 
│ │   └─┬ expand-range@0.1.1 
│ │     ├── is-number@0.1.1 
│ │     └── repeat-string@0.2.2 
│ ├─┬ glob@7.0.5 
│ │ ├── fs.realpath@1.0.0 
│ │ ├─┬ inflight@1.0.5 
│ │ │ └── wrappy@1.0.2 
│ │ └── once@1.3.3 
│ ├── graceful-fs@4.1.5 
│ ├─┬ http-proxy@1.14.0 
│ │ ├── eventemitter3@1.2.0 
│ │ └── requires-port@1.0.0 
│ ├── isbinaryfile@3.0.1 
│ ├── lodash@3.10.1 
│ ├─┬ log4js@0.6.38 
│ │ ├─┬ readable-stream@1.0.34 
│ │ │ └── isarray@0.0.1 
│ │ └── semver@4.3.6 
│ ├── mime@1.3.4 
│ ├─┬ minimatch@3.0.3 
│ │ └─┬ brace-expansion@1.1.6 
│ │   ├── balanced-match@0.4.2 
│ │   └── concat-map@0.0.1 
│ ├─┬ optimist@0.6.1 
│ │ ├── minimist@0.0.10 
│ │ └── wordwrap@0.0.3 
│ ├─┬ rimraf@2.5.4 
│ │ └── glob@7.0.5 
│ ├─┬ socket.io@1.4.8 
│ │ ├─┬ engine.io@1.6.11 
│ │ │ ├─┬ accepts@1.1.4 
│ │ │ │ ├─┬ mime-types@2.0.14 
│ │ │ │ │ └── mime-db@1.12.0 
│ │ │ │ └── negotiator@0.4.9 
│ │ │ ├── base64id@0.1.0 
│ │ │ ├─┬ engine.io-parser@1.2.4 
│ │ │ │ ├── after@0.8.1 
│ │ │ │ ├── arraybuffer.slice@0.0.6 
│ │ │ │ ├── base64-arraybuffer@0.1.2 
│ │ │ │ ├── blob@0.0.4 
│ │ │ │ ├── has-binary@0.1.6 
│ │ │ │ └── utf8@2.1.0 
│ │ │ └─┬ ws@1.1.0 
│ │ │   ├── options@0.0.6 
│ │ │   └── ultron@1.0.2 
│ │ ├── has-binary@0.1.7 
│ │ ├─┬ socket.io-adapter@0.4.0 
│ │ │ └─┬ socket.io-parser@2.2.2 
│ │ │   ├── debug@0.7.4 
│ │ │   └── json3@3.2.6 
│ │ ├─┬ socket.io-client@1.4.8 
│ │ │ ├── backo2@1.0.2 
│ │ │ ├── component-bind@1.0.0 
│ │ │ ├── component-emitter@1.2.0 
│ │ │ ├─┬ engine.io-client@1.6.11 
│ │ │ │ ├── component-inherit@0.0.3 
│ │ │ │ ├── has-cors@1.1.0 
│ │ │ │ ├── parsejson@0.0.1 
│ │ │ │ ├── parseqs@0.0.2 
│ │ │ │ ├── ws@1.0.1 
│ │ │ │ ├── xmlhttprequest-ssl@1.5.1 
│ │ │ │ └── yeast@0.1.2 
│ │ │ ├── indexof@0.0.1 
│ │ │ ├── object-component@0.0.3 
│ │ │ ├─┬ parseuri@0.0.4 
│ │ │ │ └─┬ better-assert@1.0.2 
│ │ │ │   └── callsite@1.0.0 
│ │ │ └── to-array@0.1.4 
│ │ └─┬ socket.io-parser@2.2.6 
│ │   ├── benchmark@1.0.0 
│ │   ├── component-emitter@1.1.2 
│ │   └── json3@3.3.2 
│ ├── source-map@0.5.6 
│ └─┬ useragent@2.1.9 
│   └── lru-cache@2.2.4 
├─┬ karma-coverage@0.5.5 
│ ├─┬ dateformat@1.0.12 
│ │ ├── get-stdin@4.0.1 
│ │ └─┬ meow@3.7.0 
│ │   ├─┬ camelcase-keys@2.1.0 
│ │   │ └── camelcase@2.1.1 
│ │   ├── decamelize@1.2.0 
│ │   ├─┬ loud-rejection@1.6.0 
│ │   │ ├─┬ currently-unhandled@0.4.1 
│ │   │ │ └── array-find-index@1.0.1 
│ │   │ └── signal-exit@3.0.0 
│ │   ├── map-obj@1.0.1 
│ │   ├─┬ normalize-package-data@2.3.5 
│ │   │ ├── hosted-git-info@2.1.5 
│ │   │ ├─┬ is-builtin-module@1.0.0 
│ │   │ │ └── builtin-modules@1.1.1 
│ │   │ ├── semver@5.3.0 
│ │   │ └─┬ validate-npm-package-license@3.0.1 
│ │   │   ├─┬ spdx-correct@1.0.2 
│ │   │   │ └── spdx-license-ids@1.2.2 
│ │   │   └─┬ spdx-expression-parse@1.0.2 
│ │   │     └── spdx-exceptions@1.0.5 
│ │   ├── object-assign@4.1.0 
│ │   ├─┬ read-pkg-up@1.0.1 
│ │   │ ├─┬ find-up@1.1.2 
│ │   │ │ └── path-exists@2.1.0 
│ │   │ └─┬ read-pkg@1.1.0 
│ │   │   ├─┬ load-json-file@1.1.0 
│ │   │   │ ├─┬ parse-json@2.2.0 
│ │   │   │ │ └─┬ error-ex@1.3.0 
│ │   │   │ │   └── is-arrayish@0.2.1 
│ │   │   │ └── pify@2.3.0 
│ │   │   └── path-type@1.1.0 
│ │   ├─┬ redent@1.0.0 
│ │   │ ├─┬ indent-string@2.1.0 
│ │   │ │ └─┬ repeating@2.0.1 
│ │   │ │   └─┬ is-finite@1.0.1 
│ │   │ │     └── number-is-nan@1.0.0 
│ │   │ └── strip-indent@1.0.1 
│ │   └── trim-newlines@1.0.0 
│ └─┬ istanbul@0.4.4 
│   ├── abbrev@1.0.9 
│   ├── async@1.5.2 
│   ├─┬ escodegen@1.8.1 
│   │ ├── estraverse@1.9.3 
│   │ ├── esutils@2.0.2 
│   │ ├─┬ optionator@0.8.1 
│   │ │ ├── deep-is@0.1.3 
│   │ │ ├── fast-levenshtein@1.1.4 
│   │ │ ├── levn@0.3.0 
│   │ │ ├── prelude-ls@1.1.2 
│   │ │ ├── type-check@0.3.2 
│   │ │ └── wordwrap@1.0.0 
│   │ └── source-map@0.2.0 
│   ├── esprima@2.7.2 
│   ├─┬ fileset@0.2.1 
│   │ └── minimatch@2.0.10 
│   ├─┬ handlebars@4.0.5 
│   │ ├── source-map@0.4.4 
│   │ └─┬ uglify-js@2.7.0 
│   │   ├── async@0.2.10 
│   │   ├── uglify-to-browserify@1.0.2 
│   │   └─┬ yargs@3.10.0 
│   │     ├── camelcase@1.2.1 
│   │     ├─┬ cliui@2.1.0 
│   │     │ ├─┬ center-align@0.1.3 
│   │     │ │ ├─┬ align-text@0.1.4 
│   │     │ │ │ └── longest@1.0.1 
│   │     │ │ └── lazy-cache@1.0.4 
│   │     │ ├── right-align@0.1.3 
│   │     │ └── wordwrap@0.0.2 
│   │     └── window-size@0.1.0 
│   ├─┬ js-yaml@3.6.1 
│   │ └─┬ argparse@1.0.7 
│   │   └── sprintf-js@1.0.3 
│   ├── nopt@3.0.6 
│   ├── resolve@1.1.7 
│   ├─┬ supports-color@3.1.2 
│   │ └── has-flag@1.0.0 
│   └── wordwrap@1.0.0 
├── karma-mocha@0.2.2 
├─┬ karma-phantomjs-launcher@1.0.0 
│ └── lodash@4.14.2 
├─┬ less@2.6.1 
│ ├─┬ errno@0.1.4 
│ │ └── prr@0.0.0 
│ ├── image-size@0.4.0 
│ ├─┬ mkdirp@0.5.1 
│ │ └── minimist@0.0.8 
│ ├─┬ promise@7.1.1 
│ │ └── asap@2.0.4 
│ └─┬ request@2.74.0 
│   ├── aws-sign2@0.6.0 
│   ├── aws4@1.4.1 
│   ├─┬ bl@1.1.2 
│   │ └─┬ readable-stream@2.0.6 
│   │   └── isarray@1.0.0 
│   ├── caseless@0.11.0 
│   ├─┬ combined-stream@1.0.5 
│   │ └── delayed-stream@1.0.0 
│   ├── forever-agent@0.6.1 
│   ├── form-data@1.0.0-rc4 
│   ├─┬ har-validator@2.0.6 
│   │ ├─┬ is-my-json-valid@2.13.1 
│   │ │ ├── generate-function@2.0.0 
│   │ │ ├─┬ generate-object-property@1.2.0 
│   │ │ │ └── is-property@1.0.2 
│   │ │ └── jsonpointer@2.0.0 
│   │ └─┬ pinkie-promise@2.0.1 
│   │   └── pinkie@2.0.4 
│   ├─┬ hawk@3.1.3 
│   │ ├── boom@2.10.1 
│   │ ├── cryptiles@2.0.5 
│   │ ├── hoek@2.16.3 
│   │ └── sntp@1.0.9 
│   ├─┬ http-signature@1.1.1 
│   │ ├── assert-plus@0.2.0 
│   │ ├─┬ jsprim@1.3.0 
│   │ │ ├── extsprintf@1.0.2 
│   │ │ ├── json-schema@0.2.2 
│   │ │ └── verror@1.3.6 
│   │ └─┬ sshpk@1.9.2 
│   │   ├── asn1@0.2.3 
│   │   ├── assert-plus@1.0.0 
│   │   ├─┬ dashdash@1.14.0 
│   │   │ └── assert-plus@1.0.0 
│   │   ├── ecc-jsbn@0.1.1 
│   │   ├─┬ getpass@0.1.6 
│   │   │ └── assert-plus@1.0.0 
│   │   ├── jodid25519@1.0.2 
│   │   ├── jsbn@0.1.0 
│   │   └── tweetnacl@0.13.3 
│   ├── is-typedarray@1.0.0 
│   ├── isstream@0.1.2 
│   ├── json-stringify-safe@5.0.1 
│   ├─┬ mime-types@2.1.11 
│   │ └── mime-db@1.23.0 
│   ├── node-uuid@1.4.7 
│   ├── oauth-sign@0.8.2 
│   ├── stringstream@0.0.5 
│   ├── tough-cookie@2.3.1 
│   └── tunnel-agent@0.4.3 
├─┬ less-plugin-clean-css@1.5.1 
│ └─┬ clean-css@3.4.19 
│   ├── commander@2.8.1 
│   └─┬ source-map@0.4.4 
│     └── amdefine@1.0.0 
├── UNMET PEER DEPENDENCY mocha@*
├─┬ ng-annotate@1.2.1 
│ ├── acorn@2.6.4 
│ ├── alter@0.2.0 
│ ├── convert-source-map@1.1.3 
│ ├─┬ ordered-ast-traverse@1.1.1 
│ │ └── ordered-esprima-props@1.1.0 
│ ├── simple-fmt@0.1.0 
│ ├── simple-is@0.2.0 
│ ├── stable@0.1.5 
│ ├── stringmap@0.2.2 
│ ├── stringset@0.2.1 
│ └── tryor@0.1.2 
├─┬ phantomjs-prebuilt@2.1.3 
│ ├── adm-zip@0.4.7 
│ ├─┬ fs-extra@0.26.7 
│ │ ├── jsonfile@2.3.1 
│ │ └── klaw@1.3.0 
│ ├── kew@0.7.0 
│ ├─┬ md5@2.0.0 
│ │ ├── charenc@0.0.1 
│ │ ├── crypt@0.0.1 
│ │ └── is-buffer@1.0.2 
│ ├── progress@1.1.8 
│ ├─┬ request@2.67.0 
│ │ ├─┬ bl@1.0.3 
│ │ │ └─┬ readable-stream@2.0.6 
│ │ │   └── isarray@1.0.0 
│ │ ├── qs@5.2.1 
│ │ └── tough-cookie@2.2.2 
│ ├─┬ request-progress@2.0.1 
│ │ └── throttleit@1.0.0 
│ └─┬ which@1.2.10 
│   └── isexe@1.1.2 
└─┬ sinon@1.17.3 
  ├── formatio@1.1.1 
  ├── lolex@1.3.2 
  ├── samsam@1.1.2 
  └── util@0.10.3 

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm WARN karma-mocha@0.2.2 requires a peer of mocha@* but none was installed.
npm WARN geoadmin3@3.0.0 No license field.
cp -f node_modules/angular-mocks/angular-mocks.js test/lib/;
cp -f node_modules/expect.js/index.js test/lib/expect.js;
cp -f node_modules/sinon/pkg/sinon.js test/lib/;
cp -f node_modules/google-closure-compiler/contrib/externs/angular-1.4.js externs/angular.js;
cp -f node_modules/google-closure-compiler/contrib/externs/jquery-1.9.js externs/jquery.js;
mkdir -p .build-artefacts
touch .build-artefacts/devlibs
mkdir -p .build-artefacts
virtualenv --no-site-packages .build-artefacts/python-venv
/bin/bash: virtualenv: command not found
Makefile:625: recipe for target '.build-artefacts/python-venv' failed
make[1]: *** [.build-artefacts/python-venv] Error 127
make[1]: Leaving directory '/home/bvpelt/Develop/mf-geoadmin3'
Makefile:123: recipe for target 'user' failed
make: *** [user] Error 2

**Comment by loicgasser** [comment]
You need to install python virtualenv.
