### ISSUE TITLE
Marker overlay is highlightable

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/mf-geoadmin3#3439]
Step to reproduce:

1) open the app
2) type: avenue des sciences 3 in the search field
3) click on the marker

Result:
The marker is highlighted with the yellow style of selected features

Expected result:
The marker is not highlighted

This is also reproducilble with the geolocation marker and the drawing when not in draw mode.

**Comment by loicgasser** [comment]
I can also observe it in draw v2

**Comment by gjn** [comment]
Same as https://github.com/geoadmin/mf-geoadmin3/issues/3471
