### ISSUE TITLE
Download KML on SAFARI/MAC does not work

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3440]
Reproduce:
Take latest MAC OS and latest SAFARI
Draw a line/measure
klick Download KML

Result:
download  does not start, no file in  download location

Expected result:
kml is downloaded

Workaround: use Chrome

@gjn possibel side effect of S3 switch? I doubt it

**Comment by gjn** [comment]
Doubt it's S3 related.. Das Problem kommt mir bekannt vor.

**Comment by gjn** [comment]
If I remember correctly, it's a security setting of the browser.

**Comment by gjn** [comment]
service needed for some browsers (IE and safarie) does not work anymore. -> https://github.com/geoadmin/mf-chsdi3/blob/master/chsdi/views/downloadkml.py

**Comment by gjn** [comment]
Fix is coming.

**Comment by gjn** [comment]
Fix posted. I assume no emergency deploy today. If you decide, @loicgasser can deploy this next monday.

**Comment by loicgasser** [comment]
ok
