### ISSUE TITLE
Change KML Download Functionality

### ISSUE THREAD

**Issue by gjn** [geoadmin/mf-geoadmin3#3441]
To download a kml drawing, we currently have 2 approaches, depending on browser capabilities:

1) transform blob to local file (chrome, fireforx, Edge)
2) upload to api3 and fetch file from there (IE9/IE10, Safari).

We could replace both approaches by downloading the KML directly from public.geo.admin.ch, where we already store it!

The 'download as kml' functionality was introduced _before_ we started storing all kml's.

This would be an alternative fix for https://github.com/geoadmin/mf-geoadmin3/issues/3440 and would render https://github.com/geoadmin/mf-chsdi3/pull/2206. IT would allow us to remove the downloadkml service from mf-chsdi3 as well.

Marked as high prio as potential fast fix for  https://github.com/geoadmin/mf-geoadmin3/issues/3440

**Comment by gjn** [comment]
The problem with this approache might be that we can't set a filename for the local, downloaded file. Per default it will look like [91S43_1tQsSqBPUVVbFPKw](https://public.geo.admin.ch/91S43_1tQsSqBPUVVbFPKw). It will be exactly as you would click on this link.

**Comment by loicgasser** [comment]
Fixed in prod.
