### ISSUE TITLE
Drawing: issue with stored kml

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3443]
Since the last deploy: a lot of KML  on dav0 and public.geo.admin.ch do not load anymore

Try to load this kml
https://map.geo.admin.ch/?X=205580.34&Y=638412.75&zoom=3&lang=de&topic=swisstopo&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=KML%7C%7Chttps:%2F%2Fdav0.bgdi.admin.ch%2Fswisstopo%2Fcms2007%2FKARTO%2Fstorymap-karto%2FStoryMap_NLK25_DE.xml 

result: 
no drawing shown
-it affects kml sources on dav0 as well on public.geo.admin.ch

digging deeper: 
the kml https://dav0.bgdi.admin.ch/swisstopo/cms2007/KARTO/storymap-karto/StoryMap_NLK25_DE.xml  is valid
all I get is an 404 for a marker in https://map.geo.admin.ch/1436519633940/img/maki/marker-24@2x.png

(besides that even if I draw new : I get a 404)

More affected URLs
1.)	http://www.schoolmaps.ch/2016/02/15/wer-lebt-bei-uns-ums-schulhaus-artenvielfalt-auf-digitalen-karten-festhalten/ 
https://map.geo.admin.ch/index.html?topic=ech&lang=de&bgLayer=ch.swisstopo.swissimage&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bafu.wrz-wildruhezonen_portal,ch.swisstopo.swisstlm3d-wanderwege,KML%7C%7Chttps:%2F%2Fpublic.geo.admin.ch%2FO4rG8_MZQ0ynhLzXQKeXsg&layers_visibility=false,false,false,false,true&layers_timestamp=18641231,,,,&X=228979.00&Y=607967.00&zoom=10

2.)	http://www.schoolmaps.ch/2016/04/26/weiterbildung-4-die-abschlussveranstaltung/ - > hier die Orte welche Tropfen und Häuser als Symbole hatten (April 2016)

3.)	http://www.schoolmaps.ch/2015/10/09/standorte-automatisch-eintragen-mit-kml/

4.)	http://www.schoolmaps.ch/2015/08/07/wie-erstelle-ich-meine-eigene-karte-zeichnen-und-messen-funktion/ -> Beispiele

5.)	http://www.schoolmaps.ch/2015/10/08/meine-freizeit-in-meiner-umgebung/ -> mein Kommentar unten

**Comment by oterral** [comment]
hmm that make ssens since the maki urls should be like this now : https://map.geo.admin.ch/master/3ea0981/1471529293/1471529293/img/maki/marker-24@2x.png

Nothing has bee done to transform the urls.

**Comment by davidoesch** [comment]
ETA of fix ?(a lot of customers are affected)

**Comment by loicgasser** [comment]
Will be fixed today

**Comment by loicgasser** [comment]
Do you mind to having a human readable file name ? That s what would happen if we decided to download directly from s3.

**Comment by davidoesch** [comment]
+1 for human readable.. marker_12345

**Comment by loicgasser** [comment]
ok will leave the chsdi solution then

**Comment by oterral** [comment]
I thnik @loicgasser talk about https://github.com/geoadmin/mf-geoadmin3/pull/3442


We have a fix for this in  `teo_draw` branch. we merge it in master and redeploy .

**Comment by loicgasser** [comment]
Marker will point to the new CHSDI maki service instead, like it will when the draw will be merged.
Yes I will fix the download at the same time.

**Comment by gjn** [comment]
Hi

thanks for fixing this so quickly. An overlook on the S3 switch...

G.

**Comment by loicgasser** [comment]
Fixed on prod.
