### ISSUE TITLE
Mouse over / no object info in LUBIS

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3448]
We have a inconsistency

https://s.geo.admin.ch/6decadaa7c

on mousoever  and click I get some areas with "hand active / no objetc info" for areas with no data
![image](https://cloud.githubusercontent.com/assets/4577727/17966630/cebbaf42-6ac2-11e6-9354-95ec7eaeaaea.png)

and for some are with no area not
![image](https://cloud.githubusercontent.com/assets/4577727/17966620/c4cc3b8c-6ac2-11e6-8a7a-21a08632ba5e.png)

moreover some customer report that they  _always_ get no object info even if they click on icons... But I could not reproduce  on chrome or ie

**Comment by ltclm** [comment]
@oterral could you have a look please? 
the tiles have no pixel values between the icons. seems to be something strange with the pixel detection.

**Comment by oterral** [comment]
Can't reproduce.

**Comment by ltclm** [comment]
i was able to reproduce on mac os x 10.10.5
* safari 9.1.2
* chrome latest (52.0.2743.226)

**Comment by oterral** [comment]
Can reproduce on mac probably a pixel ratio issue.

**Comment by oterral** [comment]
OL issue https://github.com/openlayers/ol3/issues/5821
