### ISSUE TITLE
adding a Cache-Control header to the kml files

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3452]
Age: 0  Some browsers ignore that. So we could improve eat enormously by adding a Cache-Control header to the kml files.

•	We should at least add must-revalidate to the Cache-Control header to force the browser to look for a newer version. We might need to add more headers (like no-cache, no-store, etc), but we can start with that.

See customer Customer feedback ID : 2016082112252630

**Comment by davidoesch** [comment]
Option according to @gjn :I think adding the no-cache header makes also sense.

**Comment by loicgasser** [comment]
http://www.bucketexplorer.com/documentation/amazon-s3--how-to-set-cache-control-header-for-s3-object.html


To change exisiting headers, this can/should be done at bucket level. Follow the instructions in the above link. (Case C)

I'll provide a PR to adapt the cache-control header for new KML.

**Comment by gjn** [comment]
This should be good. We add the new header by default and we also add in on varnish level for old kml files.
