### ISSUE TITLE
Change Hiking text in profile

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3461]
from
![image](https://cloud.githubusercontent.com/assets/4577727/18173670/ca0bdec4-706a-11e6-9bd3-d407e2f8fc7f.png)

to
[ClockSymbol] ca. [hh ,mm]

-> ad a "ca." since  our formula is not the official  formula used by the swiss hiking association

**Comment by davidoesch** [comment]
Ping @oterral

**Comment by oterral** [comment]
yes @davidoesch. Must we translate this  abbreviation ?

**Comment by davidoesch** [comment]
DE: ca.
FR: env.
IT: ca.
EN: approx.
RM: ca.
