### ISSUE TITLE
Deploy/build: check variables before build

### ISSUE THREAD

**Issue by gjn** [geoadmin/mf-geoadmin3#3462]
I just wanted to deploy a branch to S3. It's quite a long process and in the end, there was a missing env variable which resulted in an abortion.

Before we do anything, we should check if all needed variables are set - and abort early if that is not the case.

**Comment by gjn** [comment]
At my place, I can't deploy branch to s3. There's always the same error:

```
.build-artefacts/python-venv/bin/python ./scripts/s3manage.py upload /home/ltjeg/tmp/branches/gjn_img/mf-geoadmin3 int;
S3_MF_GEOADMIN3_INT env variable is not defined
Manage map.geo.admin.ch versions in AWS S3 bucket. Please make sure all your env variables are set.
```

But the variable exists on the existing console. What's wrong?

**Comment by gjn** [comment]
Even when I do it with pure python, the env variable cant be found:

```
>>> import os
>>> os.environ.get(S3_MF_GEOADMIN3_INT)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'S3_MF_GEOADMIN3_INT' is not defined
```

But `$S3_MF_GEOADMIN3_INT` works...

**Comment by loicgasser** [comment]
This is most likely related to your setup. Did you try outside screen /tmux ?

**Comment by gjn** [comment]
Yes, that might be it. My screen session is very old. I'll try in a new screen.

**Comment by gjn** [comment]
Yep, that was it.

Anyhow, checking for existence of variable early is good practice. Would avoid long loops.

**Comment by loicgasser** [comment]
Indeed I will add the guard functions in the Makefile
