### ISSUE TITLE
Fixed names branch deploys

### ISSUE THREAD

**Issue by gjn** [geoadmin/mf-geoadmin3#3463]
Before the change to s3 backed solution, it was possible to deploy branch under a given, fix name.

This had the advantage that a) it can be easily communicated, even over phone and b) can be easily remembered. I think that's important for us but mainly for 3rd parties as @davidoesch @mariokeusen etc - and we would need it anyway if we use this mechanic for an Abnameplatform.

Another disadvantage of the current solution: each new branchdeploy requires people to update existing links (mainly in github PR, but also elsewhere). 

Could this be re-done with the s3 backed solution?

Comments also welcome from @oterral @procrastinatio

**Comment by davidoesch** [comment]
Well the Advantage with the current solution: branches are broken faster.... Risk is minimized that they will used for operational use :-)

**Comment by oterral** [comment]
Totally agree with @gjn we should store only the last version of the branch.

**Comment by loicgasser** [comment]
You can keep the version by using KEEP_VERSION =true. So deployed branch should only be based on branch names I guess. I may have to also adapt the activate mecanism if we want to be able to activate a branch at the root in integration.

**Comment by gjn** [comment]
True, but hash would change when you add a commit or rebase, or. Hash and timestamps are simply too hard to remember and communicate. We need something easier.

It should/could also be optional. You only create 'named' deploy if you want/need. So we would have:

`make s3deploybranch` that does what's actually done
`make s3deploybranchNamed` that deploys a branch to something like /simplename/

Activation on root would not be needed for those.

**Comment by loicgasser** [comment]
I like that option. When deploying a branch we do make cleanall, so version can t be kept anyway. That could be optimised as well as after the first clone we usually only need to clean the templates and code base. I ll adapt and change the default behaviour, but making it possible to build from scratch as well.
