### ISSUE TITLE
ch.bafu.gefahren-basiskarte complete extent in zoom=0 missing

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3466]
reproduce
https://map.geo.admin.ch/?topic=ech&lang=de&bgLayer=voidLayer&layers=ch.bafu.gefahren-basiskarte&layers_opacity=0.75&X=126025.00&Y=679810.00&zoom=0

![image](https://cloud.githubusercontent.com/assets/4577727/18240673/75560216-734d-11e6-8694-25d189b35a97.png)

and in zoom=1
https://map.geo.admin.ch/?topic=ech&lang=de&bgLayer=voidLayer&layers=ch.bafu.gefahren-basiskarte&layers_opacity=0.75&X=126025.00&Y=679810.00&zoom=1
![image](https://cloud.githubusercontent.com/assets/4577727/18240683/8b3736b8-734d-11e6-9a8b-8133f98ed8c4.png)

**Comment by oterral** [comment]
It seems something change. We haven't the complete exetent et zoom level 0 too. Could we consider this bug as fixed ?

**Comment by davidoesch** [comment]
consider as fixed
