### ISSUE TITLE
[TIME] Layer badge and timeslider not syncronized 

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/mf-geoadmin3#3470]
Step to reproduce 

Open the app 
Show layer Journey through time 
Click on the clock 
Change the year 
Click on the clock 

Result :
Time badge falls back on its initial value 

Expected result :
Time badge keeps the value set by the time slider. 

Going a little further with that when one changes the badge year, the timeslider should be adapted accordingly.

**Comment by oterral** [comment]
Not a bug. It's wanted.
