### ISSUE TITLE
Marker overlays are highlightable

### ISSUE THREAD

**Issue by p1d1d1** [geoadmin/mf-geoadmin3#3471]
On Chrome:
1) Open map.geo.admin.ch
2) Click the geolocation button
3) Click withing the circle --> a tooltip is shown about the circle itself

**Comment by oterral** [comment]
It's awesome you can get the coordinate of your position !!!!

**Comment by gjn** [comment]
On mobile:
- we remove profile for all features
- we remove popup for gelocation circle

On desktop:
- we remove profile for geolocation circle

For all: adapt title of our own markers.

**Comment by p1d1d1** [comment]
I don't see any coordinate, just perimeter and surface of the circle.
Am I missing something?
Why don't disabling everything also on desktop?

**Comment by oterral** [comment]
Yes the highlight on circle will be deactivated everywhere. But if you click on the point in the middle you have the coordinate.

**Comment by loicgasser** [comment]
@davidoesch https://github.com/geoadmin/mf-geoadmin3/issues/3490 is in contradiction with what has been discussed here. As the draw/measure is not accessible on mobile, the only way one could access this feature at the moment is if you click a kml feature you previously created on desktop.

**Comment by davidoesch** [comment]
Will check it after my holidays

Gasser Loïc <notifications@github.com> schrieb am Do., 22. Sep. 2016, 16:03:

**Comment by gjn** [comment]
will be fixed tomorrow.
