### ISSUE TITLE
Time selector disappears in IE9

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3472]
IE only

im IE verschwindet das Fenster mit den Jahreszahlen (Zeitreise-Kartenwerke), sobald der Scrollbalken betätigt wird.
Mit Firefox und Chrome funktioniert es problemlos.

![image](https://cloud.githubusercontent.com/assets/4577727/18306748/89f48476-74ed-11e6-9096-76a133272da3.png)te

**Comment by davidoesch** [comment]
Reproduced when solved inform
Customer feedback ID : 201611061203036

**Comment by gjn** [comment]
Mousewheel scrolling works.

Looks like scroll is also interpreted as click on IE.

For all browsers: I also disappears when clicking on header/tile of the pull-out. And the state is inconsistent. When I click on a year number, 'state' is open but it disappears. I need to click twice on the year to make it re-appear again.

**Comment by loicgasser** [comment]
Year selection and scroll are working fine on IE9.
Now header selection behaviour seems to behave in a strange fasion. But this has nothing to do with this issue.

Can we create separate issues please? 

Can we have

- `Affected platform`
- `Step to reproduce`
- `Result`
- `Expected result`

**Comment by davidoesch** [comment]
even an issue on IE11 see https://www.youtube.com/watch?v=dXkg5x_juCQ

**Comment by loicgasser** [comment]
Scroll using scroll bar only

**Comment by davidoesch** [comment]
hi the fix in https://github.com/geoadmin/mf-geoadmin3/pull/3679 does not work
