### ISSUE TITLE
Error in README? openjdk 6 instead of openjdk 7

### ISSUE THREAD

**Issue by disperate** [geoadmin/mf-geoadmin3#3475]
I’m trying to setup mf-geoadmin3 on Ubuntu 14.04.5 LTS.
After installing the specified dependencies and cloning the repo I ran `$make user`.
I got this error Message:

`Exception in thread "main" java.lang.UnsupportedClassVersionError: com/google/javascript/jscomp/CommandLineRunner : Unsupported major.minor version 51.0`

The whole output: [console output.txt](https://github.com/geoadmin/mf-geoadmin3/files/461205/console.output.txt)
According this [stackoverflow discussion](http://stackoverflow.com/questions/10382929/how-to-fix-java-lang-unsupportedclassversionerror-unsupported-major-minor-versi) this error occurs when the JDK during compile time is higher than the JDK during runtime. So I installed openjdk 7.

The error did not occur anymore. 
Should I make a pull request to update the dependencies in the ReadMe?

**Comment by oterral** [comment]
PR is always welcome.

**Comment by procrastinatio** [comment]
We are now moving the project from Debian Wheezy to Jessie. Maybe have a look at this branch https://github.com/geoadmin/mf-geoadmin3/tree/gal_jessie
