### ISSUE TITLE
Distance bug in profile

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3477]
OPen
 https://map.geo.admin.ch/?topic=ech&lang=de&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bav.haltestellen-oev,ch.swisstopo.swisstlm3d-wanderwege,KML%7C%7Chttps:%2F%2Fpublic.geo.admin.ch%2FIHnQnrqkS7G3tDMKuPm7UQ&layers_visibility=false,false,false,false,true&layers_timestamp=18641231,,,,&X=229851.57&Y=753467.75&zoom=6.

open profile 
show length
![image](https://cloud.githubusercontent.com/assets/4577727/18347757/a8d2b8a6-75c7-11e6-90c1-ff42e602bac8.png)

Probably a comma unit issue

please inform customer WG: Customer feedback ID : 2016090713470694 

when fixed

**Comment by oterral** [comment]
Fixed with https://github.com/geoadmin/mf-geoadmin3/pull/3476

**Comment by oterral** [comment]
Helpdesk has been warned
