### ISSUE TITLE
Remove externs/Cesium.externs.js

### ISSUE THREAD

**Issue by fredj** [geoadmin/mf-geoadmin3#3480]
not used anymore

**Comment by gberaudo** [comment]
+1

**Comment by oterral** [comment]
It seems used here: 

https://github.com/geoadmin/mf-geoadmin3/blob/5c07c645c1cf1c62199a9e5591a078f2559cb902/Makefile#L632

but I don't know if we really need it or not.

**Comment by fredj** [comment]
Don't know either :-) but at least we should use the externs from
 `.build-artefacts/ol3-cesium/Cesium.externs.js`

**Comment by oterral** [comment]
I think this extern was previously copied from ` .build-artefacts/ol3-cesium/Cesium.externs.js` . But the modificiation of the build may have change that.

We should copy this file in the `updateol3` target
