### ISSUE TITLE
[catalogs/layertrees] add a layer by keyboard does not work anymore

### ISSUE THREAD

**Issue by mariokeusen** [geoadmin/mf-geoadmin3#3487]
UC/steps to reproduce: open app, open the catalog accordeon, navigate with the arrow keys, try to add a layer to the map with the space key
Result: app does not react on pushing the space tab
Expected: according to the current test book a layer should be added to the map

Question: did we get rid of this feature for some reason?

**Comment by loicgasser** [comment]
Can't reproduce on Chrome, but I can on FF. What did you test with?

**Comment by davidoesch** [comment]
reproduced on ff

**Comment by mariokeusen** [comment]
reproduced on ie11

**Comment by loicgasser** [comment]
Fixed
