### ISSUE TITLE
Profile info in mobile Missing

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3490]
Hiking etc not shown  on mobile Nexus 6p
Expected result:
Footer info is responsive
![screenshot_20160916-152511](https://cloud.githubusercontent.com/assets/4577727/18590596/c827cc28-7c2f-11e6-9bff-87fc369a8f13.png)

**Comment by oterral** [comment]
fPR merged and deploy on prod
