### ISSUE TITLE
Onyl GRID View

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3494]
Bonjour ,

Some users  can not access the tiles on mobile, see only grid view 

![image](https://cloud.githubusercontent.com/assets/4577727/18625747/d246c60a-7e50-11e6-8b78-aad081f82ec2.png)

User-Agent: Mozilla/5.0 (iPad; CPU OS 9_3_5 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13G36 Safari/601.1
Application Version: 1472720262

my assummption they work with android native browser and not with chrome

**Comment by mariokeusen** [comment]
Had the same issue from a helpdesk phone: user of a blackberry z10.

**Comment by procrastinatio** [comment]
I doubt it is related to tile access. Make them check on http://api3.geo.admin.ch/ (also older version of OL3).
Looks like a JS crash before requesting tiles.

BlackBerry OS 10.3.2 Mozilla/5.0 (BB10; Touch) AppleWebKit/537.35+ (KHTML, like Gecko) Version/10.3.2.2876 Mobile Safari/537.35+

Why is appcache only HTTP (like http://map.geo.admin.ch/geoadmin.1472720262.appcache) ?

**Comment by loicgasser** [comment]
What do you mean?
There's always a rewrite from http -> https and it has always been the case.

Here is the new one:
https://map.geo.admin.ch/geoadmin.1474375204.appcache

Do we have this device?

**Comment by loicgasser** [comment]
Link to test please otherwise no fix.

**Comment by oterral** [comment]
could it be related to https://github.com/geoadmin/mf-geoadmin3/pull/3515 ?

**Comment by gjn** [comment]
I would guess that this is an offline/appcache issue.

Note that not only tiles are missing, but whole application.

**Comment by procrastinatio** [comment]
Looks like it is *klein karriert*, so at least a part of the application loads.

**Comment by davidoesch** [comment]
No feedback from user so far ( user feedback ID : 2016091320314134)

**Comment by loicgasser** [comment]
Close because of lack of activity fell free to re-open

**Comment by davidoesch** [comment]
Nice one
