### ISSUE TITLE
Overlay geometries disappear on language change

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/mf-geoadmin3#3497]
Step to reproduces:

1. Open https://map.geo.admin.ch?layers=ch.swisstopo.fixpunkte-agnes
2. Click an agnes station in the map
3. Change the language

Result:
a. Marker highlight disappears
b .Legend requests are triggered for each layer in layer tree even if the legends are not open or the layer not visible.
c. Tooltip is not translated (not sure we decided to translate these on language change)

Expected Result:
a. Marker is still visible
b. Legend requests are not triggered if the legend popups are not visible
c. Translate popups content?

ping @davidoesch

**Comment by davidoesch** [comment]
Translate pop up content - yes
