### ISSUE TITLE
KML from public.geo.admin.ch blocked page rendering

### ISSUE THREAD

**Issue by oterral** [geoadmin/mf-geoadmin3#3508]
https://map.geo.admin.ch/?topic=ech&lang=en&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bav.haltestellen-oev,ch.swisstopo.swisstlm3d-wanderwege,KML%7C%7Chttps:%2F%2Fpublic.geo.admin.ch%2FJ8a3jwWlQuSUjgODSaFfCA&layers_visibility=false,false,false,false,true&layers_timestamp=18641231,,,,&X=256014&Y=754464&zoom=12&crosshair=marker

**Comment by procrastinatio** [comment]
Strange: with the following URL https://map.geo.admin.ch/?layers=KML%7C%7Chttps:%2F%2Fpublic.geo.admin.ch%2FJ8a3jwWlQuSUjgODSaFfCA&layers_visibility=true, the KML is in the layer list, but empty (no request to public.geo.admin.ch)

**Comment by procrastinatio** [comment]
_marker=crosshair_ is the killer

**Comment by oterral** [comment]
I'm on it.
