### ISSUE TITLE
Pixelkarte grau quality issue at zoom 7

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/mf-geoadmin3#3509]
See Link:
https://map.geo.admin.ch/?topic=ech&bgLayer=ch.swisstopo.pixelkarte-grau&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bav.haltestellen-oev,ch.swisstopo.swisstlm3d-wanderwege&layers_visibility=false,false,false,false&layers_timestamp=18641231,,,&lang=fr&X=199524.14&Y=597065.58&zoom=7
Around Berne only see:

https://map.geo.admin.ch/?topic=ech&bgLayer=ch.swisstopo.pixelkarte-grau&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bav.haltestellen-oev,ch.swisstopo.swisstlm3d-wanderwege&layers_visibility=false,false,false,false&layers_timestamp=18641231,,,&lang=fr&X=197710.00&Y=620090.00&zoom=7

Data generation issue.
See also:
https://wmts104.geo.admin.ch/1.0.0/ch.swisstopo.pixelkarte-grau/default/current/21781/21/117/131.jpeg

**Comment by ltclm** [comment]
it is due to a mix of different color maps in the raw data when using vrt raster data source.
we can 
* switch back to index shape files
* expand raster data to rgb
and recreate the tiles.

**Comment by gjn** [comment]
Is Datenherr aware of this?

**Comment by davidoesch** [comment]
please Check data delivery in GDWH @AFoletti

**Comment by davidoesch** [comment]
`marcel will fix it on his return

**Comment by AFoletti** [comment]
Source data looks to be OK.

**Comment by ltclm** [comment]
yes, the source data is ok. 
we have to 
* change the mapfile and replace vrt with index shape
* recreate the tiles of wmts zoomlevel 21

We switchted from index shape to vrt as a workaround because of this issue:
https://github.com/mapserver/mapserver/pull/1715

We have observed an offset in the tiles overlapping the mosaic boarders. This offset is only visible in smaller resolutions (< 1m) . We can easily switch back to index shape for lk25,lk50,...

**Comment by ltclm** [comment]
mapserver config has been changed back to tileindex [1]
cache has been flushed / invalidated [2]

[1] https://github.com/geoadmin/wms-mapfile_include/commit/8b0e76d701c54cb30e4da0bf811fdc29c5bb7e96
[2] 
```bash
$ bash scripts/flushallbypath.sh 1.0.0/ch.swisstopo.pixelkarte-grau/default/current/21781/21/*
Deleting backend cache...
INFO:tool_aws.s3.rm:Deletion started...
INFO:tool_aws.s3.rm:Actually, there's nothing to do... aborting
INFO:tool_aws.s3.rm:Hint: if your prefix starts with '/'
INFO:tool_aws.s3.rm:simply remove the first character.
INFO:tool_aws.s3.rm:Deletion finished...
Invalidating cloudfront...
{
    "Invalidation": {
        "Status": "InProgress",
        "InvalidationBatch": {
            "Paths": {
                "Items": [
                    "/1.0.0/ch.swisstopo.pixelkarte-grau/default/current/21781/21/*"
                ],
                "Quantity": 1
            },
            "CallerReference": "cli-1476683862-152492"
        },
        "Id": "I39XVO0HS0EBAR",
        "CreateTime": "2016-10-17T05:57:43.149Z"
    },
    "Location": "https://cloudfront.amazonaws.com/2016-09-07/distribution/E13EEI2NFKRNBN/invalidation/I39XVO0HS0EBAR"
}
Before invalidating the whole cache, it can take up to 20 minutes

```

**Comment by loicgasser** [comment]
Nice thanks
