### ISSUE TITLE
WMS GetFeatureInfo sometimes not working

### ISSUE THREAD

**Issue by p1d1d1** [geoadmin/mf-geoadmin3#3512]
https://mf-geoadmin3.int.bgdi.ch/?topic=emapis&layers=WMS%7C%7CHochbau%20(Query)%7C%7Chttps:%2F%2Fwms-bgdi.int.bgdi.ch%2F%3Fequery%3D(typ_code%3D47%20AND%20geschaeftsnummer%3D%270200002782%27)%7C%7Cch.blw.emapis-hochbau

Try to find the object :-) --> GetFeatureInfo in not working. map.geo.admin.ch issues a request going via ogcproxy. error is:

Request URL:https://mf-chsdi3.int.bgdi.ch/ogcproxy?url=https%3A%2F%2Fwms-bgdi.int.bgdi.ch%2F%3Fequery%3D(typ_code%3D47%20AND%20geschaeftsnummer%3D%270200002782%27)%26SERVICE%3DWMS%26VERSION%3D1.3.0%26REQUEST%3DGetFeatureInfo%26FORMAT%3Dimage%252Fpng%26TRANSPARENT%3Dtrue%26QUERY_LAYERS%3Dch.blw.emapis-hochbau%26LAYERS%3Dch.blw.emapis-hochbau%26INFO_FORMAT%3Dtext%252Fplain%26I%3D50%26J%3D50%26CRS%3DEPSG%253A21781%26STYLES%3D%26WIDTH%3D101%26HEIGHT%3D101%26BBOX%3D598088.45%252C168500.40000000002%252C598098.55%252C168510.5
Request Method:GET
Status Code:406 Not Acceptable
Remote Address:10.135.61.60:8080

Using instead the following URL (without the AND in the query), the request is working:
https://mf-geoadmin3.int.bgdi.ch/?topic=emapis&layers=WMS%7C%7CHochbau%20(Query)%7C%7Chttps:%2F%2Fwms-bgdi.int.bgdi.ch%2F%3Fequery%3D(typ_code%3D47)%7C%7Cch.blw.emapis-hochbau

The request is sent directly to the WMS (no ogc proxy):
Request URL:https://wms-bgdi.int.bgdi.ch/?equery=(typ_code=47)&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetFeatureInfo&FORMAT=image%2Fpng&TRANSPARENT=true&QUERY_LAYERS=ch.blw.emapis-hochbau&LAYERS=ch.blw.emapis-hochbau&INFO_FORMAT=text%2Fplain&I=50&J=50&CRS=EPSG%3A21781&STYLES=&WIDTH=101&HEIGHT=101&BBOX=598088.25%2C168500.30000000002%2C598098.3500000001%2C168510.4
Request Method:GET
Status Code:200 OK
Remote Address:10.135.61.60:8080

**Comment by loicgasser** [comment]
Will look into it. Thanks for reporting it

**Comment by procrastinatio** [comment]
To use `ogcproxy` the remote server has to set a `Content-Type` otherwise you get a `Not Acceptable Error`

**Comment by p1d1d1** [comment]
Ok but whya the first request is: https://mf-chsdi3.int.bgdi.ch/ogcproxy?......
and the second one is: https://wms-bgdi.int.bgdi.ch/.....
it's the same use case

**Comment by p1d1d1** [comment]
Did a further test.

CASE 1: Only 1 parameter in the "equery" --> GetFeatureInfo request without ogcproxy: it works
CASE 2: AND/OR in "equery"--> GetFeatureInfo request via ogcproxy: it does not work

**Comment by oterral** [comment]
@procrastinatio so where we should fix this error?

**Comment by loicgasser** [comment]
So there are 2 problems which make it really a huge pain...

First pyramid when doing
 `request.params.get('url')`

stops at `)`

Try for instance this path `/ogcproxy?url=https://wms-bgdi.dev.bgdi.ch/?equery=(typ_code=47%20AND%20geschaeftsnummer=%270200002782%27)&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetFeatureInfo&FORMAT=image%2Fpng&TRANSPARENT=true&QUERY_LAYERS=ch.blw.emapis-hochbau&LAYERS=ch.blw.emapis-hochbau&INFO_FORMAT=text%2Fplain&LANG=de&I=50&J=50&CRS=EPSG%3A21781&STYLES=&WIDTH=101&HEIGHT=101&BBOX=571500.0000000001%2C141749.99999999997%2C622000.0000000001%2C192249.99999999997`

it simply returns:

`u'https://wms-bgdi.dev.bgdi.ch/?equery=(typ_code=47 AND geschaeftsnummer='0200002782')"`  -_-

The second issue comes from the quoting of the url as httplib2 doesn't quote URLs per default. -_-

But that's ok and can be handled in the code. `requests` python module is much better and I would like to eventually migrate the proxy. Or simply create a new one that is only a proxy service as @gjn suggested if I recall correctly.

I will investigate how I can overcome the first problem with pyramid, it may take a while.

**Comment by procrastinatio** [comment]
@loicgasser using the double encoded url in parameter is suboptimal. Either we use the flask-style proxy (http://<hostname>:<port/p/wms.dev.bgdi.ch? or  not proxy

**Comment by gjn** [comment]
@p1d1d1 I can't reproduce it. Both links on mf-geoadmin3.int.bgdi.ch above don't go over the https proxy:

https://mf-geoadmin3.int.bgdi.ch/?topic=emapis&layers=WMS%7C%7CHochbau%20(Query)%7C%7Chttps:%2F%2Fwms-bgdi.int.bgdi.ch%2F%3Fequery%3D(typ_code%3D47%20AND%20geschaeftsnummer%3D%270200002782%27)%7C%7Cch.blw.emapis-hochbau

https://mf-geoadmin3.int.bgdi.ch/?topic=emapis&layers=WMS%7C%7CHochbau%20(Query)%7C%7Chttps:%2F%2Fwms-bgdi.int.bgdi.ch%2F%3Fequery%3D(typ_code%3D47)%7C%7Cch.blw.emapis-hochbau

Can we close this?

**Comment by p1d1d1** [comment]
@gjn I'am speaking of the GetFeatureInfo request.

With link 1 you should see a point. Click on it --> a GetFeatureInfo request is sent via the proxy --> 406 Not acceptable

![screenshot_2016-10-08_11-58-44](https://cloud.githubusercontent.com/assets/1533649/19212306/97006116-8d4e-11e6-8af3-d3ddf7c14606.png)

With link 2 you should see 2 points. Click on one of those --> the GetFeatureInfo request is not proxied --> 200 OK.

Issue still open.

**Comment by gjn** [comment]
I see it now. The URL should not be passed via proxy.

**Comment by gjn** [comment]
Problem is this regexp:
https://github.com/geoadmin/mf-geoadmin3/blob/cc6cc3aef7247478b4e34ec6a8ecb0e0e99debe7/src/components/UrlUtilsService.js#L15

The given wms requests does not validate against it, so the proxy is used. The regexp should validate the request...

**Comment by p1d1d1** [comment]
Fixed via https://github.com/geoadmin/mf-geoadmin3/issues/3543

**Comment by loicgasser** [comment]
Great, I think we should still fix ogcproxy. (or create a New one) Otherwise Equery won't work for non geoadmin URLs.
