### ISSUE TITLE
Adding CadastralWebMap from search is extremely slow

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/mf-geoadmin3#3514]
Step to reproduce:

1. Open https://map.geo.admin.ch?lang=en
2. Search for  Cad
3. Hover on some other layers (Cadastral surveying lots in fact)
3. Add cadastral web map map

Result:
A ton of tiny tiles are downloaded and rendering is extra slow

Expected Result:
Same as adding it via permalink
https://map.geo.admin.ch?layers=ch.kantone.cadastralwebmap-farbe

My take is that we're using the config of another layer..

ping @oterral @gjn

**Comment by loicgasser** [comment]
I think we have in general a huge problem with preview layers. It's affecting the catalog as well. I would fix that ASAP

**Comment by procrastinatio** [comment]
@loicgasser We cascade Cadastrawebmap, we do not host or manage the WMS server. If it is dead slow, there is nothing we can do.

For the rest, I don't know.

**Comment by loicgasser** [comment]
It is solved see PR above

**Comment by loicgasser** [comment]
So not related to preview layers directly but to the resolutions we would pass to our tiled layers. We were altering the initial resolutions definition.
