### ISSUE TITLE
Search: don't trigger requests with empty string

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/mf-geoadmin3#3516]
At the moment we a lot of Bad requests on our servers because we trigger search requests even if we have an empty string.

**Comment by gjn** [comment]
I can't reproduce...

**Comment by loicgasser** [comment]
I ll show you.

**Comment by loicgasser** [comment]
Steps to reproduce:

1. open https://map.geo.admin.ch
2. Type foo in search field
3. Press back space keyboard down (a long time) to delete text

Result:

2-3 x 400 requests with an empty string are generated

Expected result:

No request is sent

**Comment by gjn** [comment]
hint for @Ariadnigaki : look for startQuery function in the SearchDirective.js file.
