### ISSUE TITLE
IFrame: send URL of saved kml

### ISSUE THREAD

**Issue by gjn** [geoadmin/mf-geoadmin3#3517]
In order to use a drawn url outside of map.geo context, we could publish the kml url via the iframe interface to host applications

@davidoesch Do it? Prio? (See internal mail)

**Comment by davidoesch** [comment]
To use a drawn outside map.geo.admin.ch from iframe:
A) H2M user clicks on map.geo.admin.ch label and the via the draw export function he can access the kml
B) m2m URLdecode and parse the string to the KML URL and use wget alike to download /Access KML.

**Comment by gjn** [comment]
IFram communcation is here gaIFrameCom:
https://github.com/geoadmin/mf-geoadmin3/blob/master/src/components/IFrameComService.js

Use a new type message: `kml_url``

Then send the message. Message can probably be send from here: https://github.com/geoadmin/mf-geoadmin3/blob/master/src/components/draw/DrawDirective.js#L727

**Comment by davidoesch** [comment]
IMHO this is not the use case whcih wandern.ch.wants see mail.

**Comment by gjn** [comment]
It's an excercise for Ariadni.
