### ISSUE TITLE
Copyright links not working in topic=defence

### ISSUE THREAD

**Issue by p1d1d1** [geoadmin/mf-geoadmin3#3521]
Both links return 404:

![image](https://cloud.githubusercontent.com/assets/1533649/19037085/b86f8404-8974-11e6-98a1-5a2f1a34ceb8.png)

**Comment by loicgasser** [comment]
Links have changed http://www.vtg.admin.ch/de/armee.html

**Comment by gjn** [comment]
argl, it's not the same links...one is attributation, one not. one needs fix in mf-geoadmin3, one not.

**Comment by loicgasser** [comment]
The other layer link was updated in chsdi, it's good now, though the first I loaded the app today the attributions were not translated. And I can't explain it. Can you?

**Comment by loicgasser** [comment]
commit reference

**Comment by loicgasser** [comment]
https://github.com/geoadmin/mf-chsdi3/commit/615edcc55bb6dfe19517e86964ac531d6d0eb00e

**Comment by gjn** [comment]
Yes, I can explain it as I had to flush varnish today to fix a related issue (https://github.com/geoadmin/mf-geoadmin3/issues/3530). Seems to me that our s3 based deploy is not yet fully correct.

We flush varnish after uploading to s3. But maybe we need to flush it after s3activate as well.

**Comment by loicgasser** [comment]
+1 thank you for your explanation
