### ISSUE TITLE
Profile: hover does not follow on line

### ISSUE THREAD

**Issue by gjn** [geoadmin/mf-geoadmin3#3525]
Before, I seem to remember, that when you hovered on the profile, the corresponding point on the line was shown. Now, always the first point is shown.

Any idea why?

**Comment by oterral** [comment]
Yes  caused by this commit https://github.com/geoadmin/mf-geoadmin3/commit/88bcc8a61ae613608500b1d018f6356cbab28a85#diff-bfd39f2f09138781ec89cd2819dbd0d7L136
