### ISSUE TITLE
[ch.astra.nationalstrassenachsen] layer not translated in selection

### ISSUE THREAD

**Issue by mariokeusen** [geoadmin/mf-geoadmin3#3530]
UC: open app, load the new layer ch.astra.nationalstrassenachsen to the map, open the layer selection
Result: layer is not translated in the layer selector
Expected: layer is translated the same way in layer selector as in the catalog above
![astra_axis_translation](https://cloud.githubusercontent.com/assets/4577749/19140989/163791fc-8b92-11e6-86d3-3a582fa46930.PNG)

**Comment by pfanguin** [comment]
On int this is translated: https://mf-geoadmin3.int.bgdi.ch/?topic=ech&lang=en&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.astra.nationalstrassenachsen

@loicgasser, @gjn, do you have an idea ?

**Comment by gjn** [comment]
Strange. I'll re-deploy the mf-geoadmin3 snapshot.

**Comment by gjn** [comment]
I re-deployed the snapshot, and now it's good.

**Comment by pfanguin** [comment]
Ok Thanks

**Comment by loicgasser** [comment]
Chsdi not fully deployed before you deployed geoadmin or was it another issue ?

**Comment by gjn** [comment]
Now I know. I've uploaded to s3 before chsdi was deployed. Ha!
