### ISSUE TITLE
KML admin links do not work

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3531]
The admin links below do not exist anymore. User did *not* delete it

	City Trailrun: 
	https://map.geo.admin.ch/?topic=ech&lang=de&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bav.haltestellen-oev,ch.swisstopo.swisstlm3d-wanderwege,KML%7C%7Chttps:%2F%2Fpublic.geo.admin.ch%2FKsZBIJvvTGC6KNsdZD03Cw&layers_visibility=false,false,false,false,true&layers_timestamp=18641231,,,,&X=246450.99&Y=681390.53&zoom=6
	Velo: 
	https://map.geo.admin.ch/?topic=ech&lang=de&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bav.haltestellen-oev,ch.swisstopo.swisstlm3d-wanderwege&layers_visibility=false,false,false,false,true&layers_timestamp=18641231,,,,&X=247300.00&Y=685720.00&zoom=7&adminId=U7qnUN1zQeCJ10J4gWB7Gg
	Schwimmen: 
	https://map.geo.admin.ch/?topic=ech&lang=de&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bafu.wrz-wildruhezonen_portal,ch.swisstopo.swisstlm3d-wanderwege,KML||https:%2F%2Fpublic.geo.admin.ch%2FfLXyCJrtQUi5lu5bg_g8LQ&layers_visibility=false,false,false,false,true&layers_timestamp=18641231,,,,&X=244272.50&Y=694455.00&zoom=8
	Laufen: 
	https://map.geo.admin.ch/?topic=ech&lang=de&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bav.haltestellen-oev,ch.swisstopo.swisstlm3d-wanderwege&layers_visibility=false,false,false,false,true&layers_timestamp=18641231,,,,&X=244692.50&Y=695962.50&zoom=8&adminId=GsD-Ga3WToKhAOJhkmkEdQ 
	Bike: https://map.geo.admin.ch/?topic=ech&lang=de&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bav.haltestellen-oev,ch.swisstopo.swisstlm3d-wanderwege&layers_visibility=false,false,false,false,true&layers_timestamp=18641231,,,,&X=245262.50&Y=680557.50&zoom=8&adminId=moCfJykeS4aROy2wMo-RMg

**Comment by oterral** [comment]
Caused by an empty icon href in that kml. I need to fix it on OpenLayers side

**Comment by davidoesch** [comment]
Fix estimated for today

**Comment by davidoesch** [comment]
The links above are not yet working again..this is why I reopon it

**Comment by gjn** [comment]
Will be deployed shortly. Was auto-closed because corresponding PR was merged...

**Comment by oterral** [comment]
@davidoesch fixed in prod
