### ISSUE TITLE
Move element window in draw

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3540]
ALL OS ALL BROWSER

Reproduce
draw line
finish it
click on line
try to move the last point
Result:
![image](https://cloud.githubusercontent.com/assets/4577727/19183357/31bec922-8c78-11e6-9332-a0a2bddb2947.png)

expected result:
I can move the Element window, so I can grab the last point of the line

**Comment by oterral** [comment]
Reducing the window is faster than moving it.

**Comment by oterral** [comment]
@davidoesch  is reducing not enough ?

**Comment by davidoesch** [comment]
- it is...but I even thought about it (déformation professionelle )
@gjn @cedricmoullet

**Comment by gjn** [comment]
How does google do it?

**Comment by davidoesch** [comment]
@gjn : correct: google my maps has the same issue
