### ISSUE TITLE
[draw share and short link] can be edited by opening the draw tools

### ISSUE THREAD

**Issue by mariokeusen** [geoadmin/mf-geoadmin3#3545]
UC 1: open app, start draw tools, draw something, push the share button in the draw toolts, copy the share (not the edit) link, open link in a new browser window, start the draw tools, click the drawing
UC 2: open app, start draw tools, draw something, leave the draw menu, go to share, copy the short permalink, open the permalink in a new browser window, start the draw tools, click the drawing

Result: the drawing can be modified
Expected: the drawing can not be modified. Drawing should only be editable by using the "edit" links from the draw menu.

Verified with several browsers.

**Comment by cedricmoullet** [comment]
No, this is as designed. In this case, a new drawing is created, but the original drawing is not changed.

**Comment by mariokeusen** [comment]
Ok, was not informed about that...
