### ISSUE TITLE
Print -->  vector layer with a map rotation doesn't work

### ISSUE THREAD

**Issue by AlexCaron88** [geoadmin/mf-geoadmin3#3548]
Solution : 
replace: 
    `geometry.intersectsExtent(getPrintRectangleCoords())`

by: 
    `ol.extent.getIntersection(getPrintRectangleCoords(), geometry.getExtent())`

**Comment by oterral** [comment]
Nice one thx for the reporting.

**Comment by oterral** [comment]
I see there is the  measure of the circle on top right which shouldn't printed.

Do you see antything else?

**Comment by AlexCaron88** [comment]
Not only for the  measure feature but for the vector feature in general. Depending on the rotation you see some of the vector feature disapear. But for the moment I don't see anything else.
