### ISSUE TITLE
WMS SG : does not work

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3550]
Adding https://geodienste.sg.ch/wss/service/SG00010_WMS/guest?request=GetCapabilities&service=WMS

to map.geo.admin.ch

https://map.geo.admin.ch/?topic=ech&lang=de&bgLayer=ch.swisstopo.pixelkarte-grau&layers=WMS%7C%7CWaldbestand%7C%7Chttps:%2F%2Fgeodienste.sg.ch%2Fwss%2Fservice%2FSG00010_WMS%2Fguest%3Frequest%3DGetCapabilities%26service%3DWMS%7C%7CWaldbestand%7C%7C1.3.0,WMS%7C%7CGeodienst-Hinweise_Max%7C%7Chttps:%2F%2Fgeodienste.sg.ch%2Fwss%2Fservice%2FSG00010_WMS%2Fguest%3Frequest%3DGetCapabilities%26service%3DWMS%7C%7CGeodienst-Hinweise_Max%7C%7C1.3.0&X=253685.15&Y=745756.36&zoom=11

results in no data display
using the testsuite https://www.geo.admin.ch/de/geo-dienstleistungen/geodienste/pruefdienste.html

We get

Service Type "KANTON SG. WALDBESTAND" (in GetCapabilities) does not match "WMS" (Form). Service Name Node not found in GetCapabilities! Please check your parameters (url=service?) or your settings/WMS.xml.

-> is this error an issue for mf-geoadmin3 ?

**Comment by oterral** [comment]
@davidoesch the GetMap seems unauthorized : 
https://geodienste.sg.ch/wss/service/SG00010_WMS/guest?request=GetCapabilities&service=WMS&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=Waldbestand&CRS=EPSG%3A21781&STYLES=&WIDTH=1920&HEIGHT=562&BBOX=745276.36%2C253544.65%2C746236.36%2C253825.65

Results: 
```
<?xml version="1.0" encoding="UTF-8"?>
<ServiceExceptionReport version="1.1.0">
<ServiceException code="AuthorizationFailed">
<![CDATA[Insuffucient rights to call <GetMap> on this service !]]></ServiceException>
</ServiceExceptionReport>
```

**Comment by davidoesch** [comment]
awaiting customer feedback

**Comment by procrastinatio** [comment]
I see, world wide wait.

**Comment by davidoesch** [comment]
Will check

**Comment by procrastinatio** [comment]
We are slowly progressing:
```
$ curl  "https://geodienste.sg.ch/wss/service/SG00010_WMS/guest?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=Waldbestand&CRS=EPSG%3A21781&STYLES=&WIDTH=1920&HEIGHT=587&BBOX=744452.86%2C253384.9%2C746372.86%2C253971.9"                                                                                          <?xml version="1.0" encoding="UTF-8"?>
<ServiceExceptionReport version="1.1.0">
<ServiceException code="ServiceError">
<![CDATA[Could not process client request]]></ServiceException>
</ServiceExceptionReport>
```

**Comment by davidoesch** [comment]
The shut down the guest account: Now *every* user has to register...
