### ISSUE TITLE
Tiling not correct (Hardplatz)

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3559]
open https://s.geo.admin.ch/6f0cd09daa all browsers

![image](https://cloud.githubusercontent.com/assets/4577727/19554633/ce14812c-96b9-11e6-9441-658392f2f815.png)

is it already in the original data or tileforge induced?

if solved:
mailto  webgis regarding Customer feedback ID : 2016061218265046 m

**Comment by gjn** [comment]
@ltclm Isn't this the known issue of the LK10 delivery?

**Comment by ltclm** [comment]
yes it is the known issue with the data in gdwh, it will be solved with the next annual update.
