### ISSUE TITLE
Tiles not updated 

### ISSUE THREAD

**Issue by oterral** [geoadmin/mf-geoadmin3#3560]
Is it normal that the road/train network  become white at the edge of a tile ? 

https://map.geo.admin.ch/index.html?lang=fr&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&X=284545.14&Y=690059.68&dev3d=true&zoom=8&debug&layers_visibility=false,false,false,false&layers_timestamp=18641231,,,&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bav.haltestellen-oev,ch.swisstopo.swisstlm3d-wanderwege&catalogNodes=687

**Comment by ltclm** [comment]
it is a map sheet boundary, right side you see the new lk25 on the left side the old one.
https://map.geo.admin.ch/index.html?lang=de&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&X=284545.14&Y=690059.68&dev3d=true&zoom=8&debug&catalogNodes=687&layers=ch.swisstopo.pixelkarte-pk25.metadata

**Comment by oterral** [comment]
ok you can close i it's normal :)
