### ISSUE TITLE
Draw - Circle: annotation

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3563]
With Draw V2 we have the policy taht for "measures" the result is shown as request as label- to have the results on PDF/print
Now we have one use case where the user draws a circle and does not want to have the label
see
[Schaffhausen, alle, 10.16.zip](https://github.com/geoadmin/mf-geoadmin3/files/544378/Schaffhausen.alle.10.16.zip)

as 
![image](https://cloud.githubusercontent.com/assets/4577727/19599652/1b56d2c6-97a2-11e6-942b-93d9aa404b13.png)

Ideas on how to optimize this?
eg
-  only show radius as before if a circle is drawn?

Customer to notify: Customer feedback ID : 2016102114272563

**Comment by oterral** [comment]
arf It is a KML created via geoadmin?

If not just change the ids in the kml and remove 'measure_' .

**Comment by davidoesch** [comment]
created in geoadminch : workaround to remove the label in general in kml?

**Comment by oterral** [comment]
No labels are created automatically if  the id of a feature is  `measure_XXX'

**Comment by davidoesch** [comment]
any other workaround to transform the measure to pure circles? ogr to ogr?

**Comment by gjn** [comment]
Possible solition. Add drawing a circle as an option (as we have line now). @davidoesch ?

**Comment by davidoesch** [comment]
one button more? and if we add drawing as a circle, we also have to add square/rectangle as an option ( we decided not to do this in the current iteration of draw...due to complexity reason. and since gmap does not do it I would get rid of this)
proposal: add a pure circle without anotation if in line mode and add the anotation and circle if in measure mode...
doable?

**Comment by gjn** [comment]
What about users that only want 1 line?

**Comment by davidoesch** [comment]
You are right.. Bad proposal

**Comment by davidoesch** [comment]
You are right... Bad idea

**Comment by gjn** [comment]
So close this? or adding draw circle feature?

**Comment by davidoesch** [comment]
only show radius as before if a circle is drawn?

**Comment by gjn** [comment]
So only line? Or only circle?

**Comment by davidoesch** [comment]
On screen: line circle and values. In PDF line circle.
