### ISSUE TITLE
3D - unwanted indoor mode

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3565]
Open
https://mf-geoadmin3.dev.bgdi.ch/3dtiles/?tileset3d=buildings-v2&tilesetTs=20160714&pegman=true&lang=fr&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers_visibility=false,false,false,false&layers_timestamp=18641231,,,&lon=8.58072&lat=47.03475&elevation=462&heading=148.527&pitch=-11.921&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bav.haltestellen-oev,ch.swisstopo.swisstlm3d-wanderwege

pan/zoom close to building:

suddenly camera position is "in" building
![image](https://cloud.githubusercontent.com/assets/4577727/19601574/3237f6ac-97aa-11e6-95f1-e32f22341bc4.png)

expected mode

Camera is outside

**Comment by gjn** [comment]
I also sometimes am able to enter the terrain partially now. Seems to me like it's happening when loading of terrain is slow.

**Comment by fredj** [comment]
The camera can go under the terrain on https://map.geo.admin.ch is it a regression? can you also reproduce it?

**Comment by gjn** [comment]
This is much better now. I close it.
