### ISSUE TITLE
3D: void layer mode

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3567]
use case: show addresses in 3D
since - as defined- the buildings are on top of the drapped WMS layer, suer can't see the data.
therefore a switch to void layer has to be done
https://mf-geoadmin3.int.bgdi.ch/3dtiles_shadows/index.html?topic=ech&lang=en&bgLayer=voidLayer&layers_visibility=false,true,false,false&layers_timestamp=18641231,,,&lon=8.30863&lat=47.03557&elevation=661&heading=0.498&pitch=-38.105&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bav.haltestellen-oev,ch.swisstopo.swisstlm3d-wanderwege

result:
![image](https://cloud.githubusercontent.com/assets/4577727/19638901/413afffe-99d6-11e6-8ea1-f489f0a73872.png)

expected result:
iv oid layer in 3d no buildings are shown 

question: does this proposal make sense?

**Comment by gjn** [comment]
Actually, I think this makes perfect sense. voidLayer means no 3D objects.

**Comment by cedricmoullet** [comment]
Yes. This will be solved when we have real 3D representations for all layers.

**Comment by davidoesch** [comment]
as discussed wuth gin: for go live v1

**Comment by oterral** [comment]
But a void layer (white) with wohnung_register on it, seems a bit useless, no? 
We should add a layer building in the layers manager instead.

**Comment by davidoesch** [comment]
But you can drape lk10 on it and register over it... Done. It is about having the option of showing 2d layers in 3d

**Comment by davidoesch** [comment]
ok in https://github.com/geoadmin/mf-geoadmin3/pull/3679
