### ISSUE TITLE
3D: sunrise red-yellow

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3569]
lates chrome and WIN7  (assume all oss all devices)

https://map.geo.admin.ch/index.html?topic=gewiss&lang=de&bgLayer=ch.swisstopo.pixelkarte-grau&lon=9.03863&lat=45.06411&elevation=102735&heading=337.777&pitch=-22.780

![image](https://cloud.githubusercontent.com/assets/4577727/19684518/ebfd5cd4-9ab7-11e6-9ef6-2a4526265638.png)

expected result:
the red yellow bands are not shown

**Comment by loicgasser** [comment]
old issue on windows 7 only
https://github.com/geoadmin/mf-geoadmin3/issues/2913
