### ISSUE TITLE
Remove the use of config.wmsUrl in PrintDirective

### ISSUE THREAD

**Issue by oterral** [geoadmin/mf-geoadmin3#3576]
We should use `gaGlobalOptions.wmsUrl` instead or set the url property on the WMS bod layers.

https://github.com/geoadmin/mf-geoadmin3/blob/master/src/components/print/PrintDirective.js#L255

**Comment by gjn** [comment]
https://github.com/geoadmin/mf-geoadmin3/blob/master/src/components/print/PrintDirective.js#L251
