### ISSUE TITLE
KML Tooltip: arbitrary display of measure info

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3585]
IE and win7
load external kmls as in
https://s.geo.admin.ch/6f376e874b .

the tooltip look not always the same
![image](https://cloud.githubusercontent.com/assets/4577727/19847955/86ed41f0-9f4a-11e6-819c-5851635f2138.png)

it can be reproduced but not always for the same Polygon

expected result

we have one result type

**Comment by oterral** [comment]
I know I'll try to fix this for next deploy.

**Comment by oterral** [comment]
duplicate https://github.com/geoadmin/mf-geoadmin3/issues/3575

**Comment by davidoesch** [comment]
when will this be live? ping @oterral

**Comment by davidoesch** [comment]
Hi this is still the case
See 
https://s.geo.admin.ch/712a67b0f8 zeigt immer noch die drei verschiedenen, zufälligen Labels pro Kanton:
![image](https://cloud.githubusercontent.com/assets/4577727/22556770/98d29e3e-e968-11e6-9e92-b2b8fef4b6b3.png)

**Comment by oterral** [comment]
Currently the measure information are only displayed on Polygon, LineString, LinearRing and Point.

Luzern and Thurgau are MultiGeometry so no measure info.

**Comment by gjn** [comment]
So this is data issue. Good to close this, @davidoesch .

**Comment by davidoesch** [comment]
The issue is here: KML comes from our plz. What this customer needs is a KML where all Cantons are multi geometries or we show as well measure results for multi geometries

**Comment by loicgasser** [comment]
duplicate already closed once by @oterral 
same as https://github.com/geoadmin/mf-geoadmin3/issues/3704
