### ISSUE TITLE
Create Profile in iframe does not work

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3588]
Open 
http://www.schoolmaps.ch/2016/04/08/wie-viel-eis-haette-ich-ueber-mein-kopf-gehabt/

Scroll down to 
"Geografie

Konzept der Höhenlinien erklären zum Beispiel Anhand der durch den Gletscher geformten Drumlin Ruetschberg"

select and click
![image](https://cloud.githubusercontent.com/assets/4577727/19924368/e7303458-a0eb-11e6-99bf-da1be982bf7f.png)

Result:
no profile shown

expected result:
profile shown in iframe

**Comment by oterral** [comment]
Yes profile popup is deactivated on embed page.

I propose to remove the `profile erstellen` link on embed page

**Comment by davidoesch** [comment]
This would kill a lot of use cases .... Others oder @gjn ?

**Comment by oterral** [comment]
as a temprorary solution I remove the link from the popup on embed page.
