### ISSUE TITLE
Fog Mode - too close

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3591]
Did we change the fog mode?
imho we did load tiles further away ....

https://map.geo.admin.ch/?topic=ech&lang=en&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bav.haltestellen-oev,ch.swisstopo.swisstlm3d-wanderwege,ch.swisstopo.swissimage-product&layers_visibility=false,false,false,false,true&layers_timestamp=18641231,,,,&lon=7.80293&lat=46.66514&elevation=1598&heading=15.935&pitch=-8.664
![image](https://cloud.githubusercontent.com/assets/4577727/19959108/72bed430-a1a4-11e6-8cc5-10091f4b0b7b.png)

**Comment by oterral** [comment]
It was part of optimistaions we've done last year. The fog is there but behind the moutains.

**Comment by davidoesch** [comment]
Yes, bu the tiles are not loaded of the red area above..

better exmaple here: the mountain ridge is not loaded, or the fog is missing to obscure that the tiles are not loaded
https://map.geo.admin.ch/?topic=ech&lang=en&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bav.haltestellen-oev,ch.swisstopo.swisstlm3d-wanderwege,ch.swisstopo.swissimage-product&layers_visibility=false,false,false,false,true&layers_timestamp=18641231,,,,&lon=7.90204&lat=46.71056&elevation=1996&heading=134.994&pitch=-0.343

![image](https://cloud.githubusercontent.com/assets/4577727/19966997/9b0f584a-a1ce-11e6-9fb3-4e8e27776066.png)

**Comment by oterral** [comment]
It was a 80/20 decision. If you set fog parameters values for some specific panorama you loose performance (numbers of requests) and quality for other panoramas. You can't satisfy all the use case with the fog.

**Comment by davidoesch** [comment]
Ok .. Let it as it is currently... We know where we can tune.
