### ISSUE TITLE
KML: Profile info does not switch when changing selected object

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3594]
Use 
https://map.geo.admin.ch/?topic=ech&lang=de&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bav.haltestellen-oev,ch.swisstopo.swisstlm3d-wanderwege,KML%7C%7Chttps:%2F%2Fpublic.geo.admin.ch%2FEpBmxlyhQlqIFMxiSD9Rgw&layers_visibility=false,false,false,false,true&layers_timestamp=18641231,,,,&X=181682.72&Y=598310.40&zoom=3

Activate this geometrie

![image](https://cloud.githubusercontent.com/assets/4577727/19997627/37af53c8-a268-11e6-9d09-3fdc6b7d9116.png)

Then activate this geometrie
result: Profile in the bottom does not change

![image](https://cloud.githubusercontent.com/assets/4577727/19997649/5e1958f6-a268-11e6-82dc-ffafcfc0b7c0.png)

**Comment by oterral** [comment]
@davidoesch  It's ok if I close the profile when we select another geometry ?

**Comment by davidoesch** [comment]
Ok

**Comment by oterral** [comment]
Fixed with #3599
