### ISSUE TITLE
3D latest ol3-cesium : web-gl error

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3597]
Since recently, web-gl error modal window appears more often, on devices it did not before (win10 win7 chrome and android 7.0)

using this URL ( which includes an external WMS) it should be possible to reproduce the error within 20min

https://map.geo.admin.ch/?topic=ech&lang=en&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.landeskarte-farbe-10,WMS%7C%7Cskiing%7C%7Chttps:%2F%2Fwww.mapplus.ch%2Fcgi-bin%2Fmapserv%3Fmap%3D%2Fdata%2FClient_Data%2Fmapplus%2Fosm_layers%2Fskiing.map%26%26PROJLIST%3D%26LAYERS%3Dskiing%26VERSION%3D1.1.1%26REQUEST%3DGetMap%26SRS%3DEPSG:4326%26WIDTH%3D1280%26HEIGHT%3D1024%26STYLES%3Ddefault%26TRANSPARENT%3DTRUE%26FORMAT%3Dimage%2Ftiff%26%7C%7Cskiing%7C%7C1.3.0&lon=7.94840&lat=46.50731&elevation=7296&heading=358.489&pitch=-27.161

![image](https://cloud.githubusercontent.com/assets/4577727/20030743/5450adfc-a36b-11e6-9bc5-2e5f4dbd60a7.png)

**Comment by gjn** [comment]
related to https://github.com/geoadmin/mf-geoadmin3/issues/3658
