### ISSUE TITLE
KML Admin links: disappeared / not available from Share menu

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3598]
Win7 chrome ff IE11
User created a drawing 

Copies the share ADMIN link

https://map.geo.admin.ch/?topic=ech&lang=de&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bav.haltestellen-oev,ch.swisstopo.swisstlm3d-wanderwege&layers_visibility=false,false,false,false,true&layers_timestamp=18641231,,,,&X=244692.50&Y=695962.50&zoom=8&adminId=GsD-Ga3WToKhAOJhkmkEdQ 

Since last Friday (?) this link does not load anymore

Workaround-- try at least 10 times copy&pasting the URL , then URL works and I get one with a KML

https://map.geo.admin.ch/?topic=ech&lang=de&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bav.haltestellen-oev,KML%7C%7Chttps:%2F%2Fpublic.geo.admin.ch%2FrmWZSgtGQ-u7vpqQ7Z8djQ&layers_visibility=false,false,false,true&layers_timestamp=18641231,,,&X=244692.50&Y=695962.50&zoom=8&adminI%20d=GsD-%20Ga3WToKhAOJhkmkEdQ

**Comment by oterral** [comment]
it works for me

**Comment by oterral** [comment]
Maybe a problem when we are otuside bund network.

**Comment by davidoesch** [comment]
I had issue this morning on GSM, Cablecom and VPN with the link above , on 3 different devices... Only resolved with mulitple retries. Customer confirms that they have the issue since friday afternnoon ...until today. What bothers me is: what is the cause? now it works on all devices....

**Comment by oterral** [comment]
@davidoesch Have you seen that in the links you provided there was spaces in adminId and in the adminId value like this (the %20):

&adminI%20d=GsD-%20Ga3WToKhAOJhkmkEdQ 

I've corrected it in the first link you provide maybe that's why it's working now

**Comment by davidoesch** [comment]
The Second Link works the first one not. It seems that we handle spaces different since last deploy....
They have their admin links stored in a text file and copy it...

**Comment by oterral** [comment]
The links have space in their file or not ?

**Comment by gjn** [comment]
We might need to URL Decode the adminID. It might be, that when they copy, the browser URL encodes the link.

**Comment by davidoesch** [comment]
Oli has a second example in his inbox. I tried with http://meyerweb.com/eric/tools/dencoder/ and once in a while it works. I assume that the customer saves it in a format where the CR can not be read after one of the latest deploy. As the customer explained not all links are affected

**Comment by gjn** [comment]
Notice also that 2nd link has both external kml and adminId. When editing this, you'll create a new file with a new adminId because the delivered adminId is wrong.

The spaces in the URL are unusual. Can we exclude copy/paste errors? From code, we never have spaces in the key (`adminId`) and the value `hash`. So they have to come from somehwere.

**Comment by oterral** [comment]
I think there is a problem in files service : 

The file returns 404: https://api3.geo.admin.ch/files/JlWzAYssSQyr9kXTuYPYLA

**Comment by gjn** [comment]
@davidoesch Can you give us a couple of adminId's, so we can verify directly in the db if they exists.

**Comment by gjn** [comment]
In addition, we will extend the kml admin overview to 'filter' by id.

**Comment by davidoesch** [comment]
@gjn any Update (See mail sent to you last week regarding a non functional admin id) regarding how to fix non working links and preventing it from happening again in the future?

**Comment by davidoesch** [comment]
According to customer the Admin ID issues are not anymore the case -- since we don't know WHY this happened. I keep this open

**Comment by gjn** [comment]
I assume this was a copy/paste error. Maybe windows clibpoard added/removed something. Maybe when pasted to IE11 something happened.

I'm pretty sure it's not something on our side.

Anyhow, keep it open as it makes sense to have this extension in the admin kml page anyway.

**Comment by gjn** [comment]
Related to prio 1 issue. I close this one.
