### ISSUE TITLE
Search - fly does not work in 3d

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3603]
open
https://mf-geoadmin3.int.bgdi.ch/3dtiles/index.html?topic=ech&lang=de&bgLayer=ch.swisstopo.pixelkarte-grau&lon=7.85103&lat=46.68362&elevation=644&heading=315.324&pitch=-14.904&layers_visibility=false,false,false,false&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bav.haltestellen-oev,ch.swisstopo.swisstlm3d-wanderwege&layers_timestamp=18641231,,,

enter chur in search

select result
no fly to result

**Comment by oterral** [comment]
@loicgasser height service down ? 
https://mf-chsdi3.int.bgdi.ch/rest/services/height?easting=631390.450778309&elevation_model=COMB&northing=170456.7797071139

**Comment by davidoesch** [comment]
hmm see also #3606 might be related

**Comment by oterral** [comment]
Fixed
