### ISSUE TITLE
search flight to to does end in locked /white position

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3606]
open prod https://map.geo.admin.ch
switch to 3d
search for
Alpiner Gipfel Finsteraarhorn (BE) - Guttannen

select
result: fly to it  but you end up completely locked

-> IMHO this has to do with the collision settings

**Comment by davidoesch** [comment]
just adding observations:
for the branch https://mf-geoadmin3.int.bgdi.ch/teo_autorender/index.html
For alpine peaks "bietschhorn" "Eiger" etc the big peaks you enter always in the valley, whereas for small hills like "Gurten" "Caral" it works fine

**Comment by loicgasser** [comment]
@oterral can yu check with update
