### ISSUE TITLE
3d: Collision mode is off 

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3607]
scroll/move backward with mouse and you can vanish into the mountains

![image](https://cloud.githubusercontent.com/assets/4577727/20264581/8f667dc4-aa6c-11e6-9884-f96005f0acc7.png)

https://map.geo.admin.ch/?topic=ech&lang=de&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.swissimage-product&lon=8.11303&lat=46.50042&elevation=3213&heading=20.663&pitch=10.977

AFAIK we did just reduce the min distance but not remove the collision detection

**Comment by oterral** [comment]
@davidoesch  it's me or it's happening only after using the search box.

Open the page,  zoom with the mouse to the mountain and tilt the image, the collision detection is ok.
Then go on the search box and search for bern. Try to tilt and this time you go through the terrain.

Can you confirm this behavior.

**Comment by gjn** [comment]
I can go through terrain right away.

**Comment by davidoesch** [comment]
Me too: right through terrain

Gilbert Jeiziner <notifications@github.com> schrieb am Do., 17. Nov. 2016,
16:41:

**Comment by oterral** [comment]
Anf if you open the page directly in 3d : https://map.geo.admin.ch/?topic=ech&lang=fr&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bav.haltestellen-oev,ch.swisstopo.swisstlm3d-wanderwege&layers_visibility=false,false,false,false&layers_timestamp=18641231,,,&lon=8.01785&lat=46.76334&elevation=1042&heading=355.912&pitch=10.755

**Comment by davidoesch** [comment]
if I open directly: chrome win7: I cant' go trough

Correction for
"Open the page, zoom with the mouse to the mountain and tilt the image, the collision detection is ok.
Then go on the search box and search for bern. Try to tilt and this time you go through the terrain."

->Can't reproduce


Does it maybe relate to the fact that the  pitch=10.718 with is over the limit what you can do with mouse interaction? (i know this sounds esoteric, since a button does not have an impact on code)

**Comment by oterral** [comment]
Extract from Cesium 1.25 release:
```
Camera flights now disable collision with the terrain until all of the terrain in the area has finished loading. This prevents the camera from being moved to be above lower resolution terrain when flying to a position close to higher resolution terrain. 
```

Could explain what I've observed with flyTo function.

**Comment by oterral** [comment]
Ok problem found. It's basically linked to https://github.com/geoadmin/mf-geoadmin3/issues/2892.

The ` tilesWaitingForChildren` queue is never empty. So the collision detection is never reactivated after a flyTo. 

See [code](https://github.com/AnalyticalGraphicsInc/cesium/pull/4105/files#diff-6298b280e4e0977bedd881b65b769863R930).

**Comment by davidoesch** [comment]
Yes!!!!!!
