### ISSUE TITLE
3D chrome /ff webgl crashes when rotating

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3608]
win7 and win10 , chrome and ff

Open
https://mf-geoadmin3.int.bgdi.ch/3dtiles/index.html?topic=ech&lang=de&bgLayer=ch.swisstopo.pixelkarte-grau&lon=7.84870&lat=46.68625&elevation=645&heading=165.273&pitch=-15.226&layers_visibility=false,false,false,false&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bav.haltestellen-oev,ch.swisstopo.swisstlm3d-wanderwege&layers_timestamp=18641231

then start rotating, after a couple of rotations, 

[see](https://www.youtube.com/watch?v=YK3Csmhg7JA ) starting at min 0:52

chrome crashes with the following message

https://support.google.com/chrome/answer/95669?visit_id=1-636147282554985750-2019170269&p=e_awsnap_rl&rd=1

Observations
- if I turn with CTRL+ LEFT Mouse and mouse gesture: it does not crash
- in the current alpha version, this does not occur --- I can turn around as much as I want

**Comment by oterral** [comment]
can't reproduce . @davidoesch Is i still the case?

**Comment by davidoesch** [comment]
tested now 45 minutes

https://mf-geoadmin3.int.bgdi.ch/**3ddemo/**index.html?
on
-ff
-chrome

and
-win7
-win10

coun not reproduce
