### ISSUE TITLE
Catalog error for bikesharing

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/mf-geoadmin3#3614]
======================================================================
ERROR: test_nodes_connection (chsdi.tests.integration.test_catalog.TestCatalogService)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/jenkins/jobs/PR_chsdi3/workspace/chsdi/tests/integration/test_catalog.py", line 29, in test_nodes_connection
    raise Exception('%s %ss is unconnected leaf' % (row.category, row.layerBodId))
Exception: layer ch.bfe.bikesharings is unconnected leaf

@AFoletti could you check the catatlog please?

**Comment by loicgasser** [comment]
/rest/services/energie/CatalogServer is invalid as well

**Comment by AFoletti** [comment]
working on it, but the gdoc looks OK to me and Mario

**Comment by gjn** [comment]
Fixed.

**Comment by AFoletti** [comment]
Yep. Was a duplicate ID in teh gdoc. We should find a better way to enforce that
