### ISSUE TITLE
3D in iframe: preview is really really slow

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3615]
win7 Chrome /ff
when trying to embed
https://mf-geoadmin3.int.bgdi.ch/3dtiles/index.html?topic=ech&lang=de&bgLayer=ch.swisstopo.pixelkarte-grau&lon=7.84445&lat=46.69038&elevation=713&heading=267.412&pitch=-28.655&layers_visibility=false,false,false,false&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bav.haltestellen-oev,ch.swisstopo.swisstlm3d-wanderwege&layers_timestamp=18641231,,,

as iFrame via embed
viewer takes up to 60 sec to load
![image](https://cloud.githubusercontent.com/assets/4577727/20338206/dac184b6-abd5-11e6-9aee-21d24370bd9d.png)

**Comment by gjn** [comment]
2 times accessing GPU in same browser window might slow everything down...

**Comment by davidoesch** [comment]
this is what I assume. make  a "won't fix" out of it if this if it is the case
