### ISSUE TITLE
3d json Layer not visible

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3619]
Open the bike sharing layer on prod and go to 3d

https://s.geo.admin.ch/6f9db3553f

No data shown. We had this in the past as well for the hydroweb json layers.. But was fixed

**Comment by loicgasser** [comment]
(anonymous function) @ VM437:437
VM437:437 Error loading image for billboard: SecurityError: Failed to execute 'texSubImage2D' on 'WebGLRenderingContext': The cross-origin image at https://data.geo.admin.ch/ch.bfe.bikesharing/images/13.png may not be loaded.

It's because we're loading images this time.

**Comment by davidoesch** [comment]
A nice solution would be: images are displayed as billboards. As eg map.wanderland.ch does for public transportation stops in 3d.... Your thoughts?

**Comment by oterral** [comment]
Maybe CORS header can help.

**Comment by gjn** [comment]
Yes, we need CORS headres on data.geo.admin.ch

**Comment by oterral** [comment]
Asked to @danduk82

**Comment by gjn** [comment]
CORS headers are now active, but issue still remains.

**Comment by gjn** [comment]
I have the same issue in cesiums billboard sandcastle example when specifying our image:
http://cesiumjs.org/releases/b28/Apps/Sandcastle/index.html?src=Billboards.html&label=Showcases
https://data.geo.admin.ch/ch.bfe.bikesharing/images/14.png

**Comment by gjn** [comment]
That's strange. Other png's seem to work.

**Comment by gjn** [comment]
Can anyone test in safari? Might work there...

**Comment by cedricmoullet** [comment]
It doesn't work in Safari

**Comment by gjn** [comment]
Cesium doesn't send the crossOrigin headers in the request, it seems. Probably here: https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Renderer/Texture.js#L434

Somethink like crossOrigin=''; needs to be added to source. Read http://stackoverflow.com/questions/24087757/three-js-and-loading-a-cross-domain-image

In fact, I got it to work in the sandcastle example above by adding
`image.crossOrigin` = '';
before specifying the src url to image. Like this:
![image](https://cloud.githubusercontent.com/assets/2572317/20399053/dae11ed2-acef-11e6-991c-e3ad802f8afa.png)

So some patch should be possible.

**Comment by oterral** [comment]
But it's weird even in 2d the 'origin' header is not sent with th request for these images
