### ISSUE TITLE
3d: switch from 2d to 3d : loading time too long

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3620]
ALL OS all browsers
got to

https://mf-geoadmin3.int.bgdi.ch/3dtiles/index.html?topic=ech&lang=de&bgLayer=ch.swisstopo.pixelkarte-farbe&layers_visibility=false&layers_timestamp=18641231&X=187817.94&Y=754443.55&zoom=7

click on 3D

Result:
no tiles are loaded for a long time, white background. if  after a successful load i switch back to2d and then to 3d again: tiles  are loaded fast as today (since they are in cache)

expected result:
3d starts loading as today on prod. I know now we have buildings and bridges etc.- but currently the user gets the impression "nothing happens"

Possible solutions:

- as described in https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/re3-dev/SRgY60-mr8E/GEPJEhlvBwAJ 

- [ ] bigger wmts tiles
- [ ] remove wmts pyramid levels
- [ ] remove building pyramid levels
- [ ] remove terrain pyramid levels

no option: adding a waiting wheel

**Comment by gjn** [comment]
Another possibility is to not load layers which are not visible.

Terrain and wmts levels are already reduced (at least in prod, but I assume also in 3dtiles branch, right @oterral )

Removing buildings LOD might result in buildings never appearing, as our 3dtiles, to my knowledge, use refinement by addtion (and not refinement by replacement).

**Comment by oterral** [comment]
We have removed the limitations for WMTS, they are loaded on each level.

**Comment by oterral** [comment]
Another observation is that the tileset json file of buildings takes 2 secs to be download:
  1.8mo gzipped/ 7mo unzipped.

https://vectortiles2.dev.bgdi.ch/ch.swisstopo.swisstlm3d.3d/20160909/tileset.json

**Comment by loicgasser** [comment]
TO be discussed

**Comment by gjn** [comment]
This is related to names. AGI should work on it.

**Comment by gjn** [comment]
Names is now solved. So can we close this issue?

**Comment by davidoesch** [comment]
Yep
