### ISSUE TITLE
3D: "the needle"

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3623]
Seems like a faulty terrain 

https://mf-geoadmin3.int.bgdi.ch/teo_autorender/index.html?topic=ech&lang=en&bgLayer=ch.swisstopo.pixelkarte-farbe&layers_visibility=false&layers_timestamp=18641231&lon=9.10484&lat=47.14445&elevation=2202&heading=300.833&pitch=-17.226&pegman=true

![image](https://cloud.githubusercontent.com/assets/4577727/20454736/e71da8ea-ae49-11e6-8bb4-17fe111c0769.png)

can you check if the issue is in TOPO terrain?

**Comment by loicgasser** [comment]
Yes but we would need a system to check the quality of what is delivered or do it ourselves. This is not trivial though.

**Comment by oterral** [comment]
TOPO has been warned

**Comment by oterral** [comment]
Topo is working on it

**Comment by oterral** [comment]
@davidoesch , cedric from TOPO has fixed the issue but we need the generation of all the terrain, is there a release scheduled of terrain  data?

**Comment by davidoesch** [comment]
We fix that for version 1.0 when we go live. With the next update of Swiss alti 3f

**Comment by oterral** [comment]
when is the next update of swissalti3d?

**Comment by davidoesch** [comment]
Looks like once a year in March: https://jira.swisstopo.ch/browse/BGDIDI_KB-851 but afaik no update is in planning on Gdwh site @mariokeusen

**Comment by oterral** [comment]
other needle https://map.geo.admin.ch/?lang=fr&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bav.haltestellen-oev,ch.swisstopo.swisstlm3d-wanderwege,ch.swisstopo.swissimage-product&layers_visibility=false,false,false,false,true&layers_timestamp=18641231,,,,&lon=9.39627&lat=47.22014&elevation=1529&heading=265.065&pitch=-6.524
