### ISSUE TITLE
3D tiles: blinking of bridges

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3631]
open 
https://mf-geoadmin3.int.bgdi.ch/3dtiles/index.html?topic=ech&tileset3d=ch.swisstopo.bridgestest.3d&tilesetTs=20161111&lang=de&bgLayer=ch.swisstopo.pixelkarte-farbe&lon=7.84996&lat=46.68344&elevation=738&heading=27.968&pitch=-56.891&layers_visibility=false&layers_timestamp=18641231

pitch forward and backward:

Result: Shadow of bridges are blinking

**Comment by gjn** [comment]
Can't reproduce in Chrome  54.

**Comment by davidoesch** [comment]
reproduced on latest chrome on win10 and win7
see
https://www.youtube.com/watch?v=zRd3rVCUlYY

**Comment by davidoesch** [comment]
2 sets contain same objects

wil be solved with next update
