### ISSUE TITLE
3D webgl not initialized

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3633]
Open
on ios Safari and android 7.0 chrome

open 
https://mf-geoadmin3.int.bgdi.ch/3dtiles/index.html?topic=ech&tileset3d=ch.swisstopo.bridgestest.3d&tilesetTs=20161111&lang=de&bgLayer=voidLayer&layers=ch.swisstopo.swissimage-product&lon=6.14189&lat=46.20255&elevation=543&heading=324.417&pitch=-30.884

webgl support warning on ios
no bridges on android, while the same link worked before

Reproduced by @cedricmoullet

**Comment by gjn** [comment]
When was 'before'?

**Comment by davidoesch** [comment]
Less than ten minutes before.

**Comment by oterral** [comment]
There is a shader compile  error. I think it's because there is some duplicate bridges. Without the  bridgestest tileset it's working.
