### ISSUE TITLE
Parameter swipe ratio doesn't work on IE9

### ISSUE THREAD

**Issue by Sgachet** [geoadmin/mf-geoadmin3#3639]
Open this link : 

https://map.geo.admin.ch/?lang=fr&topic=swisstopo&bgLayer=voidLayer&X=190000.00&Y=660000.00&zoom=1&catalogNodes=1392&layers_timestamp=20131231,18641231&layers=ch.swisstopo.zeitreihen,ch.swisstopo.zeitreihen&swipe_ratio=0.53

Move the red line and have a lon on the parameter swipe_ratio -> doesn't change.

**Comment by gjn** [comment]
Works in chrome. Maybe you need to wait 1-2 seconds (PL is updated after a short delay)

Which browser did you test with?

**Comment by oterral** [comment]
it's normal on IE9
