### ISSUE TITLE
Tooltip based links do not work anymore

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3651]
Hi 
 since 9.12.2016 ( the emergency deploy ?)  
links from tooltips do not work for

- ch.swisstopo-vd.amtliche-vermessung

![image](https://cloud.githubusercontent.com/assets/4577727/21041038/d930218c-bde8-11e6-9738-a0ab16749992.png)

**Comment by ltclm** [comment]
we have killed this feature ourselves by blocking user agent.
code adaptions have been merged today and will be deployed next wed
https://github.com/geoadmin/mf-chsdi3/pull/2380

**Comment by davidoesch** [comment]
IMHO this requires an emergency deploy... since base funcationality is affected
@gjn @ltclm

**Comment by ltclm** [comment]
another option would be to remove the user-agent blocking from everything except height service until we have deployed this, @danduk82 is that possible?

**Comment by davidoesch** [comment]
@mariokeusen we will habe to wait here. No rollback due to current abuse issue

**Comment by mariokeusen** [comment]
customers of AV and ivs are informed...

**Comment by loicgasser** [comment]
This is solved.
