### ISSUE TITLE
EMAPIS: EN and RM are supressed

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3657]
in emapis, the multing for EN and RM is missing

![image](https://cloud.githubusercontent.com/assets/4577727/21190742/28708c80-c223-11e6-8e78-5d413aaad7b7.png)

-> geo.admin.ch is multing, EN and RM has as fallback DE

cc @p1d1d1 @mariokeusen

**Comment by loicgasser** [comment]
Yes this is as requested. If we always put the 5 langs. We might as well remove this option from the topic configuration.

**Comment by davidoesch** [comment]
Geo.admin is multi lingual -per Default. Restriction of language is ridiculous: how shall the rumantsch speaking farmer draw??? In German ? 😉

**Comment by davidoesch** [comment]
So set it to all lingos... Title and abstract will be translated by KOGIS in q1. .... It's a pity I have to explain this after 8yrs.... And an u.n. award for multilingualism for the app....

**Comment by loicgasser** [comment]
I couldn't agree more on the principle, I'll prepare geoadmin, chsdi and db to always use 5 langs and remove this restriction if confirmed by mario as well.

**Comment by davidoesch** [comment]
@mariokeusen ?

**Comment by davidoesch** [comment]
As discussed with Mario. Fix it global. We will provide translation

**Comment by loicgasser** [comment]
ok, I will, we'll use the fallback languages for now.

**Comment by mariokeusen** [comment]
Was not aware at all that suppression of RM and EN was _requested_ in this case. Was that really the case, @p1d1d1 ?? In any case I don't have an option to enable/disable languages for a topic, means this restriction could not come from the topic config table. Standard is 5 languages for a topic, even if not every language is available (in such a case the replacement languages are being set) .

**Comment by p1d1d1** [comment]
A heritage of a first eMapis-Avatar.

**Comment by mariokeusen** [comment]
@alcapat : since the zusammenfassung layer is now ready to be published tomorrow I have adapted again the topic config. Besides that, could you please make sure, that after tomorrow's deploy, all 5 languages are available for this topic?

Thanks in advance Mario

**Comment by gjn** [comment]
To verify.

**Comment by alcapat** [comment]
@mariokeusen : sorry i don't see your message. I have added missing languages (EN and RM) in the topic config. But maybe it's too late for this deploy  @oterral ?

**Comment by oterral** [comment]
We would like to do it properly on geoadmin, chsdi and db side . so can it wait the next deploy @mariokeusen ?

**Comment by mariokeusen** [comment]
I can live with that. @davidoesch ?

**Comment by davidoesch** [comment]
+1

**Comment by gjn** [comment]
Good. Getting rid of special cases is always good.

**Comment by oterral** [comment]
Ok we can remove all the topic language dependent stuff from geoadmin?
