### ISSUE TITLE
3D on prod- webgl crashes

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3658]
Try to open
https://map.geo.admin.ch/?topic=ech&lang=en&bgLayer=voidLayer&layers=ch.swisstopo.swisstlm3d-karte-grau,ch.bafu.karst-unterirdische_fliesswege,ch.bafu.karst-quellen_schwinden,ch.bafu.karst-ausdehnung_grundwasservorkommen,ch.bafu.karst-einzugsgebiete,ch.bafu.karst-einzugsgebietseinheiten&layers_opacity=1,1,1,0.75,1,0.75&lon=6.91834&lat=47.11228&elevation=1521&heading=74.309&pitch=-10.145

pan around:
Webgl crashes really fast (win7 and win10 chrome)

![image](https://cloud.githubusercontent.com/assets/4577727/21191162/8fb22376-c224-11e6-9474-c92743d5ed93.png)

**Comment by oterral** [comment]
Can't reproduce on windows 7.

**Comment by gjn** [comment]
@davidoesch still reproducible?

**Comment by davidoesch** [comment]
Same link on same devices work now can not  be reproduced. what is funyy I did clean cache, cold start browsers when reported the issue....now no issue. must be somewhere in the cash on our infra... since the datasets was deployed on the very day when ticket opened

**Comment by oterral** [comment]
@davidoesch when it happens open the console with F12 . There should be an error message in the console.

**Comment by davidoesch** [comment]
The thing is when it breaks: the browser incl console freezes
