### ISSUE TITLE
tooltip: highlight mouse

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3672]
only chrome / not IE
open this  wanderland layer

https://map.geo.admin.ch/?topic=ech&lang=de&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bav.haltestellen-oev,ch.swisstopo.swisstlm3d-wanderwege,ch.astra.wanderland&layers_visibility=false,false,false,false,true&layers_timestamp=18641231,,,,&X=201968.70&Y=676652.10&zoom=13

on mouseover, mouse transforms to a hand  on clicking

result:
no tooltip

expected result;
no hand transformation or infotootip: no object info

**Comment by oterral** [comment]
no object iInfo popup should be displayed

**Comment by davidoesch** [comment]
ok in https://github.com/geoadmin/mf-geoadmin3/pull/3679
