### ISSUE TITLE
[WMS] Proposed WMS -> new WMS VD 

### ISSUE THREAD

**Issue by ponceta** [geoadmin/mf-geoadmin3#3673]
Hi everyone!

I Wish you all the best for 2017!
As a New Year gift, Canton Vaud updated its WMS service! 

Old url http://wms.vd.ch/public/services/VD_WMS/Mapserver/Wmsserver?
should be replaced with:
http://wms.vd.ch/public/services/wmsVD/Mapserver/Wmsserver
on:
https://github.com/geoadmin/mf-geoadmin3/blob/master/src/js/ImportWmsController.js#L47

Bonne année 2017 @ tous!

Arnaud

See 
https://www.asitvd.ch/chercher/geoservices/geoservice-de-consultation-wms.html for more details.

and check out https://www.asitvd.ch/chercher/geoservices/fond-de-plan-asit-vd.html for nice background layers.

**Comment by oterral** [comment]
Hi @ponceta !!

I wish you all the best for 2017 too!!

Thx for th new url we will add it as soon as we have the new import ready.

**Comment by davidoesch** [comment]
ok in https://github.com/geoadmin/mf-geoadmin3/pull/3679
