### ISSUE TITLE
3d Icon

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3675]
hi we need
3d instead of 2.512236d

![image](https://cloud.githubusercontent.com/assets/4577727/21927060/ce126f64-d984-11e6-969b-cd15971201b9.png)

active and not active button

**Comment by loicgasser** [comment]
Don't we already have the icon somewhere @oterral ? We started of with 3d

**Comment by oterral** [comment]
I haven't. @pauloamado ?

**Comment by oterral** [comment]
Fixed by the PR mentioned above
