### ISSUE TITLE
API3 3dvectortiles service description

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3677]
Analogue to

http://api3.geo.admin.ch/services/sdiservices.html#terrain-service

create
http://api3.geo.admin.ch/services/sdiservices.html#3dvector-service

for accessing 3dtiles

**Comment by loicgasser** [comment]
@davidoesch I guess we want that before next week's go live right?

**Comment by davidoesch** [comment]
Correct... I nice to have. But the other issues are more important

**Comment by loicgasser** [comment]
I'll do it.

**Comment by davidoesch** [comment]
Thanks !

**Comment by davidoesch** [comment]
Clicking on https://vectortiles100.geo.admin.ch opens a demo site which gives back 403 http://wmts20.geo.admin.ch/demo/ (and why do we not offer multiple vector tiles addresses?)

**Comment by davidoesch** [comment]
Clicking on https://vectortiles100.geo.admin.ch/ link a mapproxy

**Comment by oterral** [comment]
Yes we have multiple address.

**Comment by oterral** [comment]
The mapproxy demo is avlaible only internally I guess. But it's not a demo of vectortiles.

**Comment by davidoesch** [comment]
MBTtiles: https://vectortiles100.geo.admin.ch is linking not mapbox but 3dtiles (*b3dm) or Am i completely wrong?

multiple adresses: I only get 100 range https://vectortiles100.geo.admin.ch/ch.swisstopo.swisstlm3d.3d/20161217/4/12/11.b3dm?v=1.0 etc in my browser, no multiple adresses

**Comment by oterral** [comment]
Yes it points to 3dtiles. That show mapproxy probably because varnsih redirects to it when there is no text given after the base url of the service.

Yes you get only 100 range in your browser because cesium doesn't support multi urls for 3dtiles layer.

But we have vectortiles100-104 available.

**Comment by davidoesch** [comment]
thanks..now I get it
in thsi case: the link to the Demo page http://wmts20.geo.admin.ch/demo/  can be removed ...

**Comment by oterral** [comment]
It should poitn to an empty file like terrain0.geo.admin.ch or wmts.geo.admin.ch
