### ISSUE TITLE
3D KML add height for display

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3678]
Hi

as discussed with @gjn 
ask c2c for support on how to make a plain kml line drawn or imported (only x y no z) in map.geo.admin.ch work in 3d view by adding on the fly alti information to it make it artificially clamp to ground ( or at least 2, above ground) as in map.wanderland

this is a workaround for 
#3374 
and
#3017

**Comment by cedricmoullet** [comment]
@oterral do you see  a way to do that ?

**Comment by oterral** [comment]
Here an example of the Cesium hack for Polyline:

1) Click [here](https://mf-geoadmin3.int.bgdi.ch/teo_kml_synchronizer/index.html?lang=fr&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&dev3d=true&debug&layers_visibility=false&layers_timestamp=18641231&X=103963.96&Y=605037.83&zoom=4)
2) Drop the file ([PatrouilledesGlaciersPOI.txt](https://github.com/geoadmin/mf-geoadmin3/files/719700/PatrouilledesGlaciersPOI.txt)) in it
3) Go to 3d

You see a small line of 30m width because the 2d line was 30 pixel width

The idea would be to improve this hack if possible and do the same hack in ol3-cesium.

**Comment by davidoesch** [comment]
this is what we need...

any review on this approach by @gberaudo @gjn 

- side effcts, limitation etc?

**Comment by oterral** [comment]
Just saw, if we get the corridor object. We can modify the width of the corridor on-the-fly

**Comment by davidoesch** [comment]
when do we have an ETA for this?

**Comment by davidoesch** [comment]
hi oli
Question, having wandern.ch working in 3D https://www.wandern.ch/ewalc/images/ewalk2/1200/geodata/geodata_de.xml
which changes do need be made?<tessellate>1</tessellate> seems not to work cc @cedricmoullet

**Comment by oterral** [comment]
Just put  <tessellate>1</tessellate> instead of  <tessellate>0</tessellate> and it works

**Comment by davidoesch** [comment]
If did a find and replace of  <tessellate>0</tessellate> to <tessellate>1</tessellate>  but no success for the file above

**Comment by oterral** [comment]
That's what I did and it works

**Comment by oterral** [comment]
![screen-clamped](https://cloud.githubusercontent.com/assets/621420/22499752/d8dfc91a-e860-11e6-9efc-a47e6bcb04f1.png)

**Comment by davidoesch** [comment]
https://gist.githubusercontent.com/davidoesch/07f308570b11e1e8e1e8bcbdfb4d6e22/raw/450c41f9ec64f584458ed949b421cac7003b26f2/3dwandern.kml  does not work in PROD or INT nor in 2d or 3d https://mf-chsdi3.int.bgdi.ch/shorten/712426c1ac on win7 chrome

**Comment by oterral** [comment]
You can't load via GIST because it returns a bad-formed XML file with text at the beginning.

**Comment by oterral** [comment]
I make it work with another KML.

**Comment by oterral** [comment]
Remove the line on map :
```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<!--  Generator: OCAD Version 12.1.1  -->````

**Comment by davidoesch** [comment]
did not change anything

![image](https://cloud.githubusercontent.com/assets/4577727/22500804/5b119cce-e866-11e6-94a1-0cea2822ecfa.png)

**Comment by oterral** [comment]
Remove also the <script> tag in it.

**Comment by oterral** [comment]
@davidoesch it works without `<script>` tag, [see](https://mf-geoadmin3.dev.bgdi.ch/src/?topic=ech&lang=fr&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,KML%7C%7Chttps:%2F%2Fgist.githubusercontent.com%2Foterral%2Fd4083be5d6c1509d00e519a57cebec5c%2Fraw%2Fa50681e0899ee394cddcdcb4868743e4c6b31f70%2Fwandern_3d.xml&layers_visibility=false,true&layers_timestamp=18641231,&lon=9.07990&lat=46.98050&elevation=3403&heading=360.000&pitch=-40.104)

**Comment by oterral** [comment]
@davidoesch  @gjn  draw clamped to ground [see](https://mf-geoadmin3.int.bgdi.ch/3dtiles_lineclamp/index.html?lang=fr&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&dev3d=true&debug&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bav.haltestellen-oev,ch.swisstopo.swisstlm3d-wanderwege,KML%7C%7Chttps:%2F%2Fpublic.dev.bgdi.ch%2FZ7zhqhUoQ5eNzgs_l-Zbig&layers_visibility=false,false,false,false,true&layers_timestamp=18641231,,,,&lon=7.60823&lat=46.90480&elevation=3123&heading=333.979&pitch=-40.010) 

with https://github.com/openlayers/ol3-cesium/pull/437

**Comment by davidoesch** [comment]
ok,, perfect!!! 

When will this be in prod? next deploy?

**Comment by davidoesch** [comment]
update?

**Comment by davidoesch** [comment]
Respectively: 
- [ ] Icons are not shown 
  
https://mf-chsdi3.int.bgdi.ch/shorten/7207a7587f

**Comment by oterral** [comment]
the star and the marker ? :) I see those

**Comment by davidoesch** [comment]
Strange- I *did* not see it before, relodaded it....

Anyway: when will this deployed?

**Comment by oterral** [comment]
#3708 merged
