### ISSUE TITLE
3dtiles branch does not load building on mobile

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3684]
Hi
Nexus 6p,7.1.1
Latest chrome
Cache cleaned
Reboot device
Cold start

https://mf-geoadmin3.int.bgdi.ch/3dtiles/mobile.html?topic=ech&lang=de&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bav.haltestellen-oev,ch.swisstopo.swisstlm3d-wanderwege&layers_visibility=false,false,false,false&layers_timestamp=18641231,,,&X=237650.38&Y=683388.44&zoom=9.675235268397802

![screenshot_20170119-210107](https://cloud.githubusercontent.com/assets/4577727/22123281/5df2c010-de8b-11e6-878b-ad50a2bcf65c.png)
No building

Can anyone confirm this on their device?

We had similar issues in the past Everytime a branch was updated with a new building tileset

**Comment by oterral** [comment]
I confirm no buildings on my mobile

**Comment by oterral** [comment]
It's not related to the vectortiles service. It seems the application doesn't get the good version of js files.

Probably a varnish cache issue.

**Comment by oterral** [comment]
Should be fixed can you test @davidoesch .

It seems the metadata layer is not very accurate :  
[Test1](https://mf-geoadmin3.int.bgdi.ch/3dtiles/index.html?topic=ech&lang=fr&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bav.haltestellen-oev,ch.swisstopo.swisstlm3d-wanderwege,ch.swisstopo.swissbuildings3d_2.metadata&layers_visibility=false,false,false,false,true&layers_timestamp=18641231,,,,&lon=7.86069&lat=46.66153&elevation=4385&heading=18.709&pitch=-71.686&layers_opacity=1,1,1,1,0.75) [Test2](https://mf-geoadmin3.int.bgdi.ch/3dtiles/index.html?topic=ech&lang=fr&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bav.haltestellen-oev,ch.swisstopo.swisstlm3d-wanderwege,ch.swisstopo.swissbuildings3d_2.metadata&layers_visibility=false,false,false,false,true&layers_timestamp=18641231,,,,&lon=7.72119&lat=46.64220&elevation=4906&heading=18.717&pitch=-71.685&layers_opacity=1,1,1,1,0.75)

**Comment by davidoesch** [comment]
works now like a charm on NEXUS 6P android 7.11 chrom
(metadata layer update: topo is informed)
