### ISSUE TITLE
WMS 3D not loaded URI

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3685]
https://mf-geoadmin3.int.bgdi.ch/3dtiles/index.html?topic=ech&lang=de&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=WMS%7C%7Cswisscom_leitungen%7C%7Chttp:%2F%2Fservice.lisag.ch%2Fwms%7C%7Cleitungen:swisscom_leitungen%7C%7C1.3.0&lon=8.65239&lat=46.85695&elevation=637&heading=360.000&pitch=-40.000

**Comment by oterral** [comment]
No default style defined in this WMS . SHould be trivial to fix.

**Comment by loicgasser** [comment]
FYI: when opening this link I can't switch back to 2d.

**Comment by oterral** [comment]
Can you retry I've cleaned the branch deplyoed for https://github.com/geoadmin/mf-geoadmin3/issues/3684
