### ISSUE TITLE
WMS not loaded on lod 8

### ISSUE THREAD

**Issue by oterral** [geoadmin/mf-geoadmin3#3688]
It happens only for WMS in 3d. The lod 8 is never loaded.

**Comment by cedricmoullet** [comment]
Is the display of ch.swisstopo.swissbuildings3d_2.metadata related to this issue ?
3D:
![image](https://cloud.githubusercontent.com/assets/319676/22417389/4320db5e-e6d4-11e6-9f71-f4cf5c215188.png)
2D:
![image](https://cloud.githubusercontent.com/assets/319676/22417469/b416a56e-e6d4-11e6-84d0-fa77320c650e.png)

**Comment by cedricmoullet** [comment]
Link: https://map.geo.admin.ch/?topic=ech&lang=fr&bgLayer=voidLayer&layers=ch.swisstopo.swissimage-product,ch.swisstopo.swissbuildings3d_2.metadata&layers_opacity=1,0.75&lon=7.80947&lat=44.30658&elevation=306770&heading=360.000&pitch=-41.593

**Comment by cedricmoullet** [comment]
@oterral ?

**Comment by oterral** [comment]
Yes. 
In fact, at the entire swiss level Cesium try to load lod 7 for WMS  and lod 8 of WMTS.

I don't know why it does that.
But I can easily workaround this in the MapService and display lod 7 for WMS.
