### ISSUE TITLE
V2 buildings

### ISSUE THREAD

**Issue by cedricmoullet** [geoadmin/mf-geoadmin3#3691]
Shouldn't we have buildings here: https://mf-geoadmin3.int.bgdi.ch/?topic=ech&lang=fr&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bav.haltestellen-oev,ch.swisstopo.swisstlm3d-wanderwege,ch.swisstopo.swissbuildings3d_2.metadata&layers_visibility=false,false,false,false,true&layers_timestamp=18641231,,,,&lon=8.45980&lat=47.39081&elevation=1418&heading=0.420&pitch=-50.277&layers_opacity=1,1,1,1,0.75

**Comment by oterral** [comment]
known issue by the dataowner. can you confirm @davidoesch ?

**Comment by davidoesch** [comment]
The 3d perimeter shop and delivered data are not in sync. Data owner (gue) is informed...
