### ISSUE TITLE
External KML Icons are bigger since deploy 20170126

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3693]
open

http://www.skitourenguru.ch/index.php/routeview?AREA=Switzerland&ID=673&RISKIND=0.28&SERVER=http://www.skitourenguru.ch/calc_data

![image](https://cloud.githubusercontent.com/assets/4577727/22323273/1e1f8bd2-e3a2-11e6-8d44-64ada0eccac6.png)

Result Feedback customer
"
Mit dem KML-Attribute “IconStyle\scale” ist es möglich, die Grösse eines Icons festzulegen. Seit heute ist das Scaling auf geo.admin.ch um ca. einen Faktor 4 verändert. D.h. alle Icons auf Skitourenguru sind 4 mal kleiner. Ich kann zwar bei mir ohne weiteres die Werte neu anpassen, aber ich befürchte, dass sich das Scaling auf geo.admin.ch erneut verändern wird.
Bereits zwischen dem 8.11 und 11.11.2015 war das Scaling 3 Tage lang um einen Faktor 2-3 anders. Was ist wohl geschehen?
"

Own observation in 3D

![image](https://cloud.githubusercontent.com/assets/4577727/22323288/350e966c-e3a2-11e6-9e40-29bffef27c5b.png)

-> they seem here quite small

**Comment by davidoesch** [comment]
@procrastinatio AFAIK the KML is OGC compliant..am I correct?

**Comment by smug007** [comment]
Ich habe dir Icons über die Nacht ca. 3-8 mal grösser gemacht. Obiges Bild repräsentiert also bereits den neuen, korrigierten Soll-Zustand.
Seit gestern gibt es noch einen weiteren Unterschied: Das Objekt-Informations-Fenster geht automatisch nach 5 Sekunden wieder zu (nur im iFrame).

**Comment by davidoesch** [comment]
Ein feedback bzgl iframe Objekt info autoclose: auf der demo Anwendung https://www.geo.admin.ch/iframe ist dieses automatische schliessen nicht der Fall - liegt as ihrer implementation?

**Comment by oterral** [comment]
@smug007  sorry about that. In 11.2016, the js library(openlayers) we use to parse KML file had changed the formula to get the icon's size from scale, so we had to fix this on our side (2 weeks after I think) before fixing this in openlayers.  So since tomorrow, so formula is simplier and I hope it will stay like this for a long time:  size on map  = scale * original size

**Comment by oterral** [comment]
I look for the popup problem.

**Comment by smug007** [comment]
Gute Frage? Tatsache ist, dass der 5 Sek-Autoclose erst seit gestern (update?) geschieht... Ich verwende lanweiliges Standard-html im description field:
<description><![CDATA[<div>Gipfel: <b>Mutteristock</b></div><div>Start: <b>Hinter Bruch</b></div><div>Risiko-Indikator: <b><font style="color: #000000; background-color: #FF0000">2.90</font></b></div><div>Höhendifferenz: <b>1370 m</b></div><div>Starthöhe: <b>917 m</b></div><div>Gipfelhöhe: <b>2287 m</b></div>]]></description>

herzliche Grüsse
Günter

**Comment by oterral** [comment]
@smug007 can you confirm the 5sek-Autolose is fixed with https://github.com/geoadmin/mf-geoadmin3/pull/3695

**Comment by davidoesch** [comment]
Hi I raised the prio since it affects other customers iframe ( like wandern.ch) 
@oterral can you give clear instructions if the customer has
either
a) to change his code
or
b) when we wil have a fix?

**Comment by oterral** [comment]
they must adjiust the scale value in the KML file or resize their images.

**Comment by procrastinatio** [comment]
Tested against `ogckml22.xsd`:
```
Validating you KML file...
status: invalid
url: http://www.skitourenguru.ch/calc_data/kml/Switzerland_RiskSymbol079.kml
message: KML document 'Switzerland_RiskSymbol079.kml' is invalid DocumentInvalid(u"Element '{http://www.opengis.net/kml/2.2}extrude': This element is not expected. Expected is ( {http://www.opengis.net/kml/2.2}coordinates )., line 74",)
warnings: Set the "Content-Type" to "application/vnd.google-earth.kml+xml" please
schema: ogckml22.xsd
```

**Comment by smug007** [comment]
www.skitourenguru.ch:
- In the next version I will delete the "extrude" element. This element doesn't affect the issue!
- All scale values in the KML got adapted
- For my project the issue is resolved.
- Please try to make sure, that the scaling procedure doesn't change or inform me, if it has to change...

**Comment by davidoesch** [comment]
Hi Marc

There are still files which did not get converted
https://map.geo.admin.ch/index.html?topic=ech&lang=en&bgLayer=ch.swisstopo.swissimage&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bafu.wrz-wildruhezonen_portal,ch.swisstopo.swisstlm3d-wanderwege,ch.swisstopo.swisstlm3d-karte-grau,KML%7C%7Chttps:%2F%2Fpublic.geo.admin.ch%2FmBWvOelIQY-1KLws5cHGeA&layers_visibility=false,false,false,false,true,true&layers_timestamp=20131231,,,,,&X=182764.84&Y=633331.77&zoom=10.784738571779302.

Customer feedback ID : 2017030114335370

**Comment by oterral** [comment]
Fixed
