### ISSUE TITLE
3D IE11 : no buildings shown

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3694]
Open this
https://map.geo.admin.ch/?topic=ech&lang=de&bgLayer=ch.swisstopo.pixelkarte-farbe&layers_visibility=false&layers_timestamp=18641231&lon=9.15914&lat=47.44552&elevation=656&heading=360.000&pitch=-40.005 

in IE11 of a swisstopo installation: no buildings shown

it seesm it loads no buildings at all?

![image](https://cloud.githubusercontent.com/assets/4577727/22326960/33e4b790-e3b5-11e6-9d66-75f294266727.png)

**Comment by davidoesch** [comment]
update if I set  manually to edge and back the it works
![image](https://cloud.githubusercontent.com/assets/4577727/22327069/aca65e2c-e3b5-11e6-86a3-99576d724c8f.png)

**Comment by oterral** [comment]
3d is deactivated for IE9 . I'm even surprise you succeed to open it

**Comment by davidoesch** [comment]
Sorry , it is IE11 of your official federal laptop. question is: can you reproduce this behavior?

**Comment by oterral** [comment]
Seems to works only when cache is disabled (with the console opens).

**Comment by oterral** [comment]
I can reproduc ea js error when we opens 3d directly. It's a timing issue caused by the alert message.

**Comment by oterral** [comment]
@davidoesch it's fixed no?

**Comment by davidoesch** [comment]
Fixed, yes
