### ISSUE TITLE
WMS Canton solothurn -parsing error

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3698]
![image](https://cloud.githubusercontent.com/assets/4577727/22415832/983327b4-e6ca-11e6-9a9a-176adad97b28.png)

**Comment by oterral** [comment]
@davidoesch it seems they have a bad configuration when we access it via ogc proxy. [See](https://api3.geo.admin.ch/ogcproxy?url=http%3A%2F%2Fwww.sogis1.so.ch%2Fwms%2Fgrundbuchplan%3FSERVICE%3DWMS%26REQUEST%3DGetCapabilities%26VERSION%3D1.3.0)

**Comment by davidoesch** [comment]
will contact sogis

**Comment by davidoesch** [comment]
"
Cannot read property  ‚trim‘ of null: *Das* Problem ist einfach gelöst: 

-> http://geoweb.so.ch/wms/grundbuchplan

Aber das *nächste* Problem wird dann anscheinend sein, dass da von unserer IT irgendwie Cookies mitverschickt werden. Bei mir funktioniert die richtige  URL jedenfalls nicht: 

Parsing error! b.getAttribute(...) is null

-> Problem ist bekannt und an die IT gemeldet.
"

**Comment by davidoesch** [comment]
"Das Cookies-Problem wurde gelöst. Die WMS des Kantons Solothurn funktionieren jetzt in map.geo.admin.ch. Ausprobiert habe ich: http://geoweb.so.ch/wms/avwms	
"

According to wms owner solved
