### ISSUE TITLE
tooltip service LV03 shift of 0.4m? 

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3699]
Customer feedback ID : 2017012714293401

"Wenn man die Koordinaten die man erhält (wenn man z.B. einen Grenzpunkt anwählt) mit denen aus einem Kataster vom GIS vergleicht stimmen die beiden Angaben nicht überein.

Sie können es ja mal ausprobieren. Es gibt zum Beispiel im GIS Solothurn die Möglichkeit komplette Kataster herunterzuladen.
Wenn man diesen (im System LV03) öffnet, den Grenzpunkt anwählt und die Werte mit ihren Angaben vergleicht ist eine Abweichung von ca. 40cm ersichtlich.

Dies war früher nicht so.
"
user is referencing this screenshot
![image](https://cloud.githubusercontent.com/assets/4577727/22416129/b1402656-e6cc-11e6-8481-4b68a7fd0dac.png)

eg for https://s.geo.admin.ch/7119c2e1ec

also: the symbols are not congruent

might have been related to https://github.com/geoadmin/mf-chsdi3/issues/2416

**Comment by davidoesch** [comment]
Issue identified: WMS in LV95...
Next steps: @ltclm is investigating solutions with @procrastinatio

**Comment by gjn** [comment]
@davidoesch We said this should be solved on data provider side. So can we close this?

**Comment by davidoesch** [comment]
@ltclm is checking with Ibele /German if the cwm wms is also serving the appropriate LV . It should -

**Comment by davidoesch** [comment]
ping @beat-github

**Comment by gjn** [comment]
Discussion going on to adapt geoshop service to have lv03 natively. So this is on hold.
