### ISSUE TITLE
Display profile link for KML MultiGeometry containing one geometry

### ISSUE THREAD

**Issue by oterral** [geoadmin/mf-geoadmin3#3704]
Steps to reproduce:

1) Open http://www.gpsies.com/createTrack.do?language=en
2) Create a line 
3) Export to KML 
4) Import this KML to Geoadmin
5) Click on the line

Results:
  No link to display the profile

Expected:
 The link to display the profile appeared

**Comment by gjn** [comment]
Treat multilinestring as linestring on import, when possible (end of one element is start of next element).

**Comment by oterral** [comment]
Fixed in prod
