### ISSUE TITLE
Make the exported draw kml editable again.

### ISSUE THREAD

**Issue by oterral** [geoadmin/mf-geoadmin3#3705]
The idea is to export the kml with the good adminID or fileId in the name then when we reimport it, you can modify it again and save it to public.geo.admin.ch.

@davidoesch does it sounds as  a good idea?

**Comment by davidoesch** [comment]
Hmm not yet convinced. So anybody can try to take whatever KML try and error an admin id and upload it? How do we make sure no one does include bad stuff into the kml (malicious content, even as comments etc)? How do you check for sanity of the file.. So no one ads stuff which does not work in our version of ol3 ?

**Comment by davidoesch** [comment]
Well if he exports it he wants to change it. So md5 will always be different. Plus mmgt of checksum another service. keep it simple

**Comment by oterral** [comment]
Ok
