### ISSUE TITLE
3D tilt

### ISSUE THREAD

**Issue by AFoletti** [geoadmin/mf-geoadmin3#3706]
For one reason or another, one of the highest ranked item in my 3D whishlist has become true. You can tilt over the horizontal line!

Look up at the [Grimsel Dam](https://s.geo.admin.ch/712eb96cc7), the [Matterhorn](https://s.geo.admin.ch/712eb9b953) or the [Eiger Nordwand](https://s.geo.admin.ch/712eb9f963) (which sadly looks like s*&t) !

![image](https://cloud.githubusercontent.com/assets/691243/22586698/821e4652-e9fe-11e6-9159-e633f9678ef9.png)

You can't achieve that via the navigation interface, which tells you that tilting more is impossible, but works via middle mouse button.

I'm almost sad to report this one... I don't want to see it reverted :wink:

**Comment by gjn** [comment]
You can't reach it with the buttons in the middle. But you can reach it with ctrl-Mouse Movement. Since seom time now.

**Comment by AFoletti** [comment]
ok, but if it's officially possible, why make the UI tell you it's impossible?

**Comment by davidoesch** [comment]
Hi 

This works as designed. in accordance with schweizmobil. if the normal user tilts to  much he gets lost. Normal user works with buttons. Pro works with mouse and keyboard shortcuts.
