### ISSUE TITLE
Swisssearch Result: no tiles shown

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3709]
Hi

All devices Intranet and Internet

Open app

enter an address

when clicking on results

->marker appears but no tiles

![image](https://cloud.githubusercontent.com/assets/4577727/22638321/aa830786-ec47-11e6-8c05-a77a0f72028d.png)

**Comment by davidoesch** [comment]
@loicgasser @gjn @ltclm any ideas?

**Comment by ltclm** [comment]
yes we're on it.
yesterday import was in lv95 due to a error on our side.

**Comment by ltclm** [comment]
wms is working again as expected, 
the sphinx index update will take about 30'
