### ISSUE TITLE
Geolocation centers permanently the map on the GPS position

### ISSUE THREAD

**Issue by daguer** [geoadmin/mf-geoadmin3#3710]

**Comment by cedricmoullet** [comment]
Wenn ich die aktive Position einschalte beginnt die Karte zu "flackern" der Zoom springt zurück wenn ich ein-zoome oder die Karte pulsiert auf dem Bildschirm. Das selbe auf mobilen Geräten wie iPhone. Sobald die Positionierung ausgeschaltet ist verhält sich die Karte normal. Bei schlechtem GPS-Empfang ist das Verhalten besser als draussen mit guter GPS-Genauigkeit (5m). Woran kann das liegen? Hat jahrelang funktioniert!!!

**Comment by oterral** [comment]
There is already a PR to fix that.
