### ISSUE TITLE
Map doesn't display after a search

### ISSUE THREAD

**Issue by cedricmoullet** [geoadmin/mf-geoadmin3#3711]
1. Start map.geo.admin.ch
2. Search for "Bergerie 38 Payerne"

-> Map doesn't appear

**Comment by loicgasser** [comment]
Data update issue, @ltclm working on it right.

**Comment by loicgasser** [comment]
duplicate of https://github.com/geoadmin/mf-geoadmin3/issues/3709

**Comment by davidoesch** [comment]
done
