### ISSUE TITLE
Impossible to print vector polygons with 3 points

### ISSUE THREAD

**Issue by oterral** [geoadmin/mf-geoadmin3#3714]
[Test](https://map.geo.admin.ch/?X=214089.51&Y=692860.69&zoom=6&topic=ech&lang=de&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bav.haltestellen-oev,ch.swisstopo.swisstlm3d-wanderwege,KML%7C%7Chttps:%2F%2Fpublic.geo.admin.ch%2FyK1QZOcrSeiPFdjmnZJqhg&layers_visibility=false,false,false,true,true&layers_timestamp=18641231)

Java error:
```
Error while generating PDF:
DocumentException: java.lang.IllegalArgumentException: Invalid number of points in LinearRing (found 3 - must be 0 or >= 4)
	at com.vividsolutions.jts.geom.LinearRing.validateConstruction(LinearRing.java:114)
	at com.vividsolutions.jts.geom.LinearRing.<init>(LinearRing.java:106)
.
.
.
```

**Comment by gjn** [comment]
We try to fix the line sent to the print.

**Comment by procrastinatio** [comment]
How do we validate geometries in OL3 ? For instance, this [KML](https://s.geo.admin.ch/71b617fba5) has 7 features, of which 4 are non valid and hence not displayed ?
