### ISSUE TITLE
draw: movie import -youtube does not work

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3716]
Take this youtube URL
https://www.youtube.com/watch?v=YoT47kJYyBU 

Open Draw
add icon
add url above into video URL
![image](https://cloud.githubusercontent.com/assets/4577727/22788326/c367aa96-eedf-11e6-90c8-082ecd56ae14.png)

field contains now
<iframe src="https://www.youtube.com/watch?v=YoT47kJYyBU" height="200" width="auto"></iframe>

Result

Video is not working

if I change manually iframe code to
<iframe width="560" height="315" src="https://www.youtube.com/embed/YoT47kJYyBU?rel=0" frameborder="0" allowfullscreen></iframe>

it works

**Comment by oterral** [comment]
Google changes something to their config:
```
Refused to display 'https://www.youtube.com/watch?v=YoT47kJYyBU' in a frame because it set 'X-Frame-Options' to 'SAMEORIGIN'.
```

According to result on google using ```https://www.youtube.com/embed/YoT47kJYyBU'`` it works

[See this draw](https://map.geo.admin.ch/?topic=ech&lang=fr&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bav.haltestellen-oev,ch.swisstopo.swisstlm3d-wanderwege,KML%7C%7Chttps:%2F%2Fpublic.geo.admin.ch%2F94-fpMxvTDKuuLzsCdruig&layers_visibility=false,false,false,false,true&layers_timestamp=18641231,,,,&X=190000.00&Y=660000.00&zoom=1)

**Comment by davidoesch** [comment]
Question:
Proposal: we change the wrapper of movie to youtube ( since most movies are online on youtube anyway)
So make the iframe code generated to <iframe width="560" height="315" src="https://www.youtube.com/embed/<ID>?rel=0" frameborder="0" allowfullscreen></iframe>

make sense? see as well #3717

**Comment by loicgasser** [comment]
We could change -> https://www.youtube.com/watch?v=YoT47kJYyBU
to
https://www.youtube.com/embed/YoT47kJYyBU

for our users.

**Comment by davidoesch** [comment]
please do so ---
