### ISSUE TITLE
Background image in help

### ISSUE THREAD

**Issue by rbovard** [geoadmin/mf-geoadmin3#3718]
When scrolling the page in help, the background image is repeated on long pages (ie. http://help.geo.admin.ch/?id=94&lang=fr).

It's possible to avoid this behaviour with this change in `js_css/styles.css`:

`background:url('../img/help_geoportal_bckgd.jpg') repeat;` > `background:url('../img/help_geoportal_bckgd.jpg') repeat fixed;`

**Comment by oterral** [comment]
Yes a lot nicer.
