### ISSUE TITLE
KML Order issue

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3719]
Add two lokal KML

"•	Ich öffne die website. Alles funktioniert 100% konform.
•	Ich schleppe den ersten Layer (egal welchen), auf die Map. Der Layer erscheint. Alles ok.
•	Ich schleppe den zweiten Layer auf die Map. Dieser projektiert sich auf die Map und den ersten Layer, liegt quasi obendrauf. Noch immer alles ok.

Problem:
•	Ich möchte, dass Layer 1 oben liegt, nicht Layer 2.
•	Ich finde den Optionsknopf auf dem Menu links auf dem Tab Dargestellte Karten, das schwarze Zahnrädchen rechts auf weissem Hintergrund)
•	Ich drücke den inzwischen ausgefahrenen Pfeilknopf von Layer 2 nach unten (zum Beispiel).
•	Der Layer springt eine Etage nach unten, der Inhalt des Layer ist aber nicht mehr zu sehen und kommt auch nicht mehr zu Vorschein.

Ich habe diesen Vorgang mit Microsoft Edge und mit dem normalen Internet Explorer geprüft auf 2 verschiedenen Computern, Work and Home.
"

**Comment by gjn** [comment]
Can this be reproduced? Did the client send the kmls?

**Comment by davidoesch** [comment]
Yes he did... The mail is in the Helpdesk inbox (sorry, in did not add the customer id here)

**Comment by procrastinatio** [comment]
Cannot reproduce, with some dummy data:

https://s.geo.admin.ch/71b6492aca

Two KMLs, one polygon and one line (above). Changing the order in the catalog also change the order in the link

**Comment by oterral** [comment]
customer id : 2017021708464873

**Comment by oterral** [comment]
can't reproduce too

**Comment by davidoesch** [comment]
see this
[Screencast_2017-03-16-15-20-15.zip](https://github.com/geoadmin/mf-geoadmin3/files/847944/Screencast_2017-03-16-15-20-15.zip)
with kml
[Desktop.zip](https://github.com/geoadmin/mf-geoadmin3/files/847947/Desktop.zip)

**Comment by oterral** [comment]
Thx I can reproduce
