### ISSUE TITLE
Real hyperlink in tooltip, instead of url

### ISSUE THREAD

**Issue by cedricmoullet** [geoadmin/mf-geoadmin3#3721]
![image](https://cloud.githubusercontent.com/assets/319676/23225038/cf043e5e-f930-11e6-85ad-b6061ba81ae5.png)

**Comment by cedricmoullet** [comment]
For www.facade-au-soleil.ch

**Comment by cedricmoullet** [comment]
BTW: this url is not available.......

**Comment by ltclm** [comment]
@AFoletti can you ask the datenherr if he wants to show a hyperlink or the url in the tooltip of the availability zoomlevel? Or can/should we do data modifications like this ourselves?

The url's in the feature tooltips will be activated today by bfe.

**Comment by oterral** [comment]
chsdi issue.

**Comment by AFoletti** [comment]
sorry, skipped this one.
I'll of course ask the datenherr to fix it

**Comment by procrastinatio** [comment]
Or you may have a function turning every URL in tooltips into links (as in GitHub)

**Comment by oterral** [comment]
It could  lead to false link and it's better if the datenherr has full control of what he wants to display.

**Comment by ltclm** [comment]
agree with @oterral, we should not change the data content.
