### ISSUE TITLE
Bad aspect ratio with embed maps on mobile

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3722]
This is a bug report. I'm experimenting with your free iFrame integration service. I'm embedding a KML file with some placemarks. On Desktop, everything is running fine. On mobile devices, the aspect ratio of the map is not ok after loading. It's fine again when I rotate my device into portrait mode and back again. But before, the vertical axis is too short, the map looks squeezed. The icon of the KML are as well. Also, the placemark icons are hard to select. To me it appears the sensitive spot is below the icon itself. I have to tap below the icon to select an icon. Again, after rotating my device into portrait mode, everything's working fine.

I checked on iOS and Android, with different browsers (Safari, Firefox, Chrome). Same behaviour everywhere.

I attached 2 screenshots, one with the bad aspect ratio (just after loading the website), another I took rotating my device into portrait mode and back again.

For a limited time, you find an example of this behaviour here: http://wis.slf.ch/versuchsfeld/poc2.html

On iPhone it can be reproduced on Android 7.1.1 not see as well discussion in forum

**Comment by marrcl** [comment]
Title is a bit misleading: Not only the KML point is not round, the whole map has a bad aspect ratio.
