### ISSUE TITLE
Representation issues of CadastralWebMap in 3D

### ISSUE THREAD

**Issue by cedricmoullet** [geoadmin/mf-geoadmin3#3723]
https://map.geo.admin.ch/?topic=ech&lang=de&bgLayer=voidLayer&layers=ch.kantone.cadastralwebmap-farbe&lon=6.93592&lat=46.82637&elevation=549&heading=360.000&pitch=-40.000

https://map.geo.admin.ch/?topic=ech&lang=de&bgLayer=voidLayer&layers=ch.kantone.cadastralwebmap-farbe&X=186362.11&Y=561642.20&zoom=13

In 3D, we see artefacts. It seems that the tiles are not aligned correctly.

**Comment by rbovard** [comment]
Misalignment + different zoom level queries:

https://map.geo.admin.ch/?topic=ech&lang=fr&bgLayer=voidLayer&layers=ch.kantone.cadastralwebmap-farbe&lon=6.23370&lat=46.35950&elevation=3189&heading=0.007&pitch=-50.094

**Comment by davidoesch** [comment]
might be related to the different zoom levels and caching options we have. changes in styling/symbology is currently in discussion by dataowner: see jira ticket https://jira.swisstopo.ch/browse/BGDIDI_KB-1354

**Comment by ltclm** [comment]
could be related to
geoshop lv95 to wms-bgdi lv03 to 3d wgs84

**Comment by gjn** [comment]
Analyse of our WMS that uses external WMS in LV95.

**Comment by oterral** [comment]
Duplicate of #https://github.com/geoadmin/mf-geoadmin3/issues/3057 ?

**Comment by procrastinatio** [comment]
@oterral Yes, it is.
