### ISSUE TITLE
Print: missing tiles

### ISSUE THREAD

**Issue by gjn** [geoadmin/mf-geoadmin3#3724]
From client:

ich habe immer wieder Probleme beim PDF Ausdruck. Es gibt auf der Karte immer wieder quadratische Felder welche weiss sind, und den Inhalt nicht drucken. Sehe Sie auch im Attachment. Bitte um Lösungsvorschlag.

Here's part of the pdf:
![image](https://cloud.githubusercontent.com/assets/2572317/23301510/8f528c6a-fa8a-11e6-9293-09560371997b.png)

What could cause this?

**Comment by loicgasser** [comment]
https://s.geo.admin.ch/718fd55693 is the area the customer tried to download.
No idea at the moment as I can't reproduce.

**Comment by loicgasser** [comment]
@gjn 
Can you add the browser info? Maybe he can't read the pdf properly, best would be for him to send us the pdf as well so that we can exclude this option.

**Comment by gjn** [comment]
I'll attach pdf.

**Comment by procrastinatio** [comment]
It would be nice to see the PDF, the print server may be out of cause for once.

**Comment by gjn** [comment]
[loeschen1.pdf](https://github.com/geoadmin/mf-geoadmin3/files/826952/loeschen1.pdf)

PDF attached.

**Comment by procrastinatio** [comment]
Hem, did knew we were producing PDF on windows:

```$ pdfinfo  loeschen1.pdf
Title:          map.geo.admin.ch(1).pdf
Author:         Optiplex
Creator:        PScript5.dll Version 5.2.2
Producer:       Acrobat Distiller 9.0.0 (Windows)
```
Looks like the original PDF is reencoded on the fly by Adobe Distiller. If I do not have the original PDf, i.e. the one we are delivering, there is not much we can do.
