### ISSUE TITLE
ol3-cesium renamed to ol-cesium

### ISSUE THREAD

**Issue by fredj** [geoadmin/mf-geoadmin3#3727]
FYI, the `ol3-cesium` project has been renamed to `ol-cesium`; you may need to update the git remote addresse

**Comment by gberaudo** [comment]
In addition:
- the build js file has also been renamed to olcesium.js.
- the OpenLayers(4) submodule is now called ol.

**Comment by loicgasser** [comment]
Thanks for the heads up !

**Comment by gjn** [comment]
Include update ol4.

**Comment by oterral** [comment]
fixed by #3772
