### ISSUE TITLE
KML can not be printed

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3730]
Try to print 

https://map.geo.admin.ch/?X=206947.67&Y=747629.46&zoom=4&topic=ech&lang=de&bgLayer=ch.swisstopo.pixelkarte-farbe&layers_visibility=false,false,false,true,true&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bav.haltestellen-oev,ch.swisstopo.swisstlm3d-wanderwege,KML%7C%7Chttps:%2F%2Fpublic.geo.admin.ch%2FzAo3XazhQmGMHVXyfdolOw&layers_timestamp=18641231,,,,

try to print a PDF
no PDF generated

Customer feedback ID : 2017030801021254 

Another example:
https://s.geo.admin.ch/71ddedfdb5

**Comment by loicgasser** [comment]
bogus geoms, @procrastinatio is working on it. See
https://github.com/geoadmin/mf-geoadmin3/pull/3728

**Comment by oterral** [comment]
Duplicate with #3714
