### ISSUE TITLE
Dead links in WMS import

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/mf-geoadmin3#3734]
http://ogc.heig-vd.ch/mapserver/wms?SERVICE=WMS&REQUEST=GetCapabilities&VERSION=1.3.0
http://www.sogis1.so.ch/cgi-bin/sogis/sogis_geologie.wms?SERVICE=WMS&REQUEST=GetCapabilities&VERSION=1.3.0
https://www.sogis1.so.ch/cgi-bin/sogis/sogis_bpav.wms?SERVICE=WMS&REQUEST=GetCapabilities&VERSION=1.3.0 (all sogis)

**Comment by davidoesch** [comment]
yep I've seen that as well @cedricmoullet  can you contact your connection of at Yverdon?

**Comment by procrastinatio** [comment]
Hardcoding external resources! Could we not have a service for that ?

**Comment by cedricmoullet** [comment]
Should be solved

**Comment by davidoesch** [comment]
And we have an open ticket : redesign import.. Where we would have a service

**Comment by procrastinatio** [comment]
See https://github.com/geoadmin/mf-geoadmin3/pull/3752
