### ISSUE TITLE
WMS default styles

### ISSUE THREAD

**Issue by procrastinatio** [geoadmin/mf-geoadmin3#3736]
Discrepancy in WMS **default** styles requests:

In 2D, styles names are omitted (**STYLES=**)
https://wms.geo.admin.ch/?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=ch.bafu.permafrost&CRS=EPSG%3A21781&STYLES=&WIDTH=739&HEIGHT=427&BBOX=420000%2C30000%2C900000%2C307000

In 3D, styles are explicitly added (**styles=default**):

https://wms.geo.admin.ch/?layers=ch.bafu.permafrost&format=image%2Fpng&service=WMS&version=1.3.0&request=GetMap&crs=EPSG:4326&bbox=46.40625,7.031250000000002,47.109375,7.734374999999999&width=256&height=256&styles=default&transparent=true

which makes some server break (Geoserver namely)

According to the spec, the default style has not to be advertised. The following requests:

```
STYLES=
STYLES=,,
STYLES=default,default
```
are valid. The latter being very rare, though.

**Comment by oterral** [comment]
I think `default` styles was added because some WMS wanted it.

**Comment by oterral** [comment]
no, it was because Cesium removed STYLES parameetr if there was undefined value, Replacing `default` by ``  should work.

**Comment by procrastinatio** [comment]
Geoserver
No **default** --> OK

 "http://wms.stauffer-studach.ch:8091/geoserver/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image/png&TRANSPARENT=true&LAYERS=Datenblatt:BAUZONEN_GR_HN&CRS=EPSG:21781&STYLES=&WIDTH=1920&HEIGHT=833&BBOX=46.40625,7.031250000000002,47.109375,7.734374999999999" 

**default** --> NOK
 "http://wms.stauffer-studach.ch:8091/geoserver/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image/png&TRANSPARENT=true&LAYERS=Datenblatt:BAUZONEN_GR_HN&CRS=EPSG:21781&STYLES=default&WIDTH=1920&HEIGHT=833&BBOX=46.40625,7.031250000000002,47.109375,7.734374999999999"
