### ISSUE TITLE
GeoJSON Update rate

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3740]
Use case:

Case:
A) we have a GEOJSON, pushed on our infra (s3) updated every ten seconds- minute
B) geosjon display is in iframe on a webiste, webiste is *not* reloaded

-> without reloading map.geo.admin.ch (F5) : can we update the Data Geojson source? eg the position and color and attribute of a geometry LIVE, and recenter the map

use case:
- Live tracking of Patrouille des Glaciers
- Meteodata

**Comment by loicgasser** [comment]
sure we can, it is already the case with hydroweb layers (and they are in iframes).
There is a property called
`updateDelay: 300000`
in milliseconds. (so refreshed every 5 minutes at the moment)

**Comment by davidoesch** [comment]
Yes!
