### ISSUE TITLE
Permalink not added in topic gewiss

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3744]
reproduce

open https://map.geo.admin.ch/?topic=gewiss

set void layer as bg
add pk10
then try to share this map: won't work because the layer is not added in pl

![image](https://cloud.githubusercontent.com/assets/4577727/24196844/93600268-0eff-11e7-9575-47e96afbbaf6.png)

or is this" works as defined"? IMHO not
I add this as a showstopper, since it affects PL

**Comment by davidoesch** [comment]
@mariokeusen standard nodes are not opened as well

**Comment by gjn** [comment]
I can reproduce.

Strange, what's the default PL for topic gewiss?

**Comment by loicgasser** [comment]
Selected and default layers have been removed by @mariokeusen  for this topic if I am not mistaken.

**Comment by davidoesch** [comment]
strange, once in a while it works....every second time not... (ongoing deploy?)

**Comment by loicgasser** [comment]
yes

**Comment by mariokeusen** [comment]
could reproduce as well.
standard nodes should be open
Info: former default layer has been removed upon customer request for this topic recently

**Comment by oterral** [comment]
Bad value in the bod .
null instead of  empty array.

**Comment by oterral** [comment]
@mariokeusen @davidoesch can you confirm it's fixed now?

**Comment by loicgasser** [comment]
it has been enforced in DB as well, those fields are not nullable anymore.

**Comment by davidoesch** [comment]
Fixed. And thanks for the enforcement

**Comment by mariokeusen** [comment]
Fixed. Thanks!

**Comment by gjn** [comment]
Merci pour le fast fix.
