### ISSUE TITLE
Thickness of Line in 3D LOD Dependent

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3745]
KML Line is visible
on https://map.geo.admin.ch/?topic=ech&lang=de&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bav.haltestellen-oev,ch.swisstopo.swisstlm3d-wanderwege,KML%7C%7Chttps:%2F%2Fpublic.geo.admin.ch%2FXjMtd9NmTCiI6oCikoIJ4A&layers_visibility=false,false,false,false,true&layers_timestamp=18641231,,,,&lon=8.03358&lat=46.49770&elevation=3569&heading=99.329&pitch=-25.779
![image](https://cloud.githubusercontent.com/assets/4577727/24237891/93754552-0fa8-11e7-9b16-540e8d74b931.png)

but not on
https://map.geo.admin.ch/?topic=ech&lang=de&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bav.haltestellen-oev,ch.swisstopo.swisstlm3d-wanderwege,KML%7C%7Chttps:%2F%2Fpublic.geo.admin.ch%2FXjMtd9NmTCiI6oCikoIJ4A&layers_visibility=false,false,false,false,true&layers_timestamp=18641231,,,,&lon=7.57914&lat=46.49615&elevation=17852&heading=99.001&pitch=-25.728

![image](https://cloud.githubusercontent.com/assets/4577727/24237903/a412508a-0fa8-11e7-8486-82a5c9c9d787.png)

-> Can thickness be adapt based on distance  ( we alread discussed this in

**Comment by gjn** [comment]
AFAIK, it's not possible. Thickness is defined in meters, not pixels. We would need to ask AGI about that.

**Comment by davidoesch** [comment]
not even sure if we  need it.. as a user if you want overview: switch to 2d

**Comment by oterral** [comment]
Cesium provided an example somewhere but if there is a lot of lines there could be potiental performance issue.
For me, it's not necessary. because in fact, if you go far away, seeing the line in 3d is the same than seeing the line in 2d so switch to 2d if you want to see it globally.

TangramJS does the same. You specify a width (in meters) and the line is being smaller when you zoom out

**Comment by davidoesch** [comment]
+1
