### ISSUE TITLE
Digest cycle conflicts when offline

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3750]
Offline does not work anymore

See description in:

https://forum.camptocamp.org/t/probleme-site-web-map-geo-admin-ch-sur-iphone/182512/5

**Comment by oterral** [comment]
There is a digest cycle conflicts.
Customer feedback ID : 2017032712513197

**Comment by davidoesch** [comment]
ETA for fix?

**Comment by gjn** [comment]
Introduced last week? Or earlier?

**Comment by oterral** [comment]
no earlier , fix is coming
