### ISSUE TITLE
lang switcher order

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3753]
Hi

if opening http://map.geo.admin.ch/?layers=ch.bafu.gewaesserschutz-badewasserqualitaet 
I get this lang order
![image](https://cloud.githubusercontent.com/assets/4577727/24455488/090a262a-1490-11e7-98eb-0313606573e8.png)

expected is this order as in www.geo.admin.ch
![image](https://cloud.githubusercontent.com/assets/4577727/24455540/469a8430-1490-11e7-849f-a4ea32939b1a.png)

**Comment by loicgasser** [comment]
Fix via https://github.com/geoadmin/mf-geoadmin3/pull/3748
https://mf-geoadmin3.int.bgdi.ch
