### ISSUE TITLE
Support loading of hidden layers via permalink

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3755]
Hi Gilbert

Situation
In the past we had the function that we could load layers which are not in the layers config via permalink, like eg https://map.geo.admin.ch/?layers=ch.myamt.dummyname

we suppressed this so user could not load layers which were in the FSDI WMTS but available exclusively for SMM. ( Skitouren...) today this restriction is not longer valid

For Automata and other testing purposes it would made sense to reintroduce this hidden feature for testing purposes-- sow could not test automata process on full stack with an artificial layer

An other option :this will be solved as soon as we have https://github.com/geoadmin/mf-geoadmin3/issues/2414 with a WMTS import

Your thoughts?

cc @ltclm

**Comment by oterral** [comment]
Doy ou have a test layer's name? with the topic all, it doesn't work?

**Comment by davidoesch** [comment]
ch.tamedia.schweizerfamilie-feuerstellen

**Comment by gjn** [comment]
Ok, we try it with WMTS import.

**Comment by davidoesch** [comment]
#2414 - you can start on this for the wmts point

**Comment by cedricmoullet** [comment]
@gjn status of this issue ?

**Comment by gjn** [comment]
Closed. I've created a dedicated branch for this (it was for automata)
