### ISSUE TITLE
Mobile Help/Promotion

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3759]
Situation

most user are not aware of mobile capabilities

Therefore

Adaption of https://help.geo.admin.ch/?id=55
- [x]  Title to mobile
- [x]  Section : "Kartenviewer für Unterwegs" with instructions on how to add a link to homescreen as shown in  https://www.ropetech.ch/asp/default.asp?PAGE=MOBI
- [x]  Offline , existing content enriched with tuorial video

Reuse QR code to: bring your map to your mobile
- [x] add instructive imeg/Link to https://www.geo.admin.ch/de/map-viewer/karten-viewer.html  and carousel

**Comment by pauloamado** [comment]
All done:
HELP: https://help.geo.admin.ch/?id=55&lang=de (DE/FR/IT/EN)
CMS : https://www.geo.admin.ch/de/map-viewer/karten-viewer.html (DE/FR/IT/EN)

Image and text can be used for carrousel. I will see it with Louise.

**Comment by davidoesch** [comment]
Excellent job!
