### ISSUE TITLE
Sanitizse description/html before displaying

### ISSUE THREAD

**Issue by gjn** [geoadmin/mf-geoadmin3#3760]
We should sanitize parsed kml test/description before displaying it in our popup.

See mail.

**Comment by gjn** [comment]
ng-bind-html that automatically sanitize the html.

**Comment by procrastinatio** [comment]
We really need a KML parser/checker/validator for KML... (extending http://codepen.io/procrastinatio/full/53303b44480d3dda4e2f5161ef4f2a51/)

Every 2 days, I have a _but-my-KML-works-in-google-earth-but-not-in-map.geo.admin.ch_ question

**Comment by gjn** [comment]
KML project was not accepted. We have to improve step by step during normal maintenance.

Not ideal, I know.

**Comment by oterral** [comment]
It seems using the angular-sanitize module this kind of stuff are removed.

**Comment by oterral** [comment]
We have discuss to sanitize only external KMLs but even the KMLs from public.geo.admin could be malicious.
https://s.geo.admin.ch/7268b5bef0

**Comment by gjn** [comment]
Any way to only filter out JS in the kml?

**Comment by oterral** [comment]
yes with an beautiful regex

**Comment by gjn** [comment]
argl.
