### ISSUE TITLE
Mobile detection

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3763]
Hi oli 
analyzing KIBANA, we assume that browser sniffing, user-agent -detection, touch devices regarding mobile is probably not detecting all devices ( latest samsung models etc...)
-> we very low  mobile client hits....

can you investigate?

**Comment by oterral** [comment]
it seems very clear something happens 14.03 at 15:30

**Comment by oterral** [comment]
seems fix, isn't it?

**Comment by davidoesch** [comment]
Ask Gilbert

**Comment by oterral** [comment]
Kibana issue
