### ISSUE TITLE
Panning lubis fullres on Android

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3765]
https://api3.geo.admin.ch/luftbilder/viewer.html?lang=de&width=5954&layer=ch.swisstopo.lubis-luftbilder_schwarzweiss&bildnummer=19470250030640&title=ch.swisstopo.lubis-luftbilder-dritte-kantone.ebkey&rotation=95&datenherr=swisstopo&height=5952&x=3573.89&y=3157.34&zoom=4

On Android 7.1.2 
Try to pan with touch screen. Page just reloads

**Comment by oterral** [comment]
There is no touch events defined.
