### ISSUE TITLE
Feedback Tool: new design

### ISSUE THREAD

**Issue by p1d1d1** [geoadmin/mf-geoadmin3#3766]
Please implement as in spec.
To be on line on 26.04.2017.
Thanks

Feedback Tool
 
![image](https://cloud.githubusercontent.com/assets/4577727/25007343/7076b676-2060-11e7-9b6f-0cd00455e28a.png)

1.	Melden Sie uns in diesem Feld Änderungen in der Karte, Verbesserungen der Daten oder Fragen zu dieser Website (erforderlich):
2.	Markieren Sie den entsprechenden Ort in der Karte:
3.	Ihre E-Mail Adresse:
Mit dem Absenden Ihre Meldung erklären Sie sich damit einverstanden, dass die von Ihnen gemachten Angaben von einer Amtsstelle des Bundes in anonymisierter Form gespeichert, verarbeitet und eventuell publiziert werden können. Nutzungsbedingungen 

FR
1.	Faites-nous part de modifications de la carte, d’amélioration des données ou posez des questions sur ce site dans ce champ (obligatoire) :
2.	Situez le lieu concerné dans la carte :
3.	Votre email:
En envoyant votre message, vous acceptez que les informations fournies soient stockée, traitée et éventuellement publiées sous une forme anonyme par un organisme officiel de la Confédération. Conditions d’utilisation

IT
1.	Ci comunichi in questo campo cambiamenti nella carta, miglioramenti dei dati o domande su questo sito (obbligatorio):
2.	Indichi il luogo corrispondente nella carta:
3.	La sua email:
Inviando un messaggio, l’utente accetta che le informazioni fornite siano salvate, trattate ed eventualmente pubblicate in forma anonima da parte di un organismo ufficiale della Confederazione. Condizioni di utilizzo

EN
1.	Report in this field changes in the map, improvements to the data or questions about this website (required):
2.	Indicate the appropriate location on the map:
3.	Your Email:
By submitting your message, you agree that the information you provided may be stored, processed and possibly published in an anonymous form by an official office of the Confederation. Terms of use

RM
1.	?
2.	?
3.	?
?. Cundiziun d'utilisaziun

Confirmation windows
 
![image](https://cloud.githubusercontent.com/assets/4577727/25007352/7ef872a2-2060-11e7-9f24-c33b9e599d67.png)

DE: Danke für Ihre Nachricht. Sie wurde erfolgreich versendet.
FR: Votre message a été envoyé avec succès. Merci.
IT: Il suo messaggio è stato inviato con successo. Grazie.
RM: Rapport trasmess cun success. Grazia.
EN: Your message was successfully sent. Thank you.

**Comment by davidoesch** [comment]
can you link to the spec?

**Comment by p1d1d1** [comment]
see my email on 11/04/2017 16:31

**Comment by davidoesch** [comment]
added it above in the ticket description: rm will  be done as soon as msgids are ready in translation table

**Comment by p1d1d1** [comment]
always something to learn!

**Comment by p1d1d1** [comment]
@gjn can you confirm planned deploy?

**Comment by oterral** [comment]
What is the link for the ' terms of use'  ?

**Comment by oterral** [comment]
https://www.geo.admin.ch/fr/about-swiss-geoportal/impressum.html#drawing ?

**Comment by oterral** [comment]
@davidoesch translations are at the end of the google doc

**Comment by p1d1d1** [comment]
Asked @pauloamado to create: https://www.geo.admin.ch/fr/about-swiss-geoportal/impressum.html#feedback

**Comment by davidoesch** [comment]
IMHO we don't need the link for terms of use . According to the mock-up all is now placed into the widget . Pls double check p1d1d1. Either we make a new entry for feedback in the cms and put the last part there and add a link to it or we have it all in the widget. Let's put into the cms- since on small screen/mobile, you will be hardly be able to add a comment.

**Comment by p1d1d1** [comment]
"Terms of use" contain more text and we cannot put all this text in the feedback tool:

Problem melden (https://www.geo.admin.ch/de/ueber-geo-admin/impressum.html#feedback) 
Nutzungsbedingungen
	Mit dem Absenden Ihre Meldung erklären Sie sich damit einverstanden, dass die von Ihnen gemachten Angaben von einer Amtsstelle des Bundes in anonymisierter Form gespeichert, verarbeitet und eventuell publiziert werden können.
	Der Nutzer verpflichtet sich, die zur Verfügung stehende Funktion nicht missbräuchlich zu verwenden und rechtswidrige Handlungen zu unterlassen. Datenschutz- und urheberrechtliche Vorschriften sind zu beachten; ein Missbrauch wird geahndet und kann strafrechtlich verfolgt werden. Insbesondere darf Schutz von Privatsphäre / persönlichen Daten nicht verletzt und Urheberrechte nicht verletzt werden. Das Bundesamt für Landestopografie swisstopo behält sich vor, solche Daten jederzeit ohne Warnung zu löschen.
	Haftungsansprüche gegen die Bundesbehörden werden - soweit gesetzlich zulässig – ausgeschlossen. Diese Funktion wird gemäss https://www.admin.ch/gov/de/start/rechtliches.html angeboten.

This text is already in CMS (unpublished). With Topo we agreed to have the first point also in the feedback tool. I would personally prefer to only leave the link to the "Terms of use". 
I would check first in mobile: if it gets too awful, then we only leave the link?

**Comment by davidoesch** [comment]
We only make a link.... It's from a usability point of view more clear to have the whole disclaimer at one place. Not a 1/8 here and 7/8 there. So we add just the link. Happy to discuss with topo. But I'm quite convinced that legal will back up my point of view 100%
