### ISSUE TITLE
Import: Add promise support in ngeo

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/mf-geoadmin3#3768]
https://github.com/geoadmin/mf-geoadmin3/pull/3596

We need it if we want to support CORS.

**Comment by oterral** [comment]
Waiting for comment https://github.com/camptocamp/ngeo/issues/2517

**Comment by oterral** [comment]
PR https://github.com/camptocamp/ngeo/pull/2532

**Comment by loicgasser** [comment]
/home/travis/build/camptocamp/ngeo/src/modules/import/importonline.js
  131:13  error  'transformUrl' is never reassigned. Use 'const' instead  prefer-const

I guess use const instead of let.

**Comment by loicgasser** [comment]
cool though thank you

**Comment by oterral** [comment]
yes I fix

**Comment by oterral** [comment]
Fixed by #3731
