### ISSUE TITLE
[import] a second local kml cannot be loaded with FF

### ISSUE THREAD

**Issue by mariokeusen** [geoadmin/mf-geoadmin3#3777]
UC: open app in FF 52, open the import tool, load a KML from a local drive, add it to the map, load a second KML from a local drive, add it to the map
Result: the second KML cannot be loaded. Seems like the function goes into kind of a timeout
![image](https://cloud.githubusercontent.com/assets/4577749/25170534/334d4294-24eb-11e7-9ee4-6c8ed86c78ae.png)
Expected: several KML can be added to the map. Works well with Chrome and IE btw.

Thanks for fixing

**Comment by Jenselme** [comment]
From what I see in the console it fails [here](https://github.com/camptocamp/ngeo/blob/master/src/modules/import/file.js#L39) on `fileReader.abort();`. This may come from the fact that on FF you cannot call abord on a file reader if it has already loaded the file. See [my patch](https://github.com/ioda-net/geo-front3/commit/a86fadb1e0c3c18a4d2f4bcd2b72a6d2b7aeb4ae#diff-6a0c7f357d5d2d297a5552e02d101bcc) on the older KML import component.

PS: it works correctly on FF nightly. So even if ngeo is not patched, it should work correctly soon on FF.

**Comment by oterral** [comment]
PR ready in https://github.com/camptocamp/ngeo/pull/2546

**Comment by oterral** [comment]
fixed by update of ngeo in #3731
