### ISSUE TITLE
CSS error in seamonkey browser

### ISSUE THREAD

**Issue by gjn** [geoadmin/mf-geoadmin3#3782]
Sehr geehrte Dame, sehr geehrter Herr,

Bei der Ansicht Ihrer Karte in Firefox/Seamokey (trunk) läuft die Kartenapplikation leider nicht fehlerfrei, es treten Fehler wie z.B. 

Timestamp: 1/1/70, 12:22:03 AM
Warning: Expected color but found ‘solid\9 ’.  Expected end of value but found ‘solid\9 ’.  Error in parsing value for ‘border-bottom’.  Declaration dropped.
Source File: https://map.geo.admin.ch/master/d3d47d8/1704121010/1704121010/style/app.css
Line: 9, Column: 42532
Source Code:
auf. Dadurch wird die Karte nicht mehr dargestellt. Meine Browserversion ist Seamonkey-2.52a1.en-US.linux-i686-20170404.

Bitte schreiben Sie mir einfach, falls Sie mehr Information oder jemand zum Testen benötigen.

User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0

**Comment by oterral** [comment]
It's just a warning, it can't be the cause of not seeing the map.

**Comment by oterral** [comment]
works on ff52 and seamonkey 2.46 . The version 2.52 of seamonkey is in alpha and we don't support this browser.

**Comment by gjn** [comment]
Thanks for the quick reply!
