### ISSUE TITLE
Missing translations after a successful parse

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/mf-geoadmin3#3783]
![image](https://cloud.githubusercontent.com/assets/3306154/25391787/595710dc-29d7-11e7-8e0f-8b5e2be01e00.png)

Step to reproduce.

1. Open import tool
2. Import a kml (https://www.procrastinatio.org/kml/simple_000005.kml for instance)
3. Don't touch anything

Result untranslated msg is displayed.

I think it's only the translation that is missing because it is in the empty.json but not anywhere else.

**Comment by oterral** [comment]
Translations are there they use the ngeo identifier but there is a ngeo issue again they manage text identifiers differently in local import and online import.

**Comment by loicgasser** [comment]
so translations are in ngeo?
```
$ git grep parse_succeeded
src/js/ImportController.js:            message: 'parse_succeeded'
src/locales/empty.json:  "parse_succeeded": "Parsing succeeded",
```

**Comment by oterral** [comment]
Translations are in geoadmin, search for "Parsing succeeded" .
So currently we can't have translations for "parse_succeeded" and "Parsing succeeded" at the same time.

importlocal uses "Parsing succeeded"
importonline uses "parse_succeeded"

**Comment by oterral** [comment]
https://github.com/camptocamp/ngeo/pull/2555

**Comment by loicgasser** [comment]
ahh, ok

**Comment by oterral** [comment]
Fixed
