### ISSUE TITLE
WMS Services geodienste.ch

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3784]
www.geodienste.ch has now a coouple of aggregated WMS sources ready
can they be added to the pulldown menu in "import"

- Amtliche Vermessung (MOpublic) : https://geodienste.ch/db/av/deu?SERVICE=WMS&REQUEST=GetCapabilities

-Amtliche Vermessung (MOpublic, Jahresstand) https://geodienste.ch/db/av_jahresstand/deu?SERVICE=WMS&REQUEST=GetCapabilities

**Comment by procrastinatio** [comment]
Nota 'deu' and 'fra' OK, no 'eng', 'ita' and 'roh'

**Comment by oterral** [comment]
Workaround: Try to import : `https://geodienste.ch/db/av/deu?SERVICE=WMS` instead of `https://geodienste.ch/db/av/deu`

**Comment by davidoesch** [comment]
+1
