### ISSUE TITLE
Slider/compare : not in pdf

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3797]
Open application
Activate Zeitreihe
Activate compare mode
Print
Result: PDF contains only Zeitreihe
Expected result PDF contains red slider with Zeitreise ob the left and BG on the right

Might related to #3794

**Comment by procrastinatio** [comment]
As there is no easy way in mapfish print to print half a layer, and there is nothing in the print proxy, I suspect this was never implemented.

**Comment by davidoesch** [comment]
Hmmm I'm quite sure this was before... But  I close it in this case.

**Comment by gjn** [comment]
Not sure we ever had this. At least in code, there's nothing that would indicate that we have.
