### ISSUE TITLE
Enforce pop up "add to Homescreen" on mobile

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3798]
iOS and Android all version
all browser

Situation:
mots people don't know that you can use  map.geoa.dmin.ch like an app and start it from home screen. we made already several improvment liks https://github.com/geoadmin/mf-geoadmin3/issues/3759

Task:
when entering "map.geo.admin.ch" on cold start of mobile browser, website appears but no active hint is given that you can save a link to homescreen. this was the case years ago for map mobile

Action:

enforce on each call (except when starting from homescreen) this hint that you can save a link to homescreen

![image](https://cloud.githubusercontent.com/assets/4577727/25738428/68fb5c34-317d-11e7-9402-4e14ee8c1a48.png)

Result:

ppl use it as an app- and more often on mobile

**Comment by oterral** [comment]
-1 we show it the first time the user uses the app  and it's enough. Nobody wants to be persecuted by this popup.

**Comment by davidoesch** [comment]
Agree... Nagware sucks. But if I clear cache and cold start I don't have it. How do we ensure a first time visit? With appcache?

Or put it in another way: how to friendly reminder once in a while that a link to Homescreen can be made (I know the easiest way would be ... Provide an app)

**Comment by oterral** [comment]
Hmm you should have it after clean chache. It is stored in the browser localStorage
