### ISSUE TITLE
Rotate mobile according to compass

### ISSUE THREAD

**Issue by cedricmoullet** [geoadmin/mf-geoadmin3#380]
very NTH

**Comment by kandre** [comment]
@cedricmoullet @davidoesch I am on it. I need some precisions about the spec, as it's been made before the creation of the compass (rotation reset) button. I would like to know:

On the second click, on the geoloc btn, the map is rotated according to the current heading, hence the compass button as well.
1. Should we be able to reset the north by cliking on it?
2. If yes, what would be the state of the geolocation button? (I would suggest: 'show heading direction of device' after 1st click on geoloc btn).

**Comment by davidoesch** [comment]
Proposal: follow the google maps app or search,ch app approach: we combine geolocation icon and map rotation icon: as soon as the map is rotated the geolocation icon turn into the map rotation icon . 

-> we save space and reduce an icon position

1. Should we be able to reset the north by cliking on it ( I suggest yes)?
-> yes, as in gmaps app: icon : switch from map roatation to geolocation icon
2. If yes, what would be the state of the geolocation button?
icon : switch from map roatation to geolocation icon
3. Still on the second click state, should we be able to rotate the map with fingers ( I suggest yes)? 
yes
4. If yes, does the state of the geolocation button should be changed? 
see intro

in one line: as in google maps app

**Comment by kandre** [comment]
Ok thank you for these clarifications. By the way, I have you already defined an orientation marker? I guess it would be a small arrow, like in google maps app?

**Comment by davidoesch** [comment]
the orientation marker : a triangle on the postisoin marker as in gmap app

**Comment by gjn** [comment]
Will be live on next deploy, via #2092.
