### ISSUE TITLE
WMS-Import not using OnlineResource from Capability description

### ISSUE THREAD

**Issue by p1d1d1** [geoadmin/mf-geoadmin3#3802]
From Helpdesk:

> It seems there is a bug in handling external web services.
If I try to add our Sentinel Hub service (sentinel-hub.com) and I use the following URL:
http://services.sentinel-hub.com/v1/wms/570197e0-4b40-4783-b261-30a054d715bb

> service correctly fetches the meta-data about available layers. However, when I try to visualize this, it does not work. Analyzing the problem I noticed that the following requests are called:
http://www.sentinel-hub.com/?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=TRUE_COLOR&CRS=EPSG%3A4326&STYLES=&WIDTH=1893&HEIGHT=656&BBOX=46.029826979622776%2C6.264159980147314%2C47.49969758692493%2C10.509460243990091

> instead of
http://services.sentinel-hub.com/v1/wms/570197e0-4b40-4783-b261-30a054d715bb?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=TRUE_COLOR&CRS=EPSG%3A4326&STYLES=&WIDTH=1893&HEIGHT=656&BBOX=46.029826979622776%2C6.264159980147314%2C47.49969758692493%2C10.509460243990091

> I believe the service wrongly parses GetCapabilities file and takes "OnlineResource" value from "Service" description, rather than from "Capability" tag..

**Comment by oterral** [comment]
To fix in ngeo https://github.com/camptocamp/ngeo/blob/master/src/modules/import/wmsgetcap.js#L70

**Comment by p1d1d1** [comment]
Will you guys open a ticket there?

**Comment by oterral** [comment]
I will fix.

**Comment by gjn** [comment]
See alos https://github.com/geoadmin/mf-geoadmin3/issues/3805 for other failing WMS.

**Comment by oterral** [comment]
Waiting for https://github.com/camptocamp/ngeo/pull/2629/files

**Comment by ponceta** [comment]
Following this.

http://www.sigip.ch/main/wsgi/mapserv_proxy
