### ISSUE TITLE
Qgis -wms not working

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3805]
There seems to be an isdue for all qgis served wms in our list

Question:qgis issue or ol3 issue ?
Here the comments from client
- Es betrifft "nur" QGIS-Server WMS-Layer. MapServer-WMS-Layer funktionieren noch.
- WMS des Kanton GL funktioniert auch nicht mehr. Setzt auch QGIS-Server ein.
- Irgendwie wird der Servername der GetMap-Url verschluckt, dh. map.geo.admin.ch requestet nun nicht geoweb.so.ch/"wms...", sondern map.geo.admin.ch/"wms..."

Funktioniert: https://geoweb.so.ch/wms/sogis_bpav.wms?SERVICE=WMS&REQUEST=GetCapabilities
Funktioniert nicht: https://geoweb.so.ch/wms/isboden?SERVICE=WMS&REQUEST=GetCapabilities

**Comment by p1d1d1** [comment]
IMHO this is linked to this: https://github.com/geoadmin/mf-geoadmin3/issues/3802

**Comment by gjn** [comment]
Yes, this is the same issue.
