### ISSUE TITLE
Measure labels are not printed

### ISSUE THREAD

**Issue by procrastinatio** [geoadmin/mf-geoadmin3#3808]
1. Open map.geo.admin.ch
2. Dessiner > Mesurer 
3. Measure something, either radius, line or polygon
4. Print what you just draw

The labels background [1] are not printed.

Related to https://github.com/geoadmin/mf-geoadmin3/issues/3794 and https://github.com/geoadmin/service-print/issues/29

[1] For instance https://map.geo.admin.ch/master/10a257a/1705101128/1705101128/img/bubble.png

**Comment by oterral** [comment]
and https://github.com/geoadmin/service-print/issues/30
