### ISSUE TITLE
KML External icons Print

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3812]
Open
Drittanbieter-POI https://s.geo.admin.ch/735b164830 ( mapplus)

-> Print PDF:
Result: Icons not shown

**Comment by oterral** [comment]
THe KML doesn't exist anymore.

**Comment by oterral** [comment]
New test link https://s.geo.admin.ch/735f78e3ad

**Comment by oterral** [comment]
Fixed by https://github.com/geoadmin/mf-geoadmin3/pull/3816
