### ISSUE TITLE
Print of measure doesn't work

### ISSUE THREAD

**Issue by cedricmoullet** [geoadmin/mf-geoadmin3#3814]
https://s.geo.admin.ch/735efa5b76

-> no pdf can be printed

**Comment by loicgasser** [comment]
![image](https://cloud.githubusercontent.com/assets/3306154/26343262/83ea31ec-3f9b-11e7-9f91-e34c37e20c7e.png)

I tried with chrome but this is was slow (you do have to be patient). (what browser did you test?)

**Comment by oterral** [comment]
Always the print icon issue when icons comes from cloudfront.

https://github.com/geoadmin/mf-geoadmin3/pull/3813 fixes it.

**Comment by procrastinatio** [comment]
See 
https://jira.camptocamp.com/servicedesk/customer/portal/6/GEO-225
https://github.com/geoadmin/service-print/issues/29
https://jira.swisstopo.ch/browse/BGDIINF_SB-458

**Comment by oterral** [comment]
Fixed in dev

**Comment by procrastinatio** [comment]
See https://github.com/geoadmin/service-print/pull/31
