### ISSUE TITLE
[KML import] KML file with symbol icon (png) from an external web source can't be displayed

### ISSUE THREAD

**Issue by mariokeusen** [geoadmin/mf-geoadmin3#3818]
![kml_punkt_png_fehler](https://cloud.githubusercontent.com/assets/4577749/26387703/ec893d1a-404f-11e7-9873-ad9c195d1ba7.png)

Is this a known issue? Bound to the recent rebuild of the import tools?

**Comment by oterral** [comment]
Tes link please.
Are you sure the images exists?

**Comment by mariokeusen** [comment]
Just emailed you the kml with all the image sources.

**Comment by oterral** [comment]
Seems to be bug a proxy bug.
https://github.com/geoadmin/service-proxy/issues/34

**Comment by gjn** [comment]
It looks like the resource is blocked sometimes when accessed via a script. See referenced service-proxy entry.

Can we ask the cleint about this?

**Comment by davidoesch** [comment]
related to ? https://github.com/geoadmin/mf-geoadmin3/issues/3812 and/or #3436

**Comment by oterral** [comment]
no it seems the resource is blocked autiomactically by their server

**Comment by davidoesch** [comment]
Info for the customer

> [1495611905154] [INFO] 2017-05-24T07:45:05.154Z e66c582a-4054-11e7-8056-4d63c21ab06f Got 403 response from https://geoshare.impulsthun.ch/kml/oet/Ausfuehrung_Gesuch_bewilligt.png
[1495611905155] [INFO] 2017-05-24T07:45:05.155Z e66c582a-4054-11e7-8056-4d63c21ab06f 54.194.151.117 - - [24/May/2017:07:45:05 +0000] "GET /https/geoshare.impulsthun.ch/kml/oet/Ausfuehrung_Gesuch_bewilligt.png HTTP/1.1" 403 609 "https://map.geo.admin.ch" "curl/7.38.0" 0/598.153 
So it's the remote server that answers with 403..
They must have some protection mechanism from python scripts.
>

**Comment by mariokeusen** [comment]
Ok thanks. Forwarded that to the customer.

**Comment by mariokeusen** [comment]
Problem solved on external server side
