### ISSUE TITLE
Mobile enforcement on Desktop

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3820]
lately  we get more often reports that desktop is forwarded to mobile version
". Mir ist dann aufgefallen, dass die Seite mich immer automatisch auf map.geo.admin.ch/mobile.html weiterleitet (Firefox und Internet Explorer) und nicht auf map.geo.admin.ch/index.html bleibt."
seems to be related to  high res retina screens

-> can be reproduced on our win7 buraut small laptops withe IE

proposal to tweak detection (if it makes sense)

[ ] FF and IE agent are always desktop
[ ] allow desktop mode for smaller screens
[ ] other ides?

**Comment by oterral** [comment]
We could removed  the mobile file and only use responsive stuff.

**Comment by gjn** [comment]
Yes, I would prefer this solution as well. But this is more mid-term goal.

Right now, I think we should update our device detection mechanisms. I consider this high priority (we already discussed it last week, I think).

**Comment by davidoesch** [comment]
Can you test this with browser shots? So we can estimate the impact?

**Comment by davidoesch** [comment]
while add it: enable 
- [ ] print
Expert functions
- [ ] draw/measure
- [ ] import

in mobile as well. they work on mobile (at least in landscape mode)
->  most user will be happy

**Comment by gjn** [comment]
We should have a fully responsive page. Meaning, no more redirection and we decide
a) what to show
b) how to show it

based on
I) screen size
II) browser capabilities

@oterral Thoughts?

**Comment by oterral** [comment]
totally agree.

Only problem i see it's AppCache.

**Comment by gjn** [comment]
1) First step is to update the browsersniffer component to contain latest browsers/detections

2) To have real responsive page. The only difference between mobile/desktop is
I) offline button
II) appcache

All the rest to be responsive.
