### ISSUE TITLE
Wmts Zurich not working

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3826]
https://s.geo.admin.ch/738a5cdbc0
Wmts can be added but data not shown....
Maybe related to #3825

**Comment by oterral** [comment]
Can you give the WMTS url please

**Comment by davidoesch** [comment]
Should be in the short URL above (generated on iPhone 7) looks like this another

http://www.gis.stadt-zuerich.ch/wmts/wmts-zh-stzh-ogd.xml

**Comment by oterral** [comment]
It doesn't work on arc map too

**Comment by davidoesch** [comment]
This one neither http://www.gis.stadt-zuerich.ch/maps/rest/services/tiled95/Uebersichtsplan1978/MapServer/WMTS/1.0.0/WMTSCapabilities.xml it gives an ok for upload. I assume it is due to lv95

Would be nice if the users get an error feedback when loading

**Comment by oterral** [comment]
Have you try on arcmap ? for me nothing is displayed.

We could generalize XML validation with the KML validation project but it's not for this year.

**Comment by procrastinatio** [comment]
Not conform...
http://api3.geo.admin.ch/owschecker/form?base_url=http://www.gis.stadt-zuerich.ch/wmts/wmts-zh-stzh-ogd.xml&service=WMTS

**Comment by davidoesch** [comment]
The ech0056 checker will be decommissioned by end of June (it checks against an old 0056 version) 
And not be replaced due to budget cuts/priority. It will be replaced by ogc testsuite

**Comment by procrastinatio** [comment]
The error is:
`TypeError: Cannot read property 'ProviderName' of undefined`

**Comment by procrastinatio** [comment]
If you update the GetCapabilities... it works...

https://s.geo.admin.ch/738e676ddf

**Comment by procrastinatio** [comment]
First url http**s**://www.gis.stadt-zuerich.ch/wmts/wmts-zh-stzh-ogd.xml does't work in either ESRI ArcMap not QGis. All  generated tiles addresses are returning an HTTP 500 error.

After debugging client's KML, we are debugging client's WMTS configuration?

**Comment by davidoesch** [comment]
correct--- welcome to the world of "interoperability"

**Comment by oterral** [comment]
Tell the owner that his WMS GetCapabilities is not working.

**Comment by davidoesch** [comment]
Well WMTS Get Cap return sth https://www.gis.stadt-zuerich.ch/wmts/wmts-zh-stzh-ogd.xml 

What exactyl has to be fixed by stadt-zuerich.ch ? ( their dev will participate in this discussion)

**Comment by oterral** [comment]
Currently we try to requet this url :

http://www.gis.stadt-zuerich.ch/maps/rest/services/tiled/Luftbild1976/MapServer/WMTS/tile/1.0.0/tiled_Luftbild1976/default/default028mm/0/902/888.png

If they can say what's wrong in it, it could be a first step.

**Comment by geoang** [comment]
it has to be "tiled95" instead of "tiled".

http://www.gis.stadt-zuerich.ch/maps/rest/services/tiled95/Luftbild1976/MapServer/WMTS/tile/1.0.0/tiled95_Luftbild1976/default/default028mm/0/881/867.png

**Comment by oterral** [comment]
Now it works. Thx for the fix @geoang.

[test](https://mf-geoadmin3.dev.bgdi.ch/?lang=fr&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&X=248152.17&Y=681358.81&dev3d=true&zoom=5&debug&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bav.haltestellen-oev,ch.swisstopo.swisstlm3d-wanderwege,WMTS%7C%7CLuftbild_1976%7C%7Chttp:%2F%2Fwww.gis.stadt-zuerich.ch%2Fwmts%2Fwmts-zh-stzh-ogd.xml&layers_visibility=false,false,false,false,true,true&layers_timestamp=18641231,,,,,)

**Comment by davidoesch** [comment]
Hmm not in 3D https://mf-chsdi3.dev.bgdi.ch/shorten/73c817aeec

**Comment by p1d1d1** [comment]
According to the OGC Team Engine the service is not valid (with URL http://www.gis.stadt-zuerich.ch/wmts/wmts-zh-stzh-ogd.xml)

![image](https://user-images.githubusercontent.com/1533649/27040605-cb1d1bc8-4f91-11e7-97b8-d810341a812a.png)

**Comment by procrastinatio** [comment]
**2D** is EPSG:21781 or EPSG:4326 client reprojected, **3D** is EPSG:4326. So switching to 3D, we have to reparse the WMTS service to find a suitable projection.

**Comment by davidoesch** [comment]
..or WMTS provider has to support EPSG:4326.
A warning window: source does not support 4326?

**Comment by procrastinatio** [comment]
On the other hand, it works fine fine with WMTS EPSG:4326 and 3D (https://mf-chsdi3.int.bgdi.ch/shorten/73ccd6b2af)(Dufour is WMTS Mapproxy). But it is the easiest way to kill your server :grin:
