### ISSUE TITLE
WMTS layers aren't displayed in 3D

### ISSUE THREAD

**Issue by t0b3** [geoadmin/mf-geoadmin3#3830]
https://s.geo.admin.ch/738d9da4c1

**Comment by oterral** [comment]
The GetCapabilities contains 2 TileMatrixSet (g and WGS84), we should be capable to use the good MatrixSet for the 3d (WGS84).

**Comment by procrastinatio** [comment]
But not all WMTS service are providing `EPSG:4326` based `TileMatrixSet`
