### ISSUE TITLE
add time selection for WM[T]S sources providing time dimension

### ISSUE THREAD

**Issue by t0b3** [geoadmin/mf-geoadmin3#3831]
There are WM[T]S sources exposing time dimension as an option.
i.e. [WMS example](https://services.sentinel-hub.com/v1/wms/ac1f375f-6ce6-4cbc-87dc-7a4f1b193d61?SERVICE=WMS&REQUEST=GetCapabilities)

```<Dimension current="1" default="2017-05-30" name="TIME" unitSymbol="" units="ISO8601">2013-01-01/2017-05-30/P1D</Dimension>```

For such sources a time selector could be provided to the user. Maybe similar to the time slider already available, however concerns YYYYMMDD not only YYYY.

**Comment by oterral** [comment]
Yes we introduce the WMTS import yesterday, it should work for WMTS now.

We should do it also for WMS.

**Comment by oterral** [comment]
I didn't see it was a timerange , we currently don't manage it.

**Comment by boecklic** [comment]
@ltclm: closed in agreement with @davidoesch
