### ISSUE TITLE
Offline: new data available warning window

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3832]
iOS/Android mobile

Reproduce 
open 
https://map.geo.admin.ch/?lang=de&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bav.haltestellen-oev,ch.swisstopo.swisstlm3d-wanderwege&layers_visibility=false,false,true,true&layers_timestamp=18641231,,,&X=105770.00&Y=621760.00&zoom=5

-save offline
-come back after 24h ( even if there was not a deploy meanwhile)
- start offline

Result:
Warning new data is available (even if there was no update of PK , hiking or pub stops)

Expected result:
Only after a deploy of a dataset this warning appears- if there are really new data

-> Customer feedback ID : 2017053117423735

**Comment by oterral** [comment]
There was an update of ch.bav.haltestellen-oev so it's good.

**Comment by davidoesch** [comment]
I know but I observed the same/ reproduced it when there was *no* update  for any datasets in the URL

**Comment by oterral** [comment]
The msg appears only if there is a difference between the timestamp saved and the last timestamp in the layer 's config. So there was an update.

I save layers on the iphone , If tomorrow I have no message I close it.

**Comment by davidoesch** [comment]
+1

**Comment by oterral** [comment]
No warning
