### ISSUE TITLE
Improve the detection of the url (WMS/WMTS/KML)

### ISSUE THREAD

**Issue by oterral** [geoadmin/mf-geoadmin3#3833]
Impossible to load WMS url like this:

 https://geodienste.ch/db/av/deu
 http://www.glamos.ch/qgis/sgi

**Comment by oterral** [comment]
Workaround use:

https://geodienste.ch/db/av/deu?SERVICE=wms
http://www.glamos.ch/qgis/sgi?SERVICE=wms

**Comment by procrastinatio** [comment]
This is less trivial than it looks like:
* Many services, especially from canton, do not support HEAD
* WMS and WMTS are both `application\xml`
* Some have a wrong `mime-type`

**Comment by rebert** [comment]
Replace head with GET, the browser will send an OPTIONS request when the host is not the same to control cors.

Programatically detect what we are importing. If not possible to be discussed

**Comment by oterral** [comment]
Fixed with https://github.com/geoadmin/mf-geoadmin3/pull/3845
