### ISSUE TITLE
WMTS arcgisonline support

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3836]
There is vast amount of free WMTS based data under https://services.arcgisonline.com/arcgis/rest/ 

eg https://services.arcgisonline.com/arcgis/rest/services/World_Physical_Map/MapServer/WMTS/1.0.0/WMTSCapabilities.xml

but loading them into map.geo.admin.ch via import

results in

Failed to load resource: the server responded with a status of 405 (Method Not Allowed)

?

**Comment by procrastinatio** [comment]
Yes before deciding how to get the document via the proxy or not, we probe the service with a `HEAD` request. Unfortunately, many serveur do not allow `HEAD` request (which is totally stupid)

```
$ curl -v -X HEAD   https://services.arcgisonline.com/arcgis/rest/services/World_Physical_Map/MapServer/WMTS/1.0.0/WMTSCapabilities.xml

< HTTP/1.1 405 Method Not Allowed
< Server: Apache-Coyote/1.1
< Content-Type: text/html;charset=utf-8
< Access-Control-Allow-Origin: *
```

**Comment by procrastinatio** [comment]
Aarg...

```
xmllint --schema http://schemas.opengis.net/wmts/1.0/wmtsGetCapabilities_response.xsd WMTSCapabilities.xml  --noout

WMTSCapabilities.xml validates
```
In OWS and WMTS 1.0, `ServiceProvider`and hence `ProviderName` are not compulsory. So OL3/ngeo  should not break on this.

**Comment by davidoesch** [comment]
omg    standards are theory

**Comment by procrastinatio** [comment]
Sometime, it is better not to show third party data, especially when more accurate than yours :innocent:  https://mf-chsdi3.dev.bgdi.ch/shorten/73a3f0c9f2

**Comment by oterral** [comment]
Fixed
