### ISSUE TITLE
Drawing artefacts in 3D on ios Chrome

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3837]
iOS latets iphone7 chrome or safari
 open
https://map.geo.admin.ch/index.html?topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bav.haltestellen-oev,ch.swisstopo.swisstlm3d-wanderwege,KML%7C%7Chttps:%2F%2Fpublic.geo.admin.ch%2FjAj3UiTrT_WMgr790Y7wdw&layers_visibility=false,false,false,false,true&layers_timestamp=18641231,,,,&lang=de&mobile=false&lon=8.27264&lat=46.84966&elevation=2014&heading=142.635&pitch=-22.830

Result: red line has a cut, can not reproduced on desktop

![image](https://cloud.githubusercontent.com/assets/4577727/26822376/19d1ca6c-4aaa-11e7-91e6-c6628d3eca9a.png)

**Comment by oterral** [comment]
Hardware incompatibilits issue:

http://webglreport.com 

If you don't see the EXT_frag_depth extension in the list, this kind of thing can happen
