### ISSUE TITLE
[app translations] update from spreadsheet

### ISSUE THREAD

**Issue by mariokeusen** [geoadmin/mf-geoadmin3#3839]
Situation: new, corrected and updated application translations are available in the translation spreadsheet (trigger is the translation project mainly for RM and EN, but there were lots of improvements esp. also in DE)
Goal: new translations are available in the application
Workaround: please import all green marked (means there have been changes) cells

**Comment by mariokeusen** [comment]
Please also update the topic translations from BOD with the same deploy. Few changes also from there, as well as RM/EN topic titles for topics geodesy and emapis.

**Comment by rebert** [comment]
Mario topic translations are in geoadmin as well so the spreadsheet

**Comment by procrastinatio** [comment]
?????

**Comment by oterral** [comment]
Translations updated with https://github.com/geoadmin/mf-geoadmin3/pull/3840
