### ISSUE TITLE
WMS-C Tiles nor loaded completely

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3841]
https://map.geo.admin.ch/?X=235880.25&Y=727769.24&zoom=8&lang=de&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&catalogNodes=532,687,720&layers=ch.swisstopo.swissboundaries3d-kanton-flaeche.fill,ch.bafu.wasser-entnahme,ch.bafu.wasser-rueckgabe,ch.bafu.wasser-leitungen,ch.bfe.statistik-wasserkraftanlagen&layers_visibility=false,true,true,true,true.

BV Net  ok
WLAN not ok
"Darstellungsprobleme: Überlagerte Symbole bleiben beim reinzoomen hängen, vgl. Bild. Auch mehrmaliges rein-/rauszoomen bringt nichts. IE und Firefox"

"Problem 2017060518522000 existiert offenbar gerade innerhalb der BV nicht, der IFrame wird hier korrekt dargestellt. Ausserhalb sehe ich nur das weisse Raster, egal ob über WLAN oder VDSL. Daher dürften Sie hier den BIT-Proxy nicht verantwortlich machen können. Es ist doch schon die Meinung, dass der IFrame auf einer beliebigen Webseite eingebunden werden kann/darf? Zumindest sagt dies die Hilfe.

Problem 2017060116313429 könnten Sie an meinem Arbeitsplatz praktisch beliebig nachvollziehen, mal mehr, mal weniger:
![image](https://user-images.githubusercontent.com/4577727/26915042-9e488d1e-4c24-11e7-9362-76bd733005f5.png)

 

Da nützt alles Browsecachelöschen nichts, und bezüglich Browser sind wir bekanntlich ein kleinwenig eingeschränkt.
"
Customer feedback ID : 2017060116313429
Customer feedback ID : 2017060518522000

**Comment by cedricmoullet** [comment]
I can observe the same on IE:
![image](https://user-images.githubusercontent.com/319676/26915152-31ef7172-4c25-11e7-9555-6519434c92a3.png)

**Comment by cedricmoullet** [comment]
![image](https://user-images.githubusercontent.com/319676/26915181-51ae929a-4c25-11e7-93d8-3a93c5316a3e.png)

**Comment by cedricmoullet** [comment]
In order to reproduce, it's needed to move, zoom-in, zoom-out very fastly. 
I can remember that we got already some equivalent problems. It was due to some tile refresh issues in OL. Did we updated OL recently ?

**Comment by oterral** [comment]
Fixed by #3829 

[Test](https://mf-geoadmin3.int.bgdi.ch/teo_up/index.html?X=221174.80&Y=724938.53&zoom=8&lang=de&topic=ech&bgLayer=voidLayer&layers=ch.swisstopo.swissboundaries3d-kanton-flaeche.fill,ch.bafu.wasser-entnahme,ch.bafu.wasser-rueckgabe,ch.bafu.wasser-leitungen,ch.bfe.statistik-wasserkraftanlagen&layers_visibility=false,true,true,true,true&catalogNodes=532,687,720)

**Comment by cedricmoullet** [comment]
it seems to work by me
