### ISSUE TITLE
KML Print rotated icons 

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3842]
Icons with annotation can not be printed

reproduce
https://map.geo.admin.ch/?lang=fr&topic=ech&bgLayer=ch.swisstopo.pixelkarte-grau&X=166193.97&Y=614674.35&zoom=2&layers=KML%7C%7Chttps:%2F%2Fwww.procrastinatio.org%2Fkml%2Ficon-rotated.kml

rotate:
print pdf

result: not all icons are printed
expected result: all icons with annotation are printed

work arround:

use icons only: no text annotation

(eg: https://www.mapplus.ch/?lang=en&basemap=osm&blop=1&x=597622.4&y=196203.2&zl=4&hl=0&layers=camping -> open in map.geo.admin.ch via  Conf Helevetica icon in the right pannel, rotate and print : all icons are printed

**Comment by oterral** [comment]
The icon style is ignored if a label style is specified.

**Comment by procrastinatio** [comment]
Rotation angle should be **degree** (0° N, 90° E,) , not **degree**

This specs files print fine: https://raw.githubusercontent.com/procrastinatio/mapfish-print-examples/master/specs/label-rotation-degrees.json

**Comment by oterral** [comment]
Rotation fixed with https://github.com/geoadmin/mf-geoadmin3/pull/3850

But there is a problem with the offset of the icon

**Comment by procrastinatio** [comment]
@oterral fill a bug issue in mapfish-print/mapfish branch '2.1.x' and see how long it does it until resolution.

**Comment by procrastinatio** [comment]
Won't fix unless we develop further the old mapfish print v2 branch
