### ISSUE TITLE
KML Print rotate text 

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3843]
Text in rotation mode can not be printed

reproduce
https://s.geo.admin.ch/73ae9a713c 

rotate:
print pdf

result: not all texts are printed
expected result: all texts with annotation are printed

work around:
none

**Comment by procrastinatio** [comment]
Features are not inlcuded in print specs file when the map is rotated

**Comment by davidoesch** [comment]
Below some observation of user

-> will #3846 fix this



I played around a bit with different map scales but same print frames positions and same orientation.
Scaling had directly an influence on the graphic items.
But also moving the map some centimeters in the print frame let change the situation and items becomes visible or fails.
Last but not least, rotating the orientation for some degrees lets the whole thing change and other graphics are concerned.



 
![image](https://user-images.githubusercontent.com/4577727/27022552-d4c3da56-4f4e-11e7-9b3e-9aed13fb0718.png)

Snapshot from print menu in map.geo
All items are correctly shown:
-	A blue track arrow heading north
-	A blue and a red referenced cross
-	The blue and red text annotation of those crosses
-	The magenta routing trackline


After creating PDF exports, several items becomes to be missing.
This depends on the selected map scale (no other changes are made between the exports except scaling the export size (Kartenmassstab / echelle):


 
![image](https://user-images.githubusercontent.com/4577727/27022578-e78633a0-4f4e-11e7-9aa6-02ee13950e33.png)

1:25‘000:
-	Blue textline is missing
-	Red textline is missing
-	Red cross is missing (blue cross is visible)
-	Top of the blue arrow is missing (only a blue line is shown)


 
![image](https://user-images.githubusercontent.com/4577727/27022588-f1341c28-4f4e-11e7-94aa-09d385eb954b.png)

1:50‘000:
-	Blue textline is missing
-	Red textline is missing

But:
-	Blue AND Red crosses are visible
-	Top of the blue arrow is visible

 
![image](https://user-images.githubusercontent.com/4577727/27022597-fc5485d4-4f4e-11e7-94c8-c967736dcffd.png)

1:100‘000:
-	Red textline is missing

But all other items ARE visible:
-	Blue textline
-	Blue AND Red crosses
-	Blue arrow incl. top of arrow
-	Magenta line

 
![image](https://user-images.githubusercontent.com/4577727/27022609-098e8af6-4f4f-11e7-9862-678c6c55cc7b.png)

1:200‘000:
All items ARE visible:
-	Blue and red textlines
-	Blue and Red crosses
-	Blue arrow incl. top of arrow
-	Magenta line

 
![image](https://user-images.githubusercontent.com/4577727/27022619-15ab76fa-4f4f-11e7-89c7-9ee265218054.png)

Otherwise, moving the map to another position of the printframe (i.e. to the upper right corner) has additional 
influence on the graphics: some other items becomes visible or hidden….
1:25‘000:
-	Blue and red textlines are now visible
-	Red cross is still missing but blue cross is now also hidden
-	Top of the blue arrow is still missing


Finally very magic….

**Comment by oterral** [comment]
Fixed on dev
