### ISSUE TITLE
iOS rotate landscape: screen zoom

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3847]
reproduce
iOS  latest, iphone 7 
safari

start from homescreen icon map.geo.admin.ch

enter in search UNESCO
load unesco layer 
rotate  device to landscape

result:
map and UI is enlarged

![image](https://user-images.githubusercontent.com/4577727/27006036-3421c3e8-4e2b-11e7-9210-0b3ec84b1682.png)

expected result:
font size stays the same

no workaround

**Comment by oterral** [comment]
Apple force allow of user zoom since ios10
https://twitter.com/thomasfuchs/status/742531231007559680/photo/1

**Comment by boecklic** [comment]
imho this can be closed. ping @davidoesch ?

**Comment by davidoesch** [comment]
Solved
