### ISSUE TITLE
Print: External WMTS KVP and RESTful are not correctly encoded by map.geo.admin.ch

### ISSUE THREAD

**Issue by procrastinatio** [geoadmin/mf-geoadmin3#3852]
For instance, this [layer](https://map.geo.admin.ch/index.html?lang=fr&topic=ech&bgLayer=voidLayer&layers=WMTS%7C%7Casitvd.fond_pourortho%7C%7Chttps:%2F%2Fows.asitvd.ch%2Fwmts%2F1.0.0%2FWMTSCapabilities.xml%3FSERVICE%3DWMS%26REQUEST%3DGetCapabilities%26VERSION%3D1.3.0&X=223298.56&Y=541204.33&zoom=0) from https://ows.asitvd.ch/wmts/1.0.0/WMTSCapabilities.xml (nota 2056 --> RESTful, 21781 --> KVP)

```
 "layers": [{
        "opacity": 1,
        "type": "WMTS",
        "baseURL": "https://wmts.geo.admin.ch",
        "maxExtent": [420000, 30000, 900000, 350000],
        "tileSize": [null, null],
        "resolutions": [4000, 3750, 3500, 3250, 3000, 2750, 2500, 2250, 2000, 1750, 1500, 1250, 1000, 750, 650, 500, 250, 100, 50, 20, 10, 5, 2.5, 2, 1.5, 1, 0.5, 0.25, 0.09999999999999999, 0.049999999999999996],
        "zoomOffset": 0,
        "version": "1.0.0",
        "requestEncoding": "REST",
        "formatSuffix": "jpeg",
        "style": "default",
        "dimensions": ["TIME"],
        "params": {},
        "matrixSet": "21781"
    }],

``` 

Obviously `requestEncoding` should be `KVP` and `baseURL`  `https://ows.asitvd.ch/wmts`, `tileSize` `256`

Same for `RESTful`  http://www.gis.stadt-zuerich.ch/wmts/wmts-zh-stzh-ogd.xml

``` "layers": [{
        "opacity": 1,
        "type": "WMTS",
        "baseURL": "https://wmts.geo.admin.ch",
        "maxExtent": [672360.5998496102, 238910.91240209187, 690357.0203424249, 257393.42844706448],
        "tileSize": [null, null],
        "resolutions": [66.14596562525627, 33.07298281262813, 16.933367200065604, 8.466683600032802, 4.233341800016401, 2.1166709000082005, 1.0583354500041002, 0.5291677250020501, 0.26458386250102506, 0.13229193125051253],
        "zoomOffset": 0,
        "version": "1.0.0",
        "requestEncoding": "REST",
        "formatSuffix": "jpeg",
        "style": "default",
        "dimensions": ["TIME"],
        "params": {},
        "matrixSet": "21781"
    }],

```

**Comment by procrastinatio** [comment]
Good news, the trusted `mapfish print v2` is even able to print KVP  ([mapfish protocol](http://www.mapfish.org/doc/print/protocol.html))

See [specs file](https://github.com/procrastinatio/mapfish-print-examples/blob/master/specs/wmts-kvp-only.json) and [result](https://www.procrastinatio.org/tmp/wmts-kvp.pdf)

And for inspiration, the old [PrintDirective.js](https://github.com/geoadmin/mf-geoadmin3/blob/kom_print_v3/src/components/print/PrintDirective.js)

**Comment by davidoesch** [comment]
try printing
https://map.geo.admin.ch/index.html?bgLayer=ch.swisstopo.swissimage&lang=de&topic=ech&X=177556.45&Y=613285.15&zoom=11&layers=WMTS%7C%7Casitvd.fond_pourortho%7C%7Chttps:%2F%2Fows.asitvd.ch%2Fwmts%2F1.0.0%2FWMTSCapabilities.xml%3FSERVICE%3DWMS%26REQUEST%3DGetCapabilities%26VERSION%3D1.3.0

**Comment by procrastinatio** [comment]
Merged & deployed, can you test?

**Comment by davidoesch** [comment]
Tested
+1 good for prod
