### ISSUE TITLE
Warning message external data on switch 2d ->3d if wgs84 is not supported 

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3855]
Open WMTS https://s.geo.admin.ch/73d1a50ff4
-> wgs84 not supported therefore data not shown in 3d.

expected result: show warning message
"One ore more external sources does not support WGS84, data will not be displayed in 3d"

**Comment by procrastinatio** [comment]
Different projection, but same problem with print https://github.com/geoadmin/mf-geoadmin3/issues/3860

**Comment by procrastinatio** [comment]
See https://github.com/geoadmin/mf-geoadmin3/issues/3820
