### ISSUE TITLE
3D b3dm  gLTF warnings in Building

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3856]
open 
https://map.geo.admin.ch/?bgLayer=ch.swisstopo.pixelkarte-farbe&lang=fr&topic=ech&lon=7.14025&lat=46.61838&elevation=1063&heading=0.186&pitch=-88.418&layers=WMTS%7C%7Casitvd.fond_pourortho%7C%7Chttps:%2F%2Fows.asitvd.ch%2Fwmts%2F1.0.0%2FWMTSCapabilities.xml%3FSERVICE%3DWMS%26REQUEST%3DGetCapabilities%26VERSION%3D1.3.0

in console: following errors appear
![image](https://user-images.githubusercontent.com/4577727/27129849-12e93220-5104-11e7-8722-190f19bca548.png)

Shoudl be fixed for acceptance protocol

**Comment by tfili** [comment]
This will all be fixed shortly. We are currently in a big push to get 3d-tiles into master and have the surrounding tools updated to the latest specs. After that we should have less breakage as the specs should remain mostly stable.
