### ISSUE TITLE
[print] Client-side reprojected WMS and WMTS won't print

### ISSUE THREAD

**Issue by procrastinatio** [geoadmin/mf-geoadmin3#3860]
WMS and WMTS layers from server not supporting EPSG:21781 are reprojected on-the-fly client-side (if EPSG:4326 is supported).
https://s.geo.admin.ch/73db2f5516

The MapFish Print Server v2 is not able to mix layer of different projection., so the layer won't print

```
java.io.IOException: Didn't receive an image while reading: 
http://www.webatlasde.de/arcgis/services/Maps4BW/MapServer/WMSServer?BBOX=595563.019945192%2C234802.71788842385%2C680441.3553455826%2C290894.3824880332&HEIGHT=1104&WIDTH=1671&map_resolution=150&CRS=EPSG%3A21781&MAP_RESOLUTION=150&SERVICE=WMS&REQUEST=GetMap&DPI=150&STYLES=&TRANSPARENT=true&EXCEPTIONS=XML&VERSION=1.1.1&FORMAT=image%2Fpng&format_options=dpi%3A150&LAYERS=Halbtonvariante&SRS=EPSG%3A21781
```

There is no obvious solution for this issue. We have to warn the user that the layer won't be printed.

**Comment by davidoesch** [comment]
BTW: webatlas is really really "slow"

**Comment by procrastinatio** [comment]
So what do we do? Issue a warning or _enhanced_ the print server (i.e. ditch it and use something else)?
