### ISSUE TITLE
[Import] WMS layer not though proxy

### ISSUE THREAD

**Issue by procrastinatio** [geoadmin/mf-geoadmin3#3861]
Some advertised WMS layer from server lacking **https** support are not directed through the proxy, and hence are not displayed correctly.

e.g. https://map.geo.admin.ch/index.html?layers=WMS%7C%7CHalbtonvariante%7C%7Chttp:%2F%2Fwww.webatlasde.de%2Farcgis%2Fservices%2FMaps4BW%2FMapServer%2FWMSServer%7C%7CHalbtonvariante%7C%7C1.3.0%7C%7Ctrue

**Comment by davidoesch** [comment]
Contacted BW

**Comment by davidoesch** [comment]
No Feedback... Will remove data
