### ISSUE TITLE
WMTS ESRI Shift

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3870]
![image](https://user-images.githubusercontent.com/4577727/27452764-1c2d4cb8-5794-11e7-9664-789b98bd5989.png)

with
https://s.geo.admin.ch/73fcb19d19

**Comment by procrastinatio** [comment]
Looks like it is wrongly georeferenced. Avully's church in Geneva is supposed to be 6.000°W, in https://services.arcgisonline.com/arcgis/rest/services/ESRI_StreetMap_World_2D/MapServer/WMTS/1.0.0/WMTSCapabilities.xml it is not.

**Comment by oterral** [comment]
Fell to reopen if somebody think the problem is on our side.
