### ISSUE TITLE
Improve Search : highlight polygons

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3873]
Search for Pfäfers SG

First entry gives you the Municipality with a point

 
![image](https://user-images.githubusercontent.com/4577727/27472186-b03c0410-57fa-11e7-84a2-31cfff2d329d.png)

expected result

![image](https://user-images.githubusercontent.com/4577727/27472195-bd6acce8-57fa-11e7-8fda-28d33618ec88.png)

might solved together with

-schweizmobil request to adapt search for subset of swissnames
-regbl road/names

**Comment by gjn** [comment]
This has been discussed early in RE4. Currently, we don't have full geometry in search results. It would require an additional request to the API.

And adding all geometries to the search index would blow it up.

We'll evaluate the best approach.

**Comment by boecklic** [comment]
related to https://github.com/geoadmin/mf-chsdi3/issues/3182

**Comment by boecklic** [comment]
closed in accordance with @davidoesch => too much visual distract with yellow overlay
