### ISSUE TITLE
WMS: maps4bw shift

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3877]
Hi we have shift here

when using eg
https://owsproxy.lgl-bw.de/owsproxy/ows/WMS_Maps4BW?request=GetCapabilities&service=WMS&Version=1.3.0&SRS=EPSG:4326 

![image](https://user-images.githubusercontent.com/4577727/27531168-f90fa396-5a5b-11e7-9289-4d25d08dff5a.png)

seems like import does not take into account the projection correctly

Diese Projektionen werden von Maps4BW unterstützt 
 

z.B. https://owsproxy.lgl-bw.de/owsproxy/ows/WMS_Maps4BW?request=GetCapabilities&service=WMS&Version=1.3.0&SRS=EPSG:4326

**Comment by oterral** [comment]
Wrong data on their side . They support 21781 so there is no reprojection on the fly.

**Comment by davidoesch** [comment]
They offer according to Get Cap 3857 

![image](https://user-images.githubusercontent.com/4577727/27678898-2edca26e-5cb7-11e7-88ee-1630ef0d4c9f.png)

why does it not work?

**Comment by oterral** [comment]
Their WMS supports 21781 so the image requested is the good one. Maybe their WMS server uses a bad definition of 21781.

**Comment by procrastinatio** [comment]
Their reprojection to `EPSG:21781` is bogus. If we use `EPSG:4326`or `EPSG:3857`both map align.
So two solution: either fix the `EPSG:21781` reprojection parameters or ditch it (map.geo.admin.ch is able to use the other projection and reproject _on-the-fly_)

**Comment by procrastinatio** [comment]
I did download the `GetCapabilities` and corrected [it](https://www.procrastinatio.org/tmp/lgl-bw.xml) by removing the `Swiss Grid`

```
 diff lgl-bw.xml lgl-bw.xml.ori
127a128
>          <CRS>EPSG:21781</CRS>
```

Now `map.geo.admin.ch`is using `EPSG:4326` and reprojecting _on-the-fly_ and [it is correctly aligned](https://s.geo.admin.ch/742352fc13) (Use a small screen, WMS do not allow big screen)

![epsg_4326](https://user-images.githubusercontent.com/1236739/27726073-41aea2a8-5d79-11e7-848c-f18e43ef4b3e.png)

So the WMS projection for `EPSG:21781` is faulty

**Comment by davidoesch** [comment]
maybe related as well to https://github.com/openlayers/openlayers/issues/4256

**Comment by oterral** [comment]
probably not. We use a single tile WMS.

**Comment by procrastinatio** [comment]
No, this issue is related to `WMTS`, we are dealing with `WMS`

**Comment by procrastinatio** [comment]
What server and definition do they use?

**Comment by davidoesch** [comment]
Awaiting feedback from bawü

**Comment by davidoesch** [comment]
I Go the feedback from "baWü"
"inzwischen wurde die  noch ausstehende Transformation EPSG:21781 mit eingepflegt."

<Layer queryable="0" opaque="0" noSubsets="0">
<Title>Maps4BW</Title>
<Abstract>Maps4BW</Abstract>
<CRS>EPSG:4326</CRS>
<CRS>EPSG:4258</CRS>
<CRS>EPSG:3857</CRS>
<CRS>EPSG:31466</CRS>
<CRS>EPSG:31467</CRS>
<CRS>EPSG:31468</CRS>
<CRS>EPSG:25832</CRS>
<CRS>EPSG:25833</CRS>
<CRS>EPSG:21781</CRS>
-> But we still have the issue

**Comment by oterral** [comment]
@davidoesch can you ask them which proj4/WKT  definition they use for EPSG:21781 ?

**Comment by davidoesch** [comment]
Awaiting feedback from bawü

**Comment by davidoesch** [comment]
Here the feedback

"
CH1903_LV03
Berechtigungscode: 21781 (EPSG)

Projection: Hotine_Oblique_Mercator_Azimuth_Center
False_Easting: 600000,0
False_Northing: 200000,0
Scale_Factor: 1,0
Azimuth: 90,0
Longitude_Of_Center: 7,439583333333333
Latitude_Of_Center: 46,95240555555556
Linear Unit: Meter (1,0)

Geographic Coordinate System: GCS_CH1903
Angular Unit: Degree (0,0174532925199433)
Prime Meridian: Greenwich (0,0)
Datum: D_CH1903
  Spheroid: Bessel_1841
    Semimajor Axis: 6377397,155
    Semiminor Axis: 6356078,962818189
    Inverse Flattening: 299,1528128
"

"
die Definition für die Projektion EPSG:21781 ist in ArcGIS beinhaltet. Um eine weitere Projektion für einen Dienst bereitszustellen, wird diese von ArcGIS vordefinierte Projektionsdatei verwendet. Das ist das, was vor einigen Wochen gemacht wurde, damit der BW-Dienst in der Schweiz eingebunden werden kann. Möglicherweise ist diese vordefinierte Datei fehlerhaft, was ich mir jedoch nicht vorstellen kann. Vieleicht liegt das Problem an anderer Stelle. Wie groß ist die Abweichung in X- und Y-Richtung ? Das gibt oft Rückschlüsse wieder
"

**Comment by oterral** [comment]
https://owsproxy.lgl-bw.de doesn't support EPSG:2056 so now the tiles are reprojected on-the-fly. So no more issue.
Feel free to reopen it if the problem occurs again when the wms will supoort EPSG:2056.

**Comment by davidoesch** [comment]
https://map.geo.admin.ch/?lang=de&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=WMS%7C%7CMaps4BW%7C%7Chttp:%2F%2Fowsproxy.lgl-bw.de%2Fowsproxy%2Fows%2FWMS_Maps4BW%3F%7C%7CHalbtonvariante%7C%7C1.3.0%7C%7Ctrue&E=2645646.85&N=1267818.97&zoom=9

dos not show data ..even when I add https

**Comment by oterral** [comment]
Size limittations of their WMS: 
```
<ServiceExceptionReport xmlns="http://www.opengis.net/ogc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.3.0" xsi:schemaLocation="http://www.opengis.net/ogc http://schemas.opengis.net/wms/1.3.0/exceptions_1_3_0.xsd">
<ServiceException code="InvalidFormat">Parameter 'width' contains unacceptable value.</ServiceException>
</ServiceExceptionReport>
```

**Comment by davidoesch** [comment]
Ahh  if I really have a small screen it will work ....
