### ISSUE TITLE
Appcache update doesn't work on iOS

### ISSUE THREAD

**Issue by oterral** [geoadmin/mf-geoadmin3#3885]
only iOS

When safari requests an old appcache, it expects a 404 or 410 error to reload the new appcache file, or on int and prod a 403 is returned so appcache is not reloaded.

**Comment by oterral** [comment]
Thx @rebert to have found this.

**Comment by danduk82** [comment]
should be fixed: 
we had to grant ListBucket permission to cloudfront. Otherwise you get a 403. Now it is a 404.

Please test and close the issue if it works.

**Comment by davidoesch** [comment]
IMHO solved on prod

**Comment by gjn** [comment]
Thanks alot for acting fast - and @rebert for the good find.
