### ISSUE TITLE
3d add  zeitreise to 3d

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3887]
enable zeitreise WMTS in 3D based on 
https://github.com/AnalyticalGraphicsInc/cesium/pull/5542

**Comment by tfili** [comment]
The PR has been move to https://github.com/AnalyticalGraphicsInc/cesium/pull/5575. The original had 2 features, one of which needed more work, so this is just the WMTS with time-dynamic dimensions.

**Comment by oterral** [comment]
Wait for https://github.com/AnalyticalGraphicsInc/cesium/pull/5696

**Comment by oterral** [comment]
Fixed in prod
