### ISSUE TITLE
KML: Issue does not load in 3D

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3888]
The KML 
[ThomasUlrich.zip](https://github.com/geoadmin/mf-geoadmin3/files/1119476/ThomasUlrich.zip)

in 3D 
does not render/crashes the application

![image](https://user-images.githubusercontent.com/4577727/27792836-cfbf7930-5ffb-11e7-9da6-457018d9f5ff.png)

-> Which part has to be fixed either in
A) KML
or 
b) in mf-geoadmin /cesium ?

since this is needed for a promotion case: quite urgent

David

PS: the live file will be loaded from
|https://www.thomasulrich.com/de/direttissima/ThomasUlrich.kml

but the server  does not give Access-Control-Allow..customer is informed

**Comment by davidoesch** [comment]
UPDATE:
new live link https://s.geo.admin.ch/743511fd6d

2d works:
3d does not work

**Comment by procrastinatio** [comment]
At first, two things
* CORS
* `TimeSpan` ouch

This is OK in 3D:

https://s.geo.admin.ch/7435738d0d

**Comment by oterral** [comment]
Caused by Ceisum: https://github.com/AnalyticalGraphicsInc/cesium/issues/5580

**Comment by davidoesch** [comment]
Seems to be fixed.https://s.geo.admin.ch/743a157830
