### ISSUE TITLE
update help with realtime parameter

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3892]
Since we can track realtime now:
update https://help.geo.admin.ch/?id=54
with 
[ ] layers_params=updateDelay
for json and kml files

as in example https://s.geo.admin.ch/7423d396b9

**Comment by procrastinatio** [comment]
Note for @pauloamado 
`updateDelay` unit are seconds (instead of millisecond in interanl JSON)
Is only for KML: WMS and WMTS update are not supported, and there is no way for a user to import JSON

**Comment by oterral** [comment]
@pauloamado Is it done ?

**Comment by oterral** [comment]
it seems yes
