### ISSUE TITLE
KML : polygon cut off in 3d

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3893]
Open
https://s.geo.admin.ch/743a157830

Result
![img_1052](https://user-images.githubusercontent.com/4577727/27839590-a24188ca-60f2-11e7-96ae-6a6cfcf6a9ea.PNG)
 Expected result: 
The polygon covers tiles of all LOD

**Comment by oterral** [comment]
if same iPhone , same issue https://github.com/geoadmin/mf-geoadmin3/issues/3837
