### ISSUE TITLE
Enable time slider in 3D

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/mf-geoadmin3#3895]
Since https://github.com/AnalyticalGraphicsInc/cesium/pull/5575 has been merged this should now be possible in 3D as well.

**Comment by oterral** [comment]
We don't use `WebMapTileImageryProvider` class but `UrlTemplateImageryProvider`

**Comment by oterral** [comment]
Duplicate with https://github.com/geoadmin/mf-geoadmin3/issues/3887
