### ISSUE TITLE
Link to LD resources

### ISSUE THREAD

**Issue by p1d1d1** [geoadmin/mf-geoadmin3#3899]
What about adding a link in tooltip for administrative units pointing to corresponding resource in ld.geo.admin.ch?

**Comment by gjn** [comment]
This would be a backe-end, data issue.

Can you give an example of a link?

**Comment by p1d1d1** [comment]
Cantons: https://ld.geo.admin.ch/boundaries/canton/"BFS-Number"
Districts: https://ld.geo.admin.ch/boundaries/district/"BFS-Number"
Municipalities: https://ld.geo.admin.ch/boundaries/municipality/"BFS-Number"

**Comment by davidoesch** [comment]
Hi
This makes sense for the tooltip of ch.swisstopo.swissboundaries3d-gemeinde-flaeche.fill etc
but not for the general tooltip

@p1d1d1 pls ask via @mariokeusen to add this via dataowner to the tooltip of swissboundaries


![image](https://user-images.githubusercontent.com/4577727/27952560-04640c40-6309-11e7-9c90-380991443434.png)

**Comment by p1d1d1** [comment]
Sure, as said in the ticket this applies only to admin units layers, meaning kantone, bezirke, gemeinde and not the general tooltip. will check with Mario

**Comment by p1d1d1** [comment]
@mariokeusen how do we proceed here?

**Comment by mariokeusen** [comment]
Good idea
Steps to do: 
1. ask data owner for a go
2. implement this on the "ld"-layers (the 4 swissboundaries)

**Comment by p1d1d1** [comment]
Got an ok from the data owner and we can proceed with this according to the following mockup:

![ld](https://user-images.githubusercontent.com/1533649/28875835-60e066d8-7797-11e7-9278-d5bdef8ab41b.png)

The Linked Data URI shoudl be built as follows:

ch.swisstopo.swissboundaries3d-kanton-flaeche.fill: https://ld.geo.admin.ch/boundaries/canton/BFSNumber

ch.swisstopo.swissboundaries3d-bezirk-flaeche.fill: https://ld.geo.admin.ch/boundaries/district/BFSNumber

ch.swisstopo.swissboundaries3d-gemeinde-flaeche.fill: https://ld.geo.admin.ch/boundaries/municipality/BFSNumber

**Comment by davidoesch** [comment]
Yes !
