### ISSUE TITLE
Improve Page load

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3902]
Start
https://testmysite.withgoogle.com/intl/en-gb/?utm_source=reactive&utm_medium=email&utm_campaign=report&utm_content=snippet

result

![image](https://user-images.githubusercontent.com/4577727/28061200-004ca314-662a-11e7-85ec-f36b5bcd5f0e.png)

According to big G:
"A few fixes could   reduce   loading time by: ~3s"

**Comment by gjn** [comment]
In addition, diretissima tech guys also mentioned that they have negative feedback on performance of map.geo on mobile devices.

**Comment by davidoesch** [comment]
on https://www.thomasulrich.com/de/direttissima/direttissima-schweiz.php 

he has enforced desktop
-> he should detect mobile and then start mobile version

**Comment by davidoesch** [comment]
and again, if I load in mobile
https://map.geo.admin.ch/?X=181583.40&Y=657531.10&zoom=1&layers_params=,updateDelay=60&layers=KML||https://cms.geo.admin.ch/Topo/KML/parcours.kml,KML||https://www.thomasulrich.com/de/direttissima/ThomasUlrich.kml
![image](https://user-images.githubusercontent.com/4577727/28068340-5a810346-6645-11e7-9d7c-3d636584d088.png)


issue: on their server?

**Comment by loicgasser** [comment]
what issue? we're testing cors it's normal you see some red in the console. not an error

**Comment by oterral** [comment]
He should used embed page and his website is very slow something block the rendering and touch events for a while

**Comment by davidoesch** [comment]
well he needs full view for the location search....

**Comment by gjn** [comment]
I think the integration in the direttisima page could be improved. But I consider this another issue.

The performance issues here described should be addressed by us.

**Comment by oterral** [comment]
@davidoesch  That's why we use appcache on mobile so this test makes no sense. Our site is already optimized.

**Comment by davidoesch** [comment]
Ok... Thanks for the explanation.
