### ISSUE TITLE
Measure distance: difference between path and linear distance

### ISSUE THREAD

**Issue by mariokeusen** [geoadmin/mf-geoadmin3#3912]
Question coming up from customer feedback:
What is exactly the difference between the path and linear distance given in the measure tool?
In most of the cases, when I measure in flat areas, there is no or only a tiny difference between the 2 values given, which I think is quite hard to understand for users. I assume that most users expect the distance between the first and the last point of their path. Customer example here: https://s.geo.admin.ch/74cd4bccee
![distance](https://user-images.githubusercontent.com/4577749/28862662-1b4a2dec-7766-11e7-9b30-7fb9ca3bd505.PNG)

I think, it would be helpful to have a more detailed documentation/explanation of the measured values given in https://help.geo.admin.ch/?id=94&lang=en or at least in the faq in wiki. @davidoesch: something we should discuss.

**Comment by oterral** [comment]
I think the description is more clear in french and german.

**Comment by davidoesch** [comment]
Linear distance is the correct translation for "luftlinie".

If the customer does not know the difference between distance and linear distance... He has to google it. We can't replicate a geography 101 tutorial in the help.

**Comment by mariokeusen** [comment]
Obviously it's unclear. Questions like that are coming in regularly in helpdesk...

**Comment by davidoesch** [comment]
Wenn Can add a link https://de.m.wikipedia.org/wiki/Luftlinie
