### ISSUE TITLE
KMZ /Dropbox stopped working

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3918]
This link is using an external KMZ file stored on dropbox. and stopped working "last week" according to customer

https://s.geo.admin.ch/7439915a60

points to eg
www.dropbox.com/s/1w24b3l8pslb9xz/chasse%20chevreuil.kmz?dl=1 

out proxy returns a 403

-> IMHO customer changed sth or did we chnage KMZ support?

**Comment by oterral** [comment]
We didn't deploy last week. If we can't have access to the file (403 is forbidden) we can't download it. Maybe the user changes the access right of the file, otherwise it's an infra problem. 

Internally dropbox is blocked I can't acces the file.

Can you ask him @davidoesch please?

**Comment by oterral** [comment]
Proxy says `Forbidden content-type`

**Comment by davidoesch** [comment]
forbidden because of KMZ? mime type wrong?

**Comment by oterral** [comment]
it seems content-type is set as `application/binary` instead of the good kmz mime-type.

I don't know if you can change that on dropbox.

**Comment by loicgasser** [comment]
https://github.com/geoadmin/service-proxy/pull/37

**Comment by loicgasser** [comment]
This is not a kmz at all.
It returns an HTML page....
So ask him to fix that. Fix has been deployed.

**Comment by davidoesch** [comment]
www.dropbox.com/s/1w24b3l8pslb9xz/chasse%20chevreuil.kmz?dl=1 is a valid kmz if unzipped it can be loaded

**Comment by loicgasser** [comment]
Well there are some carzy redirections and I am analyzing the last url... which doesn't end with .kmz and is not a valid content-type. I'll open it a bit more...

**Comment by loicgasser** [comment]
https://mf-chsdi3.int.bgdi.ch/shorten/751a682b52
fixed see url above
