### ISSUE TITLE
Newer Version warning: is nag window

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3923]
![image](https://user-images.githubusercontent.com/4577727/29378818-c79d64a0-82c0-11e7-8665-86c590da4bd3.png)

why not just load the new data in the background? and warn user only if it is not successfully update in xx min time?

**Comment by oterral** [comment]
Because the user maybe doesn't want to load the data with his 2g connection.

**Comment by loicgasser** [comment]
I believe Google does the same

**Comment by davidoesch** [comment]
Google Map app does this in the background

**Comment by loicgasser** [comment]
I mean it doesn t do it at all, unless you re connected to the wifi. So it is normal to not auto update on 2 G

**Comment by loicgasser** [comment]
I am talking about the app here and in a browser you can t tell for sure if it s a wifi or 3g connection

**Comment by davidoesch** [comment]
If in desktop version there should be no warning (since in desktop version you have no offline access) on mobile on desktop there should be a warning but even on large screens but with the fix here #3924

**Comment by boecklic** [comment]
will be fixed with https://github.com/geoadmin/mf-geoadmin3/issues/4900
