### ISSUE TITLE
3D: KML Tooltip/Object selection

### ISSUE THREAD

**Issue by gjn** [geoadmin/mf-geoadmin3#3927]
Can we make it possible?

https://map.geo.admin.ch/?topic=ech&lang=de&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.bafu.alpweiden-herdenschutzhunde,ch.astra.wanderland,ch.swisstopo.swisstlm3d-wanderwege,ch.bav.haltestellen-oev,KML%7C%7Chttp:%2F%2Fsilvercode.dwbox.ch%2Fewalk%2Fimages%2Fewalk2%2F1213%2Fgeodata%2Fgeodata_de.xml&layers_visibility=false,false,false,false,true&layers_opacity=0.5,1,1,1,1&lon=7.64414&lat=46.73531&elevation=1872&heading=359.993&pitch=-40.365

**Comment by oterral** [comment]
Here we have a problem to connect Cesium primitive to the corresponding OL feature.

**Comment by oterral** [comment]
Fixed in prod
