### ISSUE TITLE
Drawing: add option to make disappear helping tooltip

### ISSUE THREAD

**Issue by gjn** [geoadmin/mf-geoadmin3#3928]
Several people have complained that the helping tooltip (little grey box) next to the mouse in the drawing mode is not really nice - and that they want an option to remove it.

Thoughts?

**Comment by oterral** [comment]
We could add a shortcut CTRL+H to hide the tooltip.

**Comment by davidoesch** [comment]
How does google do it? my maps google does not have a tooltip.

IMHO : we can remove it completely. Reference is in Help.geo.admin.ch

**Comment by davidoesch** [comment]
@oterral you can remove: let's see what will happen: we have drawing now up and running with the current look and feel for more than a year

**Comment by boecklic** [comment]
wontfix in accordance with @davidoesch (for usability reasons)
