### ISSUE TITLE
3D: default BG BUILDING VEGETATION , selection containes Names

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3929]
When switching to 3D in Beta 1.1

A) The background is ch.swisstopo.swisstlm3d.3d (Building and vegetation NO BRIDGES)
https://mf-geoadmin3.int.bgdi.ch/3dtiles/index.html?lang=fr&topic=ech&tileset3d=ch.swisstopo.swisstlm3d.3d,ch.swisstopo.vegetation.3d,&tilesetTs=20170425,20170630_2000_1000,20161121&bgLayer=ch.swisstopo.pixelkarte-farbe&dev3d=true&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bav.haltestellen-oev,ch.swisstopo.swisstlm3d-wanderwege&layers_visibility=false,false,false,false&layers_timestamp=18641231,,,&lon=8.81974&lat=47.21927&elevation=977&heading=272.182&pitch=-35.918 

B) at the same time in the selection window contains ch.swisstopo.swissnames3d.3d  which is active and can be deselected
https://mf-geoadmin3.int.bgdi.ch/3dtiles/index.html?lang=fr&topic=ech&tileset3d=ch.swisstopo.swissnames3d.3d,&tilesetTs=20170814,20170425,20170630_2000_1000,20161121&bgLayer=ch.swisstopo.pixelkarte-farbe&dev3d=true&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bav.haltestellen-oev,ch.swisstopo.swisstlm3d-wanderwege&layers_visibility=false,false,false,false&layers_timestamp=18641231,,,&lon=7.86398&lat=46.68428&elevation=1076&heading=43.486&pitch=-26.806

**Comment by oterral** [comment]
Fixed in 3dtiles branch
