### ISSUE TITLE
WMTS import fails

### ISSUE THREAD

**Issue by gjn** [geoadmin/mf-geoadmin3#3931]
the import of our WMTS is reported as successfull (message "Upload OK!"). However, there are no layers listed for the actual import. 

http://www.ogc.stadt-zuerich.ch/mapproxy/wmts/1.0.0/WMTSCapabilities.xml

What are we missing?

**Comment by gjn** [comment]
Missing the <ows:OperationsMetadata> tag with the <ows:Operation name="GetTile"> . 

It’s where we get the URL of the service.

Example of a good WMTS:
https://www.basemap.at/wmts/1.0.0/WMTSCapabilities.xml

**Comment by oterral** [comment]
https://github.com/camptocamp/ngeo/issues/2850

**Comment by oterral** [comment]
OperationMetadata tag is optional.
