### ISSUE TITLE
External KML: remove Area/ distance in tooltip

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3932]
Area/ distance in external KML tooltip can be anoying

Proposal:
We add Area in profil footer info and remove it from tooltip

Thoughts?

**Comment by oterral** [comment]
-1 Why is it annoying ?  It's valuable informations in a small amount of place and that displays something when the feature has no description.

**Comment by davidoesch** [comment]
for pure infographics like chloropleth maps wher you want to focus the user on one value in a cell like inhabitants https://s.geo.admin.ch/755db30bdf 

plus we have all other stats in the profil

what speaks against: google has the same behaviour as it is currently implemented

**Comment by oterral** [comment]
Maybe we can provide a better visual separation between the htm description and the footer

**Comment by oterral** [comment]
if google does it, it's good :)
