### ISSUE TITLE
KML from Google Fusion does not display 'correctly'

### ISSUE THREAD

**Issue by procrastinatio** [geoadmin/mf-geoadmin3#3933]
There is a request from the federal chancellery to us map geo.admin.ch to use 

https://www.google.com/fusiontables/DataSource?docid=1U2CUL8woRuFeuqv_fp_ljNXA-2TgXRbOLaVOY2PH 

in fusiontables/google maps

![f](https://user-images.githubusercontent.com/1236739/29861542-e13da9ac-8d69-11e7-818d-adb9df9df47d.png)

![ff](https://user-images.githubusercontent.com/1236739/29861616-1bec69da-8d6a-11e7-99c0-bc2665dbdb84.jpg)

We had this issue earlier
https://github.com/geoadmin/mf-geoadmin3/issues/3421 
and see attached mail

**Comment by oterral** [comment]
Do we provide fusiontable assistance now ? :)

**Comment by davidoesch** [comment]
As written in the mail: I have workaround.
it is rather: 
do we have a clean KML file of cantons where the user can enter HEX color code to  each canton which works with  ol

**Comment by oterral** [comment]
wrong google export , what can we do?

**Comment by davidoesch** [comment]
Nothing... there is a workaround
