### ISSUE TITLE
3D does not work in EDGE or IE9

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3940]
open in win10 edge BUraut

https://mf-geoadmin3.int.bgdi.ch/3dtiles/index.html?lang=en&topic=ech&tileset3d=ch.swisstopo.swissnames3d.3d,ch.swisstopo.swisstlm3d.3d,ch.swisstopo.vegetation.3d&tilesetTs=20170814,20170425,20170630_2000_1000,20161121&bgLayer=ch.swisstopo.pixelkarte-farbe&dev3d=true&layers=WMS%7C%7Ctlm3d%20wms%20dev%7C%7Chttp:%2F%2Fwms-bod.dev.bgdi.ch%2F%3F%7C%7Cch.swisstopo.swisstlm3d-karte-farbe.3d%7C%7C1.3.0,ch.swisstopo.swissimage-product&layers_visibility=false,false&lon=7.41969&lat=46.95438&elevation=736&heading=34.892&pitch=0.278

**Comment by oterral** [comment]
Tom is on it

**Comment by oterral** [comment]
fixed in 3dtiles
