### ISSUE TITLE
Search result : 3 times same place

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3941]
reproduce:

enter "Schliern" in swiss search

result:
3 times same entry with same center
![image](https://user-images.githubusercontent.com/4577727/29958315-73ec40cc-8ef2-11e7-8340-4045719adf46.png)

expected result

only one result

**Comment by ltclm** [comment]
will be fixed here:
https://github.com/geoadmin/service-sphinxsearch/pull/336

**Comment by ltclm** [comment]
sphinx config on prod instances has not been updated, issue still there.
