### ISSUE TITLE
Implement Plus Codes/Open Location Code in context "Position" menu (right-click)

### ISSUE THREAD

**Issue by sfkeller** [geoadmin/mf-geoadmin3#3946]
Plus Codes are the "open" alternative e.g. to W3W.

* Public site (Docs, Forum etc.): http://www.openlocationcode.com/
* Github project (Wiki, z.B. Python): https://github.com/google/open-location-code/tree/master/python
* Demo site: http://plus.codes/

Example "bQm Kulturcafé & Bar Zürich":
* Lat/Lon: 47.375938,8.546687
* Plus Code (complete 10 codes): 8FVC9GGW+9M
* Plus Code (short code): 9GGW+9M
* Plus Code (shorter code with geoname): GW+9M Zürich

**Comment by gjn** [comment]
Which codes to show on the context popup?

Which codes to support in the search?

Do we remove w3w?

**Comment by davidoesch** [comment]
We keep w3w in search and context pop up ( Q4 2018 . usage check)
PLusCode 
- Search  a go
- Context : would fill up Context-pop up: we need to reconsider on what we implement. Proposal/brainstorming: add as well plus code

**Comment by sfkeller** [comment]
I've an additional, natural enhancement: Implement Plus Codes/Open Location Code not only in context Context-pop up but also in the "Geographical search" (centre on coordinates).
And I would not object at all if this issue would be implemented after a year of discussion :-). Just in case the pop up is filled up too much, I'd suggest to drop those geocode systems which are proprietary and not.open.atall ;-).

**Comment by davidoesch** [comment]
So far , the number of requests for this feature are quasi noon existent. We will look into that again on the next version of the map viewer.

**Comment by boecklic** [comment]
wontdo in accordance with @davidoesch

**Comment by LaPingvino** [comment]
😢 

> I'd suggest to drop those geocode systems which are proprietary and not open at all.

I am seeing more and more people adopting w3w and it worries me because if their central service to look up the codes disappears, you have a huge issue. On the contrary, I implemented OLC-support for the osm.org website as a bookmarklet at https://github.com/lapingvino/olc-tools in an evening work, because they somehow think that because it comes from Google, it's proprietary. Nope, it's not and it's SO trivially easy to implement, and it can help people so much that I find it cruel to let this depend on requests for it.

**Comment by sfkeller** [comment]
Actually; I can't confirm that w3w is being adopted widely. This is a sign given the amount of money the got and invest in order to scam e.g. poor countries.

What really hurts, is, that neutral, independent and good situated portals like GeoAdmin get induced by w3w - and then don't even give a chance for alternatives.

**Comment by picsi** [comment]
I definitely agree that having an open source alternative like Plus Codes would be preferrable.
