### ISSUE TITLE
Error when KML is modified and updateDelay is specified 

### ISSUE THREAD

**Issue by nadine-piveteau** [geoadmin/mf-geoadmin3#3961]
Given a KML, errors occurs when the KML is modified using draw- and measure-tools.

[testlink](https://mf-geoadmin3.dev.bgdi.ch/?lang=fr&topic=ech&bgLayer=ch.swisstopo.pixelkarte-grau&X=196500.00&Y=624125.00&zoom=1&layers_params=updateDelay%3D3&layers=KML%7C%7Chttps:%2F%2Fpublic.int.bgdi.ch%2Fu1E0P4d_Tom7s7w8Ez4Kng)

**Comment by oterral** [comment]
When we open draw the updateDelay timeout should stop

**Comment by boecklic** [comment]
wontfix in accordance with @davidoesch
