### ISSUE TITLE
3D Permalink layer order

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3971]
I have this view

![image](https://user-images.githubusercontent.com/4577727/31125528-dd158990-a848-11e7-87e1-03bc7904a684.png)
 
Copying the permalink
https://mf-geoadmin3.int.bgdi.ch/3dtiles/index.html?lang=fr&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.swissimage-product,ch.swisstopo.swissnames3d&lon=7.69293&lat=46.67758&elevation=1658&heading=153.410&pitch=-17.196

-> the order is not taken into account, swisismage is over the names layer: Iayer order not in pl

![image](https://user-images.githubusercontent.com/4577727/31125616-29f061a4-a849-11e7-9eba-a65a54bbf4ff.png)

expected result:
in 3d layer works as well

**Comment by oterral** [comment]
Name is always on top in 3d wherever you put it on the layers list

**Comment by oterral** [comment]
but yes it's strange names are under in the list

**Comment by oterral** [comment]
I can't reproduce

**Comment by davidoesch** [comment]
nope layers are NOT on the top, they are not shown if they are not on the top. can reproduce here on all browsers

**Comment by oterral** [comment]
swissimage uses the opaque property . I think it's probably related .

**Comment by oterral** [comment]
Fixed
