### ISSUE TITLE
Highlight for multipoint geometries not working

### ISSUE THREAD

**Issue by AFoletti** [geoadmin/mf-geoadmin3#3972]
Issue:
When you click on a point no highlight is done if the geometry coming from the identify request is of type:MultiPoint.
This is clearly a regression, but I can't say when exactly it went to prod

Steps to reproduce:
- activate ch.astra.unfaelle-personenschaeden_motorraeder on map.geo.admin.ch
- click on a point: tooltip comes up normally but no highlight

**Comment by oterral** [comment]
OL update related https://github.com/openlayers/openlayers/pull/7297

**Comment by AFoletti** [comment]
OK. Do we get the OL fix by next deploy?

**Comment by oterral** [comment]
yes in 2 weeks

**Comment by AFoletti** [comment]
I get discordant info from your answer.
Next deploy is next week. So "yes" or "no, but in 2 weeks"?

**Comment by oterral** [comment]
yes  in 1 week.

**Comment by AFoletti** [comment]
😃 thanks for clarifying
