### ISSUE TITLE
adaption of feedback when deploying

### ISSUE THREAD

**Issue by rebert** [geoadmin/mf-geoadmin3#3991]
**When activating S3 to prod (make s3activateprod S3_VERSION_PATH=master/2cd45c6/1710111336) following message appears:**
Please check it on mf-geoadmin3.prod.bgdi.ch/index.html
And mf-geoadmin3.prod.bgdi.ch/src/index.html

**Should be**
Please check it on mf-geoadmin3.prod.bgdi.ch/index.html
And mf-geoadmin3.prod.bgdi.ch/**master/2cd45c6/1710111336/src**/index.html

It scared the hell out of me ;-)

**Comment by oterral** [comment]
Fixed by #4012
