### ISSUE TITLE
GPX: profile / distance in tooltip footer

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3992]
Hi

for external GPX

https://map.geo.admin.ch/?lang=de&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bav.haltestellen-oev,ch.swisstopo.swisstlm3d-wanderwege,GPX%7C%7Chttp:%2F%2Fwww.barbalex.ch%2FBike%2FAargau%2FBrugg-ChestenbergViaAare.GPX&layers_visibility=false,false,false,false,true&layers_timestamp=18641231,,,,&X=256530.61&Y=656345.78&zoom=7

-> link  to profile and distance/Area in tooltip footer possible? so we have feature parity with KML

**Comment by oterral** [comment]
we have feature parity. I think it's because it's a multiline. We don't display the profile link for MultiXXX geometries. But we can improve it.
