### ISSUE TITLE
[URL shortener] shortened permalinks do not work in Edge

### ISSUE THREAD

**Issue by mariokeusen** [geoadmin/mf-geoadmin3#3993]
UC: open app, zoom somewhere, add some data, store the permalink with the URL shortener under "share". copy + paste short url and open it in MS Edge.
Result: no map, but a site as in the screenshot below opens
Expected: map opens with the original settings made by the user by generating the short url

Remarks: 
- made this observation inside BV, but did not test outside. May be a specific setting in Edge?
- when I try the same with the long permalink, it works as expected

**Comment by mariokeusen** [comment]
![shorturl_edge](https://user-images.githubusercontent.com/4577749/31597068-b1020e7a-b246-11e7-8d06-e57467c0765e.PNG)

**Comment by davidoesch** [comment]
https://s.geo.admin.ch/764f4568d5
in EDGE  (BVNET) works like a charm

-> you need to kill cash or pray for a better/faster proxy @bit 

![image](https://user-images.githubusercontent.com/4577727/31598438-fda7275e-b24d-11e7-8f1f-182c40b97613.png)

**Comment by mariokeusen** [comment]
Sounds like we cannot influence that...
In any case, short URLs never work on my EDGE in BVnet (and I'm not the only one facing this)

**Comment by gjn** [comment]
I obseve the same. Remember the call we had last Friday, @davidoesch ?

Oli: can you have a look? Maybe there's a workaround - but I doubt it. I think edge doesn't fully do a re-direct - or there's a timing issue in that the base url doesn't change.

**Comment by gjn** [comment]
ping @oterral

**Comment by davidoesch** [comment]
Outside bv net it Works on Edge

**Comment by oterral** [comment]
It works for me at swisstopo. I really think there is edge configuration which forbid the redirect.

**Comment by davidoesch** [comment]
Hmm I observed it... On bv net: it seems like the short URL generation process in edge on slow connection is an issue ... My assumption

**Comment by oterral** [comment]
Please reopen if you succes to reproduce.
