### ISSUE TITLE
slash missing in help file : paramteter

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3995]
slash missing in help file : paramteter
https://help.geo.admin.ch/?id=54&lang=de

![image](https://user-images.githubusercontent.com/4577727/31672610-54628024-b35d-11e7-8153-9580da8e236b.png)

since  I can't edit it -- thanks marc for tehe fix

**Comment by oterral** [comment]
Does it change anything ? it's the same with or without.

**Comment by davidoesch** [comment]
The URL when clicked is different. Was a remark from a user

**Comment by oterral** [comment]
@pauloamado cna you fix this pls?

**Comment by pauloamado** [comment]
It's done.

**Comment by oterral** [comment]
Thx
