### ISSUE TITLE
edge : does not copy link

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#4001]
reproduce:
open EDGE on win 10 
https://mf-chsdi3.int.bgdi.ch/shorten/7674ee7dbf 

pan arroudn

shre:

copy link button

Result:

link not copied

expected result:
link copied

work around
copy link manually control c

**Comment by oterral** [comment]
works for me.  @nadine-piveteau you have the same problem, haven't you?

**Comment by nadine-piveteau** [comment]
I've just tested it in edge and it seems to work. However, it doesnt work in IE11.

**Comment by oterral** [comment]
can't reproduce
