### ISSUE TITLE
3D: Site marker not shown

### ISSUE THREAD

**Issue by nadine-piveteau** [geoadmin/mf-geoadmin3#4002]
The red site marke does not appear when you look for a place.

Tested on Chrome, Firefox, Edge, IE11

Reproduce: 
1. Open [link ](https://mf-chsdi3.int.bgdi.ch/shorten/7665529faf)
2. Enter in swisssearch `Thun(BE)` (or any other place)

Results: Marker does not appear

**Comment by oterral** [comment]
duplicate of #3354

**Comment by loicgasser** [comment]
Problem is with the artificially introduced `()` in the label.
we could stript those characters in the search and it would do the trick.
