### ISSUE TITLE
GPX export

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#4003]
Request by several customers

GPX export

Proposal
 when hitting the "export" button
- create besides the KML file as well a GPX file

your thoughts 
@gjn @procrastinatio @oterral

**Comment by oterral** [comment]
You will loose style informations, no measure, no text, no circle. GPX is not format to show a draw.
But we can, if users wants that.

**Comment by davidoesch** [comment]
this exactly the trade off: do implement an export GPX and afterwards explin to customers that it won't contain any drawing/description tag?  This measn those are just the follow up question. an GPX makes sense for  pure measures of lines.
Actually there are a lot of API and services like gpxtokml.com which do exactly this task. 
on the other hand: schweizmobil also allows adding images and text to their drawings but when exported (gpx ) they are gone https://www.schweizmobilplus.ch/schweizmobilplus/anleitung.html

so I'm not yet convinced

**Comment by boecklic** [comment]
wontfix in accordance with @davidoesch
