### ISSUE TITLE
Misaligned terrain tiles

### ISSUE THREAD

**Issue by AFoletti** [geoadmin/mf-geoadmin3#4009]
There are some misaligned terrain tiles. You can see a long line of them around here:
https://s.geo.admin.ch/767828cefc

**Comment by loicgasser** [comment]
This is a known issue. Topo wasn't able to export the different parts of the terrain properly. This occurs when cutting the TIN into smaller parts based on the national map division at 25 meters. I hope that the next delivrery will solve this issue.

For a visual explanation see:
https://s.geo.admin.ch/76a2c8d4fe

**Comment by oterral** [comment]
bad clsoed issue

**Comment by oterral** [comment]
Fixed with the last terrain version.
