### ISSUE TITLE
iFrame centering issues with "width:100%"

### ISSUE THREAD

**Issue by AFoletti** [geoadmin/mf-geoadmin3#4010]
A customer reported an issue of the iFrame when setting "width:100%" instead of a fixed pixel width.
Apparently, the centering of the map is messed up by this setting. Could you please check that out?

Example of use:
https://www.rsi.ch/news/vita-quotidiana/cultura-e-spettacoli/Obelix-%C3%A8-passato-da-Berna-9698107.html

**Comment by oterral** [comment]
hmm I don't see the problem.
