### ISSUE TITLE
Print legend of external WMS

### ISSUE THREAD

**Issue by oterral** [geoadmin/mf-geoadmin3#4016]
To reproduce:
 - [link with external wms](https://mf-chsdi3.int.bgdi.ch/shorten/76a37d7b46)
 - Print the map with legend checkbox checked.
---> No legend in the PDF

Expected:
--> The image genereated by GetLegendGraphic is displayed

We already use the GetLgednGraphic in the metadata info box. It should be straightforward to send it to the print.

**Comment by boecklic** [comment]
wontfix in accordance with @davidoesch
