### ISSUE TITLE
3D  performance lag compared with beta cesium

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#4025]
open: https://beta.cesium.com/viewer/3d4afc16-979d-4a39-9f62-4fdc64141aed

it is way faster tha our BETA

- [ ] review the fixes we did on the c2c branch for cesium. Could be that they are no longer needed - or even degrade performance.

- [ ] Maybe cesium has added other performance related options that we simply don't use yet

- [ ] mouse scroll/movement is way more better (not as sensitive as in our beta)

**Comment by oterral** [comment]
Quantity of data displayed is everything.

With the same terrain and imagery we have the same performance.[Test](https://mf-geoadmin3.dev.bgdi.ch/teo_vib/vib/templates/csmap.html)

**Comment by gberaudo** [comment]
Strangely with upstream Cesium the camera can sink below the terrain. Do you also reproduce it?

**Comment by oterral** [comment]
Yes.

**Comment by davidoesch** [comment]
mouse scroll/movement is way more better (not as sensitive as in our beta)
