### ISSUE TITLE
PDF: annotation local file

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#4031]
add a local kml/gpx file

print PDF

result 
![image](https://user-images.githubusercontent.com/4577727/32512861-ada6d710-c3f8-11e7-8d72-55dbc92d9761.png)

expected result; "map.geo.admin.ch" is not shown (since  we are NOT responsible for local draw) if we do show sth: the sho the drive letter

**Comment by oterral** [comment]
It's also the case in the UI.
@davidoesch  What do you want as attribution for local files ?  nothing?

**Comment by davidoesch** [comment]
local files : NTH is path to the directory (eg "C:\temp\mynice\data\onmynice\windwoscomputer\inmyfile.kml" or at tleast the first 35 char-- 
if not doable with pareto: keep it empty

**Comment by oterral** [comment]
I'm in favor to keep it empty.

**Comment by gjn** [comment]
Or a generic term like 'Local File' in read (to mark it external). Maybe 'Custom File', 'Custom Data', 'Import', or something. But I think it's important to show something, I think.

**Comment by oterral** [comment]
User Data ?

**Comment by oterral** [comment]
Local FIle is fin for me

**Comment by davidoesch** [comment]
+1 ... 
use it for all lang
