### ISSUE TITLE
PDF: annotation  third party  on one line right

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#4032]
open a third party external link eg https://s.geo.admin.ch/76c3472bae

print to PDF

result
![image](https://user-images.githubusercontent.com/4577727/32513034-2c2a10a2-c3f9-11e7-8c0d-134c4139710e.png)

expected result

annoattaion is 
- [  ] on the right ,leftbound of the scale, 
- [  ]  on one (1) line

as it was before

**Comment by oterral** [comment]
@davidoesch  could we avoid to display the copyright of external data in red ? it will simplify a lot the management of copyrights.

**Comment by davidoesch** [comment]
OK for  the (c) text in the map: you can display it in black. Keep the text in red in the box below
