### ISSUE TITLE
Inconsistent height

### ISSUE THREAD

**Issue by p1d1d1** [geoadmin/mf-geoadmin3#4034]
Highlighted by a customer:

![map geo admin_hoehe](https://user-images.githubusercontent.com/1533649/32558353-d31a2a04-c4a4-11e7-9251-9248594e065e.jpg)

On the LK the height is 2915. The tooltip shows 2817.

I've been informed that in map.geo.admin.ch the source for the height service is "COMB".
At this point (2'604'096.500, 1'113'361.000) "COMB" takes swissALTI3D as source:

http://api3.geo.admin.ch/rest/services/height?easting=2604096.500&northing=1113362&elevation_model=DTM2&sr=2056

whith a difference of almost 100 meters.

If you use DTM25 (which is default for the height service) as source you get a closer result (10 meters difference):

http://api3.geo.admin.ch/rest/services/height?easting=2604096.500&northing=1113362&elevation_model=DTM25&sr=2056

**Comment by davidoesch** [comment]
Awaiting Feedback topio

**Comment by davidoesch** [comment]
Il s'agit d'une erreur dans les données. Il manque un bout de la montage (trou) 

 

L’original ressemble à ça

 

Ce sera corrigé et intégré dans la prochaine publication en mars 2018.
![image](https://user-images.githubusercontent.com/4577727/32598057-f73718c2-c538-11e7-9008-b512fc2d66a5.png)


Il y aura encore des petites différences entre la valeur de la carte et la valeur du click, mais pas de 100m.
