### ISSUE TITLE
Swisssearch abbreviation does not work

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#4036]
Abkürzungen sollten mit wordforms unterstützt sein:

https://github.com/geoadmin/service-sphinxsearch/blob/master/conf/wordforms_main.txt

https://github.com/geoadmin/service-sphinxsearch/commit/7b6b2274916834374f1cb455f99acf45a04e5244

 

Scheinbar ist der punkt am Ende ein Problem:

Funktioniert:

https://api3.geo.admin.ch/rest/services/api/SearchServer?searchText=Schwarzenburgstrasse 157&type=locations

https://api3.geo.admin.ch/rest/services/api/SearchServer?searchText=Schwarzenburgstr 157&type=locations

Funktioniert nicht:

https://api3.geo.admin.ch/rest/services/api/SearchServer?searchText=Schwarzenburgstr. 157&type=locations

**Comment by mavelli** [comment]
Der Punkt stört auch bei anderen Abkürzungen wie "place":
fails:
https://api3.geo.admin.ch/rest/services/api/SearchServer?type=locations&searchText=pl.%20du%20March%C3%A9,%20,%201350,%20Orbe
works:
https://api3.geo.admin.ch/rest/services/api/SearchServer?type=locations&searchText=pl%20du%20March%C3%A9,%20,%201350,%20Orbe

**Comment by mavelli** [comment]
Ebenso bei Ortsnamen:
fails:
https://api3.geo.admin.ch/rest/services/api/SearchServer?type=locations&searchText=Lindenstrasse%207,%20,%203550,%20Langnau%20i.%20E.
works:
https://api3.geo.admin.ch/rest/services/api/SearchServer?type=locations&searchText=Lindenstrasse%205,%20,%203550,%20Langnau%20i%20E

quick and dirty workaround would be to substitute all tailing dots with blanks - no example yet where this would fail to circumvent the issue

**Comment by loicgasser** [comment]
Hi, for pl. we have place and platz.

Removing the `.` would probably have some undesired side effects.
Our layer ids use dots for instance. See: 
`ch.swisstopo.pixelkarte-farbe` for instance.

I'll run some tests see what I can do. Maybe remove the `.` only for the location search, not sure at this point.

**Comment by mavelli** [comment]
from what i read the API3, the layer ids are not used in the searchText variable, right? maybe a substitute of ". " with "  " in searchText may work generally? 

let me know if you need some external testing :)

**Comment by loicgasser** [comment]
@davidoesch we need to upgrade sphinx search to support dots in sphinxsearch

**Comment by davidoesch** [comment]
Effort estimate?

**Comment by loicgasser** [comment]
Fixed and should be deployed to prod today.
