### ISSUE TITLE
Third party and time enabled collision

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/mf-geoadmin3#4037]
https://s.geo.admin.ch/76cdc8f2cc
See in layertree

**Comment by davidoesch** [comment]
Since there is an important update with wildruhezonen.ch ... And will have a lot b of users. A fix need on first of Dec

**Comment by oterral** [comment]
Not so urgent because the link of @loicgasser  uses  the wmts geo admin with the import tool.

If you use the layer from the catalog or the search box the third party will not aqppear

**Comment by oterral** [comment]
Wmts geoadmin is not detcted as a 2rd party
