### ISSUE TITLE
location search is not fuzzy enough (House Nr "7c" works, "7 c" does not)

### ISSUE THREAD

**Issue by mavelli** [geoadmin/mf-geoadmin3#4038]
Location search fails when the house number-letter combinations have a space between them.

this works:
https://api3.geo.admin.ch/rest/services/api/SearchServer?type=locations&searchText=7c,%20av.%20Alfred%20Cortot,%201260,%20Nyon

this does not:
https://api3.geo.admin.ch/rest/services/api/SearchServer?type=locations&searchText=7%20c,%20av.%20Alfred%20Cortot,%201260,%20Nyon

**Comment by oterral** [comment]
I think it's normal , house with number and letter are not separated by space in the official register.
