### ISSUE TITLE
Forbidden acces to ign wmts

### ISSUE THREAD

**Issue by oterral** [geoadmin/mf-geoadmin3#4039]
Try to import https://wxs.ign.fr/bvl2gp6za3srtz6yblo9fx8o/wmts?SERVICE=WMTS&VERSION=1.0.0&REQUEST=GetCapabilities

Server answer:
```
<ExceptionReport>
<Exception exceptionCode="MissingRights">
Wrong referer or wrong IP Adress or wrong User-Agent
</Exception>
</ExceptionReport>
```

**Comment by oterral** [comment]
@davidoesch can you contact them ?

**Comment by davidoesch** [comment]
Hi @cedricmoullet can u contact them? Since you were in touch for setting it up

**Comment by loicgasser** [comment]
we forward the header [1], so it should work in geoadmin.
https://github.com/geoadmin/service-proxy/blob/master/service_proxy/main.py#L158

**Comment by oterral** [comment]
It works on production but not on dev.
