### ISSUE TITLE
update PL help with changes due to LV95 migration

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#4040]
https://help.geo.admin.ch/?id=54

besides x,y (lv03) we have now LV95 support (N,E) in the PL

-> pls add alll new features introduced

@beat-github pls add this to your com plan/fact sheet to migration lv03LV95

**Comment by oterral** [comment]
@pauloamado can you add `E`and `N` parameters pls?

**Comment by boecklic** [comment]
ping @pauloamado

**Comment by pauloamado** [comment]
Done
