### ISSUE TITLE
wmts_url=//service-proxywms.dev.bgdi.ch default mode=preview

### ISSUE THREAD

**Issue by ltclm** [geoadmin/mf-geoadmin3#4041]
when visualizing wmts_url=//service-proxywms.(dev|int|prod).bgdi.ch urls the default configuration should be 
``mode=preview``

We could be able to test/visualize new data without writing to s3. 
this could even be the default mode in service-proxywms.

**Comment by oterral** [comment]
service-proxywms.(dev|int|prod).bgdi.ch?mode=preview
or
service-proxywms.(dev|int|prod).bgdi.ch/preview
service-proxywms.(dev|int|prod).bgdi.ch/debug
service-proxywms.(dev|int|prod).bgdi.ch/default

**Comment by procrastinatio** [comment]
You may change mode in https://github.com/geoadmin/service-proxywms/blob/master/dev.env

**Comment by danduk82** [comment]
for dev mode=preview since quite a long time in the docker-compose config of the service-proxywms
