### ISSUE TITLE
Print

### ISSUE THREAD

**Issue by p1d1d1** [geoadmin/mf-geoadmin3#4043]
Several customers are highlighting an issue with the print (maybe already known?):

Customer feedback ID : 2017111422242552: Mir ist aufgefallen, dass beim Drucken 1:50'000 die "alte" Karte dargestellt wird und nicht das neue Kartenmaterial. Noch im März war das anders (ich kann Ihnen ein entsprechendes PDF schicken). Auch wenn ich bei SchweizMobil 1:50000 drucke, bekomme ich als Ausdruck die neue Karte.

Customer feedback ID : 2017111420325864: beim ausdrucken der neuen karte 1:25'000 entspicht die qualität der karte der 1:50'000 alte karte vom 07.05.2017 neue karte vom 09.11.2017.

**Comment by procrastinatio** [comment]
This is fixed, we only need to deploy `mf-geoadmin3` (`mapfish-print`tomcat is already deployed:
`mapfish-print`https://github.com/geoadmin/service-print/pull/48 (https://github.com/geoadmin/service-print/releases/tag/r_171109)
`mf-geoadmin3` https://github.com/geoadmin/mf-geoadmin3/pull/4028

[Demo](https://mf-geoadmin3.int.bgdi.ch/mom_print_dpi/index.html?print_url=%2F%2Fservice-print.prod.bgdi.ch&lang=fr&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bav.haltestellen-oev,ch.swisstopo.swisstlm3d-wanderwege&layers_visibility=false,false,false,false&layers_timestamp=18641231,,,)

**Comment by procrastinatio** [comment]
@p1d1d1 @davidoesch does this fix the issue?

**Comment by procrastinatio** [comment]
It has been deployed. Please test.

**Comment by p1d1d1** [comment]
@procrastinatio as fas as the 2 customer feedbacks are concerned, it seems to have been fixed.

**Comment by gjn** [comment]
Merci!
