### ISSUE TITLE
Inform user if too many points

### ISSUE THREAD

**Issue by gjn** [geoadmin/mf-geoadmin3#4044]
While drawing, we are sending the drawn points on a regular basis to our backends. If the line/polygon is huge, this causes a huge request causing problems in the backend.

Once we detect that the number of points is > x points, we inform the user that we don't do the profile anymore. Maybe directly in the profile windows.

x=1000 to start, but needs to be verified.

@nadine-piveteau That could be something for you (no GIFS/Harlekins here, please ;=))

**Comment by davidoesch** [comment]
Hi both...
needs further investigation before we limit the user

- [  ]  define "huge" : number of vertexes? Or distance?  How many times  did we reach this limit in the last year (6month)?

- [  ]  Reporting:  Showing a an info like " to big drawing no profile calculation possible" is not service excellence. we should at least reduce the number of points *before* we call the profile service. not showing a profile at all..does not make sense.  rule number in egov: don't patronize the user ...

**Comment by oterral** [comment]
@davidoesch has tried with an ugly line yesterday and the respons was pretty fast 
with 3000 points. https://s.geo.admin.ch/770a344e41

**Comment by loicgasser** [comment]
thanks for the info. Ultimately, I'd like to be able to parse a bigger linestring and I think this should be possible using an iterative approach. I'll put a hard limit for really big lines.

**Comment by oterral** [comment]
Can we more details of what broke the service height?
Are we sure it's related to draw?
How many requests ?

**Comment by loicgasser** [comment]
It s not how many. It is how big.

**Comment by gjn** [comment]
Yes, we are sure that lines with a huge number of points can break the profile service. The problem is also that we auto-update on edit of huge polylines.

I've send you an example link.

I think front-end, we can do 2 things:

a) Throttle the automatic profile update in function of the number of points (or response time of previous request!)
b) Downsize the number of points before sending. 3000 points should be good.

**Comment by oterral** [comment]
I think the auto update can be improved . Currently the profile is updating when the user is dragging the point. Waiting the user  drop the point could fix part of the issue.

**Comment by loicgasser** [comment]
https://github.com/geoadmin/service-alti/pull/28
I propose to limit content-length at 150'000 and return a 413. (around 7'000 coordinates)

https://restpatterns.mindtouch.us/HTTP_Status_Codes/413_-_Request_Entity_Too_Large
You can then inform the user.

**Comment by davidoesch** [comment]
how many of todays KML (generated in the last 6 month) would be affected?
