### ISSUE TITLE
GSM slow loading/not loading

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#4046]
Open
https://map.geo.admin.ch/?lang=de&topic=ech&bgLayer=voidLayer&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bav.haltestellen-oev,ch.swisstopo.swisstlm3d-wanderwege,ch.bakom.mobil-antennenstandorte-gsm&layers_visibility=false,false,false,false,true&layers_timestamp=18641231,,,,&E=2540404.86&N=1182839.84&zoom=5

on chrome/ ie etc.... pan and zoom ....  slow really slow generation of the tiles. and once  in a while the tiles don't load at all . 

![image](https://user-images.githubusercontent.com/4577727/32941460-2504df84-cb86-11e7-85aa-abc8b71375db.png)

**Comment by oterral** [comment]
Yes there is some tiles which are generated in 1.5 sec . It's a WMS issue.

**Comment by loicgasser** [comment]
just switch it to WMTS if ok with data owner.
ping @gjn

**Comment by loicgasser** [comment]
FYI this is not TOD, but pure WMS

**Comment by davidoesch** [comment]
Ambroggio can you contact the customer and check the switch to wmts ? Since we will offer raw download ... This should possible

**Comment by ltclm** [comment]
there are daily updates.

**Comment by davidoesch** [comment]
ToD invalidation settings should be able to handle this

**Comment by loicgasser** [comment]
yes when we can call a service after the data update. This is planned early 2018

**Comment by ltclm** [comment]
we have wms-c for this use case.

**Comment by AFoletti** [comment]
This layer, along with the other antennenstandorte, is planned to switch to a geoJSON solution early 2018
This should make the whole faster and we will not have to worry about wms/wmts/tod

**Comment by davidoesch** [comment]
Serving more than 5000 points with json will probably not be performant for mobile/ weak clients

**Comment by oterral** [comment]
Perfect use case for vector tiling

**Comment by AFoletti** [comment]
As info, migration of the Antennae layers to geoJSON is ongoing.
[Here a testlink](https://mf-chsdi3.dev.bgdi.ch/gas_bakom_json/shorten/790ce11695) if someone is interested (and I know @davidoesch is 😉 ). Performance is not too bad in my opinion. @Sgachet will check with Loïc to try to optimize

**Comment by oterral** [comment]
@ambrogio why ch.bakom.radio-fernsehsender is not geokjson and the others are. [See](https://s.geo.admin.ch/7a9de6df4a)
