### ISSUE TITLE
swisssearch: Doubleentries for resulttypes "Ausfahrt" and "Verzweigung"

### ISSUE THREAD

**Issue by mariokeusen** [geoadmin/mf-geoadmin3#4047]
UC: open app, search for "Kiesen" and "Härkingen"
Result: there are always 2 results for the same place from type "Ausfahrt" and "Verzweigung" (see screenshots)
Expected: only one result without "§" character

Probably a data source driven phenomenon.

Remark: the result without the "§" zooms to object on zoomlevel 9, while the result with the "§" goes to zoomlevel 10. Otherwise no difference.
![swisssearch_ausfahrt](https://user-images.githubusercontent.com/4577749/32945026-298ad5de-cb92-11e7-8d06-a5dd342566bf.PNG)
![swisssearch_verzweigung](https://user-images.githubusercontent.com/4577749/32945030-2d53dc6a-cb92-11e7-8564-47890df3ab86.PNG)

**Comment by boecklic** [comment]
@mariokeusen pls clarify with dataowner. will close issue here
