### ISSUE TITLE
Css issue on mobile trash on top of porfile

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/mf-geoadmin3#4056]
![screenshot_20171122-200855](https://user-images.githubusercontent.com/3306154/33145588-46481140-cfc1-11e7-8547-2b4d4b5177a1.png)

**Comment by loicgasser** [comment]
C est juste magique d avoir toutes les fonctionnalités sur mobile. Masterdul @oterral

**Comment by gjn** [comment]
I fully agree.
