### ISSUE TITLE
PDF generation: filenaming convention

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#4062]
since the recent update, filenaming convention changed. Customers set up processes whcih depend upon the filenaming convention for printed pdf

please do create files with followoing filenaming convention as before

mapgeoadminch_YYYYMMDDHHSS.pdf

**Comment by gjn** [comment]
?

I'm not sure it was like this before. In my download folders, I don't have PDF's with this naming convenction.

Was it browser specific?

**Comment by davidoesch** [comment]
nope, but IMHo this makes sense since we have the same rouleset for the KML donwload

**Comment by procrastinatio** [comment]
OK, so the print service is not exclusively for map.geo.admin.ch, and with have customers for it, that is an interesting news.

Nothing has changed. The files on the EFS are written has before as _ mapfish-print4036736447557526268.pdf.printout_ and _mapfish-print-multi1711091119004600.pdf.printout_ (multi), but nobody is supposed to know this information.

When, printing, you get a link as:
    `{"getURL":"https://print.geo.admin.ch/print/3098482393337918520.pdf.printout"}`
And the application use this link to download the file 

As before, the file is download as `map.geo.admin.ch.pdf` (attachment)

File name are [pretty well burried](https://github.com/geoadmin/mapfish-print/blob/2.1.x_geoadmin3/src/main/java/org/mapfish/print/servlet/MapPrinterServlet.java#L71) in mapfish print v2 code

**Comment by oterral** [comment]
It was never like this before I think you think about KML name: map.geo.admin.ch_KML_20170703090940.kml

**Comment by oterral** [comment]
@procrastinatio said we can do it via [nginx](https://github.com/geoadmin/service-print/blob/master/nginx/nginx.conf.in#L63)

**Comment by procrastinatio** [comment]
There is no easy way to generate a date in nginx. The only way is to parse the temporary file for its id and send it back. It will produce something like `mapgeoadminch_6241639260603667797.pdf`

[link](https://mf-geoadmin3.int.bgdi.ch/?print_url=%2F%2Fservice-print.dev.bgdi.ch)

**Comment by davidoesch** [comment]
80/20 wise enough

**Comment by oterral** [comment]
@procrastinatio we could modifiy directly the print using a dtae instead of a generate id: 
https://github.com/mapfish/mapfish-print/blob/d99b2a60d7e67a98aaf894101c14ff76c6620966/src/main/java/org/mapfish/print/servlet/MapPrinterServlet.java#L188

**Comment by oterral** [comment]
even better we could add the date we want with the post request

**Comment by procrastinatio** [comment]
See https://github.com/geoadmin/service-print/pull/83/files

**Comment by procrastinatio** [comment]
See https://github.com/geoadmin/service-print/pull/83

[Demo](https://mf-geoadmin3.dev.bgdi.ch/?print_url=//service-print.dev.bgdi.ch)

**Comment by oterral** [comment]
Name is now map.geo.admin.ch_YYYYMMDDHHSSsss.pdf to be consistent with KML

**Comment by oterral** [comment]
we deploy it tomorrow

**Comment by boecklic** [comment]
solved
