### ISSUE TITLE
PDF: many external WMS fail to deliver print

### ISSUE THREAD

**Issue by procrastinatio** [geoadmin/mf-geoadmin3#4064]
So many external WMS server are not supported anymore.

We have to check for 10+ external WMS, but it looks like some WMS servers do not like options like _DPI_, _map_params_ or _format_options_ send by _QGIS_, _mapserver_ and _Geoserver_.

**Comment by davidoesch** [comment]
This is bad... For interoperability. 
Solution?

**Comment by procrastinatio** [comment]
Yeah, interoperability....

So `GR` is still LV03, so map.geo.admin.ch uses `WGS:84`, so no print. And by the way, should be `https`
`geodienste.ch` responds with empty images...
`zugmap` chockes on parameters `EXCEPTION=XML`
We do not have access to IGN

**Comment by oterral** [comment]
So we have done all what we can do
