### ISSUE TITLE
Feature search uses bbox

### ISSUE THREAD

**Issue by cedricmoullet** [geoadmin/mf-geoadmin3#4066]
1. Start https://s.geo.admin.ch/77337d0469
2. Search for 1469353
3. Feature is found
4. Search for 9051164
5. Feature is not found

Workaround: zoom out and search again -> feature is found.

Feature search is using the window bbox in order to search for feature -> is it really wanted ? @davidoesch  @gjn ?

My proposal is to remove the bbox filter in this case (and maybe use it only in order to order the result list)

**Comment by davidoesch** [comment]
Remove bbox Filter Not wanted. 
@mariokeusen @ltclm Might be related to lfhk search issue

**Comment by gjn** [comment]
It was wanted back in the days. We had a long discussion about it. We could find it in the issues here somewhere....

I see the following: we used bbox (also) for ordering the results around the center of the bbox. Before, results were distributed randomly all over switzerland - also in locations that are _not_ visible in the map. This confused the user.

I propose the following: for featuresearch, we use bbox for sorting only, but not to filter results. For location search, we do the same.

**Comment by loicgasser** [comment]
I don't think we should mess around with the ranking of the location search.
The sortbbox will ignore the weight of the matching string. I think this is incorrect, it should be a combination of both spatial and text relevance. I would say for now KISS.
Also, the sortbbox  adds an overhead on the search service.

**Comment by davidoesch** [comment]
No changes in the ranking. Remove window bbox

**Comment by gjn** [comment]
ok.

but we could not change ranking for location search, and change it for feature-search.

**Comment by davidoesch** [comment]
Imho You can remove it from feature search. And possible related https://github.com/geoadmin/mf-chsdi3/issues/2727 ?
