### ISSUE TITLE
wmts_url=//localhost:7000

### ISSUE THREAD

**Issue by ltclm** [geoadmin/mf-geoadmin3#4070]
https://github.com/geoadmin/mf-geoadmin3/blob/463c18853b2330c3e7a3586da3ff1dab9a202fec/src/components/import/example/index.html#L89

it would be useful to use a service-proxywms image on localhost:7000 as wmts source.
``wmts_url=//localhost:7000``

**Comment by oterral** [comment]
only in dev, accept localhost

**Comment by oterral** [comment]
Fixed  by #4157
