### ISSUE TITLE
Zivile Signaturen BABS

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#4073]
Situation 
- [x] http://www.babs.admin.ch/de/publikservice/grundlagen/zivileabk.html#tabs_0 zivilesignaturende.pdf
we are dealing only with point elements
- [x]  Dashed line
- [x]  Pulldown Symbol Selektor
[DE] Standard / Zivile Signaturen
[FR] défaut / Signes conventionnels civils
[IT] predefinito / Segni convenzionali civili
[EN] default / civil symbols

![image](https://user-images.githubusercontent.com/4577727/33663373-fe1aefc6-da8f-11e7-8705-0324d1ae9ee5.png)

and
![image](https://user-images.githubusercontent.com/4577727/33663406-2454a72c-da90-11e7-92d2-838a37b69014.png)

Next Step:
- EMF to PNG: Defintion Grösse/Format instructions BABS  to Convert it to our spec 
See emf zip under http://www.babs.admin.ch/de/publikservice/grundlagen/zivileabk.html#tabs_0
See example below for  48x48 conversion via imagemagick

Symbols:
[babs-Signaturen_10180226.zip](https://github.com/geoadmin/mf-geoadmin3/files/1757959/babs-Signaturen_10180226.zip)

**Comment by gjn** [comment]
Es geht darum, neue Symbole hinzuzufügen?
Wenn ja, welche? (Ich finde auf dem Link nichts)

Get es darum BABS spezifisches Zeichnen zu machen?

**Comment by davidoesch** [comment]
Correct link http://www.babs.admin.ch/de/publikservice/grundlagen/zivileabk.html#tabs_0  (under documented you find the emf file link and the link to the PDF)

Proposal is: to create a pulldown menu for symbol : default is today's symbol set and a second is babs)

Can you give me 
- the spec for the symbols which a delivery from babs needs to have (PNG format, size (only one afaik we scale it via the icon size parameter), color set , naming convention) so Babs can estimate their workload 

- estimate of igeb-b for adding pulldown and new icon set so we can take it up into the planning sheet

**Comment by davidoesch** [comment]
I did a quick imagemagick convert " for /r %i in (*) do convert -resize 48x48 %i %i.png"

resulting in the images below

- are those images suited this way for our drawing?
- Color: They have to choose the right color via color selector (since we always do offer all colors for all icons)

![bezirksfuhrungsorgan emf](https://user-images.githubusercontent.com/4577727/33657998-58ec55da-da7b-11e7-83e1-9a919a85715b.png)
![biounfall emf](https://user-images.githubusercontent.com/4577727/33657999-59109fa8-da7b-11e7-927f-cb361cc5dda0.png)
![bombenanschlag emf](https://user-images.githubusercontent.com/4577727/33658000-59489d04-da7b-11e7-92e0-960ee82dae4f.png)
![bombendrohung emf](https://user-images.githubusercontent.com/4577727/33658001-5967e646-da7b-11e7-9f3d-a93890794ecb.png)




![angehorigensammelstelle emf](https://user-images.githubusercontent.com/4577727/33657988-577896fa-da7b-11e7-9f20-476b61642678.png)
![atomunfall emf](https://user-images.githubusercontent.com/4577727/33657989-579db3ae-da7b-11e7-93fc-64948c1c6462.png)
![autounfall emf](https://user-images.githubusercontent.com/4577727/33657991-57c74462-da7b-11e7-9c56-36629efdd94e.png)
![beobachtung emf](https://user-images.githubusercontent.com/4577727/33657993-57ecc17e-da7b-11e7-8d5a-7a3310893a4a.png)
![beschadigung emf](https://user-images.githubusercontent.com/4577727/33657995-58345a2a-da7b-11e7-9a37-eb0a29fa6669.png)
![betreuungsstelle emf](https://user-images.githubusercontent.com/4577727/33657996-5873b30a-da7b-11e7-9877-c203257dc9dd.png)
![betriebsstoffabgabestelle emf](https://user-images.githubusercontent.com/4577727/33657997-58c991a8-da7b-11e7-93b7-718a02be8678.png)

**Comment by oterral** [comment]
If it's official color we could disable the color change when we select this list of icons

**Comment by davidoesch** [comment]
Even better. 
Do the icons fit your requirement? If yes I will ask babs to rename them with a counter so the order of appearance is clear

**Comment by oterral** [comment]
Yes I can probably use it as it is

**Comment by davidoesch** [comment]
Awaiting feedback from BABS

**Comment by davidoesch** [comment]
Hi @oterral 
can you check if attached zip fits our set up?

-> babs will deliver a final version if it is ok
[Zivile_Signaturen (2).zip](https://github.com/geoadmin/mf-geoadmin3/files/1694121/Zivile_Signaturen.2.zip)

**Comment by oterral** [comment]
yes I'm checking

**Comment by oterral** [comment]
width/height are ok.

But to be consistent with maki icons if they could:
    - optimize the png. It doesn't seems it the case.
    - use a naming onvention without  'xxx-marker' and the '00' at the end. Ex:  babs-1.png, babs-2.png ,....

I say that for future deliveries if it's a one shot I can do it myself.

2-3 days are needed to add them to map.geo.admin.ch.

**Comment by davidoesch** [comment]
BABS delivered the final signatures
(see ticket description above)

**Comment by oterral** [comment]
@davidoesch we could save the choosen set of icons in the localstorage. So on the next use on the same PC  they don't have to change the list again. It could be annoying if you do that for each icon you place on the map . what do yout think?

**Comment by gjn** [comment]
In favor of keeping app state, good idea. Usually, we keep app state in permalink - on first thought, I think it makes sense to put iconset in PL as well (there might be more coming...).

**Comment by davidoesch** [comment]
do we have an ETA? June?

**Comment by davidoesch** [comment]
Hi @nadine-piveteau can you follow this one up? ETA would be June.  (NTH) .
Can give you a short intro on the scope

**Comment by oterral** [comment]
@davidoesch it's not the last version on the description field. Do you have the new version?

**Comment by davidoesch** [comment]
U mean the File Names in the zip File?

**Comment by oterral** [comment]
yes

**Comment by oterral** [comment]
sorry the zip is good on the description. @nadine-piveteau

**Comment by davidoesch** [comment]
as discussed with oli its the link in the description of the ticket
https://github.com/geoadmin/mf-geoadmin3/files/1757959/babs-Signaturen_10180226.zip
