### ISSUE TITLE
feature search is broken on gwr layer

### ISSUE THREAD

**Issue by cedricmoullet** [geoadmin/mf-geoadmin3#4075]
Search for address on https://map.geo.admin.ch/?lang=fr&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bav.haltestellen-oev,ch.swisstopo.swisstlm3d-wanderwege&layers_visibility=false,true,false,false&layers_timestamp=18641231,,,
![image](https://user-images.githubusercontent.com/319676/33740019-7ecf924c-db9f-11e7-9f9f-350d8f232220.png)
![image](https://user-images.githubusercontent.com/319676/33740044-89ce8c98-db9f-11e7-826c-92b030ba2f12.png)

**Comment by loicgasser** [comment]
fixed via https://github.com/geoadmin/service-sphinxsearch/pull/356
sorry for that

![gwr](https://user-images.githubusercontent.com/3306154/33743347-b86302fc-dbac-11e7-92ae-537efbdbd260.png)
