### ISSUE TITLE
Link To Object does not open tooltip

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#4076]
open a link to object
https://map.geo.admin.ch/?ch.swisstopo.lubis-luftbilder_schwarzweiss=19502510013656&lang=de&topic=luftbilder&catalogNodes=1179,1180,1186&bgLayer=ch.swisstopo.pixelkarte-grau&layers=ch.swisstopo.lubis-luftbilder_schwarzweiss,ch.swisstopo.lubis-luftbilder_farbe&layers_timestamp=99991231,99991231&E=2722296.14&N=1251367.26&zoom=7

result only highlight

expected result; highlight AND tooltip open

**Comment by oterral** [comment]
Are you sure it wasn't like that before?

**Comment by AFoletti** [comment]
I've the feeling that "link to object" never opened the tooltip, but I can be wrong

**Comment by davidoesch** [comment]
I'm not sure , but IMHo t makes sense

**Comment by loicgasser** [comment]
Defenetly was the case. Probably a regression introduced when we added link to object support for geojson.

**Comment by oterral** [comment]
It makes sense for [extended tooltip](https://mf-chsdi3.dev.bgdi.ch/rest/services/luftbilder/MapServer/ch.swisstopo.lubis-luftbilder_farbe/20010110035047/extendedHtmlPopup?lang=de) . I think the `notooltip` permalink param was used for that but it doesn't seem to be used in the extened tooltip.

**Comment by oterral** [comment]
I've found there is another `showTooltip=true` permalink param if you set it to true the popup is shown.

**Comment by oterral** [comment]
So is the `showTooltip` param enough?  @davidoesch .

**Comment by davidoesch** [comment]
a fix with https://map.geo.admin.ch/?ch.swisstopo.lubis-luftbilder_schwarzweiss=19502510013656&lang=de&topic=luftbilder&catalogNodes=1179,1180,1186&bgLayer=ch.swisstopo.pixelkarte-grau&layers=ch.swisstopo.lubis-luftbilder_schwarzweiss,ch.swisstopo.lubis-luftbilder_farbe&layers_timestamp=99991231,99991231&E=2722296.14&N=1251367.26&zoom=7&showTooltip=true
is ennough
