### ISSUE TITLE
Koordinatennetz CH1903+/LV95 (Bundesamt für Landestopografie swisstopo): does not work

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#4080]
Koordinatennetz CH1903+/LV95 (Bundesamt für Landestopografie swisstopo) does not work
https://s.geo.admin.ch/777fe0e27f

**Comment by loicgasser** [comment]
what does not work? I can see the grid right now.

**Comment by davidoesch** [comment]
Ahh after 40 seconds!

why is 
https://wms.geo.admin.ch/?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=org.epsg.grid_2056&LANG=de&CRS=EPSG%3A2056&STYLES=&WIDTH=960&HEIGHT=569&BBOX=2420000%2C1047750%2C2900000%2C1332250

so slow

**Comment by AFoletti** [comment]
strange. It is blazing fast by me

**Comment by loicgasser** [comment]
Same here. Might be a device related bug.

**Comment by davidoesch** [comment]
same here from home PC. but I had several teachers which gave me this feedback (ToD issue?)

**Comment by loicgasser** [comment]
No it s WMS single tile.

**Comment by oterral** [comment]
Feel free to reopen if you have more details to reproduce it.
