### ISSUE TITLE
Profile troubles

### ISSUE THREAD

**Issue by gjn** [geoadmin/mf-geoadmin3#4083]
Despite fixes in mf-geoadmin3 and mf-chsdi3, we are still in a position that our application causes our backends to have outages. Outages took place Friday around 18:30 and was caused by this:

https://map.geo.admin.ch/?topic=swisstopo&lang=de&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.hiks-siegfried,KML%7C%7Chttps:%2F%2Fpublic.geo.admin.ch%2FbeFYnM2ZQ425Kt3rY0TtrA&E=2570787.62&N=1200005.87&zoom=3.4818177664692733&catalogNodes=1396,1427

I think both the app and api need better fixes to mitigate such risks.

**Comment by loicgasser** [comment]
The fix for the profile has not been deployed yet.

**Comment by loicgasser** [comment]
In service-alti

**Comment by oterral** [comment]
i think it's fixed now
