### ISSUE TITLE
Import IGC flight tracks

### ISSUE THREAD

**Issue by t0b3** [geoadmin/mf-geoadmin3#4088]
Import feature for IGC tracks would be awesome for [paragliding](https://openlayers.org/en/latest/examples/igc.html?mode=advanced).
Seems very similar to GPX (#3962) you just added.
 [IGC](https://openlayers.org/en/latest/apidoc/ol.format.IGC.html) file format is supported by openlayers.

**Comment by davidoesch** [comment]
http://igc2kml.com/ as workaround

**Comment by davidoesch** [comment]
Low prio

**Comment by boecklic** [comment]
wontfix in accordance with @davidoesch
