### ISSUE TITLE
Testing custom stylesheets JSON

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#4094]
To test different JSON styles

https://map.geo.admin.ch?style_url=https://pathtomystyle.json&layers=ch.meteoschweiz.messdaten-lufttemperatur

This could be part of the accpetance infra (Int) but not production and would enable the customer to fiddel around with his json easiert than in https://codepen.io/geoadmin/pen/ZWzXgv?editors=0010 

cc @loicgasser @mariokeusen

**Comment by gjn** [comment]
+1 from me.

We will need something similar for vector tiles as well, once we are there. We need to enable people to easily style their stuff themselfes.

We also e.g. use case for data presentations per  commune or canton, etc.

**Comment by oterral** [comment]
Fixed
