### ISSUE TITLE
IE : stationboard not actualized after reload

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#4098]
"
Zum Beispiel folgender Link:
https://map.geo.admin.ch/?lang=de&topic=ech&showTooltip=true&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.bav.haltestellen-oev,ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.swisstopo.swisstlm3d-wanderwege&layers_visibility=true,false,false,false&layers_timestamp=,18641231,,&E=2601749.00&N=1205099.00&zoom=8

Die Abfahrtszeiten werden bei neu laden resp. F5 nicht aktualisiert. siehe PC zeit 10.35 vs. Abfahrtszeit 10.40 und direkt nachfolgend verbleibende 27min Zeit bis zur Abfahrt. Das stimmt definitiv nicht. ev proxyproblem, cache scheint es nicht zu sein denn in private mode von ie gleiches verhalten.... proxy anpassen oder autoreload der Website alle 30sek.
auf dem Androidmobile mit Google Ghrome funktioniert es übrigens problemlos.
"

customer feedback WG: INC000008887925

**Comment by loicgasser** [comment]
@rebert have you had the chance to test it? On chrome desktop it seems to work well.

**Comment by oterral** [comment]
Porbably IE cache the request like it does for https://github.com/geoadmin/mf-geoadmin3/issues/3937

**Comment by rebert** [comment]
On my workplace it works with:
- Firefox
- Chrome
- IE Edge
- Safari iPhone

But IE 11 did not update the tooltip

**Comment by oterral** [comment]
@davidoesch  Edge or IE 11?

**Comment by oterral** [comment]
Just saw @rebert comment so if it's IE 11 it's the same problem as #3937

so do the same fix : https://github.com/geoadmin/mf-geoadmin3/pull/3939/files

**Comment by rebert** [comment]
Fixed with https://github.com/geoadmin/mf-chsdi3/pull/2781
