### ISSUE TITLE
Stationboard:  Wrong destinations

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#4101]
Station Board für einzelne Haltestellen eine falsche Destination angezeigt wird. 
Betroffen sind (mindestens) PAG-Haltestellen im Raum Frienisberg und Interlaken, sowie die Linien 102, 104 und 106, siehe Bilder unten.Ich habe einen Hinweis erhalten, dass im Station Board für einzelne Haltestellen eine falsche Destination angezeigt wird. 

zb
https://s.geo.admin.ch/780b519d6d

![image](https://user-images.githubusercontent.com/4577727/34772092-2a7ad92c-f607-11e7-9c18-c74a447f0ded.png)

**Comment by rebert** [comment]
This issue is related to the OpenTrans API. When we request:

<?xml version="1.0" encoding="UTF-8"?>
<Trias version="1.1" xmlns="http://www.vdv.de/trias" xmlns:siri="http://www.siri.org.uk/siri" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <ServiceRequest>
        <siri:RequestTimestamp>2018-01-10T13:23:11</siri:RequestTimestamp>
        <siri:RequestorRef>EPSa</siri:RequestorRef>
        <RequestPayload>
            <StopEventRequest>
                <Location>
                    <LocationRef>
                        <StopPointRef>8587328</StopPointRef>
                    </LocationRef>
                    <DepArrTime>2018-01-10T13:23:11</DepArrTime>
                </Location>
                <Params>
                    <NumberOfResults>5</NumberOfResults>
                    <StopEventType>departure</StopEventType>
                    <IncludePreviousCalls>false</IncludePreviousCalls>
                    <IncludeOnwardCalls>true</IncludeOnwardCalls>
                    <IncludeRealtimeData>true</IncludeRealtimeData>
                </Params>
            </StopEventRequest>
        </RequestPayload>
    </ServiceRequest>
</Trias>


We get:
<?xml version="1.0" encoding="UTF-8"?>
<Trias xmlns="http://www.vdv.de/trias" version="1.1">
<ServiceDelivery>
    <ResponseTimestamp xmlns="http://www.siri.org.uk/siri">2018-01-10T12:17:30Z</ResponseTimestamp>
    <ProducerRef xmlns="http://www.siri.org.uk/siri">EFAController10.2.6.30-WIN-G0NJHFUK71P</ProducerRef>
    <Status xmlns="http://www.siri.org.uk/siri">true</Status>
    <MoreData>false</MoreData>
    <Language>de</Language>
    <DeliveryPayload>
        <StopEventResponse>
            <StopEventResult>
                <ResultId>ID-AD25BD19-C581-4FCA-8E74-8664A7BB4AAC</ResultId>
                <StopEvent>
                    <ThisCall>
                        <CallAtStop>
                            <StopPointRef>8587328</StopPointRef>
                            <StopPointName>
                                <Text>Säriswil, Dorf</Text>
                                <Language>de</Language>
                            </StopPointName>
                            <ServiceDeparture>
                                <TimetabledTime>2018-01-10T12:25:00Z</TimetabledTime>
                            </ServiceDeparture>
                            <StopSeqNumber>16</StopSeqNumber>
                        </CallAtStop>
                    </ThisCall>
                    <OnwardCall>
                        <CallAtStop>
                            <StopPointRef>8571369</StopPointRef>
                            <StopPointName>
                                <Text>Säriswil, Wendeplatz</Text>
                                <Language>de</Language>
                            </StopPointName>
                            <ServiceArrival>
                                <TimetabledTime>2018-01-10T12:28:00Z</TimetabledTime>
                            </ServiceArrival>
                            <StopSeqNumber>2</StopSeqNumber>
                        </CallAtStop>
                    </OnwardCall>
                    <Service>
                        <OperatingDayRef>2018-01-10</OperatingDayRef>
                        <JourneyRef>odp:06102::R:j18:10229:10229</JourneyRef>
                        <LineRef>odp:06102::R</LineRef>
                        <DirectionRef>return</DirectionRef>
                        <Mode>
                            <PtMode>bus</PtMode>
                            <BusSubmode>regionalBus</BusSubmode>
                            <Name>
                                <Text>Bus</Text>
                                <Language>de</Language>
                            </Name>
                        </Mode>
                        <PublishedLineName>
                            <Text>102</Text>
                            <Language>de</Language>
                        </PublishedLineName>
                        <OperatorRef>odp:801</OperatorRef>
                        <Attribute>
                            <Text>
                                <Text>0926</Text>
                                <Language>de</Language>
                            </Text>
                            <Code>12524385</Code>
                            <Mandatory>false</Mandatory>
                        </Attribute>
                        <Attribute>
                            <Text>
                                <Text>0702</Text>
                                <Language>de</Language>
                            </Text>
                            <Code>12524386</Code>
                            <Mandatory>false</Mandatory>
                        </Attribute>
                        <OriginStopPointRef>8507785</OriginStopPointRef>
                        <OriginText>
                            <Text>Interlaken West, Bahnhof</Text>
                            <Language>de</Language>
                        </OriginText>
                        <DestinationStopPointRef>8571369</DestinationStopPointRef>
                        <DestinationText>
                            <Text>Niederried b.I'laken, Wendepl</Text>
                            <Language>de</Language>
                        </DestinationText>
                    </Service>
                </StopEvent>
            </StopEventResult>
            <StopEventResult>
                <ResultId>ID-C8C8BC06-28C0-48CD-9488-FEF85E0CBCC6</ResultId>
                <StopEvent>
                    <ThisCall>
                        <CallAtStop>
                            <StopPointRef>8587328</StopPointRef>
                            <StopPointName>
                                <Text>Säriswil, Dorf</Text>
                                <Language>de</Language>
                            </StopPointName>
                            <ServiceDeparture>
                                <TimetabledTime>2018-01-10T12:30:00Z</TimetabledTime>
                            </ServiceDeparture>
                            <StopSeqNumber>2</StopSeqNumber>
                        </CallAtStop>
                    </ThisCall>
                    <OnwardCall>
                        <CallAtStop>
                            <StopPointRef>8571368</StopPointRef>
                            <StopPointName>
                                <Text>Säriswil, Schulhaus</Text>
                                <Language>de</Language>
                            </StopPointName>
                            <ServiceArrival>
                                <TimetabledTime>2018-01-10T12:31:00Z</TimetabledTime>
                            </ServiceArrival>
                            <ServiceDeparture>
                                <TimetabledTime>2018-01-10T12:31:00Z</TimetabledTime>
                            </ServiceDeparture>
                            <StopSeqNumber>2</StopSeqNumber>
                        </CallAtStop>
                    </OnwardCall>
                    <OnwardCall>
                        <CallAtStop>
                            <StopPointRef>8571367</StopPointRef>
                            <StopPointName>
                                <Text>Säriswil, Birchi</Text>
                                <Language>de</Language>
                            </StopPointName>
                            <ServiceArrival>
                                <TimetabledTime>2018-01-10T12:32:00Z</TimetabledTime>
                            </ServiceArrival>
                            <ServiceDeparture>
                                <TimetabledTime>2018-01-10T12:32:00Z</TimetabledTime>
                            </ServiceDeparture>
                            <StopSeqNumber>3</StopSeqNumber>
                        </CallAtStop>
                    </OnwardCall>
                    <OnwardCall>
                        <CallAtStop>
                            <StopPointRef>8571366</StopPointRef>
                            <StopPointName>
                                <Text>Möriswil, Abzw.</Text>
                                <Language>de</Language>
                            </StopPointName>
                            <ServiceArrival>
                                <TimetabledTime>2018-01-10T12:33:00Z</TimetabledTime>
                            </ServiceArrival>
                            <ServiceDeparture>
                                <TimetabledTime>2018-01-10T12:33:00Z</TimetabledTime>
                            </ServiceDeparture>
                            <StopSeqNumber>4</StopSeqNumber>
                        </CallAtStop>
                    </OnwardCall>
                    <OnwardCall>
                        <CallAtStop>
                            <StopPointRef>8571365</StopPointRef>
                            <StopPointName>
                                <Text>Uettligen, Schüpfenried</Text>
                                <Language>de</Language>
                            </StopPointName>
                            <ServiceArrival>
                                <TimetabledTime>2018-01-10T12:34:00Z</TimetabledTime>
                            </ServiceArrival>
                            <ServiceDeparture>
                                <TimetabledTime>2018-01-10T12:34:00Z</TimetabledTime>
                            </ServiceDeparture>
                            <StopSeqNumber>5</StopSeqNumber>
                        </CallAtStop>
                    </OnwardCall>
                    <OnwardCall>
                        <CallAtStop>
                            <StopPointRef>8571364</StopPointRef>
                            <StopPointName>
                                <Text>Uettligen, Dorf</Text>
                                <Language>de</Language>
                            </StopPointName>
                            <ServiceArrival>
                                <TimetabledTime>2018-01-10T12:37:00Z</TimetabledTime>
                            </ServiceArrival>
                            <ServiceDeparture>
                                <TimetabledTime>2018-01-10T12:37:00Z</TimetabledTime>
                            </ServiceDeparture>
                            <StopSeqNumber>6</StopSeqNumber>
                        </CallAtStop>
                    </OnwardCall>
                    <OnwardCall>
                        <CallAtStop>
                            <StopPointRef>8571362</StopPointRef>
                            <StopPointName>
                                <Text>Oberdettigen</Text>
                                <Language>de</Language>
                            </StopPointName>
                            <ServiceArrival>
                                <TimetabledTime>2018-01-10T12:39:00Z</TimetabledTime>
                            </ServiceArrival>
                            <ServiceDeparture>
                                <TimetabledTime>2018-01-10T12:39:00Z</TimetabledTime>
                            </ServiceDeparture>
                            <StopSeqNumber>7</StopSeqNumber>
                        </CallAtStop>
                    </OnwardCall>
                    <OnwardCall>
                        <CallAtStop>
                            <StopPointRef>8571361</StopPointRef>
                            <StopPointName>
                                <Text>Thalmatt</Text>
                                <Language>de</Language>
                            </StopPointName>
                            <ServiceArrival>
                                <TimetabledTime>2018-01-10T12:41:00Z</TimetabledTime>
                            </ServiceArrival>
                            <ServiceDeparture>
                                <TimetabledTime>2018-01-10T12:41:00Z</TimetabledTime>
                            </ServiceDeparture>
                            <StopSeqNumber>8</StopSeqNumber>
                        </CallAtStop>
                    </OnwardCall>
                    <OnwardCall>
                        <CallAtStop>
                            <StopPointRef>8571360</StopPointRef>
                            <StopPointName>
                                <Text>Halenbrücke</Text>
                                <Language>de</Language>
                            </StopPointName>
                            <ServiceArrival>
                                <TimetabledTime>2018-01-10T12:42:00Z</TimetabledTime>
                            </ServiceArrival>
                            <ServiceDeparture>
                                <TimetabledTime>2018-01-10T12:42:00Z</TimetabledTime>
                            </ServiceDeparture>
                            <StopSeqNumber>9</StopSeqNumber>
                        </CallAtStop>
                    </OnwardCall>
                    <OnwardCall>
                        <CallAtStop>
                            <StopPointRef>8590075</StopPointRef>
                            <StopPointName>
                                <Text>Bern, Neufeld P+R</Text>
                                <Language>de</Language>
                            </StopPointName>
                            <ServiceArrival>
                                <TimetabledTime>2018-01-10T12:46:00Z</TimetabledTime>
                            </ServiceArrival>
                            <ServiceDeparture>
                                <TimetabledTime>2018-01-10T12:46:00Z</TimetabledTime>
                            </ServiceDeparture>
                            <StopSeqNumber>10</StopSeqNumber>
                        </CallAtStop>
                    </OnwardCall>
                    <OnwardCall>
                        <CallAtStop>
                            <StopPointRef>8583222</StopPointRef>
                            <StopPointName>
                                <Text>Bern, Lindenhofspital</Text>
                                <Language>de</Language>
                            </StopPointName>
                            <ServiceArrival>
                                <TimetabledTime>2018-01-10T12:47:00Z</TimetabledTime>
                            </ServiceArrival>
                            <ServiceDeparture>
                                <TimetabledTime>2018-01-10T12:47:00Z</TimetabledTime>
                            </ServiceDeparture>
                            <StopSeqNumber>11</StopSeqNumber>
                        </CallAtStop>
                    </OnwardCall>
                    <OnwardCall>
                        <CallAtStop>
                            <StopPointRef>8590038</StopPointRef>
                            <StopPointName>
                                <Text>Bern, Unitobler</Text>
                                <Language>de</Language>
                            </StopPointName>
                            <ServiceArrival>
                                <TimetabledTime>2018-01-10T12:49:00Z</TimetabledTime>
                            </ServiceArrival>
                            <ServiceDeparture>
                                <TimetabledTime>2018-01-10T12:49:00Z</TimetabledTime>
                            </ServiceDeparture>
                            <StopSeqNumber>12</StopSeqNumber>
                        </CallAtStop>
                    </OnwardCall>
                    <OnwardCall>
                        <CallAtStop>
                            <StopPointRef>8571358</StopPointRef>
                            <StopPointName>
                                <Text>Bern, Mittelstrasse</Text>
                                <Language>de</Language>
                            </StopPointName>
                            <ServiceArrival>
                                <TimetabledTime>2018-01-10T12:50:00Z</TimetabledTime>
                            </ServiceArrival>
                            <ServiceDeparture>
                                <TimetabledTime>2018-01-10T12:50:00Z</TimetabledTime>
                            </ServiceDeparture>
                            <StopSeqNumber>13</StopSeqNumber>
                        </CallAtStop>
                    </OnwardCall>
                    <OnwardCall>
                        <CallAtStop>
                            <StopPointRef>8579748</StopPointRef>
                            <StopPointName>
                                <Text>Bern, Obergericht</Text>
                                <Language>de</Language>
                            </StopPointName>
                            <ServiceArrival>
                                <TimetabledTime>2018-01-10T12:55:00Z</TimetabledTime>
                            </ServiceArrival>
                            <ServiceDeparture>
                                <TimetabledTime>2018-01-10T12:55:00Z</TimetabledTime>
                            </ServiceDeparture>
                            <StopSeqNumber>14</StopSeqNumber>
                        </CallAtStop>
                    </OnwardCall>
                    <OnwardCall>
                        <CallAtStop>
                            <StopPointRef>8507785</StopPointRef>
                            <StopPointName>
                                <Text>Bern, Hauptbahnhof</Text>
                                <Language>de</Language>
                            </StopPointName>
                            <PlannedBay>
                                <Text>4</Text>
                                <Language>de</Language>
                            </PlannedBay>
                            <ServiceArrival>
                                <TimetabledTime>2018-01-10T12:58:00Z</TimetabledTime>
                            </ServiceArrival>
                            <StopSeqNumber>15</StopSeqNumber>
                        </CallAtStop>
                    </OnwardCall>
                    <Service>
                        <OperatingDayRef>2018-01-10</OperatingDayRef>
                        <JourneyRef>odp:06102::R:j18:10234:10234</JourneyRef>
                        <LineRef>odp:06102::R</LineRef>
                        <DirectionRef>return</DirectionRef>
                        <Mode>
                            <PtMode>bus</PtMode>
                            <BusSubmode>regionalBus</BusSubmode>
                            <Name>
                                <Text>Bus</Text>
                                <Language>de</Language>
                            </Name>
                        </Mode>
                        <PublishedLineName>
                            <Text>102</Text>
                            <Language>de</Language>
                        </PublishedLineName>
                        <OperatorRef>odp:801</OperatorRef>
                        <Attribute>
                            <Text>
                                <Text>0926</Text>
                                <Language>de</Language>
                            </Text>
                            <Code>12524387</Code>
                            <Mandatory>false</Mandatory>
                        </Attribute>
                        <Attribute>
                            <Text>
                                <Text>0702</Text>
                                <Language>de</Language>
                            </Text>
                            <Code>12524388</Code>
                            <Mandatory>false</Mandatory>
                        </Attribute>
                        <OriginStopPointRef>8571369</OriginStopPointRef>
                        <OriginText>
                            <Text>Niederried b.I'laken, Wendepl</Text>
                            <Language>de</Language>
                        </OriginText>
                        <DestinationStopPointRef>8507785</DestinationStopPointRef>
                        <DestinationText>
                            <Text>Interlaken West, Bahnhof</Text>
                            <Language>de</Language>
                        </DestinationText>
                    </Service>
                </StopEvent>
            </StopEventResult>
            <StopEventResult>
                <ResultId>ID-C25CC925-C138-4B54-9187-FB43FF396FE5</ResultId>
                <StopEvent>
                    <ThisCall>
                        <CallAtStop>
                            <StopPointRef>8587328</StopPointRef>
                            <StopPointName>
                                <Text>Säriswil, Dorf</Text>
                                <Language>de</Language>
                            </StopPointName>
                            <ServiceDeparture>
                                <TimetabledTime>2018-01-10T12:55:00Z</TimetabledTime>
                            </ServiceDeparture>
                            <StopSeqNumber>16</StopSeqNumber>
                        </CallAtStop>
                    </ThisCall>
                    <OnwardCall>
                        <CallAtStop>
                            <StopPointRef>8571369</StopPointRef>
                            <StopPointName>
                                <Text>Säriswil, Wendeplatz</Text>
                                <Language>de</Language>
                            </StopPointName>
                            <ServiceArrival>
                                <TimetabledTime>2018-01-10T12:58:00Z</TimetabledTime>
                            </ServiceArrival>
                            <StopSeqNumber>2</StopSeqNumber>
                        </CallAtStop>
                    </OnwardCall>
                    <Service>
                        <OperatingDayRef>2018-01-10</OperatingDayRef>
                        <JourneyRef>odp:06102::R:j18:10231:10231</JourneyRef>
                        <LineRef>odp:06102::R</LineRef>
                        <DirectionRef>return</DirectionRef>
                        <Mode>
                            <PtMode>bus</PtMode>
                            <BusSubmode>regionalBus</BusSubmode>
                            <Name>
                                <Text>Bus</Text>
                                <Language>de</Language>
                            </Name>
                        </Mode>
                        <PublishedLineName>
                            <Text>102</Text>
                            <Language>de</Language>
                        </PublishedLineName>
                        <OperatorRef>odp:801</OperatorRef>
                        <Attribute>
                            <Text>
                                <Text>0702</Text>
                                <Language>de</Language>
                            </Text>
                            <Code>12524389</Code>
                            <Mandatory>false</Mandatory>
                        </Attribute>
                        <OriginStopPointRef>8507785</OriginStopPointRef>
                        <OriginText>
                            <Text>Bern, Hauptbahnhof</Text>
                            <Language>de</Language>
                        </OriginText>
                        <DestinationStopPointRef>8571369</DestinationStopPointRef>
                        <DestinationText>
                            <Text>Säriswil, Wendeplatz</Text>
                            <Language>de</Language>
                        </DestinationText>
                    </Service>
                </StopEvent>
            </StopEventResult>
            <StopEventResult>
                <ResultId>ID-21365129-A373-482B-9B2B-32E733839459</ResultId>
                <StopEvent>
                    <ThisCall>
                        <CallAtStop>
                            <StopPointRef>8587328</StopPointRef>
                            <StopPointName>
                                <Text>Säriswil, Dorf</Text>
                                <Language>de</Language>
                            </StopPointName>
                            <ServiceDeparture>
                                <TimetabledTime>2018-01-10T13:00:00Z</TimetabledTime>
                            </ServiceDeparture>
                            <StopSeqNumber>2</StopSeqNumber>
                        </CallAtStop>
                    </ThisCall>
                    <OnwardCall>
                        <CallAtStop>
                            <StopPointRef>8571368</StopPointRef>
                            <StopPointName>
                                <Text>Säriswil, Schulhaus</Text>
                                <Language>de</Language>
                            </StopPointName>
                            <ServiceArrival>
                                <TimetabledTime>2018-01-10T13:01:00Z</TimetabledTime>
                            </ServiceArrival>
                            <ServiceDeparture>
                                <TimetabledTime>2018-01-10T13:01:00Z</TimetabledTime>
                            </ServiceDeparture>
                            <StopSeqNumber>2</StopSeqNumber>
                        </CallAtStop>
                    </OnwardCall>
                    <OnwardCall>
                        <CallAtStop>
                            <StopPointRef>8571367</StopPointRef>
                            <StopPointName>
                                <Text>Säriswil, Birchi</Text>
                                <Language>de</Language>
                            </StopPointName>
                            <ServiceArrival>
                                <TimetabledTime>2018-01-10T13:02:00Z</TimetabledTime>
                            </ServiceArrival>
                            <ServiceDeparture>
                                <TimetabledTime>2018-01-10T13:02:00Z</TimetabledTime>
                            </ServiceDeparture>
                            <StopSeqNumber>3</StopSeqNumber>
                        </CallAtStop>
                    </OnwardCall>
                    <OnwardCall>
                        <CallAtStop>
                            <StopPointRef>8571366</StopPointRef>
                            <StopPointName>
                                <Text>Möriswil, Abzw.</Text>
                                <Language>de</Language>
                            </StopPointName>
                            <ServiceArrival>
                                <TimetabledTime>2018-01-10T13:03:00Z</TimetabledTime>
                            </ServiceArrival>
                            <ServiceDeparture>
                                <TimetabledTime>2018-01-10T13:03:00Z</TimetabledTime>
                            </ServiceDeparture>
                            <StopSeqNumber>4</StopSeqNumber>
                        </CallAtStop>
                    </OnwardCall>
                    <OnwardCall>
                        <CallAtStop>
                            <StopPointRef>8571365</StopPointRef>
                            <StopPointName>
                                <Text>Uettligen, Schüpfenried</Text>
                                <Language>de</Language>
                            </StopPointName>
                            <ServiceArrival>
                                <TimetabledTime>2018-01-10T13:04:00Z</TimetabledTime>
                            </ServiceArrival>
                            <ServiceDeparture>
                                <TimetabledTime>2018-01-10T13:04:00Z</TimetabledTime>
                            </ServiceDeparture>
                            <StopSeqNumber>5</StopSeqNumber>
                        </CallAtStop>
                    </OnwardCall>
                    <OnwardCall>
                        <CallAtStop>
                            <StopPointRef>8571364</StopPointRef>
                            <StopPointName>
                                <Text>Uettligen, Dorf</Text>
                                <Language>de</Language>
                            </StopPointName>
                            <ServiceArrival>
                                <TimetabledTime>2018-01-10T13:07:00Z</TimetabledTime>
                            </ServiceArrival>
                            <ServiceDeparture>
                                <TimetabledTime>2018-01-10T13:07:00Z</TimetabledTime>
                            </ServiceDeparture>
                            <StopSeqNumber>6</StopSeqNumber>
                        </CallAtStop>
                    </OnwardCall>
                    <OnwardCall>
                        <CallAtStop>
                            <StopPointRef>8571362</StopPointRef>
                            <StopPointName>
                                <Text>Oberdettigen</Text>
                                <Language>de</Language>
                            </StopPointName>
                            <ServiceArrival>
                                <TimetabledTime>2018-01-10T13:09:00Z</TimetabledTime>
                            </ServiceArrival>
                            <ServiceDeparture>
                                <TimetabledTime>2018-01-10T13:09:00Z</TimetabledTime>
                            </ServiceDeparture>
                            <StopSeqNumber>7</StopSeqNumber>
                        </CallAtStop>
                    </OnwardCall>
                    <OnwardCall>
                        <CallAtStop>
                            <StopPointRef>8571361</StopPointRef>
                            <StopPointName>
                                <Text>Thalmatt</Text>
                                <Language>de</Language>
                            </StopPointName>
                            <ServiceArrival>
                                <TimetabledTime>2018-01-10T13:11:00Z</TimetabledTime>
                            </ServiceArrival>
                            <ServiceDeparture>
                                <TimetabledTime>2018-01-10T13:11:00Z</TimetabledTime>
                            </ServiceDeparture>
                            <StopSeqNumber>8</StopSeqNumber>
                        </CallAtStop>
                    </OnwardCall>
                    <OnwardCall>
                        <CallAtStop>
                            <StopPointRef>8571360</StopPointRef>
                            <StopPointName>
                                <Text>Halenbrücke</Text>
                                <Language>de</Language>
                            </StopPointName>
                            <ServiceArrival>
                                <TimetabledTime>2018-01-10T13:12:00Z</TimetabledTime>
                            </ServiceArrival>
                            <ServiceDeparture>
                                <TimetabledTime>2018-01-10T13:12:00Z</TimetabledTime>
                            </ServiceDeparture>
                            <StopSeqNumber>9</StopSeqNumber>
                        </CallAtStop>
                    </OnwardCall>
                    <OnwardCall>
                        <CallAtStop>
                            <StopPointRef>8590075</StopPointRef>
                            <StopPointName>
                                <Text>Bern, Neufeld P+R</Text>
                                <Language>de</Language>
                            </StopPointName>
                            <ServiceArrival>
                                <TimetabledTime>2018-01-10T13:16:00Z</TimetabledTime>
                            </ServiceArrival>
                            <ServiceDeparture>
                                <TimetabledTime>2018-01-10T13:16:00Z</TimetabledTime>
                            </ServiceDeparture>
                            <StopSeqNumber>10</StopSeqNumber>
                        </CallAtStop>
                    </OnwardCall>
                    <OnwardCall>
                        <CallAtStop>
                            <StopPointRef>8583222</StopPointRef>
                            <StopPointName>
                                <Text>Bern, Lindenhofspital</Text>
                                <Language>de</Language>
                            </StopPointName>
                            <ServiceArrival>
                                <TimetabledTime>2018-01-10T13:17:00Z</TimetabledTime>
                            </ServiceArrival>
                            <ServiceDeparture>
                                <TimetabledTime>2018-01-10T13:17:00Z</TimetabledTime>
                            </ServiceDeparture>
                            <StopSeqNumber>11</StopSeqNumber>
                        </CallAtStop>
                    </OnwardCall>
                    <OnwardCall>
                        <CallAtStop>
                            <StopPointRef>8590038</StopPointRef>
                            <StopPointName>
                                <Text>Bern, Unitobler</Text>
                                <Language>de</Language>
                            </StopPointName>
                            <ServiceArrival>
                                <TimetabledTime>2018-01-10T13:19:00Z</TimetabledTime>
                            </ServiceArrival>
                            <ServiceDeparture>
                                <TimetabledTime>2018-01-10T13:19:00Z</TimetabledTime>
                            </ServiceDeparture>
                            <StopSeqNumber>12</StopSeqNumber>
                        </CallAtStop>
                    </OnwardCall>
                    <OnwardCall>
                        <CallAtStop>
                            <StopPointRef>8571358</StopPointRef>
                            <StopPointName>
                                <Text>Bern, Mittelstrasse</Text>
                                <Language>de</Language>
                            </StopPointName>
                            <ServiceArrival>
                                <TimetabledTime>2018-01-10T13:20:00Z</TimetabledTime>
                            </ServiceArrival>
                            <ServiceDeparture>
                                <TimetabledTime>2018-01-10T13:20:00Z</TimetabledTime>
                            </ServiceDeparture>
                            <StopSeqNumber>13</StopSeqNumber>
                        </CallAtStop>
                    </OnwardCall>
                    <OnwardCall>
                        <CallAtStop>
                            <StopPointRef>8579748</StopPointRef>
                            <StopPointName>
                                <Text>Bern, Obergericht</Text>
                                <Language>de</Language>
                            </StopPointName>
                            <ServiceArrival>
                                <TimetabledTime>2018-01-10T13:25:00Z</TimetabledTime>
                            </ServiceArrival>
                            <ServiceDeparture>
                                <TimetabledTime>2018-01-10T13:25:00Z</TimetabledTime>
                            </ServiceDeparture>
                            <StopSeqNumber>14</StopSeqNumber>
                        </CallAtStop>
                    </OnwardCall>
                    <OnwardCall>
                        <CallAtStop>
                            <StopPointRef>8507785</StopPointRef>
                            <StopPointName>
                                <Text>Bern, Hauptbahnhof</Text>
                                <Language>de</Language>
                            </StopPointName>
                            <PlannedBay>
                                <Text>4</Text>
                                <Language>de</Language>
                            </PlannedBay>
                            <ServiceArrival>
                                <TimetabledTime>2018-01-10T13:28:00Z</TimetabledTime>
                            </ServiceArrival>
                            <StopSeqNumber>15</StopSeqNumber>
                        </CallAtStop>
                    </OnwardCall>
                    <Service>
                        <OperatingDayRef>2018-01-10</OperatingDayRef>
                        <JourneyRef>odp:06102::R:j18:10236:10236</JourneyRef>
                        <LineRef>odp:06102::R</LineRef>
                        <DirectionRef>return</DirectionRef>
                        <Mode>
                            <PtMode>bus</PtMode>
                            <BusSubmode>regionalBus</BusSubmode>
                            <Name>
                                <Text>Bus</Text>
                                <Language>de</Language>
                            </Name>
                        </Mode>
                        <PublishedLineName>
                            <Text>102</Text>
                            <Language>de</Language>
                        </PublishedLineName>
                        <OperatorRef>odp:801</OperatorRef>
                        <Attribute>
                            <Text>
                                <Text>0702</Text>
                                <Language>de</Language>
                            </Text>
                            <Code>12524390</Code>
                            <Mandatory>false</Mandatory>
                        </Attribute>
                        <OriginStopPointRef>8571369</OriginStopPointRef>
                        <OriginText>
                            <Text>Säriswil, Wendeplatz</Text>
                            <Language>de</Language>
                        </OriginText>
                        <DestinationStopPointRef>8507785</DestinationStopPointRef>
                        <DestinationText>
                            <Text>Bern, Hauptbahnhof</Text>
                            <Language>de</Language>
                        </DestinationText>
                    </Service>
                </StopEvent>
            </StopEventResult>
            <StopEventResult>
                <ResultId>ID-8E0DDA78-8BFC-4A5F-8F26-E523CBE16F4E</ResultId>
                <StopEvent>
                    <ThisCall>
                        <CallAtStop>
                            <StopPointRef>8587328</StopPointRef>
                            <StopPointName>
                                <Text>Säriswil, Dorf</Text>
                                <Language>de</Language>
                            </StopPointName>
                            <ServiceDeparture>
                                <TimetabledTime>2018-01-10T13:25:00Z</TimetabledTime>
                            </ServiceDeparture>
                            <StopSeqNumber>16</StopSeqNumber>
                        </CallAtStop>
                    </ThisCall>
                    <OnwardCall>
                        <CallAtStop>
                            <StopPointRef>8571369</StopPointRef>
                            <StopPointName>
                                <Text>Säriswil, Wendeplatz</Text>
                                <Language>de</Language>
                            </StopPointName>
                            <ServiceArrival>
                                <TimetabledTime>2018-01-10T13:28:00Z</TimetabledTime>
                            </ServiceArrival>
                            <StopSeqNumber>2</StopSeqNumber>
                        </CallAtStop>
                    </OnwardCall>
                    <Service>
                        <OperatingDayRef>2018-01-10</OperatingDayRef>
                        <JourneyRef>odp:06102::R:j18:10233:10233</JourneyRef>
                        <LineRef>odp:06102::R</LineRef>
                        <DirectionRef>return</DirectionRef>
                        <Mode>
                            <PtMode>bus</PtMode>
                            <BusSubmode>regionalBus</BusSubmode>
                            <Name>
                                <Text>Bus</Text>
                                <Language>de</Language>
                            </Name>
                        </Mode>
                        <PublishedLineName>
                            <Text>102</Text>
                            <Language>de</Language>
                        </PublishedLineName>
                        <OperatorRef>odp:801</OperatorRef>
                        <Attribute>
                            <Text>
                                <Text>0926</Text>
                                <Language>de</Language>
                            </Text>
                            <Code>12524391</Code>
                            <Mandatory>false</Mandatory>
                        </Attribute>
                        <Attribute>
                            <Text>
                                <Text>0702</Text>
                                <Language>de</Language>
                            </Text>
                            <Code>12524392</Code>
                            <Mandatory>false</Mandatory>
                        </Attribute>
                        <OriginStopPointRef>8507785</OriginStopPointRef>
                        <OriginText>
                            <Text>Interlaken West, Bahnhof</Text>
                            <Language>de</Language>
                        </OriginText>
                        <DestinationStopPointRef>8571369</DestinationStopPointRef>
                        <DestinationText>
                            <Text>Ringgenberg, Säge</Text>
                            <Language>de</Language>
                        </DestinationText>
                    </Service>
                </StopEvent>
            </StopEventResult>
        </StopEventResponse>
    </DeliveryPayload>
</ServiceDelivery>
</Trias>

**Comment by rebert** [comment]
A classical GIGO

**Comment by davidoesch** [comment]
wont fix: confirmed issue  by at opentransportdata.swiss api. they are working on it
