### ISSUE TITLE
Print:  White border around copyright text

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#4102]
in the PDF, the copyright text like (C)swisstopo needs white border around the letters, since on black bg tetxt not visible

**Comment by procrastinatio** [comment]
Hm, the white box will not fit to the text so it is ugly. The only way is to put the copyright text outside, as before, or at least it left.

![ugly](https://user-images.githubusercontent.com/1236739/35669993-4e751d6a-0737-11e8-8cbc-b6fa58325274.png)

**Comment by davidoesch** [comment]
in this case: try to increase the white border around the letters?

**Comment by procrastinatio** [comment]
There is no `halo` in `mapfish-print v2` neither for text nor for feature label.
I am trying various hack supperposing a black font on the bold equivalent as white to simulate a `halo`with with no acceptable result for now (bold font are wider...).
The easier would be to write the copyright under the disclaimer.

**Comment by procrastinatio** [comment]
Really hard to make better:
![hack](https://user-images.githubusercontent.com/1236739/35734098-36415cba-0820-11e8-87db-7cbf5a0fe39b.png)

**Comment by davidoesch** [comment]
Under the disclaimer:
you are right  and since eg https://map.wanderland.ch/?lang=en&bgLayer=pk&resolution=20&season=summer&E=2641020&N=1183120 has it on the side. 
is as well not on map anymore (the law ?)

give it a try 
- [  ]  put the disclaimer 1.5 lines down
- [  ] add directly under the map the copyright (same line now disclaimer right bound)
![image](https://user-images.githubusercontent.com/4577727/35734131-551b3cdc-0820-11e8-9a7c-eac95765d92f.png)

**Comment by procrastinatio** [comment]
[test link (a3, a4, landscape, portrait)](https://mf-chsdi3.dev.bgdi.ch/shorten/7886e34661)

**Comment by davidoesch** [comment]
Perfect simple solution. can you add a white space after each entry ?
currently
(c)swisstopo,www.procastrinatio.org

should be
(c)swisstopo, www.procastrinatio.org

(i'm picky)
