### ISSUE TITLE
Print:  Time is wrong in PDF

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#4104]
ther eis a  delta of one hour between the  TIME stated in the PDF and actual local printing time

**Comment by procrastinatio** [comment]
Not if you are in London! 
The print server currently does not know the local time:
* Print in UT (easy)
* map.geo.admin.ch send the time or timezone to the print server.

**Comment by davidoesch** [comment]
Easy Solution : add UTC at the End.
