### ISSUE TITLE
3d: Print to PDF

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#4106]
Print 3d tp PDF via png

https://www.businesslocationcenter.de/wab/maps/main/?startingmap=cesium&lang=en&cameraPosition=13.37149%2C52.51298%2C572.34234&groundPosition=13.37831%2C52.51667%2C34.50305&distance=819.64&pitch=-41.01&heading=48.43&roll=0.19 

![image](https://user-images.githubusercontent.com/4577727/34878129-548df214-f7a9-11e7-8b94-9332232ca49c.png)

**Comment by oterral** [comment]
Easy to do on modern browser for webgl. But not for canvas when we display external data.

**Comment by oterral** [comment]
MAy be if we use the proxy for all external layers

**Comment by procrastinatio** [comment]
See https://github.com/geoadmin/mf-geoadmin3/pull/4205

**Comment by davidoesch** [comment]
If we start at PNG support in the print we will also need in 2D. What is the effort to st ick to PDF as well in 3d. We could then use the existing menu. And later add 3d printing

**Comment by procrastinatio** [comment]
The main issue with client-side image generation, we want to fit an image we have no size control on (image a smartphone) in a very well defined PDF (A4, A3). You have to sacrifice resolution or scale.
An interesting option is to render server-side with a headless browser. It works, but headless WebGL is challenging..
..or _ye olde_ `window.print();`


I am currently looking for the next generation "printing" ( https://github.com/procrastinatio/web-map-printing/blob/master/web-map-printing.pdf, still very early stages)

**Comment by oterral** [comment]
@davidoesch  is that ctrl+P not enought for 3d? you can print in pdf with the native print.

**Comment by oterral** [comment]
I close this one since https://github.com/geoadmin/mf-geoadmin3/issues/4286 is more relevant
