### ISSUE TITLE
Hover event on drawing triggers a KML POST

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/mf-geoadmin3#4111]
Steps to reproduce:

1. Open geoadmin and create a drawing
2. Stop drawing and deselect the line
3. Hover on your drawing (only the first time)

Result:
A POST requests is trigger to save the kml (which has already been saved before)

Expected Result:
No POST request is triggered on hover

**Comment by oterral** [comment]
It's not on hover, the kml is saved 2sec after the feature was deselected

**Comment by loicgasser** [comment]
ah lol
