### ISSUE TITLE
AED Defibrillators on map[DATA INT]

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#4121]
A request which could save lives

Situation
AED / Defibrillators locations are aggregated by various initiatives [1]  or even on cantonal level [2]
Making them available on  LK25 PK10 level background as  icons , frequently updated will save live [3] 

Task
- [ ] define andidates for Fachstelle Bund  eg bag.admin.ch
- [ ] via Fachstelle a regular data delivery  eg with [1]
- [ ] put data on map

Action
- [ ] contact SLA  BAG 
- [ ] define zoom dependent appearance (vector tiles RE4 anyone?)

Result:
 Similar to having all public transportation stops on zoomlevel PK10 we do also have icons for AED Defibrillators on map, eg https://s.geo.admin.ch/7844b4a05a  

[1] http://www.herzsicher.ch/aed-standorte/gps-daten-download/?no_cache=1
[2] https://www.firstresponder.be/ 
[3] https://www.srf.ch/news/schweiz/wo-sind-die-lebensrettenden-defibrillatoren

**Comment by davidoesch** [comment]
+1

**Comment by averof** [comment]
It is definitely urgent to set the positions on map. I had  an emergency case where I needed a AED and was not able to locate the next one. It's a pity that in a connected world this live saving tool is not locateble on a map...

**Comment by rebert** [comment]
http://www.herzsicher.ch/fileadmin/files/standortemap.html

**Comment by oterral** [comment]
@davidoesch what is the status of this. It's more data integration stuf than an geoadmin issue . @AFoletti

**Comment by davidoesch** [comment]
it has mmgt attention: it places here so public can comment on it

**Comment by davidoesch** [comment]
@p1d1d1 for big room meeting decision

**Comment by boecklic** [comment]
ping @p1d1d1 : pls add it to big room meeting and track it in jira, will close it here
