### ISSUE TITLE
Update jquery library because of security issue

### ISSUE THREAD

**Issue by pauloamado** [geoadmin/mf-geoadmin3#4124]
We found a potential security vulnerability in a repository which you have been granted security alert access.
 
geoadmin/mf-geoadmin3 
Known moderate severity security vulnerability detected in jquery < 3.0.0 defined in package.json. 
package.json update suggested: jquery ~> 3.0.0.

**Comment by oterral** [comment]
To update jquery to v3 we need to also update bootstrap to v3.3.7

**Comment by oterral** [comment]
It seems bootstrap is already to v3.3.7. So it should be trivial.
