### ISSUE TITLE
Drawing Tool: Add height information in resulting KML file

### ISSUE THREAD

**Issue by gjn** [geoadmin/mf-geoadmin3#4135]
All in the title.

**Comment by gjn** [comment]
@oterral @davidoesch @loicgasser Thoughts?

**Comment by davidoesch** [comment]
you mean the results according to https://help.geo.admin.ch/?id=94&lang=de as Description tag ?

**Comment by oterral** [comment]
I need to check if the <alitudeMode> takes precedence on the z coordinates. If it's the case we could.

Only problem I see is that could increase a lot the use of height service.

**Comment by procrastinatio** [comment]
Hm, now we may use these height data with KML?
But first, we must have a raw mode in `rest/service/profile.json` (without ligne simplification)

**Comment by davidoesch** [comment]
No. Height service can _not_ be used in kml.
License restricted.
