### ISSUE TITLE
Improve: PDF Coords label print

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#4136]
currently coords are hard to read  on printed maps as in
![image](https://user-images.githubusercontent.com/4577727/35609747-d110f75a-065e-11e8-94f8-08fc5d4a0d10.png)

proposal

for coords: use a white backgound box (if possible)

**Comment by AFoletti** [comment]
I'm reassigning this to @alcapat since he already did a lot in term of grid optimization

**Comment by oterral** [comment]
@alcapat an update pls?

**Comment by boecklic** [comment]
wontfix in accordance with @davidoesch
