### ISSUE TITLE
coords differ in footer and pop up

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#4137]
![image](https://user-images.githubusercontent.com/4577727/35609844-5c0ee600-065f-11e8-8703-e5e2a1422018.png)

both coords should be the same

Here a customer feedback

> Ich wollte die Höhe bei CH1903 827246|198554 abfragen. Dazu muss ich im augenblicklichen Zustand Ihrer Webseiten rechts klicken bei 827247|198554. Das habe ich gemacht - siehe Koordinaten-Anzeige in der Fußleiste. Genau diese Koordinaten stehen im Pop-Up-Fenster als CH1903+-Koordinaten, und zwar ganzzahlig. Der Unterschied zu CH1903 beträgt in diesem Teil der Ostschweiz rd. 1 m im RECHTS-Wert, so dass ich meinen Zielpunkt 827246|198554 aus der angezeigten Koordinate 827246.03|198553.82 runden muss. Das stimmt aber so, weil ich anhand der Höhe 2474.5 m die Koordinate mit früheren Ergebnissen - vor der Umstellung auf eine bildschirmunabhängige Koordinaten-Anzeige - vergleichen kann. Damals war es so: CH1903 ausgewählt, 827246|198554 angeklickt, 827246|198554 im Pop-Up-Fenster bekommen, Höhe 2474.5 abgelesen. Wie früher befinde ich mich also in der selben 2-mal-2-Meter-Zelle des Höhenmodells mit dieser, mir bekannten Höhe, und zwar am linken unteren Eck.
>  
> Wie in meinem 1. Schreiben gesagt, ist das eine Kleinigkeit, mit der ich klar komme. Aber nicht jeder Nutzer ist mit Geodäsie vertraut. Außerdem ist auch die Möglichkeit des Vergleichs auf die Dauer nicht sicher, weil diese Zelle bei der nächsten Revision des Modells vielleicht die neue Höhe 2474.3 bekommen könnte. Deshalb wäre es schön, wenn Sie dieses Problem bearbeiten würden. Das heißt, wenn man im Listenfeld der Fußleiste das Datum CH1903 gewählt hat, sollten auch die metrisch ganzzahligen CH1903-Koordinaten daneben in der Fußleiste angezeigt werden (oder man löst stärker auf, z.B. auf halbe Meter) und bei Rechtsklick sollten dieselben ganzzahligen (oder höher aufgelösten) Koordinaten sowie die richtige Höhe im Pop-Up-Fenster kommen.
> Diesen unscharfen Ausdruck "richtig" musste ich nehmen, weil ich nur vermuten kann, dass bei der besagten Umstellung auch das Höhenmodell auf CH1903+ umgestellt wurde. Ich glaube, Sie haben jetzt die 2-Meter-Zellen auf ganzzahlige CH1903+-Koordinaten abgebildet? Dann müsste eine Methode gefunden werden, wie die CH1903-Daten dort eingeklinkt werden, vielleicht durch einfaches Runden. Man könnte auch an eine zusätzliche Kontrolle denken, indem man die 2-Meter-Zellen eindeutig nummeriert und die Zellnummer anzeig

t.

**Comment by gjn** [comment]
Im Context Popup wird der genaue Reframe Service der Geodäsie verwendet. Dieser wird abgefragt, wenn das Popup startet.

In der Fusszeile wird die Koordinate rudimentär berechnet und reagiert auf jede Maus Bewegung. Wir können nicht bei jeder Maus Bewegung eine Abfrage an den Reframe Service senden. Zudem besteht die Inkonsistenz nur, wenn die Maus nach dem Rechts Klick nie bewegt wird. Bewegt man die Maus, dann steht in der Fusszeile so oder so eine andere Koordinate.

Ausserdem: die Koordinaten sind gleich, in der Fusszeile wird einfach gerundet :=)

**Comment by davidoesch** [comment]
thanks: this answer goes into helpdesk FAQ @mariokeusen

**Comment by oterral** [comment]
Not anymore since LV95 migration, CH1903+/LV95 is the coordinate given by the mouse. The coordinate are different only because in the mouse position, values are rounded.

**Comment by gjn** [comment]
@oterral is correct.

Anyhow, a mismatch based on reframe can still happen (if user selects LV03 in mousepostion dropbox and compares to LV03 in context popup.

So 2 reasons for mismatch: rounding and reframe.

**Comment by oterral** [comment]
Yes you're right.

**Comment by procrastinatio** [comment]
Is it important?
At the lowest level, 1 pixel represent 0.1m. Is a mouse pointing device capable of selecting a specific pixel on a screen? At other zoom level, it has absolutely no importance.
On a smartphone, with glove, could luck.

Rounding and precision should be done according to zoom level.

**Comment by davidoesch** [comment]
from a user perspective:
the same mouse position gives a different result... which is _not_correct then from a user perspective

same same but different is not an argument

so how to unify it?

**Comment by procrastinatio** [comment]
No, it is to educate and sensiblise the user to this inherantly imperfect world. There is no absolut truth. We want the user to be critic and question everything, even holy cows carved into [Aar-Massiv granit](https://s.geo.admin.ch/7877c866fb)  like swiss coordinates.

No, seriously, round them to _meter_ which is the more correct answer for all zoom levels except the smallest and biggest.

**Comment by gjn** [comment]
Easiest solution: get rid of reframe functionality in the context popup. Then, numbers will always be the same (independant of rounding/resolution problematic). I propose:

1) not use reframe in context menu anymore
2) always show dm rounding in context menu
3) always who m rounding in footer

**Comment by davidoesch** [comment]
we removed rounding from  context menue..and added it back after several complaints...think cadastre. 
some data sets we show _are_ of submeter precision.

3) ?

**Comment by loicgasser** [comment]
removing reframe means also that we are less accurate between coordinates in LV95 and LV03 which is much worst in my eyes.

**Comment by davidoesch** [comment]
you got a point there , @loicgasser

**Comment by gjn** [comment]
Caught in a conundrum.

**Comment by gjn** [comment]
Discussed, we will add a coma (1dm) in the mousepointer component.
