### ISSUE TITLE
Strange type fo search results

### ISSUE THREAD

**Issue by oterral** [geoadmin/mf-geoadmin3#4141]
Steps:

1) Open [geoadmin](https://map.geo.admin.ch/?topic=ech&lang=fr&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bav.haltestellen-oev,ch.swisstopo.swisstlm3d-wanderwege&layers_visibility=false,false,false,false&layers_timestamp=18641231,,,)
2)Type test in the search box

Results:
   Some results have a weird type : "Lieu-dit swisstopo", "Nom local swisstopo"

Why the text "swisstopo" is in the result type  ?  it should just be"Nom local"

**Comment by loicgasser** [comment]
These tags are in chsdi translations, I think it's related to SwissTLM categories.
https://github.com/geoadmin/mf-chsdi3/blob/master/chsdi/locale/fr/LC_MESSAGES/chsdi.po#L10119

Not nice I agree.

**Comment by oterral** [comment]
@davidoesch do we  leave as it is?

**Comment by davidoesch** [comment]
Leave it as it is
