### ISSUE TITLE
Add share button to whatsapp on mobile

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/mf-geoadmin3#4151]
http://alandaitch.com/how-to-add-share-on-whatsapp-button-on-your-mobile-website/

Would be really cool I think.

**Comment by davidoesch** [comment]
Yes!!! As long as no cookies are set or user is tracked

**Comment by davidoesch** [comment]
Eg https://www.sharethis.com/ was er... not ok

**Comment by loicgasser** [comment]
I think it's only available on modern android devices.

**Comment by loicgasser** [comment]
No cookie. I just checked. Sharethis is a third party app. This is just a href balise. It s the same as the other buttons in essence. Twitter button also opens the app if installed.

**Comment by davidoesch** [comment]
Ask @paolo for nice artwork /icon

**Comment by loicgasser** [comment]
Does it work out also of the box pn your iphone?

**Comment by davidoesch** [comment]
Works
