### ISSUE TITLE
Support Progressive Web App

### ISSUE THREAD

**Issue by gjn** [geoadmin/mf-geoadmin3#4152]
Allow uses to profit from the progressive web app specification on mobile devices. After chrome, also Firefox is supportin this. Here is the spec:

https://developers.google.com/web/progressive-web-apps

This needs deeper analysis to determine the cost.

**Comment by oterral** [comment]
Be careful with skeleton-screen,  it often results to the feelling that is slower

**Comment by boecklic** [comment]
wontfix in accordance with @davidoesch, reconsider when refactoring offline
