### ISSUE TITLE
Deploy branch from current directory

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/mf-geoadmin3#4177]
Because during branch deployment in our CI we create a folder outside the current directory to clone and deploy the branch, this might result in conflicts when push several commits in a row and create conflicts.
I added a commit to solve this issue.

**Comment by oterral** [comment]
@loicgasser you 've fixed this no?

**Comment by loicgasser** [comment]
Nop I remved the commit from the PR. Had some issue with ownership.

**Comment by oterral** [comment]
CI deploy from the current directory now with 

```
make int && s3copybranch
```
