### ISSUE TITLE
should use wmts100-109.geo.admin.ch instead of tod100-109

### ISSUE THREAD

**Issue by danduk82** [geoadmin/mf-geoadmin3#4178]
In 3D we are still using TOD cloudfront distribution. We should use wmts100-109.geo.admin.ch.

**Comment by gjn** [comment]
yes, leftover from migration phase. chmobil already switched back to official address

**Comment by oterral** [comment]
It's fixed on prod I think

**Comment by danduk82** [comment]
seems good
