### ISSUE TITLE
Move linear and polygon objects in draw mode

### ISSUE THREAD

**Issue by AFoletti** [geoadmin/mf-geoadmin3#4216]
This is a request coming from customers in helpdesk

Open draw mode and draw a polygon or line.
If you want to move it, you do not have any solution other than either move every vertex or delete and redraw.
The requested enhancement is to make it possible via click-hold to move the selected object as a whole, the same way as in google mymaps
![move](https://user-images.githubusercontent.com/691243/37698261-27f86d10-2ce2-11e8-9578-8867d7762c6d.gif)

**Comment by boecklic** [comment]
wontfix in accordance with @davidoesch
