### ISSUE TITLE
Auto deploy on PR merge in master fails

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/mf-geoadmin3#4245]
![image](https://user-images.githubusercontent.com/3306154/38246965-d6c5833a-3743-11e8-8327-8f259eb1724f.png)

the following paths are generated in the index.html 

https://mf-geoadmin3.int.bgdi.ch/1803291132/style/app.css
https://mf-geoadmin3.int.bgdi.ch/1803291132/lib/build.js

which is incorrect.

Regression introduced in https://github.com/geoadmin/mf-geoadmin3/pull/4225

**Comment by loicgasser** [comment]
sill not ok.
now when deploying master we have
https://mf-geoadmin3.int.bgdi.ch/HEAD/be532fa/1804051436/1804051436/style/app.css

see:
https://mf-geoadmin3.int.bgdi.ch/master/be532fa/1804051436/index.html

as a result saucelabs tests are failing after the merge.

it should be https://mf-geoadmin3.int.bgdi.ch/master/be532fa/1804051436/1804051436/style/app.css

**Comment by oterral** [comment]
It works https://mf-geoadmin3.int.bgdi.ch/master/22189a3/1804060609/index.html?lang=fr&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe

Thx for the heavy testing @loicgasser

**Comment by oterral** [comment]
Still not working:
master/4f1a437/1804060621/
master/4f1a437/1804060622/

vrrsion number change between the build and the deploy

**Comment by loicgasser** [comment]
😭
