### ISSUE TITLE
Use cached wms-bgdi when imported via import-wms

### ISSUE THREAD

**Issue by AFoletti** [geoadmin/mf-geoadmin3#4256]
Now that wms-bgdi is behind a cloudfront, visualization of WMS-based chsdi layers can better take advantage of the cache.

### Please extend the wms-import tool so that it can use the cache too for **wms-bgdi layers**.

This development is vital for the rapidmapping project and should be online no later than 02.05

Thanks!

**Comment by procrastinatio** [comment]
Import used whatever address is used in the Capabilities...

**Comment by AFoletti** [comment]
> wms-bgdi behind cloudfront is in testing phase on map.geo.

> I think this is now good and we can move all wms behind CF. @danduk82 what's your take?

> (This would do what @AFoletti wants)

I am not sure this will suffice. What I need is tiled requests to wms-bgdi when the service is used in map.geo via wms-import-tool. The CF will do nothing if WMS requests are not tiled
(sorry, initial description was not clear enough)

@procrastinatio what do you mean with your comment?

**Comment by AFoletti** [comment]
ping @oterral 
I know you have a lot to do, but the deadline for this one is next week

**Comment by oterral** [comment]
I like pressure !!!!

**Comment by oterral** [comment]
But we are not under cloudfront anymore

**Comment by oterral** [comment]
@AFoletti  do you have  alayer's name to test?

**Comment by oterral** [comment]
@AFoletti [Test link](https://mf-geoadmin3.int.bgdi.ch/fix_4256/index.html?lang=fr&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&dev3d=true&zoom=1&debug&layers_visibility=false&layers_timestamp=18641231&E=2687463.73&N=1190083.58). I needs halfday to clean and to add tests.

**Comment by AFoletti** [comment]
ok, that's great!
I have the feeling it produces a whole lot of requests (44 for zooming from 7 to 8. The pixelkarte for the same movement tops at 27 requests)
Otherwise works as a charm

**Comment by oterral** [comment]
i think it's normal the pyramid is not the same.

**Comment by procrastinatio** [comment]
I don't get it. If we want WMTS pyramid, why not use WMTS (tod)? 
Seems doable for me.

**Comment by procrastinatio** [comment]
And it event prints...

**Comment by AFoletti** [comment]
because
a) it's not a chsdi layer (only WMS)
b) we have _n_ layers (and thus pyramids) with a 60min cycle.

Mind, I've nothing against ToD if you manage to make it work.

**Comment by oterral** [comment]
Whatever we can stick with the dflt pyramid. It's not aproblem if that make more requests, everything will be stored in cloudfront.

**Comment by AFoletti** [comment]
> Whatever we can stick with the dflt pyramid. It's not aproblem if that make more requests, everything will be stored in cloudfront.

It was probably just a wrong feeling due to browser cache. I'd say not to change the actual behaviour
