### ISSUE TITLE
wishlist/backlog

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#426]
Backlog

- All legend in footer
- mobile: 3 functions of geolocation button: true north/roatet map, geolocate, geolocationoff: will be done in 3D
- Search : highlight search term in results

-API: http://api.geo.admin.ch/maps?layers=ch.swisstopo.hiks-dufour,ch.swisstopo.hiks-siegfried,ch.swisstopo.zeitreihen,ch.swisstopo.zeitreihen,ch.swisstopo.zeitreihen,ch.swisstopo.zeitreihen,ch.swisstopo.zeitreihen,ch.swisstopo.zeitreihen,ch.swisstopo.zeitreihen&width=600&zoom=7&lat=235151.5&lon=702646.3&layers_timestamp=18450101,18700101,19501231,19601231,19701231,19801231,19901231,20001231,20101231

**Comment by gjn** [comment]
@davidoesch Agree to close this? (Everything in here is already done or WIP.
