### ISSUE TITLE
EGIDs, perimeter, and coordinates

### ISSUE THREAD

**Issue by RobertoMinelli** [geoadmin/mf-geoadmin3#4265]
As per [this question](https://groups.google.com/forum/#!topic/geoadmin-api/ef1_a1ny2sY), I believe that GeoAdmin's REST API lacks of two key functionalities:

1. Given a EGID, obtain the **base perimeter** of the building, i.e., a sorted list of 2D points.

2. Given a 2D point (i.e., coordinate) obtain the base perimeter of the building that contains the point and, in turn, the **list of EGIDs** that are inside this perimeter. This issue is complementary to the one above: If an EGID knows the coordinates of its base perimeter, obtaining the list of EGIDs for a point is trivial.

I hope you can consider my requests for a next release of your cool API.

Best,
Roberto

**Comment by davidoesch** [comment]
Imho.. Using a mashup of the existing services should do the trick. The issue is rather in the availability of the building data: they are not available as feature service. 
Ping @beattschanz @procastrinatio

**Comment by beat-github** [comment]
Hi 
Thank you for suggesting of new features. The function is not yet implementable for data reasons.

The EGID is an attribute of the dataset "Gebäude- und Wohnungsregister". The geometry is a point.
The base perimeter of a building takes part of the data set “Amtliche Vermessung”.
The two datasets are currently not fully matching (ongoing work) and the dataset of the “Amtliche Vermessung” is not freely accessible all over (means among other things, the geometry of the building is not integrated in our geodata infrastructure).

In context with the introduction of the "official directories of streets and building addresses"  a functional improvement can be expected. Termination is currently not possible.

**Comment by RobertoMinelli** [comment]
Dear @beat-github,

Thanks for your answer.

> On Apr 11, 2018, at 10:49, Tschanz <notifications@github.com> wrote:
> 
> Hi
> Thank you for suggesting of new features. The function is not yet implementable for data reasons.
> 
> The EGID is an attribute of the dataset "Gebäude- und Wohnungsregister". The geometry is a point.

I know, it is the coordinate of the EGID.

> The base perimeter of a building takes part of the data set “Amtliche Vermessung”.
> The two datasets are currently not fully matching (ongoing work) and the dataset of the “Amtliche Vermessung” is not freely accessible all over (means among other things, the geometry of the building is not integrated in our geodata infrastructure).

I see the problem. More than the perimeter per se, a great feature would be, given a coordinate obtain the list of EGIDs that are inside a Building. The perimeter can also be computed or stored internally and not offered to the final user. Please, take also a look at Issue #4264 where I proposed a possible solution for this problem.

> In context with the introduction of the "official directories of streets and building addresses" a functional improvement can be expected. Termination is currently not possible.

Good, please keep me posted when the "official directories of streets and building addresses" is available :)

Best,
Roberto

**Comment by RobertoMinelli** [comment]
Hum, @oterral why are you closing? I would keep it open until you integrate the _"official directories of streets and building addresses"_ so that we can have some improvements on the issue.
