### ISSUE TITLE
Exact result in SPHINX not shown "Dom"

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#4287]
Hi

the location "Dom" entered in swisssearch does not show up the peak "Dom " in the result

I assume it is due to the fact that the sphinx search needs more than 3 char otherwise it starts only with the guess

-> ideas?

Customer feedback ID : 2018042108134534

**Comment by oterral** [comment]
When a query fit a complete word it should be on first place.

**Comment by AFoletti** [comment]
we have some client reports about that issue too.
Try searching for "Ricken". There is an exact match but is buried after tons of other things.

**Comment by ltclm** [comment]
duplicate of https://github.com/geoadmin/mf-chsdi3/issues/2925

**Comment by ltclm** [comment]
there are other customer complaints concerning missing results with exact matches:
p.e. search for ``entle`` should return the river Entle but it does not.

https://api3.geo.admin.ch/rest/services/ech/SearchServer?sr=2056&searchText=entle&lang=de&type=locations&origins=gazetteer

**Comment by davidoesch** [comment]
Any idea for a solution? sphinx community?

**Comment by ltclm** [comment]
yes, i think it's worth a try to separate non-fuzzy queries into wildcard queries and exact match queries:
https://stackoverflow.com/questions/44883623/how-to-boost-relevance-for-exact-match-results-when-using-wildcard-in-sphinx

**Comment by davidoesch** [comment]
I hope performance wise it works...

**Comment by ltclm** [comment]
fix is online
