### ISSUE TITLE
Print Json: labels not shown

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#4290]
If printed a json https://mf-chsdi3.dev.bgdi.ch/meteo_temp/shorten/7a231d005b

![image](https://user-images.githubusercontent.com/4577727/39188944-4df71f98-47d1-11e8-95ca-2b1b396d8fae.png)

PDF looks like this

![image](https://user-images.githubusercontent.com/4577727/39188972-5e8c991e-47d1-11e8-8ef8-99d4c1367ecf.png)

Expected result:
labels (text has  corresponding bg as in webview)
@danduk82 pls assign

**Comment by procrastinatio** [comment]
As a reminder, vector support in `mapfish print v2` is minimal. This feature is not supported.
Solutions:
* Implement this feature is `mapfish print v2`
* Calculate and add rectangulare features to the vector layer to mimic label boxes (ugly as hell)
* Migrate to `mapfish print v3`
* Move away from mapfish print

**Comment by oterral** [comment]
The test should at least be at the good position
