### ISSUE TITLE
WMS.GEO.ADMIN.CH behind cloudfront

### ISSUE THREAD

**Issue by danduk82** [geoadmin/mf-geoadmin3#4291]
Hello @procrastinatio , could you please validate (curl, anything) that this cloudfront distribution seems to be working for WMS geo admin ch?

d3sl3avkeaqv2r.cloudfront.net

these addresses:
wms.geo.admin.ch
wms[0-4].geo.admin.ch

**Comment by danduk82** [comment]
wait maybe half an hour before testing...

**Comment by danduk82** [comment]
@hpchrist , if @procrastinatio and @ltclm agree with the config, could you please inform with @beat-github and try to do the DNS migration on next monday? 

ping @AFoletti  for info

**Comment by danduk82** [comment]
@ltclm please test it too....

**Comment by ltclm** [comment]
as far as i can tell, the cloudfront config is working fine. I have succesfully tested some getmap and getcap variants (http, https, /xyz/?blabla&,  etc.)

**Comment by gjn** [comment]
Beforw go live, please test with fat clients and test our print.

**Comment by ltclm** [comment]
qgsi 2.18 working fine in single tile and wms-c mode

**Comment by ltclm** [comment]
arcmap 10.4.1 working fine in single tile mode, wms-c is not supported

**Comment by procrastinatio** [comment]
With `curl` or `owslib` looks OK.
With map.geo.admin.ch, QGis and mapfish print  we cannot set the host easily.

**Comment by hpchrist** [comment]
Hi,

I will therefore request the BIT now to plan the DNS switch for next Monday, April 30 (I'll request to execute it at 10:00a.m.):

wms.geo.admin.ch CNAME d3sl3avkeaqv2r.cloudfront.net
wms[0-4].geo.admin.ch CNAME d3sl3avkeaqv2r.cloudfront.net

Best regards,

Hanspeter
