### ISSUE TITLE
Can't use ESRI syntax to Identify Features in GeoAdmin REST API

### ISSUE THREAD

**Issue by RobertoMinelli** [geoadmin/mf-geoadmin3#4295]
I am trying to use the ESRI syntax as `geometry` parameter for an [Identify Features](https://api3.geo.admin.ch/services/sdiservices.html#identify-features) request with GeoAdmin REST API.

Quoting from [your documentation](https://api3.geo.admin.ch/services/sdiservices.html#identify-features): 

> **geometry (required):** The geometry to identify on. The geometry is specified by the geometry type. This parameter is specified as a separated list of coordinates. The simple syntax (comma separated list of coordinates) and the complex one can be used. ([ESRI syntax for geometries](http://resources.arcgis.com/en/help/arcgis-rest-api/index.html#//02r3000000n1000000))

This is the location to identify on, expressed using the JSON ESRI syntax:

```{"x":717725.72800819238,"y":96257.179952642487,"spatialReference":{"wkid":21781}}```

Here is the complete request:

[```https://api3.geo.admin.ch/rest/services/all/MapServer/identify?geometryType=esriGeometryPoint&returnGeometry=true&lang=en&layers=all:ch.bfs.gebaeude_wohnungs_register&geometry={"x":717725.72800819238,"y":96257.179952642487,"spatialReference":{"wkid":21781}}&tolerance=100&mapExtent=0,0,100,100&imageDisplay=100,100,100```](https://api3.geo.admin.ch/rest/services/all/MapServer/identify?geometryType=esriGeometryPoint&returnGeometry=true&lang=en&layers=all:ch.bfs.gebaeude_wohnungs_register&geometry={"x":717725.72800819238,"y":96257.179952642487,"spatialReference":{"wkid":21781}}&tolerance=100&mapExtent=0,0,100,100&imageDisplay=100,100,100)

When executing the request, I receive the following answer:

```{"status":"error","code":400,"detail":"Please provide a valid geometry"}```

Please note that I also tried to escape characters such as `{` (U+007B), `"` (U+0022), `:` (U+003A), `,` (U+002C), and `}` (U+007D) but without success. Below the ERSI point with escaped characters.

```%7B%22x%22%3A717725.72800819238%2C%22y%22%3A96257.179952642487%2C%22spatialReference%22%3A%7B%22wkid%22%3A21781%7D%7D```

What am I doing wrong?

Thanks for your support.

Rob

**Comment by loicgasser** [comment]
For ponts a simple comma separated list should be used.
Try
https://api3.geo.admin.ch/rest/services/all/MapServer/identify?geometryType=esriGeometryPoint&returnGeometry=true&lang=en&layers=all:ch.bfs.gebaeude_wohnungs_register&geometry=717725.72800819238,96257.179952642487&tolerance=100&mapExtent=0,0,100,100&imageDisplay=100,100,100

**Comment by RobertoMinelli** [comment]
I know that it works with comma separated coords. I  was only wondering whether it is possible to make it work using ESRI syntax.

Best,
Rob

On 27 Apr 2018, at 08:53, Gasser Loïc <notifications@github.com<mailto:notifications@github.com>> wrote:


For ponts a simple comma separated list should be used.
Try
https://api3.geo.admin.ch/rest/services/all/MapServer/identify?geometryType=esriGeometryPoint&returnGeometry=true&lang=en&layers=all:ch.bfs.gebaeude_wohnungs_register&geometry=717725.72800819238,96257.179952642487&tolerance=100&mapExtent=0,0,100,100&imageDisplay=100,100,100

**Comment by loicgasser** [comment]
Currently  not. We support polylines and polygons definitions only.
For instance:
http://api3.geo.admin.ch/rest/services/api/MapServer/identify?geometry={"rings":[[[675000,245000],[670000,255000],[680000,260000],[690000,255000],[685000,240000],[675000,245000]]]}&geometryType=esriGeometryPolygon&imageDisplay=500,600,96&mapExtent=548945.5,147956,549402,148103.5&tolerance=5&layers=all:ch.bafu.bundesinventare-bln

It would make sense to support the ESRI syntax for points as well.

**Comment by RobertoMinelli** [comment]
Thanks. Yes, I already tried with Polygons and I know it works.

Thanks!

Rob

On 27 Apr 2018, at 10:32, Gasser Loïc <notifications@github.com<mailto:notifications@github.com>> wrote:


Currently not. We support polylines and polygons definitions only.
For instance:
http://api3.geo.admin.ch/rest/services/api/MapServer/identify?geometry={"rings":[[[675000,245000],[670000,255000],[680000,260000],[690000,255000],[685000,240000],[675000,245000]]]}&geometryType=esriGeometryPolygon&imageDisplay=500,600,96&mapExtent=548945.5,147956,549402,148103.5&tolerance=5&layers=all:ch.bafu.bundesinventare-bln<http://api3.geo.admin.ch/rest/services/api/MapServer/identify?geometry=%7B%22rings%22:%5B%5B%5B675000,245000%5D,%5B670000,255000%5D,%5B680000,260000%5D,%5B690000,255000%5D,%5B685000,240000%5D,%5B675000,245000%5D%5D%5D%7D&geometryType=esriGeometryPolygon&imageDisplay=500,600,96&mapExtent=548945.5,147956,549402,148103.5&tolerance=5&layers=all:ch.bafu.bundesinventare-bln>

It would make sense to support the ESRI syntax for points as well.
