### ISSUE TITLE
Illegal 'cache-control' header with value `max-age=1800,`

### ISSUE THREAD

**Issue by RobertoMinelli** [geoadmin/mf-geoadmin3#4311]
Dear all,

I am trying to use the [find](https://api3.geo.admin.ch/services/sdiservices.html#find) and [identify](https://api3.geo.admin.ch/services/sdiservices.html#identify-features) services from you REST API programmatically (i.e., from Scala).

The returned HTTP response, however, contains an illegal header. I am getting the following error in console `Invalid input 'EOI', expected OWS or cache-directive`. Indeed the `cache-control` header contains an invalid value: `cache-control: max-age=1800,` (please note the comma at the end).

[Here](https://securityheaders.com/?q=https%3A%2F%2Fapi3.geo.admin.ch%2Frest%2Fservices%2Fapi%2FMapServer%2Ffind%3Fcontains%3Dfalse%26returnGeometry%3Dtrue%26lang%3Den%26layer%3Dch.bfs.gebaeude_wohnungs_register%26searchField%3Degid%26searchText%3D11103024) you can see the scan results for a sample find query to your API.

Best,
Roberto

**Comment by fredj** [comment]
There's a space here: https://github.com/geoadmin/mf-chsdi3/blob/master/rc_prod#L26 (also in )

```
$ export CACHE_CONTROL=max-age=1800, public
$ echo $CACHE_CONTROL
max-age=1800,
```
Adding double quotes around the value seems to work:
```
$ export CACHE_CONTROL="max-age=1800, public"
$ echo $CACHE_CONTROL
max-age=1800, public
```

**Comment by oterral** [comment]
Will be on prod next wednesday @RobertoMinelli

**Comment by RobertoMinelli** [comment]
Thank you very much @oterral and @fredj

**Comment by oterral** [comment]
Yes it should be on prod since yesterday
