### ISSUE TITLE
KML won't show

### ISSUE THREAD

**Issue by procrastinatio** [geoadmin/mf-geoadmin3#4318]
This invalide KML won't display in map.geo.admin.ch: https://www.procrastinatio.org/kml/OGISWasserOMWSanWK-SPCHdatakml180508%20SanG%20KMLSanG_GewaesserAbschnittG_WBSanG_GewaesserAbschnittG_WB.kml

A valid version of the same file, also won't display
[Link](https://s.geo.admin.ch/7a6f2d86ea)

> . Ich habe per ArcGIS Pro eine KML mit Gewässerabschnitten erstellt und möchte diese nun online importieren. Die KML wird erfolgreich geladen, jedoch nicht dargestellt. Dasselbe Prozedere mit Punktdaten hat funklioniert

Betreff: Customer feedback ID : 2018050908150604

**Comment by oterral** [comment]
Just change the poly style

**Comment by oterral** [comment]
Like this  :  
```
    <PolyStyle>
      <color>00000000</color>
      <outline>5</outline>
    </PolyStyle>
```
