### ISSUE TITLE
Returned geometries SR is independent from the SR of the geometry to identify on

### ISSUE THREAD

**Issue by RobertoMinelli** [geoadmin/mf-geoadmin3#4320]
I figured out that identify requests with `returnGeometry=true` always return geometries in LV03 spatial reference.

I believe it makes sense that the returned geometries have the same format of the geometries to identify on. If I specify geometries in `sr=2056` it would be consistent that also the returned geometries are in `sr=2056` and not in `sr=21781`.

Just my 2 cents.

Best,
Roberto

P.s. Any update on #4311? Is it in prod already?

**Comment by procrastinatio** [comment]
Yes, makesperfectly sense

**Comment by RobertoMinelli** [comment]
Thanks @procrastinatio!
