### ISSUE TITLE
Use prod WMTS/WMS Urls on integration

### ISSUE THREAD

**Issue by gjn** [geoadmin/mf-geoadmin3#4329]
Thoughts?

@danduk82 @oterral @procrastinatio @ltclm 

We can always overwrite via parameter for testing on integration new and updated layers. Would need to be taken into account during deploy.

**Comment by procrastinatio** [comment]
Why? And not all resources? If the goal is to start disconnect code and content, and to automatically push code to prod, yes.

**Comment by gjn** [comment]
Idea was to have better performance also on integratio., as wi now use integration for demo purposes and abmahme.

But it's not a good idea. Default should be to use int tod - and if we want good perforance, use wmts_url parameter. We can close this.
