### ISSUE TITLE
3D Black tiles 

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#4357]
https://s.geo.admin.ch/7add75c81f

Switch on 3d on chrome/Safari on iOS. A lot of black tiles

**Comment by oterral** [comment]
It happens evens if you reload the page ? it seems black tile appears only when it can't get the tile, so it's probably a temporay service failure.

**Comment by davidoesch** [comment]
it is a temporary service failure...but then it should be white and not black

**Comment by oterral** [comment]
Re-open if it happens again
