### ISSUE TITLE
Swisssearch :  result Highlight Gemeindegrenze 

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#4360]
This is  slight improvement stated by various customer ( recently by  SWISS ARMY as well)

OS:
ALL
Browsers: ALL

Reproduce

1) Search in swisssearch field  on map.geo.admin.ch for eg T"rimmis"
2) on Hover in result list keep pin
3) When cliking on recentering on Trimmis: Show 
-  [ ] Boundary
-  [ ] Highlight Overlay
4) When deleting the reuslt in swissssearch : highlight is removed (analogeous as currently for the pin)

(in general: as in gmaps....)

ETA: with RE4

**Comment by oterral** [comment]
Duplicate with https://github.com/geoadmin/mf-geoadmin3/issues/3873
