### ISSUE TITLE
Offline does not work with external WMS

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#4366]
https://s.geo.admin.ch/7af6e90ff4

try to save offline this view

Save button does not react

Due to the wms.geoa.dmin.ch settings for rapirdmappin?

**Comment by procrastinatio** [comment]
I guess, there are many issues:
* WMS is not HTTPS
* http://rm-swisstopo.s3.amazonaws.com/2017-02-Bondo/20170830-OBLIQUE-IMAGES/20170830-OBLIQUE-IMAGES.kml is not https
* And as all rabitmapping layer have no GetCapabilities, I guess we cannot decide if it may be cached or not (https://github.com/geoadmin/mf-geoadmin3/blob/bed2d74ce0a541da740bc4c663bb46142b1cdee5/src/components/offline/OfflineService.js#L73)

**Comment by oterral** [comment]
I'll try to use the dfltTileGrid

**Comment by oterral** [comment]
Offline was not meant to work for external WMS layers because it was only single tile WMS layer.
Do we allow offline for external layer @davidoesch ?

**Comment by davidoesch** [comment]
Nth if possible

**Comment by oterral** [comment]
Nth?

**Comment by davidoesch** [comment]
Nice to have
