### ISSUE TITLE
URL Parameter to deacticvate tooltip/only highlight

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#4371]
similar to show_tooltip=false in API for iframe usage

customer request meteoschweiz

**Comment by davidoesch** [comment]
showTooltip | showTooltip=true oder false | https://map.geo.admin.ch/?ch.bav.haltestellen-oev=8500010&lang=fr&topic=ech&showTooltip=true&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.bav.haltestellen-oev&X=266309.00&Y=611362.00&zoom=9
-- | -- | --

**Comment by davidoesch** [comment]
does not work

**Comment by pakb** [comment]
Could you clarify the wanter behaviour? Is it near what is described here https://github.com/geoadmin/mf-geoadmin3/issues/4474 ?
Meaning a new param that will disable any tooltip appearance during the whole session (and not just at load time)?

**Comment by davidoesch** [comment]
duplicate off #4474
