### ISSUE TITLE
Certain places not marked after search

### ISSUE THREAD

**Issue by nadine-piveteau** [geoadmin/mf-geoadmin3#4374]
Reproduce situation:
1. Look for "Rheineck"
2. Select suggestion "Rheineck (SG)"

Result:
Zooms to place but does not display the marker symbol. 

Shouldn't there be a marker symbol?

**Comment by ltclm** [comment]
@oterral you asked me about that some days ago.
i think this is a feature.
For some reasons, sorry but i can't remember the reasons for all the exceptions that have been implemented, objects with origin gg25 (polygon features) have no zoomlevel in the sphinx query ``zoomlevel=-1``, so there is no marker symbol for these objects.
If you want to change this behaviour, you have to tell me the zoomlevel that these objects should be recentered on.

**Comment by oterral** [comment]
@davidoesch what do you want ?

**Comment by loicgasser** [comment]
gg25 are based on polygons if I recall correctly and their areas can vary quite a bit. So we use the extent to zoom to the appriopriate zoom level.

**Comment by davidoesch** [comment]
Oh.. @loicgasser I do remember now. Have to check with Marcel if this is still the case for tlm Swiss names

**Comment by ltclm** [comment]
maybe related to https://github.com/geoadmin/mf-geoadmin3/issues/4462

**Comment by procrastinatio** [comment]
Everything from `gg25` has a real BBOX (not a point):

https://api3.geo.admin.ch/1808290840/rest/services/ech/SearchServer?sr=2056&searchText=Rheineck&lang=fr&type=locations

for instance: `"BOX(2760969.661 1258711.263,2762497.033 1261715.808)"`

**Comment by pakb** [comment]
What do we do? Do we add the possibility to place a marker at the center of a shape in some cases?

**Comment by pakb** [comment]
or we could highlight the shape "à la Google" like when you look for a town or county (like this : https://www.google.com/maps/place/Berne/@46.9547658,7.3248301,12z/data=!3m1!4b1!4m5!3m4!1s0x478e39c0d43a1b77:0xcb555ffe0457659a!8m2!3d46.9479739!4d7.4474468)

**Comment by davidoesch** [comment]
For everything which is not a point but a polygon we should highlight the polygon as eg gmap does it. The reason why we did not do it: back in Dev for re3 : the management of all those feature highlights of course swissnames and swissboundaries was to big of an effort to link it to Sphinx in  a way so the mouseover was performant as well..  ltclm knows more about this. Maybe this changed in the past

**Comment by boecklic** [comment]
wontfix in accordance with @davidoesch
