### ISSUE TITLE
webmercator viewer tooltip LV95/03 values wrong

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#4383]
https://mf-chsdi3.int.bgdi.ch/mom_merc/shorten/7ab268221c  

"Beim Koordinatenherauslesen (Rechtsklick auf einen Punkt) kommen bei LV95 und LV03 irgendwelche Fantasiezahlen (und die Höhe fehlt)"

-> to be fixed if we get the ok for the ALPHA

**Comment by davidoesch** [comment]
related to https://github.com/geoadmin/mf-geoadmin3/pull/4272

**Comment by procrastinatio** [comment]
Solved?
 https://mf-chsdi3.int.bgdi.ch/mvt/shorten/7efc5c454f

**Comment by pakb** [comment]
old link
![image](https://user-images.githubusercontent.com/11540521/50473156-27ef3300-09bc-11e9-8a23-5aaeb6657816.png)
new link
![image](https://user-images.githubusercontent.com/11540521/50473183-405f4d80-09bc-11e9-9477-f7940360fb4b.png)

LGTM

**Comment by oterral** [comment]
Fixed
