### ISSUE TITLE
Link to geocat : direkt URL to Full view

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#4387]
Situation

the link to geocat

![image](https://user-images.githubusercontent.com/4577727/41452712-650c323e-7073-11e8-95ad-2489575ed1df.png)

goes to the dataset https://www.geocat.ch/geonetwork/srv/eng/catalog.search#/metadata/4a064664-a346-4c1a-b424-4e8a0f0b56cb 
but user wants in 99% of the cases the phone number and adress of the dataowner to make a call drop a mail.

there fore

@ltgap can you enhance geocat  permalinks, so that we can add an url directly to "full view" display and tab "complete"

![image](https://user-images.githubusercontent.com/4577727/41452825-bf3c8e98-7073-11e8-8655-7dc35bdf40d5.png)

result:

we  get rid off at least 5 phone calls per week

**Comment by p1d1d1** [comment]
@davidoesch the link you're using in map.geo.admin.ch is not the geocat permalink, but the link to the new default page, which is in my opinion far better then the full view.
IMHO in the full view the user is completely lost: too many information.

I'd propose instead to improve the contact info on the default page:

![image](https://user-images.githubusercontent.com/1533649/41454761-ee0fbdec-707a-11e8-89c4-ba9812033e9a.png)

**Comment by davidoesch** [comment]
Give the user full Access ... From beginning. Don't pantronize him. Don't tell the user how he should Access info. Give him all the info from beginning

**Comment by p1d1d1** [comment]
Information creep. Don't trow on the user tons of info, give her/him overviews. She/he is cleaver enough to understand if he needs more info and will find the way to get to it.

**Comment by ltgap** [comment]
I agree with Pasquale: keep it simple, therefore stick to the Default View. In addition, I like the map of the product perimeter on the right side of the default view.
And yes, we should 
1.  make the phone numbers visible for every contact
2.  enhance the translations, e.g. for "pointOfContact"

BTW, did you know the "Feedback" Icon on the top right above the mentioned map? It opens the following dialog where you can select the mail address of your choice

![geocat-01](https://user-images.githubusercontent.com/16152485/41612445-43e24ae8-73f3-11e8-976e-271a2365354f.png)

**Comment by gjn** [comment]
I wonder: why is standard view in geocat directly accessible but complete view is not?

(in other words: why don't we allow people the share what they want?)

**Comment by davidoesch** [comment]
Michel Quinquis will check if the link  architecture
https://www.geocat.ch/geonetwork/srv/ger/catalog.search#/metadata/4a064664-a346-4c1a-b424-4e8a0f0b56cb 

can be replaced with

A) 
https://www.geocat.ch/geonetwork/srv/ger/md.viewer#/full_view/4a064664-a346-4c1a-b424-4e8a0f0b56cb 

B) and a Permalien which will enforce "Complete" tab

**Comment by p1d1d1** [comment]
Please not so fast. What do you mean with replacing the "link architecture". If you want to change the new default geocat overview, you cannot simply decide it on your own: I personally don't agree.

If I can summarize your use case, as far as I can understand it, you want that if someone uses the geocat link in map.geo.admin.ch he will be redirected to the full view and in "Complete" tab: is that right? 
If yes then you don't need to replace the default geocat view.
The way the geocat permalink is already linking to the full view. So at the end you only need B)

**Comment by davidoesch** [comment]
A) already exists b) will be added. Then mfchsdi will be Adapted.
Cool down

**Comment by p1d1d1** [comment]
didn't warm up, so don't need to cool down.
Just discussing, if I may.

**Comment by ltgap** [comment]
Yes, at the end we need B), so we can let the geocat Default View be as it is.

Unfortunately from Dave's point of view is the fact that the Full View defaults to the Default Tab [sic!]. Maybe we can tell the application with an additional URL parameter to display the Full View in *Complete* Tab. Let's see if camp2camp sees a solution to [this JIRA-ticket](https://jira.swisstopo.ch/browse/MGEO_SB-376).

**Comment by mariokeusen** [comment]
Direct link to geocat full view is now online on the mapviewer and I let @davidoesch close this issue.

**Comment by davidoesch** [comment]
Done. Next step: beautify geocat view
