### ISSUE TITLE
No more CORS headers on reframe service

### ISSUE THREAD

**Issue by oterral** [geoadmin/mf-geoadmin3#4395]
The request failed when called from map.geo.admin.ch because there is no more cors headers.

https://geodesy.geo.admin.ch/reframe/lv95tolv03?easting=2727500&northing=1191250

@danduk82 @davidoesch @hpchrist  who manage this url? us?

**Comment by danduk82** [comment]
@hpchrist might this be related with the migration to stretch of the geodesy server?

**Comment by davidoesch** [comment]
Jérôme Rey. Pls contact him

..... And would really like to get this stack operated by kogis or get rid of it from our domain

**Comment by danduk82** [comment]
I have added a comment in the migration ticket by camptocamp

**Comment by danduk82** [comment]
@oterral it should be solved, can you confirm?

here is a quote from the C2C ticket:
```
There is an Apache configuration on the old server in /var/www/vhosts/tc-geodesy/conf/cors.conf (not managed by Puppet, belongs to ltmom:geodata) that sets these headers.
I copied this file over to the new server and enabled the mod_headers Apache module that it needs.
```

it is now puppetized by Christian, it shouldn't be a problem next time.

**Comment by oterral** [comment]
fixed thx
