### ISSUE TITLE
WM(T)S wmts.geo.bs.ch failes on import (CORS)

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#4412]
using this on import
https://wmts.geo.bs.ch/
nothings works
https://wmts.geo.bs.ch/1.0.0/WMTSCapabilities.xml

works but with

Failed to load https://wmts.geo.bs.ch/1.0.0/WMTSCapabilities.xml.: Redirect from 'https://wmts.geo.bs.ch/1.0.0/WMTSCapabilities.xml.' to 'https://wmts.geo.bs.ch/error_path/400.html?al_req_id=WzN4BawTBI8AANAdA94AAAf-' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://map.geo.admin.ch' is therefore not allowed access.

Same is the case for https://wms.geo.bs.ch/ and https://wms.geo.bs.ch/?SERVICE=WMS&VERSION=2.0.0
&REQUEST=GetCapabilities

-> What are the instructions for Basel to fix their issue? which standards do the violate?

**Comment by oterral** [comment]
@davidoesch 

First error:
> XMLHttpRequest cannot load https://wmts.geo.bs.ch/1.0.0/WMTSCapabilities.xml. The 'Access-Control-Allow-Origin' header has a value 'https://basel-stadt.virtualcitymap.de' that is not equal to the supplied origin. Origin 'https://map.geo.admin.ch' is therefore not allowed access.

They should add `https://map.geo.admin.ch`or `* ` to the  'Access-Control-Allow-Origin' header

2nd error:
> Failed to load https://wmts.geo.bs.ch/1.0.0/WMTSCapabilities.xml.: Redirect from 'https://wmts.geo.bs.ch/1.0.0/WMTSCapabilities.xml.' to 'https://wmts.geo.bs.ch/error_path/400.html?al_req_id=WzN4BawTBI8AANAdA94AAAf-' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://map.geo.admin.ch' is therefore not allowed access.

It will not happens if first error is fixed

**Comment by davidoesch** [comment]
asked via twitter https://twitter.com/GeoPortalBS to do so

**Comment by svareg** [comment]
Hi there,

I'm about to look at this configuration problem with our sysadmins.
I'll let you know as soon as it's fixed.

**Comment by svavoi** [comment]
@davidoesch
The 'Access-Control-Allow-Origin' header for https://wms.geo.bs.ch/ and https://wmts.geo.bs.ch/1.0.0/WMTSCapabilities.xml is now set to *.

**Comment by davidoesch** [comment]
@procrastinatio Can You test if there is now all ok? I still get an issue when loading on prod

**Comment by procrastinatio** [comment]
For me it is OK when loading through the advanced tool

https://s.geo.admin.ch/7cd5a94d53

**Comment by davidoesch** [comment]
Still get the error

**Comment by davidoesch** [comment]
For https://wmts.geo.bs.ch/

**Comment by danduk82** [comment]
I get : `Access-Control-Allow-Origin: http://map.geo.bs.ch`,
but strangely the tiles are loaded successfully.
@procrastinatio do you understand this?

**Comment by davidoesch** [comment]
Still get the error

**Comment by procrastinatio** [comment]
I may display WMTS tiles in 2D
If you write:
_https://wmts.geo.bs.ch/_, it will be requested with parameters _service=WMTS&version=1.0.0&_, which the bs.ch server doesn't support
if you write: _https://wmts.geo.bs.ch/1.0.0/WMTSCapabilities.xml_ it is OK

**Comment by boecklic** [comment]
cant be reproduced. pls reopen if issue persists.
