### ISSUE TITLE
Civil signatures: wrong image url

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#4415]
Reproduce

open: map.geo.admin.ch
draw a point default and draw a point civil signatures
export
according to KML
civil icons are located at
https://map.geo.admin.ch/master/d227132/1806271439/1806271439/img/babs/babs-1.png

whereas default are located at
https://api3.geo.admin.ch/color/255,0,0/marker-24@2x.png

expected result
https://map.geo.admin.ch/master/d227132/1806271439/1806271439/img/babs/babs-1.png
should be located at 
https://api3.geo.admin.ch/img/babs/babs-1.png

reason: so symbols can be replaced even if master URL is changed -

this is prio 1: if ppl start now using it it wil be PITA to symlink the babs-*.png urls

**Comment by oterral** [comment]
good point we didn't think about this

**Comment by nadine-piveteau** [comment]
it's on prod

**Comment by oterral** [comment]
@nadine-piveteau thx can you ceate a new release please
