### ISSUE TITLE
Support WGS 84 and WebMercator by API REST Services

### ISSUE THREAD

**Issue by beat-github** [geoadmin/mf-geoadmin3#4429]
The API REST Services e.g. https://api3.geo.admin.ch/rest/services/api/MapServer/{layerBodId}/{featureId},{featureId} has to support request and answers of further projections: WGS84 EPSG:4328and WebMercator EPSG:3857.
(customer requests)

**Comment by davidoesch** [comment]
AFAIK  it should  via the SRS parameter introduced for LV95/L03 migration

**Comment by procrastinatio** [comment]
See https://github.com/geoadmin/mf-chsdi3/tree/mom_merc and
https://github.com/geoadmin/mf-geoadmin3/issues/4383

**Comment by boecklic** [comment]
solved.
