### ISSUE TITLE
GetFeatureInfo does not work for imported WMS 

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#4430]
> "
> Die Nutzung von importierten WMS aus geodienste.ch funktioniert ja auch für die Zugriffsgeschützten, wenn man sich in einem Browser-Tab gleichzeitig auf geodienste.ch mit einem (berechtigten) User einloggt. 
> 
> Nun wurde mir aber gemeldet, dass das GetFeatureInfo bei zugriffsgeschützten Diensten nicht funktioniert. Ich kann das reproduzieren: 
> 
> 	https://s.geo.admin.ch/7b8aec535d
> 	Einloggen unter geodienste.ch mit irgendeinem User
> 	Refresh in map.geo.admin.ch und Abfrage, Karte/Inhalt wird erwartungsgemäss in LU angezeigt (dort ist der WMS zugriffsgeschützt resp. kann nur mit Registrierung konsumiert werden)
> 	Informationsabfrage in LU: GetFeatureInfo results: Search returned no results. 
> 
> In QGIS 2.18.11 habe ich dieses Problem nicht. 
> 
> Hast du eine Idee, wo hier das Problem liegen könnte? Wie sendet map.geo.admin.ch die GetFeatureInfo Requests? 
> 
> "

**Comment by davidoesch** [comment]
GetCap Abfragen sollten ja eigentlich vom Client aus gemacht werden welcher sich bei den Geodiensten eingeloggt 

@procrastinatio

**Comment by oterral** [comment]
We don't send credentials with the request.

**Comment by oterral** [comment]
Another reason could be, the WMS GetFEatureInfo  doesn't have CORS header so we made the request through the service-proxy. Tell him to add the CORS headers and to retry.

Another reason could be the HEAD request is not allowed by the WMS .

**Comment by procrastinatio** [comment]
@davidoesch It won't work. The browser won't send `Authorization` headers for let say `wms.swisstopo.admin.ch` to `map.geo.admin.ch`.  So forget about `GetCapabilities`.
But what do work, it to configure the permalink, as:

https://map.geo.admin.ch/?layers=WMS%7C%7CArr%C3%AAts%20tp%7C%7Chttps:%2F%2Fwms.swisstopo.admin.ch%2F%3F%7C%7Cch.swisstopo.geologie-geologischer_atlas%7C%7C1.3.0&layers_visibility=true

If you did access the basic auth protected resource before `wms.swisstopo.admin.ch`, it will display that WMS layer

**Comment by dkottmann** [comment]
@procrastinatio 
Get**Map** works for basic auth protected WMS imported in maap.geo.admin.ch (e.g. in the example above with https://geodienste.ch/db/planerischer_gewaesserschutz)

Get**FeatureInfo** doesn't... 

Not sure if this was clear.

**Comment by dkottmann** [comment]
@procrastinatio 
OK, thanks for the explanation. 
I guess that means GetFeatureInfo on map.geo.admin.ch won't be possible for imported, http basic auth protected WMS...?

**Comment by procrastinatio** [comment]
Basic auth will not not work with any resource that not requested trough the browser itself (KML, GetCapabilities, etc.)

**Comment by davidoesch** [comment]
@dkottmann : since the limitation is given here by the standard. we can't (should not) fix it with a technical hack ---- the only solution I see: open up the data
