### ISSUE TITLE
Upgrade to openlayers 5.0.2

### ISSUE THREAD

**Issue by gjn** [geoadmin/mf-geoadmin3#4437]
See https://github.com/openlayers/openlayers/releases/tag/v5.0.0 for upgrad guide. Latest version is 5.0.2

This release changes how modules are loaded and removes the closure compiler dependency.

It contains some important changes for drawing.

It contains a very good improvement for vector tiles: https://github.com/openlayers/openlayers/pull/8227

Ping @danduk82 summer work.

**Comment by procrastinatio** [comment]
See https://github.com/geoadmin/mf-geoadmin3/pull/4511
