### ISSUE TITLE
Adaption to new varnish instances

### ISSUE THREAD

**Issue by rebert** [geoadmin/mf-geoadmin3#4444]
Jira-Ticket: BGDI Infrastructure BGDIINF_SB-680

due to new varnish instances the flush from Makefile is not working any more:
https://github.com/geoadmin/mf-geoadmin3/blob/master/scripts/flushvarnish.sh

**Comment by procrastinatio** [comment]
See https://jira.camptocamp.com/servicedesk/customer/portal/5/INF-2711

**Comment by procrastinatio** [comment]
Should be solved
