### ISSUE TITLE
New topic for BFS

### ISSUE THREAD

**Issue by mariokeusen** [geoadmin/mf-geoadmin3#4448]
UC: open app, click the topic selector

Goal: add a new blue topic to the selector for BFS.
All configuration has been done in "tool-wms" / BOD. Tasks:

- Embed the topic icon by @pauloamado 
![bfs](https://user-images.githubusercontent.com/4577749/43003252-2c943f8a-8c2c-11e8-909b-6535cd34603e.png)

- Put the translations given in the translation spreadsheet for the fields:

bfs
bfs_service_link_href
bfs_service_link_label
topic_bfs_tooltip

- Put the fully translated topic to dev or int, in order BFS can have a watch before putting the topic on prod

Thanks in advance
Mario

**Comment by mariokeusen** [comment]
This might be something for @ltkum , together with the DI-introduction? @rebert ?
In any case all layers are now configured for the topic, only the tasks written above are left.

**Comment by mariokeusen** [comment]
Thanks!

**Comment by mariokeusen** [comment]
Two slight changes made:

1. translation on English topic title corrected
2. Configuration changed (catalog will be open by default instead of layer selection)

Could you please import these changes on the current dev version of the topic?
Otherwise topic is ready to go on prod with next possible release.
Thanks Mario

**Comment by mariokeusen** [comment]
@danduk82 it would be good to have this new topic put to prod with the deploy of Aug 29th. and I think @ltkum will need some help to do so.
Thanks in advance

**Comment by mariokeusen** [comment]
I have now put all topic categories to staging=prod in the bod.

**Comment by ltkum** [comment]
I updated the pull request [4449](https://github.com/geoadmin/mf-geoadmin3/pull/4449). You can now try it.

**Comment by mariokeusen** [comment]
This is on prod now. Thanks4work!
