### ISSUE TITLE
[WMS import] add INSPIRE WMS service to dropdown list of portrayal services

### ISSUE THREAD

**Issue by mariokeusen** [geoadmin/mf-geoadmin3#4451]
UC: open app, open the wms import tool, open the dropdown list with the known services
Expected: I can find the new INSPIRE WMS service provided by the FSDI [1]
Workaround: please add the new service to the list
![grafik](https://user-images.githubusercontent.com/4577749/43181903-a339cdc4-8fdf-11e8-97b5-a4cb369ce4d4.png)

Thanks Mario

[1] getCapabilities WMS INSPIRE: https://wms-inspire.geo.admin.ch/?REQUEST=GetCapabilities&SERVICE=WMS&VERSION=1.0.0&lang=de

**Comment by davidoesch** [comment]
Is already done https://github.com/geoadmin/mf-geoadmin3/pull/4457
