### ISSUE TITLE
[topic bafu] URL to bafu landing page does not work anymore

### ISSUE THREAD

**Issue by mariokeusen** [geoadmin/mf-geoadmin3#4453]
UC: open app, switch to topic=bafu, click the reference link on the bottom right (bafu.admin.ch)
Result: a 404 error appears (obviously bafu has changed the urls of its landing page)
Expected: bafu.admin.ch landing page opens

Workaround: please update the bafu_service_link_href values from the translation table with the new correct urls.

Thanks Mario

**Comment by davidoesch** [comment]
The Link needs to be changed to www.bafu.admin.ch .....

**Comment by davidoesch** [comment]
@mariokeusen proper solution: change to the official URL  "www.bafu.admin.ch " instead " bafu.admin.ch"

**Comment by mariokeusen** [comment]
Exactly this part of the topics does not have its source in the BOD but in the translation spreadsheet. But yes, I would absolutely prefer a solution where all this information comes out of "tool-wms"/BOD.

**Comment by davidoesch** [comment]
the bafu_service_link_href label link in https://docs.google.com/spreadsheets/d/1bRzdX2zwN2VG7LWEdlscrP-wGlp7O46nvrXkQNnFvVY/edit#gid=54811248 is correct  but not imported in "bafu_service_link_href" in 
https://github.com/geoadmin/mf-geoadmin3/blob/c943b366f66a5447b8928e961e88834e157a8691/src/locales/en.json 

-> @danduk82 can you do here a PR (@gjn used to trigger the updates)

**Comment by mariokeusen** [comment]
Or maybe handle application translations in github or tool-wms/BOD? tbd @davidoesch @danduk82 @gjn 
This issue here is solved now, I close it.
