### ISSUE TITLE
[dev-viewer] location search zoom does not work correctly on dev

### ISSUE THREAD

**Issue by mariokeusen** [geoadmin/mf-geoadmin3#4462]
UC: open the application on test (dev) level, search for "Zürich", choose "Zürich (ZH)" on top of the result list
Result: Marker is correctly set to "Zurich (ZH)" map is correctly recentered to the marker, but the map does not zoom to the location search result geometry, but to zoomlevel 0
Expected: Marker is set, map is recentered to the marker and zoomed to the extent geometry of the search result (as on integration and production viewer)

Observed only on dev-level. Important will be, not to inherit that to int or prod level.

**Comment by ltclm** [comment]
there was a test version of gg25 / gg25_metaphone index on sphinx-dev.
see here: https://github.com/geoadmin/mf-geoadmin3/issues/4374
I have recreated the index with the official (prod) version.
recenter behaviour is back to normal.
