### ISSUE TITLE
3D: new version produces an error message on latest android/cr

### ISSUE THREAD

**Issue by mariokeusen** [geoadmin/mf-geoadmin3#4467]
UC: open the latest test version (for outside BV) in chrome on an android device
Result: browser messages the following
Expected: 3D can be used normally
![3d_chrome](https://user-images.githubusercontent.com/4577749/44448881-db01e700-a5ec-11e8-8c8b-9944c53df722.png)
![android](https://user-images.githubusercontent.com/4577749/44448930-01c01d80-a5ed-11e8-8b56-32b48e2f60bb.png)

Rq: 

- I have the latest version of android and chrome for android installed, webgl is enabled. Problem with the graphics hw of the device?

- same message appears with the current 3D on prod

Can somebody with an android device reproduce that?

**Comment by p1d1d1** [comment]
Chrome 65.0.3323.109 and 68.0.3440.91
Android 8.0.0

Cannot reproduce

**Comment by mariokeusen** [comment]
Probably the hardware on my device

**Comment by davidoesch** [comment]
Make of device ?
