### ISSUE TITLE
3D: 3D navigation buttons do not work completely in EDGE inside BIT zone

### ISSUE THREAD

**Issue by mariokeusen** [geoadmin/mf-geoadmin3#4468]
UC: open the testlink with latest version in EDGE (inside BV, problem does not occur in EDGE from outside BV)
Result: 3D navigation buttons are not complete and do not work completely:
![3d_navigation_edge_bitzone](https://user-images.githubusercontent.com/4577749/44453310-07bbfb80-a5f9-11e8-9f4f-8f41460f5576.PNG)
Expected: 3D navigation buttons look like and work as in the other browsers

Can somebody reproduce that?

**Comment by mariokeusen** [comment]
Seems to be a matter of responsiveness. On a larger screen everything ok. Looks like I had a tablet layout on my laptop (but only with edge).

**Comment by AFoletti** [comment]
I can confirm that, in my experience, is based on screen size.
Additionally:
- in FF the navigation buttons are misaligned 
![immagine](https://user-images.githubusercontent.com/691243/44505903-2925f180-a6a4-11e8-8ec0-c48eac3cb48c.png)
- with smaller screen the navigation buttons are misleading: you got a hand cursor hovering over them but clicking does nothing. Maybe we should just remove them?

**Comment by davidoesch** [comment]
ff aligned is an issue pls open separate ticket fo this @AFoletti
