### ISSUE TITLE
3D: location search, marker does not appear in EDGE

### ISSUE THREAD

**Issue by mariokeusen** [geoadmin/mf-geoadmin3#4469]
UC: open app with EDGE, switch to 3d, search for "Thun BE", click on the first result "Thun BE" in the result list
Result: 3d map is recentered to a bird view of the city of Thun BE (so far so good), but the location is not marked by a red pin like in 2D mode or in 3D in other browsers (e.g. FF).
Expected: location is marked by a red pin

**Comment by mariokeusen** [comment]
Same issue in Safari

**Comment by davidoesch** [comment]
After entering Bern (be) and then go for Thun (BE)
![image](https://user-images.githubusercontent.com/4577727/45686536-f52bd800-bb4c-11e8-92fe-5ef0d47ea4c5.png)


it works.... strange
