### ISSUE TITLE
3D: in flight mode UP and DOWN should be applied to current orientation of the view

### ISSUE THREAD

**Issue by danduk82** [geoadmin/mf-geoadmin3#4470]
in flight mode when we press on arrow UP or DOWN, the orientation vector is tilted in the vertical direction. Instead it should be applied to the current local rotation axis. I.e. if the plane is rotated, UP should allow for a sharper turn, as in a real plane.

```
vx = V * cos(horizonzalAngle)
vy = V * sin(horizonzalAngle)
```
where V is the delta defined when pressing UP or DOWN

**Comment by AFoletti** [comment]
Can't I give a +100 directly? It will be on par on how many times I raised the issue (ok, not officially here in a ticket, but anyways)

**Comment by davidoesch** [comment]
Afaik : This Is a cesium feature ....

**Comment by fredj** [comment]
See https://github.com/geoadmin/mf-geoadmin3/blob/master/src/components/controls3d/fps.js#L360-L402

**Comment by danduk82** [comment]
indeed we shoud do something like:
```
if (this.buttons_.forward) {
    pitch -= 0.02 * sin(roll);
    heading -= 0.02 * cos(roll);
}
etc
```
instead of simply updating the pitch

**Comment by danduk82** [comment]
fixed [here](https://github.com/geoadmin/mf-geoadmin3/pull/4476). Thanks @fredj for finding the src file :+1:
