### ISSUE TITLE
Object information (Advanced tools) does not find from pull-down in certain circumstances

### ISSUE THREAD

**Issue by AFoletti** [geoadmin/mf-geoadmin3#4471]
**Steps to reproduce:**

- open [this link](https://mf-chsdi3.int.bgdi.ch/gas_bakom_notruf/shorten/7c97817c58)
- open "advanced tools" --> "object information"
- in "Query conditions" select the active layer, then "112 Emergency Center" as lookup attribute
- click on the "..." button to get a pulldown list of available values
- choose one and click search

**Result:**
- nothing found!

**Expected result:**
- each object with the selected value is found and highlighted

**Note:**
- the same procedure works with other layers (ex: "Traffic counting locations principal") and results are correctly found
- it looks to me that the pull-down list is not correctly taken by the search box. Some characters are missing (ex: line breaks) and the text has then some issues ("Saint-Martin 331005 Lausanne" instead of "Saint-Martin 33 1005 Lausanne")
- taking a long entry from the list and delete some characters to make it shorter solves the problem. Do we maybe have a character limit somewhere?

Thanks for having a look!!

**Comment by procrastinatio** [comment]
Request is https://mf-chsdi3.int.bgdi.ch/gas_bakom_notruf/rest/services/all/MapServer/ch.bakom.notruf-112_mobilnetz?lang=en

**Comment by AFoletti** [comment]
Sorry @procrastinatio , are you telling me that by following the steps I described you are getting a result?
Because I'm consistently getting none...

**Comment by ltclm** [comment]
there are line feeds in the database, that's why the ilike is not working.
This is the query string which is not working: 
```
http://localhost:9076/rest/services/all/MapServer/identify?geometryFormat=geojson&imageDisplay=1169,803,96&lang=en&layers=all:ch.bakom.notruf-112_mobilnetz&mapExtent=2454734.813976,1000064.9423119999,2952121.6260240003,1341725.857688&returnGeometry=true&sr=2056&tolerance=5&where=mo_addresse_112 ilike '%Etat de Genève Police Cantonale
Chemin de la Gravière 9
1227 Les Acacias%'
```
I think you need the line feeds for the tooltip.
For each queryable attribute with line feeds, you could add a (queryable attribute search only) column to the view and replace line feeds with space
```SQL
regexp_replace(mo_addresse_112, '\r|\n', ' ', 'g') as mo_addresse_112_queryable
```

**Comment by AFoletti** [comment]
Thanks for your analysis @ltclm 
Do we need to add a column to a view in order to solve the problem or could we solve it in the sphinx config? This would spare us some tinkering with the DB

**Comment by ltclm** [comment]
you have to add columns to the view. sphinx is not involved in the queryable attribute stuff.

**Comment by ltclm** [comment]
an alternative solution would be:
https://github.com/geoadmin/mf-chsdi3/blob/ee88d1b4323b27fbe4630434e833874aa4f841a5/chsdi/lib/helpers.py#L185

replace line feeds with ``%`` when generating the ilike string, but im not sure about side effects, i can give it a try if you want.

**Comment by AFoletti** [comment]
Personally I would like a general solution better than a per-layer one. We could very well encounter the same issue in other layers (and we probably we already have that... we simply did never notice the issue) and it would be stupid to have to add a special column just to solve this issue.

But I understand that the general solution in chsdi is more demanding in terms of time.

@danduk82 and @gjn your opinion?

**Comment by ltclm** [comment]
pr and testlink are here: https://github.com/geoadmin/mf-chsdi3/pull/2978

**Comment by AFoletti** [comment]
Well, that was fast

**Comment by AFoletti** [comment]
fixed with https://github.com/geoadmin/mf-chsdi3/pull/2978
