### ISSUE TITLE
showTooltip Parameter does not work

### ISSUE THREAD

**Issue by gjn** [geoadmin/mf-geoadmin3#4474]
showTooltip=false still shows tooltip when clicking the map. It should not, as noted in the help of geoadmin.

https://map.geo.admin.ch/?showTooltip=false&lang=en&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.swisstlm3d-wanderwege,ch.kantone.cadastralwebmap-farbe&layers_visibility=false,true&E=2638855.95&N=1229318.83&zoom=7

**Comment by procrastinatio** [comment]
Apparently, the `showTooltip`has no effect on **WMS** layer, as `,ch.kantone.cadastralwebmap-farbe`, ans **GeoJSON**, as `bikesharing`

**Comment by davidoesch** [comment]
ping @gjn this works as defined see procastrinatio

**Comment by procrastinatio** [comment]
See also https://github.com/geoadmin/mf-geoadmin3/issues/4487

**Comment by pakb** [comment]
showTooltip is only taken into account if the URL is using a `layerBodId=featureId` syntax, and not with a `layers=...&X=...&Y=...` syntax.

working as intended with tooltip on : https://map.geo.admin.ch/?ch.bav.haltestellen-oev=8500010&showTooltip=true
working as intended with tooltip off : https://map.geo.admin.ch/?ch.bav.haltestellen-oev=8500010&showTooltip=false
param showTooltip ignored : https://map.geo.admin.ch/?showTooltip=true&layers=ch.bav.haltestellen-oev&E=2611363.00&N=1266308.00&zoom=9

looks good to me, but maybe I misunderstood something in the doc?

**Comment by pakb** [comment]
@gjn do you mean that, if showTooltip=false, any click on anything in this instance of map should not show a tooltip? Isn't it an init phase only param?

**Comment by davidoesch** [comment]
ping @gjn

**Comment by gjn** [comment]
Yes, I was wrong. showTooltip is for initial load of map only.

We would need another parameter to dusable tooltip altogether.

I propose 'disableTooltip' parameter (default = false). This feature has been asked mainly from iframe users like meteoschweiz.

I'lk adapt the op.
