### ISSUE TITLE
Opacity 0.9 not taken into account?

### ISSUE THREAD

**Issue by AFoletti** [geoadmin/mf-geoadmin3#4485]
**Steps to reproduce:**

- open map.geo.admin.ch and, in the console, look for the layersConfig file
- open the layersConfig file and search for "bikesharing"
- in the bikesharing config, look for "opacity": 0.9," to confirm the config
- in map.geo.admin.ch, activate the Bikesharing layer

**Result:**
- the bikesharing layer is activated with **100%** opacity

**Expected:**
- the bikesharing layer is activated with **90%** opacity

Thanks for having a look!

**Comment by AFoletti** [comment]
I know it's a vector dataset, but the LayersConfig should be taken into account.
Moreover, it was changed to 0.9 from 0.75, and 0.75 was correctly used as default value for opacity on layer's add

**Comment by procrastinatio** [comment]
@AFoletti Please check

**Comment by AFoletti** [comment]
Thanks for your fix!
