### ISSUE TITLE
Missing translation 

### ISSUE THREAD

**Issue by oterral** [geoadmin/mf-geoadmin3#4495]
See screenshot:
![map geo admin ch-bug-translation](https://user-images.githubusercontent.com/621420/45621429-8719df00-ba80-11e8-9bde-f839ed98b783.png)

**Comment by davidoesch** [comment]
sorry folks: the translation is all wrong see original ticket https://github.com/geoadmin/mf-geoadmin3/issues/4073

A) the Text reference is in modify_icon_label (Symbol ...)
B) Then the Pulldown should be:

[DE] Standard / Zivile Signaturen
[FR] défaut / Signes conventionnels civils
[IT] predefinito / Segni convenzionali civili
[EN] default / civil symbols

**Comment by mariokeusen** [comment]
I guess due to this missing (shorter) translation users always have to scroll down in order to choose the symbol type. Better is either to bring the dropdowns for "Size" and "modify_icon_category_label" on the same line or to enlarge the window.
![symbol_edit_box](https://user-images.githubusercontent.com/4577749/46348771-6345c400-c650-11e8-9157-736c296801f6.png)

**Comment by davidoesch** [comment]
Please See my comments above: it was correct and one of the latest deploys killed it

**Comment by davidoesch** [comment]
Ping @procrastinatio

**Comment by procrastinatio** [comment]
For @mariokeusen comment see #4516

For transalation see https://github.com/geoadmin/mf-geoadmin3/pull/4529

**Comment by procrastinatio** [comment]
Please one problem per issue.
translation > /dev/integration

**Comment by davidoesch** [comment]
Hi Marc 
There is no need for a new translation.
The whole thing was correct. It is a regression introduced lately.

So once it was correct: roll back
Hint: remove the tag modify_icon_category_label And Make Sure translation as mentioned above is applied like it was.

There is *no* need for a a bigger drawing window
Cc @mariokeusen no action required for your side

**Comment by procrastinatio** [comment]
So, thanks the SSL termination, nobody is using the Google doc anymore?

**Comment by davidoesch** [comment]
We save are faster if Mario foa and I directly change in locales

**Comment by davidoesch** [comment]
@procrastinatio 

Replace the "Standard /Zivile Signaturen"
with

[DE] Signaturen
[FR] Signes 
[IT]  Segni
[EN] symbols

and in the pull down "standard" "babs"
with

[DE] Standard / Zivile Signaturen
[FR] défaut / Signes conventionnels civils
[IT] predefinito / Segni convenzionali civili
[EN] default / Civil symbols
![image](https://user-images.githubusercontent.com/4577727/47993442-bb5c6400-e0ef-11e8-8445-66aa4f2c12dc.png)

**Comment by davidoesch** [comment]
still an issue

![image](https://user-images.githubusercontent.com/4577727/49145843-02a9cf00-f301-11e8-8f31-974fd6d216f9.png)
