### ISSUE TITLE
KML-Einbindung produziert Fehler

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#4500]
Can you please investigate?  might be related to our service-proxy.prod.bgdi.ch

> Problem 1: KML-Einbindung produziert Fehler
> Unter bestimmten Umständen wird beim Aufruf des Swisstopo-Iframes ein Fehler erzeugt, der dazu führt, dass unser KML nicht angezeigt wird.
>  
> Mit folgenden Schritten lässt sich das reproduzieren (als Browser verwenden wir Firefox). Achtung: Es gibt Momente, wo alles perfekt läuft (dann ist das auch bei Randoplan so), dann wieder hakt es. Den selben Fehler hatte ich auch schon bei wandern.ch produziert, allerdings ist uns dies heute nicht gelungen zu reproduzieren.
>  
> > Aufruf von EWALC auf dem Stage Server: https://www.wandern-stage.ch/de/wandern/unsere-wandervorschlaege/alle-wandervorschlaege 

> > Das KML mit allen Wanderungen erscheint korrekt
> 
> > Nun die Suche einschränken, z.B. Wanderregion: Berner Oberland wählen => Suche auführen
> 
> > Wenn nun im iframe weiterhin Icons erscheinen, einfach eine weitere Wanderregion hinzufügen und die Suche starten
> 
> > Sobald die Situation eintritt, dass keine Icons angezeigt werden, kann in der JavaScript-Konsole folgender Fehler ausgemacht werden:
> 
> XML-Verarbeitungsfehler: Ungeschlossenes Token
> Adresse: https://service-proxy.prod.bgdi.ch/https/www.wandern-stage.ch%2Ftmp%2Fkml%2F7d69564b48218531962088c3c3989198.kml
> Zeile Nr. 7, Spalte 229429: www.wandern-stage.ch/tmp/kml/7d69564b48218531962088c3c3989198.kml:7:229429
> XML-Verarbeitungsfehler: Ungeschlossenes Token
> Adresse: https://map.geo.admin.ch/embed.html?zoom=0&topic=ech&lang=de&bgLayer=ch.swisstopo.pixelkarte-farbe&layers_visibility=true
> Zeile Nr. 7, Spalte 234181:
> embed.html:7:234181 
> XML-Verarbeitungsfehler: Ungeschlossenes Token
> Adresse: https://map.geo.admin.ch/embed.html?zoom=0&topic=ech&lang=de&bgLayer=ch.swisstopo.pixelkarte-farbe&layers_visibility=true
> Zeile Nr. 7, Spalte 229429:
>  
> Nach einem Page-Reload läuft es meist wieder perfekt.
>  
> Beim neuen Randoplan-Tool fällt dieses Verhaltenmanchmal extrem auf, so dass jede Seite reloaded werden muss. Heute morgen aber hat zunächst alles perfekt funktioniert – aber eben hatten wir das Verhalten wieder.
>  
> Unsere erste Vermutung war, dass ev. das KML noch nicht fertig geschrieben war, aber der Aufruf bei Swisstopo bereits erfolgt ist. Dies können wir mittlerweile aber mit Gewissheit ausschliessen. 
> 
> > Bei einer Suchabfrage wird auf unserem Server ein KML erzeugt, dessen URL dann beim iframe-Aufruf als Parameter mitgegeben wird.
> > Die Funktion, welche das KML erzeugt, ist nicht asynchron, d.h., das Programm wartet mit der Ausführung, bis das KML komplett geschrieben wurde. Die Resultateseite wird erst dann gerendert.
> > Testweise haben wir dennoch nach dem Erzeugen der Datei eine 10-Sekunden-Warteschlaufe (sleep 10) eingebaut, um sicher zu gehen, dass die Datei komplett geschrieben wurde. Der Fehler trat trotzdem auf.
> > Last but not least haben wir die KMLs jeweils geprüft. Es sind keine Fehler vorhanden. Ein KML, welches nicht angezeigt wird, sieht genau gleich aus wie ein KML, welche angezeigt wird (diff-Vergleich)
>  
> Wir vermuten das Problem liegt am Service-Proxy (https://service-proxy.prod.bgdi.ch), aber sicher sind wir uns da natürlich nicht.
> 
>

**Comment by procrastinatio** [comment]
map.geo.admin.ch cannot access "Basic Auth" protected KML or GPX, as the requests are done by the JS application, not the browser. You may, however, access protected WMS as images requested are done by the browser.

**Comment by davidoesch** [comment]
But why does it work most of the time? This would mean that the kml is once in a while protected: this means issue is not on map.geo.admin.ch infra site. Kml is protected at the moment application tries to load it.

**Comment by silvercode-ch** [comment]
This works because there is a .htaccess in the /tmp/kml directory to grant access for all.

**Comment by davidoesch** [comment]
ping @silvercode-ch  we close this ticket, please reopen if we need to take an action on our side
