### ISSUE TITLE
WMS Import: GetFeatureInfo zeigt nur 1 Objekt an

### ISSUE THREAD

**Issue by dkottmann** [geoadmin/mf-geoadmin3#4503]
@davidoesch 

Bsp.:
https://geodienste.ch/db/npl_nutzungsplanung/deu?SERVICE=WMS&REQUEST=GetCapabilities 

Layer: ueberlagernde_nutzungsplaninhalte_flaechen

Objekte können sich überlagern. Ggf. müssten die Abfrageresultate aller Objekte angezeigt werden. 
https://s.geo.admin.ch/7d263fcac7

**Comment by davidoesch** [comment]
Marc: issue in the import controller?

**Comment by p1d1d1** [comment]
@dkottmann you have to select all layers and click on the right point :-)
It works also if you load the root layer:

https://s.geo.admin.ch/7d26fa4218

**Comment by p1d1d1** [comment]
@dkottmann this request (in the browser) returns only one object:

https://wfs.geodienste.ch/npl_nutzungsplanung/deu?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetFeatureInfo&FORMAT=image%2Fpng&TRANSPARENT=true&QUERY_LAYERS=ueberlagernde_nutzungsplaninhalte_flaechen&LAYERS=ueberlagernde_nutzungsplaninhalte_flaechen&INFO_FORMAT=text%2Fplain&LANG=de&I=50&J=50&CRS=EPSG%3A2056&STYLES=&WIDTH=101&HEIGHT=101&BBOX=2668726.85%2C1203760.45%2C2668736.9499999997%2C1203770.55

**Comment by dkottmann** [comment]
@p1d1d1 

Koordinate: 2663589.4 1199119.2

Beispiel:
https://s.geo.admin.ch/7d27378eca
Inforamtionsabfrage ergibt 1 Objekt

```
GetFeatureInfo results:

Layer 'ueberlagernde_nutzungsplaninhalte_flaechen'
  Feature 509124: 
    publiziertab = '2017-06-09'
    rechtsstatus = 'inKraft'
    bemerkungen = ''
    typ_kommunal_code = '5111'
    typ_kommunal_bezeichnung = 'Ortsbildschutzzone'
    typ_kantonal_code = '511'
    typ_kantonal_bezeichnung = 'Ortsbildschutzzonen'
    hauptnutzung_code = '51'
    hauptnutzung_bezeichnung = 'überlagernde Ortsbildschutzzonen'
    kanton = 'OW'
```

Im Browser erhalte ich ebenfalls 1 Objekt mit: 
https://wfs.geodienste.ch/npl_nutzungsplanung/deu?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetFeatureInfo&FORMAT=image%2Fpng&TRANSPARENT=true&QUERY_LAYERS=ueberlagernde_nutzungsplaninhalte_flaechen&LAYERS=ueberlagernde_nutzungsplaninhalte_flaechen&INFO_FORMAT=text%2Fplain&LANG=de&I=50&J=50&CRS=EPSG%3A2056&STYLES=&WIDTH=101&HEIGHT=101&BBOX=2663589.4%2C1199119.2%2C2663599.4%2C1199129.2



In QGIS erhalte ich jedoch 2 Objekte. Abfrage-URL aus QGIS: 
https://wfs.geodienste.ch/npl_nutzungsplanung/deu?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetFeatureInfo&BBOX=2663012.9055130765773356,1198859.75057315710000694,2664301.41926663694903255,1199652.61304311803542078&CRS=EPSG:2056&WIDTH=1435&HEIGHT=883&LAYERS=ueberlagernde_nutzungsplaninhalte_flaechen&STYLES=&FORMAT=image/png&QUERY_LAYERS=ueberlagernde_nutzungsplaninhalte_flaechen&INFO_FORMAT=application/vnd.ogc.gml&I=641&J=594&FEATURE_COUNT=10

Scheint an dem Parameter FEATURE_COUNT=10 zu liegen. 

map.geo.admin.ch müsste evtl. defaultmässig auch einen FEATURE_COUNT Value verwenden. Der QGIS default Wert 10 scheint mir relativ vernünftig. Besser wäre aber, wenn immer alle Objekte ohne Limite ausgeliefert würden. Kann das evtl. im Request irgendwie übersteuert werden?

**Comment by p1d1d1** [comment]
@dkottmann the issue is exactly with FEATURE_COUNT. This parameter is not mandatory and its default is "1". 
IMHO you could try to add this parameter in your Capabilities document for the GetFeatureInfo request.
something like:

https://wfs.geodienste.ch/npl_nutzungsplanung/deu?FEATURE_COUNT=10

**Comment by dkottmann** [comment]
Am besten wäre es, wenn FEATURE_COUNT=0 "unlimitiert" bedeuten würde und dies in UMN Mapserver der Default-Wert wäre... UMN Mapserver unterstützt aber scheinbar ein solches Verhalten nicht. 

> his parameter is not mandatory and its default is "1".

Wo ist dieser Default-Wert FEATURE_COUNT=1 festgelegt? Ist das eine Vorgabe von OGC? 

Aus meiner Sicht wäre es besser, wenn der Default-Wert clientseitig z.B. auf 10 (analog zu QGIS) erhöht wird, damit wir serverseitig die Requests nicht übersteuern... 

--> Könnt ihr eine Anpassung in map.geo.admin.ch prüfen?

**Comment by p1d1d1** [comment]
> Wo ist dieser Default-Wert FEATURE_COUNT=1 festgelegt? Ist das eine Vorgabe von OGC?
OGC WMS 1.3.0 paragraph 7.4.3.6

**Comment by dkottmann** [comment]
>     Wo ist dieser Default-Wert FEATURE_COUNT=1 festgelegt? Ist das eine Vorgabe von OGC?
> 
> OGC WMS 1.3.0 paragraph 7.4.3.6

@p1d1d1: OK. Das spricht eingentlich für eine clientseitige Steuerung des FEATURE_COUNT, also Anpassung default Request Paramter `FEATURE_COUNT=10` (oder evtl. höher) bei GetFeatureInfo Requests in map.geo.admin.ch... wie siehst du das?

**Comment by davidoesch** [comment]
@p1d1d1 in line with eCH 0056?
@procrastinatio will we break existing usage? map.geo.admin.ch functions (select by rectangle etc)?
can you upvote /downvote here -- me myself an upvote

**Comment by p1d1d1** [comment]
> @p1d1d1 in line with eCH 0056?
It was not before, it is not now. But doesn't matter, it is at least OGC compliant
