### ISSUE TITLE
Print multiple legends failed

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#4534]
win10 FF IE EDGE Chrome

reproduce

open 
https://s.geo.admin.ch/7dd57634d4

print with legend

result:
pdf only contains  legend of  haltestellen but not of  adressess

expected result
pdf  contains  legend of  haltestellen and  adressess

**Comment by procrastinatio** [comment]
This duplicates https://github.com/geoadmin/mf-geoadmin3/issues/4514
