### ISSUE TITLE
Print multi PDF failed IE

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#4535]
win10 IE Bund

reproduce

open
https://map.geo.admin.ch/?topic=ech&lang=de&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bav.haltestellen-oev,ch.swisstopo.swisstlm3d-wanderwege&layers_visibility=true,false,false,false&layers_timestamp=18641231,,,&E=2666568.29&N=1230411.31&zoom=4

print with Multipdf
result:
pdf generation does not start, stalls at 0%

expected result
pdf generated

Workaround:
work on EDGE

**Comment by procrastinatio** [comment]
Same as https://github.com/geoadmin/mf-geoadmin3/issues/4478 (IE10, IE11)
