### ISSUE TITLE
[MVT] change bg switcher

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#4545]
bg switcher contains
- [x] existing ch.swisstopo.pixelkarte-farbe Color Map Icon
- [x] existing voidLayer "white background  Icon
- [x]  existing ch.swisstopo.swissimage 
- [x] new  Lightbase Map (Instead of Grey map) @pauloamado use Positron https://openmaptiles.org/
- [ ] remove temporary Openmaptiles (for the time beeing until swisstopo finally provides once in the blue moon lightbase and hybrid map)

linked to https://github.com/geoadmin/mf-geoadmin3/issues/4546

**Comment by pauloamado** [comment]
Here is the new bg (png sprite):

1st part is the Hybrid Map
2nd part is the Lightbase Map
3rd part is the regular Color Map

Thx for feedback.
![bg_switcher_vector](https://user-images.githubusercontent.com/6584138/48249530-afc4b200-e3fb-11e8-944a-64c0a2d6e941.png)

**Comment by davidoesch** [comment]
thx!

**Comment by oterral** [comment]
@davidoesch do you really want wmts and void layers  in the bg list ? The point is to force user to test the vector tile layer, if he saves a link with the wmts map I m pretty sure it will not understand why  he can't modify the style anymore.

**Comment by davidoesch** [comment]
Yes we want. Same bg  selector as in current prod. The only thing: grey is replaced with the light basemap. The goal is not only vector tile but also pixel Karte in web Mercator

**Comment by oterral** [comment]
ok

**Comment by loicgasser** [comment]
Fixed
