### ISSUE TITLE
[MVT] logo Edit and mobile third party

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#4546]
Edit logo

![image](https://user-images.githubusercontent.com/4577727/47838821-d5750a00-ddb0-11e8-9b60-a4fa0bae60d6.png)

as same size of for edit in https://mf-geoadmin3.int.bgdi.ch/third_party/index.html?lang=fr&topic=are&bgLayer=omt.vt&E=2568726.58&N=1142792.88&zoom=10&catalogNodes=954,959,965&bgLayer_styleUrl=https:%2F%2Frawgit.com%2Fopenmaptiles%2Fosm-bright-gl-style%2Fmaster%2Fstyle.json 

![image](https://user-images.githubusercontent.com/4577727/47838958-34d31a00-ddb1-11e8-88b6-be58ea87c3c9.png)

for mobile
- we need only external style warning

- no edit (@pauloamado will provide a logo with a more centered person)
![image](https://user-images.githubusercontent.com/4577727/47839020-68ae3f80-ddb1-11e8-96c1-00832d55bb2f.png)

**Comment by loicgasser** [comment]
done on my side

**Comment by pauloamado** [comment]
I propose to use the user-edit icon from Font Awesome:
![icon_edit_vector](https://user-images.githubusercontent.com/6584138/48251415-d84faa80-e401-11e8-8429-cd9a83bd92bf.png)

Here is the result on viewer selector (real size view):
![icon_edit_vector_real_size_view](https://user-images.githubusercontent.com/6584138/48251672-c7536900-e402-11e8-9f27-73f7686da349.png)

For the mobile logo (only style warning) go on using the user icon from Font Awesome, but bigger and centered:
![bg_switcher_vector_mobile](https://user-images.githubusercontent.com/6584138/48253066-b0af1100-e406-11e8-8148-0bd975b9e3bc.png)

**Comment by davidoesch** [comment]
awesome
@loicgasser you can add them to the testviewer

**Comment by pauloamado** [comment]
Here is the new fonts set, with icon "fa-user-edit"
[font-awesome-4.5.0.zip](https://github.com/geoadmin/mf-geoadmin3/files/2565846/font-awesome-4.5.0.zip)

**Comment by loicgasser** [comment]
we should end up with 3 layer right? 
basemap
hybrid
raster color

It's maybe best to wait for actual data, to have the same look and feel.

**Comment by davidoesch** [comment]
See 
https://github.com/geoadmin/mf-geoadmin3/issues/4545
- void layer
- swissimage ( no hybrid layer - swisstopo is Not able to provide it :-( )
- basemap @danduk82  will push it to prod
- pixelkarte

**Comment by pauloamado** [comment]
![bg_switcher_vector](https://user-images.githubusercontent.com/6584138/48330911-a717ea00-e64e-11e8-9e81-99ad240215fc.png) or
![bg_switcher_vector_enhanced](https://user-images.githubusercontent.com/6584138/48330917-a8e1ad80-e64e-11e8-9718-86cb82c5bfa8.png)

**Comment by loicgasser** [comment]
Fixed, there is another Issue open for bg images.
