### ISSUE TITLE
[MVT] Show Openstreetmap crendentials when View port shows non CH area

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#4547]
**as** user /operator

**I want ** to see ""© OpenMapTiles,  OpenStreetMap contributors, swisstopo” with link to https://www.openstreetmap.org/copyright  when in the viewport of the map contains outside of switzerland regions. 

**because** we respect copyrights and  state teh source of map info

 
*Acceptance*
- [ ] if switzerland only area is shwon: only the existing layer  attribution in the footer is shown
- [ ] if outside switzerland area is shown in the viewport : in the footer dynamicyally appears  the  OSM crendential text

*Deliverables:*
- [ ] mf-geo-admin.ch RR

**Comment by loicgasser** [comment]
@davidoesch are we gona use openstreetmap for the alpha viewer? If it is the case you should register and take an api key for openmaptiles.

**Comment by davidoesch** [comment]
osm data will be used via openmaptiles in the two products of swisstopo for the outside of switzerland area ...this will be part of the tile generation process by @danduk82 . we will as well store and provide those tiles on /from our infra and update it

this ticket is only about about showing the foooter content based on the geographic coverage of the view port

**Comment by davidoesch** [comment]
we wait for the data @danduk82

**Comment by loicgasser** [comment]
https://www.maptiler.com/maps/#basic//vector/3/29.35/38.37

**Comment by davidoesch** [comment]
As discussed ""© OpenMapTiles,  OpenStreetMap contributors, swisstopo” for vectortiles BG
