### ISSUE TITLE
[MVT] Zoom In everywhere not only switzerland

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#4557]
Situation

when I zoom in eg on London; I can't 
when I want o pan to London; I can't 

Expected result
the whole world is accessible at full resolution

**Comment by loicgasser** [comment]
only if we end up integrating openmaptiles, it looks like some know how has been lost and current integration of openmaptiles is suboptimal to say the least. I explained @danduk82 what was done with openmaptiles according to me.

**Comment by gjn** [comment]
In sbb sample, we had an application based restriction on where you can zoom in.

Are we sure that this is not active?

Mixed datset (TLM inside swiss, openmaptiles outside) was created using adapted version of tippecanoe. Documentation and code for this should exist.

**Comment by oterral** [comment]
So do we implement it ?  we can specify an extent for each background.

**Comment by davidoesch** [comment]
NTH on hold

**Comment by procrastinatio** [comment]
If the whole Webmercator extent is valid, we won't be able to **guess** LV05 and LV95 because they are valid Webmercator coordinates (see https://github.com/geoadmin/mf-geoadmin3/issues/4618).

**Comment by davidoesch** [comment]
yep... this is a nasty one ... here we need some brainstorming @gjn @procrastinatio ---- 
- we can specify an extent for each background. (well hopefully we will have a global approach)
- remove the guess function

other?
