### ISSUE TITLE
[MVT] F-005 : add Line and Font edit

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#4558]
add the possbility to change
besides color

If font
- [x]   font size
- [x]   font width
if line
- [x]   line width

**Comment by davidoesch** [comment]
https://github.com/geoadmin/mf-geoadmin3/pull/4550

**Comment by davidoesch** [comment]
seems to be done imho

**Comment by loicgasser** [comment]
Yep done
