### ISSUE TITLE
[MVT] F-001 : Link to Advanced edit

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#4559]
Replace in Feedback panel text
"In our service description you'll find more information on how to get started with the vector tiles yourself”
with
”Create your own MapStyle and add it to your wbsite  with the **Advanced Edit Function** or in **our service description** you'll find more information on how to get started with the vector tiles yourself”

- [x]  define msgids for "Create your own MapStyle and add it to your wbsite  with the **Advanced Edit Function**"
- [x] open **Advanced Edit Function** with edit board

**Comment by loicgasser** [comment]
@davidoesch 

Create your own MapStyle and add it to your website with the
Advance Edit Function
or in our
service description
you'll find more information on how to get started with the vector tiles yourself.

for

vector_feedback_getting_started_1
vector_feedback_getting_started_2
vector_feedback_getting_started_3
vector_feedback_getting_started_4
vector_feedback_getting_started_5

please mind the space at the end of msgid for 1 to 4.
