### ISSUE TITLE
[MVT] F-006 Third party style by (source) : you can export but not edit"

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#4561]
When triying edit a third party style as in https://mf-geoadmin3.int.bgdi.ch/mvt/index.html?lang=en&topic=ech&bgLayer=omt.vt&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bav.haltestellen-oev,ch.swisstopo.swisstlm3d-wanderwege&layers_visibility=false,false,false,false&layers_timestamp=18641231,,,&bgLayer_styleUrl=https:%2F%2Fraw.githubusercontent.com%2Fopenmaptiles%2Ffiord-color-gl-style%2Fmaster%2Fstyle.json&E=2601011.88&N=1199625.93&zoom=17 

 Add in 

![image](https://user-images.githubusercontent.com/4577727/48213106-56b63900-e37d-11e8-81ce-c6122b40182c.png)

- [ ] msgid " Third party style by (source) : you can export but not edit"
- [ ] even deactivate the pulldown "Choose layer"
or
- [ ] don't even open the Advanced EDIT mode: only show msgid " Third party style by (source) : you can export but not edit"

**Comment by loicgasser** [comment]
This is a bug it is fixed in https://github.com/geoadmin/mf-geoadmin3/pull/4563

@davidoesch I am asked a question in the Pull request description above, can you try to answer?

**Comment by davidoesch** [comment]
Awg ... Didn't save my answer this morning

Answered again in the pr above

**Comment by davidoesch** [comment]
the 
- [ ] red warning man
- [ ] footer info
is missing
when 
- [ ] loading A B C layer
- [ ] changing  A B C style layer and saving it
- [ ]  having an external style layer

**Comment by pakb** [comment]
as it's a bit of a duplicate of what is described in https://github.com/geoadmin/mf-geoadmin3/issues/4584 I'll take your checklist and copy paste it there and close this issue
