### ISSUE TITLE
[MVT] Advance edit: re-apply last style when edit is activated

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/mf-geoadmin3#4565]
@oterral see discussion in PR description here
https://github.com/geoadmin/mf-geoadmin3/pull/4563

**Comment by oterral** [comment]
You mean: remove the style defined by the feedback driective when we open the advanced edition

**Comment by loicgasser** [comment]
Yes I mean the one we store on bg.olLayer.glStyle

**Comment by oterral** [comment]
ok

**Comment by loicgasser** [comment]
https://github.com/geoadmin/mf-geoadmin3/pull/4580
