### ISSUE TITLE
[MVT] Can t load KML files

### ISSUE THREAD

**Issue by oterral** [geoadmin/mf-geoadmin3#4567]
Steps to reproduce:
 - Open this [link](https://mf-chsdi3.int.bgdi.ch/mvt/shorten/7e340acd52)

----->> A kml should appear

Expected:
  - the kml is displayed

There is an access deny error  on the KML files from public .
@procrastinatio @loicgasser  do you have an idea why ?

**Comment by loicgasser** [comment]
Well service is the same. If I use mf-geoadmin3 master et the mvt branch, the drawing appears.
https://mf-chsdi3.int.bgdi.ch/mvt/shorten/7e35709362

so this was most likely introduced in your last PR with the advance edit.
You can try it out from scratch here as well with a mvt chsdi backend

https://mf-chsdi3.int.bgdi.ch/mvt/shorten/7e35709362

**Comment by oterral** [comment]
I get ids from the service /mvt/files, so there is a problem on sevice side.

**Comment by oterral** [comment]
my bad,  I add ` /files`  in the public url but for KML we don t have it

**Comment by loicgasser** [comment]
fixed
