### ISSUE TITLE
Objekt info: tooltip info stays if iframe is reloaded

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#4568]
Use case:

iframe is used and controlled (new datasets loaded) from outside by meteoschweiz

description

> Ich habe einen kurzen video zu den Objekt-Informationen gemacht:
> 
> Zoom ist realisiert und wir haben entsprechend eine Anpassung gemacht. Für uns OK.
> 
> Objekt-Information: Das Verhalten zeigt sich seit dem von Dir erwähnen Release: Objektinformationen bleiben bei Layerwechsel leer, vgl. Video.
> Auf unserer Seite können wir nicht nachvollziehen, wie es zu diesem Verhalten kommt.
> Ziel: Mit der "gelben" Markierung der Station soll auch die Objekt-Information mit Informationen gefüllt werden und bei einem Layerwechsel (Parameter und/oder Wechsel zwischen "nach Parameter" und "Nach Messnetz") soll die Objekt-Information nicht geleert werden.
> Achtung: wenn die Objekt-Information geschlossen wird, verschwindet auch die gelbe Markierung.

see attached video
[messwerte-objekt-informationen.zip](https://github.com/geoadmin/mf-geoadmin3/files/2572866/messwerte-objekt-informationen.zip)

**Comment by sabine-stauffer** [comment]
Ihr könnt den Fehler/das Problem bei Quatico nachvollziehen:
http://cms.test.mchrel.quatico.com/content/meteoswiss-testpages/de/home/products/mchws-1060-messwertekomponente-v3.html?wcmmode=disabled 
admin
qtc4meteo!

**Comment by gjn** [comment]
Das scheint tatsächlich ein Bug zu sein. Ich kann den ausserhalb des iframes noch nicht reproduzieren. Wäre es möglich den Code zu erhalten, der ausgeführt wird, wenn die Datenquelle in der Parent Applikation geändert wird?

**Comment by davidoesch** [comment]
@gjn Zugriffe auf die Website wo der Code ausgeführt wird via Mail von kw46

**Comment by mbuehrig** [comment]
@gjn Hier der Code den wir verwenden, wenn die Datensource für die Karte ändert (z.B. wenn die Kategorie gewechselt wird.)

```
updateMapSrc: function() {
      if (this.avoidReload) {
        this.avoidReload = false;

        return false;
      }

      var paramID = store.state.selection.subParam ? store.state.selection.subParam.id : store.state.selection.param.id;
      var selectedStation = this.selectedStation;
      var zoom = '1.25';
      var mapSrc = this.patternMapSrc;
      var showTooltip = false;

      mapSrc = mapSrc.replace(/% paramID %/gi, paramID);

      if (selectedStation) {
        showTooltip = true;
        zoom = 3;

        mapSrc = mapSrc.replace(/% paramIDwithStationID %/gi, paramID + '=' + selectedStation.id);
        mapSrc = mapSrc.replace(/% coordinates %/gi, 'Y=' + selectedStation.coordinates[1] + '&X=' + selectedStation.coordinates[0]);
      } else {
        mapSrc = mapSrc.replace(/% paramIDwithStationID %/gi, '');
        mapSrc = mapSrc.replace(/% coordinates %/gi, '');
      }

      mapSrc = mapSrc.replace(/% zoom %/gi, '&zoom=' + zoom);

      mapSrc = mapSrc.replace(/% showTooltip %/gi, showTooltip.toString());
      mapSrc = mapSrc.replace(/% lang %/gi, $('html').attr('lang'));

      this.mapSrc = mapSrc;
    },
```

Zusätzlich verwenden wir einen Template-String der mit Regex ersetzt wird, welches den Link für die Karte generiert. 
`https://map.geo.admin.ch/embed.html?lang=% lang %&topic=ech&bgLayer=voidLayer% zoom %&showTooltip=% showTooltip %&layers=ch.bafu.gefahren-basiskarte,ch.meteoschweiz.% paramID %&ch.meteoschweiz.% paramIDwithStationID %&layers_opacity=0.4,1&% coordinates %"`

Anhand des Strings wird dann die neue URL generiert, welches das iFRame anzeigt.

**Comment by gjn** [comment]
Getestet auf dem aktuellen Testsystem und das Problem scheint mir behoben zu sein.

@mbuehrig Kannst du das bestätigen?

**Comment by mbuehrig** [comment]
Ja scheint behoben zu sein. Danke für die rasche Hilfe.
