### ISSUE TITLE
Search crashes on "ga2"

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#4569]
iOS Safari latest

open app from homescreen

enter in search "ga2"
Application crashes

see screencast here
https://photos.app.goo.gl/BfCVfbTb117r8Kr68

**Comment by danduk82** [comment]
weird

**Comment by procrastinatio** [comment]
Looks ok since https://github.com/geoadmin/service-sphinxsearch/pull/375

**Comment by danduk82** [comment]
@davidoesch can you confirm that the migration to the new version of sphinx solved the issue?

**Comment by davidoesch** [comment]
Fixed- confirmed
