### ISSUE TITLE
[MVT] Translations

### ISSUE THREAD

**Issue by oterral** [geoadmin/mf-geoadmin3#4575]
There is a lot of message to translate, line in shiny green in the google doc

Ask me if you don 't know where the message stands

**Comment by davidoesch** [comment]
changed

vector_feedback_select_style
vector_feedback_description_title
vector_feedback_getting_started_3
vector_feedback_choose_color
edit_glstyle_choose_color
edit_glstyle_choose_layer
landuse-residential
landcover_grass
edit_not_possible
edit_current_layer
edit_fill_color
edit_text_color
edit_text_size
edit_text_halo_color
show
hide
edit_fill_outline_color
edit_line_color
edit_line_width
light_gray
light_green
light_blue
light_yellow
purple
edit_or_reset_style




Question

landuse-residential
landcover_grass

-> For those you should neetd all layers available in ch.swisstopo.leichte-basiskarte (raw)
