### ISSUE TITLE
[MVT] F-001 Simplify feedback window

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#4581]
Remove: choose a layer
Remove  choose a color
Select style pulldown: with BASEMAP and USER defined purple style (applying the same data)
Add:Create your own MapStyle  “EDIT MAP” Button /remove it from getting started
MOVE : Labels on/off to advanced
MOVE : Object information to advanced

![image](https://user-images.githubusercontent.com/4577727/48563973-ca17f780-e8f5-11e8-9f5b-1d381560fad4.png)

**Comment by loicgasser** [comment]
Instead of labels on/off we could enable the user to hide and show each "selectable" layer or category.

Hide landuse or cities names etc...

What do you think @davidoesch and @oterral ?

**Comment by davidoesch** [comment]
Since we don't know yet the final structure of the coming final vectortiles layer: would be quite an effort to switch them on and off. PARETO: A global label on off is currently more feasible... Especially when I think maintenance

**Comment by oterral** [comment]
Yes it s just another style property for me , I can add it in the config. so we can test.
