### ISSUE TITLE
[MVT] F-005 : Group data for advanced mode

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#4582]
It is not possible to get this information (layer list) directly from the tileset(s) listed in ch.swisstopo.leichte-basiskarte.vt - To many layers
->  propose a grouping: focus on all zoomlevel visible

**Comment by oterral** [comment]
With #4589 with use regex to select layers using the id int he glStyle

**Comment by davidoesch** [comment]
done
