### ISSUE TITLE
[MVT] F-001 Feedback window is closed if not vt

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#4583]
Feedback window is closed/does not appear if swissimage , void or pixelmap is active
If WMTS layer
- [x] close feedback window
- [x] Add "TRY THE" Vector map in closed feedback window header

on open this closed feedback panel switch to vector bg map

**Comment by oterral** [comment]
May be a more promotional text will be better than only " Vector Tile BASEMAp" when the feedback is close and we are non-vector-tile-bg.

Something like  :  "Switch to our new ALPHA vector tile  background  clicking here !!!! "  and, on click, you switch to the 'basis' vt layer.

**Comment by davidoesch** [comment]
We can add this in the bG switcher below in red. will talk to Amado

**Comment by davidoesch** [comment]
If WMTS layer
- [ ] close feedback window
- [ ] Add "TRY THE" Vector map in closed feedback window header

on open this closed feedback panel switch to vector bg map

**Comment by oterral** [comment]
Fixed also in #4589
