### ISSUE TITLE
[MVT] Help for style Edit

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/mf-geoadmin3#4585]
![image](https://user-images.githubusercontent.com/3306154/48649773-bafe7b80-e9c1-11e8-80d1-5607655eccde.png)

Once the edit mode is over we should create an help. At the moment it points to the draw help.

**Comment by davidoesch** [comment]
Yes this makes sense. We will have several places where we will have link to the test viewer

**Comment by oterral** [comment]
For the test viewer we just a need an the id in the help.

**Comment by davidoesch** [comment]
https://help.geo.admin.ch/?id=82

It is not used yet but we will set it up as soon as everything is in there

**Comment by loicgasser** [comment]
ping @pauloamado

**Comment by pauloamado** [comment]
Done

**Comment by davidoesch** [comment]
Thx
