### ISSUE TITLE
layers_visibility=false doesn't work for external WMTS layers

### ISSUE THREAD

**Issue by smug007** [geoadmin/mf-geoadmin3#4587]
In the following link one **external** WMTS layer is added. layers_visibility is set to false. If the link is clicked, geo.admin.ch displays the WMTS layer even though it shouldn't. With **internal** WMTS (like slope inclination layer of Swisstopo) there is no such problem.

https://map.geo.admin.ch/?lang=de&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&zoom=7&Y=694000&X=168000&layers=WMTS%7C%7CAvalancheATHM%7C%7Chttps:%2F%2Fmap.skitourenguru.ch%2FATHM_GetCapabilities.xml&layers_opacity=0.3&layers_visibility=false

**Comment by procrastinatio** [comment]
@smug007 Can you check it and give a feedback?

**Comment by smug007** [comment]
Excellent, that bugfix **resolves** the problem.
