### ISSUE TITLE
[MVT] zoom levels are not in line with permalink spec

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#4588]
[ ] zoom parameter is not correct zoom=9
https://mf-geoadmin3.int.bgdi.ch/mvt/index.html?lang=en&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers_visibility=false&layers_timestamp=18641231&E=2662674.85&N=1193252.89&zoom=9
should be  zoom=2
https://map.geo.admin.ch/?lang=en&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers_visibility=false&layers_timestamp=18641231&zoom=2&E=2655000.63&N=1176366.40

- [ ] mapbox  zoomlevel increment is 0.15

[ ] data shown is not correct
Make sure the order of LK is the same as in  https://map.geo.admin.ch/?lang=en&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe for bg 

zoom
on the left current status of https://mf-geoadmin3.int.bgdi.ch/mvt/index.html? on the right how it shoudl e

zoom=2
https://mf-geoadmin3.int.bgdi.ch/teo_refactor/index.html?lang=en&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers_visibility=false&layers_timestamp=18641231&E=2679099.15&N=1175968.84&zoom=9

and 

https://map.geo.admin.ch/?lang=en&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers_visibility=false&layers_timestamp=18641231&E=2631256.58&N=1156500.00&zoom=2

![image](https://user-images.githubusercontent.com/4577727/48757514-4bc4a800-ec9d-11e8-9c7c-09684415f3bf.png)

zoom=3 is ok

zoom=4 
https://mf-geoadmin3.int.bgdi.ch/teo_refactor/index.html?lang=en&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers_visibility=false&layers_timestamp=18641231&E=2679099.15&N=1175968.84&zoom=11

https://map.geo.admin.ch/?lang=en&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers_visibility=false&layers_timestamp=18641231&E=2675000.00&N=1177600.00&zoom=4

![image](https://user-images.githubusercontent.com/4577727/48757557-757dcf00-ec9d-11e8-81e3-2a89f7d6fd10.png)

zoom=5
https://mf-geoadmin3.int.bgdi.ch/teo_refactor/index.html?lang=en&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers_visibility=false&layers_timestamp=18641231&E=2679099.15&N=1175968.84&zoom=12

https://map.geo.admin.ch/?lang=en&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers_visibility=false&layers_timestamp=18641231&E=2675000.00&N=1177600.00&zoom=5

![image](https://user-images.githubusercontent.com/4577727/48757590-921a0700-ec9d-11e8-82ac-478b3a4dc3fa.png)

zoom=6
https://mf-geoadmin3.int.bgdi.ch/teo_refactor/index.html?lang=en&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers_visibility=false&layers_timestamp=18641231&E=2679099.15&N=1175968.84&zoom=13

https://map.geo.admin.ch/?lang=en&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers_visibility=false&layers_timestamp=18641231&E=2675000.00&N=1177600.00&zoom=6

![image](https://user-images.githubusercontent.com/4577727/48757647-bfff4b80-ec9d-11e8-86c7-f84c5ff8d943.png)

zoom=7
https://mf-geoadmin3.int.bgdi.ch/teo_refactor/index.html?lang=en&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers_visibility=false&layers_timestamp=18641231&E=2687851.61&N=1174210.97&zoom=14

https://map.geo.admin.ch/?lang=en&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers_visibility=false&layers_timestamp=18641231&E=2688792.60&N=1173837.46&zoom=7

![image](https://user-images.githubusercontent.com/4577727/48757707-f6d56180-ec9d-11e8-85af-39844e13cbb9.png)

etc

**Comment by loicgasser** [comment]
@davidoesch We can easily map the zoom levels but... We will never have 100% parity as the pyramid is different. Also we will have to introduce negative map zoom levels if we want to support smaller web mercator zoom levels.

At the moment the zoom you see in the permalink is the actual web mercator zoom level requested for the tiles.

Concerning the attribution both are Swisstopo for pixelkarte. So I don't understand your comment.

**Comment by davidoesch** [comment]
@loicgasser : regarding zoomlevel  we need a 99.99%  backward compatibility of the zoomlevel stated in https://api3.geo.admin.ch/services/sdiservices.html#wmts otherwise  we will break to much

for the imagery above data shown is not correct: i added some screenshots above

**Comment by loicgasser** [comment]
@davidoesch
This has to do with the configuration of the WMS sever, not the client.

@ltclm Can we tweak it?

I will change the permalink parameters convert coordinates and zoom levels.
99.99% is impossible. It will be more like 80 to 90% similar. These are the implications of using web mercator.

**Comment by procrastinatio** [comment]
@loicgasser just for the recall, one meter in webmercator does not equal one meter in LV03, hence the resolutions and scales are also very different. 

See https://mf-chsdi3.int.bgdi.ch/mvt/shorten/7e61f4e863

**Comment by ltclm** [comment]
@loicgasser do you mean the scale limits of the pixelmap aggregation?

**Comment by loicgasser** [comment]
Yes

**Comment by loicgasser** [comment]
WMTS CH - Web Mercator
```
            14: 8,
            15: 8,
            16: 9,
            17: 11,
            18: 12,
            19: 13,
            20: 14,
            21: 15,
            22: 16,
            23: 16,
            24: 17,
            25: 17,
            26: 18,
            27: 19,
            28: 21
```

**Comment by davidoesch** [comment]
can we add zoom intermediare in ol? like 17.6 etc

**Comment by ltclm** [comment]
yes we can tweak that in the mapfile, but im not sure at all if we should do that!
web mercator resolution reference is at equator. All the scale or resolution dependent settings in our mapfiles are optimized for resolutions/scales at latitude 46. 
According to https://wiki.openstreetmap.org/wiki/Slippy_map_tilenames#Resolution_and_Scale we would have to either multiply our MAPFILE RESOLUTION with cos(46) or divide all the SCALEDENOM with cos(47) ~ 0.6.

For the pixelkarte config we would have to  replace
```bash
    SCALETOKEN
        NAME "%replace%"
        VALUES
        "0" "/var/local/geodata/bund/swisstopo/cn25/krel10/index_cn25_krel10.vrt"
        "18000" "/var/local/geodata/bund/swisstopo/cn50/krel10/index_cn50_krel10.vrt"
        "35000" "/var/local/geodata/bund/swisstopo/cn100/krel10/index_cn100_krel10.vrt"
        "50000" "/var/local/geodata/bund/swisstopo/cn200/krel10/index_cn200_krel10.vrt"
        "100000" "/var/local/geodata/bund/swisstopo/cn500/krel10/index.vrt"
        "200000" "/var/local/geodata/bund/swisstopo/cn1000/krel10/index.vrt"
        "1000000" "/var/local/geodata/bund/swisstopo/cn1000/web/index.vrt"
        END
    END
```
with 
```bash
    SCALETOKEN
        NAME "%replace%"
        VALUES
        "0" "/var/local/geodata/bund/swisstopo/cn25/krel10/index_cn25_krel10.vrt"
        "27000" "/var/local/geodata/bund/swisstopo/cn50/krel10/index_cn50_krel10.vrt"
        "52500" "/var/local/geodata/bund/swisstopo/cn100/krel10/index_cn100_krel10.vrt"
        "75000" "/var/local/geodata/bund/swisstopo/cn200/krel10/index_cn200_krel10.vrt"
        "150000" "/var/local/geodata/bund/swisstopo/cn500/krel10/index.vrt"
        "300000" "/var/local/geodata/bund/swisstopo/cn1000/krel10/index.vrt"
        "1000000" "/var/local/geodata/bund/swisstopo/cn1000/web/index.vrt"
        END
    END
```
and so on ....

There is also the option to add the argument ``MAP_RESOLUTION`` to the getmap request (when asking for webmercator). Our default RESOLUTION in the mapfiles is 96, knowing that you would have to add MAP_RESOLUTION=64 ``96*cos(47)`` to the webmercator requests to the have the correct scale limits
http://wms-test.dev.bgdi.ch/ltclm/xx/?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=ch.swisstopo.pixelkarte-farbe&CRS=EPSG%3A3857&STYLES=&WIDTH=990&HEIGHT=768&BBOX=923311.5285423445%2C5884791.26139096%2C942229.6930429274%2C5899467.170821715&MAP_RESOLUTION=96

http://wms-test.dev.bgdi.ch/ltclm/xx/?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=ch.swisstopo.pixelkarte-farbe&CRS=EPSG%3A3857&STYLES=&WIDTH=990&HEIGHT=768&BBOX=923311.5285423445%2C5884791.26139096%2C942229.6930429274%2C5899467.170821715&MAP_RESOLUTION=64

**Comment by ltclm** [comment]
there's also an interesting discussion about "scale calculation" with web mercator here https://trac.osgeo.org/mapserver/ticket/309

an inactive issue:
https://github.com/mapserver/mapserver/issues/3265

webmercator, wgs84 cannot be used with scale dependant layer configurations because the scale is not stable in north/south direction.

**Comment by loicgasser** [comment]
@ltclm there is a testlink in geoadmin here: https://mf-geoadmin3.int.bgdi.ch/mvt_permalink/index.html

So the idea is to take a geoadmin permlink with CH zoom=0 (8 for tile addresses) et we should see 
the same pixelmap aggregation.

Compare for zoom 0:
https://mf-geoadmin3.int.bgdi.ch/mvt_permalink/index.html?zoom=0&E=2658500.00&N=1200000.00
https://map.geo.admin.ch?zoom=0&E=2658500.00&N=1200000.00

and so on...

the geoadmin app will detect that it is a CH permalink because of `E` and `N` and will transform the zoom level into an absolute Web Mercator zoom level. Parameters `E` and `N` are also removed and converted to `lon` and `lat`.

At the moment I am working with integer zoom levels only, but I will try to use decimal zoom levels as well to use the client zoom and have an extent that is more similar to the CH ones.

**Comment by loicgasser** [comment]
What about using `MAP_RESOLUTION=64` in service proxywms?

**Comment by loicgasser** [comment]
@ltclm now I cheated as much as I can for permalink compatibility using client zoom out and requesting the next set of tiles whenever I can.

I remember customers were asking about that. I think using map_resolution for wgs and web mercator would be a great improvement, but I know it implies flushing the cache for both projections.
ping @danduk82

**Comment by ltclm** [comment]
if there are now side effects with symbol size etc. we could do add this to proxywms for all layers in wgs84 and web mercator, but we have to check that first...

**Comment by davidoesch** [comment]
@gjn tbd

**Comment by gjn** [comment]
I didn't analyse in detail. I looked at it back in the day when we started doing 3D. I've attached an excell sheet listing zoom levels of systems and their respective resolution.
[wmts_and_lod.xlsx](https://github.com/geoadmin/mf-geoadmin3/files/2615150/wmts_and_lod.xlsx)

In general, I would not try to solve a problem that is not clearly a problem (yet). We have a test/alpha phase for exactly these reasons. Let's focus on the MVP (minimal viable product), continue with in-app transformation (as @loicgasser did, can you create a PR?)  and adapt backends once we have feedback. Let's also not forget that we do webmercator wmts for years now and while it's not used heavily, it is used and rarely do we have negative feedback.

I would also create a document with typical use cases that _could_ be problematic and compare lv95 map.geo with web-mercatro map.geo; as @loicgasser did in the comments here (showing the overview map). So I would do 2 things now:

[ ] Finishe the code that @loicgasser started to transform in-app and create PR
[ ] Chooses some uses cases to show the potential problems in an excel sheet or wiki (collect them)

I would NOT start tangling with WMS configuration, proxywms configuration, etc. now.

**Comment by gjn** [comment]
@loicgasser Regarding the matching, I have a slighlty different matching between zoom levels than yours. I corrected for latitutde and have the following matching:

WMTS CH - Web Mercator
```
            14: 7,
            15: 8,
            16: 9,
            17: 10,
            18: 11,
            19: 12,
            20: 13,
            21: 14,
            22: 15,
            23: 16,
            24: 16,
            25: 17,
            26: 18,
            27: 19,
            28: 20
```
I've attached my calc sheet here.
[wmts_and_lod.xlsx](https://github.com/geoadmin/mf-geoadmin3/files/2618601/wmts_and_lod.xlsx)

**Comment by davidoesch** [comment]
hmm using &E=2682200.00&N=1193000.00&zoom=0 it results in a blurry image 
![image](https://user-images.githubusercontent.com/4577727/49139426-11d55080-f2f2-11e8-83d0-ca7e361bc573.png)
compared to
![image](https://user-images.githubusercontent.com/4577727/49139451-21549980-f2f2-11e8-88a4-b5c9587a1762.png)

**Comment by loicgasser** [comment]
Reprojection + Client zoom

**Comment by loicgasser** [comment]
With the current services it's the best we can do for now. I cheated a LOT on the client already.

**Comment by davidoesch** [comment]
if @loicgasser  says "best we can do" --- #godmode is next level

-> ok then let it be for the time now

**Comment by davidoesch** [comment]
Seems not in line anymore

since 


https://map.geo.admin.ch/?zoom=9

and

https://test.map.geo.admin.ch/?zoom=9

are now different ....they were more close during acceptance phase

**Comment by danduk82** [comment]
ping @pakb can you check please?

**Comment by davidoesch** [comment]
My fault: needs to enter as well x and y
https://map.geo.admin.ch/?lang=en&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers_visibility=false&layers_timestamp=18641231&E=2641022.43&N=1170639.12&zoom=7

the it works  
https://test.map.geo.admin.ch/?lang=en&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers_visibility=false,false,false,false&layers_timestamp=18641231,,,&zoom=10.50&lon=7.974866434400536&lat=46.6857139327634&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bav.haltestellen-oev,ch.swisstopo.swisstlm3d-wanderwege

**Comment by davidoesch** [comment]
@boecklic here is a testlink for the redirection https://cms.geo.admin.ch/test/ol6/Comparepermalink.html

**Comment by boecklic** [comment]
> My fault: needs to enter as well x and y
> https://map.geo.admin.ch/?lang=en&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers_visibility=false&layers_timestamp=18641231&E=2641022.43&N=1170639.12&zoom=7
> 
> the it works
> https://test.map.geo.admin.ch/?lang=en&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers_visibility=false,false,false,false&layers_timestamp=18641231,,,&zoom=10.50&lon=7.974866434400536&lat=46.6857139327634&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bav.haltestellen-oev,ch.swisstopo.swisstlm3d-wanderwege

If you specify E and N, then the zoom parameter in the url is interpreted as LV95 zoom and recalculated to webmercator zoom level resulting in a intermediate (e.g. 10.5 for 7) zoom level, if you just load the app then you get the full-number webmerc zoom steps, which lie in between the ones of LV95
