### ISSUE TITLE
permalink: external URL is removed

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#4592]
resolve
https://s.geo.admin.ch/7e34cec471

permalink of external URL is removed

**Comment by procrastinatio** [comment]
WMS title was not meant to write a short novel: if you remove coma in  `Satellitenbild, METEOSAT, RGB, bereinigt um Schnee, Eis und Nebel, reines Wolkenbild, 3 stündige Auflieferung` it is OK.

This work

https://map.geo.admin.ch/?lang=fr&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=WMS%7C%7CSatellitenbild%7C%7Chttps:%2F%2Fmaps.dwd.de%2Fgeoproxy%2Fservice%3F%7C%7CSAT_EU_central_RGB_cloud%7C%7C1.3.0%7C%7Ctrue&E=2691250.00&N=1179500.00&zoom=2

**Comment by davidoesch** [comment]
OK... Got it. Will tell the Geo community that interoperability will work for poems not novels
