### ISSUE TITLE
IE11 3D controls are not centered

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#4600]
open on win10 office bit laptop 3d

https://map.geo.admin.ch/?topic=ech&lang=de&bgLayer=voidLayer&layers=ch.swisstopo.zeitreihen,ch.swisstopo.swissnames3d&layers_timestamp=19501231,&lon=8.37866&lat=46.93821&elevation=3431&heading=318.131&pitch=-28.214&time=1950

switch to 3d

left aligned controls instead centered controls

![image](https://user-images.githubusercontent.com/4577727/49142507-3a147d80-f2f9-11e8-8412-84065ee7f4d1.png)

and 3d in edge is way faster than  in chrome

**Comment by pakb** [comment]
fixed by https://github.com/geoadmin/mf-geoadmin3/pull/4630
