### ISSUE TITLE
3D Control and time: play button missing

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#4601]
EDGE CHROME

switch to zeitreise and 3d
![image](https://user-images.githubusercontent.com/4577727/49142653-9c6d7e00-f2f9-11e8-95de-c1f766da15be.png)

button missing

**Comment by procrastinatio** [comment]
Was never active in 3D

https://github.com/geoadmin/mf-geoadmin3/blob/master/src/components/timeselector/partials/timeselector.html#L16

**Comment by davidoesch** [comment]
A pity..

**Comment by procrastinatio** [comment]
No feedback. Considered done.

**Comment by davidoesch** [comment]
Well it would have been nice
