### ISSUE TITLE
[MVT] Translation

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#4603]
Changed all the  yellow parts in the translation sheet, you can
- [x] update it

then:
for the layers shown: you proposed to group it automatically as shown in https://github.com/geoadmin/mf-geoadmin3/issues/4582 
so we don't actually need the translation for 
- [ ] roadtraffic
- [ ] hydrology
- [ ] landuse
- [ ] settlement
- [ ] landuse-residential
- [ ] landcover_grass

since you can use the raw group layer

in Edit Mode and label/text there is the button none/visible
- [x] use the msgid SHOW  and HIDE for it
- [x]  edit_visibility you can remove it, since "visibility " is not needed if you use SHOW and HIDE

**Comment by loicgasser** [comment]
![image](https://user-images.githubusercontent.com/3306154/49190183-4b807880-f33f-11e8-8ba2-275e66b22a16.png)

Carte de base light is too long in french and italian.
Proposal -> stick to "Carte de base"

**Comment by loicgasser** [comment]
Fixed in https://github.com/geoadmin/mf-geoadmin3/pull/4523/commits/02269aeb06cf482c52331007802714d3611cd1db
and
https://github.com/geoadmin/mf-geoadmin3/pull/4523/commits/6921e272764636c2ccbaa0a7ebd6421b27438c20

**Comment by davidoesch** [comment]
Ok .. we Stick To carte de base

**Comment by oterral** [comment]
@davidoesch  yes we need roadtraffic, settlement, .... . These are the ids of group displayed in the select box.

**Comment by davidoesch** [comment]
swisstopo will change translation for 

roadtraffic
hydrology
landuse
settlement

https://docs.google.com/spreadsheets/d/1bRzdX2zwN2VG7LWEdlscrP-wGlp7O46nvrXkQNnFvVY/edit#gid=54811248

**Comment by davidoesch** [comment]
done @loicgasser

**Comment by oterral** [comment]
Trad on mvt branch
