### ISSUE TITLE
[MVT] footer links

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#4604]
if 

basemaplight or OSM bg is shown: footer has a link

"© OpenMapTiles, OpenStreetMap contributors, swisstopo” **with link ** to https://openmaptiles.org/, https://www.openstreetmap.org/copyright

**Comment by davidoesch** [comment]
iOS Chrome and Safari. Footer not shown on test.map.geo.admin.ch.very same device for map.geo.admin.ch it works
![EBD2F385-80A6-4008-8BDD-43E50FFC5916](https://user-images.githubusercontent.com/4577727/57102438-c5b88d00-6d23-11e9-8339-db46dcc0311c.jpeg)

**Comment by davidoesch** [comment]
Reported by: https://twitter.com/luxperisa/status/1124036218168184838?s=21

**Comment by boecklic** [comment]
currently the footer (visible on desktop) says "geo.admin.ch   Copyright & data protection" (both parts with links, where the second one points to https://www.geo.admin.ch//about-swiss-geoportal/impressum.html#copyright, which doesn't exist). What's the correct swisstopo copyright link?

**Comment by pakb** [comment]
seems like the page URL changes depending on the lang, see https://www.geo.admin.ch/de/ueber-geo-admin/impressum.html for instance.
So it seems also related to the issue https://github.com/geoadmin/mf-geoadmin3/issues/4913 as there's not `langId` in the URL you've linked

**Comment by boecklic** [comment]
True, but the main problem is that the attribution is not shown for the vector tiles layer (all OS, all Browser)

**Comment by pakb** [comment]
test link on https://github.com/geoadmin/mf-geoadmin3/pull/4917

**Comment by davidoesch** [comment]
Not good on iPhone/mobile. It has to look like  Re3
