### ISSUE TITLE
[MVT] Navigation Vector edit switch IOS crashes

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#4607]
_OS/Device_
iphone Ios latest chrome and safari

_Steps to reproduce_

1.        Open application  https://mf-geoadmin3.int.bgdi.ch/mvt/index.html?
try to  change bg

_result_
see crash
https://photos.app.goo.gl/fEpkGnXGTZUjrKKy6

_expected result_
 works

_Workaround:_
none

**Comment by davidoesch** [comment]
It barely works on iOS....

**Comment by loicgasser** [comment]
The reason is ol + under-optimized data.

I found out we were also downloading the ovt layer with the light base map.
I removed it in https://github.com/geoadmin/mf-geoadmin3/pull/4613 so it should be a little better.

**Comment by davidoesch** [comment]
Slightly better Performance. But the basemap does only load the hill shade on iOS and some labels. Let's wait for v004 of the swisstopo vec tiles

**Comment by davidoesch** [comment]
wo wow wow wow ---- it works now on iOS and EDGE and FIREFOX on desktop!!!

the lag we have now is  actually  the high res hillshade

@mariokeusen @AFoletti @gjn @boecklic @pakb @Brunim28 
Can  you give it a quick try on your perso mobile / and gov laptop EDGE? https://mf-chsdi3.int.bgdi.ch/mvt/shorten/7ee929ad7d 
and give an up downvote if it is better than before?

**Comment by davidoesch** [comment]
@oterral compare mode broken 
https://mf-chsdi3.int.bgdi.ch/mvt/shorten/7eec819ad6

**Comment by oterral** [comment]
probably the update of ol

**Comment by loicgasser** [comment]
Just grep precompose / postcompose

**Comment by pakb** [comment]
Faster navigation on EDGE and IE11 (on gov laptop).
Only downside is that I can still see quite often the hillshade layer when zooming.

**Comment by davidoesch** [comment]
The hill shade is just loaded earlier since it loads faster than vec tiles.
The vec team works high prio to include either hill shade into the pbf or remove it completely

**Comment by oterral** [comment]
Without a lot of tiles cached, there is no interim tiles displayed between 2 zoom levels  that why we see the hillshade often. But bigger is the tile cache size sooner the app will crash on ios. I put 20 as tile cache size it seems to reduce this effect.

**Comment by davidoesch** [comment]
seems not yet in https://mf-geoadmin3.int.bgdi.ch/teo_opti_ios/index.html or https://mf-geoadmin3.int.bgdi.ch/mvt/index.html

**Comment by loicgasser** [comment]
Have you tried the mvt branch?

**Comment by davidoesch** [comment]
I Get only a white BG and a lot of 400 for the https://wmts100.bgdi.ch/1.0.0/ch.swisstopo.swissalti3d-reliefschattierung/default/current/3857/8/128/128.png

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>400 Bad Request</title>
<h1>Bad Request</h1>
<p>Tile out of bounds 8/128/128</p>

**Comment by loicgasser** [comment]
That s a side effect of going global! We need to add a default extent to all layers except the background layers. Ping @procrastinatio

**Comment by davidoesch** [comment]
Ping @procrastinatio

**Comment by davidoesch** [comment]
Hi @oterral  we think that this is a defect. we solved this already for 3d
"default extent to all layers except the background layers" we solved this already in 3d on application side.. you remember?

**Comment by oterral** [comment]
the problem is https://github.com/geoadmin/mf-geoadmin3/issues/4686#issuecomment-453012913 no?

**Comment by oterral** [comment]
@davidoesch I see what you mean I set the default extent to the swissExtent for layers of bod except vectortile

**Comment by oterral** [comment]
Should be fixed by https://github.com/geoadmin/mf-geoadmin3/pull/4523/commits/8353462187a830bb233aed64a1b66e05145dce27

**Comment by oterral** [comment]
I also fix the extent for vectortile layer with https://github.com/geoadmin/mf-geoadmin3/pull/4523/commits/5b89c77013634340897f450b163ad3396999f094 , no more empty tile loaded normally.

**Comment by davidoesch** [comment]
imho fixed @pakb  I close therfore
