### ISSUE TITLE
[MVT] 3D mode is not available

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#4611]
_OS/Device_
all OS /Browsers

_Steps to reproduce_
start https://mf-geoadmin3.int.bgdi.ch/mvt/index.htm

_result_
no 3d Button

_expected result_
3d Button available, greyed /deactaived out when in vectormode (if we can't run it in 3d)

_Workaround:_
None

**Comment by loicgasser** [comment]
Ok, 3d is simply deactivated. Because we also have swissimage.
Out of 4 layers, 2 are not 3d compatible.

**Comment by davidoesch** [comment]
sad but true--- but we would like to test it. add it

**Comment by loicgasser** [comment]
Fixed
