### ISSUE TITLE
[MVT] Offline save does not work

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#4612]
_OS/Device_
iOS Safari Chrome

_Steps to reproduce_
switch to BG swissimage or pixelkarte or vector tiles
try to save  extend

_result_

download stops at 0% for raster

_expected result_
Raster  offline works
vector offline does work s as well or show warning: " disabled in this version"

_Workaround:_
None

**Comment by oterral** [comment]
For each zoom level we generate the list of tiles to download:
    - bg layer: zoom 8 to 16 => 15km2 extent
    - other layers: zoom 12,14,16 => 15km2 extent

**Comment by davidoesch** [comment]
to be tested by @davidoesch

**Comment by davidoesch** [comment]
offline does not work with vectortiles..only hillshade @oterral

**Comment by oterral** [comment]
It works on Chrome desktop. I think the branch teo_offline could be merged like this, since we deactivate the offline button. 
For mobile I think we reach the max rendering capability of the mobile.

**Comment by oterral** [comment]
Has been decided to deatcivate for alpha in #4657
