### ISSUE TITLE
KML tooltip don't work as before

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#4616]
Customer feedback

> Wir haben ein Problem mit KMLs, welche kürzlich noch funktioniert haben.
> 
> Auf dieser Seite:
> https://www.wandern.ch/de/shop?cat=165 
> 
> haben wir ihr iframe eingebunden. Darin enthalten ist die Blatteinteilung von Wanderkarten.
> Wann man nun auf ein Rechteck klickt, müsste sich ein Layer mit Infos öffnen – tut es aber seltsamerweise nicht mehr. Ich weiss nicht, seit wann es nicht mehr geht, aber dies hat definitiv unlängst noch problemlos funktioniert.
> 
> Wenn ich das KML in Google Earth öffne, werden die Layers bei Klick eingeblendet. Wenn ich das selbe KML ins Browserfenster von map.geo.admin.ch schiebe, funktionieren die Layers nicht.
> 
> Das KML finden Sie im Attachment oder live hier:
> https://www.wandern.ch/tmp/shopkml/de-165.xml
> 
> 
> [test.zip](https://github.com/geoadmin/mf-geoadmin3/files/2638513/test.zip)

**Comment by davidoesch** [comment]
ping @procrastinatio

**Comment by procrastinatio** [comment]
This is because the ways geometries are handleld in OL5.
A not filled polygon is treated as a polyline. The tooltip is OK, but you have to click on the line.

If you want a polygon, you have to fill it.

See https://s.geo.admin.ch/7ea40df3eb

Filled polygons is the above link are clickable (the colored ones or the ones with thicker lines)

``` 
                <Style>
                    <LineStyle>
                        <color>ffdb0000</color>
                        <width>2</width>
                    </LineStyle>
                    <PolyStyle>
                        <color>00db6d58</color>   <!-- this is fully transparent -->
                        <fill>1</fill>   <!-- this is a polyon -->
                    </PolyStyle>
                </Style>
```

**Comment by silvercode-ch** [comment]
Thanks @procrastinatio, this works.

**Comment by davidoesch** [comment]
in this case--will close the issue
