### ISSUE TITLE
[MVT] localization: wrong results for search with LV03 and LV95 coordinates

### ISSUE THREAD

**Issue by mariokeusen** [geoadmin/mf-geoadmin3#4618]
OS: WIn 10, desktop, Chrome (same issue also on EDGE)
Steps to reproduce: open app, enter "600000 200000" (or "2600000 1200000") into the search field
Result: app pans/zooms somewhere northeast of Stockholm, Sweden
Expected: app pans/zooms to Berne, Switzerland as on productive map.geo.admin.ch

**Comment by mariokeusen** [comment]
Related to this: also the Swiss coordinates in the position window are wrong. Here what the app returns in Berne: 
![image](https://user-images.githubusercontent.com/4577749/49374864-f0fe6800-f702-11e8-847c-db4a57b3aa45.png)

**Comment by procrastinatio** [comment]
Now we try to guess what the user inputs based on the extent of LV03, LV95 and WGS84. 
Is Webmerc extent restricted to Switzerland? If yo, me may assume northing larger than 5'000'000 to be Webmerc, if not we cannot guess.

**Comment by procrastinatio** [comment]
Fixed with https://github.com/geoadmin/mf-geoadmin3/pull/4625

**Comment by procrastinatio** [comment]
Small side remarks. 
Apparently, we are now global (see https://github.com/geoadmin/mf-geoadmin3/issues/4631)
There is **no** way to guess what system a user is using, as all LV95 and LV03 coordinates are also valid Webmercator coordinates.

**Comment by p1d1d1** [comment]
What about "synchronizing" the search with the SRS selected in the pull-down menu bottom left?

**Comment by davidoesch** [comment]
+1 for Pasquales proposal. Needs a hint when entering coordinates in the search field

**Comment by loicgasser** [comment]
Coordinates in search are ok bow. We need to fix the context popup.

**Comment by p1d1d1** [comment]
@loicgasser 
Not in here: https://mf-chsdi3.int.bgdi.ch/mvt/shorten/7ea9d07d3a
Try with 2563937 1129848 (EPSG:2056) and 775944 5831628 (corresponding EPSG:3857)

**Comment by loicgasser** [comment]
Swiss coords do work. Web merc don't because we have feature parity with prod. Try F5

**Comment by procrastinatio** [comment]
We are global now:  https://github.com/geoadmin/mf-geoadmin3/issues/4631

**Comment by procrastinatio** [comment]
If we do not have interest in regions like the Gulf of Guinea (Sao tome e Principe), the south sudanese border and a tiny region at almost 0,0 degree (see areas in red on https://mf-chsdi3.int.bgdi.ch/mvt/shorten/7eaaa3890c)
we may still assume that these projected coordinates are LV03 and LV95 respectively.

**Comment by davidoesch** [comment]
Not a real clean solution.... But very very simple.... I do like

**Comment by procrastinatio** [comment]
IMHO, nobody uses Web Mercator coordinates (im meters)  for real. So we use something real like WGS84 and UTM (and MGRS, three words, etc.) , which are widely used, an everything which looks like metrics is Swiss grids (old or new). We don't break anything.

**Comment by loicgasser** [comment]
This is fixed
