### ISSUE TITLE
[MVT] attribute search: wrong results and visualization gets lost when zooming to object

### ISSUE THREAD

**Issue by mariokeusen** [geoadmin/mf-geoadmin3#4620]
OS: Win10, desktop, Chrome and also EDGE
steps to reproduce: open app, add the layer ch.bazl.luftfahrthindernis to the map, search for  object "253-BE-10067". Click the object in the search result list
Result: map zooms to object with the object highlighted, but: the tooltip of a different object ("253-BE-101") appears and the map is empty apart from the highlighted object.
Expected: map zooms to object with the object highlighted, correct tooltip is shown and the backgroundmap and data layers stay the same.
Remarks: 
1) after that search operation, when I am zooming out, I find myself somewhere outside Switzerland
2) the object search on the same layer works well on productive map.geo.admin.ch

**Comment by procrastinatio** [comment]
Fixed with https://github.com/geoadmin/mf-geoadmin3/pull/4625

**Comment by oterral** [comment]
because this is not merged in chsdi mvt branch https://github.com/geoadmin/mf-chsdi3/pull/3030

**Comment by oterral** [comment]
so we receive the result in 2056. @davidoesch @procrastinatio  re-assign me if you prefer we hack the frontend.

**Comment by davidoesch** [comment]
Fixed
