### ISSUE TITLE
[MVT] use latest master of ol5 to improve perfomance

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#4622]
Hi Oli/Loic

Since the test even on openmaptiles  (an not only the swisstopo basemap light) are not that promising regarding performance

Would it be possible to create a branch with the latest ol5.3 master which includes the code sprint results like

The essential of the work done is here: https://github.com/openlayers/openlayers/pull/8923
•	Add rendering metrics, and comparison between branches: https://github.com/openlayers/openlayers/pull/8921
•	Remove WebGL core code, and add a specific WebGL layer for heatmap as an example https://github.com/openlayers/openlayers/pull/8951
•	Regactor replay group creation and rendering to prepare work for the webworker https://github.com/openlayers/openlayers/pull/8926
•	Many other improvment like https://github.com/openlayers/openlayers/pull/8924

thanks

**Comment by loicgasser** [comment]
Well it is still work in progress. This might break other things, they still come up with fixes related to the refactoring. I would wait for an official release

**Comment by davidoesch** [comment]
Cc @danduk82 @gjn 
Tbd

**Comment by loicgasser** [comment]
We can maybe just give it a try and test well separately.

**Comment by oterral** [comment]
I guess the update to ol 5.3.0 is doable easily, but for the master is a bit soon I guess. But I can try and see if something fails.

**Comment by davidoesch** [comment]
Oli tested  the last version -- vector perfomance is not yet incorperated. test by @oterral
