### ISSUE TITLE
[MVT] Navigation: iOS Safari panning+zooming+ rotate does not work

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#4627]
OS: iOS latest SAFARI
Test Navigation -> Issue:
Zooming +/- in general very unreliable, after a few zoom in / out cycles content is lost..

To reproduce:
Open application
pan & zoom 
Rotate
Zooming +/- in general very unreliable, after a few zoom in / out cycles content is lost..
independend of background

Expected Results:
pan and zoom and rotate works

workaround: using Chrome APP on the same device  works flawless

**Comment by davidoesch** [comment]
inform user with warning to use  CHROME

**Comment by loicgasser** [comment]
So if we have https://github.com/geoadmin/mf-geoadmin3/issues/4652 this should be enough right?

**Comment by davidoesch** [comment]
correct-- its related to ol5

**Comment by oterral** [comment]
@davidoesch  I just saw diese bug: https://github.com/openlayers/openlayers/issues/8956#issuecomment-443230474  maybe it 's related for ios problem.
