### ISSUE TITLE
[MVT] Vector Advanced Edit : color in hex instead of names

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#4629]
OS: iOS latest SAFARI and CHROME

To reproduce:
Open application
Edit modus
change color

Result:

![image](https://user-images.githubusercontent.com/4577727/49460544-d5be5600-f7f1-11e8-99da-ae7284696603.png)

Expected Results:
no hexedec

**Comment by oterral** [comment]
That s the current value in the style , before modification. We can t which color is it. Do you prefer we display  somthing like  "curent value"  or "default" or  we don t displax it ?

**Comment by davidoesch** [comment]
+1 for current value
