### ISSUE TITLE
[MVT] WM(T)S IMPORT: cover now global imports

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#4631]
OS: all OS all Browser

To reproduce:
open basemap.at 
https://mf-geoadmin3.int.bgdi.ch/mvt_ovt/index.html?topic=ech&lang=en&bgLayer=ch.swisstopo.pixelkarte-farbe&lon=11.47744&lat=47.15315&zoom=7&layers=WMTS%7C%7Cbmaphidpi%7C%7Chttp:%2F%2Fwww.basemap.at%2Fwmts%2F1.0.0%2FWMTSCapabilities.xml

or

https://mf-geoadmin3.int.bgdi.ch/mvt_ovt/index.html?topic=ech&lang=en&bgLayer=ch.swisstopo.pixelkarte-farbe&lon=11.47744&lat=47.15315&zoom=7&layers=WMTS%7C%7CWorld_Street_Map%7C%7Chttps:%2F%2Fservices.arcgisonline.com%2Farcgis%2Frest%2Fservices%2FWorld_Street_Map%2FMapServer%2FWMTS%2F1.0.0%2FWMTSCapabilities.xml
Result:

clipped at old LV95 tileset border

Expected result:
I See now the whole world...this is the whole point about webmercator and its chances for interoperability

**Comment by procrastinatio** [comment]
See https://github.com/geoadmin/mf-geoadmin3/pull/4637
