### ISSUE TITLE
[MVT] Landscape Mode : zoom out not result in no tiles shown

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#4635]
OS: iOS, safari and chrome on iphone 7s

To reproduce:
https://mf-geoadmin3.int.bgdi.ch/mvt/index.html?topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bav.haltestellen-oev,ch.swisstopo.swisstlm3d-wanderwege,ch.swisstopo.hiks-dufour,ch.swisstopo.fixpunkte-agnes&layers_visibility=false,false,false,false,true,true&layers_timestamp=18641231,,,,,&lang=en&E=2603250.00&N=1192250.00&zoom=5

then zoom out
Result:

https://photos.app.goo.gl/8fSW4E9nNcLH724n7

white out

Expected result:
tiles always shown

**Comment by loicgasser** [comment]
Not based on mvt branch. This is @procrastinatio branch based on master.

**Comment by davidoesch** [comment]
also valid for https://mf-geoadmin3.int.bgdi.ch/mvt/index.html?topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bav.haltestellen-oev,ch.swisstopo.swisstlm3d-wanderwege,ch.swisstopo.hiks-dufour,ch.swisstopo.fixpunkte-agnes&layers_visibility=false,false,false,false,true,true&layers_timestamp=18641231,,,,,&lang=en&E=2603250.00&N=1192250.00&zoom=5

**Comment by procrastinatio** [comment]
@loicgasser ?

**Comment by oterral** [comment]
I think it s just slow

**Comment by oterral** [comment]
or maybe related to the failed offline cache.

**Comment by davidoesch** [comment]
- [ ] limit to zoom out to zoom=4 if there wmts/wms/ geo.admin.ch  shown
- [ ] maybe fixed with https://github.com/geoadmin/mf-geoadmin3/issues/4612

**Comment by davidoesch** [comment]
@oterral @loicgasser *not* fixed with #4612 tested with https://github.com/geoadmin/mf-geoadmin3/pull/4643
try to limit the zoom

**Comment by davidoesch** [comment]
fixed
