### ISSUE TITLE
Build is broken

### ISSUE THREAD

**Issue by gjn** [geoadmin/mf-geoadmin3#4641]
Build is broken for most users (ltclm had problems yesterday, I have now and pascal as well) since https://github.com/geoadmin/mf-geoadmin3/pull/4590

And it's hard getting in to run again.

**Comment by gjn** [comment]
Here's the error we get:

```
/bin/bash: line 2: nvm: command not found
Makefile:289: recipe for target 'env' failed
```

Executing nvm on the cmdline outside of make works fine.

**Comment by gjn** [comment]
Funny thing: `source rc_user_ltjeg && make all` works, but `make user` doesn't.

**Comment by davidoesch** [comment]
update?

**Comment by pakb** [comment]
It should be fixed by this PR : https://github.com/geoadmin/mf-geoadmin3/pull/4642 but there still seems to be an issue with it (with ng-annotate)

**Comment by oterral** [comment]
It works yes but very slow because of ng-annotate
