### ISSUE TITLE
[MVT] Search broken

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#4651]
all OS all browsers

open https://mf-geoadmin3.int.bgdi.ch/mvt/index.html?

enter  chur in search

nothing happens

**Comment by oterral** [comment]
@davidoesch  it seems sphinx has been updated on a new infra maybe mvt branch point to the old 'non existing animore' infra . @danduk82 ?

**Comment by danduk82** [comment]
possible. yes. @ltclm what do you think, should we rebase chsdi3 MVT branch on current master, or cherry-pick the commits that put the new sphinx online?
@procrastinatio and @ltclm can you check what it is better to do?
thanks in advance

**Comment by ltclm** [comment]
you have to cherry-pick this commit
https://github.com/geoadmin/mf-chsdi3/commit/5afb41b866bb6516eff396c8805012a3e266b3c9

**Comment by danduk82** [comment]
@procrastinatio can you take care of it please?

**Comment by procrastinatio** [comment]
Without further notice, I'll merge `webmerc` into master.

**Comment by danduk82** [comment]
tests are still failing : https://github.com/geoadmin/mf-chsdi3/pull/3030

I call you at 16:30 and we can do a code review before merging

**Comment by procrastinatio** [comment]
Or use it with my branch https://mf-chsdi3.int.bgdi.ch/webmer

[https://mf-geoadmin3.int.bgdi.ch/mvt/index.html?api_url=//mf-chsdi3.int.bgdi.ch/webmerc](https://mf-geoadmin3.int.bgdi.ch/mvt/index.html?api_url=//mf-chsdi3.int.bgdi.ch/webmerc)

**Comment by loicgasser** [comment]
@procrastinatio we also need the style service from mvt branch in chsdi.

**Comment by danduk82** [comment]
IMO we must:
- merge webmerc into master
- rebase mvt

**Comment by loicgasser** [comment]
well because we need a working version of mvt, I'll rebase mvt on master. This should fix the search issue.

**Comment by danduk82** [comment]
agree, or cherry-pick the commit pointed by @ltclm

**Comment by loicgasser** [comment]
ok rebased and deployed
