### ISSUE TITLE
[MVT] Openmaptiles is not cut

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/mf-geoadmin3#4653]
The base configuration file is https://vectortiles.geo.admin.ch/gl-styles/ch.swisstopo.leichte-basiskarte.vt/v004/style.json

These are the sources defined:

```json
sources: {
ch.swisstopo.vektorkarte.vt: {
url: "https://vectortiles.geo.admin.ch/mbtiles/ch.swisstopo.vektorkarte.vt/v004.json",
type: "vector"
},
ch.swisstopo.swissnames3d: {
url: "https://vectortiles.geo.admin.ch/mbtiles/ch.swisstopo.swissnames3d/v004.json",
type: "vector"
},
ch.swisstopo.amtliches-strassenverzeichnis_validiert: {
url: "https://vectortiles.geo.admin.ch/mbtiles/ch.swisstopo.amtliches-strassenverzeichnis_validiert/v001.json",
type: "vector"
},
ch.bav.haltestellen-oev: {
url: "https://vectortiles.geo.admin.ch/mbtiles/ch.bav.haltestellen-oev/v001.json",
type: "vector"
},
ch.swisstopo.swissalti3d-reliefschattierung: {
url: "https://vectortiles.geo.admin.ch/json/relief.json",
type: "raster"
},
OpenMapTiles: {
url: "https://vectortiles.geo.admin.ch/mbtiles/osm-2017-07-24-v3.6.2-europe-cut-20170918/v001.json",
type: "vector"
}
```
And this is what appears if I select only the OpenMapTiles `cut` source. Clearly we still have the entire data set.
Did anybody notice it as well?
So we are downloading the tiles twice again.

Request example:
https://vectortiles.geo.admin.ch/mbtiles/osm-2017-07-24-v3.6.2-europe-cut-20170918/v001/7/65/45.pbf

![image](https://user-images.githubusercontent.com/3306154/49701154-96f41b80-fbb6-11e8-94ac-4c6b36b98397.png)

Again, this explains, the shadow like effect of the labels.

I remove it for now....

**Comment by davidoesch** [comment]
@gjn : might be fixed with your aggregated approach?

**Comment by oterral** [comment]
I m not sure but if I remember correctly. We used all the data of openmaptiles on lower level and then on slower level the cut is done.
But yes now the cut should be done for all the levels,

**Comment by davidoesch** [comment]
cut is not shown

**Comment by pakb** [comment]
Is http://test.map.geo.admin.ch at a sufficiently good state to say this is solved?

**Comment by davidoesch** [comment]
We take this to the steering committee. Imho for test phase.
