### ISSUE TITLE
[MVT]  Wrong sprite link for styles alternatives

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/mf-geoadmin3#4654]
https://gist.githubusercontent.com/davidoesch/6223bb04dee87172e93e98d1e7c0bbc3/raw/e75972dfc0edcb572b7efe0525b4de49957f634b/styles-ch.swisstopo.basiskarte.vt_v004.json
https://gist.githubusercontent.com/davidoesch/b531a80d89f982cd38fcebaf8f23a0fe/raw/684d357d72e10e7b1eb20994ad84e930e5d50d6f/styles-ch.swisstopo.leichte-basiskarte-grey.vt_v004.json
https://gist.githubusercontent.com/davidoesch/f6a23f30c653e1dac5709dcd9be92b29/raw/b09cec946961adb34f619bc59a11e71d04af5438/styles-ch.swisstopo.basiskarte-lsd.vt_v004.json

To be fixed for all of these.

mapbox://sprites/vib2d/cjeeaiozg3icf2sn7c3gjazob

Please fix if you know which one should be used.

**Comment by davidoesch** [comment]
@danduk82  you can the move those json to the official gist of geo.admin.ch

**Comment by davidoesch** [comment]
wait for v006

**Comment by pakb** [comment]
solved, see https://vectortiles.geo.admin.ch/gl-styles/ch.swisstopo.leichte-basiskarte.vt/v006/style.json

**Comment by swissgis3084** [comment]
when changing the styles to "A" (vintage) and "B" (grey), the color of symbols remain the same. the same sprites are displayed. I prepared sprites also for vintage and grey.

vintage:
![ch swisstopo leichte-basiskarte-vintage](https://user-images.githubusercontent.com/42927494/56284528-fccc5300-6114-11e9-9137-48f730c2f4b1.png)
![ch swisstopo leichte-basiskarte-grey](https://user-images.githubusercontent.com/42927494/56284575-1f5e6c00-6115-11e9-9330-d705fb4f8b5b.png)

json-file is identical for all our sprites:
{
	"airport": {
		"width": 40,
		"height": 40,
		"x": 0,
		"y": 0,
		"pixelRatio": 1
	},
	"donut85black": {
		"width": 40,
		"height": 40,
		"x": 40,
		"y": 0,
		"pixelRatio": 1
	},
	"pointheavyred": {
		"width": 40,
		"height": 40,
		"x": 80,
		"y": 0,
		"pixelRatio": 1
	},
	"pointheavyblue": {
		"width": 40,
		"height": 40,
		"x": 120,
		"y": 0,
		"pixelRatio": 1
	},
	"peak": {
		"width": 40,
		"height": 40,
		"x": 160,
		"y": 0,
		"pixelRatio": 1
	},
	"hospital": {
		"width": 40,
		"height": 40,
		"x": 200,
		"y": 0,
		"pixelRatio":1
	}
}

**Comment by boecklic** [comment]
solved. check e.g. https://s.geo.admin.ch/81a341369e
note: you (might) have to reset your browser-cache to see it!
