### ISSUE TITLE
[MVT] F-006 Third party style: footer URL missing

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#4662]
if a third party style is added or drawn

https://mf-chsdi3.int.bgdi.ch/mvt/shorten/7ed8b871f6 

![image](https://user-images.githubusercontent.com/4577727/50012364-b9bf6f00-ffbe-11e8-9899-2ad58bf685c9.png)

there should be a link in red in the  (c) as for drawing

eg in

![image](https://user-images.githubusercontent.com/4577727/50012437-ef645800-ffbe-11e8-9de2-06fee9e34da8.png)

**Comment by oterral** [comment]
Fixed on mvt branch
