### ISSUE TITLE
3d Attribution in flight mode wrong

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#4671]
open https://s.geo.admin.ch/7ef62eafac

go into flight mode
bottom left a cesium attribution appears

-> remove it

![image](https://user-images.githubusercontent.com/4577727/50274361-5f4e6480-043d-11e9-9bc5-986b86cdd6b5.png)

**Comment by procrastinatio** [comment]
So data stored on `gist.githubusercontent.com`(https://gist.githubusercontent.com/davidoesch/63858db1d48a874331beaa086595a98c/raw/2aeb8430e03e05d72f1e63dbc0df26dbb4e7d672/Bern900m.kml) are not considered as external data?
