### ISSUE TITLE
 [MVT ] Style v005

### ISSUE THREAD

**Issue by oterral** [geoadmin/mf-geoadmin3#4677]
Things to improve in style ch.swisstopo.leichte-basiskarte.vt/v005/style.json : 

Avoid conflicts between bodIds:
 - [ ] Change source's name `ch.swisstopo.swissnames3d` to `ch.swisstopo.swissnames3d.vt` 
 - [ ] Change source's name `Leichte Basiskarte` to `ch.swisstopo.vektorkarte.vt` 

Reorder source:
 - [ ]  `ch.swisstopo.swissalti3d-reliefschattierung` must be the first element of the sources list.

Styling:
 - [ ] Labels are duplicated between `OpenMapTiles` and `Leichte Basiskarte`. Remove OpenMapTiles Labels inside Switzerland.

**Comment by davidoesch** [comment]
ping @swissmap @swissgis3084
