### ISSUE TITLE
`npm-check-updates` do we need it?

### ISSUE THREAD

**Issue by pakb** [geoadmin/mf-geoadmin3#4679]
Some dependencies of this tool are deprecated and this tool is no longer really maintained.
Plus it is in the `dependencies` and not in `devDependecies` which seems odd as this is a package.json manager.
Was it used before greenkeeper got the update covered?
@gjn any hint on this tool?

**Comment by procrastinatio** [comment]
Was added one year ago. I guess you may discard it.

**Comment by pakb** [comment]
has been removed by https://github.com/geoadmin/mf-geoadmin3/pull/4680
