### ISSUE TITLE
[MVT] acceptance criteria: provide minimal documentation so that IGEB-B can continue the work

### ISSUE THREAD

**Issue by danduk82** [geoadmin/mf-geoadmin3#4683]
In order to continue the development, could you (@oterral and @loicgasser ) please provide a very short documentation that contains:

- [x] the 2-3 JS files where the magic happens (i.e. overwrite of layer config, etc)
- [x] notable issues that we might encounter very fast
- [x] list of hard-coded stuff that we might need to cleanup (layer names, vectortiles URL, etc)
- [x] ~~list of hard-coded translation~~ (@oterral update: there is no hardcoded translation afaik)
- [x] location of style editing component

An answer with the above content in the comments below is sufficient, no need to write some fancy doc.

**Comment by oterral** [comment]
Doc mvt

Specific stuff added for glStyle management:



	`src/components/map/MvtService.js`: Service containing only one function `reload`. This function takes an `ol.layer.VectorTile` or an `ol.layer.Group` in parameter and reload the correct glStyle dependng on its properties.

	`src/components/ExportGlStyleService.js`: Service to export the glStyle and download it. It works the same as `src/components/ExportKmlService.js`.  Take the json representing the glStyle and use `FileSaver` lib to download it.

	`src/components/GlStyleStorageService.js`: Service to save the glStyle in a s3 bucket. It works the same as `src/components/FileStorageService.js` used to save KML in s3 bucket, only the endpoint of the service used and the contentType value changes between the 2.	

	`src/components/edit/` : This folder contains all the glStyle editor stuff. 

		`EditDirective.js` : This directive is the container of the glStyle editor, it adds the button (export, share...) around the glStyle Editor.
		`EditGlStyleDirective.js` : The glStyle editor, it takes a glStyle as input (a js object), goes through all the `layers` and their properties and display a widget for each modifiable property.
								  Properties modifiable are specified in the layer's definiton in `LayersConfig`, see `README` file of the project for more informations.
		`SizeDirective.js`, `ToggleDirective.js`, `ColorDirective.js` : These directives represents a modifiable property, see `README` file of the project for more informations.

	`src/components/queryvector/`: Folder containing directives to display the content of a vector tile feature in a popup on mouse move. 

	`src/components/vectorfeedback/`: Folder containing directives to display/manage the grey feedback panel.


	`src/js/EditController.js`: Controller of the `Edit` directive.
	`src/js/VectorFeedbackController.js`: Controller of the `VectorFeedback` directive.
	`src/js/MainController.js`: Management of `Edit` menu activation depending on permalink parameter, like the management of `Draw` menu display.


	`src/components/backgroundselector/BackgroundService.js` : Permalink management of `bgLayer_styleUrl` and `glStylesAdminId` mainly in functions `updateBgLayerStyleUrlParam` and
	`registerBgLayerStyleUrlPermalink`.

	`src/components/map/DefinePropertiesForLayerService.js` :  3 properties have been added on layers,
			- `glStyle`: the entire glStyle object apply to a layer,
			- `styles`: the list of styles available for the layer,
			- `sourceId`: the source's id from the glStyle associated to this layer. one mvt layer <--> one source in the glStyle.

	`src/components/map/LayersService.js`: We add a new `vectortile` layer's type management in `getOlLayerById` function.


	`src/components/map/MapUtils.js`: We add 2 important functions:
			- `applyGlStyleToOlLayer`: Applies a glStyle object on an `ol.layer.VectorTile` using `ol-mapbox-style` module. 
			- `applyGlSourceToOlLayer`: Applies a glStyle source object on an `ol.layer.Layer` 

	`src/components/share/ShareDrawDirective.js`: Mange the share link for glStyle.



Hardcoded value:

	To add a MVT background layer in the background layer selector, we harcoded it  to src/components/backgroundselector/BackgroundService.js :
```
var vtBgs = {
  'ch.swisstopo.leichte-basiskarte.vt': {
    id: 'ch.swisstopo.leichte-basiskarte.vt',  // bodId of the layer in the `layersConfig`
    label: 'basis',	 // Translation's id for the label
    disable3d: true, // Don't show it in 3d
    labels: false    // Not used anymore. TODO: Remove it.
  } 
};
```

	To add a MVT layers in the `layersConfig`, we harcoded it just after the file is loaded in src/components/backgroundselector/LayersService.js, see `README` file of the project for more informations about how these layers are configured.

**Comment by oterral** [comment]
@danduk82 is that enough?  

for `notable issues that we might encounter very fast`, I didn't fine any. If you understand how the configuration of a MVT layer works /see README)  everything will goes fine.

**Comment by davidoesch** [comment]
- [ ] Vector tiles URL should be in configuration

**Comment by oterral** [comment]
@gjn  what do you meant with this "vector tiles url in configuration".

Ideally the definiton of vectortiles should go in the layersConfig like for a geojson layer.

And if you want to override you use the bglayers_styleurl permalink parameter like for the geojson layer.

**Comment by pakb** [comment]
I'm still a little bit wet behind the ears on this matter, but that looks like a good start to me.

**Comment by danduk82** [comment]
@oterral , it is enough, thanks a lot for the great work!
