### ISSUE TITLE
[MVT] Minimal update to use v006 of style.json

### ISSUE THREAD

**Issue by boecklic** [geoadmin/mf-geoadmin3#4691]
ViB2d v006 is online on 'tileserver.int', mf-geoadmin3 should be updated to consider style v006

Styles

- http://tileserver.int.bgdi.ch/gl-styles/ch.swisstopo.leichte-basiskarte.vt/v006/?vector#13/46.9488/7.4444
- http://tileserver.int.bgdi.ch/gl-styles/ch.swisstopo.leichte-basiskarte-grey.vt/v006/?vector#13/46.9488/7.4444
- http://tileserver.int.bgdi.ch/gl-styles/ch.swisstopo.leichte-basiskarte-vintage.vt/v006/?vector#13/46.9488/7.4444

Tiles

- http://tileserver.int.bgdi.ch/mbtiles/ch.swisstopo.leichte-basiskarte.vt/v006/#13/46.9488/7.4444
- http://tileserver.int.bgdi.ch/mbtiles/osm-2018-12-03-v3.8-planet_cut/v000/#8/46.949/7.444

Important Note: Changes here will be minimal including just the new style. It will be sufficient for performance test, but e.g. editing functionality and other features may not work and will not be fixed on this branch (`mvt_style_v006`). This branch will be discarded afterwards and the proper integration of v006 will be done after the cleanup (Issue #4702).

**Comment by davidoesch** [comment]
Funny: cpu load when viewing: 100%

**Comment by danduk82** [comment]
@boecklic , please ensure that for INT you use `vectortiles.int.bgdi.ch` (cloudfront) instead of `tilesever.int.bgdi.ch` (varnish) and that for PROD you use `vectortiles.geo.admin.ch`

@ltkum , is this stlye and the data deployed to PROD?

**Comment by danduk82** [comment]
@boecklic , yes pretty heavy stuff

**Comment by ltkum** [comment]
@danduk82 

Currently syncing data to prod. It is quite heavy so it takes some time. styles, jsons and sprites have already been deployed.

**Comment by danduk82** [comment]
@ltkum, ok please report when online

**Comment by boecklic** [comment]
@danduk82 / @ltkum `vectortiles.dev.bgdi.ch` doesn't exist, right? Does it make sense to set it up, so we would have the same (dev|int|prod) pattern as for all other backend services? Currently the `vectortiles.int.bgdi.ch` fqdn is hardcoded...

**Comment by danduk82** [comment]
@boecklic  this makes totally sense, yes

**Comment by boecklic** [comment]
current work in [`mvt_style_v006`](https://github.com/geoadmin/mf-geoadmin3/tree/mvt_style_v006)

**Comment by oterral** [comment]
@boecklic  just a reminder this PR https://github.com/geoadmin/mf-geoadmin3/pull/4673 contains a simplification to load style without `subLayersId` option.

**Comment by pakb** [comment]
Thanks for the hint @oterral 

The style is being loaded, but there are still some issues with labels' z-index between OSM and our own.

**Comment by loicgasser** [comment]
OSM data is still not cut it seems.

**Comment by davidoesch** [comment]
It should be on production http://vectortiles.geo.admin.ch/gl-styles/ch.swisstopo.leichte-basiskarte.vt/v006/?vector#14.85/47.21201/7.52891/0/6

**Comment by pakb** [comment]
well, either our implementation alters the layering, or something is missing with OpenLayers (and the lib OpenLayersMapboxStyle)
https://mf-geoadmin3.int.bgdi.ch/mvt_style_v006/index.html

**Comment by gjn** [comment]
Strange regarding labels. I assumed that labels are removed in osm inside Switzerland.

Could you verify if we have the same effect using the old osm cut version? (https://vectortiles.geo.admin.ch/mbtiles/osm-2017-07-24-v3.6.2-europe-cut-20170918/v001.json)

**Comment by ahocevar** [comment]
@oterral OpenLayers indeed does decluttering per OpenLayers layer instance. A good vector tile setup for OpenLayers only uses a single vector tile source, and minimizes the number of OpenLayers layer instances that need to be created. The number of labels that need to be considered does affect performance a bit, but actually rendering too many labels is a bigger performance hit.

**Comment by oterral** [comment]
@gjn maybe you should ask for a version wihtout labels to see if there is a big difference or not. The labels problem is there since the first useable version of the vector tile layer. I also see  lakes on top of lake's names on level 6. So I think the osm cut needs to be verified.

**Comment by pakb** [comment]
Found a fix, set the zIndex to the `ol/layer/Group` and voilà (there are two groups added to OL, one for OSM data, and one for our own data).
There are still some issues with OSM labels underneath our data, but no more double labels (maybe more linked to our OSM cut)

**Comment by oterral** [comment]
Actually there is only one ` ol/layer/Group`  added for vector tiles with 2 `ol.layer.vectorTile` in it, at least with https://github.com/geoadmin/mf-geoadmin3/pull/4673,  the other Group are the default layers of the current topic . That's funny that  setting the `zIndex` of the  ` ol/layer/Group` change the order of the layers in this group. That shouldn't be the case.

Whatever,  this hack hide the  labels but you still can see artefacts on swiss borders.

I think the problem is because the osm cut is done by tiles (I didn't know that) and not by geometry. The osm cut only remove tiles which are not in over the swiss border. That's why you see 'olten' label until the zoom 8 and 'thonex' (and all osm data) until zoom 12

**Comment by loicgasser** [comment]
We have a custom tippecanoe for that.
https://github.com/geoadmin/tippecanoe/commits/master
There is some doc in word document in vib2d project.
I remember there are several steps. If you can't make it work ask @stebie
Ping @danduk82

**Comment by pakb** [comment]
A good solution would be to remove everything OSM over swiss territory (specifically labels) so that we could set the same zindex for OSM labels and our labels.

**Comment by loicgasser** [comment]
Actually doc is in the repo.
https://github.com/geoadmin/tippecanoe#tile-cut

You just need a polygon in WebMercator representing Switzerland, create a tileset with it, cut both OSM and Swisstopo data.

Finally combine them with tile-joins, from doc:

```
If you specify multiple source mbtiles files or source directories of tiles, all the sources are read and their combined contents are written to the new mbtiles output. 
```
https://github.com/geoadmin/tippecanoe#tile-join

**Comment by danduk82** [comment]
Hi @loicgasser, thanks a lot for the tip!

**Comment by danduk82** [comment]
@ltkum please take the OSM tileset and cut it using the custom version of tippecanoe as explained by @loicgasser ASAP.

**Comment by gjn** [comment]
Guys, that's what I did. The result is the same as what stibe created.

**Comment by danduk82** [comment]
done
