### ISSUE TITLE
backport changes in mvt to master

### ISSUE THREAD

**Issue by boecklic** [geoadmin/mf-geoadmin3#4696]
Some changes in `mvt` are not directly related to vectortiles and should therefore be backported to current `master` to keep the diff between `mvt` and `master` as small as possible. In particular

- refactoring of `FileStorageService.js` into `FileStorageService.js` and `PublicStorageService.js` (which serves as base later for GlStyleStorageService as well
- backgroundselector.less: both image files types of `bg-layersx2.(jpg|png)` should be included in `master`, one used by `master` the other one used by `mvt`

**Comment by danduk82** [comment]
done
