### ISSUE TITLE
[MVT] edit translation SHARE

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#4699]
When sharing an edit style
https://mf-geoadmin3.int.bgdi.ch/mvt/index.html?

Result
![image](https://user-images.githubusercontent.com/4577727/51390035-5e891b00-1b2e-11e9-87d8-13662c05c080.png)

Expected result:

Link to share your drawing/style
Link to edit your drawing/style later

-> can you point me to MSGIDs I need to translate in DE FR EN IT RM?

**Comment by pakb** [comment]
`draw_share_admin_link` and `draw_share_user_link`
but that's the same labels as when you want to share a drawing, is that intended?

**Comment by davidoesch** [comment]
Ok if it is the same for both.
Two separate is a nice to have

**Comment by davidoesch** [comment]
ping @pakb

**Comment by davidoesch** [comment]
ping @pakb 
what is the status here? it is only translation

**Comment by pakb** [comment]
@davidoesch  Could you verify if it's been updated in the MSGID? We've made a couple `make translate` today with other issues, and I don't see any change on these two labels.

**Comment by boecklic** [comment]
solved with translation

**Comment by davidoesch** [comment]
is still not fixed

**Comment by pakb** [comment]
@davidoesch could you had a space in German between `/` and `Still` in the translation spreadsheet for id `draw_share_user_link`? That's the current output in DE vs EN :
`Link zum Teilen ihrer Zeichnung /Stil`
`Link to share your drawing / style`

**Comment by pakb** [comment]
will be updated by https://github.com/geoadmin/mf-geoadmin3/pull/4957

**Comment by davidoesch** [comment]
Add the space

**Comment by pakb** [comment]
Has been deployed on https://test.map.geo.admin.ch
