### ISSUE TITLE
LUBIS: time selector does not switch to all data when switched off

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#4710]
Steps to reproduce
all os all browser

open http://map.lubis.admin.ch

activate  time slider
![image](https://user-images.githubusercontent.com/4577727/51598527-04a59e00-1efe-11e9-82d2-337f0b64fc4a.png)

Switch time slider off

result:
only last year is active
![image](https://user-images.githubusercontent.com/4577727/51598568-1be48b80-1efe-11e9-8375-d6fec73f8aa7.png)

expected result:
ALL years are shown/selected
![image](https://user-images.githubusercontent.com/4577727/51598604-2f8ff200-1efe-11e9-9576-0bbfb33cfa05.png)
 

since LUBIS is one of  most used layers...prio2

**Comment by procrastinatio** [comment]
@boecklic The issue is with `ch.swisstopo.lubis-bildstreifen` whose timesamp are 4-digits `2018` instead of the standard `20181231`. All layers is the special `timestamp=99991231`

https://map.geo.admin.ch/?topic=swisstopo&layers=ch.swisstopo.lubis-bildstreifen&lang=de&bgLayer=ch.swisstopo.pixelkarte-farbe&layers_timestamp=2010&time=2010

If you remove this layer , it is OK

https://s.geo.admin.ch/697a2a205a

**Comment by davidoesch** [comment]
ETA?

**Comment by pakb** [comment]
2nd prio, so whenever we have some time (which is not the case right now sadly)

**Comment by davidoesch** [comment]
Well it's one of the most used layers.
There is a work around but for swisstopo sales it's quite a PITA to explain this to customer.
Question was ETA...

**Comment by pakb** [comment]
It's not on my backlog for the next two or three weeks, try convince @danduk82 otherwise if you think it should be done more urgently.

**Comment by danduk82** [comment]
The clean solution should be part of the discussion that we have also for historical data for meteoCH. We can do a dirty hack for next deploy.

**Comment by procrastinatio** [comment]
Hmm, layers `ch.swisstopo.lubis-luftbilder_schraegaufnahmen` and `ch.swisstopo.lubis-bildstreifen` are WMS and do not have the infamous timestamp `9999` (I would call it `666` personally).
`WMTS` 1 year=19651231, all years=99991231
`WMS`: 1 year=1966, all year=`-`  [example](https://wms.geo.admin.ch/?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=ch.swisstopo.lubis-bildstreifen&LANG=de&WIDTH=552&HEIGHT=552&CRS=EPSG%3A2056&STYLES=&BBOX=2466000%2C820000%2C2942000%2C1354000)
