### ISSUE TITLE
[MVT] if style applied: OSM part is not taken into account

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#4714]
if user changes style
https://s.geo.admin.ch/7fcac36e2e 

outside switzerland style is not applied

expected result:
style applied as well outside switzerland (red sea is red...)

IMHO @swissgis3084 @swissmap this has to do with the fact that layers are named differently.... to have an optimal customer experience -- 1:1 match with osm ids is needed..

**Comment by oterral** [comment]
You just need to change the regex to match  the layer's id fron the style. https://github.com/geoadmin/mf-geoadmin3/blob/mvt/src/components/map/LayersService.js#L371

**Comment by swissgis3084** [comment]
as far as I know multiple layers cannot have the same layer-name in the style

**Comment by pakb** [comment]
a little wildcard in the regex before hydrology should do the trick

**Comment by davidoesch** [comment]
eta?

**Comment by pakb** [comment]
done, see https://test.map.geo.admin.ch
