### ISSUE TITLE
[MVT] vectortiles.geo.admin.ch subdomaines not used

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#4716]
we only use
https://vectortiles.geo.admin.ch/mbtiles/ch.swisstopo.leichte-basiskarte.vt/v006/15/17254/11539.pbf
 not

https://vectortiles01.geo.admin.ch
https://vectortiles02.geo.admin.ch
https://vectortiles03.geo.admin.ch
https://vectortiles04.geo.admin.ch

is not used

**Comment by gjn** [comment]
Check if openlayers supports multidomain support for mvt sources.

**Comment by procrastinatio** [comment]
`http2` has no need for multidomain.

**Comment by gjn** [comment]
Not all browsers (and proxies!) support http2.

**Comment by danduk82** [comment]
vectortiles10-14.geo.admin.ch is working.  @sontags is deploying the new routing rules (S3) and then this should be good

**Comment by pakb** [comment]
done, see https://test.map.geo.admin.ch
