### ISSUE TITLE
[MVT] Zoom level load ?

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#4717]
If I load https://s.geo.admin.ch/7fcff85460 loads https://s.geo.admin.ch/7fcff9043f it loads 1M
https://s.geo.admin.ch/7fcff9daf1  even more details loads 200k

Why do have more details and less KB loaded?

**Comment by gjn** [comment]
One part might be sub-optimal cut of osm data in switzerland.

I'm currently analysing that.
