### ISSUE TITLE
[MVT] Country label prio/size

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#4722]
this is rather about the cartography/ product mmgt

all country labels have

- same size
- big countries are not showsn

eg
https://s.geo.admin.ch/7fdf4bda8c

![image](https://user-images.githubusercontent.com/4577727/52178480-65bb5480-27cf-11e9-9f5a-e7d0c0709628.png)

compared with original data from openmaptiles
https://www.maptiler.com/maps/#topo//vector/3.15/18.66/50.16

where spain appears and andorra is small

**Comment by swissgis3084** [comment]
yes and this is a political discussion we shouldn't care about right now i think
