### ISSUE TITLE
[MVT] Google PageSpeed insights score:  0 (zero, nill)

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#4726]
running
https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Ftest.map.geo.admin.ch

results in 0 on mobile low 30 on desktop

There  are a couple of opportunities to fix
- Preload key requests
- Defer unused CSS
- Enable text compression

etc

**Comment by pakb** [comment]
Score is now 50 for desktop which is fine by me, as far as I know we don't target mobile audience for now.
IMHO it's a bit putting the cart before the horse talking optimisation when we don't have polished all aspect of the viewer and its backends.

**Comment by davidoesch** [comment]
Mobile First :-) but for test phase ok
