### ISSUE TITLE
[MVT] fonts are not loaded from style JSON by olms library

### ISSUE THREAD

**Issue by pakb** [geoadmin/mf-geoadmin3#4732]
As described in https://github.com/openlayers/ol-mapbox-style README.md, this library ignores `glyphs` part of GL-Style JSON and asks us to load ourselves the font we need by other means.
We need to address that in the test viewer (default font is not ok, as it's not a Sans Serif but Times new roman or equivalent)

**Comment by swissgis3084** [comment]
in our styles we reference "https://tileserver.int.bgdi.ch/fonts/{fontstack}/{range}.pbf", where we use ROBOTO (this is the font we want)
we use: 
- Roboto Regular
- Roboto Italic
- Roboto Condensed Bold

**Comment by boecklic** [comment]
Workaround for using Roboto font family: #4743 (test link in PR)

**Comment by pakb** [comment]
Will be included next time we deploy the testviewer (we still need to fix background colour for OSM data)

**Comment by gjn** [comment]
We should try to deploy the testviewet once something is fixed. 

Is deploy mechano now done/ready?

**Comment by procrastinatio** [comment]
See https://github.com/geoadmin/mf-geoadmin3/pull/4731

**Comment by pakb** [comment]
online on https://test.map.geo.admin.ch
