### ISSUE TITLE
[MVT] Switch bg stops loading vec tiles

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#4733]
How to reproduce
OS: iOS chrome / Safari

Open test.map.geo.admin.ch

start with vector
zoom in
pan around load some tiles
switch to swissimage
pan
switch back to vector tiles
pan
result;
no tiles loaded or only partly

see video here
https://photos.app.goo.gl/q5gHizeHtU9pkfFn9

expected result:
loads without issue

**Comment by danduk82** [comment]
@pakb , can you have a look please?

**Comment by pakb** [comment]
There's a bunch of error in the console on iOs, seems to be related to the drawing on the device and not the loading of the tile, I'll dig deeper
![image](https://user-images.githubusercontent.com/11540521/52474639-55252880-2b99-11e9-924f-542f4c06fdd4.png)

**Comment by pakb** [comment]
maybe related to https://github.com/openlayers/ol-mapbox-style/issues/125

**Comment by pakb** [comment]
it's now working on my iPhone, could you give it a try with yours and tell me if it also is fixed for you?

**Comment by davidoesch** [comment]
I can still reproduce it... Will show u 1:1

**Comment by boecklic** [comment]
other strange effects can be observed on ios when playing around, it seems to be related to a memory limit of ios set for canvas

![5ccae1502fccb276629751](https://user-images.githubusercontent.com/7808191/57075076-0b566500-6ce6-11e9-9a47-78c5374222db.gif)

**Comment by pakb** [comment]
the label issue has been reported separately here https://github.com/geoadmin/mf-geoadmin3/issues/4916
The issue here is solved so we will continue discussing the label issue on the other one

**Comment by davidoesch** [comment]
No this issue is NOT solved,, I can still reproduced it

**Comment by pakb** [comment]
Then you'll have to show me how, I was able to reproduce it before, but now not anymore (but I face the label issue when I encounter the out of memory issue).
Which model of iPhone do you have?

**Comment by davidoesch** [comment]
as in the initial video  iphone 7 latest ios latest safari and chrome

**Comment by davidoesch** [comment]
not to reproducable anymore
