### ISSUE TITLE
[MVT] background ch rest of world

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#4739]
result
![image](https://user-images.githubusercontent.com/4577727/52549921-f993ae80-2dd5-11e9-93f0-96d72990db22.png)

expected result

![image](https://user-images.githubusercontent.com/4577727/52549930-0c0de800-2dd6-11e9-98d9-eacb94840b61.png)

**Comment by swissgis3084** [comment]
same issue as #4721 ?

**Comment by swissgis3084** [comment]
seems that order of layers is different than specified in the style?

**Comment by pakb** [comment]
fixed by https://github.com/geoadmin/mf-geoadmin3/pull/4746

**Comment by pakb** [comment]
online on https://test.map.geo.admin.ch

**Comment by swissgis3084** [comment]
not fixed for "Darstellung "A", "B", "C"

**Comment by davidoesch** [comment]
not fixed for "Darstellung "A", "B", "C"

**Comment by danduk82** [comment]
the only official style is v006. The others are examples. I unpriorize.

**Comment by pakb** [comment]
There is no data in the background of OSM, we are styling a layer called `territory` with our data, but this layer is not present for the rest of the world.

**Comment by ltkum** [comment]
We made a small style that removes only the territory field in the style json, you can see it on 
http://tileserver.dev.bgdi.ch/gl-styles/ch.swisstopo.leichte-basiskarte.vt/v009/?vector#7/47/8/0/6 
It works on tileserver dev, so feel free to test it on the viewer.

**Comment by pakb** [comment]
Loading of custom style is done, but is not yet working with permalink loading

**Comment by davidoesch** [comment]
@pakb  IMHO solved?
