### ISSUE TITLE
[MVT] interactive change of street color

### ISSUE THREAD

**Issue by swissgis3084** [geoadmin/mf-geoadmin3#4741]
when user changes the color of streets: only layers "roadtraffic" that do NOT contain the string "contour" should be targeted. this way the filling of the roads change color but the contours will remain in original color (the contour is the small outline of a road: it makes the road stand out more and it is possible to discerne over- and underpaths)

in the style jsons all contour-layers contain the string "contour" and those should not change in color:
![image](https://user-images.githubusercontent.com/42927494/52567932-bbb27c80-2e0d-11e9-8a21-7dd3a70ecc86.png)

with contour:
![image](https://user-images.githubusercontent.com/42927494/52567686-2dd69180-2e0d-11e9-8c82-2a6da24f8ff0.png)
result as we have it at the moment when user changes color:
![image](https://user-images.githubusercontent.com/42927494/52567786-65453e00-2e0d-11e9-8383-dbd0fe4f9bbd.png)

**Comment by davidoesch** [comment]
the current behaviour fits the testviewer needs. 
the solution for in detail work is to export the style and deal with it in maputnik , qgis etc
