### ISSUE TITLE
LV95 native/reprojected tiles are blurry

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#4742]
According to 
https://groups.google.com/forum/#!topic/geoadmin-api/WwiNUWWRt0A

> 
> Dear GeoAdmin team,
> 
> I recently noticed that the LV95 WMTS tiles look a bit blurry compared to the LV03 tiles,
> and then saw that it used to be documented [1] that only the LV03 tiles are "native",
> while all other projections are raster-reprojected. Is this still valid also for the
> future (that's a big word, I mean the next few years), or is this going to change soon?
> 
> The reason I ask is that for most applications I work on, it is more important to display
> or print sharp tiles than to worry about the 1-2 m difference between LV03 and LV95.
> 
> For example, I am wondering if I should switch the default to LV03 for the Leaflet plugin [2].
> 
> 
> [1] https://github.com/geoadmin/mf-chsdi3/commit/ad206694386ab58128bbfa449be310847dd07f78#diff-5c02070ecc65a7f3d78836f51a384996L876
> [2] https://github.com/rzoller/Leaflet.TileLayer.Swiss

Expected result:
LV95 is NOT blurry

**Comment by procrastinatio** [comment]
Which layer are you interested in? 

swissimage and the Winterkarte are LV95. The rasters are generally still LV03. Vectors are all LV95.
At the end of the year 2017, we switch from mapproxy to mapserver for the reprojection. Before the switch, we did reproject the LV03 pre-generated tiles to other projection with mapproxy (see https://github.com/geoadmin/service-mapproxy). Then, we only have a WTMStoWMS request proxy (https://github.com/geoadmin/service-proxywms), and let mapserver do the job.

**Comment by rzoller** [comment]
> Which layer are you interested in?

Yes, sorry, I forgot to specify that: `ch.swisstopo.pixelkarte-farbe` is where the issue came up, but it would be interesting for all layers to know which one is native/reprojected, in order to know where to expect the best quality.

Screenshot for pixelkarte-farbe (left: LV03, sharp / right: LV95, blurry):

![screenshot](https://user-images.githubusercontent.com/3082173/52630248-068acd80-2ebc-11e9-8671-d0adc8b8bc96.png)

See also [left/right comparison centered on Mendrisio](https://codepen.io/anon/pen/BMVjZj), which is an area with big difference between LV03 and LV95 according to [this layer](https://s.geo.admin.ch/800ca160c8).

**Comment by gjn** [comment]
I think we should switch the original base data of all raster layers to lv95 if they are available (exception might be zeitreihen).

LV95 is now the most use srs in our wmts services.

@ltclm @danduk82 what do you think?

**Comment by ltclm** [comment]
yes we should.
The following raster layers are affected
* ch.swisstopo.pixelkarte-farbe
* ch.swisstopo.pixelkarte-grau
* ch.swisstopo.pixelkarte-farbe-pk25.noscale
* ch.swisstopo.pixelkarte-farbe-pk50.noscale
* ch.swisstopo.pixelkarte-farbe-pk100.noscale
* ch.swisstopo.pixelkarte-farbe-pk200.noscale
* ch.swisstopo.pixelkarte-farbe-pk500.noscale
* ch.swisstopo.pixelkarte-farbe-pk1000.noscale

The source data can be shifted to lv95.
For the migration of the pk layers we have to:
* stop automata
* shift source data to lv95
* change mapfile snippets
* deploy shifted data and new mapfile snippets (wms-*, service-proxywms)
* change automata scripts
* flush and preheat lv95 wmts cache
* re-activate automata

@danduk82 you have to set a prio for this task, in my eyes the pk layers should be shifted with a higher prio then all the other layers.

this is the current inventory of raster layers with source data in lv03 :
```bash
$ grep -lZ "init=epsg:21781" * | xargs -0 grep -li 'TYPE RASTER' | sort
ch.astra.ivs-gelaendekarte.map
ch.bafu.gefahren-aktuelle_erdbeben.map
ch.bafu.gefahren-basiskarte.map
ch.bafu.gewaesserschutz-diffuse_eintraege_phosphor.map
ch.bafu.gewaesserschutz-diffuse_eintraege_stickstoff.map
ch.bafu.hydrogeologische-karte_100.map
ch.bafu.neophyten-amerikanische_kermesbeere.map
ch.bafu.neophyten-amerikanischer_stinktierkohl.map
ch.bafu.neophyten-armenische_brombeere.map
ch.bafu.neophyten-aufrechtes_traubenkraut.map
ch.bafu.neophyten-auslaeuferbildendes_fettkraut.map
ch.bafu.neophyten-balfours_springkraut.map
ch.bafu.neophyten-bastardindigo.map
ch.bafu.neophyten-bastard_staudenknoeterich.map
ch.bafu.neophyten-besen_radmelde.map
ch.bafu.neophyten-blauglockenbaum.map
ch.bafu.neophyten-brasilianisches_tausendblatt.map
ch.bafu.neophyten-carolina_nachtschatten.map
ch.bafu.neophyten-chinesische_samtpappel.map
ch.bafu.neophyten-druesiges_springkraut.map
ch.bafu.neophyten-einjaehriges_berufkraut.map
ch.bafu.neophyten-essbare_kermesbeere.map
ch.bafu.neophyten-essbares_zypergras.map
ch.bafu.neophyten-essigbaum.map
ch.bafu.neophyten-felsen_greiskraut.map
ch.bafu.neophyten-fortunes_hanfpalme.map
ch.bafu.neophyten-gestreiftes_suessgras.map
ch.bafu.neophyten-gewoehnliche_jungfernrebe.map
ch.bafu.neophyten-glattes_zackenschoetchen.map
ch.bafu.neophyten-goetterbaum.map
ch.bafu.neophyten-grossbluetiges_heusenkraut.map
ch.bafu.neophyten-grosser_wassernabel.map
ch.bafu.neophyten-haargurke.map
ch.bafu.neophyten-henrys_geissblatt.map
ch.bafu.neophyten-herbst_traubenkirsche.map
ch.bafu.neophyten-igelgurke.map
ch.bafu.neophyten-japanischer_staudenknoeterich.map
ch.bafu.neophyten-japanisches_geissblatt_gridcolor.map
ch.bafu.neophyten-japanisches_geissblatt.map
ch.bafu.neophyten-kanadische_goldrute.map
ch.bafu.neophyten-kanadische_wasserpest.map
ch.bafu.neophyten-karolina_haarnixe.map
ch.bafu.neophyten-kaukasus_fettkraut.map
ch.bafu.neophyten-kirschlorbeer.map
ch.bafu.neophyten-kletternder_giftsumach.map
ch.bafu.neophyten-kopoubohne.map
ch.bafu.neophyten-mahonie.map
ch.bafu.neophyten-nadelkraut.map
ch.bafu.neophyten-nuttalls_wasserpest.map
ch.bafu.neophyten-portulak_heusenkraut.map
ch.bafu.neophyten-riesenbaerenklau_gridcolor.map
ch.bafu.neophyten-riesenbaerenklau.map
ch.bafu.neophyten-robinie.map
ch.bafu.neophyten-runzelblaettriger_schneeball.map
ch.bafu.neophyten-sachalin_staudenknoeterich.map
ch.bafu.neophyten-schmetterlingsstrauch.map
ch.bafu.neophyten-seidiger_hornstrauch.map
ch.bafu.neophyten-spaetbluehende_goldrute.map
ch.bafu.neophyten-suedafrikanisches_greiskraut.map
ch.bafu.neophyten-syrische_seidenpflanze.map
ch.bafu.neophyten-topinambur.map
ch.bafu.neophyten-verlotscher_beifuss.map
ch.bafu.neophyten-vielaehriger_knoeterich.map
ch.bafu.neophyten-vielblaettrige_lupine.map
ch.bafu.permafrost.map
ch.bfe.globalstrahlung.map
ch.bfe.windenergie-potenzialgebiete.map
ch.blw.bewaesserungsbeduerftigkeit.map
ch.blw.erosion.map
ch.blw.erosion-mit_bergzonen.map
ch.blw.erosion-ohne_bergzonen.map
ch.blw.erosion-quantitativ.map
ch.blw.gewaesseranschlusskarte.map
ch.swisstopo.dhm25-relief.map
ch.swisstopo.digitales-hoehenmodell_25_reliefschattierung.map
ch.swisstopo.geoidmodell-ch1903.map
ch.swisstopo.geoidmodell-etrs89.map
ch.swisstopo.geologie-bodenunruhe.map
ch.swisstopo.geologie-eiszeit-lgm-raster.map
ch.swisstopo.geologie-generalkarte-ggk200.map
ch.swisstopo.geologie-geocover.map
ch.swisstopo.geologie-geologische_karte.map
ch.swisstopo.geologie-geologischer_atlas.map
ch.swisstopo.geologie-geotechnik-gk200.map
ch.swisstopo.geologie-geotechnik-mineralische_rohstoffe200.map
ch.swisstopo.geologie-gravimetrischer_atlas.map
ch.swisstopo.geologie-hydrogeologische_karte-grundwasservorkommen.map
ch.swisstopo.geologie-hydrogeologische_karte-grundwasservulnerabilitaet.map
ch.swisstopo.geologie-tektonische_karte.map
ch.swisstopo.hangneigung-ueber_30.map
ch.swisstopo.hebungsraten.map
ch.swisstopo.hiks-dufour.map
ch.swisstopo.hiks-siegfried.map
ch.swisstopo.images-landsat25.map
ch.swisstopo.images-spotimage.map
ch.swisstopo-karto.hangneigung.map
ch.swisstopo.koordinatenaenderung.map
ch.swisstopo.pixelkarte-farbe.map
ch.swisstopo.pixelkarte-farbe.map.group
ch.swisstopo.pixelkarte-farbe-pk1000.noscale.map
ch.swisstopo.pixelkarte-farbe-pk100.noscale.map
ch.swisstopo.pixelkarte-farbe-pk200.noscale.map
ch.swisstopo.pixelkarte-farbe-pk25.noscale.map
ch.swisstopo.pixelkarte-farbe-pk500.noscale.map
ch.swisstopo.pixelkarte-farbe-pk50.noscale.map
ch.swisstopo.pixelkarte-grau.map
ch.swisstopo.pixelkarte-grau.map.group
ch.swisstopo.pixelkarte-grau-pk1000.noscale.map
ch.swisstopo.swissnames3d.map
ch.swisstopo.swisstlm3d-karte-farbe.3d.map
ch.swisstopo.swisstlm3d-karte-farbe.map
ch.swisstopo.swisstlm3d-karte-farbe.mapproxy.map
ch.swisstopo.swisstlm3d-karte-grau.3d.map
ch.swisstopo.swisstlm3d-karte-grau.map
ch.swisstopo.transformation-bezugsrahmen_hoehe.map
ch.swisstopo.transformationsgenauigkeit.map
ch.swisstopo.uebersicht-gemeinden.map
ch.swisstopo.uebersicht-schweiz.map
ch.swisstopo-vd.amtliche-vermessung.map
ch.swisstopo.zeitreihen.map
ch.vbs.grunddispositiv-zeus.map
```

**Comment by procrastinatio** [comment]
And force the api to LV95?

**Comment by ltclm** [comment]
> And force the api to LV95?

for now nothing changes in the api, the changes mentioned above are on data level and wms configuration only. It's transparent for the api (WMS/WMTS) usage. Some day we will be disabling lv03 i think but i dont know until when we have to support lv03 in our services.

**Comment by gjn** [comment]
From my POV, high prio for pk (most used) Low for all others.

**Comment by ltclm** [comment]
ok i will do the migration of pk data and layers asap.
@mariokeusen could you please inform our automata responsibles that we will have to disable the pk automata process between 25.02 - 28.02 for the changes mentioned in this issue.
* 25.02.2019
- [ ] disable pk automata
- [ ] shift pk25-pk1000 data to lv95
* 26.02.2019
- [ ] update wms and service-proxywms configuration
- [ ] deploy new data and wms configuration to dev and int
- [ ] modifiy automata scripts
* 27.02.2019
- [ ] modifiy automata scripts
- [ ] deploy new data and wms configuration to prod (as part of the regular deploy)
* 28.02.2019
- [ ] activate automata

**Comment by mariokeusen** [comment]
Ok, I'll inform Karto about that
Question for @ltclm: I assume that the GDWH import will not be affected of that and all updates due will be published in Web-FSDI as soon as the automata process is reactivated. Or must they also stop imports into GDWH during that maintenance window?

**Comment by ltclm** [comment]
thank you! no the gdwh import is not affected. we will publish the new imports later.

**Comment by mariokeusen** [comment]
ok, thx. Info for Karto done.

**Comment by ltclm** [comment]
the lv95 migration of pk data is finished, data, services and cache have been updated (details see above).
@davidoesch please ask customer for confirmation.

**Comment by davidoesch** [comment]
Will do it KW 10

**Comment by davidoesch** [comment]
@ltclm customer confirmed. all ok. I close this ticket
