### ISSUE TITLE
Offline fails with some layers

### ISSUE THREAD

**Issue by procrastinatio** [geoadmin/mf-geoadmin3#4744]
Via helpdesk (Customer feedback ID : 2019021216393903)

------
Depuis récemment, je ne suis pas sûr que la fonction de téléchargement d'une carte pour utilisation offline fonctionne encore correctement.

J'ai l'habitude en ski de randonnée de sauvegarder la carte avec un calque "Itinéraire à ski" puis de passer en mode avion. Malgré quelques pop-ups d'avertissement, je pouvais utiliser la carte offline.
Je suis sur Iphone avec Safari.

Maintenant j'ai l'impression que malgré j'ai téléchargé une carte, il faut une connexion au début pour quand même télécharger la dalle détaillée: une fois que la position GPS précise est acquise, la carte reste blanche en mode avion, et si je repasse en 4G, je vois qu'une dalle se télécharger.

Serait-ce possible que la sauvegarde de la carte à l'avance "oublie" de téléchargé certaines dalles au 1/250000 ?

-------

**Comment by danduk82** [comment]
@procrastinatio , can you have a look please?

**Comment by procrastinatio** [comment]
Layers are stored only from zoom level 14 and greater. Above, layers may or may not stay in browser cache. I guess it was made to save place.
