### ISSUE TITLE
Customer feedback: dreht sich die Karte immer wieder

### ISSUE THREAD

**Issue by AFoletti** [geoadmin/mf-geoadmin3#4754]
--------------------------------------

Customer feedback ID : 2019021419485684

Folgendes passiert, wenn ich "Zeichnen und Messen" verwende oder nachdem ich es verwendet, aber beendet habe: 
Unter Windows 10, bei Verwendung von Tastatur mit integriertem Touchpad, dreht sich die Karte immer wieder, wenn ich sie nur verschieben will. Verwende ich die Touchfunktion des Bildschirms ist es noch schlimmer: Auf Berührung dreht sich die Karte und wird zugleich maximal gezoomt. In anderen Worten ist es unmöglich, mit der Karte weiterzuarbeiten..

--------------------------------------

I am unable to reproduce. What can we do to help the user?

**Comment by pakb** [comment]
So they are using some kind of Windows surface if I understand correctly? (or some sort of hybrid touch/desktop computer?)
Would be nice to be able to reproduce to find a workaround (or a fix)

**Comment by AFoletti** [comment]
Yes, I think you are right.
But by wife has exactly one of those hybrids and never had such an issue... I don't know if it's really useful to spend too much time on this

**Comment by AFoletti** [comment]
A couple of more infos from customer:
_Acer Switch 7 mit Windows 10 Pro. Firefox aktuell. Was ich vergessen hatte zu erwähnen: Die Geo-Map war gleichzeitig in 2 Tabs im Firefox geöffnet. Ich habe das Tab mit den Funktionsproblemen geschlossen und konnte dann im anderen Tab weiterarbeiten_

He could later not give us steps to reproduce. I am prone to consider this more or less a glitch instead of a true bug. I will test this evening on a hybrid device with multiple tabs and update the ticket tomorrow

**Comment by AFoletti** [comment]
Can't reproduce. I guess it is a strange quirk. Closing this
