### ISSUE TITLE
Offline does not work

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#4763]
Platform/browser
IOS and Android , all browsers

Steps to reproduce
Clear cache of your browser
Cold start your browser
Enter map.geo.admin.ch in url bar
Search  ftan 
Save offline
Once you succeed (I had trial and error at 99% several times)
Close browser
Go offline airplane mode
Start browser
Enter map.geo.admin.ch in url

Result:
Website not available

Expected result:
Offline version starts

Workaround: 
Save the application as link on home screen. 
Then save offline then go offline then start application from offline

**Comment by davidoesch** [comment]
Has been reported by customers...a couple of weeks ago already

**Comment by procrastinatio** [comment]
Looks like older version works

https://map.geo.admin.ch/master/0580412/1802071220/index.html
https://map.geo.admin.ch/master/3460166/1805081342/index.html

but none of OL6 version does

https://map.geo.admin.ch/master/c83064e/1810241036/index.html (first OL6)
https://map.geo.admin.ch/master/33fbbd1/1812191439/index.html
https://map.geo.admin.ch/master/9e1a0f2/1901230927/index.html
https://map.geo.admin.ch/master/7cee0df/1902061519/index.html

**Comment by gjn** [comment]
The reason is quite easy: the manifest entry in the mobile.html page disappeared....

**Comment by boecklic** [comment]
Hmm, but
```
$ curl -sL map.geo.admin.ch/mobile.html | gunzip | head -n 1
<!DOCTYPE html><html ng-app="geoadmin" ng-controller="GaMainController" itemscope itemtype="http://schema.org/WebApplication" manifest="geoadmin.1902061519.appcache"><head><!--![if !HTML5]>
```
?

**Comment by procrastinatio** [comment]
If the manifest file were missing no css or js would be cached. This is not
the case, the applications looks fine and in some case we cannot access the
saved tiles. I did notice that reloading without params when offline solves
the issue, at least on chrome.

**Comment by boecklic** [comment]
Tested in Android (chrome), iOS (safari), Surface (edge): 

- production works or at least we couldn't verify that it doesn't work
- int doesn't work yet

I'm checking what's wrong on int

**Comment by gjn** [comment]
I was wrong. Sorry about that!

Anyhow, some browsers/platforms work just fine.

Some don't. So priority for this issues can be lowered.

**Comment by davidoesch** [comment]
Latest ios it does not work. Most used mobile platform Switzerland. Prio 1

**Comment by pakb** [comment]
https://github.com/geoadmin/mf-geoadmin3/pull/4783 should fix the issue in the manifest file with /root/ as base path for index.html that @gjn pointed out.
But as @procrastinatio showed me on his phone, the problem might lay with the URL params that are causing the app to misbehave with appcache data.

**Comment by procrastinatio** [comment]
Are you using `http`or `https`?
On `iOS10`, `http` won't work anymore, as browser won't allow `appcache` on such website. With `https` the page loads fine.

**Comment by procrastinatio** [comment]
Can someone give feedback on the http://map.geo.admin.ch vs https://map.geo.admin.ch, please?

**Comment by gjn** [comment]
If connected, http redirects to https. Once this has happened on mobile, the page should be cached.

Now, when the user is offline and enters map.geo.admin.ch in the browser, it should load the application via appcache (we can't expect user to enter https://).

iOS on Safari does not support that? No workaround?

if not, the so be it, @davidoesch ?

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by davidoesch** [comment]
if not, the so be it: yes +1

**Comment by danduk82** [comment]
The solution would be to change offline technology such as [html5-service-workers](https://www.w3schools.com/html/html5_webworkers.asp) for example.
