### ISSUE TITLE
tooltip pub stop does not work

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#4808]
eg for
 https://s.geo.admin.ch/8073fe110d

or
https://s.geo.admin.ch/8073fed69c 
no result
![image](https://user-images.githubusercontent.com/4577727/53733013-ea0d0000-3e7f-11e9-9e9b-8120e356426a.png)

or
https://s.geo.admin.ch/8073ff2e14 is just infite loading

**Comment by pakb** [comment]
![image](https://user-images.githubusercontent.com/11540521/53734138-5806f680-3e83-11e9-8184-3b74d2682680.png)

![image](https://user-images.githubusercontent.com/11540521/53734093-34dc4700-3e83-11e9-9be0-e972889044f7.png)
Working fine for me. Have you tried from outside of the Bund network?

**Comment by davidoesch** [comment]
yep
funny: desktop: cablecom
mobile: swisscom

at the time of writing it did not work (reproduced each 3 times including cold start)... now it works....

**Comment by pakb** [comment]
Might be an issue with the provided content (if I remember correctly, the time table is provided through an iFrame given by the data holder, so if he has a downtime with his service, we can't do anything but wait...)

**Comment by davidoesch** [comment]
It's an external service... No iframe

**Comment by pakb** [comment]
well..
![image](https://user-images.githubusercontent.com/11540521/53745261-f5235880-3e9e-11e9-9d96-4518d1a48947.png)
now you know 😄

**Comment by pakb** [comment]
but you're right in thinking it's purely internal stuff, seems there's no call to any external URL. So maybe we had some downtime, but nothing has alerted us of that

**Comment by davidoesch** [comment]
as you see in the iframe view-source:https://api3.geo.admin.ch/rest/services/all/MapServer/ch.bav.haltestellen-oev/8577020/iframeHtmlPopup?lang=en 

it calls 
//api3.geo.admin.ch/stationboard/stops/8577020

which calls
https://opentransportdata.swiss/de/cookbook/abfahrts-ankunftsanzeiger/ 

-> a glitch there? rather not since we have a pingdom sonde set up for this and it is fine....

So I suppose it was on our side

**Comment by gjn** [comment]
@danduk82 what does kibana tell on the stationboard service for today? Increased error rate or increased response times?

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
