### ISSUE TITLE
[MVT] Attribution in mapbox service viewer

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#4812]
http://vectortiles.geo.admin.ch/gl-styles/ch.swisstopo.leichte-basiskarte.vt/v006/?vector#7/47/8/0/6

in the (i) bottom right , 
result
"© OpenMapTiles © OpenStreetMap contributors"
should be
"© swisstopo, OpenMapTiles , OpenStreetMap contributors"

**Comment by danduk82** [comment]
solved
