### ISSUE TITLE
small iframes - Tooltip size to big

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#4834]
ALL OS ALL DEVICES ALL BROWSERS

Small iframe implementation with e.g. tooltip on trainstops: 

Result:
once opened 
- you can't close tooltip
- can't resize tooltip

expected result:

tooltip is
- usable even in small iframes 
eg. 
- minmal version of tooltip, scrollable
- open outside in new window/tab when on small screen

othee ideas?

[Test_GeoAdmin.zip](https://github.com/geoadmin/mf-geoadmin3/files/2960303/Test_GeoAdmin.zip)

Considering that almost 50% of our traffic is via iframes--I consider this  more than NTH

**Comment by procrastinatio** [comment]
@pakb Too much CSS... There are `tooltip` when you click on something, and `popover` when something is displayed without user interaction, like the address search opening a `popover` (see the iframe source link)

[Demo with 200x267px Iframe! (scroll down)](https://mf-geoadmin3.int.bgdi.ch/Test_GeoAdmin.html)

**Comment by pakb** [comment]
I've added a little rule for popup on mobile, I'll check if it doesn't break desktop and tablet as soon as it's built

**Comment by pakb** [comment]
top of tooltip is now ok, but it's still not good with the bottom. Part of the content (bottom part) is still hidden, I'll look into that

**Comment by pakb** [comment]
should be fixed on with test link of https://github.com/geoadmin/mf-geoadmin3/pull/4844
