### ISSUE TITLE
[Topic selector] topic 'dev' is on prod although it shouldn't according to BOD

### ISSUE THREAD

**Issue by mariokeusen** [geoadmin/mf-geoadmin3#4840]
UC: open mapviewer, open the topic selector
Result: besides "INSPIRE", a topic "dev" is visible on production
Expected: topic "dev" is never available on production.

Rq: In the BOD, the "dev" topic still has staging=test. So, theoretically, it is not possible to see that topic on prod.

**Comment by pakb** [comment]
Fixed, this mistake will not be possible anymore when https://github.com/geoadmin/mf-geoadmin3/pull/4835 will be merged

**Comment by mariokeusen** [comment]
thanks

**Comment by mariokeusen** [comment]
Same issue again...

**Comment by pakb** [comment]
fixed, but I have to look into why this has happened again even though we build the config before uploading it

**Comment by mariokeusen** [comment]
Ok, thanks

**Comment by procrastinatio** [comment]
`source rc_prod  && make clean configs/ s3uploadconfigprod`

**Comment by mariokeusen** [comment]
We got that again today... could you please refix?

**Comment by boecklic** [comment]
fixed. Will try to find a sustainable solution tomorrow
