### ISSUE TITLE
IMPORT https *.admin.ch for kml does not work

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#4851]
Try to add
https://www.geo.admin.ch/content/dam/geo-internet/de/files/S-Red_2019.kml 
in the import tool

result:
error
Failed to load https://www.geo.admin.ch/content/dam/geo-internet/de/files/S-Red_2019.kml: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://map.geo.admin.ch' is therefore not allowed access.
build.js:718 Uploading file failed:  {data: null, status: -1, headers: ƒ, config: {…}, statusText: "", …}
(anonymous) @ build.js:718
(anonymous) @ build.js:265
$digest @ build.js:276
$apply @ build.js:280
k @ build.js:231
v @ build.js:236
y.onerror @ build.js:237
error (async)
(anonymous) @ build.js:237
s @ build.js:233
(anonymous) @ build.js:230
(anonymous) @ build.js:265
$digest @ build.js:276
$apply @ build.js:280
(anonymous) @ build.js:323
dispatch @ build.js:60
y.handle @ build.js:60
build.js:238 Cross-Origin Read Blocking (CORB) blocked cross-origin response https://www.geo.admin.ch/content/dam/geo-internet/de/files/S-Red_2019.kml with MIME type application/vnd.google-earth.kml+xml.

Workaround

use http
http://www.geo.admin.ch/content/dam/geo-internet/de/files/S-Red_2019.kml

**Comment by procrastinatio** [comment]
Yes, to speed thing up, we assumed that all resources in the '*.geo.admin.ch' domain were CORS enabled. Which is not the case.
So back to step one, check if CORS is enabled and act upon.

**Comment by danduk82** [comment]
@davidoesch and @procrastinatio from what I understand the problem is that the CMS does not set CORS. The problem has to be solved by namics or aspectra.
@hpchrist do you think that you can treat this with aspectra?

**Comment by davidoesch** [comment]
ping @danduk82

**Comment by danduk82** [comment]
@davidoesch and @hpchrist can we ask to aspectra to add correct CORS headers on their CMS? I don't like at all the workaround made by @procrastinatio .
ping @pauloamado

**Comment by procrastinatio** [comment]
This 2019. We may assume people know how go configure CORS. If they don't
they probably don't want go share their datas.

Le ven. 26 avr. 2019 à 14:41, Andrea Borghi <notifications@github.com> a
écrit :

**Comment by davidoesch** [comment]
IMHO this is solved.
Try with 
https://www.swisstopo.admin.ch/content/dam/swisstopo-internet/de/files/karto-files/kml-files/S-Red_2019.kml

now it works -- someone changed sth
