### ISSUE TITLE
[MVT] style-spec supported features

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#4858]
the complete Style spec https://docs.mapbox.com/mapbox-gl-js/style-spec/

Which parts of those styles

- [ ] are supported
- [ ] will be supported in future
- [ ] will not be supported by ol6

-> pls check with Ol6 dev community @pakb and involve @swissgis3084 reagarding the swisstopo prio 

line-color
line-opacity
line-width
line-offset
line-pattern
line-dasharray
line-join
line-cap
line-gap-width
line-miter-limit
line-round-limit
line-blur
fill-color
fill-opacity
fill-outline-color
fill-antialias
circle-color
circle-opacity
circle-radius
circle-blur
icon-image
icon-size
icon-opacity
icon-rotation-alignment
icon-translate-anchor
icon-padding
icon-allow-overlap
icon-halo-blur
icon-halo-width
icon-halo-color
text-font
text-size
text-field
symbol-placement
symbol-avoid-edges
symbol-spacing
text-color
text-opacity
text-justify
text-letter-spacing
text-line-height
text-keep-upright
text-allow-overlap
text-padding
text-offset
text-rotate
text-halo-color
text-halo-width
text-halo-blur
text-max-angle
text-max-width
text-optional
text-transform
text-pitch-alignment
text-roatation-alignment
text-anchor
text-translate-anchor
raster-saturation
raster-hue-rotate
raster-contrast
raster-max-brightness
raster-min-brightness
raster-opacity
raster-fade-duration
background-color

**Comment by swissgis3084** [comment]
here is the list of specs used in our lighbasemap
**bold are currently not supported by OL**
? = not sure wether supported by OL or not

line-color
line-opacity
line-width
**line-offset**
**line-dasharray**
line-join
line-cap
**line-gap-width**
**line-miter-limit?
line-round-limit?**
fill-color
fill-opacity
fill-outline-color
fill-antialias? but antialias seems to be good in OL
icon-image
**icon-size?
icon-rotation-alignment?
icon-translate-anchor?
icon-padding?
icon-allow-overlap?**
text-font
**text-size? exactly the same as in mapbox?**
text-field
symbol-placement
**symbol-spacing** seems not to be supported: watercourse labels repeat far too often
**text-color? seem to be slightly different than in mapbox**
text-justify
text-letter-spacing
text-line-height
**text-keep-upright?
text-allow-overlap?
text-padding?**
**text-offset** seems to be different than in mapbox
text-rotate
**text-halo-color?** seems to be different than in mapbox
**text-halo-width?
text-halo-blur?
text-max-angle?
text-max-width?
text-transform? currently not used by our style: always set to "none"**
text-anchor
background-color

**Comment by pakb** [comment]
As we are using Mapbox engine to render tiles, we have now a 100% feature compliance 🎉
