### ISSUE TITLE
[MVT] caching not enabled

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#4861]
All os All Browsers

Start the testviewer zoom in and zoom out
then zoom in again

result:

the previous loaded datasets seem to loaded again (starting with a white square)

Expected result
Previous loaded  data loads immediately  from local storage

**Comment by davidoesch** [comment]
this flickering is really annoying... related/linked to https://github.com/geoadmin/mf-geoadmin3/issues/4860

**Comment by danduk82** [comment]
this also should be fixed using mapbox renderer as composite layer

**Comment by pakb** [comment]
Please check this again with the new Mapbox hybrid rendering (now live on test viewer). Maybe Mapbox will handle this better and we can close this issue.

**Comment by davidoesch** [comment]
Is fixed
