### ISSUE TITLE
[MVT] link on Re3 to test viewer

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#4864]
![image](https://user-images.githubusercontent.com/4577727/55161725-7e5c4100-5166-11e9-9aff-98330be8dc5e.png)

in red
DE : Probieren sie test.map.geo.admin.ch aus
FR : Essayez test.map.geo.admin.ch
EN: Try out test.map.geo.admin.ch
IT: Prova test.map.geo.admin.ch

**Comment by pakb** [comment]
In German, wouldn't it be more appropriate to capitalize the `Sie` from `Probieren sie test.map.geo.admin.ch aus`?

**Comment by davidoesch** [comment]
Correct , pls do so

**Comment by procrastinatio** [comment]
@pakb But wait... you speak German?
