### ISSUE TITLE
[MVT] Feedback window closed under 768px width

### ISSUE THREAD

**Issue by pauloamado** [geoadmin/mf-geoadmin3#4892]

**Comment by davidoesch** [comment]
precision:
if  embed.html is used (use case: iframe)

**Comment by davidoesch** [comment]
IMHO this is already solved for embed @pauloamado 

check
https://cms.geo.admin.ch/test/ol6/Comparepermalink.html

**Comment by davidoesch** [comment]
Sorry the link above works because LBM is not set as bg

**Comment by pauloamado** [comment]
And it doesn't work correctly on Edge

**Comment by davidoesch** [comment]
> And it doesn't work correctly on Edge

to many iframes for EDGE......

**Comment by pakb** [comment]
It doesn't look gorgeous, but in embed there's no toolbar so only the feedback modal is present
![image](https://user-images.githubusercontent.com/11540521/56961746-dd8de680-6b54-11e9-8274-eb905b1edb8c.png)

Do we need more than that?

**Comment by davidoesch** [comment]
It should look like this here on the right side
https://cms.geo.admin.ch/test/ol6/Comparepermalink.html

(Same as if pixelkarte is used as bg..  maybe by can even reuse the code)

**Comment by pakb** [comment]
online on https://mf-geoadmin4.int.bgdi.ch, please test and give me a feedback if that doesn't work as you expected
