### ISSUE TITLE
update translation DE RM

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#4894]
the following MSGID   for RM can be updated from the famous spreadsheet
msgid
--
3d_pegman_help
3d_pegman_tooltip
astra_alle_lastyear_casualties
azimuth_label
edit_confirm_reset_style
external_data_tooltip
feature
layer_cant_be_displayed_in_3d
layer_cant_be_printed
layer_invalid_outside_map
locations_results_header_fuzzy
meteoschweiz
meteoschweiz_service_link_label
plz
print_layout
shop_msg_title
topic_meteoschweiz_tooltip
url_image
url_link
url_video
vector_feedback_description_title
vector_feedback_tryit_title
vector_feedback_description_text
vector_feedback_choose_style
vector_feedback_select_style
vector_feedback_choose_layer
vector_feedback_choose_color
vector_feedback_labels_on_off
vector_feedback_getting_started_title
vector_feedback_create_your_own
vector_feedback_edit_map
vector_feedback_getting_started_1
vector_feedback_getting_started_2
vector_feedback_getting_started_3
vector_feedback_survey_title
vector_feedback_survey_btn_text
vector_feedback_survey_modal_title
edit_glstyle_choose_color
edit_glstyle_choose_layer
landuse-residential
landcover_grass
edit_not_possible
edit_current_layer
edit_fill_color
edit_text_color
edit_text_size
edit_text_halo_color
show
hide
displayed
hidden
edit_fill_outline_color
edit_line_color
edit_line_width
light_gray
light_green
light_blue
light_yellow
purple
edit_or_reset_style
basis
labels
roadtraffic
hydrology
landuse
settlement
edit_visibility
current_value

thx

**Comment by pakb** [comment]
done in https://github.com/geoadmin/mf-geoadmin3/pull/4903
