### ISSUE TITLE
[MVT] Service description link is wrong on fly out

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#4897]
ALL OS ALL BROWSERS
![image](https://user-images.githubusercontent.com/4577727/56878620-47bf6200-6a55-11e9-9429-0373cad4e591.png)

points to
https://api3.geo.admin.ch/services/sdiservices.html#vectortiles

instead of 
https://api3.geo.admin.ch/services/sdiservices.html#mapbox-vector-tiles

**Comment by pakb** [comment]
will be fixed with https://github.com/geoadmin/mf-geoadmin3/pull/4855
