### ISSUE TITLE
[MVT] deactivate 3D as well for bg pixelkarte farbig

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#4898]
since 3D does not work 
deactivate 3D button as well for bgLayer=ch.swisstopo.pixelkarte-farbe

 https://test.map.geo.admin.ch/?topic=ech&lang=de&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bav.haltestellen-oev,ch.swisstopo.swisstlm3d-wanderwege,ch.swisstopo.swissnames3d&layers_visibility=false,false,false,false,true&layers_timestamp=18641231,,,,&lon=7.42577&lat=46.93142&elevation=984&heading=360.000&pitch=-40.197

**Comment by boecklic** [comment]
solved with #4855
