### ISSUE TITLE
Attribute Search IVS does not work

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#4899]
ALL OS ALL BROWSER
1. Open application
2. Add the layer IVS National to the map
3. Type "BE 10.2.20" into the search field
4. Choose the first of the attribute search results

Result
2. layer is available in the map3. Attribut search results are listed
nothing happens

Expected result
4. Application zooms to an object between Thun and Steffisburg and the feature is highlighted

with  with :2. Add the layer ch.bfe.kehrichtverbrennungsanlagen3. Type "UTO"  it works

ping @mariokeusen

**Comment by mariokeusen** [comment]
Will be fixed with:
https://jira.swisstopo.ch/browse/BGDIDI_KB-33
https://jira.swisstopo.ch/browse/BGDIDI_KB-31
https://jira.swisstopo.ch/browse/BGDIDI_KB-30

**Comment by alcapat** [comment]
Search problem fixed with this PR: https://github.com/geoadmin/service-sphinxsearch/pull/398

**Comment by boecklic** [comment]
will be fixed with next deploy
