### ISSUE TITLE
[MVT] Link to testviewer with PL

### ISSUE THREAD

**Issue by gjn** [geoadmin/mf-geoadmin3#4904]
The new link from map.geo to the testviewer should include the current PL minus the background parameter. From the user perspective, it's 'how would this look in the new testviewer?'.

Map State in map.geo:
https://map.geo.admin.ch/?lang=en&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bav.haltestellen-oev,ch.swisstopo.swisstlm3d-wanderwege&layers_visibility=false,true,false,true&layers_timestamp=18641231,,,&E=2659711.46&N=1260393.89&zoom=9

**Current link to test**: 
https://test.map.geo.admin.ch/?lang=en

**New link to test**:
https://test.map.geo.admin.ch/?lang=en&topic=ech&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bav.haltestellen-oev,ch.swisstopo.swisstlm3d-wanderwege&layers_visibility=false,true,false,true&layers_timestamp=18641231,,,&E=2659711.46&N=1260393.89&zoom=9

**Comment by pakb** [comment]
Test link on https://github.com/geoadmin/mf-geoadmin3/pull/4907
