### ISSUE TITLE
[MVT] add banner to change browers if using IE11 (user agent detection)

### ISSUE THREAD

**Issue by danduk82** [geoadmin/mf-geoadmin3#4909]
the standard browser when opening a link from outlook is IE11, please add a banner that says that this browser is not supported.

**Comment by danduk82** [comment]
@davidoesch please provide the text that we are supposed to use for the banner. 
 please create a line with `msgid = mvt_ie11_alert`


@pakb please use `msgid = mvt_ie11_alert`

**Comment by mariokeusen** [comment]
@davidoesch I have just created the msgid with tmp text at the end of the spreadsheet.

**Comment by davidoesch** [comment]
translation: done

**Comment by danduk82** [comment]
deployed on production
