### ISSUE TITLE
cesium.js can not be loaded (staging int)

### ISSUE THREAD

**Issue by rebert** [geoadmin/mf-geoadmin3#4911]
Browser: Chrome
Issue: When switching to 3D following error appears:
![image](https://user-images.githubusercontent.com/2940619/57065121-b9ebad00-6cc8-11e9-9276-cef39b6ee8f4.png)

**Comment by pakb** [comment]
There's something fishy with staging, here's the problem IMO :
https://github.com/geoadmin/mf-geoadmin3/blob/6bd28ff2ce5300bfcb62d2ca46261638a881d22a/src/js/GaCesium.js#L22-L26

https://github.com/geoadmin/mf-geoadmin3/blob/6bd28ff2ce5300bfcb62d2ca46261638a881d22a/src/index.mako.html#L713-L727

So as long as we are hosted on `*.int.*` or `*.dev.*`, the app will try to get `Cesium.js` from `lib/Cesium/Cesium.js` whereas it's in fact located in `lib/Cesium.min.js` when it's deployed on int or dev...

What do we do?

**Comment by davidoesch** [comment]
remove prio1 because it is NOT affecting prod

**Comment by rebert** [comment]
@davidoesch first prio would be fine, as I need a testlink - 3D is going prod next week... on Monday

**Comment by pakb** [comment]
we can quick fix your testlinks, if needed, by copying Cesium.min.js to /Cesium/Cesium.js on the bucket you're using.

**Comment by boecklic** [comment]
solved. branches that need this should be rebased to `master`

**Comment by rebert** [comment]
@boecklic herzlichen Dank!
