### ISSUE TITLE
[MVT] Iphone X /macBookPro crash on load

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#4912]
iOS :12.2 browser: Safari Device: iPhone X and MacBookPro

Reproduce:
Enter : test.map.geo.admin.ch

Result:
![A5E78D98-DF1E-4C41-8844-5DDF48CF83C2](https://user-images.githubusercontent.com/4577727/57100554-812af280-6d1f-11e9-865b-301e26bf6272.jpeg)

Thread https://twitter.com/schvvyzer/status/1124024947708518406?s=21 and https://twitter.com/VeloSpinner/status/1124187170653315072?s=20

**Comment by davidoesch** [comment]
Firefox: 2 automatische reloads anschliessend schwarze seite.
Duckduckgo: dauerende reloads

**Comment by pakb** [comment]
Here's what I experience with my devices :
- I don't have an iPhone X to try out, but on my iPhone 8 (iOs 12.2) it loads without err
- MacBook Pro (late 2013 with latest MacOS 10.14.4, Safari 12.1) I have no issue loading the app
- On the MacBook Pro with Firefox 66.0.3 I have no issue loading the app either, no black screen or stuff like that.

For duckduckgo, I'm sorry but I don't see why it's related to us, could you clarify?
Could we get more information on how to reproduce?

**Comment by manuelroth** [comment]
I can reproduce this problem on iOS :12.2 browser: Safari Device: iPhone XS

![screencast](https://user-images.githubusercontent.com/1810384/57126250-a0139e00-6d8c-11e9-9ebd-fde4bf08ba11.gif)

**Comment by pakb** [comment]
Ok, I guess it should be linked to memory issue akin to https://github.com/geoadmin/mf-geoadmin3/issues/4733#issuecomment-488652333
We're facing some issue with "out of memory" on iOs devices, we need to investigate more

**Comment by pakb** [comment]
Memory issue has been reported as a separate issue here : https://github.com/geoadmin/mf-geoadmin3/issues/4916
What bothers me is that, on an iPhone X(S/R), out of memory seems to behave differently than on other iOs devices.
@davidoesch do you know anyone at swisstopo that own an iPhone latest gen (X, XS or XR)? I'd gladly have a look at the console output while the issue is active

**Comment by manuelroth** [comment]
@pakb here is the console output of the crashing site on iOS Safari:

<img width="998" alt="Screenshot 2019-05-03 at 13 15 38" src="https://user-images.githubusercontent.com/1810384/57134223-b9751400-6da5-11e9-9c35-5f4667458d3e.png">

I am glad to help if you need any more information

**Comment by manuelroth** [comment]
After some more pitch and zooming around I am getting this errors:

<img width="998" alt="Screenshot 2019-05-03 at 13 21 07" src="https://user-images.githubusercontent.com/1810384/57134530-b6c6ee80-6da6-11e9-8351-28a084a5ac49.png">

<img width="999" alt="Screenshot 2019-05-03 at 13 22 03" src="https://user-images.githubusercontent.com/1810384/57134535-bdedfc80-6da6-11e9-83a2-e4b82523f75c.png">

So I think you are right that its connected to out of memory issue. BTW [TrackJS](https://trackjs.com/) could help log the JS-Error happening on your clients devices. Could be pritty helpful to find problems before your users are reporting them to you

**Comment by fredj** [comment]
@manuelroth do you have the same errors with this page: https://5yq2mn7pjk.codesandbox.io/ ?
It's the map only, without the geoadmin code.

**Comment by manuelroth** [comment]
@fredj yes getting the same error:

<img width="997" alt="Screenshot 2019-05-03 at 16 27 33" src="https://user-images.githubusercontent.com/1810384/57144123-a58adb80-6dc0-11e9-89ae-b56e2f2f1118.png">

![IMG_2294](https://user-images.githubusercontent.com/1810384/57144143-ae7bad00-6dc0-11e9-88e7-085a102877ae.JPG)

**Comment by pakb** [comment]
Same with other issues gathered in https://github.com/geoadmin/mf-geoadmin3/issues/4924, as we've moved to use Mapbox to render vector tiles, performance and memory management has been improved. This can be closed as it's been fixed IMO.

**Comment by davidoesch** [comment]
Fixed. Tested on iPhone x

**Comment by manuelroth** [comment]
I can confirm as well. The issues are resolved. Tested on iPhone XS
