### ISSUE TITLE
{{langId}} is not (yet) availble in index.html

### ISSUE THREAD

**Issue by boecklic** [geoadmin/mf-geoadmin3#4913]
...hence links that use it are not correct (e.g. https://www.geo.admin.ch/{{langId}}/about-swiss-geoportal/impressum.html results in https://www.geo.admin.ch//about-swiss-geoportal/impressum.html)

**Comment by pakb** [comment]
Aren't URLs starting with www.geo.admin.ch managed on the CMS config?

**Comment by boecklic** [comment]
it's a link inside mf-geoadmin index.html that poinst to www.geo.admin.ch, depending on the language that is used to view test.map.geo.admin.ch (and is not available, hence empty). 
https://github.com/geoadmin/mf-geoadmin3/blob/master/src/index.mako.html#L457

**Comment by pakb** [comment]
testlink on PR https://github.com/geoadmin/mf-geoadmin3/pull/4915
