### ISSUE TITLE
[MVT] floating labels

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#4916]
Reproduced several times
on
iPhone 8 iOS 12.2 
by @pauloamado 

See: https://cms.geo.admin.ch/test/viewer/test.map.geo.admin.ch.ios.mp4

**Comment by pakb** [comment]
Here's the console output when this happens :
![image](https://user-images.githubusercontent.com/11540521/57133980-dc52f880-6da4-11e9-8ed3-bd3ca997740c.png)

Out of memory somehow.

**Comment by pauloamado** [comment]
It seems to be a known issue
https://github.com/openlayers/openlayers/issues/8956

**Comment by davidoesch** [comment]
If u want to reproduce very fast with a real use case (one of the most b used combination)
http://map.schneesport.admin.ch/
Switch to LBM

**Comment by davidoesch** [comment]
And another nice one: open on iOS within Twitter app
Switch styles . Stalls
https://photos.app.goo.gl/RwKSdrGD45dvtxrf9

**Comment by pakb** [comment]
IMHO this can be closed as Mapbox handles its cache with what is available (I wasn't able to make my iPhone 8 crash like before after having loaded a huge amount of PBF tiles and switched a couple times backgrounds).
@davidoesch Could you also give it a try on your phone and close this if you find the result satisfying?

**Comment by davidoesch** [comment]
Tested on iPhone... After 15 min not reproducable
