### ISSUE TITLE
[MVT] switching styles crashing

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#4919]
All iOS devices
Start test viewer
Quickly change the styles

Result app crashes
https://photos.app.goo.gl/c6JZzskRnrPWFkpQA

It is an extreme use case however...

**Comment by pakb** [comment]
As we're now delegating rendering (and caching & co) to Mapbox, this could have been improved.
On my iPhone 8, after about 100 changes of style in a row it still works nicely.

**Comment by davidoesch** [comment]
Same here. Thx for the fix
