### ISSUE TITLE
[MVT] background: don't show lbm if other BG is active

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#4928]
All os
All browsers

If other than lbm is selected as BG: don't show lbm

Pls stick to the specs. Don't introduce changes

**Comment by gjn** [comment]
This is prio 1 for me as it also degrades performance when LBM is not background.

**Comment by pakb** [comment]
Fix is on test.map.geo.admin.ch

**Comment by pakb** [comment]
deployed
