### ISSUE TITLE
notooltip=true  not active when not in iframe

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#4930]
*As*          a end user
*I want*    notooltip=true  always overridden/ set to false when not in ifmrame/embed.html
*because* if i leave application sites like https://www.meteoschweiz.admin.ch/home/messwerte.html?param=messwerte-lufttemperatur-10min or in future as well http://hydrodaten.admin.ch/de/messstationen_temperatur.html  I want to have in in the no i frame application the tooltip function working, eg the notooltip=true parameter removed

*Deliverable*
- [ ] permalink rewrite?

*how to demo*
if on https://www.meteoschweiz.admin.ch/home/messwerte.html?param=messwerte-lufttemperatur-10min cliked on a station. no tooltip shown. if clicked on "in map.geo.admin.ch ansehen" the viewer opens with https://map.geo.admin.ch/?topic=ech&lang=de&bgLayer=voidLayer&zoom=1.25&showTooltip=false&layers=ch.bafu.gefahren-basiskarte,ch.meteoschweiz.messwerte-lufttemperatur-10min&ch.meteoschweiz.&layers_opacity=0.4,1

**Comment by gjn** [comment]
The parameter is undocumented and was specifically introduced for iframe. So I'm fine with this change.

**Comment by boecklic** [comment]
pls test: mf-geoadmin3.int.bgdi.ch/?notooltip=true should show the tooltip

**Comment by davidoesch** [comment]
LGTM
