### ISSUE TITLE
Rollback for layers config

### ISSUE THREAD

**Issue by procrastinatio** [geoadmin/mf-geoadmin3#4936]

**Comment by davidoesch** [comment]
Since I Assume this is a bug which breaks the deploy...

**Comment by pakb** [comment]
it's more like a security net for the deployer

**Comment by procrastinatio** [comment]
No this is a new urgent feature. For the last 10 years, we deployed again and again.

**Comment by procrastinatio** [comment]
Closing with https://github.com/geoadmin/mf-geoadmin3/pull/4952
