### ISSUE TITLE
"Draw a rectangle" button for shop layers does not work on MacOS 10.14

### ISSUE THREAD

**Issue by AFoletti** [geoadmin/mf-geoadmin3#4939]
**Customer feedback ID : 2019051411065017**

On MacOS 10.14.4, the "Draw a rectangle" button for shop layers does not work.

Steps to reproduce:
**Please note that I currently have no way to test on such a system (macs are today out of house).**

1.  open [this link](https://s.geo.admin.ch/81e72b1958)
2.  click on a location where there is data available
3.  in the tooltip, choose "Extent" as selection method
4.  try to use the button to draw a rectangle as purchase selection

Tasks:
- try to reproduce on the right OS
- confirm bug/nobug on our side to customer, and guide him to a solution or inform him about the ongoing fixing

Thanks!

**Comment by pakb** [comment]
So I've tried it on a MacBook Pro with MacOS 10.14.4 and Safari 12.1, and I can't reproduce this bug.
I've also tried reproducing it on Chrome and FF on the same system with no avail.

The "Draw a rectangle" button didn't need any interaction though. It was activated as soon as I chose the Extent selection method (but was working fine if I used it afterward).

**Comment by AFoletti** [comment]
Ok, thanks for checking this out. I will contact the customer directly and try to understand what he does wrongly.
I will update and close the ticked once settled

**Comment by pakb** [comment]
The cursor is not hinting that it's working though. When the draw rectangle button is active it's still a hand, we could switch to a crosshair to make it more obvious it's active...

**Comment by AFoletti** [comment]
The customer confirmed that it works. He simply did not notice the button activation.
Thus yes, I suggest we make the cursor a crosshair when the "draw a rectangle" function is active to differentiate from the "pan the map" status.

**Comment by AFoletti** [comment]
@pakb maybe something for @Simon1193 ?

**Comment by pakb** [comment]
I had looked into it for little over an hour, it's not that trivial in the code (what is trivial nowadays in this project? 😉)

**Comment by AFoletti** [comment]
Ok. That's truly a minor issue and could be closed if @boecklic and @davidoesch agree
