### ISSUE TITLE
[MVT] kml Tooltip pop does not work anymore

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#4940]
ALL OS ALL BROWSER

Open KML

https://test.map.geo.admin.ch/?lang=en&topic=ech&bgLayer=ch.swisstopo.leichte-basiskarte.vt&zoom=10&lat=47.3764&lon=7.3368&layers=KML%7C%7Chttp:%2F%2Fpnac.swisstopo.admin.ch%2Fdivers%2Fdens_vel%2Feu_dens_vel_val_basic.kml

click on icon

result:
no tooltip

expected result:
Tooltip appears

This worked a couple weeks ago..so pls update as well the tests

**Comment by boecklic** [comment]
will be resolved once https://github.com/geoadmin/mf-geoadmin3/pull/4925 is deployed (failing tests need to be fixed first)

**Comment by davidoesch** [comment]
Here’s what will be online today if tests go well : https://mf-geoadmin4.int.bgdi.ch/?layers=KML%7C%7Chttp:%2F%2Fpnac.swisstopo.admin.ch%2Fdivers%2Fdens_vel%2Feu_dens_vel_val_basic.kml

**Comment by pakb** [comment]
fix is live on test viewer
