### ISSUE TITLE
[MVT] Baselayer should be the lowest layer - and not cover WMS layers

### ISSUE THREAD

**Issue by Rdataflow** [geoadmin/mf-geoadmin3#4941]
The baselayer covers 3rd party WMS layers partly or even globally.
Case a) base layer = basiskarte light: only the swiss part is hidden (below the base layer)
https://s.geo.admin.ch/81e60b26b3 
![image](https://user-images.githubusercontent.com/26090254/57836599-55991500-77c1-11e9-8122-5d750cd30e18.png)

Case b) other baselayers = [landeskarte | ortophoto]: the third party layers are entirely hidden (below the base layer)

**Comment by pakb** [comment]
Please have another look, it should have been fixed by today's deployment.

**Comment by davidoesch** [comment]
@rdataflow your source is not working.
Please test and reopen if it is not working

**Comment by pakb** [comment]
I got it working after waiting for a long time, and data was displayed correctly.

**Comment by davidoesch** [comment]
In this case you are more patient than me ....
