### ISSUE TITLE
[print] does not work for layer ch.bafu.wald-vegetationshoehenstufen_1995 on scales 1:25'000 or larger

### ISSUE THREAD

**Issue by mariokeusen** [geoadmin/mf-geoadmin3#4946]
![image](https://user-images.githubusercontent.com/4577749/58002077-9f457080-7add-11e9-9922-bf0c11a7a175.png)
UC: open mapviewer, add layer ch.bafu.wald-vegetationshoehenstufen_1995, print a pdf in 1:25'000 or larger scale
Result: no data visible or only incomplete tiles (see image)
Expected: data are printed completely

Workaround: looks like a tile cache issue.

https://s.geo.admin.ch/81ff64648b

**Comment by Sgachet** [comment]
Sorry, I cannot reproduce it... 
I'll investigate a little more in the next few days

**Comment by davidoesch** [comment]
can not reproduce it anymore: related to ToD downtime? @danduk82

**Comment by mariokeusen** [comment]
cannot reproduce anymore as well
