### ISSUE TITLE
Geolocalisation Rotate does not work anymore on mobile 

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#4947]
ALL ios
ALL mobile devices 
All Safari

Reproduce
open viewer in browser or via homescreen link
try to rotate map via  geolocation button
https://help.geo.admin.ch/?id=27

result:
only position  not an arrow of device orientation and maps is not rotating on second click

expected result
only position , arrow of device orientation , rotate map on second click

works in chrome on ios

**Comment by pakb** [comment]
Is the help broken? I have only header and footer when I open the link you've provided

I also noticed that if you double tap slightly out of the button (on the app header bar) the whole app is being zoomed which is really bad for mobile experience, we should address that too

**Comment by davidoesch** [comment]
Help works.

**Comment by pakb** [comment]
Say thanks to Apple for another round of breaking changes without giving much crap about existing apps and developers : https://www.macrumors.com/2019/02/04/ios-12-2-safari-motion-orientation-access-toggle/
It's a "simple" toggle to activate on your device (as seen in the link above), and Safari can access accelerometer again (but by default it's off, for fun's sake).
On iOs Chrome there's no issue as this toggle is not taken into account.

**Comment by davidoesch** [comment]
Paulo
Can u add to https://help.geo.admin.ch/?id=27
With reference to the link above
"iOS 12.2 above: activate Motion & Orientation Access toggle under Settings > Safari > Privacy & Security. Toggled off by default, this new setting must be turned on in order for map.geo.admin.ch  to display your  Position on the iPhone, iPad, and iPod touch. "

**Comment by pauloamado** [comment]
Done
