### ISSUE TITLE
[MVT] Some layers don't react to opacity change anymore

### ISSUE THREAD

**Issue by pakb** [geoadmin/mf-geoadmin3#4949]
Try with "Register of Buildings and Dwellings", changing its opacity doesn't affect the layer. But the other 3 layers of "The big 4" works.

I'm investigating if latest changes in OL6 beta could have broken something on our side.

**Comment by pakb** [comment]
issue opened it OL issue tracker https://github.com/openlayers/openlayers/issues/9587

**Comment by davidoesch** [comment]
https://map.geo.admin.ch/?lang=en&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.swissnames3d is also aggregated layer WMS WMTS (last 2 zoom level?)

**Comment by pakb** [comment]
yep, same behaviour, so it's definitely linked to aggregate layer, that's a good starting point! thanks for the hint.

**Comment by pakb** [comment]
so this is something than need to be fixed in OL, we are waiting for a patch

**Comment by pakb** [comment]
related issue in OL : https://github.com/openlayers/openlayers/issues/9587

**Comment by pakb** [comment]
will be fixed by https://github.com/geoadmin/mf-geoadmin3/pull/4964

**Comment by pakb** [comment]
live on https://test.map.geo.admin.ch
