### ISSUE TITLE
Overlays are drawn on top of baselayer labels

### ISSUE THREAD

**Issue by manuelroth** [geoadmin/mf-geoadmin3#4951]
### Description
At the moment you are using Mapbox GL JS to draw the basemap and OpenLayers to draw the overlays on top. I understand that you want to preserve the projection (LV95) of your overlay geometries and therefore want to use OpenLayers for its support of projections. But this approach introduces a visual problem:

![Screenshot 2019-05-21 at 09 35 57](https://user-images.githubusercontent.com/1810384/58077699-5e1c9180-7bad-11e9-937d-f056c58a0b6d.png)

The overlays like hiking trails in the example above overlap the labels of the basemap (See Schlieren). The benefit of rendering the map on client-side is exactly this. You have full control over the layering. But if you are using a different rendering engine for the overlays you loose this benefit. 
I would highly recommend you using Mapbox GL JS also for the overlays. So you have full control over the layering. See [this example](https://docs.mapbox.com/mapbox-gl-js/example/geojson-layer-in-stack/) in Mapbox GL JS

**Comment by pakb** [comment]
We are currently using a hybrid approach. We delegate the background vector tile rendering to Mapbox, but still use OpenLayers for overlays as we don't want to have to rewrite the whole app to accommodate to Mapbox (that's something that could happen in the future).
So for now we will have to live with it, labels won't be on top.

**Comment by manuelroth** [comment]
I understand. If I would be evaluating SwissTopo maps for my product this would definitely be a minus. So I think this should definitely have a priority. One workaround could be to give the option to disable label-layers in the basemap. Maybe for some usecases they are not necessary. 

An argument for rewriting the overlay/marker code could be to not only accomodate Mapbox GL JS, but abstract away the specifics of OpenLayers/Mapbox GL JS. So you are more flexible in the future, if there is a new rendering library thats popular.

**Comment by davidoesch** [comment]
Thanks for the feedback.
As this is a test viewer - its not intended for operational use.
If vector tiles will go into production, most layers will be accessible via this service and therefore u as developer can choose whatever framework u desire. 
The full description of our services are here http://vectortiles.geo.admin.ch/
We would be happy if you can fill out the survey and add your description above to it https://findmind.ch/c/vectortilesEN
