### ISSUE TITLE
Open a local KML via Permalink

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#4963]
Use case
I want to open via permalink (eg generated from excel) a local stored KML file eg
https://map.geo.admin.ch/?zoom=13&lang=de&topic=ech&bgLayer=ch.swisstopo.swissimage&E=2759456.05&N=1191617.85&layers=KML||file:///C:/temp/Alignment.kml

does not work -- possible to support the local storage url in Permalink?

**Comment by procrastinatio** [comment]
You can't open file dialogue programmatically (JS) on the client, it would be a huge security risk. The only user-triggered events may open a local file.
What is allowed is to have a list of links, and let the user click on all to load the files.

**Comment by davidoesch** [comment]
Donath: Save the files on a local network drive .... And link to it
