### ISSUE TITLE
provide a working testlink for DIEMO

### ISSUE THREAD

**Issue by danduk82** [geoadmin/mf-geoadmin3#4969]
**as:** me
**I want:** a working link 
**because:** I want to see how DIEMO is going on

please provide a link that allows to test:
- geoadmin with the new symbology 
- the new tooltips
- the `where` working to search for stations
- based on INT DIEMO infrastructure

**Comment by AFoletti** [comment]
This was a deliverable for the sprint who ended last Friday. I guess we will hear something once @ltkum comes back?

**Comment by rebert** [comment]
Querying CHSDI:
https://jira.swisstopo.ch/browse/BGDIINF_SB-837

On the db and service side the feedback of Hertach has been implemented:
Here are some query examples. But in general here is the URL to get all Attrbutes queriable:
https://mf-chsdi3.dev.bgdi.ch/ltrea_diemo/rest/services/all/MapServer/ch.bfe.ladestellen-elektromobilitaet?lang=de
Get all stations nearby 2000m where IsOpen24Hours:
http://mf-chsdi3.int.bgdi.ch/ltrea_diemo/rest/services/all/MapServer/identify?geometry=2577070,1184860&mapExtent=0,0,100,100&imageDisplay=100,100,100&geometryFormat=geojson&geometryType=esriGeometryPoint&lang=fr&layers=all:ch.bfe.ladestellen-elektromobilitaet&returnGeometry=true&tolerance=2000&sr=2056&where=IsOpen24Hours+=+%27true%27
Get the station having the evse with the ID CH*CCC*EBS*1763*2:
http://mf-chsdi3.dev.bgdi.ch/ltrea_diemo/rest/services/all/MapServer/identify?layers=all:ch.bfe.ladestellen-elektromobilitaet&returnGeometry=true&where=EvseID+ilike+%27%CH*CCC*EBS*1763*2%%27
Get the stations in Würelingen:
http://mf-chsdi3.dev.bgdi.ch/ltrea_diemo/rest/services/all/MapServer/identify?lang=de&layers=all:ch.bfe.ladestellen-elektromobilitaet&returnGeometry=true&where=City+ilike+%27%W%C3%BCrenlingen%%27
To be able to query lists, following lists have been converted to an aggregated string - is this ok?
QueryPlugs
QueryChangingFacitilies
QueryPaymentOptions
QueryAuthenticationModes
And concatenated values:
Address
GeoCoordinates

**Comment by danduk82** [comment]
https://mf-chsdi3.int.bgdi.ch/diemo/shorten/82d8d2de5a
