### ISSUE TITLE
iOS mobile Search bar hidden 

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#5042]
iOS 13.1
iPhone

Search bar hidden
Reproduce
https://photos.app.goo.gl/cgFnNozHYBB4kLwdA

**Comment by pakb** [comment]
How come you don't have the URL bar anymore? On my device (iPhone 8) the address bar doesn't hide (neither on Chrome or Safari) when visit map.geo.admin.ch

**Comment by davidoesch** [comment]
Start the Application from home screen link

**Comment by pakb** [comment]
So this is very tricky.
This toolbar seems to appear only when some form of inputs are activated (checkbox, text input, ...) but not always.
For instance, on my device, the activation of the search bar doesn't trigger this toolbar. The selection of a search result does (see https://photos.app.goo.gl/zb79Gad8E4ri2PgNA)

And when you play with the iOs built-in zoom for web page, some weird stuff happens (sometimes at 100% the search bar is correctly positioned under the toolbar, sometime not)
see https://photos.app.goo.gl/W53d8vCCW3ynsqir5

IMHO we should wait for Apple to fix this on their own, we can't meddle with this behaviour without risking breaking the user experience for some devices while fixing it for others (no easy fix).

**Comment by davidoesch** [comment]
How do other mobile website  tackle this issue?
Is there an eta for a fix by Apple?

**Comment by AFoletti** [comment]
As info, this is coming up in the helpdesk too.
Ex: Customer feedback ID : 2019100211270018

**Comment by mariokeusen** [comment]
Another customer observation with iphone 11 and latest iOS, which could be related to this:
![image](https://user-images.githubusercontent.com/4577749/66479134-25b61b00-ea9c-11e9-84e5-58c835ec4e9a.png)

**Comment by davidoesch** [comment]
Will be fixed with https://github.com/geoadmin/mf-geoadmin3/pull/5050

**Comment by pakb** [comment]
@mariokeusen was that also while using geoadmin as a homescreen link, or straight out of Safari?

**Comment by davidoesch** [comment]
thanks @boecklic  for fixing this

**Comment by pakb** [comment]
has been deployed.
It is mandatory to recreate a new homescreen link to fix this issue as iOs store the HTML page on the device when creating one.
Browser cache should be emptied beforehand. A good way to check that it is the case is that it should prefill app name with `Map of Switzerland` (and only this text, not the full title `Maps of Switzerland - Swiss Confederation  - map.geo.admin.ch`) when creating the Homescreen link.
