### ISSUE TITLE
identify tolerance on vector tooltip wrong

### ISSUE THREAD

**Issue by eraymann** [geoadmin/mf-geoadmin3#5055]
all OS 
all platform

**how to reproduce**

open map.geo.admin.ch
add two kmls https://s.geo.admin.ch/84e500f436

klick on one point which is close to antoher point of the other kml

**result**
highlight ok but tooltip contains info from a not highlighted  point from other kml

![image](https://user-images.githubusercontent.com/29711349/66631673-012a8200-ec07-11e9-8369-b08ba09e0837.png)

**expected result**
only highhlighted geometries are shown in tooltip

**workaround**
none

@davidoesch  thinks: regress of 
https://github.com/geoadmin/mf-geoadmin3/pull/5052

**Comment by davidoesch** [comment]
Raised the prio to a showstopper, since the kml choosen is arbitrary.
and this feature is core for the validation of the addresses with the cantons

**Comment by pakb** [comment]
would it make more sense to highlight multiple features with a single click, like the identify for any other type of layers (WMTS, WMS, ...), and show all highlighted features in the tooltip?

**Comment by davidoesch** [comment]
it should highlight and show only the closest one. if there is a need to select multiple  points: then the user should use select by rectangle.
 do mind: this should work next tuesday 15.10 since there will be a communication to all cantons

**Comment by pakb** [comment]
so what happend when there's two sources of features?
for instance I activate both "Temperature 2 m, 10 min" and "Sunshine duration, 10 min", I click on a station, which tooltip should I show? (both layers have the same stations so same positioning)

**Comment by pakb** [comment]
Underlying question : why are we doing something different only for vector layers? our API works as I have described above, a click returns every features under the click taking tolerance into account.

**Comment by AFoletti** [comment]
I think it actually gets just one feature, but actually duplicates it and opens a tooltip with different headers.
One is 100% right, the second one has all the attributes of the first (and is actually the same object) but has the header of the second layer.

**Comment by davidoesch** [comment]
> Underlying question : why are we doing something different only for vector layers? our API works as I have described above, a click returns every features under the click taking tolerance into account.

it dos not work like this for the issue stated on top. you get arbitrary results.....

**Comment by davidoesch** [comment]
@pakb pls do quick call @AFoletti he will explain

**Comment by AFoletti** [comment]
Additional problem: the tooltip for the light blue polygons does not work, while it does for the violet ones

**Comment by pakb** [comment]
testlink with same KML : https://mf-chsdi3.int.bgdi.ch/shorten/84f44839d7

**Comment by AFoletti** [comment]
The double tooltip problem is fixed.
Not so the missing tooltip for the bluish polygones. Could you please have a look?

**Comment by pakb** [comment]
Testlink updated with the fix for polygon identify

**Comment by AFoletti** [comment]
Wonderful! It works perfectly for me.
@eraymann could you please test?

**Comment by eraymann** [comment]
Yep, works as desired. Well done, thanks @pakb !

**Comment by davidoesch** [comment]
Then let’s close our

**Comment by pakb** [comment]
it's been deployed
