### ISSUE TITLE
identify  on vector tooltip is wrong

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#5073]
all OS
all platform

**how to reproduce**

open map.geo.admin.ch
add  kml http://data.geo.admin.ch/ch.bfs.gebaeude_wohnungs_register/address/OW/OW_str.kml 

klick on ballon in Yellow rectangel below
https://s.geo.admin.ch/8599f25398

![image](https://user-images.githubusercontent.com/4577727/68936299-85d66600-079a-11ea-99b8-7502f4c73b1f.png)

Result:
point in "ried" is also highlighted

Expected result
point in "ried" is not highlighted

And
Klick on ballon in yellow "ried" above

![image](https://user-images.githubusercontent.com/4577727/68936440-d8178700-079a-11ea-8397-717af01184ae.png)

Result:
No highlight of the ballon

Expected result:
Hilghlight ballon

**workaround**
none

Maybe related https://github.com/geoadmin/mf-geoadmin3/issues/5055 

according to @eraymann  this issue was introduced approx 3 weeks ago

**Comment by pakb** [comment]
The two "bubbles" correspond to the same feature in the KML :
![image](https://user-images.githubusercontent.com/11540521/69136190-b419b580-0aba-11ea-90f6-f2d673ac02dc.png)
![image](https://user-images.githubusercontent.com/11540521/69136220-c136a480-0aba-11ea-8d27-9af0e69c94d2.png)
![image](https://user-images.githubusercontent.com/11540521/69136235-c98edf80-0aba-11ea-9140-c12a0f27d58e.png)

Isn't that a bit weird?

**Comment by davidoesch** [comment]
@eraymann  can you elaborate?

**Comment by eraymann** [comment]
reproduction case is wrong

**how to reproduce**

load kml as described above
click on any yellow balloon

result A (upper left yellow balloon):
two points are highlighted. This is the expected result (yellow points indicate naming duplication, in this case Ried)

result B (lower left yellow balloon):
cannot select/highlight point.

note
yellow points are always multipoints with at least two vertices.
seems like one of the yellow points is kind of covered by yellow polygon and cannot be selected.
expliciteliy set z-level of features in kml does not fix the problem.

**Comment by pakb** [comment]
I think this is more related to the fact that I haven't though about multipoint possibilities in the vector feature selection.
I'm calculating the distance with the mouse pixel with what's called a "simplified geometry" and I suspect the duality of the multi point is lost in this process. Then only the first coordinate is taken into account, hence only one of them is working. I'll make a fix for that.
