### ISSUE TITLE
Where is documentation?

### ISSUE THREAD

**Issue by lucamanga** [geoadmin/mf-geoadmin3#5119]
Hello,

I could not find documentation on how to prepare and configure a simple project and how to deploy ir. Where is it?

**Comment by procrastinatio** [comment]
Thank you for your kind interest in `map.geo.admin.ch`.

Unfortunately, there is nothing simple in this project, you also need to install a complex backend (https://github.com/geoadmin/mf-chsdi3), a tile server, a print server and above all, it is pretty much at the end of the road (it's still running AngularJS 1).

Some very motivated users have managed to fork and install this project, as the Italian region of Trentino (https://webgis.provincia.tn.it/wgt/), not to discourage you, but it's a daunting task.

You may have a look at http://api3.geo.admin.ch/

**Comment by boecklic** [comment]
@boecklic commented: Thank you for your kind interest in `map.geo.admin.ch`.

Unfortunately, there is nothing simple in this project, you also need to install a complex backend (https://github.com/geoadmin/mf-chsdi3), a tile server, a print server and above all, it is pretty much at the end of the road (it's still running AngularJS 1).

Some very motivated users have managed to fork and install this project, as the Italian region of Trentino (https://webgis.provincia.tn.it/wgt/), not to discourage you, but it's a daunting task.

You may have a look at http://api3.geo.admin.ch/
