### ISSUE TITLE
KML: icon image not loaded (via service-proxy)

### ISSUE THREAD

**Issue by fredj** [geoadmin/mf-geoadmin3#5129]
Hi all,

I'm trying to import [this](https://dev.suissealpine.sac-cas.ch/api/1/protection_rules_en.kml) KML into geoadmin but the icon image is not correctly loaded.

The service-proxy returns an HTTP 403 error:
https://service-proxy.prod.bgdi.ch/https/dev.suissealpine.sac-cas.ch/img/icons/poi_routes/plain/condition_warning.svg

This KML is correctly displayed by OpenLayers using this example:
https://openlayers.org/en/latest/examples/drag-and-drop.html

**Comment by fredj** [comment]
```
curl -e "https://map.geo.admin.ch/" https://service-proxy.prod.bgdi.ch/https/dev.suissealpine.sac-cas.ch/img/icons/poi_routes/plain/condition_warning.svg
```
Returns:
```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>403 Forbidden</title>
<h1>Forbidden</h1>
<p>Forbidden content-type</p>
```
So I guess allowing `svg` as content-type should fix the issue

**Comment by davidoesch** [comment]
> http://www.feedvalidator.org/check.cgi?url=https%3A%2F%2Fdev.suissealpine.sac-cas.ch%2Fapi%2F1%2Fprotection_rules_en.kml

returns

> This feed does not validate.
> 
> line 9, column 16: Unexpected id attribute on Icon element (2 occurrences) [help]
> 
>                 <Icon id="54">
>                 ^
> In addition, interoperability with the widest range of feed readers could be improved by implementing the following recommendation.
> 
> line 2, column 0: Use of unknown namespace: http://www.google.com/kml/ext/2.2 [help]
> 
> <kml xmlns="http://www.opengis.net/kml/2.2" xmlns:gx="http://www.google.com/ ...

**Comment by procrastinatio** [comment]
@fredj Just deployed (https://github.com/geoadmin/service-proxy/releases/tag/r_2020317)

Looks ok:
```
curl -I   https://service-proxy.prod.bgdi.ch/https/www.procrastinatio.org/tmp/simple2.svg
HTTP/1.1 200 OK
Content-Type: image/svg+xml
Content-Length: 134808

```

**Comment by fredj** [comment]
Thanks @procrastinatio !
