### ISSUE TITLE
Add altitude in the coordinates shown in the footer

### ISSUE THREAD

**Issue by p1d1d1** [geoadmin/mf-geoadmin3#5143]
Sorry, mistyped the title.
Customer feedback 2020033012094603:
"Sarebbe più confortevole che quando muovo il mouse vedo le coordinate x,y e … anche z (livello sul mare)"

**Comment by davidoesch** [comment]
It is solved with right mouseclick

**Comment by p1d1d1** [comment]
yes i know and suggested that, but not very "friendly" according to the user. 
I'm just reporting !

**Comment by pakb** [comment]
This will be very resource intensive, as it will require an API call to the backend each little move of the mouse. I would not recommend that.
Currently, when you right click, one of those API request to the height service is made, that's how the information is retrieved.
