### ISSUE TITLE
[topics] topic catalogs astra and bafu are not loaded in some languages

### ISSUE THREAD

**Issue by mariokeusen** [geoadmin/mf-geoadmin3#5174]
UC: open application, turn language to German, switch the topic to ASTRA and/or BAFU
Result: topic is switched, but the catalogs ASTRA/BAFU are not visible. Nothing is shown in DE. ASTRA works in all other languages, BAFU as well apart from DE and FR.
Expected: topic catalogs are loaded in all languages
![image](https://user-images.githubusercontent.com/4577749/82794318-91ee5f00-9e72-11ea-9ac5-0ce777ec5a07.png)

This seems to be a new issue since the latest release. I have never observed it before.

**Comment by mariokeusen** [comment]
Same problem in EN for Topic nga:
https://map.geo.admin.ch/?lang=en&topic=nga&bgLayer=ch.swisstopo.pixelkarte-grau&layers_opacity=0.75&E=2719706.14&N=1184773.16&zoom=3&catalogNodes=15066,15041

**Comment by ltclm** [comment]
some of the catalog json on s3  and in cloudfront are not valid:
https://map.geo.admin.ch/configs/de/catalog.bafu.json -> error
https://map.geo.admin.ch/configs/fr/catalog.bafu.json -> error
https://map.geo.admin.ch/configs/it/catalog.bafu.json -> correct

The makefile targets for the generation of the config json should be improved
- [ ] check if mf-chsdi response is a valid json 

@pakb what do you think?

**Comment by p1d1d1** [comment]
swisstopo topic in "ita" is also affected (customer feedback)

**Comment by ltclm** [comment]
The config files have been fixed. Catalog / language change should work now.
@mariokeusen could you verify if anything is working as expected now.

**Comment by mariokeusen** [comment]
yes, works again as expected, thx4fixing!
