### ISSUE TITLE
[swiss search] Can not find layer ch.swisstopo.swisstlm3d-wald with chrome

### ISSUE THREAD

**Issue by consta-v** [geoadmin/mf-geoadmin3#5188]
UC: open app in chrome, change language to german, search for "wald".
Result: the layer wald swiss tlm doesn't appear in the result list
Expected: the layer can be found with this search (as it does with edge)

**Comment by davidoesch** [comment]
I assume it’s the same root cause as in https://github.com/geoadmin/mf-geoadmin3/issues/4900

Workaround clear cache and app cache
