### ISSUE TITLE
unable to import wms sub-group

### ISSUE THREAD

**Issue by dkottmann** [geoadmin/mf-geoadmin3#5225]
![grafik](https://user-images.githubusercontent.com/23079469/109763940-2ac8bc80-7bf3-11eb-82af-368095deaa2f.png)

GetCap seems ok and extent is given: https://geodienste.ch/db/planerischer_gewaesserschutz_v1_1_1/deu?SERVICE=WMS&REQUEST=GetCapabilities 

Main group "gewaesserschutzkarte" and single layers are not affected by this issue. 

Issue in WMS or map.geo.admin.ch? @davidoesch ?

**Comment by davidoesch** [comment]
You are on directory /group level
-You need to click on the icon below , to open the group
![image](https://user-images.githubusercontent.com/4577727/109775728-26f06680-7c02-11eb-9ebf-cb1d28216a4e.png)

**Comment by dkottmann** [comment]
@davidoesch 

this sub-group should be importable. it can be requested like any other layer and is answered correctly. 

e.g.:
https://geodienste.ch/db/planerischer_gewaesserschutz_v1_1_1?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&BBOX=2670625,1274321,2694906,1292728&CRS=EPSG:2056&WIDTH=1331&HEIGHT=1009&LAYERS=grundwasserschutzzonen&STYLES=&FORMAT=image/png&DPI=96&MAP_RESOLUTION=96&FORMAT_OPTIONS=dpi:96&TRANSPARENT=TRUE 

this feature (nested groups) was btw explicitly introduced in mapserver due to inspire... 

i think this is a bug on your side. please re-open, look at this again and fix this issue.

**Comment by davidoesch** [comment]
Hmm
All other WMS service do have the same behavior (even WMs.geo.admin.ch)

since this is not a show stopper and we have a code freeze on my-geoadmin we will look into that in Web-mapviewer

**Comment by dkottmann** [comment]
@mariokeusen 
Kannst du etwas zum Stand der Umsetzung dieses Issues sagen? Bleibt das weiterhin auf freeze oder kommt es evtl. für den nächsten major release von map.geo.admin.ch? 
War ja auch Thema am letzten Austausch BAFU-KOGIS-KGK...
