### ISSUE TITLE
CORS Issue while importing data from dropbox

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#5227]
ALL OS ALL devices

Try to download 

https://www.dropbox.com/s/i4qtmflv7vdpfhp/2021-03-04_325666018_TransalpMelsnachScuol.gpx?dl=1

via import
results in

> Access to XMLHttpRequest at 'https://www.dropbox.com/s/i4qtmflv7vdpfhp/2021-03-04_325666018_TransalpMelsnachScuol.gpx?dl=1&SERVICE=WMS&REQUEST=GetCapabilities&VERSION=1.3.0' from origin 'https://map.geo.admin.ch' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

(BTW: as well "*my.sharepoint.com" will be blocked by CORS policy
Expected result

no CORS Issue

workaround: use GIST or gdrive or whatever webspace

**Comment by procrastinatio** [comment]
Strange, the Url is not recognized as a GPX file

**Comment by davidoesch** [comment]
this one is still open after https://github.com/geoadmin/mf-geoadmin3/issues/5229 has been closed will be solved with Always use proxy for external WMTS GetCapabilities #5230

**Comment by davidoesch** [comment]
deployed today
