### ISSUE TITLE
 Upload error for external WMTS ressources

### ISSUE THREAD

**Issue by skitourenguru** [geoadmin/mf-geoadmin3#5229]
Since 5. March 2021 its not possible anymore to import external WMTS ressources to map.geo.admin.ch. When you try to add one of the 2 following external GetCap-Links, there is an upload error:
https://map.skitourenguru.ch/ATHM_GetCapabilities.xml
https://map.slf.ch/public/mapcache/wmts/1.0.0/WMTSCapabilities.xml

Was there an update last friday?

Tested with Chrome and Firefox on Win.

**Comment by skitourenguru** [comment]
There is a problem with CORS at Swisstopo (#5227)
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://map.slf.ch/public/mapcache/wmts/1.0.0/WMTSCapabilities.xml. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing)

**Comment by davidoesch** [comment]
we look into that on monday

**Comment by davidoesch** [comment]
AFAIK: we did not deploy on fridays 
CORS Issues can be reproduced

**Comment by davidoesch** [comment]
Thx

**Comment by skitourenguru** [comment]
The problem applies as well to the accidents of the SLF (Swisstopo-iFrame with referenced KML) under this link:
https://www.slf.ch/de/lawinen/unfaelle-und-schadenlawinen/toedliche-lawinenunfaelle-aktuell.html#tabelement1-tab2

**Comment by skitourenguru** [comment]
On Skitourenguru KML with LineString-Geometry are displayed, KML with Point-Geometry are not displayed. All KML are placed on the same Server. Try this link:

https://map.geo.admin.ch/?topic=ech&notooltip=true&bgLayer=ch.swisstopo.pixelkarte-farbe&E=2682465.37&N=1185538.08&zoom=4&c=3&lang=en&layers=KML%7C%7Chttps:%2F%2Fwww.skitourenguru.ch%2Fcalc_data2%2Fkml%2FSwitzerland_Routes_en.kml%3FTS%3D56082,KML%7C%7Chttps:%2F%2Fwww.skitourenguru.ch%2Fcalc_data2%2Fkml%2FSwitzerland_WebCams.kml%3FTS%3D2670,KML%7C%7Chttps:%2F%2Fwww.skitourenguru.ch%2Fcalc_data2%2Fkml%2FSwitzerland_Segments_en_Route00420.kml%3FTS%3D5383950,KML%7C%7Chttps:%2F%2Fwww.skitourenguru.ch%2Fcalc_data2%2Fkml%2FSwitzerland_Cruxes_en_Route00420.kml%3FTS%3D56082,KML%7C%7Chttps:%2F%2Fwww.skitourenguru.ch%2Fcalc_data2%2Fkml%2FSwitzerland_Symbols_en.kml%3FTS%3D5383950

**Comment by cype** [comment]
hey there. CORS-problem also with KML-imports, see example here: http://www.uvek-gis.admin.ch/BFE/storymaps/WK_SpeicherbareEnergie/

**Comment by davidoesch** [comment]
-root cause identified
-Issue solved (a bug on our side)
- all systems back to normal

**Comment by skitourenguru** [comment]
All works fine now... Thanks a lot for the fast fix.
