### ISSUE TITLE
Broken link in "Ladestationen für Elektroautos" layer description

### ISSUE THREAD

**Issue by edigonzales** [geoadmin/mf-geoadmin3#5282]
"Die Elektromobilität ist eine Schlüsseltechnologie für eine nachhaltigere Mobilität und trägt zur Erreichung ambitionierter energie- und klimapolitischer Ziele bei. Elektroantriebe sind effizient und der Einsatz von Strom erlaubt die Nutzung erneuerbarer Energien. ich-tanke-strom.ch zeigt die Verfügbarkeit von Ladestellen für Elektrofahrzeuge in Echtzeit an. Aktuell werden die Ladestationen der grössten Ladenetzwerke angezeigt. Das BFE lädt weitere interessierte Anbietende von öffentlichen Ladestationen für Elektrofahrzeuge ein, sich anzuschliessen. Weitere Informationen und Liste der angeschlossenen Lade-Netzwerke: https://github.com/SFOE/DIEMO-Documentation"

https://github.com/SFOE/DIEMO scheint nicht mehr zu funktionieren

**Comment by davidoesch** [comment]
@cype und @SFOE via mail informiert muss in geoact.ch geändert werden
