### ISSUE TITLE
Swissimage tiles are failing

### ISSUE THREAD

**Issue by ponceta** [geoadmin/mf-geoadmin3#5296]
I face a swissimage tiles issue this morning :

![image](https://user-images.githubusercontent.com/8614223/218678444-0817cb9d-6f54-4383-834f-62af23acf9e9.png)

Lot of 500 status errors :

![image](https://user-images.githubusercontent.com/8614223/218678561-8b8f596a-9945-4f48-9cc3-b424bdab93c1.png)

Have a good day! :)

**Comment by ponceta** [comment]
Looks fine now! Thank you!

**Comment by davidoesch** [comment]
We had an unfortunate update of our WMTS service.

Root cause identified 

And fixed
