### ISSUE TITLE
KML with Prefixed Namespace return parsing error

### ISSUE THREAD

**Issue by 3l-gee** [geoadmin/mf-geoadmin3#5310]
When Importing a KML file that utilizes prefixed namespaces into Advanced tools/import returns a parsing error. 
When drag and dropping a KML file that utilizes prefixed namespaces returns nothing.

This issue prevents any KML file formatted with prefixed namespaces from being displayed or utilized within map.geo.admin. 

**Eexemples :**  [kml_exemples.zip](https://github.com/geoadmin/mf-geoadmin3/files/14882776/kml_exemples.zip)

 Prefixed Namespace : _kml_exemples/Prefixed_Namespace.kml_
- ✅ Google earth
- ❌map.geo.admin

Default Namespace : _kml_exemples/Default_Namespace.kml_
- ✅ Google earth
- ✅ map.geo.admin

**Comment by ltshb** [comment]
This issue will be fixed in the next generation viewer geoadmin/web-mapviewer
