### ISSUE TITLE
When parcel is selected, add cadastralwebmap layer and highlight parcel

### ISSUE THREAD

**Issue by gjn** [geoadmin/mf-geoadmin3#602]

**Comment by ponceta** [comment]
Form helpdesk:

Die Parzellensuche funktioniert zusammen mit dem Datensatz «CadastralWebMap». Dies ist ein reduzierter Datensatz der amtlichen Vermessung und steht via map.geo.admin.ch frei zur Verfügung.
Die Parzellennummer dürfen wir nicht direkt publizieren, ebenso finden Sie keine Informationen über die Parzellen (z.B. Fläche).
Die Freigabe der Daten der amtlichen Vermessung liegt in der Hoheit der jeweiligen Kantone, für die Nutzung der Daten wenden Sie sich direkt an dieses Stellen.
http://www.cadastre.ch/internet/cadastre/de/home/address/cantons.html

Weitere Informationen zum Datensatz CadastralWebMap erhalten Sie hier:
http://www.cadastre.ch/internet/cadastre/de/home/products/webmap/cwm.html

This means that we do not have to display ANY informations for cadastral-webmaps layer except linking to the cantons geoportals cadastre.
