### ISSUE TITLE
6.2.2 Catalog navigation with keyboard

### ISSUE THREAD

**Issue by mariokeusen** [geoadmin/mf-geoadmin3#617]
OS/Browser: all/all
UC: open app, open the catalog, click to somewhere in the catalog, use the arrow keys to navigate up or down to a layer, press enter in order to load the layer to the map
Result: Catalog does not react on keyboard interaction
Expected: User is able to navigate in the catalog with the arrow keys and to load/unload layers with the enter key

According to @davidoesch this is planned to be implemented.

**Comment by oterral** [comment]
Can we close this? to old to be fixed.

**Comment by loicgasser** [comment]
yes
