### ISSUE TITLE
6.2.15 Tooltip DESKTOP : change mousepointer on mousover  on features with tooltip

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#878]
ALL OS, All DESKTOP Browsers

When a feature of an active layer has a tooltip, change mousepointer on mousover  on features with tooltip (from arrow to a questionmark) ( I know, UTFGrid we dont' have have and won't do)

**Comment by cedricmoullet** [comment]
@davidoesch use case for UTF Grid or we close it ?

**Comment by davidoesch** [comment]
If it can't done with pure ol3 as stated by @gjn above : utfgrid

**Comment by oterral** [comment]
Tis PR lookx very promising for teh feature we want https://github.com/openlayers/ol3/pull/3172

**Comment by davidoesch** [comment]
Yep --- Imho we should go in this direction.
