### ISSUE TITLE
6.3.5  Import & KML : support KMZ

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#935]
all OS all browsers

Since KMZ is just a zipped version of KML: can we adda support for this? or do we have to unzip it on server side, store it and them publish it as kml(which is a no go to store user data)

**Comment by davidoesch** [comment]
any news here @cedricmoullet

**Comment by cedricmoullet** [comment]
@procrastinatio do you see a way to improve that server side ?

**Comment by procrastinatio** [comment]
As stated in my comment (https://github.com/geoadmin/mf-geoadmin3/issues/935#issuecomment-33706477) the KMZ has a style using a local png (in the zipped KMZ). So if you want to be able to use such KMZ in map.geo.admin.ch, you have to:
- Upload the local ressource(s) somewhere (public.geo.admin.ch ?)
- Parse and modify the links in the KML (and event. also upload it, to avoid redoing the manipulation)
So is it OK for you ?

**Comment by gjn** [comment]
To discuss in tomorrows brainstorming session.

**Comment by gjn** [comment]
Discussed during the import re-design.

**Comment by davidoesch** [comment]
a nice to have, since eg https://www.mapplus.ch/?lang=en&basemap=osm&x=628869.79725527&y=153565.00823418&zl=3&hl=0&layers=skiing_nordic|skiing_pisten in map geo does not work

**Comment by gjn** [comment]
by-passing the import via ogcproxy would enable it. So prepend the url with ogcproxy and it should be good.

**Comment by davidoesch** [comment]
https://map.geo.admin.ch/ogcproxy?url=http://www.mapplus.ch/mapimage/kml_mapplus_7ddu9jqrvqq0fgfo82i3f0lqv7.kml 

dos not work (anymore)

**Comment by gjn** [comment]
ogc proxy is on api3...gotta go, but i can prepare a testlink.

**Comment by davidoesch** [comment]
get a bad gateway on https://api3.geo.admin.ch/ogcproxy?url=http://www.mapplus.ch/mapimage/kml_mapplus_7ddu9jqrvqq0fgfo82i3f0lqv7.kml

**Comment by gjn** [comment]
Strange. When I enter the above URL in the search box, kml is loaded, but I don't see anything. Not sure why:
https://map.geo.admin.ch/?topic=ech&lang=de&bgLayer=ch.swisstopo.pixelkarte-grau&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bav.haltestellen-oev,ch.swisstopo.swisstlm3d-wanderwege,KML%7C%7Chttps:%2F%2Fapi3.geo.admin.ch%2Fogcproxy%3Furl%3Dhttp:%2F%2Fwww.mapplus.ch%2Fmapimage%2Fkml_mapplus_7ddu9jqrvqq0fgfo82i3f0lqv7.kml&layers_visibility=false,false,false,false,true&layers_timestamp=18641231,,,,

**Comment by davidoesch** [comment]
Darn

this seems an issue on mapplus: since in google maps I cant open it neither. so those KMZ are not ok

**Comment by gjn** [comment]
@davidoesch How important is this? We shouldn't store external data just to make this work.

We'd like to close this (won't fix).

**Comment by davidoesch** [comment]
Won't fix

**Comment by ponceta** [comment]
:+1:  Good external KMLs should already have their links to hosted data (externally)

**Comment by oterral** [comment]
With [jszip](https://stuk.github.io/jszip/documentation/howto/read_zip.html) we could possibly read the content then display the images available in the zip.

**Comment by procrastinatio** [comment]
@oterral And how do you saved/export it?

**Comment by davidoesch** [comment]
ping @oterral

**Comment by oterral** [comment]
with the same lib. Everything is store as a a blob during the session.

**Comment by boecklic** [comment]
wontfix
